;
; Unify Corporation 2008
; SQLBase INItialization file

; Win32 (Windows 2000, XP and Vista)
;------------------------------------
; This section is for the SQLBase Win32 database server.  You can 
; specify which communication protocol(s) the server can use as well as which 
; protocol(s) a database can use.

[dbntsrv]
dbname=ISLAND
dbname=SBTASK
ANSIJoinSyntax=1
centurydefaultmode=1
servername=water
Password=grahamf
autolocktable=1
batchpriority=1
cache=64000
dbdir=C:\water
tempdir=C:\water

; The default value for readonly is 1, which allows use of "read only" and
; "read committed" (RO and RC) isolation levels.  Uncommenting "readonly=0"
; will disallow use of RO and RC isolation levels.
;readonly=0

; To get process logging, specify a log file and display level.
;log=c:\dbsrv.log 
;displevel=4 


DBNAME=WATERING,SQLWS32
[dbntsrv.gui]

[dbntsrv.dll]
comdll=sqlws32
;comdll=sqlapipe

[dbntsrv.apipe]

[dbntsrv.ws32]
ListenPort=2155

; Win32 (Windows 2000, XP and Vista)
;------------------------------------
; Use this section to specify Win32 client workstation parameters  that  
; are independent of the communications protocol(s) being used.
;
; This section is for the Win32 client workstations. Here you will specify
; the COMmunication DLL(s) that the Win32 application(s) intend to use.
; Use the following protocol(s) to connect to the specified SQLBase product:
;
;	comdll		SQLBase target
;	------		--------------
;	sqlapipe	LOCAL database using Anonymous Pipes
;	sqlws32		REMOTE database using TCP/IP (WinSock)

[win32client]
clientname=Win32User
clientruntimedir="C:\Program Files (x86)\Unify\SQLBase116"
secureapi=0
negotiateapi=0

[win32client.dll]
comdll=sqlws32
;comdll=sqlapipe

[win32client.apipe]
;serverpath=water
autostartserverpath="C:\Program Files (x86)\Unify\SQLBase116\dbntsrv.exe"

[win32client.ws32]
serverpath=water,localhost,2155/*
autostartserverpath="C:\Program Files (x86)\Unify\SQLBase116\dbntsrv.exe" "INI=C:\Program Files (x86)\Unify\SQLBase116\sql.ini" 
