.head 0 +  Application Description: SQLWindows version 5.0 
.data CLASSPROPSSIZE
0000: 4200
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 04000A0000000041 707050617468000A 006B3A5C63656E74 7572610000000000
0040: 0000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF160000 0016000000A60200 004F010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000C819DD0A0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: -0.05"
.head 3 -  Top: 0.01"
.head 3 -  Width:  8.025"
.head 3 -  Height: 5.042"
.head 2 +  Options Box Location
.data VIEWINFO
0000: D4188507B80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.625"
.head 3 -  Top: 3.01"
.head 3 -  Width:  4.175"
.head 3 -  Height: 2.875"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.363"
.head 3 -  Top: 1.188"
.head 2 -  Fully Qualified External References? Yes
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: INTFUNC.APL
.head 2 -  File Include: STDWIND.APL
.head 2 -  File Include: myfunc.apl
.head 2 -  File Include: vtspin.apl
.head 2 -  File Include: vtmeter.apl
.head 2 -  File Include: vtmisc.apl
.head 2 -  File Include: vttblwin.apl
.head 2 -  File Include: JANFLAGS.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: ADDRESS.APL
.head 2 -  File Include: ITEM.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Dialog Box
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Dark Green
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Green
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Dark Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Number: 0000000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: dd-MMM-yyyy hh:mm:ss AMPM
.head 3 -  Date/Time: MMMM, yyyy
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! PAM_Messages in here can only go in range SAM_User + 2000 -> 2099
.head 4 -  Number: PAM_PRINTCONFIRM = SAM_User + 2002
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1788087585
0000: 6E0F0000F6090000 0000000000000000 02000083000000AC 0300001004000000
0020: 037601E8C0030000 0073000000010000 0023B00300190004 0000017601C103BA
0040: 000073D100010000 68C9030019008901 76C203006E007300 34010000E2035A00
0060: 040003A3C4030000 9B7300018D00E603 009619000176E8C5 0300004673000100
0080: 00A3FF0300192500 0176C603BA000073 D100010000681804 000400CD03C9036E
00A0: 0073003601001C04 5A00190001A276CA 0300001B73000100 8D00350400961900
00C0: 0176E8CB03000046 7300010000A34E04 00043500033806B8 00000073D9000100
00E0: 6852040019008901 763906006E007300 340100006B045A00 190001A2763A0600
0100: 001B730001008D00 8404001604000276 01E83B0600006673 000100238804003B
0120: 0102000007760121 0EA0010098060073 C900010000688C04 00040008010276F9
0140: 0E0000FE00C18001 0000003F90049A00 040001A3FA0E0000 7F80F20100008F94
0160: 0400D6040003E085 1200000046730001 0000A39804001925 0001768612BA0000
0180: 73D10001000068B1 0400190089017687 12006E0073003401 0000CA045A000400
01A0: 03A3891200009B73 00018D00CE040096 19000176E88A1200 00467300010000A3
01C0: E704001925000176 8B12BA000073D100 0100006105000004 008D038D12006E00
01E0: 730036010004055A 00190001A2768E12 00001B730001008D 001D050096190001
0200: 76E88F1200004673 0001000023360500 04003500039112BA 000073D900010068
0220: 3A05001900890176 9212006E00730034 01000053055A0019 0001A27693120000
0240: 1B730001008D006C 0500D6040003E895 1200006673000100 A370050019250001
0260: 769612BA000073D1 0001000068890500 1900890176971200 6E00730034010000
0280: A2055A00040003A3 991200009B730001 8D00A60500941900 000176E89A120000
02A0: 467300010000A3BF 050019250001769B 12BA000073D10001 000068D805000400
02C0: 0D03C61400006E00 7300360100DC055A 00190001A276C714 00001B730001008D
02E0: 00F5050096190001 76E8C81400004673 00010000A30E0600 043500032917B800
0300: 000073D900010068 1206001900890176 2A17006E00730034 0100002B065A0004
0320: 0002A32B1700009B 7300018D002F0600 D6040002E82C1700 006673000100A333
0340: 0600043500034517 BA000073D9000100 6837060019008901 764617006E007300
0360: 3401000050065A00 190001A276471700 001B730001008D00 690600D6040003E8
0380: 4917000066730001 00A36D0600192500 01764A17BA000073 D100010000688606
03A0: 0019008901764B17 006E007300340100 009F065A00040003 A34D1700009B7300
03C0: 018D00A306009619 000176E84E170000 467300010000A3BC 060019250001764F
03E0: 17BA000073D10001 000068D506000400 0D031A1800006E00 7300360100D9065A
0400: 00190001A2761B18 00001B730001008D 00F20600D6040002 E81C180000667300
0420: 0100A3F606000435 00021D18BA000073 D900010068FA0600 04008D033618006E
0440: 007300360100FE06 5A00190001A07601 371800001B730001 000D001707000096
0460: 19000176E8381800 00467300010000A3 300700043500033A 18BA000073D90001
0480: 0068340700190089 01763B18006E0073 00340100004D075A 00190001A2763C18
04A0: 00001B730001008D 00660700D6040003 E80D190000667300 0100A36A07001925
04C0: 0001760E19BA0000 73D1000100006883 070019008901760F 19006E0073003401
04E0: 00009C075A000400 03A3491900009B73 00018D00A0070096 19000176E84A1900
0500: 00467300010000A3 B90700043500024B 19BA000073D90001 0068BD070004008D
0520: 024C19006E007300 360100C1075A0004 0003A3661900009B 7300018D00C50700
0540: 9619000176E86719 0000467300010000 A3DE070019250001 766819BA000073D1
0560: 0001000068F70700 04008D036919006E 007300360100FB07 5A00190001A2766A
0580: 1900001B73000100 0D00140800009619 000176E86B190000 467300010000A32D
05A0: 080004350003E419 BA000073D9000100 6831080019008901 76E519006E007300
05C0: 340100004A085A00 190001A276E61900 001B730001008D00 630800D6040003E0
05E0: C51B000000667300 0100A36708001925 000176C61BBA0000 73D1000100006880
0600: 08001900890176C7 1B006E0073003001 00000099085A0004 0003A3C91B00009B
0620: 7300018D009D0800 9619000176E8CA1B 0000467300010000 A3B6080019250001
0640: 76CB1BBA000073D1 0001000068CF0800 04000D032E1C0000 6E007300360100D3
0660: 085A00190001A276 2F1C00001B730001 008D00EC08009619 000176E8301C0000
0680: 4673000100008305 0900000435000332 1CBA000073D90001 0068090900190089
06A0: 0176331C006E0073 003401000022095A 00190001A276341C 00001B730001008D
06C0: 003B0900D6040003 E8F41C0000667300 0100A33F09001925 000176F51CBA0000
06E0: 73D1000100006858 09001900890176F6 1C006E0073003401 000071095A000400
0700: 03A3F81C00009B73 00018D0075090096 19000176E8F91C00 00467300010000A3
0720: 8E09001925000176 FA1CBA000073D100 01000068A7090004 008D03FC1C006E00
0740: 7300360100AB095A 00190001A276FD1C 00001B730001008D 00C4090096190001
0760: 76E8FE1C00004673 00010000A3DD0900 04350003001DB800 000073C900010000
0780: 68E1090019008901 76011D006E007300 34010000FA095A00 190001A276021D00
07A0: 001B730001000D00 130A0000D6040003 E8041D0000667300 0100A3170A001925
07C0: 000176051DBA0000 73D1000100006830 0A00190089017606 1D006E0073003401
07E0: 0000490A5A000400 03A3081D00009B73 00018D004D0A0096 19000176E8091D00
0800: 00467300010000A3 660A001925000176 0A1DBA000073D100 010000687F0A0004
0820: 000D038B1F00006E 007300360100830A 5A00190001A2768C 1F00001B73000100
0840: 8D009C0A00961900 0176E88D1F000046 7300010000A3B50A 00043500038F1FBA
0860: 000073D900010068 B90A001900890176 901F006E00730034 010000D20A5A0019
0880: 0001A276911F0000 1B730001008D00EB 0A00D6040003E001 2000000066730001
08A0: 00A3EF0A00192500 01760220BA000073 D10001000060080B 0000190089017603
08C0: 20006E0073003401 0000210B5A001900 01A2766C2000001B 730001008D003A0B
08E0: 00D6040003E04524 0000006673000100 A33E0B0019250001 764624BA000073D1
0900: 0001000068570B00 1900890176472400 6E00730034010000 700B5A0019000182
0920: 762F260000001B73 0001008D00890B00 9619000176E02C2D 0000004673000100
0940: 00A3A20B00192500 01762D2DBA000073 D10001000068BB0B 0019008901762E2D
0960: 006E007300340100 00D40B5A00190001 A2762F2D00001B73 0001008D00ED0B00
0980: 9619000176E0D037 0000004673000100 0083060C00001925 000176D137BA0000
09A0: 73D100010000681F 0C00190001047601 FE3A00006E007300 360100380C5A0019
09C0: 00018276D8100000 001B730001008D00 510C00D404000003 F40B000066730001
09E0: 00A3550C00192500 01760C00BD0073D1 00010000686E0C00 19000901760D0000
0A00: 006F730034010000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 182316308
0000: 1C0B000037070000 0000000000000000 0200001000FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F08003C00 001663006C73646C
0040: 6751756500727943 737446726D00496E 764E6F400000E000 02000000013B0100
0060: 0000078000010C00 0100980600400073 0000000100060004 0000003B27000701
0080: 0E34000198007393 000100000101806C 0000000102000015 4F7572460272576E
00A0: 6457697400684368 696C645462806CB8 00000006001E0019 0000120001801000
00C0: 0086006803730068 0001000019B30019 0084018011000000 3D6800011A000032
00E0: 00002C0004000380 60011200000068CF 0001060036000000 194B00018013D800
0100: 000068A300010000 C14F000000191200 01800F0000F60068 680001000068B000
0120: 0000040086035C00 000039680300011B 0001806C13000200 0012044F75446C67
0140: 5769FF9F0006BD00 19B500010F8D00B0 0373D10001000066 1900190069018010
0160: 007BB000B4010000 325900040003D901 11009EB000016D00 36009619000180B6
0180: 1200B04700010000 9B4F0019A5000180 13ED00B0D1000100 006468000004000D
01A0: 03140000007BB000 3601000180001D00 0000030000000014 5069636B496E7400
01C0: 6F5461626C655062 9C436C4000E40002 00002D0400038068 01080000EC8C0373
01E0: 0001003600040019 4B00018009D80000 00ECA30001000001 0180D30000000443
0200: 000F4F755F1C4368 5F546147E4010010 7B00040B00028001 1618000000280473
0220: A20000010000CD04 00041A0002170000 F600286C00010008 B200000400860218
0240: 0000003D2800011B 000C0000AC000400 026919000028CF00 0136001000046B00
0260: 021AD800000028B3 000100C914000019 120001801C0000F6 002868000100002D
0280: B00000001900A401 801D00003D280001 1A00004600002C00 19000180611E0000
02A0: 00288F0001000600 5F000000190B0004 800120D800000028 B3000100C1780000
02C0: 0019120001802100 00F6002868000100 0091A10000040000 8602220000003D28
02E0: 00011B00950000AC 0004000261230000 0028CF0001160099 0000194B00018025
0300: D800000028A30001 0000C1B200000019 12000180260000F6 00286800010000CB
0320: B000000004008602 270000003D280001 1B00CF0000AC0004 0002612800000028
0340: CF000106000180BE 0000000005000000 104E65C8774F7543 68F95461D700005B
0360: 040002DB0C001846 04730001006D0004 00D6040002B00D00 000046670001009B
0380: 080004B500020EEC 000046D900010066 0C0004006D020F00 7B4600B601001059
03A0: 00040002DB10009E 4600016D001400D6 040003B611004667 0001009318000004
03C0: B5000312ED0046D9 000100641C000019 0069018014007B46 0034010000350058
03E0: 0000190001CA8015 00001E460001000D 004E000000961900 0180B61600464700
0400: 0100008367000000 19A500018017ED00 46D1000100006280 000004006D021900
0420: 7B46003601008400 580000190001C280 1B0000001E460001 002D009D00009619
0440: 000180B61C004647 0001000083B60000 0004B500021DED00 46D900010060BA00
0460: 000004006D021E00 7B46003601000180 642D00000600180E 4F756F6C75706D6E
0480: 436CB8B200000600 B70400A602050000 315E04730001DA00 0004AC0004000269
04A0: 0600005ECF000136 000800046B000207 D80000005EB30001 00CD0C0004DA0002
04C0: 08F6005E6C000100 10B3000400B60209 003D5E0001DB0014 2C0019000180610A
04E0: 0000005E8F000100 C60001802D080007 0000114F75014461 7461466965F06C64
0500: 436CB3000600B704 00B6020500316A04 730001DA000004AC 000400026D06006A
0520: CF00013600080004 6B000207DB006AB3 000100CD0C0004DA 000208F6006A6C00
0540: 010010B3000400B6 0209003D6A0001DB 00142C0019000180 6D0A006A8F000100
0560: 860001800400CC00 080011C954625175 09446C426F7822A2 0000010000B70400
0580: B6031B0031880473 00011B0001800423 000900000C04636C 636247656E406572
05A0: 616C220000F40100 00D6040002360600 6605647300000100 6301801D00040A00
05C0: 000E634F75015365 61736F6E59206561 7240000002780000 0019EB00011B00BA
05E0: 0573A300010000CD 190004D200028007 F600BA6C00010001 0C8004000B000010
0600: 00134F7552616400 696F427574746F6E 8E43732200E80001 0000AD0400026D06
0620: 00CCCC05730001C6 0001800408000C00 0010636C01546F6F 6C5469700057696E
0640: 646F772200D10001 00005B040003D901 0500910873000001 8D0001801D11000D
0660: 00000D63026C5365 6E64456D6061696C 734000F002000000 D619000137006008
0680: 4673000100009B19 0004A500028006ED 0060D90001001001 801900000E000100
06A0: 0C67774D6F750073 65576865656C22A3 00010000B71900B4 01800A0037730001
06C0: 1A00000180812000 00000F000008E063 514F456D60C00000 0006006F19006D01
06E0: 050063D8087300B4 0100001959001900 01D2800800001ED8 0001006D00320096
0700: 19000180B40B0000 D84700010000834B 00000019A5000180 0EED00D8D1000100
0720: 0060640000001900 69018011007BD800 340100007D001800 0004000102DA8014
0740: 007F80F001000000 0F
.enddata
.head 3 +  Pushbutton Class: clsNewPushbutton
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  0.552"
.head 5 -  Width Editable? Class Default
.head 5 -  Height: 0.552"
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Arial
.head 4 -  Font Size: 8
.head 4 -  Font Enhancement: Bold
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: OurPushbuttonClass
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 -  Message Actions
.head 3 +  Dialog Box Class: clsdlgQueryCstFrmInvNo
.head 4 -  Title: Query Customer By Invoice No
.head 4 -  Accessories Enabled? Yes
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  6.513"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 1.885"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Gray
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 10
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Gray
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbSelect
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 4
.head 7 -  Class: clsNewPushbutton
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Select
.head 7 -  Window Location and Size
.head 8 -  Left: 0.013"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_CLICK
.head 9 +  If NOT bLookedUp
.head 10 -  Call SalSendMsg( pbQuery, SAM_Click, 0, 0 )
.head 9 -  Call PushNumber( dfCustNo )
.head 9 -  Call PushString( dfCustName )
.head 9 -  Call SalEndDialog( hWndForm, TRUE )
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsNewPushbutton
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Query
.head 7 -  Window Location and Size
.head 8 -  Left: 3.225"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: F7
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_CLICK
.head 9 +  If NewGetCustDetailsFromInvNo( dfInvoiceNo, dfCustNo, dfCustName, SH_cls_Execute )
.head 10 -  Set bLookedUp = TRUE
.head 9 +  Else
.head 10 -  Set bLookedUp = FALSE
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsNewPushbutton
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Exit
.head 7 -  Window Location and Size
.head 8 -  Left: 5.825"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: F12
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_CLICK
.head 9 -  Call SalEndDialog( hWndForm, 0 )
.head 4 +  Contents
.head 5 -  Background Text: Invoice No.
.head 6 -  Resource Id: 63702
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 1
.head 6 -  Class:
.head 6 -  Window Location and Size
.head 7 -  Left: 1.938"
.head 7 -  Top: 0.188"
.head 7 -  Width:  1.0"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.167"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Justify: Right
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Blue
.head 6 -  Background Color: Gray
.head 5 +  Data Field: dfInvoiceNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 2
.head 6 -  Class:
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Default
.head 7 -  Data Type: Number
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.0"
.head 8 -  Top: 0.146"
.head 8 -  Width:  1.625"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: #0
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: White
.head 7 -  Input Mask: Unformatted
.head 6 -  Message Actions
.head 5 -  Background Text: Cust.No.
.head 6 -  Resource Id: 63703
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 7
.head 6 -  Class:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.1"
.head 7 -  Top: 0.667"
.head 7 -  Width:  0.825"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.167"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Justify: Right
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Gray
.head 5 +  Data Field: dfCustNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 8
.head 6 -  Class:
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Default
.head 7 -  Data Type: Number
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 1.013"
.head 8 -  Top: 0.625"
.head 8 -  Width:  0.825"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: #0
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: White
.head 7 -  Input Mask: Unformatted
.head 6 -  Message Actions
.head 5 -  Background Text: Cust.Name
.head 6 -  Resource Id: 63704
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class:
.head 6 -  Window Location and Size
.head 7 -  Left: 1.913"
.head 7 -  Top: 0.667"
.head 7 -  Width:  1.013"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.167"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Justify: Right
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Gray
.head 5 +  Data Field: dfCustName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 10
.head 6 -  Class:
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Default
.head 7 -  Data Type: String
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.0"
.head 8 -  Top: 0.625"
.head 8 -  Width:  3.238"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Unformatted
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: White
.head 7 -  Input Mask: Unformatted
.head 6 -  Message Actions
.head 4 -  Derived From
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Boolean: bLookedUp
.head 4 +  Functions
.head 5 +  Function: NewGetCustDetailsFromInvNo
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nInvNo
.head 7 -  Receive Number: nCustNo
.head 7 -  Receive String: sCustName
.head 7 -  Number: nActionType
.head 6 +  Static Variables
.head 7 -  FunctionalVar: fcOurHandle
.head 8 -  Class: hcSqlHandle
.head 7 -  FunctionalVar: fcOurHistHandle
.head 8 -  Class: hcSqlHandle
.head 6 +  Local variables
.head 7 -  String: sSql
.head 7 -  String: sBind
.head 7 -  String: sInto
.head 7 -  String: sName
.head 7 -  Number: nInd
.head 7 -  !
.head 7 -  Number: nGotCustNo
.head 7 -  String: sGotCustName
.head 6 +  Actions
.head 7 +  Select Case nActionType
.head 8 +  Case SH_cls_Execute
.head 9 -  Set sSql = ' SELECT 
  Transaction.Cust_No, 
  Customer_Master.Cust_Name 
FROM 
  Customer_Master, 
  Transaction  
WHERE 
  Transaction.Reference_Id = :1 AND 
  Transaction.Cust_No = Customer_Master.Cust_No '
.head 9 -  Set sName = 'GETINVCSTNUM'
.head 9 -  Set sBind = ':nInvNo'
.head 9 -  Set sInto = ':nGotCustNo, :sGotCustName'
.head 9 -  Call fcOurHandle.Setup( sSql, sName, sBind, sInto )
.head 9 -  Call SqlVarSetup( fcOurHandle.hSqlHandle )
.head 9 -  !
.head 9 -  Set sSql = ' SELECT 
  Trans_History.Cust_No, 
  Customer_Master.Cust_Name 
FROM 
  Customer_Master, 
  Trans_History  
WHERE 
  Trans_History.Hist_Reference_Id = :1 AND 
  Trans_History.Cust_No = Customer_Master.Cust_No '
.head 9 -  Set sName = 'GETHINVCSTNUM'
.head 9 -  Set sBind = ':nInvNo'
.head 9 -  Set sInto = ':nGotCustNo, :sGotCustName'
.head 9 -  Call fcOurHistHandle.Setup( sSql, sName, sBind, sInto )
.head 9 -  Call SqlVarSetup( fcOurHistHandle.hSqlHandle )
.head 9 -  !
.head 9 -  Set nGotCustNo = NUMBER_Null
.head 9 -  Set sGotCustName = ''
.head 9 -  Set nCustNo = NUMBER_Null
.head 9 -  Set sCustName = ''
.head 9 -  !
.head 9 +  If fcOurHandle.Execute( )
.head 10 +  If fcOurHandle.FetchNext( nInd )
.head 11 -  Set nCustNo = nGotCustNo
.head 11 -  Set sCustName = sGotCustName
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 +  If fcOurHistHandle.Execute( )
.head 12 +  If fcOurHistHandle.FetchNext( nInd )
.head 13 -  Set nCustNo = nGotCustNo
.head 13 -  Set sCustName = sGotCustName
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 9 +  Else
.head 10 -  Return FALSE
.head 8 +  Case SH_cls_Disconnect
.head 9 -  Call fcOurHandle.Disconnect( )
.head 9 -  Call fcOurHistHandle.Disconnect( )
.head 9 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set bLookedUp = FALSE
.head 5 +  On SAM_CreateComplete
.head 6 -  Call SalWaitCursor( FALSE )
.head 5 +  On SAM_Destroy
.head 6 -  Call NewGetCustDetailsFromInvNo( 0, dfCustNo, dfCustName, SH_cls_Disconnect )
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control: cSpinField
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  ! Dialog Box: dlgApplyDate
.winattr
.head 2 -  Class:
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Apply Date To Be Used
.head 2 -  Accessories Enabled? No
.head 2 -  Visible? Yes
.head 2 -  Display Settings
.head 3 -  Display Style? Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 2.238"
.head 4 -  Top: 2.083"
.head 4 -  Width:  5.0"
.head 4 -  Width Editable? Yes
.head 4 -  Height: 1.875"
.head 4 -  Height Editable? Yes
.head 3 -  Absolute Screen Location? Yes
.head 3 -  Font Name: Default
.head 3 -  Font Size: Default
.head 3 -  Font Enhancement: Default
.head 3 -  Text Color: Default
.head 3 -  Background Color: Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.end
.head 2 -  Description: 
.head 2 +  Tool Bar 
.winattr
.head 3 -  Display Settings
.head 4 -  Display Style? Default
.head 4 -  Location? Top
.head 4 -  Visible? Yes
.head 4 -  Size: Default
.head 4 -  Size Editable? Yes
.head 4 -  Docking Toolbar? No
.head 4 -  Toolbar Docking Orientation: Top | Bottom
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Resizable? No
.end
.head 3 -  Contents 
.head 2 +  Contents 
.head 3 +  Pushbutton: pbOk
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Ok
.head 4 -  Window Location and Size
.head 5 -  Left: 1.788"
.head 5 -  Top: 1.073"
.head 5 -  Width:  1.0"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.292"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Keyboard Accelerator: (none)
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: None
.head 4 -  Image Style: Single
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Button Appearance: Standard
.end
.head 4 +  Message Actions 
.head 5 +  On SAM_Click
.head 6 +  If SalIsNull( dfApplyDate )
.head 7 -  Call SalMessageBox( 'Please enter a date to be used for applying', 'Cash Receipts', MB_Ok )
.head 7 -  Return FALSE
.head 6 -  Set dtApplyDate = dfApplyDate
.head 6 -  Call SalEndDialog( dlgApplyDate, TRUE )
.head 3 -  Frame 
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 1.588"
.head 5 -  Top: 0.99"
.head 5 -  Width:  1.4"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.5"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Corners: Square
.head 4 -  Border Style: Solid
.head 4 -  Border Thickness: 1
.head 4 -  Border Color: Default
.head 4 -  Background Color: Default
.end
.head 3 -  Background Text: Please enter the apply date to
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.188"
.head 5 -  Top: 0.281"
.head 5 -  Width:  2.3"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Left
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.end
.head 3 -  Background Text: to be used for this instance
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.288"
.head 5 -  Top: 0.448"
.head 5 -  Width:  2.2"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Left
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.end
.head 3 -  Background Text: of this program
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 1.188"
.head 5 -  Top: 0.615"
.head 5 -  Width:  1.3"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Left
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.end
.head 3 +  Data Field: dfApplyDate
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Date/Time
.head 5 -  Editable? Yes
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 2.588"
.head 6 -  Top: 0.323"
.head 6 -  Width:  1.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Justify: Left
.head 5 -  Format: dd-MMM-yyyy
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Midnight Blue
.head 5 -  Background Color: Default
.head 5 -  Input Mask: Unformatted
.end
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 +  Window Parameters 
.head 3 -  Receive Date/Time: dtApplyDate
.head 2 -  Window Variables 
.head 2 +  Message Actions 
.head 3 +  On SAM_CreateComplete
.head 4 -  Set dfApplyDate = SalDateCurrent(  )
.head 1 -  ! Making the assumption that the next 2 dialogs are only being called by the transaction program
.head 1 +  Dialog Box: dlgGetDate
.head 2 -  Class: Our_Dialog_Box
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.638"
.head 4 -  Top: 1.365"
.head 4 -  Width:  4.713"
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 1.781"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbCancel
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurPushbuttonClass
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.45"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: OK.BMP
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 +  Message Actions
.head 6 +  On PAM_CLICK
.head 7 +  If SalModalDialog( dlgVerify, hWndForm, dfDate )
.head 8 -  Call SalWaitCursor( TRUE )
.head 8 -  Call PushDateTime( dfDate )
.head 8 -  Call SalEndDialog( hWndForm, TRUE )
.head 7 +  Else
.head 8 -  Return FALSE
.head 2 +  Contents
.head 3 -  Background Text: Please enter a Date
.head 4 -  Resource Id: 26731
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.1"
.head 5 -  Top: 0.531"
.head 5 -  Width:  1.688"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Center
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: 3D Face Color
.head 3 +  Data Field: dfDate
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Date/Time
.head 5 -  Editable? Yes
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 1.838"
.head 6 -  Top: 0.49"
.head 6 -  Width:  1.425"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Justify: Center
.head 5 -  Format: dd-MMM-yyyy
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Input Mask: Unformatted
.head 4 -  Message Actions
.head 3 +  ! Pushbutton: pbOk
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: O&k - Enter
.head 4 -  Window Location and Size
.head 5 -  Left: 0.225"
.head 5 -  Top: 0.927"
.head 5 -  Width:  1.575"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.292"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Keyboard Accelerator: Enter
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: None
.head 4 -  Image Style: Single
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Button Appearance: Standard
.end
.head 4 +  Message Actions 
.head 5 +  On SAM_Click
.head 6 +  If SalModalDialog( dlgVerify, hWndForm, dfDate )
.head 7 -  Call SalWaitCursor( TRUE )
.head 7 -  Call PushDateTime( dfDate )
.head 7 -  Call SalEndDialog( hWndForm, TRUE )
.head 6 +  Else 
.head 7 -  Return FALSE
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCurrentDate
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  String: sHeading
.head 3 -  Date/Time: dtDate
.head 2 -  Window Variables
.head 2 +  Message Actions
.head 3 +  On SAM_CreateComplete
.head 4 -  Call SalSetWindowText( hWndForm, sHeading )
.head 4 +  If dtDate = DATETIME_Null
.head 5 -  Set dfDate = dfCurrentDate
.head 4 +  Else
.head 5 -  Set dfDate = dtDate
.head 4 -  Call SalWaitCursor( FALSE )
.head 1 +  Dialog Box: dlgVerify
.head 2 -  Class: Our_Dialog_Box
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Verify
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.925"
.head 4 -  Top: 2.771"
.head 4 -  Width:  5.338"
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 2.198"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbCancel
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurPushbuttonClass
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.45"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: OK.BMP
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 +  Message Actions
.head 6 +  On PAM_CLICK
.head 7 -  Call SalEndDialog( hWndForm, TRUE )
.head 2 +  Contents
.head 3 +  Data Field: dtVerifyDate
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdfGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Date/Time
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 2.175"
.head 6 -  Top: 0.51"
.head 6 -  Width:  2.325"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: MMMM, yyyy
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text: Please verify that the
.head 4 -  Resource Id: 26609
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.163"
.head 5 -  Top: 0.365"
.head 5 -  Width:  1.8"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Left
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 3 -  Background Text: month required is:
.head 4 -  Resource Id: 26610
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.438"
.head 5 -  Top: 0.542"
.head 5 -  Width:  1.55"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Left
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 3 +  ! Pushbutton: pbOk
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Ok - Enter
.head 4 -  Window Location and Size
.head 5 -  Left: 0.325"
.head 5 -  Top: 1.208"
.head 5 -  Width:  1.363"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.292"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Keyboard Accelerator: Enter
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Italic
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: None
.head 4 -  Image Style: Single
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Button Appearance: Standard
.end
.head 4 +  Message Actions 
.head 5 +  On SAM_Click
.head 6 -  Call SalEndDialog( hWndForm, TRUE )
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCurrentDate
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  Date/Time: dtRolloverDate
.head 2 -  Window Variables
.head 2 +  Message Actions
.head 3 +  On SAM_CreateComplete
.head 4 -  Set dtVerifyDate = dtRolloverDate
.head 1 +  Dialog Box: dlgGetDateSelect
.head 2 -  Class: Our_Dialog_Box
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.638"
.head 4 -  Top: 1.365"
.head 4 -  Width:  4.525"
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 2.104"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbCancel
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurPushbuttonClass
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.45"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: OK.BMP
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 +  Message Actions
.head 6 +  On PAM_CLICK
.head 7 +  If SalModalDialog( dlgVerify, hWndForm, dfDate )
.head 8 -  Call SalWaitCursor( TRUE )
.head 8 -  Call PushDateTime( dfDate )
.head 8 -  Call SalEndDialog( hWndForm, TRUE )
.head 7 +  Else
.head 8 -  Return FALSE
.head 2 +  Contents
.head 3 -  Background Text: Please enter a Date
.head 4 -  Resource Id: 6300
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.1"
.head 5 -  Top: 0.427"
.head 5 -  Width:  1.688"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Center
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: 3D Face Color
.head 3 +  Data Field: dfDate
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Date/Time
.head 5 -  Editable? Yes
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 1.825"
.head 6 -  Top: 0.385"
.head 6 -  Width:  1.425"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Justify: Center
.head 5 -  Format: dd-MMM-yyyy
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Input Mask: Unformatted
.head 4 -  Message Actions
.head 3 +  Radio Button: rbAllCustomers
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: All Customers
.head 4 -  Window Location and Size
.head 5 -  Left: 1.813"
.head 5 -  Top: 0.698"
.head 5 -  Width:  1.513"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: 3D Face Color
.head 4 +  Message Actions
.head 5 +  ! On SAM_Create
.head 6 -  Set nType = nAllCustomers
.head 5 +  On SAM_Click
.head 6 -  Set nType = nAllCustomers
.head 5 +  On PAM_DISABLECUSTCHOICE
.head 6 -  Call SalDisableWindow( hWndItem )
.head 3 +  Radio Button: rbSelectedCustomers
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Selected Customers
.head 4 -  Window Location and Size
.head 5 -  Left: 1.8"
.head 5 -  Top: 0.99"
.head 5 -  Width:  2.0"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: 3D Face Color
.head 4 +  Message Actions
.head 5 +  On SAM_Click
.head 6 -  Set nType = nSelectedCustomers
.head 5 +  On PAM_DISABLECUSTCHOICE
.head 6 -  Call SalDisableWindow( hWndItem )
.head 6 -  Set rbSelectedCustomers = TRUE
.head 6 -  Set nType = wParam
.head 3 +  ! Pushbutton: pbOk
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: O&k - Enter
.head 4 -  Window Location and Size
.head 5 -  Left: 0.225"
.head 5 -  Top: 1.323"
.head 5 -  Width:  1.575"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.292"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Keyboard Accelerator: Enter
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: None
.head 4 -  Image Style: Single
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Button Appearance: Standard
.end
.head 4 +  Message Actions 
.head 5 +  On SAM_Click
.head 6 +  If SalModalDialog( dlgVerify, hWndForm, dfDate )
.head 7 -  Call SalWaitCursor( TRUE )
.head 7 -  Call PushDateTime( dfDate )
.head 7 -  Call SalEndDialog( hWndForm, TRUE )
.head 6 +  Else 
.head 7 -  Return FALSE
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCurrentDate
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  String: sHeading
.head 3 -  Date/Time: dtDate
.head 3 -  Receive Number: nType
.head 2 +  Window Variables
.head 3 -  ! Number: nType
.head 2 +  Message Actions
.head 3 +  On SAM_CreateComplete
.head 4 -  Call SalSetWindowText( hWndForm, sHeading )
.head 4 -  Set dfCurrentDate = SalDateCurrent(  )
.head 4 +  If dtDate = DATETIME_Null
.head 5 -  Set dfDate = dfCurrentDate
.head 4 +  Else
.head 5 -  Set dfDate = dtDate
.head 4 +  If nType = nSelectedCustomers
.head 5 -  Set rbSelectedCustomers = TRUE
.head 4 +  Else
.head 5 -  Set rbAllCustomers = TRUE
.head 4 -  Call SalWaitCursor( FALSE )
.head 3 +  On PAM_SETINSTANCEVARS
.head 4 -  Set sDatabase = SqlDatabase
.head 1 +  Dialog Box: dlgGetSummaryDates
.head 2 -  Class: Our_Dialog_Box
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Date Range
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.55"
.head 4 -  Top: 1.115"
.head 4 -  Width:  5.0"
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 2.302"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbCancel
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurPushbuttonClass
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.225"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Enter
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: OK.BMP
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 +  Message Actions
.head 6 +  On PAM_CLICK
.head 7 -  Call PushDateTime( dfFromDate )
.head 7 -  Call PushDateTime( dfToDate )
.head 7 -  Call SalSendMsg( pbCancel, SAM_Click, 0, TRUE )
.head 2 +  Contents
.head 3 -  Background Text: From Date
.head 4 -  Resource Id: 26732
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.05"
.head 5 -  Top: 0.479"
.head 5 -  Width:  0.963"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Center
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: 3D Face Color
.head 3 -  Background Text: To Date
.head 4 -  Resource Id: 26733
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 2.45"
.head 5 -  Top: 0.49"
.head 5 -  Width:  0.963"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Center
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: 3D Face Color
.head 3 +  Data Field: dfFromDate
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Date/Time
.head 5 -  Editable? Yes
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 1.05"
.head 6 -  Top: 0.438"
.head 6 -  Width:  1.363"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Justify: Left
.head 5 -  Format: dd-MMM-yyyy
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Dark Blue
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Unformatted
.head 4 -  Message Actions
.head 3 +  Data Field: dfToDate
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: Date/Time
.head 5 -  Editable? Yes
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 3.438"
.head 6 -  Top: 0.448"
.head 6 -  Width:  1.363"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Justify: Left
.head 5 -  Format: dd-MMM-yyyy
.head 5 -  Country: Default
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Dark Blue
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Unformatted
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCurrentDate
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 +  Window Variables
.head 3 -  String: sYear
.head 3 -  Number: nYear
.head 2 +  Message Actions
.head 3 +  On PAM_SETINSTANCEVARS
.head 4 -  Set sDatabase = SqlDatabase
.head 3 +  On SAM_CreateComplete
.head 4 -  Set dfFromDate = SalDateConstruct( SalDateYear( dfCurrentDate ), SalDateMonth( dfCurrentDate ), 1, 0, 0, 0 )
.head 4 -  Set dfToDate = SalDateConstruct( SalDateYear( dfCurrentDate ), SalDateMonth( dfCurrentDate ), 31, 0, 0, 0 )
.head 4 -  Call SalWaitCursor( FALSE )
.head 1 +  Dialog Box: dlgQueryCstFrmInvNo
.head 2 -  Class: clsdlgQueryCstFrmInvNo
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.663"
.head 4 -  Top: 1.885"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbSelect
.head 5 -  Class Child Ref Key: 4
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCstFrmInvNo
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.521"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 5
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCstFrmInvNo
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.521"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCstFrmInvNo
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.521"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 63705
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCstFrmInvNo
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfInvoiceNo
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCstFrmInvNo
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 63706
.head 4 -  Class Child Ref Key: 7
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCstFrmInvNo
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCustNo
.head 4 -  Class Child Ref Key: 8
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCstFrmInvNo
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 63707
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCstFrmInvNo
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCustName
.head 4 -  Class Child Ref Key: 10
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCstFrmInvNo
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
