.head 0 +  Application Description: SQLWindows version 5.01
.data CLASSPROPSSIZE
0000: 4200
.enddata
.data CLASSPROPS
0000: 4170705061746800 0A006B3A5C63656E 7475726100417070 506174684C656E00
0020: 04000A0000000055 7365476C6F62616C 5061746800040001 0000000000000000
0040: 0000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000F40000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF6AFFFF FF010000007E0200 00A0010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000C819DD0A0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: -0.05"
.head 3 -  Top: 0.01"
.head 3 -  Width:  8.025"
.head 3 -  Height: 5.042"
.head 2 +  Options Box Location
.data VIEWINFO
0000: D4188507B80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.613"
.head 3 -  Top: 3.031"
.head 3 -  Width:  4.175"
.head 3 -  Height: 2.844"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 7.163"
.head 3 -  Top: 1.958"
.head 2 -  Fully Qualified External References? Yes
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: myfunc.apl
.head 2 -  File Include: intfunc.apl
.head 2 -  File Include: vtspin.apl
.head 2 -  File Include: vtmeter.apl
.head 2 -  File Include: vtmisc.apl
.head 2 -  File Include: vttblwin.apl
.head 2 -  File Include: tgroups.apl
.head 2 -  File Include: strings.apl
.head 2 -  File Include: JANFLAGS.APL
.head 2 -  File Include: ADDRESS.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 +  Select From: STDWIND.APL
.head 3 -  Constants
.head 2 -  File Include: STDWIND.APL
.head 2 +  Select From: CSTINREG.APL
.head 3 -  Constants
.head 2 -  File Include: ITEM.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Dialog Box
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Dark Green
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Green
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Dark Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Number: 0000000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: dd-MMM-yyyy hh:mm:ss AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! PAM_Messages in here can only go in range SAM_User + 3200 -> 3299
.head 4 -  !
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 750849819
0000: CE1B0000F8080000 0000000000000000 0200001101000035 020000E003040000
0020: 00FF3F3902820001 0D000000FFFFE846 020001FE00FFA353 020003FB00FF8F57
0040: 0200EE0100FF3F64 02BA000100FFFFE8 71020003FE00FFA3 75020001FB00FF8F
0060: 820200EE0100FF3F 8F02BA000300FFFF E893020001FE00FF A3A0020001FB00FF
0080: 8FAD0200E8020400 00FF3FB102BA0002 00FFFFE8B5020002 FE00FFA3B9020001
00A0: FB00FF8FC60200EE 0100FF3FD302BA00 0100FFFFE8E00200 01FE00FFA3ED0200
00C0: 03FB00FF8FF10200 EE0200FF3FF502BA 000100FFFFE00203 000001FE00FFA30F
00E0: 030001FB00FF8F1C 0300EC020400FF3F 2003BA000200FFFF E824030002FE00FF
0100: A328030001FB00FF 8F350300EE0100FF 3F4203A200040D00 00FFFFE84F030001
0120: FE00FFA35C030002 FB00FF8F600300EE 0200FF3F64033A00 020001FA00000780
0140: 01000000FFE86803 0002EC0001009F80 01FC0000A36C0300 03FB00FF8F700300
0160: EC010D00FF3F7D03 BA000100FFFFE88A 030003FE00FFA38E 030001FB00FF8F9B
0180: 0300EE0100FF3FA8 03BA000300FFFFE8 AC030001FE00FFA3 B9030001FB00FF8F
01A0: C60300EE0300FF3F CA03BA000100FFFF E8D7030001FE00FF A3E4030003FB00FF
01C0: 8FE80300EE0100FF 3FF503BA000100FF FFEE0203FE00FFA3 06040001FB00FF8F
01E0: 130400EE0100FF3F 2004BA000300FFFF E824040001FE00FF A331040001FB00FF
0200: 8F3E0400EE0300FF 3F4204BA000100FF FFE84F040002FE00 FFA353040002FB00
0220: FF8F570400EE0300 FF3F5B04BA000100 FFFFE868040001FE 00FFA375040003FB
0240: 00FF8F790400EE01 00FF3F8604BA0001 00FFFFE893040003 FE00FFA397040001
0260: FB00FF8FA40400EE 0100FF3FB104BA00 0300FFFFE8B50400 01FE00FFA3C20400
0280: 02FB00FF8FC60400 EE0200FF3FCA04BA 000300FFFFE8CE04 0001FE00FFA3DB04
02A0: 0001FB00FF8FE804 00EE0300FF3FEC04 BA000100FFFFE8F9 040001FE00FF8306
02C0: 05000003FB00FF8F 0A0500EE0100FF3F 1705BA000100FFFF E824050003FE00FF
02E0: A328050001FB00FF 8F350500EE0200FF 3F3905BA000200FF FFE83D050003FE00
0300: FFA341050001FB00 FF8F4E0500EE0100 FF3F5B05BA000300 FFFFE85F050001FE
0320: 00FFA36C050001FB 00FF8F790500EE03 00FF3F7D05BA0001 00FFFFE88A050001
0340: FE00FFA397050003 FB00FF8F9B0500EE 0100FF3FA805BA00 0100FFFFE8B50500
0360: 03FE00FFA3B90500 01FB00FF8FC60500 EE0100FF3FD305BA 000300FFFFE8D705
0380: 0001FE00FFA3E405 0001FB00FF8FF105 00EE0300FF3FF505 BA000100FFFFE002
03A0: 06000001FE00FFA3 0F060003FB00FF8F 130600EE0100FF3F 2006BA000100FFFF
03C0: E82D060003FE00FF A331060001FB00FF 8F3E0600EE0100FF 3F4B06BA000300FF
03E0: FFE84F060001FE00 FFA35C060001FB00 FF8F690600EE0300 FF3F6D06BA000100
0400: FFFFE87A060001FE 00FFA387060003FB 00FF8F8B0600EE01 00FF3F9806BA0001
0420: 00FFFFE8A5060003 FE00FFA3A9060001 FB00FF8FB60600EE 0100FF3FC306BA00
0440: 0300FFFFE8C70600 01FE00FFA3D40600 01FB00FF8FE10600 EE0300FF3FE506BA
0460: 000100FFFFE8F206 0001FE00FFA3FF06 0003FB00FF0F0307 0000EE0100FF3F10
0480: 07BA000100FFFFE8 1D070001FE00FF23 2A07000304FB00FF 8F2E0700EE0100FF
04A0: 3F3B07BA000100FF FFE848070003FE00 FFA34C070001FB00 FF8F590700EE0100
04C0: FF3F6607BA000300 FFFFE86A070001FE 00FFA377070001FB 00FF8F840700EE03
04E0: 00FF3F8807BA0001 00FFFFE895070001 FE00FFA3A2070003 FB00FF8FA60700EE
0500: 0100FF3FB307BA00 0100FFFFE8C00700 01FE00FFA3CD0700 01FB00FF8FDA0700
0520: EE0300FF3FDE07BA 000100FFFFE8EB07 0001FE00FFA3F807 0001FB00FF0F0508
0540: 0000EE0100FF3F12 08BA000300FFFFE8 16080001FE00FFA3 23080001FB00FF8F
0560: 300800EE0100FF3F 3D08BA000100FFFF E84A080003FE00FF A34E080001FB00FF
0580: 8F5B0800EE0100FF 3F6808BA000100FF FFE875080001FE00 FFA382080003FB00
05A0: FF8F860800EE0100 FF3F9308BA000100 FFFFE8A0080001FE 00FFA3AD080001FB
05C0: 00FF8FBA0800EE01 00FF3FC708BA0003 00FFFFE8CB080001 FE00FFA3D8080001
05E0: FB00FF8FE50800EE 0100FF3FF208BA00 0100FFFFE8FF0800 01FE00FF830C0900
0600: 0001FB00FF8F1909 00EE0100FF3F2609 BA000100FFFFE833 090004FE00FFA340
0620: 090001FB00FF8F4D 0900EE0300FF3F51 09BA000100FFFFE8 5E090001FE00FF23
0640: 6B09000204FB00FF 8F6F0900EE0200FF 3F7309BA000100FF FFE880090001FE00
0660: FFA38D090001FA00 00FF8F9A0900EE01 00FF3FA709BA0003 00FFFFE8AB090002
0680: FE00FFA3AF090001 FB00FF8FBC0900EE 0100FF3FC909BA00 0100FFFFE8D60900
06A0: 02FE00FFA3DA0900 02FB00FF8FDE0900 EE0200FF3FE209BA 000100FFFFE8EF09
06C0: 0001FE00FFA3FC09 0004FB00FF0F090A 0000EE0100FF3F16 0ABA000200FFFFE8
06E0: 1A0A0002FE00FFA3 1E0A0002FB00FF8F 220A00EE0200FF3F 260ABA000100FFFF
0700: E8330A0001FE00FF A3400A0001FB00FF 8F4D0A00EE0100FF 3F5A0ABA000300FF
0720: FFE85E0A0002FE00 FFA3620A0001FB00 FF8F6F0A00EE0100 FF3F7C0ABA000100
0740: FFFFE8890A0002FE 00FFA38D0A0002FB 00FF8F910A00EE02 00FF3F950AAA0001
0760: 0000FFFFE8A20A00 01FE00FFA3AF0A00 04FB00FF8FBC0A00 EE0100FF3FC90ABA
0780: 000200FFFFE8CD0A 0002FE00FFA3D10A 0002FB00FF8FD50A 00EE0200FF3FD90A
07A0: BA000100FFFFE8E6 0A0001FE00FFA3F3 0A0001FB00FF1F0B 0000EE0100FF3F0D
07C0: 0BBA000300FFFFE8 110B0002FE00FFA3 150B0001FB00FF8F 220B00EE0100FF3F
07E0: 2F0BBA000100FFFF E83C0B0002FE00FF A3400B0002FB00FF 8F440B00EE0200FF
0800: 3F480BBA000100FF FFE8550B0001FE00 FFA3620B0004FB00 FF8F6F0B00EE0100
0820: FF3F7C0BBA000200 FFFFE8800B0002FE 00FFA3840B0002FB 00FF8F880B00EE02
0840: 00FF3F8C0BBA0001 00FFFFE8990B0001 FE00FFA3A60B0001 FB00FF8FB30B00EE
0860: 0100FF3FC00BBA00 0300FFFFE8C40B00 02FE00FFA3C80B00 01FB00FF8FD50B00
0880: EE0100FF3FE20BBA 000100FFFFE8EF0B 0002FE00FFA3F30B 0002FB00FF8FF70B
08A0: 00EE0200FF3FFB0B BA000100FFFFE008 0C000001FE00FFA3 150C0004FB00FF8F
08C0: 220C00EE0100FF3F 2F0CBA000200FFFF E8330C0002FE00FF A3370C0003FB00FF
08E0: 8F3B0C00EE0100FF 3F480CBA000100FF FFE8550C0003FE00 FFA3590C0001FB00
0900: FF8F660C00EE0100 FF3F
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1938710113
0000: 930900003F040000 0000000000000000 0200000F00FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F3C003C00 00154F0075724672
0040: 6D576E6400576974 684368696C006454 626CA0000000F006 000000E0010D0000
0060: 00FF3F0D00B90001 00FFFF001A000000 03040000FE00FF83 1E00000001FB00FF
0080: 0F2B000000EE0100 FF3F3800B8000003 00FFFF1001803C00 000100200000124F
00A0: 75446CF8675769FF EC000600D9010D00 FF7F0D73000100FF FFCD1A0003FD00FF
00C0: 371E0001F700FFDF 2BDC000100FF7F38 73000300FFFF0101 8011000000020000
00E0: 0000145069636B00 496E746F5461626C E0655062436C6438 00000200EF03FE00
0100: FF13040000010DFB 00FF0F01807F0000 0000030000000F4F E2755F4368385F54
0120: 61A401C200100000 00A302040000FFFF E6040002FE00FF83 0800000002FB00FF
0140: 0F0C000000EE0200 FFBF10B9000200FF FFC014000000010D FE00FF8321000000
0160: 01FB00FF0F2E0000 00EE0100FF3F3B00 A00000040D0000FF FFE04800000001FE
0180: 00FF835500000002 FB00FF0F59000000 EE0200FF3F5D00B8 00000100FFFFE06A
01A0: 00000001FE00FF83 7700000002FB00FF 0F7B000000EE0200 FF3F018040760000
01C0: 0004000040104E65 774F7543CE685461 BF00DE0002FD00FF 37040002F700FFDF
01E0: 08DC000200FF7F0C 73000200FFFFCD10 0002FD00FF371400 03F60400FF1F1800
0200: 00DC000300FF7F1C 60000000010D00FF FFC12900000001FD 00FF073600000001
0220: F700FF1F430000DC 000100FF7F507000 00000200FFFFC154 00000001FD00FF07
0240: 6100000001F700FF 1F6E0000DC000200 FF7F727000000002 00FFFF2101802100
0260: 0005C00000000E4F 75806F6C756D6E43 6C93A0000006BD00 02FB00FF6F0400EE
0280: 0200FFBF08B90002 00FFFFE60C0002FE 00FF9B100002FB00 FF6F1400EC010D00
02A0: FF3F018066210006 0008114F75446174 61804669656C6443 6C9F0006BD0002FB
02C0: 00FF6F0400EE0200 FFBF08B9000200FF FFE60C0002FE00FF 9B100002FB00FF6F
02E0: 1400EC010D00FF3F 0180040400000700 00004E1154625140 75657279446C4210
0300: 6F781E00000100BD 0003FB00FF8F0180 04190008000C6300 6C73636247656E65
0320: 2072616C1E000001 7A000002F700FF1F 0180110300090000 000E08634F755365
0340: 6173006F6E596561 723800D100020000 B3010D00FFFFC60D 000204FE00FF6301
0360: 800400800A000000 134F750052616469 6F42757470746F6E 4373441E00000100
0380: 00EF02FE00FF6301 800400800B000000 10636C00546F6F6C 5469705780696E64
03A0: 6F771E00E8000100 00DD0300FF7F018C 8011000C0010000D 636C53656E006445
03C0: 6D61696C7338A300 02000067010D00FF FF890D00000204FD 00FF8701800D000C
03E0: 000D000C6777004D 6F75736557686518 656C1E0001003D00 010DFB00FF0F0180
0400: 45000000000E0000 00086370514F456D A8B0000000060067 010D00FFFFCD0D00
0420: 01FD00FF371A0001 F700FF1F270000DC 000100FF7F347000 00000100FFFFC141
0440: 00000002D1000100 003F8001F8000000 07
.enddata
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control: cSpinField
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  Form Window: frmPrintCustNotOnLoads
.head 2 -  Class: OurFrmWndWithChildTbl
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Customers In Regions & their Loads
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? No
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 5.75"
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 15
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurFrmWndWithChildTbl
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 16
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurFrmWndWithChildTbl
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbSelectFromTable
.head 5 -  Class Child Ref Key: 17
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurFrmWndWithChildTbl
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: OurFrmWndWithChildTbl
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCurrentDate
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: OurFrmWndWithChildTbl
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text: Region Ids
.head 4 -  Resource Id: 61934
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 3.15"
.head 5 -  Top: 0.094"
.head 5 -  Width:  1.013"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Center
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 3 +  Multiline Field: mlRegions
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  String Type: String
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Border? Yes
.head 5 -  Word Wrap? No
.head 5 -  Vertical Scroll? Yes
.head 5 -  Window Location and Size
.head 6 -  Left: 0.0"
.head 6 -  Top: 0.302"
.head 6 -  Width:  9.738"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.427"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 4 +  Message Actions
.head 5 +  On PAM_REPORTCOLUMNS
.head 6 -  Call BuildSQL( wParam, hWndItem, 'REGIONIDS' )
.head 3 -  !
.head 3 +  Child Table: tblCustInRegions
.head 4 -  Class Child Ref Key: 5
.head 4 -  Class ChildKey: 0
.head 4 -  Class: OurFrmWndWithChildTbl
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.0"
.head 6 -  Top: 0.729"
.head 6 -  Width:  9.763"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 4.229"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colRowId
.head 6 -  Class Child Ref Key: 6
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurFrmWndWithChildTbl
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colRowId.bPopulateColumn = FALSE
.head 7 +  On PAM_REPORTCOLUMNS
.head 8 -  Call SalSendMsg( frmPrintCustNotOnLoads.mlRegions, PAM_REPORTCOLUMNS, wParam, lParam )
.head 5 +  Column: colYear
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Year
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Class Default
.head 6 -  Width:  0.525"
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colYear.sSQLCOLNAME = 'CUSTOMER_ORDER.YEAR_OF_SALE'
.head 8 -  Set colYear.bReportColumn = TRUE
.head 5 +  Column: colRegionId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: RegionId
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  0.838"
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colRegionId.sSQLCOLNAME = 'CUSTOMER_MASTER.REGION_ID'
.head 8 -  Set colRegionId.bReportColumn = TRUE
.head 5 +  Column: colRegionDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: RegionDesc
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colRegionDesc.sSQLCOLNAME = 'REGION.REGION_DESC'
.head 8 -  Set colRegionDesc.bReportColumn = TRUE
.head 5 +  Column: colCustNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: CustNo
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colCustNo.sSQLCOLNAME = 'CUSTOMER_MASTER.CUST_NO'
.head 8 -  Set colCustNo.bReportColumn = TRUE
.head 5 +  Column: colCustName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: CustName
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colCustName.sSQLCOLNAME = 'CUSTOMER_MASTER.CUST_NAME'
.head 8 -  Set colCustName.bReportColumn = TRUE
.head 5 +  Column: colBusAddr1
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Addr.Line 1
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colBusAddr1.sSQLCOLNAME = 'ADDRESS_LINE_1'
.head 8 -  Set colBusAddr1.bPopulateColumn = FALSE
.head 8 -  Set colBusAddr1.bReportColumn = TRUE
.head 5 +  Column: colBusAddr2
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Addr.Line 1
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colBusAddr2.sSQLCOLNAME = 'ADDRESS_LINE_2'
.head 8 -  Set colBusAddr2.bPopulateColumn = FALSE
.head 8 -  Set colBusAddr2.bReportColumn = TRUE
.head 5 +  Column: colSuburb
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Suburb
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colSuburb.sSQLCOLNAME = 'SUBURB'
.head 8 -  Set colSuburb.bPopulateColumn = FALSE
.head 8 -  Set colSuburb.bReportColumn = TRUE
.head 5 +  Column: colState
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: State
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  0.638"
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colState.sSQLCOLNAME = 'STATE'
.head 8 -  Set colState.bPopulateColumn = FALSE
.head 8 -  Set colState.bReportColumn = TRUE
.head 5 +  Column: colPostcode
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Postcode
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: String
.head 6 -  Justify: Class Default
.head 6 -  Width:  0.913"
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colPostcode.sSQLCOLNAME = 'POSTCODE'
.head 8 -  Set colPostcode.bPopulateColumn = FALSE
.head 8 -  Set colPostcode.bReportColumn = TRUE
.head 5 +  Column: colFruitTrees
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Fruit Trees
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Class Default
.head 6 -  Width:  0.988"
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colFruitTrees.sSQLCOLNAME = 'FRUIT_TREES'
.head 8 -  Set colFruitTrees.bPopulateColumn = FALSE
.head 8 -  Set colFruitTrees.bReportColumn = TRUE
.head 5 +  Column: colOrnamTrees
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Ornam Trees
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Class Default
.head 6 -  Width:  1.113"
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colOrnamTrees.sSQLCOLNAME = 'ORNAM_TREES'
.head 8 -  Set colOrnamTrees.bPopulateColumn = FALSE
.head 8 -  Set colOrnamTrees.bReportColumn = TRUE
.head 5 +  Column: colContTrees
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Cont Trees
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Class Default
.head 6 -  Width:  1.038"
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colContTrees.sSQLCOLNAME = 'CONT_TREES'
.head 8 -  Set colContTrees.bPopulateColumn = FALSE
.head 8 -  Set colContTrees.bReportColumn = TRUE
.head 5 +  Column: colCombined  ! This column is used for all rows where the hold_Order_date > todays date
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? No
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colCombined.sSQLCOLNAME = 'FRUIT_TREES + ORNAM_TREES + CONT_TREES'
.head 8 -  Set colCombined.bPopulateColumn = FALSE
.head 8 -  Set colCombined.bReportColumn = TRUE
.head 7 +  On PAM_REPORTCOLUMNS
.head 8 -  Call BuildSQL ( wParam , hWndItem, 'COMBINEDTREES' )
.head 5 +  Column: colHoldDate
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Hold Date
.head 6 -  Visible? No
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Date/Time
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colHoldDate.sSQLCOLNAME = 'HOLD_ORDER_DATE'
.head 8 -  Set colHoldDate.bPopulateColumn = FALSE
.head 8 -  Set colHoldDate.bReportColumn = FALSE
.head 5 +  Column: colSysDate
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 0
.head 6 -  Class: OurColumnClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? No
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Date/Time
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set colSysDate.sSQLCOLNAME = 'SYSDATE'
.head 8 -  Set colSysDate.bPopulateColumn = TRUE
.head 8 -  Set colSysDate.bReportColumn = FALSE
.head 4 +  Functions
.head 5 +  Function: GetLoadType
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sLoadId
.head 7 -  Receive String: sLoadType
.head 7 -  Number: nActionType
.head 6 +  Static Variables
.head 7 -  Sql Handle: hSqlHandle
.head 7 -  Boolean: bHandleConnected
.head 7 -  Boolean: bHandlePrepared
.head 6 +  Local variables
.head 7 -  String: sSql
.head 7 -  String: sFuncName
.head 7 -  Boolean: bOk
.head 7 -  Number: nInd
.head 7 -  String: sGotLoadType
.head 6 +  Actions
.head 7 -  Set sFuncName = 'GetLoadType'
.head 7 +  Select Case nActionType
.head 8 +  Case SH_cls_Execute
.head 9 +  If sLoadId = ''
.head 10 -  Return TRUE
.head 9 +  Else
.head 10 +  Loop Execute
.head 11 +  Loop Connect
.head 12 +  If bHandleConnected
.head 13 -  Break Connect
.head 12 +  Else
.head 13 -  Set bHandleConnected = SqlConnect( hSqlHandle ) 
.head 13 +  If bHandleConnected
.head 14 -  Call SqlSetLockTimeout( hSqlHandle, SQLTIMEOUT )
.head 14 -  Call SqlSetParameter( hSqlHandle, DBP_PRESERVE, TRUE, ''  )
.head 14 -  Break Connect
.head 13 +  Else
.head 14 +  If IDNO = SalMessageBox( 'Could not connect handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 15 -  Break Connect
.head 11 +  Loop Prepare
.head 12 +  If bHandlePrepared
.head 13 -  Break Prepare
.head 12 +  Else
.head 13 -  Set sSql = " SELECT 
  Load_Primary_Type 
FROM 
  Load 
INTO 
  :sGotLoadType
WHERE 
  Load_Id = :sLoadId "
.head 13 +  If SqlPrepare( hSqlHandle, sSql )
.head 14 -  Set bHandlePrepared = TRUE
.head 14 -  Break Prepare
.head 13 +  Else
.head 14 -  Set bHandlePrepared = FALSE
.head 14 +  If IDNO = SalMessageBox( 'Could not prepare handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 15 -  Break Prepare
.head 11 -  !
.head 11 -  Set sGotLoadType = ''
.head 11 -  Set sLoadType = ''
.head 11 -  !
.head 11 +  If SqlExecute( hSqlHandle )
.head 12 -  Call SqlFetchNext( hSqlHandle, nInd )
.head 12 -  Set sLoadType = sGotLoadType
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Set bHandlePrepared = FALSE
.head 12 +  If IDNO = SalMessageBox( 'Could not execute handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 13 -  Return FALSE
.head 8 +  Case SH_cls_Disconnect
.head 9 -  Set bOk = TRUE
.head 9 +  Loop Disconnect
.head 10 +  If bHandleConnected
.head 11 +  If SqlDisconnect( hSqlHandle )
.head 12 -  Set bHandleConnected = FALSE
.head 12 -  Set bHandlePrepared = FALSE
.head 12 -  Break Disconnect
.head 11 +  Else
.head 12 +  If IDNO = SalMessageBox( 'Could not disconnect handle in function '||sFuncName||'Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 13 -  Set bOk = FALSE
.head 13 -  Break Disconnect
.head 10 +  Else
.head 11 -  Break Disconnect
.head 9 -  Return bOk
.head 8 +  Case SH_cls_RePrepare
.head 9 -  Set bHandlePrepared = FALSE
.head 9 -  Return TRUE
.head 5 +  Function: CalcCustConfVTypeTreesNoLoad
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nCustNo
.head 7 -  Number: nYear
.head 7 -  String: sVarietyType
.head 7 -  Receive Number: nTrees
.head 7 -  Boolean: bIncludeContainers
.head 7 -  Number: nActionType
.head 6 +  Static Variables
.head 7 -  FunctionalVar: fcOurContHandle
.head 8 -  Class: hcSqlHandle
.head 7 -  FunctionalVar: fcOurNoContHandle
.head 8 -  Class: hcSqlHandle
.head 6 +  Local variables
.head 7 -  String: sSql
.head 7 -  String: sBind
.head 7 -  String: sInto
.head 7 -  String: sName
.head 7 -  !
.head 7 -  Number: nGotTrees
.head 7 -  !
.head 7 -  Number: nInd
.head 6 +  Actions
.head 7 +  Select Case nActionType
.head 8 +  Case SH_cls_Execute
.head 9 -  Set nTrees = NUMBER_Null
.head 9 -  Set nGotTrees = NUMBER_Null
.head 9 -  !
.head 9 +  If bIncludeContainers
.head 10 -  Set sSql = " SELECT 
  Sum( Conf_Amt ) 
FROM 
  Customer_Order, 
  Stock_Item 
WHERE 
  Customer_Order.Cust_No = :1 AND 
  Customer_Order.Year_Of_Sale = :2 AND 
  Customer_Order.Load_Id IS NULL AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL ) AND 
  Customer_Order.Stock_Item_No = Stock_Item.Item_No AND 
  Stock_Item.Variety_Type = :3 "
.head 10 -  Set sName = 'CUSTVTYPETREESNL'
.head 10 -  Set sBind = ':nCustNo, :nYear, :sVarietyType'
.head 10 -  Set sInto = ':nGotTrees'
.head 10 -  Call fcOurContHandle.Setup( sSql, sName, sBind, sInto )
.head 10 -  Call SqlVarSetup( fcOurContHandle.hSqlHandle )
.head 10 -  !
.head 10 +  If fcOurContHandle.Execute( )
.head 11 -  Call fcOurContHandle.FetchNext( nInd )
.head 11 -  Set nTrees = nGotTrees
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Return FALSE
.head 9 +  Else
.head 10 -  Set sSql = " SELECT 
  Sum( Conf_Amt ) 
FROM 
  Customer_Order, 
  Stock_Item 
WHERE 
  Customer_Order.Cust_No = :1 AND 
  Customer_Order.Year_Of_Sale = :2 AND 
  Customer_Order.Load_Id IS NULL AND
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL ) AND 
  Customer_Order.Stock_Item_No = Stock_Item.Item_No AND 
  Stock_Item.Variety_Type = :3 AND 
  NOT Stock_Item.Tree_Type LIKE 'C%' "
.head 10 -  Set sName = 'CUSTVTYPENCTREESNL'
.head 10 -  Set sBind = ':nCustNo, :nYear, :sVarietyType'
.head 10 -  Set sInto = ':nGotTrees'
.head 10 -  Call fcOurNoContHandle.Setup( sSql, sName, sBind, sInto )
.head 10 -  Call SqlVarSetup( fcOurNoContHandle.hSqlHandle )
.head 10 -  !
.head 10 +  If fcOurNoContHandle.Execute( )
.head 11 -  Call fcOurNoContHandle.FetchNext( nInd )
.head 11 -  Set nTrees = nGotTrees
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Return FALSE
.head 8 +  ! Case nCommit
.head 9 -               Return fcOurHandle.Commit( )
.head 8 +  ! Case nRollback
.head 9 -               Return fcOurHandle.Rollback( )
.head 8 +  Case SH_cls_Disconnect
.head 9 -  Call fcOurContHandle.Disconnect( )
.head 9 -  Call fcOurNoContHandle.Disconnect( )
.head 9 -  Return TRUE
.head 5 +  Function: CalcCustConfContTreesNoLoad
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nCustNo
.head 7 -  Number: nYear
.head 7 -  Receive Number: nTrees
.head 7 -  Number: nActionType
.head 6 +  Static Variables
.head 7 -  FunctionalVar: fcOurHandle
.head 8 -  Class: hcSqlHandle
.head 6 +  Local variables
.head 7 -  String: sSql
.head 7 -  String: sBind
.head 7 -  String: sInto
.head 7 -  String: sName
.head 7 -  !
.head 7 -  Number: nGotTrees
.head 7 -  !
.head 7 -  Number: nInd
.head 6 +  Actions
.head 7 +  Select Case nActionType
.head 8 +  Case SH_cls_Execute
.head 9 -  Set sSql = " SELECT 
  Sum( Conf_Amt ) 
FROM 
  Customer_Order, 
  Stock_Item 
WHERE 
  Customer_Order.Cust_No = :1 AND 
  Customer_Order.Year_Of_Sale = :2 AND 
  Customer_Order.Load_Id IS NULL AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL ) AND 
  Customer_Order.Stock_Item_No = Stock_Item.Item_No  AND 
  Stock_Item.Tree_Type LIKE 'C%' "
.head 9 -  Set sName = 'CUSTCONTTREESN2'
.head 9 -  Set sBind = ':nCustNo, :nYear'
.head 9 -  Set sInto = ':nGotTrees'
.head 9 -  Call fcOurHandle.Setup( sSql, sName, sBind, sInto )
.head 9 -  Call SqlVarSetup( fcOurHandle.hSqlHandle )
.head 9 -  !
.head 9 -  Set nTrees = NUMBER_Null
.head 9 -  Set nGotTrees = NUMBER_Null
.head 9 -  !
.head 9 +  If fcOurHandle.Execute( )
.head 10 -  Call fcOurHandle.FetchNext( nInd )
.head 10 -  Set nTrees = nGotTrees
.head 10 -  Return TRUE
.head 9 +  Else
.head 10 -  Return FALSE
.head 8 +  ! Case nCommit
.head 9 -               Return fcOurHandle.Commit( )
.head 8 +  ! Case nRollback
.head 9 -               Return fcOurHandle.Rollback( )
.head 8 +  Case SH_cls_Disconnect
.head 9 -  Return fcOurHandle.Disconnect( )
.head 5 +  Function: CalcCustConfCurrContTreesNoLoad
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nCustNo
.head 7 -  Number: nYear
.head 7 -  Receive Number: nTrees
.head 7 -  Number: nActionType
.head 6 +  Static Variables
.head 7 -  FunctionalVar: fcOurHandle
.head 8 -  Class: hcSqlHandle
.head 6 +  Local variables
.head 7 -  String: sSql
.head 7 -  String: sBind
.head 7 -  String: sInto
.head 7 -  String: sName
.head 7 -  !
.head 7 -  Number: nGotTrees
.head 7 -  !
.head 7 -  Number: nInd
.head 6 +  Actions
.head 7 +  Select Case nActionType
.head 8 +  Case SH_cls_Execute
.head 9 -  ! GF 30/10/01 Changed query to not find orders where hold date > todays date
.head 9 -  Set sSql = " SELECT 
  Sum( Conf_Amt ) 
FROM 
  Customer_Order, 
  Stock_Item, 
  Growing_Sale 
WHERE 
  Customer_Order.Cust_No = :1 AND 
  Customer_Order.Year_Of_Sale = :2 AND 
  Customer_Order.Load_Id IS NULL AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL ) AND 
  Customer_Order.Stock_Item_No = Stock_Item.Item_No AND 
  Customer_Order.Batch_Location_Id = Growing_Sale.Location_Id AND 
  Customer_Order.Year_Of_Sale = Growing_Sale.Year_Of_Sale AND 
  Customer_Order.Stock_Item_No = Growing_Sale.Stock_Item_No  AND 
  Stock_Item.Stock_Type = 'C' AND 
  (Customer_Order.Hold_Order_Date <= SYSDATE OR 
  Customer_Order.Hold_Order_Date is NULL) AND
  ( Growing_Sale.Est_Sale_Date <= SYSDATE OR 
    Growing_Sale.Est_Sale_Date IS NULL ) AND 
  ( Growing_Sale.Not_For_Sale = 'N' OR 
    Growing_Sale.Not_For_Sale IS NULL ) "
.head 9 -  ! Set sSql = " SELECT 
  Sum( Conf_Amt ) 
FROM 
  Customer_Order, 
  Stock_Item, 
  Growing_Sale 
WHERE 
  Customer_Order.Cust_No = :1 AND 
  Customer_Order.Year_Of_Sale = :2 AND 
  Customer_Order.Load_Id IS NULL AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL ) AND 
  Customer_Order.Stock_Item_No = Stock_Item.Item_No AND 
  Customer_Order.Batch_Location_Id = Growing_Sale.Location_Id AND 
  Customer_Order.Year_Of_Sale = Growing_Sale.Year_Of_Sale AND 
  Customer_Order.Stock_Item_No = Growing_Sale.Stock_Item_No  AND 
  Stock_Item.Stock_Type = 'C' AND 
  Customer_Order.Hold_Order_Date <= SYSDATE AND
  ( Growing_Sale.Est_Sale_Date <= SYSDATE OR 
    Growing_Sale.Est_Sale_Date IS NULL ) AND 
  ( Growing_Sale.Not_For_Sale = 'N' OR 
    Growing_Sale.Not_For_Sale IS NULL ) "
.head 9 -  Set sName = 'CSTCNTCRTRSN4'
.head 9 -  Set sBind = ':nCustNo, :nYear'
.head 9 -  Set sInto = ':nGotTrees'
.head 9 -  Call fcOurHandle.Setup( sSql, sName, sBind, sInto )
.head 9 -  Call SqlVarSetup( fcOurHandle.hSqlHandle )
.head 9 -  !
.head 9 -  Set nTrees = NUMBER_Null
.head 9 -  Set nGotTrees = NUMBER_Null
.head 9 -  !
.head 9 +  If fcOurHandle.Execute( )
.head 10 -  Call fcOurHandle.FetchNext( nInd )
.head 10 -  Set nTrees = nGotTrees
.head 10 -  Return TRUE
.head 9 +  Else
.head 10 -  Return FALSE
.head 8 +  Case SH_cls_Disconnect
.head 9 -  Return fcOurHandle.Disconnect( )
.head 4 +  Window Variables
.head 5 -  String: sLoadType
.head 5 -  String: sTmp
.head 5 -  Date/Time: dtTmp
.head 5 -  !
.head 5 -  Number: nLastCustNo
.head 5 -  String: sBusAddr1
.head 5 -  String: sBusAddr2
.head 5 -  String: sSuburb
.head 5 -  String: sPostcode
.head 5 -  String: sState
.head 5 -  Boolean: bTmp
.head 4 +  Message Actions
.head 5 +  On PAM_SETINSTANCEVARS
.head 6 -  Set nSelectType = nSELDISTINCT
.head 6 -  Set sSQLTABLENAME = ''
.head 6 -  Set sPrinter = 'SmallFanFold'
.head 6 -  Set sSQLPOPTABLENAME = ' Customer_Master, Region, Customer_Order '
.head 6 -  !
.head 6 +  ! If frmPrintCustNotOnLoads.nReportType = nSelectionRegions
.head 7 -  Set sSQLWHERE = " WHERE
  Customer_Master.Region_Id IN ("||frmPrintCustNotOnLoads.mlRegions||") AND 
  Customer_Master.Cust_No = Customer_Order.Cust_No AND 
  Customer_Master.Region_Id = Region.Region_Id AND 
  Customer_Order.Year_Of_Sale = :frmPrintCustNotOnLoads.nYear AND
  Customer_Order.Load_Id IS NULL AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL ) AND 
  ( Customer_Order.Hold_Order_Date <= SYSDATE OR 
    Customer_Order.Hold_Order_Date IS NULL ) "
.head 6 +  ! Else
.head 7 -  Set sSQLWHERE = " WHERE
  Customer_Master.Cust_No = Customer_Order.Cust_No AND 
  Customer_Master.Region_Id = Region.Region_Id AND 
  Customer_Order.Year_Of_Sale = :frmPrintCustNotOnLoads.nYear AND 
  Customer_Order.Load_Id IS NULL  AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL ) AND 
  ( Customer_Order.Hold_Order_Date <= SYSDATE OR 
    Customer_Order.Hold_Order_Date IS NULL ) "
.head 6 +  If frmPrintCustNotOnLoads.nReportType = nSelectionRegions
.head 7 -  Set sSQLWHERE = " WHERE
  Customer_Master.Region_Id IN ("||frmPrintCustNotOnLoads.mlRegions||") AND 
  Customer_Master.Cust_No = Customer_Order.Cust_No AND 
  Customer_Master.Region_Id = Region.Region_Id AND 
  Customer_Order.Year_Of_Sale = :frmPrintCustNotOnLoads.nYear AND
  Customer_Order.Load_Id IS NULL AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL )  "
.head 6 +  Else
.head 7 -  Set sSQLWHERE = " WHERE
  Customer_Master.Cust_No = Customer_Order.Cust_No AND 
  Customer_Master.Region_Id = Region.Region_Id AND 
  Customer_Order.Year_Of_Sale = :frmPrintCustNotOnLoads.nYear AND 
  Customer_Order.Load_Id IS NULL  AND 
  ( Customer_Order.Invoiced_Flag = 'N' OR Customer_Order.Invoiced_Flag IS NULL )"
.head 6 -  !
.head 6 -  Set sORDERBY = ' ORDER BY
  Customer_Master.Region_Id, 
  Customer_Master.Cust_Name, 
  Customer_Master.Cust_No'
.head 6 -  Set sTableHeading = 'Customers In Regions and their Loads'
.head 6 -  Set bSelectFirstRow = FALSE
.head 6 -  Set nTableFillType = TBL_FillAll
.head 6 -  Set sReportFileName = OurGetIniFileParameter( 'GENERAL', 'ReportsPath', '' ) || '\\cstntld2.qrp'
.head 5 +  On SAM_FetchRowDone
.head 6 -  Call GetShipAddress( colCustNo, nYear, dtTmp, sTmp, colBusAddr1, colBusAddr2, colSuburb, colPostcode, colState, sTmp, sTmp, sTmp, sTmp, sTmp, sTmp, sTmp, sTmp, bTmp, SH_cls_Execute )
.head 6 +  If sStockType = 'BARE' OR sStockType = 'BOTH'
.head 7 +  If sStockType = 'BARE'
.head 8 -  Call CalcCustConfVTypeTreesNoLoad( colCustNo, frmPrintCustNotOnLoads.nYear, 'F', colFruitTrees, FALSE, SH_cls_Execute )
.head 8 -  Call CalcCustConfVTypeTreesNoLoad( colCustNo, frmPrintCustNotOnLoads.nYear, 'O', colOrnamTrees, FALSE, SH_cls_Execute )
.head 7 +  Else
.head 8 -  Call CalcCustConfVTypeTreesNoLoad( colCustNo, frmPrintCustNotOnLoads.nYear, 'F', colFruitTrees, TRUE, SH_cls_Execute )
.head 8 -  Call CalcCustConfVTypeTreesNoLoad( colCustNo, frmPrintCustNotOnLoads.nYear, 'O', colOrnamTrees, TRUE, SH_cls_Execute )
.head 8 -  Call CalcCustConfContTreesNoLoad( colCustNo, frmPrintCustNotOnLoads.nYear, colContTrees, SH_cls_Execute )
.head 6 +  Else
.head 7 -  Set colFruitTrees = NUMBER_Null
.head 7 -  Set colOrnamTrees = NUMBER_Null
.head 7 -  ! GF30/10/01 Changed  CalcCustConfCurrContTreesNoLoad() so that it does not find stock with hold date > today, as I can't find where
colHoldDate gets populated SEE BELOW
.head 7 -  Call CalcCustConfCurrContTreesNoLoad( colCustNo, frmPrintCustNotOnLoads.nYear, colContTrees, SH_cls_Execute )
.head 6 +  If ( colFruitTrees + colOrnamTrees + colContTrees ) = 0
.head 7 -  Call SalTblSetRowFlags( hWndForm, lParam, ROW_Hidden, TRUE )
.head 6 +  Else
.head 7 -  ! GF30/10/01 Changed  CalcCustConfCurrContTreesNoLoad() so that it does not find stock with hold date > today, as I can't find where
colHoldDate gets populated SEE ABOVE
.head 7 +  If colHoldDate > colSysDate
.head 8 -  Set colFruitTrees = NUMBER_Null
.head 8 -  Set colOrnamTrees = NUMBER_Null
.head 8 -  Set colContTrees = NUMBER_Null
.head 7 +  Else
.head 8 -  Set colCombined = NUMBER_Null
.head 6 -  Return TRUE
.head 5 +  On SAM_Destroy
.head 6 -  Call GetBusAddress( 0, dtTmp, sTmp, colBusAddr1, colBusAddr2, colSuburb, colPostcode, colState, sTmp, sTmp, sTmp, sTmp, sTmp, sTmp, sTmp, sTmp, SH_cls_Disconnect )
.head 6 -  Call CalcCustConfVTypeTreesNoLoad( 0, 0, '', colFruitTrees, 0, SH_cls_Disconnect )
.head 6 -  Call CalcCustConfContTreesNoLoad( 0, 0, colContTrees, SH_cls_Disconnect )
.head 6 -  Call CalcCustConfCurrContTreesNoLoad( 0, 0, colContTrees, SH_cls_Disconnect )
.head 6 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 5 +  On PAM_PRINTFULLTABLEREPORT
.head 6 -  Call MyTableLoop( hWndForm, hWndForm, PAM_ROWACTION, ROW_Hidden, 0, 'Checking Data', nLowToHi )
.head 6 -  Set nReportPrintOrView = nReportView
.head 6 -  Return SalSendClassMessage( PAM_PRINTFULLTABLEREPORT, wParam, lParam )
.head 5 +  On PAM_ROWACTION
.head 6 -  Call SalTblDeleteRow( hWndForm, lParam, TBL_Adjust )
.head 6 -  Return nRowDeleted
.head 3 -  !
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  String: saRegionIds[*]
.head 3 -  Number: nYear
.head 3 -  ! sStock Type ( 'CONT' = Containers, 'BARE' = Bare root, 'BOTH' = Bare root and Containers )
.head 3 -  String: sStockType
.head 3 -  ! User nAllRegions, nSelectionRegions
  NOTE saRegionIds[*] parameter needs only be set with nSelectionRegions report type
.head 3 -  Number: nReportType
.head 2 -  Window Variables
.head 2 +  Message Actions
.head 3 +  On PAM_SETINSTANCEVARS
.head 4 -  Set sDatabase = SqlDatabase
.head 4 -  Set OurFrmWndWithChildTbl.bQueryTableAllowed = FALSE
.head 4 -  Set OurFrmWndWithChildTbl.bAddRowsAllowed = FALSE
.head 4 -  Set OurFrmWndWithChildTbl.bSaveRowsAllowed = FALSE
.head 4 -  Set OurFrmWndWithChildTbl.bDeleteRowsAllowed = FALSE
.head 4 -  Set OurFrmWndWithChildTbl.bUnDeleteRowsAllowed = FALSE
.head 4 -  Set OurFrmWndWithChildTbl.bTablePrintReportAllowed = TRUE
.head 3 +  On SAM_Create
.head 4 +  If nReportType = nSelectionRegions
.head 5 -  Call MakeStringList( saRegionIds, " , ", "'", mlRegions )
.head 4 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 3 +  On SAM_CreateComplete
.head 4 -  Call SalHideWindow( SalParentWindow( hWndForm ) )
.head 4 -  Call SalWaitCursor( FALSE )
.head 3 +  On SAM_Destroy
.head 4 -  Call SalShowWindow( SalParentWindow( hWndForm ) )
.head 4 -  Call SalSendMsg( SalParentWindow( hWndForm ), PAM_REPORTFINISHED, 0, 0 )
.head 4 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
