.head 0 +  Application Description: SQLWindows 5.01 Jans Dialog Class
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 4170705061746800 24006B3A5C63656E 747572615C636C61 73733B6B3A5C6365
0020: 6E747572615C666C 656D61706C730041 7070506174684C65 6E00040024000000
0040: 00557365476C6F62 616C506174680004 0001000000000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000003000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF160000 0016000000A60200 004F010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D01000000075769 6E646F7773000001
0080: 800400FFFFFFFF00 000000090100002C 0000000000000001 000000FFFFFFFFFF
00A0: FFFFFFFCFFFFFFE9 FFFFFF1600000016 000000B20200005A 0100000000000001
00C0: 000000030000000F 4170706C69636174 696F6E4974656D07 436C617373657310
00E0: 636C734469616C6F 6747656E6572616C 00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.1"
.head 3 -  Top: 2.969"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.917"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 6.6"
.head 3 -  Top: 0.521"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: Spnfield.apl
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: VTWIN.APL
.head 2 -  File Include: Datfield.apl
.head 2 -  File Include: Bgtext.apl
.head 2 -  File Include: BUTTON.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for DIALOG.APL
.head 4 -  Number: DIALOGaplOffSet = SAM_User + 300
.head 4 -  ! Message go up to DIALOGaplOffSet + 99
.head 4 -  Number: DIALOGAplConstOffSet = 150
.head 4 -  ! Messages
.head 4 -  Number: PAM_clsDLG_SHOW = DIALOGaplOffSet + 1
.head 4 -  Number: PAM_clsDLG_EXIT = DIALOGaplOffSet + 2
.head 4 -  Number: PAM_clsDLG_RETURN = DIALOGaplOffSet + 3
.head 4 -  Number: PAM_clsDLG_ACTIVATE = DIALOGaplOffSet + 4
.head 4 -  Number: PAM_clsDLG_PUSHFIELDS = DIALOGaplOffSet + 5
.head 4 -  Number: PAM_clsDLG_POPFIELDS = DIALOGaplOffSet + 6
.head 4 -  Number: PAM_clsDLG_NOTTREESYS = DIALOGaplOffSet + 7
.head 4 -  Number: PAM_clsDLG_SETEXITVALUE = DIALOGaplOffSet + 8
.head 4 -  ! Constants
.head 4 -  Number: DLG_Modal = DIALOGAplConstOffSet + 1
.head 4 -  Number: DLG_Modeless = DIALOGAplConstOffSet + 2
.head 4 -  !
.head 4 -  Number: DLG_EndOnExit = DIALOGAplConstOffSet + 3
.head 4 -  Number: DLG_HideOnExit = DIALOGAplConstOffSet + 4
.head 4 -  Number: DLG_NextOnExit = DIALOGAplConstOffSet + 5
.head 4 -  Number: DLG_BackOnExit = DIALOGAplConstOffSet + 6
.head 4 -  Number: DLG_FinishOnExit = DIALOGAplConstOffSet + 7
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 764546215
0000: 9A00000070000000 0000000000000000 0200000500000010 0100001019000000
0020: 016C01F0B2000000 4073000000010000 A329010019250001 6C3A01BA000073D1
0040: 0001000068420100 190089016C3B0100 6E00730034010000 5B015A0019000182
0060: 6C95030000001B73 0001008D00740100 161900046C01E084 0E00000066730001
0080: 0003
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 3837303995
0000: 8608000097050000 0000000000000000 0200001200FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F53003C00 001063006C734469
0040: 616C6F670047656E 6572616C9A800000 0005000000871900 0000800166011200
0060: 000001F800730000 0001D80000001920 0004000000026660 0113000000F8CF00
0080: 0106001D00000019 0B0004660114D800 0000F8B300010081 3600000004000200
00A0: 036601150000F600 F86C0001003AB000 0000190084016616 0000003DF800011A
00C0: 0000018019220000 0100001104636C53 70696E5300656173 6F6E596561C07222
00E0: 00000001DE001912 0001660600008600 7C01730068000100 0001088004000002
0100: 000010000C636C64 66473E652200D100 0100005B040003DF 0098C4017300018D
0120: 0001801981000300 00000CC370624765 3F00017A0000194B 0001660718000000
0140: 240273A200000100 0001018068000000 04C30009636C8148 656C709A00EC0005
0160: 002D040002666F00 308C027300010036 000400194B000166 08D800000030A300
0180: 010000CD1D001912 000166090000F600 30680001000036B3 0019008401660A00
01A0: 00003D3000011A00 004F00002C001900 0166610B00000030 8F000100C6000180
01C0: 19CC000500090745 78697422A2000001 0000B71900B40166 0700314802730001
01E0: 1A00000180042300 0600000C07506963 45784070616E6422 0000F4010000D604
0200: 00023700C0026673 0001006301800400 8407000012636C07 546F67676C006542
0220: 7574746F6E22A200 00010000B70400B6 02060031CC027300 011B000180532200
0240: 000800000B04636C 466F726D42206173 659A0000057B0019 4B000166081B0020
0260: 0373A20000010000 CD190004DA000209 F600206C0001001D B3001900B404660A
0280: 003D200001DB0036 280004000003666D 0B0020CF00013600 3A00194B0001660C
02A0: D800000020A30001 0000310180190009 C2000017636C0750 72696E7404426169
02C0: 63526570306F7274 2200017A0000194B 000166091B009E03 73A3000100003101
02E0: 8004000A72000010 54006F6F6C546970 5769406E646F7722 0000F4010000D604
0300: 0003340500002804 6473000001006301 800400E40B00000C F87262478F000100
0320: DE0004DA00020686 00420573006C0001 000188801D00000C 0018000C63636247
0340: 3F4000D000000200 005B190001DE6600 185A05730001006D 0019009604000266
0360: B607005A67000100 6301801D00800D00 00000D636C005365 6E64456D6169106C
0380: 734000000200BD00 19A5000166058D00 C60573D100010000 6619000400690266
03A0: 06007BC600360100 018000810000000E 000000C00863514F 456DC1C000000006
03C0: DE0019D200016605 8600140673006800 01000019B3001900 B4016608003D1400
03E0: 011A00003200002C 00190001666D0B00 148F00010006004B 000000194B000166
0400: 0EDA000014A30001 0000C16400000019 12000166110000F6 001468000100007D
0420: 30000000040001B4 02661400FFE08001 0000001F01800403 000F0000000C876D
0440: 6C47656E652200F4 010000D604000336 0500200666730001 0003018046000000
0460: E010000000110270 5374617274500072 6F6772616DD600D8 000007005B040002
0480: DB06001858047300 01006D000400D604 0002B60700586700 01009308000004B5
04A0: 000208ED0058D900 0100640C00001900 69016609007B5800 3401000025005800
04C0: 00040003DB0A009E 5800010D00290000 00D6040002B60B00 5867000100832D00
04E0: 000019A50001660C ED0058D100010000 0001805200000011 0021000F636C5374
0500: FFA33001000ABD00 19A5000166058D00 6A0473D100010000 6619001900690166
0520: 06007B6A00B40100 00325900040002DB 07009E6A00016D00 3600D6040002B608
0540: 006A670001009B3A 0004B5000209ED00 6AD9000100603E00 000004006D020A00
0560: 7B6A003601004200 580000040002DB0B 009E6A00014D0046 0000D6040002B60C
0580: 006A67000100834A 000000043500020D 00ED006AD9000100 604E00000004006D
05A0: 020E007B6A003601 00
.enddata
.head 3 +  Dialog Box Class: clsDialogGeneral
.head 4 -  Title:
.head 4 -  Accessories Enabled? Yes
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  5.0"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 1.885"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 16
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: 0.354"
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clspbHelp
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 0.013"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clspbPrintForm
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 0.375"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 15
.head 7 -  Class: clspbExit
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 4.538"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 8
.head 6 -  Class: clsdfDatabase
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.0"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? No
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Gray
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class: clsdfUser
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.9"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? No
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Gray
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 13
.head 6 -  Class: clsSpinSeasonYear
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 3.95"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 +  Message Actions
.head 7 +  On PAM_clsDLG_NOTTREESYS
.head 8 -  Call SalPostMsg( hWndItem, PAM_clsSPN_DISABLE, 0, 0 )
.head 7 +  On PAM_clsDLG_ACTIVATE
.head 8 +  If wParam
.head 9 -  Call ccSeasonYear.MatchSeasonYearToSpinField(  )
.head 5 -  Background Text:
.head 6 -  Resource Id: 35180
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 14
.head 6 -  Class: clsBackTextSeasonYear
.head 6 -  Window Location and Size
.head 7 -  Left: 3.138"
.head 7 -  Top: 0.052"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 4 -  Derived From
.head 4 +  Class Variables
.head 5 -  Number: nTmp
.head 5 -  String: sTmp
.head 5 -  Date/Time: dtTmp
.head 5 -  Window Handle: hWndTmp
.head 5 -  Number: nReturn
.head 4 +  Instance Variables
.head 5 -  Number: nDialogType
.head 5 -  Number: nActionOnExit
.head 5 -  String: sHelpFileName
.head 5 -  Boolean: bMapEnterToTab
.head 5 -  Boolean: bPrintFormAllowed
.head 5 -  Boolean: bTreeSystem
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Call OurWaitCursor( TRUE )
.head 6 -  Set nDialogType = DLG_Modal
.head 6 -  Set nActionOnExit = DLG_EndOnExit
.head 6 -  Set sHelpFileName = ''
.head 6 -  Set bMapEnterToTab = FALSE
.head 6 -  Set bPrintFormAllowed = FALSE
.head 6 -  Set bTreeSystem = TRUE
.head 6 -  Call SalSendMsg( hWndForm, PAM_clsDLG_POPFIELDS, 0, 0 )
.head 6 -  Call SalSendMsg( hWndForm, PAM_cls_SETINSTANCEVARS, 0, 0 )
.head 6 +  If NOT bPrintFormAllowed
.head 7 -  Call SalSendMsg( pbPrintForm, PAM_clsPB_HIDE, 0, 0 )
.head 6 +  If NOT bTreeSystem
.head 7 -  Call SalSendMsgToChildren( hWndForm, PAM_clsDLG_NOTTREESYS, 0, 0 )
.head 5 +  On SAM_CreateComplete
.head 6 +  If bMapEnterToTab
.head 7 -  Call OurMapEnterToTab( TRUE )
.head 6 -  Call OurWaitCursor( FALSE )
.head 5 +  On SAM_Destroy
.head 6 +  If nActionOnExit = FRM_EndOnExit
.head 7 -  Return SalSendMsg( hWndForm, PAM_cls_DESTROY, 0, 0 )
.head 5 +  On PAM_cls_DESTROY
.head 6 +  If bMapEnterToTab
.head 7 -  Call OurMapEnterToTab( FALSE )
.head 6 +  If SalParentWindow( hWndForm )
.head 7 -  Call SalSendMsg( SalParentWindow( hWndForm ), PAM_cls_PARENTACTIVATE, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  On SAM_Close
.head 6 -  Set nReturn = SalSendMsg( hWndForm, PAM_cls_EXIT, 0, 0 )
.head 6 +  If nReturn = PB_ExitHideWindow
.head 7 -  Call SalHideWindow( hWndForm )
.head 7 -  Return FALSE
.head 5 +  On PAM_cls_CLOSE
.head 6 -  Set nReturn =  SalSendMsg( hWndForm, PAM_cls_EXIT, wParam, lParam )
.head 6 +  If nReturn = PB_ExitDestroyWindow
.head 7 -  Return SalDestroyWindow( hWndForm )
.head 6 +  Else If nReturn = PB_ExitEndDialog
.head 7 -  Return SalEndDialog( hWndForm, wParam )
.head 6 +  Else If nReturn = PB_ExitHideWindow
.head 7 -  Return SalHideWindow( hWndForm )
.head 5 +  On PAM_cls_PARENTACTIVATE
.head 6 -  Call SalShowWindow( hWndForm )
.head 6 -  Call SalBringWindowToTop( hWndForm )
.head 5 +  On SAM_Activate
.head 6 -  Call SalSendMsgToChildren( hWndForm, PAM_clsDLG_ACTIVATE, wParam, lParam )
.head 5 +  On PAM_cls_EXIT
.head 6 -  Call SalSendMsg( hWndForm, PAM_clsDLG_PUSHFIELDS, 0, 0 )
.head 6 -  Call SalSendMsg( SalParentWindow( hWndForm ), PAM_clsDLG_RETURN, 0, SalWindowHandleToNumber( hWndForm ) )
.head 6 +  If nDialogType = DLG_Modal
.head 7 -  Return PB_ExitEndDialog
.head 6 +  Else If nActionOnExit = DLG_EndOnExit
.head 7 -  Return PB_ExitDestroyWindow
.head 6 +  Else
.head 7 -  Return PB_ExitHideWindow
.head 5 +  On PAM_cls_HELP
.head 6 -  Return DisplayHelp( hWndForm )
.head 5 +  On PAM_clsDLG_SHOW
.head 6 -  Call SalSendMsg( hWndForm, PAM_clsDLG_POPFIELDS, 0, 0 )
.head 6 -  Return SalShowWindow( hWndForm )
.head 3 +  Dialog Box Class: clsdlgWizard
.head 4 -  Title:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Class Default
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  7.788"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 4.042"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 11
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsDialogGeneral
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 10
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsDialogGeneral
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 15
.head 7 -  Class ChildKey: 7
.head 7 -  Class: clsDialogGeneral
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? No
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 8
.head 6 -  Class ChildKey: 1
.head 6 -  Class: clsDialogGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 9
.head 6 -  Class ChildKey: 2
.head 6 -  Class: clsDialogGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 13
.head 6 -  Class ChildKey: 3
.head 6 -  Class: clsDialogGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 5.25"
.head 8 -  Top: 0.083"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? No
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 17866
.head 6 -  Class Child Ref Key: 14
.head 6 -  Class ChildKey: 4
.head 6 -  Class: clsDialogGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 4.438"
.head 7 -  Top: 0.135"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? No
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Pushbutton: pbBack
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 8
.head 6 -  Class: clspbGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: < Back
.head 6 -  Window Location and Size
.head 7 -  Left: 1.988"
.head 7 -  Top: 2.823"
.head 7 -  Width:  1.0"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_clsPB_CLICK
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsDLG_SETEXITVALUE, DLG_BackOnExit, 0 )
.head 8 -  Return SalSendMsg( SalParentWindow( hWndItem ), PAM_cls_CLOSE, wParam, lParam )
.head 5 +  Pushbutton: pbNext
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class: clspbGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Next >
.head 6 -  Window Location and Size
.head 7 -  Left: 3.188"
.head 7 -  Top: 2.823"
.head 7 -  Width:  1.0"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_clsPB_CLICK
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsDLG_SETEXITVALUE, DLG_NextOnExit, 0 )
.head 8 -  Return SalSendMsg( SalParentWindow( hWndItem ), PAM_cls_CLOSE, wParam, lParam )
.head 5 +  Pushbutton: pbFinish
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 10
.head 6 -  Class: clspbGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Finish
.head 6 -  Window Location and Size
.head 7 -  Left: 4.388"
.head 7 -  Top: 2.823"
.head 7 -  Width:  1.0"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_clsPB_CLICK
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsDLG_SETEXITVALUE, DLG_FinishOnExit, 0 )
.head 8 -  Return SalSendMsg( SalParentWindow( hWndItem ), PAM_cls_CLOSE, wParam, lParam )
.head 5 +  Pushbutton: pbCancel
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 11
.head 6 -  Class: clspbGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Cancel
.head 6 -  Window Location and Size
.head 7 -  Left: 5.588"
.head 7 -  Top: 2.823"
.head 7 -  Width:  1.0"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_clsPB_CLICK
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsDLG_SETEXITVALUE, DLG_EndOnExit, 0 )
.head 8 -  Return SalSendMsg( SalParentWindow( hWndItem ), PAM_cls_CLOSE, wParam, lParam )
.head 4 +  Derived From
.head 5 -  Class: clsDialogGeneral
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Number: nExitValue
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_clsDLG_SETEXITVALUE
.head 6 -  Set nExitValue = wParam
.head 5 +  On PAM_cls_EXIT
.head 6 -  ! Overridding class to send nExitValue to Parent
.head 6 +  If SalSendMsg( hWndForm, PAM_clsDLG_PUSHFIELDS, 0, 0 )
.head 7 -  Call SalSendMsg( SalParentWindow( hWndForm ), PAM_clsDLG_RETURN, nExitValue, SalWindowHandleToNumber( hWndForm ) )
.head 7 -  Call SalEndDialog( hWndForm, nExitValue )
.head 6 +  Else
.head 7 -  Return FALSE
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton: clspbGeneral
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text: clsBackTextSeasonYear
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control: clsSpinSeasonYear
.head 3 -  ActiveX:
.head 2 -  Application Actions
