.head 0 +  Application Description: Jans new classes Ver 5.00
.data CLASSPROPSSIZE
0000: 5800
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400200000000041 7070506174680020 006B3A5C63656E74 7572613B6B3A5C63
0040: 656E747572615C63 6F6D6D6F6E61706C 7300000000000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000800000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF000000 0000000000140300 009F010000010000 0000000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.head 3 -  Visible? Yes
.head 3 -  Left: 6.05"
.head 3 -  Top: 3.708"
.head 3 -  Width:  3.738"
.head 3 -  Height: 2.177"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 6.6"
.head 3 -  Top: 0.521"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: vtspin.apl
.head 2 -  File Include: myfunc.apl
.head 2 -  File Include: vtmeter.apl
.head 2 -  File Include: vtmisc.apl
.head 2 -  File Include: vttblwin.apl
.head 2 -  ! File Include: sqlhandl.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Dialog Box
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Line
.head 4 -  Line Color: Use Parent
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages they need to be in range 2700 - 2799
.head 4 -  Number: PAM_LOOKUPSTART = SAM_User + 2700
.head 4 -  Number: PAM_LOOKUPINIT = SAM_User + 2701
.head 4 -  Number: PAM_LOOKUPNEXT = SAM_User + 2702
.head 4 -  Number: PAM_LOOKUPFINISH = SAM_User + 2703
.head 4 -  Number: PAM_SELECTALLOWED = SAM_User + 2704
.head 4 -  !
.head 4 -  Number: SEL_OneToMany = 1
.head 4 -  Number: SEL_ManyToMany = 2
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 614354770
0000: 6E0F0000F4090000 0000000000000000 02000083000000AC 0300001004000000
0020: 037001E003020000 0000730000000100 000023B003001900 0400000170010402
0040: BA000073D1000100 0068C90300190089 01700502006E0073 0034010000E2035A
0060: 00040003A3070200 009B7300018D00E6 03009619000170E8 0802000046730001
0080: 0000A3FF03001925 0001700902BA0000 73D1000100006818 040004008D030C02
00A0: 006E007300360100 1C045A00190001A2 700D0200001B7300 01008D0035040096
00C0: 19000170E80E0200 00467300010000A3 4E0400043500037B 04BA000073D90001
00E0: 0068520400190089 01707C04006E0073 00340100006B045A 00190001A2707D04
0100: 00001B730001008D 0084040016040002 7001E87E04000066 7300010023880400
0120: 3B01020000077001 640C8001003C0800 0073C90001000068 8C04000400080102
0140: 703C0D0000FE00C1 80010000003F9004 9A00040001A33D0D 00007F80F2010000
0160: 8F940400D6040003 E0C8100000004673 00010000A3980400 1925000170C910BA
0180: 000073D100010000 68B1040019008901 70CA10006E007300 34010000CA045A00
01A0: 040003A3CC100000 9B7300018D00CE04 009619000170E8CD 1000004673000100
01C0: 00A3E70400192500 0170CE10BA000073 D100010000610500 0004008D03D01000
01E0: 6E00730036010004 055A00190001A270 D11000001B730001 008D001D05009619
0200: 000170E8D2100000 4673000100002336 05000400350003D4 10BA000073D90001
0220: 00683A0500190089 0170D510006E0073 003401000053055A 00190001A270D610
0240: 00001B730001008D 006C0500D6040003 E8D8100000667300 0100A37005001925
0260: 000170D910BA0000 73D1000100006889 05001900890170DA 10006E0073003401
0280: 0000A2055A000400 03A3DC1000009B73 00018D00A6050096 19000170E8DD1000
02A0: 00467300010000A3 BF05001925000170 DE10BA000073D100 01000068D8050004
02C0: 000D03091300006E 007300360100DC05 5A00190001A2700A 1300001B73000100
02E0: 8D00F50500961900 0170E80B13000046 7300010000830E06 0000043500036C15
0300: B800000073D90001 0068120600190089 01706D15006E0073 00340100002B065A
0320: 00040002A36E1500 009B7300018D002F 0600D6040002E86F 1500006673000100
0340: A333060004350003 8815BA000073D900 0100683706001900 8901708915006E00
0360: 7300340100005006 5A00190001A2708A 1500001B73000100 8D00690600D60400
0380: 03E88C1500006673 000100A36D060019 250001708D15BA00 0073D10001000068
03A0: 8606001900890170 8E15006E00730034 0100009F065A0004 0003A3901500009B
03C0: 7300018D00A30600 9619000170E89115 0000467300010000 A3BC060019250001
03E0: 709215BA000073D1 0001000068D50600 04000D035D160000 6E007300360100D9
0400: 065A00190001A270 5E1600001B730001 008D00F20600D604 0002E85F16000066
0420: 73000100A3F60600 043500026016BA00 0073D900010068FA 060004008D037916
0440: 006E007300360100 FE065A00190001A2 707A1600001B7300 01000D0017070000
0460: 9619000170E87B16 0000467300010000 A330070004350003 7D16BA000073D900
0480: 0100683407001900 8901707E16006E00 7300340100004D07 5A00190001A2707F
04A0: 1600001B73000100 8D00660700D60400 03E0501700000066 73000100A36A0700
04C0: 19250001705117BA 000073D100010000 6883070019008901 705217006E007300
04E0: 340100009C075A00 040003A38C170000 9B7300018D00A007 009619000170E88D
0500: 1700004673000100 00A3B90700043500 028E17BA000073D9 00010068BD070004
0520: 008D028F17006E00 7300360100C1075A 00040003A3A91700 009B7300018D00C5
0540: 07009619000170E8 AA17000046730001 0000A3DE07001925 000170AB17BA0000
0560: 73D10001000068F7 070004008D03AC17 006E007300360100 FB075A00190001A2
0580: 70AD1700001B7300 01008D0014080096 19000170E8AE1700 00467300010000A3
05A0: 2D08000435000327 18B800000073D900 0100683108001900 8901702818006E00
05C0: 7300340100004A08 5A00190001A27029 1800001B73000100 8D00630800D60400
05E0: 03E0081A00000066 73000100A3670800 1925000170091ABA 000073D100010000
0600: 6880080019008901 700A1A006E007300 300100000099085A 00040003A30C1A00
0620: 009B7300018D009D 08009619000170E8 0D1A000046730001 0000A3B608001925
0640: 0001700E1ABA0000 73D10001000068CF 080004008D03711A 006E007300360100
0660: D3085A00190001A2 70721A00001B7300 01008D00EC080096 19000170E8731A00
0680: 0046730001000083 0509000004350003 751ABA000073D900 0100680909001900
06A0: 890170761A006E00 7300340100002209 5A00190001A27077 1A00001B73000100
06C0: 8D003B0900D60400 03E0371B00000066 73000100A33F0900 1925000170381BBA
06E0: 000073D100010000 6858090019008901 70391B006E007300 3401000071095A00
0700: 040003A33B1B0000 9B7300018D007509 009619000170E83C 1B00004673000100
0720: 00A38E0900192500 01703D1BBA000073 D10001000068A709 0004008D033F1B00
0740: 6E007300360100AB 095A00190001A270 401B00001B730001 008D00C409009619
0760: 000170E8411B0000 467300010000A3DD 090004350003431B BA000073D9000100
0780: 68E1090019008901 70441B006E007300 34010000FA095A00 190001A270451B00
07A0: 001B730001000D00 130A0000D6040003 E8471B0000667300 0100A3170A001925
07C0: 000170481BBA0000 73D1000100006830 0A00190089017049 1B006E0073003401
07E0: 0000490A5A000400 03A34B1B00009B73 00018D004D0A0096 19000170E84C1B00
0800: 00467300010000A3 660A001925000170 4D1BBA000073D100 010000687F0A0004
0820: 000D03CE1D00006E 007300360100830A 5A00190001A270CF 1D00001B73000100
0840: 8D009C0A00961900 0170E8D01D000046 7300010000A3B50A 0004350003D21DBA
0860: 000073D900010068 B90A001900890170 D31D006E00730034 010000D20A5A0019
0880: 0001A270D41D0000 1B730001008D00EB 0A00D6040003E044 1E00000066730001
08A0: 00A3EF0A00192500 0170451EBA000073 D10001000060080B 0000190089017046
08C0: 1E006E0073003401 0000210B5A001900 01A270AF1E00001B 730001008D003A0B
08E0: 00D6040003E08822 0000006673000100 A33E0B0019250001 708922BA000073D1
0900: 0001000068570B00 19008901708A2200 6E00730034010000 700B5A0019000182
0920: 70832C0000001B73 0001008D00890B00 9619000170E8842C 0000467300010000
0940: A3A20B0019250001 70852CBA000073D1 0001000068BB0B00 1900890170862C00
0960: 6E00730034010000 D40B5A0019000182 7027370000001B73 0001008D00ED0B00
0980: 9619000170E82837 0000467300010000 83060C0000190500 047001553AB80000
09A0: 0073D9000100681F 0C00190089017080 10006E0073003401 0000380C5A001900
09C0: 01A2708F1500001B 730001008D00510C 00940400000370F4 0B00006673000100
09E0: A3550C0019250001 700C00BD0073D100 010000686E0C0019 004901700D00006F
0A00: 730034010000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1112466023
0000: 7F0C0000FB070000 0000000000000000 0200001200FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F4B003C00 00194A00616E5365
0040: 6C6563740046726F 6D5461626CE06550 62436C005E000000 030000000F190000
0060: 0001017E01060000 0003F20073000000 B001000000195900 190001C27E070000
0080: 001EF20001000D00 3200000096190001 7EB008000000F247 000100000301801D
00A0: 0000008401000017 4A61005069636B49 6E746FFC54610F40 000000F002000000
00C0: 961900017E360600 FE00467300010000 1B19000400840000 037E0107ED00FED9
00E0: 0001008001806C00 0000020100154E65 774F750072446C67 5769746800436869
0100: 6C6454626C40B800 00000600006F1900 01017E012E000000 430A01730000B401
0120: 0000195900190001 C27E2F0000001E0A 0001006D003200D6 040003B030000000
0140: 0A67000100833600 0000192500017E31 00EC00000AD10001 0000604F00000019
0160: 0049017E3200007B 0A00340100006800 580000040003C333 0000009E0A00018D
0180: 0001806C11000300 00154F027546726D 576E64FC57697F00 F60600961900017E
01A0: 3010000000360244 7300000100009B19 00192500017E1100 EC000036D1000100
01C0: 0066320004000903 7E120000007B3600 3601003600590019 0001C27E13000000
01E0: 1C36020001006D00 4F00961900017EB0 0F00000036470001 00009B6800043500
0200: 035C00EC000036D9 0001009801806C00 04A100124F7544FF FFEC0006002D1900
0220: 017E6D0F007E8C02 7300010036001900 194B00017E10DB00 7EA300010000CD32
0240: 0004DA000311F600 7E6C00010036B200 001900B4017E1200 3D7E0001DA00004F
0260: 2C001900017E6D13 007E8F0001003600 6800046B000314D8 0000007EB3000100
0280: 3101801D0005C000 0000145069FFFE65 670002006F04006D 03080063BA027300
02A0: B401000004590019 0001C27E09000000 1EBA0001000D0001 80D3001800000600
02C0: 0F4FE2755F436838 5F5461E401D20010 00005B040002C07E 011600000018F602
02E0: 730001006D000400 D6040002B0170000 00F6670001009308 0000043500021800
0300: EC0000F6D9000100 600C00000004004D 021900007BF600B6 0100105900040002
0320: C31A0000009EF600 014D001400009619 00017EB01C000000 F64700010000832D
0340: 000000192500017E 1D00ED00F6D10001 0000604600000019 0009017E1E000000
0360: 7BF600340100005F 00580000190004C0 7E01200000009EF6 00010D0078000000
0380: 961900017EB02100 0000F64700010000 0B91000004003500 022200EC0000F6D9
03A0: 0001006095000000 04000D0223000000 7BF600B601009958 0000190001C27E25
03C0: 0000001EF6000100 2D00B20000961900 017EB026000000F6 470001000083CB00
03E0: 0000043500022700 EC0000F6D9000100 60CF00000004000D 02280000007BF600
0400: 360100018040BE00 000007000078104E 6543CE685461BF00 DE00049A00020C00
0420: 8600140373006800 01000004B3000400 86020D0000003D14 0001DB0008AC0004
0440: 0002610E00000014 CF000136000C0004 6B00020FDB0014B3 000100CD100004DA
0460: 000210F600146C00 010014B200000400 B603110039140300 019B001800AC0004
0480: 00036D120014CF00 0126001C0000194B 00017E14DB0014A3 00010000C1350000
04A0: 00195200017E1500 F600146800010000 4EB00000001900B4 017E16003D140001
04C0: 1A00006700002C00 1900017E6D170014 8F00010016008000 00046B000219DB00
04E0: 14B3000100C18400 0000191200017E1B 0000F60014680001 00009DB100001900
0500: B4017E1C003D1400 011A0000B60000AC 000400026D1D0014 CF00010600BA0000
0520: 00046B00021EDB00 14B3000100210180 2D000008C3000E4F 75806F6C756D6E43
0540: 6C93B8000006BD00 0435000205008D00 2C0373D100010000 66040004006D0206
0560: 007B2C00B6010008 5900040002DB0700 9E2C00016D000C00 D6040002B608002C
0580: 670001009B100004 B5000209ED002CD9 0001006414000019 0009017E0A000000
05A0: 7B2C003401000001 80462D0009000008 114F754461746180 4669656C64436C9F
05C0: 0006BD0004B50002 058D00380373D100 0100006604000400 6D0206007B3800B6
05E0: 0100085900040002 DB07009E3800016D 000C00D6040002B6 080038670001009B
0600: 100004B5000209ED 0038D90001006614 00190069017E0A00 7B38003401000001
0620: 80440400000A0000 4E11546251407565 7279446C42106F78 2200000100BD0004
0640: B500031B8D005603 73D9000100180180 04000B000000000C 636C736362004765
0660: 6E6572616C22A200 00010000B70400B6 0206002134047300 00011B0001801D23
0680: 000C00000E08634F 7553656173006F6E 596561724000D100 0200005B190001DE
06A0: 7E00188804730001 006D001900960400 027EB60700886700 0100630180040084
06C0: 0D0000134F750052 6164696F42757470 746F6E4373442200 000100006F04006D
06E0: 020600639A047300 3601000180460400 0E00000810636C54 6F6F6C0054697057
0700: 696E646F88772200 000100DE0004DA00 0305860094077300 6C000100018C801D
0720: 000F0010000D636C 53656E0064456D61 696C7340A3000200 00B71900BC017E00
0740: 31F407730001DA00 00192C000400027E 6D0600F4CF000186 0001801900080010
0760: 00000C6777004D6F 7573655768651865 6C22000100BD0019 A500017E0ABD0073
0780: D100010000000180 8100000011000100 0863514F456D07C0 000000067B00194B
07A0: 00017E051B008A08 73A20000010000CD 1900199200017E08 00F6008A68000100
07C0: 0032B3001900A401 7E0B00003D8A0001 9A00004B002C0019 00017E6D0E008A8F
07E0: 0001000600640000 00194B00017E11DB 008AA300010000C1 7D00000004900001
0800: 027E1400FE008380 010000007F
.enddata
.head 3 -  ! The next two push button classes go hand in hand
.head 3 +  Pushbutton Class: JanSelectFromTablePbClass
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description: Use this push button class to implement a select button to select data from a table window
into another window.  This class talks with JanPickIntoTablePbClass to achive its selections.
INSTANCE VARIABLES :
  hWndTable : refers to the ussually child table on hWndForm which is being selected from
  hWndSelectParent : refers to the button (JanPickIntoTablePbClass) that should have
                                   created hWndForm
  bManytoManySelect : Default is TRUE, this specifies that selecting multiple rows will select
                                      into the corresponding selected rows and when the select into 
                                      selected rows run out (ie:not enough) PAM_ADDROW is send to
                                      add a ROW_New until all the user selected rows have been processed.
  bOneToManySelect : Default is FALSE, this allows one user select to be selected into
                                     many selected rows.
  nSelectDirection : Values are nLowToHi , nHiToLow, nLowToHiWithPositioning, 
                                nHiToLowWithPositioning.  Purpose is the way the user selected selected rows
                                get processed from top to bottom or bottom to top.
  MESSAGES TO IMPLEMENT PER INSTANCE
    PAM_PUSHFIELDS  : Must return TRUE
    PAM_POPFIELDS : Must return TRUE, should pop off the data pushed in PAM_PUSHFIELDS
                                   message.  ( HAS TO BE IMPLEMENTED )
    PAM_LOOKUPFINISH : Trap this message to implement the destroy or hide of the pick screen
                                          once the selection process has been completed.
.head 4 +  Derived From
.head 5 -  Class: OurPushbuttonClass
.head 4 +  Class Variables
.head 5 -  Number: nTotalRows
.head 5 -  Boolean: bOneToManyActivated
.head 5 -  Boolean: bFirst
.head 4 +  Instance Variables
.head 5 -  Window Handle: hWndTable
.head 5 -  Window Handle: hWndSelectParent
.head 5 -  Boolean: bManyToManySelect
.head 5 -  Boolean: bOneToManySelect
.head 5 -  Number: nSelectDirection
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set hWndTable = hWndNULL
.head 6 -  Set hWndSelectParent = hWndNULL
.head 6 -  Set bManyToManySelect = TRUE
.head 6 -  Set bOneToManySelect = FALSE
.head 6 -  Set nSelectDirection = nLowToHi
.head 6 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  On PAM_CLICK
.head 6 +  If MyTableAnyRows( hWndTable, ROW_Selected, 0, nTotalRows )
.head 7 -  Set bOneToManyActivated = FALSE
.head 7 +  If nTotalRows = 1
.head 8 +  If bOneToManySelect
.head 9 -  Set bOneToManyActivated = TRUE
.head 7 -  !
.head 7 +  If bOneToManyActivated
.head 8 +  If SalSendMsg( hWndSelectParent, PAM_SELECTALLOWED, SEL_OneToMany, 0 )
.head 9 +  If SalSendMsg( hWndSelectParent, PAM_LOOKUPSTART, SEL_OneToMany, 0 )
.head 10 -  Set bFirst = TRUE
.head 10 -  Set bOk = TRUE
.head 10 +  While bOk
.head 11 +  If bFirst
.head 12 -  Set bFirst = FALSE
.head 12 +  If SalSendMsg( hWndItem, PAM_PUSHFIELDS, 0, 0 )
.head 13 +  If SalSendMsg( hWndSelectParent, PAM_LOOKUPINIT, SEL_OneToMany, 0 )
.head 14 -  Set bFirst = FALSE
.head 13 +  Else
.head 14 -  Call SalSendMsg( hWndItem, PAM_POPFIELDS, 0, 0 )
.head 14 -  Set bOk = FALSE
.head 12 +  Else
.head 13 -  Set bOk = FALSE
.head 11 +  Else
.head 12 +  If SalSendMsg( hWndItem, PAM_PUSHFIELDS, 0, 0 )
.head 13 +  If NOT SalSendMsg( hWndSelectParent, PAM_LOOKUPNEXT, SEL_OneToMany, 0 )
.head 14 -  Call SalSendMsg( hWndItem, PAM_POPFIELDS, 0, 0 )
.head 14 -  Set bOk = FALSE
.head 12 +  Else
.head 13 -  Set bOk = FALSE
.head 10 -  Call SalSendMsg( hWndSelectParent, PAM_LOOKUPFINISH, SEL_OneToMany, 0 )
.head 7 +  Else
.head 8 +  If SalSendMsg( hWndSelectParent, PAM_SELECTALLOWED, SEL_ManyToMany, 0 )
.head 9 +  If SalSendMsg( hWndSelectParent, PAM_LOOKUPSTART, 0, 0 )
.head 10 -  Set bFirst = TRUE
.head 10 -  Call MyTableLoop( hWndTable, hWndItem, PAM_ROWACTION, ROW_Selected, 0, 'Selecting Multiple Rows', nSelectDirection )
.head 10 -  Call SalSendMsg( hWndSelectParent, PAM_LOOKUPFINISH, 0, 0 )
.head 6 +  Else
.head 7 -  Call SalMessageBox( 'Row Not Selected', 'Error', MB_Ok )
.head 5 +  On PAM_ROWACTION
.head 6 +  If bFirst
.head 7 +  If SalSendMsg( hWndItem, PAM_PUSHFIELDS, 0, 0 )
.head 8 +  If SalSendMsg( hWndSelectParent, PAM_LOOKUPINIT, SEL_ManyToMany, 0 )
.head 9 -  Set bFirst = FALSE
.head 9 -  Return TRUE
.head 8 +  Else
.head 9 -  Call SalSendMsg( hWndItem, PAM_POPFIELDS, 0, 0 )
.head 9 -  Return FALSE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Else
.head 7 +  If SalSendMsg( hWndItem, PAM_PUSHFIELDS, 0, 0 )
.head 8 +  If SalSendMsg( hWndSelectParent, PAM_LOOKUPNEXT, SEL_ManyToMany, 0 )
.head 9 -  Return TRUE
.head 8 +  Else
.head 9 -  Call SalSendMsg( hWndItem, PAM_POPFIELDS, 0, 0 )
.head 9 -  Return FALSE
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  On PAM_PUSHFIELDS
.head 6 -  Return TRUE
.head 5 +  On PAM_POPFIELDS
.head 6 -  Return TRUE
.head 3 +  Pushbutton Class: JanPickIntoTablePbClass
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description: Use this button class to implement a PICK button that creates a window from which the user
can select rows to select back into hWndForm. This class talks with JanSelectFromTablePbClass
to achive the selections.
INSTANCE VARIABLES :
  bPickModalDialog : Default FALSE, This specifies if the pick screen should be modal or modeless.
  hWndChildTable : This is the handle of the child table window that is receiving the seleted values.
  sPickDialogName : string name of the pick screen ie ('dlgQItem').
  nLookUpMessage : Default PAM_LOOKUP, This is the message that gets sent first to hWndItem
                                  to try to pop the values of.  If a FALSE is returned ( ussually ) because the
                                  message is not implemented the PAM_LOOKUP is sent to the hWndChildTable
                                  if a FALSE is returned then PAM_LOOKUP is sent to the children of hWndChildTable.
                                  wParam of this message is one of two contstants SEL_OneToMany OR SEL_ManyToMany,
                                  lParam is the context row number
  bManyToManySelect : Default is TRUE, This allows multiple picked rows to be selected into multiple
                                     selected INTO (hWndChildTable) rows and when hWndChildTable rows selected
                                     run out the PAM_ADDROW is sent to insert new rows to retreive all the picked rows.
  bOneToManySelect : Default is FALSE, This allows one picked row to be selected into multiple selected
                                     into rows.
  bPAM_ADDROWOnManySelect : Default is TRUE, This speciefies that a PAM_ADDROW message
                                                       will be sent to the selected into table window when not enough
                                                       into selected rows are for the number of user picked rows.
.head 4 +  Derived From
.head 5 -  Class: OurPushbuttonClass
.head 4 +  Class Variables
.head 5 -  Number: nRow
.head 5 -  Window Handle: hWndCol
.head 4 +  Instance Variables
.head 5 -  Boolean: bPickModalDialog
.head 5 -  Window Handle: hWndChildTable
.head 5 -  String: sPickDialogName
.head 5 -  Number: nLookUpMessage
.head 5 -  Boolean: bManyToManySelect
.head 5 -  Boolean: bOneToManySelect
.head 5 -  Boolean: bPAM_ADDROWOnManySelect
.head 5 -  !
.head 5 -  Boolean: bEnableDlgSelectPb
.head 5 -  Window Handle: hWndPickDlg
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set bEnableDlgSelectPb = FALSE
.head 6 -  Set bManyToManySelect = TRUE
.head 6 -  Set bOneToManySelect = FALSE
.head 6 -  Set bPAM_ADDROWOnManySelect = TRUE
.head 6 -  Set bPickModalDialog = TRUE
.head 6 -  Set hWndChildTable = hWndNULL
.head 6 -  Set sPickDialogName = ''
.head 6 -  Set hWndPickDlg = hWndNULL
.head 6 -  Set hWndChildTable = hWndNULL
.head 6 -  Set nLookUpMessage = PAM_LOOKUP
.head 6 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  On PAM_CLICK
.head 6 -  Set bEnableDlgSelectPb = FALSE
.head 6 -  Call SalTblQueryFocus( hWndChildTable, nRow, hWndCol )
.head 6 +  If SalTblQueryRowFlags( hWndChildTable, nRow, ROW_Selected )
.head 7 -  Set bEnableDlgSelectPb = TRUE
.head 6 +  Else
.head 7 +  If SalSendMsg( hWndCol, PAM_ENABLECHILDSELECTPB, nRow, 0 )
.head 8 -  Set bEnableDlgSelectPb = TRUE
.head 8 -  Call SalTblSetRowFlags( hWndChildTable, nRow, ROW_Selected, TRUE )
.head 7 +  Else
.head 8 -  Set bEnableDlgSelectPb = FALSE
.head 6 -  Return SalSendMsg( hWndItem, PAM_STARTPICKDLG, 0, 0 )
.head 5 -  !
.head 5 +  On PAM_STARTPICKDLG
.head 6 +  If hWndPickDlg = hWndNULL OR SalGetWindowState( hWndPickDlg ) = Window_Invalid
.head 7 +  If sPickDialogName != ''
.head 8 -  Call PushNumber( bEnableDlgSelectPb )
.head 8 -  Call PushWndHdl( hWndItem )
.head 8 -  Call SalSendMsg( hWndItem, PAM_PUSHFIELDS, 0, 0 )
.head 8 +  If bPickModalDialog
.head 9 -  Call SalModalDialog( sPickDialogName, hWndForm )
.head 8 +  Else
.head 9 -  Set hWndPickDlg = SalCreateWindow( sPickDialogName, hWndForm )
.head 6 +  Else
.head 7 -  Call SalSendMsg( hWndItem, PAM_PUSHFIELDS, 0, 0 )
.head 7 -  Call SalSendMsg( hWndPickDlg, PAM_SHOW, bEnableDlgSelectPb, 0 )
.head 6 -  Return TRUE
.head 5 +  On PAM_HIDEPICKDLG
.head 6 -  Call SalSendMsg( hWndPickDlg, PAM_HIDE, 0, 0 )
.head 5 +  On PAM_SHOWPICKDLG
.head 6 -  Call SalSendMsg( hWndPickDlg, PAM_SHOW, 0, 0 )
.head 5 +  On PAM_ENDPICKDLG
.head 6 -  Call SalSendMsg( hWndPickDlg, PAM_END, 0, 0 )
.head 5 -  !
.head 5 +  On PAM_SELECTALLOWED
.head 6 +  If wParam = SEL_OneToMany
.head 7 +  If bOneToManySelect
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Else
.head 7 +  If bManyToManySelect
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 -  !
.head 5 +  On PAM_LOOKUPSTART
.head 6 -  Set nRow = TBL_MinRow
.head 6 -  Return TRUE
.head 5 +  On PAM_LOOKUPINIT
.head 6 +  If SalTblFindNextRow( hWndChildTable, nRow, ROW_Selected, 0 )
.head 7 -  Call SalTblFetchRow( hWndChildTable, nRow )
.head 7 -  !
.head 7 +  If SalSendMsg( hWndItem, nLookUpMessage, wParam, nRow )
.head 8 -  Return TRUE
.head 7 +  Else If SalSendMsg( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 8 -  Return TRUE
.head 7 +  Else If SalSendMsgToChildren( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Else
.head 7 +  If wParam = SEL_OneToMany
.head 8 -  Return FALSE
.head 7 +  Else
.head 8 +  If bPAM_ADDROWOnManySelect
.head 9 +  If SalSendMsg( hWndChildTable, PAM_ADDROW, 0, 0 ) = TBL_Error
.head 10 -  Return FALSE
.head 9 +  Else
.head 10 +  If SalSendMsg( hWndItem, nLookUpMessage, wParam, nRow )
.head 11 -  Return TRUE
.head 10 +  Else If SalSendMsg( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 11 -  Return TRUE
.head 10 +  Else If SalSendMsgToChildren( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Return FALSE
.head 8 +  Else
.head 9 -  Return FALSE
.head 5 +  On PAM_LOOKUPNEXT
.head 6 +  If SalTblFindNextRow( hWndChildTable, nRow, ROW_Selected, 0 )
.head 7 -  Call SalTblFetchRow( hWndChildTable, nRow )
.head 7 -  !
.head 7 +  If SalSendMsg( hWndItem, nLookUpMessage, wParam, nRow )
.head 8 -  Return TRUE
.head 7 +  Else If SalSendMsg( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 8 -  Return TRUE
.head 7 +  Else If SalSendMsgToChildren( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Else
.head 7 +  If bPAM_ADDROWOnManySelect
.head 8 +  If wParam = SEL_OneToMany
.head 9 -  Return FALSE
.head 8 +  Else
.head 9 +  If SalSendMsg( hWndChildTable, PAM_ADDROW, 0, 0 ) = TBL_Error
.head 10 -  Return FALSE
.head 9 +  Else
.head 10 +  If SalSendMsg( hWndItem, nLookUpMessage, wParam, nRow )
.head 11 -  Return TRUE
.head 10 +  Else If SalSendMsg( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 11 -  Return TRUE
.head 10 +  Else If SalSendMsgToChildren( hWndChildTable, nLookUpMessage, wParam, nRow )
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Return FALSE
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  On PAM_LOOKUPFINISH
.head 6 -  Call SalSendMsg( hWndPickDlg, PAM_LOOKUPFINISH, wParam, 0 )
.head 6 -  Return TRUE
.head 3 +  Dialog Box Class: NewOurDlgWithChildTbl
.head 4 -  Title:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  7.863"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 3.917"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 54
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description: Flemings default dialog with child table window and
relevant table actions with default colours
Has database field left top and current date time
right top
ON PAM_SETINSTANCEVARS
  always
    Set sDatabase = SqlDatabase
  as needed
    Set sHelpFileName = 'n:\apps\gutpa\help\help.txt'
    Set sAboutDlgName = 'dlgAbout' - THIS IS DEFAULT
    
bAddRowsAllowed allows table action add rows allowed
bSaveRowsAllowed allows table action save changes allowed
bClearRowsAllowed allows table action clear selections allowed
bDeleteRowsAllowed allows table action delete rows allowed
bUnDeleteRowsAllowed allows table action undelete rows allowed
bOrderTableAllowed allows table action order table allowed
bMoveUpDownRowsAllowed allows table action move selected
  rows up or down one by coping them up or down.
bQueryTableAllowed allows quering of table
bTablePrintReportAllowed allows printing of table report
bSelectPbEnable allows pbSelect
bExitOnSelect if true saldestroywindow on select else just hide window
bQueryOnSelect if true and bSelectPbEnableb then calls table query
  else populates table on creation 
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: 0.333"
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbOrderTable
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 18
.head 7 -  Class:
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: &Order Table
.head 7 -  Window Location and Size
.head 8 -  Left: 0.813"
.head 8 -  Top: 0.021"
.head 8 -  Width:  1.1"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.208"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Italic
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On SAM_Click
.head 9 -  Call SalSendMsg( tblChildTable, PAM_ORDERTABLE, 0, 0 )
.head 8 +  On PAM_ENABLE
.head 9 -  Call SalShowWindow( hWndItem )
.head 8 +  On PAM_DISABLE
.head 9 -  Call SalHideWindow( hWndItem )
.head 6 +  Pushbutton: pbRepopTable
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 27
.head 7 -  Class:
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: &Repop Tbl
.head 7 -  Window Location and Size
.head 8 -  Left: 1.988"
.head 8 -  Top: 0.021"
.head 8 -  Width:  0.963"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.208"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Italic
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On SAM_Click
.head 9 +  If NOT TableForgetChanges( tblChildTable, tblChildTable.bEdit )
.head 10 -  Return FALSE
.head 9 -  Call SalSendMsg( tblChildTable, PAM_REPOPULATE, 0, 0 )
.head 8 +  On PAM_ENABLE
.head 9 -  Call SalShowWindow( hWndItem )
.head 8 +  On PAM_DISABLE
.head 9 -  Call SalHideWindow( hWndItem )
.head 6 +  Pushbutton: pbMoveTblRowsUp
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 19
.head 7 -  Class:
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Move Rows Up
.head 7 -  Window Location and Size
.head 8 -  Left: 3.05"
.head 8 -  Top: 0.021"
.head 8 -  Width:  1.363"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.208"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Italic
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On SAM_Click
.head 9 -  Call SalSendMsg( tblChildTable, PAM_MOVESELECTEDROWSUPONE, 0, 0 )
.head 8 +  On PAM_ENABLE
.head 9 -  Call SalShowWindow( hWndItem )
.head 8 +  On PAM_DISABLE
.head 9 -  Call SalHideWindow( hWndItem )
.head 6 +  Pushbutton: pbMoveTblRowsDown
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 20
.head 7 -  Class:
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Move Rows Down
.head 7 -  Window Location and Size
.head 8 -  Left: 4.413"
.head 8 -  Top: 0.021"
.head 8 -  Width:  1.575"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.208"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Italic
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On SAM_Click
.head 9 -  Call SalSendMsg( tblChildTable, PAM_MOVESELECTEDROWSDOWNONE, 0, 0 )
.head 8 +  On PAM_ENABLE
.head 9 -  Call SalShowWindow( hWndItem )
.head 8 +  On PAM_DISABLE
.head 9 -  Call SalHideWindow( hWndItem )
.head 6 +  Pushbutton: pbPrintTableReport
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 22
.head 7 -  Class:
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: &Print Table Report
.head 7 -  Window Location and Size
.head 8 -  Left: 6.038"
.head 8 -  Top: 0.021"
.head 8 -  Width:  1.663"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.208"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Italic
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On SAM_Click
.head 9 -  Call SalSendMsg( tblChildTable, PAM_PRINTFULLTABLEREPORT, 0, 0 )
.head 8 +  On PAM_ENABLE
.head 9 -  Call SalShowWindow( hWndItem )
.head 8 +  On PAM_DISABLE
.head 9 -  Call SalHideWindow( hWndItem )
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 52
.head 7 -  Class: Our_Dialog_Box
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbCancel
.head 7 -  Class Child Ref Key: 10
.head 7 -  Class ChildKey: 53
.head 7 -  Class: Our_Dialog_Box
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 54
.head 7 -  Class: Our_Dialog_Box
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Child Table: tblChildTable
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 6
.head 6 -  Class: NewOurChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: -0.013"
.head 8 -  Top: 0.406"
.head 8 -  Width:  7.75"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 2.313"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colRowId
.head 8 -  Class Child Ref Key: 3
.head 8 -  Class ChildKey: 7
.head 8 -  Class: NewOurChildTable
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title:
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 6 -  Functions
.head 6 -  Window Variables
.head 6 +  Message Actions
.head 7 +  On SAM_DoubleClick
.head 8 +  If SalIsWindowVisible( pbSelectRows )
.head 9 -  Call SalSendMsg( pbSelectRows, SAM_Click, 0, 0 )
.head 5 -  !
.head 5 +  Pushbutton: pbSelectRows
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 35
.head 6 -  Class: JanSelectFromTablePbClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: &Select
.head 6 -  Window Location and Size
.head 7 -  Left: 0.075"
.head 7 -  Top: 2.792"
.head 7 -  Width:  1.2"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.292"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set pbSelectRows.hWndTable = tblChildTable
.head 8 -  Set pbSelectRows.hWndSelectParent = hWndSelectParent
.head 8 -  Set pbSelectRows.bOneToManySelect = TRUE
.head 7 +  On PAM_CLICK
.head 8 +  If NOT TableForgetChanges( tblChildTable, tblChildTable.bEdit )
.head 9 -  Return FALSE
.head 8 -  Return SalSendClassMessage( PAM_CLICK, wParam, lParam )
.head 5 -  !
.head 5 +  Pushbutton: pbAddRows
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 28
.head 6 -  Class: OurPushbuttonClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: &Add Rows - F6
.head 6 -  Window Location and Size
.head 7 -  Left: 1.363"
.head 7 -  Top: 2.792"
.head 7 -  Width:  1.338"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.292"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: F6
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_CLICK
.head 8 -  Call SalSendMsg( tblChildTable, PAM_ADDROW, 0, 0 )
.head 5 +  Pushbutton: pbSaveRows
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 29
.head 6 -  Class: OurPushbuttonClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: &Save Changes - F5
.head 6 -  Window Location and Size
.head 7 -  Left: 2.7"
.head 7 -  Top: 2.792"
.head 7 -  Width:  1.713"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.292"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: F5
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_CLICK
.head 8 -  Call SalSendMsg( tblChildTable, PAM_WRITEINSERTSUPDATES, 0, 0 )
.head 5 +  Pushbutton: pbClearRows
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 30
.head 6 -  Class: OurPushbuttonClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: &Clear Selection - F3
.head 6 -  Window Location and Size
.head 7 -  Left: 4.588"
.head 7 -  Top: 2.792"
.head 7 -  Width:  1.763"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.292"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: F3
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_CLICK
.head 8 -  Call SalSendMsg( tblChildTable, PAM_CLEARSELECTIONS, 0, 0 )
.head 5 +  Pushbutton: pbDeleteRows
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 31
.head 6 -  Class: OurPushbuttonClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: &Delete Rows - F4
.head 6 -  Window Location and Size
.head 7 -  Left: 3.088"
.head 7 -  Top: 3.135"
.head 7 -  Width:  1.638"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.292"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: F4
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_CLICK
.head 8 -  Call SalSendMsg( tblChildTable, PAM_DELETEROWS, 0, 0 )
.head 5 +  Pushbutton: pbUnDeleteRows
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 32
.head 6 -  Class: OurPushbuttonClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: &UnDelete Rows
.head 6 -  Window Location and Size
.head 7 -  Left: 4.725"
.head 7 -  Top: 3.135"
.head 7 -  Width:  1.638"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.292"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: (none)
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_CLICK
.head 8 -  Call SalSendMsg( tblChildTable, PAM_UNDELETEROWS, 0, 0 )
.head 5 +  Pushbutton: pbQueryTable
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 34
.head 6 -  Class: OurPushbuttonClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: &Query Table - F7
.head 6 -  Window Location and Size
.head 7 -  Left: 0.075"
.head 7 -  Top: 3.135"
.head 7 -  Width:  1.688"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.292"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Keyboard Accelerator: F7
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Picture File Name:
.head 6 -  Picture Transparent Color: Class Default
.head 6 -  Image Style: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Button Appearance: Standard
.head 6 +  Message Actions
.head 7 +  On PAM_CLICK
.head 8 -  Call SalSendMsg( tblChildTable, PAM_QUERY, 0, 0 )
.head 5 -  !
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 1
.head 6 -  Class ChildKey: 46
.head 6 -  Class: Our_Dialog_Box
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfCurrentDate
.head 6 -  Class Child Ref Key: 2
.head 6 -  Class ChildKey: 47
.head 6 -  Class: Our_Dialog_Box
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 4 +  Derived From
.head 5 -  Class: Our_Dialog_Box
.head 4 +  Class Variables
.head 5 -  Number: nRow
.head 5 -  Number: nRowCount
.head 5 -  Window Handle: hWndCol
.head 5 -  Boolean: bEnableDlgSelectPb
.head 5 -  Number: nTotalSelectRows
.head 5 -  Window Handle: hWndMeter
.head 4 +  Instance Variables
.head 5 -  Boolean: bAddRowsAllowed
.head 5 -  Boolean: bSaveRowsAllowed
.head 5 -  Boolean: bClearRowsAllowed
.head 5 -  Boolean: bDeleteRowsAllowed
.head 5 -  Boolean: bUnDeleteRowsAllowed
.head 5 -  Boolean: bOrderTableAllowed
.head 5 -  Boolean: bMoveUpDownRowsAllowed
.head 5 -  Boolean: bQueryTableAllowed
.head 5 -  Boolean: bTablePrintReportAllowed
.head 5 -  Boolean: bSelectPbEnabled
.head 5 -  Boolean: bExitOnSelect
.head 5 -  Boolean: bQueryOnSelect
.head 5 -  Number: nMultipleSelectDirection
.head 5 -  !
.head 5 -  Boolean: bSelect
.head 5 -  Window Handle: hWndSelectParent
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set bAddRowsAllowed = TRUE
.head 6 -  Set bSaveRowsAllowed = TRUE
.head 6 -  Set bClearRowsAllowed = TRUE
.head 6 -  Set bDeleteRowsAllowed = TRUE
.head 6 -  Set bUnDeleteRowsAllowed = TRUE
.head 6 -  Set bOrderTableAllowed = FALSE
.head 6 -  Set bMoveUpDownRowsAllowed = FALSE
.head 6 -  Set bQueryTableAllowed = TRUE
.head 6 -  Set bTablePrintReportAllowed = FALSE
.head 6 -  Set bSelectPbEnabled = FALSE
.head 6 -  Set bSelect = FALSE
.head 6 -  Set bExitOnSelect = TRUE
.head 6 -  Set bQueryOnSelect = FALSE
.head 6 -  Set hWndSelectParent = hWndNULL
.head 6 -  Set nMultipleSelectDirection = nHiToLow
.head 6 -  Call SalSendMsg( hWndForm, PAM_POPFIELDS, 0, 0 )
.head 6 -  Call PopWndHdl( hWndSelectParent, FALSE )
.head 6 -  Call PopNumber( bSelectPbEnabled, FALSE )
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 +  If bAddRowsAllowed = FALSE
.head 7 -  Call SalSendMsg( pbAddRows, PAM_DISABLE, 0, 0 )
.head 6 +  If bSaveRowsAllowed = FALSE
.head 7 -  Call SalSendMsg( pbSaveRows, PAM_DISABLE, 0, 0 )
.head 6 +  If bClearRowsAllowed = FALSE
.head 7 -  Call SalSendMsg( pbClearRows, PAM_DISABLE, 0, 0 )
.head 6 +  If bDeleteRowsAllowed = FALSE
.head 7 -  Call SalSendMsg( pbDeleteRows, PAM_DISABLE, 0, 0 )
.head 6 +  If bUnDeleteRowsAllowed = FALSE
.head 7 -  Call SalSendMsg( pbUnDeleteRows, PAM_DISABLE, 0, 0 )
.head 6 +  If bOrderTableAllowed = FALSE
.head 7 -  Call SalSendMsg( pbOrderTable, PAM_DISABLE, 0, 0 )
.head 6 +  If bQueryTableAllowed = FALSE
.head 7 -  Call SalSendMsg( pbQueryTable, PAM_DISABLE, 0, 0 )
.head 6 +  If bMoveUpDownRowsAllowed = FALSE
.head 7 -  Call SalSendMsg( pbMoveTblRowsUp, PAM_DISABLE, 0, 0 )
.head 7 -  Call SalSendMsg( pbMoveTblRowsDown, PAM_DISABLE, 0, 0 )
.head 6 +  If bTablePrintReportAllowed = FALSE
.head 7 -  Call SalSendMsg( pbPrintTableReport, PAM_DISABLE, 0, 0 )
.head 6 +  If bSelectPbEnabled = FALSE
.head 7 -  Call SalSendMsg( pbSelectRows, PAM_HIDE, 0, 0 )
.head 6 +  If bQueryOnSelect
.head 7 -  Call SalPostMsg( tblChildTable, PAM_QUERY, 0, 0 )
.head 6 +  Else
.head 7 -  Call SalPostMsg( tblChildTable, PAM_POPULATE, 0, 0 )
.head 5 +  On SAM_Close
.head 6 +  If NOT TableForgetChanges( tblChildTable, tblChildTable.bEdit )
.head 7 -  Return FALSE
.head 6 +  If lParam
.head 7 -  Return TRUE
.head 5 +  On PAM_SHOW
.head 6 -  Call SalSendMsg( hWndForm, PAM_POPFIELDS, 0, 0 )
.head 6 -  Call SalBringWindowToTop( hWndForm )
.head 6 -  Call SalShowWindow( hWndForm )
.head 6 +  If wParam
.head 7 -  Call SalSendMsg( pbSelectRows, PAM_SHOW, 0, 0 )
.head 6 +  Else
.head 7 -  Call SalSendMsg( pbSelectRows, PAM_HIDE, 0, 0 )
.head 6 +  If bQueryOnSelect
.head 7 -  Call SalSendMsg( tblChildTable, PAM_QUERY, 0, 0 )
.head 5 +  On PAM_HIDE
.head 6 -  Call SalHideWindow( hWndForm )
.head 5 +  On PAM_END
.head 6 -  Call SalDestroyWindow( hWndForm )
.head 5 +  On PAM_LOOKUPFINISH
.head 6 +  If bExitOnSelect
.head 7 -  Call SalSendMsg( pbCancel, SAM_Click, TRUE, 0 )
.head 6 +  Else
.head 7 -  Call SalSendMsg( hWndForm, PAM_HIDE, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  On SAM_Destroy
.head 6 -  Call SalSendMsgToChildren( hWndForm, PAM_ENDPICKDLG, 0, 0 )
.head 3 +  ! Column Class: JanColumnClass
.winattr
.head 4 -  Title:
.head 4 -  Visible? Yes
.head 4 -  Editable? Yes
.head 4 -  Maximum Data Length: Default
.head 4 -  Data Type: String
.head 4 -  Justify: Left
.head 4 -  Width:  Default
.head 4 -  Width Editable? Yes
.head 4 -  Format: Unformatted
.head 4 -  Country: Default
.head 4 -  Input Mask: Unformatted
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Cell Options
.head 5 -  Cell Type? Standard
.head 5 -  Multiline Cell? No
.head 5 -  Cell DropDownList
.head 6 -  Sorted? Yes
.head 6 -  Vertical Scroll? Yes
.head 6 -  Auto Drop Down? No
.head 6 -  Allow Text Editing? Yes
.head 5 -  Cell CheckBox
.head 6 -  Check Value:
.head 6 -  Uncheck Value:
.head 6 -  Ignore Case? Yes
.end
.head 4 -  Description: This should be type of column used with JanChildTable
.head 4 -  Derived From 
.head 4 -  Class Variables 
.head 4 +  Instance Variables 
.head 5 -  String: sREPORTBINDNAME
.head 4 -  Functions 
.head 4 -  List Values 
.head 4 +  Message Actions 
.head 5 +  On SAM_Create
.head 6 -  Set sREPORTBINDNAME = ''
.head 6 -  Call SalSendMsg( hWndItem, PAM_SETINSTANCEVARS, 0, 0 )
.head 5 -  !
.head 5 +  On SAM_Validate
.head 6 -  Call SalSendMsg( SalParentWindow( hWndItem ), PAM_VALIDATE, wParam, lParam )
.head 6 -  Return VALIDATE_Ok
.head 5 +  On SAM_Click
.head 6 -  Call SalPostMsg( hWndItem, PAM_CHECKEDIT, wParam, lParam )
.head 5 +  On SAM_SetFocus
.head 6 -  Call SalPostMsg( hWndItem, PAM_CHECKEDIT, wParam, lParam )
.head 5 +  On PAM_CHECKEDIT
.head 6 +  If SalSendMsg( hWndItem, PAM_EDITCHECK, wParam, lParam )
.head 7 -  Return TRUE
.head 6 +  Else 
.head 7 -  Call SalTblKillEdit( hWndForm )
.head 7 -  Return FALSE
.head 5 +  On PAM_EDITCHECK
.head 6 -  Return TRUE
.head 5 +  On PAM_DATAVAL
.head 6 -  Return TRUE
.head 5 +  On PAM_ENABLECHILDSELECTPB
.head 6 -  Return TRUE
.head 3 +  ! Child Table Class: JanChildTable
.winattr
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Default
.head 6 -  Width Editable? Yes
.head 6 -  Height: Default
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Dark Blue
.head 5 -  Background Color: Sky
.head 5 -  View: Table
.head 5 -  Allow Row Sizing? No
.head 5 -  Lines Per Row: Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Default
.head 5 -  Discardable? Yes
.head 4 -  Next Class Child Key: 3
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.end
.head 4 -  Description: 
.head 4 -  Derived From 
.head 4 +  Contents 
.head 5 +  OurColumnClass: colRowId
.head 6 -  List Values 
.head 6 +  Message Actions 
.head 7 +  On PAM_SETINSTANCEVARS
.head 8 -  Set OurColumnClass.bInsert = FALSE
.head 8 -  Set OurColumnClass.bUpdate = FALSE
.head 7 +  On PAM_SQL
.head 8 +  If OurColumnClass.bPopulateColumn
.head 9 -  Call BuildSQL(  wParam, hWndItem, sRowIdColumn )
.head 9 -  Return TRUE
.head 8 +  Else 
.head 9 -  Return FALSE
.head 7 +  On PAM_SQLROWID
.head 8 +  If OurColumnClass.bPopulateColumn
.head 9 -  Call BuildSQL(  wParam, hWndItem, sRowIdColumn )
.head 9 -  Return TRUE
.head 8 +  Else 
.head 9 -  Return FALSE
.head 7 +  On PAM_INITIALIZE
.head 8 -  Call SalClearField( hWndItem )
.head 7 +  On PAM_COPYROWINFOFROM
.head 8 -  Call SalTblFetchRow( hWndForm, lParam )
.head 8 -  Set sTemp = colRowId
.head 7 +  On PAM_COPYROWINFOTO
.head 8 -  Call SalTblFetchRow( hWndForm, lParam )
.head 8 -  Set colRowId = sTemp
.head 4 +  Class Variables 
.head 5 -  String: sTmpStr
.head 5 -  String: sParentName
.head 5 -  String: sTableName
.head 5 -  String: sQueryTmpStr
.head 5 -  String: sRowIdColumn
.head 5 -  Window Handle: hWndTemp
.head 5 -  Window Handle: hWndQueryDlg
.head 5 -  !
.head 5 -  Number: nRow
.head 5 -  Number: nLastRow
.head 5 -  Boolean: bRowsConsequtive
.head 5 -  Number: nNumRows
.head 5 -  !
.head 5 -  String: sTemp
.head 5 -  !
.head 5 -  Boolean: bReportTableSelectedRowsOnly
.head 5 -  Number: nReportTableRow
.head 5 -  String: sRepInto
.head 5 -  String: sRepBind
.head 4 +  Instance Variables 
.head 5 -  String: sTABLEPOPSTATEMENT
.head 5 -  String: sTableHeading
.head 5 -  String: sReportFileName
.head 5 -  Number: nReportPrintOrView
.head 5 -  Boolean: bSelectFirstRow
.head 5 -  Boolean: bGetSaveConfirmation
.head 5 -  Boolean: bAddRowBellow
.head 5 -  Number: nTableFillType
.head 5 -  Number: nSelectType
.head 5 -  Window Handle: hWndRowNewColumn
.head 5 -  String: sQueryDialogName
.head 5 -  !
.head 5 -  Sql Handle: hLocalSqlPopTbl
.head 5 -  Boolean: bLocalSqlPopTbl
.head 5 -  Sql Handle: hLocalSqlDoTbl
.head 5 -  Boolean: bLocalSqlDoTbl
.head 5 -  Window Handle: hWndFocusColumn
.head 5 -  Boolean: bEdit
.head 5 -  !
.head 4 +  Functions 
.head 5 +  Function: CopyTableRowFromTo
.head 6 -  Description: 
.head 6 +  Returns 
.head 7 -  Boolean: 
.head 6 +  Parameters 
.head 7 -  Window Handle: hWndTable
.head 7 -  Number: nFromRow
.head 7 -  Number: nToRow
.head 6 -  Static Variables 
.head 6 +  Local variables 
.head 7 -  Window Handle: hWndChild
.head 7 -  Number: nColumnType
.head 7 -  !
.head 7 -  Boolean: bTmpFromROW_Edited
.head 7 -  Boolean: bTmpFromROW_Hidden
.head 7 -  Boolean: bTmpFromROW_HideMarks
.head 7 -  Boolean: bTmpFromROW_MarkDeleted
.head 7 -  Boolean: bTmpFromROW_New
.head 7 -  Boolean: bTmpFromROW_Selected
.head 7 -  Boolean: bTmpFromROW_UnusedFlag1
.head 7 -  ! Boolean: bTmpFromROW_UnusedFlag2
.head 6 +  Actions 
.head 7 -  Set bTmpFromROW_Edited = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_Edited )
.head 7 -  Set bTmpFromROW_Hidden = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_Hidden )
.head 7 -  Set bTmpFromROW_HideMarks = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_HideMarks )
.head 7 -  Set bTmpFromROW_MarkDeleted = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_MarkDeleted )
.head 7 -  Set bTmpFromROW_New = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_New )
.head 7 -  Set bTmpFromROW_Selected = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_Selected )
.head 7 -  Set bTmpFromROW_UnusedFlag1 = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_UnusedFlag1 )
.head 7 -  ! Set bTmpFromROW_UnusedFlag2 = SalTblQueryRowFlags( hWndForm, nFromRow, ROW_UnusedFlag2 )
.head 7 -  !
.head 7 -  Set hWndChild = SalGetFirstChild( hWndTable, TYPE_TableColumn )
.head 7 +  While hWndChild != hWndNULL
.head 8 -  !
.head 8 -  Set nColumnType = SalGetDataType( hWndChild )
.head 8 -  Call SalSendMsg( hWndChild, PAM_COPYROWINFOFROM, nColumnType, nFromRow )
.head 8 -  Call SalSendMsg( hWndChild, PAM_COPYROWINFOTO, nColumnType, nToRow )
.head 8 -  !
.head 8 -  Set hWndChild = SalGetNextChild( hWndChild, TYPE_TableColumn )
.head 7 -  !
.head 7 -  Call SalTblSetRowFlags( hWndForm, nToRow, ROW_Edited, bTmpFromROW_Edited )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nToRow, ROW_Hidden, bTmpFromROW_Hidden )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nToRow, ROW_HideMarks, bTmpFromROW_HideMarks )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nToRow, ROW_MarkDeleted, bTmpFromROW_MarkDeleted )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nToRow, ROW_New, bTmpFromROW_New )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nToRow, ROW_Selected, bTmpFromROW_Selected )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nToRow, ROW_UnusedFlag1, bTmpFromROW_UnusedFlag1 )
.head 7 -  ! Call SalTblSetRowFlags( hWndForm, nToRow, ROW_UnusedFlag2, bTmpFromROW_UnusedFlag2 )
.head 5 +  Function: SetSqlPositions
.head 6 -  Description: 
.head 6 -  Returns 
.head 6 +  Parameters 
.head 7 -  Window Handle: hWndTable
.head 6 -  Static Variables 
.head 6 +  Local variables 
.head 7 -  Window Handle: hWndChild
.head 7 -  Number: nColPosition
.head 6 +  Actions 
.head 7 -  Set nColPosition = 0
.head 7 -  Set hWndChild = SalGetFirstChild( hWndTable, TYPE_TableColumn )
.head 7 +  While hWndChild != hWndNULL
.head 8 -  !
.head 8 +  If SalSendMsg( hWndChild, PAM_CHECKSQLPOS, 0, 0 )
.head 9 -  Set nColPosition = nColPosition + 1
.head 9 -  Call SalSendMsg( hWndChild, PAM_SETSQLPOS, nColPosition, 0 )
.head 8 -  !
.head 8 -  Set hWndChild = SalGetNextChild( hWndChild, TYPE_TableColumn )
.head 4 +  Message Actions 
.head 5 +  On PAM_POPULATE
.head 6 -  Set sRowIdColumn = sROWID
.head 6 -  Call NewTablePopulate( hWndForm, hLocalSqlPopTbl, nSelectType, sSQLPOPTABLENAME, sSQLWHERE, sORDERBY, sCurrentBuildWhere, bSelectFirstRow, nTableFillType, PAM_SQL )
.head 5 +  On PAM_REPOPULATE
.head 6 -  Set sRowIdColumn = sROWID
.head 6 -  Call TableRePopulate( hWndForm, hLocalSqlPopTbl, nSelectType, sSQLPOPTABLENAME, sCurrentBuildWhere, bSelectFirstRow, nTableFillType, PAM_SQL )
.head 5 +  On PAM_SEARCH
.head 6 -  Call PopWndHdl( hWndQueryDlg, TRUE )
.head 6 -  Call SalSendMsg( hWndQueryDlg, PAM_PUSHFIELDS, 0, 0 )
.head 6 -  Call SalSendMsg( hWndForm, PAM_POPFIELDS, 0, 0 )
.head 6 -  Set sRowIdColumn = sROWID
.head 6 -  Call NewTableSearch( hWndForm, hWndQueryDlg, hLocalSqlPopTbl, nSelectType, sSQLPOPTABLENAME, sSQLWHERE, sORDERBY, sCurrentBuildWhere, bSelectFirstRow, nTableFillType, PAM_SQL )
.head 6 -  Return TRUE
.head 5 +  On PAM_QUERY
.head 6 +  If NOT TableForgetChanges( hWndForm, bEdit )
.head 7 -  Return FALSE
.head 6 -  Call SalWaitCursor( TRUE )
.head 6 +  If sQueryDialogName != ''
.head 7 -  Call SalSendMsg( hWndForm, PAM_PUSHFIELDS, 0, 0 )
.head 7 -  Call PushWndHdl( hWndForm )
.head 7 +  If SalModalDialogFromStr( sQueryDialogName, hWndForm )
.head 8 -  Call SalWaitCursor( FALSE )
.head 8 -  Return TRUE
.head 7 +  Else 
.head 8 -  Call SalWaitCursor( FALSE )
.head 8 -  Return FALSE
.head 6 -  Call SalWaitCursor( FALSE )
.head 5 +  On PAM_RESET
.head 6 -  Call PopWndHdl( hWndFocusColumn, TRUE )
.head 6 -  Call TableReset( hWndForm, hWndFocusColumn )
.head 5 +  On PAM_DELETEROWS
.head 6 -  Call TableDeleteRows( hWndForm )
.head 5 +  On PAM_UNDELETEROWS
.head 6 -  Call TableUnDeleteRows( hWndForm )
.head 5 +  On PAM_CLEARSELECTIONS
.head 6 -  Call ClearSelections( hWndForm )
.head 5 +  On PAM_WRITEINSERTSUPDATES
.head 6 -  Set sRowIdColumn = sROWID
.head 6 -  Return NewTableSaveChanges( hWndForm, hLocalSqlDoTbl, sTableHeading, sSQLTABLENAME, sSQLWHEREROWID, bEdit, bGetSaveConfirmation )
.head 5 +  On PAM_NOROWS
.head 6 -  Call SalMessageBox( 'No rows match the search criteria', sTableHeading, MB_Ok )
.head 5 +  On PAM_ADDROW
.head 6 +  If bAddRowBellow
.head 7 -  Call TableAddRowNewBellow( hWndForm, hWndRowNewColumn )
.head 6 +  Else 
.head 7 -  Call TableAddRowNew( hWndForm, hWndRowNewColumn )
.head 5 +  On SAM_Create
.head 6 -  Set bLocalSqlPopTbl = SqlConnect( hLocalSqlPopTbl ) 
.head 6 +  If bLocalSqlPopTbl
.head 7 -  Call SqlSetLockTimeout( hLocalSqlPopTbl, SQLTIMEOUT )
.head 7 -  Call SqlSetParameter( hLocalSqlPopTbl, DBP_PRESERVE, TRUE, ''  )
.head 6 +  Else 
.head 7 -  Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 7 -  Return FALSE
.head 6 -  Set bLocalSqlDoTbl = SqlConnect( hLocalSqlDoTbl ) 
.head 6 +  If bLocalSqlDoTbl
.head 7 -  Call SqlSetLockTimeout( hLocalSqlDoTbl, SQLTIMEOUT )
.head 6 +  Else 
.head 7 -  Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 7 -  Return FALSE
.head 6 -  Set bEdit = FALSE
.head 6 -  Set bGetSaveConfirmation = TRUE
.head 6 -  Set sROWID = ' ROWID '
.head 6 -  Set sSQLTABLENAME = ''
.head 6 -  Set sSQLPOPTABLENAME = ''
.head 6 -  Set sSQLWHERE = ''
.head 6 -  Set sORDERBY = ''
.head 6 -  Set sTableHeading =  'Class Declaration Heading'
.head 6 -  Set sReportFileName = ''
.head 6 -  Set nReportPrintOrView = nReportPrint
.head 6 -  !
.head 6 -  Call SalGetItemName( SalParentWindow( hWndForm ), sParentName )
.head 6 -  Call SalGetItemName( hWndForm, sTableName )
.head 6 -  Set sTmpStr = sParentName || '.' || sTableName || '.' || 'colRowId'
.head 6 -  Set sSQLWHEREROWID = ' WHERE ROWID = :' || sTmpStr
.head 6 -  !
.head 6 -  Set bSelectFirstRow = TRUE
.head 6 -  Set bAddRowBellow = FALSE
.head 6 -  Set nTableFillType = TBL_FillNormal
.head 6 -  Set nSelectType = nSELECT
.head 6 -  Set hWndRowNewColumn = hWndNULL
.head 6 -  Set sQueryDialogName = ''
.head 6 -  Call SalSendMsg( hWndForm, PAM_SETINSTANCEVARS, 0, 0 )
.head 5 +  On SAM_Destroy
.head 6 +  If bLocalSqlPopTbl
.head 7 -  Call SqlDisconnect( hLocalSqlPopTbl )
.head 6 +  If bLocalSqlDoTbl
.head 7 -  Call SqlDisconnect( hLocalSqlDoTbl )
.head 5 -  !
.head 5 +  On PAM_MOVESELECTEDROWSUPONE
.head 6 -  ! lParam is assumed to indicate number of rows in table
.head 6 -  ! wParam if not 0 then is assumed to be a ROW_flag which should be set to TRUE
! for every row involved in the movement up one
.head 6 -  Call SalWaitCursor( TRUE )
.head 6 -  Set nRow = TBL_MinRow
.head 6 +  While SalTblFindNextRow( hWndForm, nRow, 0, 0 )
.head 7 -  Call SalTblSetContext( hWndForm, nRow )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_UnusedFlag2, FALSE )
.head 6 -  Set nNumRows = nRow
.head 6 +  If SalSendMsg( hWndForm, PAM_CHECKFORCONSEQUTIVEROWS, 0, 0 )
.head 7 -  Set nRow = TBL_MinRow
.head 7 +  If SalTblFindNextRow( hWndForm, nRow, ROW_UnusedFlag2, 0 )
.head 8 -  Call SalTblFetchRow( hWndForm, nRow )
.head 8 +  If nRow > 0
.head 9 -  Call CopyTableRowFromTo( hWndForm, nRow - 1, TBL_TempRow )
.head 9 -  Set nLastRow = nRow
.head 9 -  Set nRow = nRow - 1
.head 9 +  While SalTblFindNextRow( hWndForm, nRow, ROW_UnusedFlag2, 0 )
.head 10 -  Call SalTblFetchRow( hWndForm, nRow )
.head 10 -  Call CopyTableRowFromTo( hWndForm, nRow, nRow - 1 )
.head 10 -  Call SalTblSetRowFlags( hWndForm, nRow - 1, ROW_Selected, TRUE )
.head 10 +  If wParam != 0
.head 11 -  Call SalTblSetRowFlags( hWndForm, nRow - 1, wParam, TRUE )
.head 10 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_UnusedFlag2, FALSE )
.head 10 -  Set nLastRow = nRow
.head 9 -  Call CopyTableRowFromTo( hWndForm, TBL_TempRow, nLastRow )
.head 9 +  If wParam != 0
.head 10 -  Call SalTblSetRowFlags( hWndForm, nLastRow, wParam, TRUE )
.head 6 +  Else 
.head 7 -  Call SalWaitCursor( FALSE )
.head 7 -  Call SalMessageBox( 'Selected rows need to be in one BLOCK to move! Please rectify!', 'Warning', MB_Ok )
.head 7 -  Call SalWaitCursor( TRUE )
.head 6 -  Call SalWaitCursor( FALSE )
.head 5 +  On PAM_MOVESELECTEDROWSDOWNONE
.head 6 -  ! wParam if not 0 then is assumed to be a ROW_flag which should be set to TRUE
! for every row involved in the movement down one
.head 6 -  Call SalWaitCursor( TRUE )
.head 6 -  Set nRow = TBL_MinRow
.head 6 +  While SalTblFindNextRow( hWndForm, nRow, 0, 0 )
.head 7 -  Call SalTblSetContext( hWndForm, nRow )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_UnusedFlag2, FALSE )
.head 6 -  Set nNumRows = nRow
.head 6 +  If SalSendMsg( hWndForm, PAM_CHECKFORCONSEQUTIVEROWS, 0, 0 )
.head 7 -  Set nRow = TBL_MaxRow
.head 7 +  If SalTblFindPrevRow( hWndForm, nRow, ROW_UnusedFlag2, 0 )
.head 8 -  Call SalTblFetchRow( hWndForm, nRow )
.head 8 +  If nRow < nNumRows - 1
.head 9 -  Call CopyTableRowFromTo( hWndForm, nRow + 1, TBL_TempRow )
.head 9 -  Set nLastRow = nRow
.head 9 -  Set nRow = nRow + 1
.head 9 +  While SalTblFindPrevRow( hWndForm, nRow, ROW_UnusedFlag2, 0 )
.head 10 -  Call SalTblFetchRow( hWndForm, nRow )
.head 10 -  Call CopyTableRowFromTo( hWndForm, nRow, nRow + 1 )
.head 10 -  Call SalTblSetRowFlags( hWndForm, nRow + 1, ROW_Selected, TRUE )
.head 10 +  If wParam != 0
.head 11 -  Call SalTblSetRowFlags( hWndForm, nRow + 1, wParam, TRUE )
.head 10 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_UnusedFlag2, FALSE )
.head 10 -  Set nLastRow = nRow
.head 9 -  Call CopyTableRowFromTo( hWndForm, TBL_TempRow, nLastRow )
.head 9 +  If wParam != 0
.head 10 -  Call SalTblSetRowFlags( hWndForm, nLastRow, wParam, TRUE )
.head 6 +  Else 
.head 7 -  Call SalWaitCursor( FALSE )
.head 7 -  Call SalMessageBox( 'Selected rows need to be in one BLOCK to move! Please rectify!', 'Warning', MB_Ok )
.head 7 -  Call SalWaitCursor( TRUE )
.head 6 -  Call SalWaitCursor( FALSE )
.head 5 +  On PAM_CHECKFORCONSEQUTIVEROWS
.head 6 -  Set nRow = TBL_MinRow
.head 6 -  Set bRowsConsequtive = TRUE
.head 6 -  Set nLastRow = TBL_MinRow
.head 6 +  While SalTblFindNextRow( hWndForm, nRow, ROW_Selected, 0 )
.head 7 -  Call SalTblSetContext( hWndForm, nRow )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_Selected, FALSE )
.head 7 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_UnusedFlag2, TRUE )
.head 7 +  If nLastRow = TBL_MinRow
.head 8 -  Set nLastRow = nRow
.head 7 +  Else If nRow - nLastRow = 1
.head 8 -  Set nLastRow = nRow
.head 7 +  Else 
.head 8 -  Set nLastRow = nRow
.head 8 -  Set bRowsConsequtive = FALSE
.head 6 +  If NOT bRowsConsequtive
.head 7 -  Set nRow = TBL_MinRow
.head 7 +  While SalTblFindNextRow( hWndForm, nRow, ROW_UnusedFlag2, 0 )
.head 8 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_UnusedFlag2, FALSE )
.head 6 -  Return bRowsConsequtive
.head 5 -  !
.head 5 +  On PAM_ORDERTABLE
.head 6 +  If NOT TableForgetChanges( hWndForm, bEdit )
.head 7 -  Return FALSE
.head 6 -  Call SalWaitCursor( TRUE )
.head 6 -  Call SetSqlPositions( hWndForm )
.head 6 -  Call PushWndHdl( hWndForm )
.head 6 -  Call PushWndHdl( hWndForm )
.head 6 -  Call PushString( sCurrentBuildWhere )
.head 6 -  Call SalModalDialog( dlgTblOrderBy, hWndForm )
.head 5 +  On PAM_ENABLE
.head 6 +  If wParam
.head 7 -  Call PopString( sCurrentBuildWhere, TRUE )
.head 7 -  Call SalSendMsg( hWndForm, PAM_REPOPULATE, 0, 0 )
.head 6 -  Call SalWaitCursor( FALSE )
.head 5 -  !
.head 5 +  On PAM_PRINTFULLTABLEREPORT
.head 6 -  Call TableReportPrint( hWndForm, sReportFileName, PAM_REPORTCOLUMNS, nReportPrintOrView )
.head 5 +  On SAM_ReportStart
.head 6 -  Return TRUE
.head 5 +  On SAM_ReportFetchInit
.head 6 -  Return TableReportFetchInit( hWndForm, nReportTableRow, bReportTableSelectedRowsOnly )
.head 5 +  On SAM_ReportFetchNext
.head 6 -  Return TableReportFetchNext( hWndForm, nReportTableRow, bReportTableSelectedRowsOnly )
.head 5 +  On SAM_ReportFinish
.head 6 -  Return TRUE
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
