.head 0 +  Application Description: SQLWindows version 5.0 
.data CLASSPROPSSIZE
0000: 4200
.enddata
.data CLASSPROPS
0000: 4170705061746800 0A006B3A5C63656E 7475726100417070 506174684C656E00
0020: 04000A0000000055 7365476C6F62616C 5061746800040001 0000000000000000
0040: 0000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400800000
0020: 0000000000D80000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF840000 0084000000180300 00A3010000010000 0000000000010000
0060: 000F4170706C6963 6174696F6E497465 6D02000000075769 6E646F777313646C
0080: 674765744F75744E 504144657461696C 73
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000C819DD0A0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: -0.05"
.head 3 -  Top: 0.01"
.head 3 -  Width:  8.025"
.head 3 -  Height: 5.042"
.head 2 +  Options Box Location
.data VIEWINFO
0000: D4188507B80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.625"
.head 3 -  Top: 3.729"
.head 3 -  Width:  4.175"
.head 3 -  Height: 2.156"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 7.163"
.head 3 -  Top: 1.958"
.head 2 -  Fully Qualified External References? Yes
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: myfunc.apl
.head 2 -  File Include: intfunc.apl
.head 2 -  File Include: vtspin.apl
.head 2 -  File Include: vtmeter.apl
.head 2 -  File Include: vtmisc.apl
.head 2 -  File Include: vttblwin.apl
.head 2 -  File Include: JANFLAGS.APL
.head 2 -  File Include: STDWIND.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: ADDRESS.APL
.head 2 -  File Include: ITEM.APL
.head 2 -  File Include: npa.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Dialog Box
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Dark Green
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Green
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Dark Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Number: 0000000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: dd-MMM-yyyy hh:mm:ss AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  !
.head 4 -  ! Number: nSelectedLoads = 95
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1851250907
0000: 6E0F0000F5090000 0000000000000000 02000083000000AC 0300001004000000
0020: 037201E002020000 0000730000000100 000023B003001900 0400000172010302
0040: BA000073D1000100 0068C90300190089 01720402006E0073 0034010000E2035A
0060: 00040003A3060200 009B7300018D00E6 03009619000172E8 0702000046730001
0080: 0000A3FF03001925 0001720802BA0000 73D1000100006818 040004008D030B02
00A0: 006E007300360100 1C045A00190001A2 720C0200001B7300 01008D0035040096
00C0: 19000172E80D0200 00467300010000A3 4E0400043500037A 04BA000073D90001
00E0: 0068520400190089 01727B04006E0073 00340100006B045A 00190001A2727C04
0100: 00001B730001008D 0084040016040002 7201E87D04000066 7300010023880400
0120: 3B01020000077201 630C800100260600 0073C90001000068 8C04000400080102
0140: 723B0D0000FE00C1 80010000003F9004 9A00040001A33C0D 00007F80F2010000
0160: 8F940400D6040003 E0C7100000004673 00010000A3980400 1925000172C810BA
0180: 000073D100010000 68B1040019008901 72C910006E007300 34010000CA045A00
01A0: 040003A3CB100000 9B7300018D00CE04 009619000172E8CC 1000004673000100
01C0: 00A3E70400192500 0172CD10BA000073 D100010000610500 0004008D03CF1000
01E0: 6E00730036010004 055A00190001A272 D01000001B730001 008D001D05009619
0200: 000172E8D1100000 4673000100002336 05000400350003D3 10BA000073D90001
0220: 00683A0500190089 0172D410006E0073 003401000053055A 00190001A272D510
0240: 00001B730001008D 006C0500D6040003 E8D7100000667300 0100A37005001925
0260: 000172D810BA0000 73D1000100006889 05001900890172D9 10006E0073003401
0280: 0000A2055A000400 03A3DB1000009B73 00018D00A6050096 19000172E8DC1000
02A0: 00467300010000A3 BF05001925000172 DD10BA000073D100 01000068D8050004
02C0: 000D03081300006E 007300360100DC05 5A00190001A27209 1300001B73000100
02E0: 8D00F50500961900 0172E80A13000046 7300010000A30E06 00043500036B15B8
0300: 00000073D9000100 6812060019008901 726C15006E007300 340100002B065A00
0320: 040002A36D150000 9B7300018D002F06 00D6040002E86E15 00006673000100A3
0340: 3306000435000387 15BA000073D90001 0068370600190089 01728815006E0073
0360: 003401000050065A 00190001A2728915 00001B730001008D 00690600D6040003
0380: E88B150000667300 0100A36D06001925 0001728C15BA0000 73D1000100006886
03A0: 060019008901728D 15006E0073003401 00009F065A000400 03A38F1500009B73
03C0: 00018D00A3060096 19000172E8901500 00467300010000A3 BC06001925000172
03E0: 9115BA000073D100 01000068D5060004 000D035C1600006E 007300360100D906
0400: 5A00190001A2725D 1600001B73000100 8D00F20600D60400 02E85E1600006673
0420: 000100A3F6060004 3500025F16BA0000 73D900010068FA06 0004008D03781600
0440: 6E007300360100FE 065A00190001A072 01791600001B7300 01000D0017070000
0460: 9619000172E87A16 0000467300010000 A330070004350003 7C16BA000073D900
0480: 0100683407001900 8901727D16006E00 7300340100004D07 5A00190001A2727E
04A0: 1600001B73000100 8D00660700D60400 03E04F1700000066 73000100A36A0700
04C0: 19250001725017BA 000073D100010000 6883070019008901 725117006E007300
04E0: 340100009C075A00 040003A38B170000 9B7300018D00A007 009619000172E88C
0500: 1700004673000100 00A3B90700043500 028D17BA000073D9 00010068BD070004
0520: 008D028E17006E00 7300360100C1075A 00040003A3A81700 009B7300018D00C5
0540: 07009619000172E8 A917000046730001 0000A3DE07001925 000172AA17BA0000
0560: 73D10001000068F7 070004008D03AB17 006E007300360100 FB075A00190001A2
0580: 72AC1700001B7300 01000D0014080000 9619000172E8AD17 0000467300010000
05A0: A32D080004350003 2618B800000073D9 0001006831080019 008901722718006E
05C0: 007300340100004A 085A00190001A272 281800001B730001 008D00630800D604
05E0: 0003E0071A000000 6673000100A36708 001925000172081A BA000073D1000100
0600: 0068800800190089 0172091A006E0073 0030010000009908 5A00040003A30B1A
0620: 00009B7300018D00 9D08009619000172 E80C1A0000467300 010000A3B6080019
0640: 250001720D1ABA00 0073D10001000068 CF080004008D0370 1A006E0073003601
0660: 00D3085A00190001 A272711A00001B73 0001008D00EC0800 9619000172E8721A
0680: 0000467300010000 8305090000043500 03741ABA000073D9 0001006809090019
06A0: 0081017201751A00 6E00730034010000 22095A00190001A2 72761A00001B7300
06C0: 01008D003B0900D6 040003E0361B0000 006673000100A33F 0900192500017237
06E0: 1BBA000073D10001 0000685809001900 890172381B006E00 7300340100007109
0700: 5A00040003A33A1B 00009B7300018D00 7509009619000172 E83B1B0000467300
0720: 010000A38E090019 250001723C1BBA00 0073D10001000068 A7090004008D033E
0740: 1B006E0073003601 00AB095A00190001 A2723F1B00001B73 0001008D00C40900
0760: 9619000172E8401B 0000467300010000 A3DD090004350003 421BBA000073D900
0780: 010068E109001900 890172431B006E00 730034010000FA09 5A00190001A27244
07A0: 1B00001B73000100 0D00130A0000D604 0003E8461B000066 73000100A3170A00
07C0: 1925000172471BBA 000073D100010000 68300A0019008901 72481B006E007300
07E0: 34010000490A5A00 040003A34A1B0000 9B7300018D004D0A 009619000172E84B
0800: 1B00004673000100 00A3660A00192500 01724C1BBA000073 D100010000687F0A
0820: 0004000D03CD1D00 006E007300360100 830A5A00190001A2 72CE1D00001B7300
0840: 01008D009C0A0096 19000172E8CF1D00 00467300010000A3 B50A0004350003D1
0860: 1DBA000073D90001 0068B90A00190089 0172D21D006E0073 0034010000D20A5A
0880: 00190001A272D31D 00001B730001008D 00EB0A00D6040003 E0431E0000006673
08A0: 000100A3EF0A0019 25000172441EBA00 0073D10001000060 080B000019008901
08C0: 72451E006E007300 34010000210B5A00 190001A272AE1E00 001B730001008D00
08E0: 3A0B00D6040003E0 8722000000667300 0100A33E0B001925 0001728822BA0000
0900: 73D1000100006857 0B00190089017289 22006E0073003401 0000700B5A001900
0920: 0182722E26000000 1B730001008D0089 0B009619000172E0 2B2D000000467300
0940: 010000A3A20B0019 250001722C2DBA00 0073D10001000068 BB0B001900890172
0960: 2D2D006E00730034 010000D40B5A0019 0001A2722E2D0000 1B730001008D00ED
0980: 0B009619000172E0 CF37000000467300 01000083060C0000 1925000172D037BA
09A0: 000073D100010000 681F0C0019000104 7201FD3A00006E00 7300360100380C5A
09C0: 00190001B272D810 001B730001008D00 510C00D404000003 F40B000066730001
09E0: 00A3550C00192500 01720C00BD0073D1 00010000686E0C00 19004901720D0000
0A00: 6F730034010000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 546522884
0000: B70A0000EB060000 0000000000000000 0200000F00FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F6C003C00 00154F0075724672
0040: 6D576E6400576974 684368696C006454 626CB8000000F006 0000001019000000
0060: 0172013010000000 FA01007300000001 0000009B19001925 0001721100EC0000
0080: FAD1000100000032 0000000400000001 037201120000007B FA00360100360058
00A0: 0000190001C27213 0000001EFA000100 0D004F0000009619 000172B00F000000
00C0: FA47000100008368 000000043500035C 00EC0000FAD90001 001001806C000001
00E0: 002100124F75446C F8675769FFEC0006 002D190001726D0F 0042880273000001
0100: 0036001900194B00 017210DB0042A300 010000CD320004DA 000311F600426C00
0120: 010036B3001900B4 017212003D420001 DA00004F2C001900 01726D1300428F00
0140: 010036006800046B 000314D800000042 B30001000101801D 0000000200000000
0160: 145069636B00496E 746F5461626CE065 5062436C60400000 0002006F04000D03
0180: 08000000637E0273 00B4010000045900 190001C272090000 001E7E0001000D00
01A0: 0180D30000000003 0000000F4FE2755F 4368385F5461E401 D2001000005B0400
01C0: 02C0720116000000 18BA02730001006D 000400D6040002B0 17000000BA670001
01E0: 0093080000043500 021800EC0000BAD9 000100600C000000 04004D021900007B
0200: BA00B60100105900 040002C31A000000 9EBA00014D001400 009619000172B01C
0220: 000000BA47000100 00832D0000001925 0001721D00ED00BA D100010000604600
0240: 000019000901721E 0000007BBA003401 00005F0058000019 0004C07201200000
0260: 009EBA00010D0078 0000009619000172 B021000000BA4700 0100000B91000004
0280: 003500022200EC00 00BAD90001006095 00000004000D0223 0000007BBA00B601
02A0: 0099580000190001 C272250000001EBA 0001000D00B20000 009619000172B026
02C0: 000000BA47000100 0083CB0000000435 00022700EC0000BA D900010060CF0000
02E0: 0004000D02280000 007BBA0036010001 8060BE0000000400 40104E65774F7543
0300: CE685461BF00DE00 049A00020C00C600 D802736800010000 04B300040086020D
0320: 0000003DD80001DB 0008AC0004000261 0E000000D8CF0001 36000C00046B0002
0340: 0FDB00D8B3000100 CD100004DA000210 F600D86C00010014 B3000400B4037211
0360: 003DD800019B0018 00AC000400036D12 00D8CF000126001C 0000194B00017214
0380: DB00D8A300010000 C135000000195200 01721500F600D868 000100004EB00000
03A0: 001900B401721600 3DD800011A000067 00002C0019000172 6D1700D88F000100
03C0: 1600800000046B00 0219DB00D8B30001 00C1840000001912 0001721B0000F600
03E0: D868000100009DB1 00001900B401721C 003DD800011A0000 B60000AC00040002
0400: 6D1D00D8CF000106 00BA000000046B00 021EDB00D8B30001 002101802D000005
0420: C00000000E4F7580 6F6C756D6E436C93 B8000006BD000435 000205008D00F002
0440: 73D1000100006604 0004004D02060000 7BF000B601000859 00040002C3070000
0460: 009EF000016D000C 00D6040002B60800 F0670001009B1000 04B5000209ED00F0
0480: D900010066140019 000901720A000000 7BF0003401000001 80662D0006000811
04A0: 4F75446174618046 69656C64436C9F00 06BD0004B5000205 8D00FC0273D10001
04C0: 000066040004006D 0206007BFC00B601 00085900040002DB 07009EFC00016D00
04E0: 0C00D6040002B608 00FC670001009B10 0004B5000209ED00 FCD9000100661400
0500: 19006901720A007B FC00340100000180 440400000700004E 1154625140756572
0520: 79446C42106F7822 00000100BD0004B5 00031B0D001A0373 00D9000100980180
0540: 04000801000C636C 7363620047656E65 72616C22A2000001 0000B70400B60206
0560: 0031F8037300011B 0001801D23000900 000E08634F755365 6173006F6E596561
0580: 724000D100020000 5B190001DE720010 4C0473000001006D 0019009604000272
05A0: B607004C67000100 6301800400840A00 00134F7500526164 696F42757470746F
05C0: 6E43734422000001 00006F04006D0206 00635E0473003601 0001800604000B00
05E0: 00000810636C546F 6F6C005469705769 6E646F8877220000 0100DE0004DA0003
0600: 0586008E0773006C 000100018C801D00 0C0010000D636C53 656E0064456D6169
0620: 6C7340A300020000 B71900BC01720031 EE07730001DA0000 192C00040002726D
0640: 0600EECF00018600 0180190008000D00 000C6777004D6F75 736557686518656C
0660: 22000100BD0019A5 0001720A3D007300 D100010000000180 810000000E000100
0680: 0863514F456D07C0 000000067B00194B 000172051B006608 73A20000010000CD
06A0: 190019D200017208 F600666800010000 32B3001900A40172 0B00003D6600011A
06C0: 00004B00002C0019 000172690E000066 8F00010006006400 0000194B00017211
06E0: DB0066A300010000 C17D00000004D000 01027214FE008380 010000007F
.enddata
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control: cSpinField
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  Dialog Box: dlgGetOutNPADetails
.head 2 -  Class: Our_Dialog_Box
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Outstanding Non Propagating Agreements Report
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 2.463"
.head 4 -  Top: 1.604"
.head 4 -  Width:  5.813"
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 2.573"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Gray
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Gray
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbCancel
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: Our_Dialog_Box
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: OurPushbuttonClass
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.775"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Enter
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: OK.BMP
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 +  Message Actions
.head 6 +  On PAM_CLICK
.head 7 -  Set sYear = cSeasonYear.GetNumber( )
.head 7 -  Set nYear = SalStrToNumber( sYear )
.head 7 -  Call PushNumber( nType )
.head 7 -  Call PushNumber( nYear )
.head 7 -  Call PushString( sCompany )
.head 7 -  Call SalSendMsg( pbCancel, SAM_Click, 0, TRUE )
.head 2 +  Contents
.head 3 -  Background Text: Season
.head 4 -  Resource Id: 2341
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 1.288"
.head 5 -  Top: 0.698"
.head 5 -  Width:  0.663"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Right
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Gray
.head 3 +  Custom Control: cSeasonYear
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: cOurSeasonYear
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.0"
.head 6 -  Top: 0.646"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 +  Message Actions
.head 5 +  On PAM_SETINSTANCEVARS
.head 6 -  Set cSeasonYear.bEditable = TRUE
.head 3 +  ! cOurSpinField: cNPAYear
.head 4 +   Message Actions 
.head 5 +   On PAM_SETINSTANCEVARS
.head 6 -   Call cNPAYear.SetNumberProperties( 0, 99, 1, 0 )
.head 3 +  Radio Button: rbAllCustomers
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: All Customers
.head 4 -  Window Location and Size
.head 5 -  Left: 0.775"
.head 5 -  Top: 0.958"
.head 5 -  Width:  1.588"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Blue
.head 4 -  Background Color: Gray
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set nType = nAllCustomers
.head 5 +  On SAM_Click
.head 6 -  Set nType = nAllCustomers
.head 3 +  Radio Button: rbSelectedLoads
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Selected Loads
.head 4 -  Window Location and Size
.head 5 -  Left: 0.775"
.head 5 -  Top: 1.208"
.head 5 -  Width:  1.588"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Blue
.head 4 -  Background Color: Gray
.head 4 +  Message Actions
.head 5 +  On SAM_Click
.head 6 -  Set nType = nSelectedLoads
.head 3 +  Radio Button: rbFlemings
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Fleming's NPAs
.head 4 -  Window Location and Size
.head 5 -  Left: 2.875"
.head 5 -  Top: 0.958"
.head 5 -  Width:  1.588"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Blue
.head 4 -  Background Color: Gray
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set sCompany = 'FLEMINGS'
.head 5 +  On SAM_Click
.head 6 -  Set sCompany = 'FLEMINGS'
.head 3 +  Radio Button: rbZeeSweet
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Zee Sweet NPAs
.head 4 -  Window Location and Size
.head 5 -  Left: 2.875"
.head 5 -  Top: 1.208"
.head 5 -  Width:  1.588"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Blue
.head 4 -  Background Color: Gray
.head 4 +  Message Actions
.head 5 +  On SAM_Click
.head 6 -  Set sCompany = 'ZEE_SWEET'
.head 3 -  ! Background Text: NPA Year
.winattr
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.975"
.head 5 -  Top: 0.667"
.head 5 -  Width:  0.988"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Center
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Dark Green
.end
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCurrentDate
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: Our_Dialog_Box
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 +  Window Variables
.head 3 -  String: sYear
.head 3 -  String: sCompany
.head 3 -  Number: nYear
.head 3 -  Number: nType
.head 2 +  Message Actions
.head 3 +  On PAM_SETINSTANCEVARS
.head 4 -  Set sDatabase = SqlDatabase
.head 3 +  On SAM_CreateComplete
.head 4 -  ! Call cNPAYear.SetNumber( OurDateYear( dfCurrentDate ) )
.head 4 -  Call SalWaitCursor( FALSE )
.head 1 -  !
.head 1 +  ! OurFormWindow: frmPrintOutstandingNPAs
.head 2 -   Description: 
.head 2 -   Named Menus 
.head 2 -   Menu 
.head 2 +   Tool Bar 
.head 3 -   Contents 
.head 2 +   Contents 
.head 3 +   Data Field: dfDatabase
.head 4 -   Message Actions 
.head 3 +   Data Field: dfCurrentDate
.head 4 +   Message Actions 
.head 5 +   On PAM_NPAGENERALFIELDS
.head 6 -   Call BuildSQL(  wParam,hWndItem,'AgreementDate' )
.head 3 +   Child Table: tblCust
.head 4 +   Contents 
.head 5 +   Column: colRowId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colRowId.bPopulateColumn = FALSE
.head 5 +   Column: colCustNo
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colCustNo.sSQLCOLNAME = 'CUSTOMER_MASTER.CUST_NO'
.head 5 +   Column: colCustName
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colCustName.sSQLCOLNAME = 'CUSTOMER_MASTER.CUST_NAME'
.head 5 +   Column: colBusName
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colBusName.sSQLCOLNAME = 'CUSTOMER_MASTER.BUS_NAME'
.head 5 +   Column: colRegionId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colRegionId.sSQLCOLNAME = 'CUSTOMER_MASTER.REGION_ID'
.head 5 +   Column: colRegionDesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colRegionDesc.bPopulateColumn = FALSE
.head 5 +   Column: colBusAddrL1
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colBusAddrL1.sSQLCOLNAME = 'CUSTOMER_ADDRESS.ADDRESS_1'
.head 5 +   Column: colBusAddrL2
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colBusAddrL2.sSQLCOLNAME = 'CUSTOMER_ADDRESS.ADDRESS_2'
.head 5 +   Column: colBusSuburb
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colBusSuburb.sSQLCOLNAME = 'CUSTOMER_ADDRESS.SUBURB'
.head 5 +   Column: colBusState
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colBusState.sSQLCOLNAME = 'CUSTOMER_ADDRESS.STATE'
.head 5 +   Column: colBusPostcode
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colBusPostcode.sSQLCOLNAME = 'CUSTOMER_ADDRESS.POSTCODE'
.head 5 +   Column: colContactWrkAreaCode
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colContactWrkAreaCode.sSQLCOLNAME = 'CUSTOMER_CONTACTS.WRK_PHONE_CODE'
.head 5 +   Column: colContactWrkPhone
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colContactWrkPhone.sSQLCOLNAME = 'CUSTOMER_CONTACTS.CONTACT_WORK_PHONE'
.head 4 +   Functions 
.head 5 +   Function: GetRegionDesc
.head 6 -   Description: 
.head 6 +   Returns 
.head 7 -   Boolean: 
.head 6 +   Parameters 
.head 7 -   String: sRegionId
.head 7 -   Receive String: sRegionDesc
.head 7 -   Number: nActionType
.head 6 +   Static Variables 
.head 7 -   : fcOurHandle
.head 6 +   Local variables 
.head 7 -   String: sSql
.head 7 -   String: sBind
.head 7 -   String: sInto
.head 7 -   String: sName
.head 7 -  !
.head 7 -   String: sGotRegionDesc
.head 7 -  !
.head 7 -   Number: nInd
.head 6 +   Actions 
.head 7 +   Select Case nActionType
.head 8 +   Case nExecute
.head 9 -   Set sSql = " SELECT Region_Desc 
FROM Region 
WHERE Region_Id = :1 "
.head 9 -   Set sName = 'GETREGDESC'
.head 9 -   Set sBind = ':sRegionId'
.head 9 -   Set sInto = ':sGotRegionDesc'
.head 9 -  !
.head 9 -   Call fcOurHandle.Setup( sSql, sName, sBind, sInto )
.head 9 -   Call SqlVarSetup( fcOurHandle.hSqlHandle )
.head 9 -  !
.head 9 -   Set sRegionDesc = ''
.head 9 -   Set sGotRegionDesc = ''
.head 9 -  !
.head 9 +   If fcOurHandle.Execute( )
.head 10 -   Call fcOurHandle.FetchNext( nInd )
.head 10 -  !
.head 10 -   Set sRegionDesc = sGotRegionDesc
.head 10 -   Return TRUE
.head 9 +   Else 
.head 10 -   Return FALSE
.head 8 +  ! Case nCommit
.head 9 -   Return fcOurHandle.Commit( )
.head 8 +  ! Case nRollback
.head 9 -   Return fcOurHandle.Rollback( )
.head 8 +   Case nDisconnect
.head 9 -   Return fcOurHandle.Disconnect( )
.head 4 -   Window Variables 
.head 4 +   Message Actions 
.head 5 +   On PAM_SETINSTANCEVARS
.head 6 +   If frmPrintOutstandingNPAs.nActionType = nAllCustomers
.head 7 -   Set sSQLTABLENAME = ''
.head 7 -   Set sSQLPOPTABLENAME = 'Customer_Master, Customer_Address, Customer_Contacts'
.head 7 -   Set sROWID = ''
.head 7 -   Set sSQLWHERE = " WHERE Customer_Master.Cust_No = Customer_Address.Cust_No AND
Customer_Address.Main_Address_Flag = 'Y' AND 
Customer_Master.Cust_No = Customer_Contacts.Cust_No AND 
Customer_Contacts.Main_Contact_Flag = 'Y' "
.head 7 -   Set sORDERBY = 'ORDER BY Customer_Master.Region_Id, Customer_Master.Cust_Name, Customer_Master.Cust_No'
.head 6 +   Else 
.head 7 -   Set sSQLTABLENAME = ''
.head 7 -   Set sSQLPOPTABLENAME = 'Load_Customers, Customer_Master, Customer_Address, Customer_Contacts'
.head 7 -   Set sROWID = ''
.head 7 -   Set sSQLWHERE = " WHERE Load_Customers.Load_Id = :frmPrintOutstandingNPAs.sLoadId AND 
Load_Customers.Cust_No = Customer_Master.Cust_No AND 
Customer_Master.Cust_No = Customer_Address.Cust_No AND 
Customer_Address.Main_Address_Flag = 'Y' AND 
Customer_Master.Cust_No = Customer_Contacts.Cust_No AND 
Customer_Contacts.Main_Contact_Flag = 'Y' "
.head 7 -   Set sORDERBY = ' ORDER BY Load_Customers.Sequence_No'
.head 5 +   On SAM_FetchRowDone
.head 6 +   If NOT SalIsNull( colRegionId )
.head 7 -   Call GetRegionDesc( colRegionId, colRegionDesc, nExecute )
.head 5 +   On PAM_NOROWS
.head 6 -   Return TRUE
.head 5 +   On SAM_Destroy
.head 6 -   Call GetRegionDesc( '', colRegionDesc, nDisconnect )
.head 6 -   Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 3 +   Child Table: tblOrd
.head 4 +   Contents 
.head 5 +   Column: colRowId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colRowId.bPopulateColumn = FALSE
.head 5 +   Column: colTreeType
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colTreeType.sSQLCOLNAME = 'STOCK_ITEM.TREE_TYPE'
.head 5 +   Column: colCultDesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colCultDesc.sSQLCOLNAME = 'STOCK_ITEM.CULT_DESC'
.head 5 +   Column: colRootDesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colRootDesc.sSQLCOLNAME = 'STOCK_ITEM.ROOT_DESC'
.head 5 +   Column: colConfAmt
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colConfAmt.sSQLCOLNAME = 'CONF_AMT'
.head 5 +   Column: colNPASentFlag
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colNPASentFlag.sSQLCOLNAME = 'NPA_SENT_FLAG'
.head 5 +   Column: colNPASentDate
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SETINSTANCEVARS
.head 8 -   Set colNPASentDate.sSQLCOLNAME = 'NPA_SENT_DATE'
.head 4 -   Functions 
.head 4 -   Window Variables 
.head 4 +   Message Actions 
.head 5 +   On PAM_SETINSTANCEVARS
.head 6 -   Set sSQLTABLENAME = ''
.head 6 -  !
.head 6 +   If frmPrintOutstandingNPAs.nYear < OurDateYear( SalDateCurrent(  ) )
.head 7 -   Set sSQLPOPTABLENAME = 'CUST_ORDER_HiSTORY, STOCK_ITEM'
.head 6 +   Else 
.head 7 -   Set sSQLPOPTABLENAME = 'CUSTOMER_ORDER, STOCK_ITEM'
.head 6 -  !
.head 6 -   Set sROWID = ''
.head 6 -   Set sSQLWHERE = " WHERE Stock_Item_No = Stock_Item.Item_No AND 
Year_Of_Sale = :frmPrintOutstandingNPAs.nYear AND 
Cust_No = :frmPrintOutstandingNPAs.tblCust.colCustNo AND 
NOT NPA_Recd_Flag = 'Y' "
.head 6 -   Set sORDERBY = ''
.head 5 +   On PAM_NOROWS
.head 6 -   Return TRUE
.head 3 +   Pushbutton: pbExit
.head 4 -   Message Actions 
.head 3 -   Frame 
.head 3 +   Pushbutton: pbItemEnq
.head 4 -   Message Actions 
.head 2 +   Functions 
.head 3 +   Function: GetLoadDesc
.head 4 -   Description: 
.head 4 +   Returns 
.head 5 -   Boolean: 
.head 4 +   Parameters 
.head 5 -   String: sLoadId
.head 5 -   Receive String: sLoadDesc
.head 5 -   Number: nActionType
.head 4 +   Static Variables 
.head 5 -   : fcOurHandle
.head 4 +   Local variables 
.head 5 -   String: sSql
.head 5 -   String: sBind
.head 5 -   String: sInto
.head 5 -   String: sName
.head 5 -  !
.head 5 -   String: sGotLoadDesc
.head 5 -  !
.head 5 -   Number: nInd
.head 4 +   Actions 
.head 5 +   Select Case nActionType
.head 6 +   Case nExecute
.head 7 -   Set sSql = " SELECT Load_Description 
FROM Load 
WHERE Load_Id = :1 "
.head 7 -   Set sName = 'GETLOADDESC'
.head 7 -   Set sBind = ':sLoadId'
.head 7 -   Set sInto = ':sGotLoadDesc'
.head 7 -  !
.head 7 -   Call fcOurHandle.Setup( sSql, sName, sBind, sInto )
.head 7 -   Call SqlVarSetup( fcOurHandle.hSqlHandle )
.head 7 -  !
.head 7 -   Set sLoadDesc = ''
.head 7 -   Set sGotLoadDesc = ''
.head 7 -  !
.head 7 +   If fcOurHandle.Execute( )
.head 8 -   Call fcOurHandle.FetchNext( nInd )
.head 8 -  !
.head 8 -   Set sLoadDesc = sGotLoadDesc
.head 8 -   Return TRUE
.head 7 +   Else 
.head 8 -   Return FALSE
.head 6 +  ! Case nCommit
.head 7 -   Return fcOurHandle.Commit( )
.head 6 +  ! Case nRollback
.head 7 -   Return fcOurHandle.Rollback( )
.head 6 +   Case nDisconnect
.head 7 -   Return fcOurHandle.Disconnect( )
.head 2 +   Window Parameters 
.head 3 -   String: saLoadIds[ * ]
.head 3 -   Number: nYear
.head 3 -   Number: nActionType
.head 3 -  ! nActionType of nSelectedLoads, nAllCustomers
.head 2 +   Window Variables 
.head 3 -   String: sRepInto
.head 3 -   String: sRepBind
.head 3 -   String: sReportFile
.head 3 -   Number: nError
.head 3 -  !
.head 3 -   Boolean: bProcessLoads
.head 3 -   Boolean: bProcessCust
.head 3 -   Boolean: bProcessOrders
.head 3 -   Boolean: bPopulateTblCust
.head 3 -   Boolean: bPopulateTblOrd
.head 3 -   Number: nLoadIdsPos
.head 3 -   Number: nCustRow
.head 3 -   Number: nOrderRow
.head 3 -  !
.head 3 -  ! Report Binds
.head 3 -   String: sLoadId
.head 3 -   String: sLoadDescription
.head 3 -  !
.head 2 +   Message Actions 
.head 3 +   On PAM_SETINSTANCEVARS
.head 4 -   Set sDatabase = SqlDatabase
.head 3 +   On SAM_CreateComplete
.head 4 -   Call SalHideWindow( hWndForm )
.head 4 -   Call SalSendMsg( hWndForm, PAM_PRINTNPAS, 0, 0 )
.head 4 -   Call SalWaitCursor( FALSE )
.head 3 +   On PAM_PRINTNPAS
.head 4 -   Call SalWaitCursor( TRUE )
.head 4 -  !
.head 4 -   Set sRepInto = 'Cust_No, Cust_Name, BusName, Region_Desc, Ship_Address_Line1, Ship_Address_Line2,
Suburb, State, Postcode, Contact_Wrk_Ph_Code, Contact_Wrk_Ph, Tree_Type, CultivarDesc, RootDesc,
NPASent, NPASentDate, ConfAmt, Load_Description'
.head 4 -  !
.head 4 -   Set sRepBind = 'frmPrintOutstandingNPAs.tblCust.colCustNo, frmPrintOutstandingNPAs.tblCust.colCustName,
frmPrintOutstandingNPAs.tblCust.colBusName, frmPrintOutstandingNPAs.tblCust.colRegionDesc, 
frmPrintOutstandingNPAs.tblCust.colBusAddrL1, frmPrintOutstandingNPAs.tblCust.colBusAddrL2, 
frmPrintOutstandingNPAs.tblCust.colBusSuburb, frmPrintOutstandingNPAs.tblCust.colBusState, 
frmPrintOutstandingNPAs.tblCust.colBusPostcode, frmPrintOutstandingNPAs.tblCust.colContactWrkAreaCode,
frmPrintOutstandingNPAs.tblCust.colContactWrkPhone, frmPrintOutstandingNPAs.tblOrd.colTreeType, 
frmPrintOutstandingNPAs.tblOrd.colCultDesc, frmPrintOutstandingNPAs.tblOrd.colRootDesc, 
frmPrintOutstandingNPAs.tblOrd.colNPASentFlag, frmPrintOutstandingNPAs.tblOrd.colNPASentDate, 
frmPrintOutstandingNPAs.tblOrd.colConfAmt, frmPrintOutstandingNPAs.sLoadDescription'
.head 4 -  !
.head 4 -   Set sReportFile = 'g:\\apps\\gupta\\reports\\npaoutst.qrp'
.head 4 -   Set nError = 1
.head 4 -   Call SalReportPrint( hWndForm, sReportFile, sRepBind, sRepInto, 1, RPT_PrintAll,0,0, nError )
.head 3 +   On SAM_ReportStart
.head 4 -   Return TRUE
.head 3 +   On SAM_ReportFetchInit
.head 4 -   Set bProcessLoads = TRUE
.head 4 -   Set bProcessCust = FALSE
.head 4 -   Set bProcessOrders = FALSE
.head 4 -  !
.head 4 -   Set bPopulateTblCust = FALSE
.head 4 -   Set bPopulateTblOrd = FALSE
.head 4 -  !
.head 4 -   Set nLoadIdsPos = 0
.head 4 -   Set nCustRow = TBL_MinRow
.head 4 -   Set nOrderRow = TBL_MinRow
.head 4 -   Return TRUE
.head 3 +   On SAM_ReportFetchNext
.head 4 +   Loop 
.head 5 +   If bProcessLoads
.head 6 +   If nActionType = nSelectedLoads
.head 7 -   Set sLoadId = saLoadIds[ nLoadIdsPos ]
.head 7 +   If sLoadId = ''
.head 8 -   Return FALSE
.head 7 +   Else 
.head 8 -   Set bProcessLoads = FALSE
.head 8 -   Set bProcessCust = TRUE
.head 8 -   Set bPopulateTblCust = TRUE
.head 8 -   Set nLoadIdsPos = nLoadIdsPos + 1
.head 8 -  !
.head 8 -   Call GetLoadDesc( sLoadId, sLoadDescription, nExecute )
.head 6 +   Else 
.head 7 -  ! else assumes nAllCustomers
.head 7 -   Set bProcessLoads = FALSE
.head 7 -   Set bProcessCust = TRUE
.head 7 -   Set bPopulateTblCust = TRUE
.head 5 +   If bProcessCust
.head 6 +   If bPopulateTblCust
.head 7 -   Call SalSendMsg( tblCust, PAM_POPULATE, 0, 0 )
.head 7 -   Set bPopulateTblCust = FALSE
.head 6 -  !
.head 6 +   If SalTblFindNextRow( tblCust, nCustRow, 0, 0 )
.head 7 -   Call SalTblFetchRow( tblCust, nCustRow )
.head 7 -   Set bProcessCust = FALSE
.head 7 -   Set bProcessOrders = TRUE
.head 7 -   Set bPopulateTblOrd = TRUE
.head 6 +   Else 
.head 7 -   Set bProcessCust = FALSE
.head 7 -   Set bProcessLoads = TRUE
.head 5 +   If bProcessOrders
.head 6 +   If bPopulateTblOrd
.head 7 -   Call SalSendMsg( tblOrd, PAM_POPULATE, 0, 0 )
.head 7 -   Set bPopulateTblOrd = FALSE
.head 6 -  !
.head 6 +   If SalTblFindNextRow( tblOrd, nOrderRow, 0, 0 )
.head 7 -   Call SalTblFetchRow( tblOrd, nOrderRow )
.head 7 -   Return TRUE
.head 6 +   Else 
.head 7 -   Set bProcessOrders = FALSE
.head 7 -   Set bProcessCust = TRUE
.head 3 +   On SAM_ReportFinish
.head 4 -   Call GetLoadDesc( '', sLoadDescription, nDisconnect )
.head 4 -   Call SalDestroyWindow( hWndForm )
.head 4 -   Call SalWaitCursor( FALSE )
.head 4 -   Return TRUE
.head 1 +  ! Form Window: frmRegion
.winattr
.head 2 -  Class:
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Region
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? No
.head 2 -  Visible? Yes
.head 2 -  Display Settings
.head 3 -  Display Style? Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? No
.head 3 -  Initial State: Maximized
.head 3 -  Maximizable? No
.head 3 -  Minimizable? No
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Yes
.head 3 -  Resizable? No
.head 3 -  Window Location and Size
.head 4 -  Left: 4.029"
.head 4 -  Top: 0.031"
.head 4 -  Width:  3.9"
.head 4 -  Width Editable? Yes
.head 4 -  Height: 4.156"
.head 4 -  Height Editable? Yes
.head 3 -  Form Size
.head 4 -  Width:  Default
.head 4 -  Height: Default
.head 4 -  Number of Pages: Dynamic
.head 3 -  Font Name: Default
.head 3 -  Font Size: Default
.head 3 -  Font Enhancement: Default
.head 3 -  Text Color: Default
.head 3 -  Background Color: Light Green
.end
.head 2 -   Description: 
.head 2 -   Named Menus 
.head 2 +   Menu 
.head 3 +   Popup Menu: &File
.head 4 -   Enabled when: 
.head 4 -   Status Text: 
.head 4 -   Menu Item Name: 
.head 4 +   Menu Item: E&xit
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbExit, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 4 +   Menu Item: &Help
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: 
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbHelp, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 4 +   Menu Item: A&bout...
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: 
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalModalDialog( dlgAbout, hWndForm )
.head 5 -   Menu Item Name: 
.head 3 +   Popup Menu: &Information
.head 4 -   Enabled when: 
.head 4 -   Status Text: 
.head 4 -   Menu Item Name: 
.head 4 +   Menu Item: &Query
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbQuery, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 4 +   Menu Item: O&k Query
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: bShowQueryOk = TRUE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbOk, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 3 +   Popup Menu: Ac&tion
.head 4 -   Enabled when: 
.head 4 -   Status Text: 
.head 4 -   Menu Item Name: 
.head 4 +   Menu Item: &Add
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbAdd, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 4 +   Menu Item: &Save
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbSave, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 3 +   Popup Menu: &Report
.head 4 -   Enabled when: 
.head 4 -   Status Text: 
.head 4 -   Menu Item Name: 
.head 4 +   Menu Item: &Full
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 -   Menu Actions 
.head 5 -   Menu Item Name: 
.head 4 +   Menu Item: &Condensed
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -  ! Send a message to the form to print
.head 6 -   Call SalSendMsg( hWndForm,PAM_PRINTCONDENSED,0,0 )
.head 5 -   Menu Item Name: 
.head 3 +   Popup Menu: F&urther
.head 4 -   Enabled when: 
.head 4 -   Status Text: 
.head 4 -   Menu Item Name: 
.head 4 +   Menu Item: &Loads
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: hWndRegLoad = hWndNULL AND bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbLoads, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 4 +   Menu Item: &Freight
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: hWndFreight = hWndNULL AND bShowQueryOk = FALSE
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( hWndForm.pbFreight, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 4 -   Menu Separator 
.head 4 +   Menu Item: &Specific Region Transport Charges
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: 
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 +   If SalTblAnyRows( tblRegion, ROW_Selected, 0 )
.head 7 -   Call SalWaitCursor( TRUE )
.head 7 -   Call PushString( frmRegion.tblRegion.colRegId )
.head 7 -   Call PushString( frmRegion.tblRegion.colRegdesc )
.head 7 -   Call SalCreateWindow( frmRegTranspChrg, hWndForm )
.head 6 +   Else 
.head 7 -   Call SalMessageBox( 'Please select a Region first!', 'NOTE', MB_Ok )
.head 5 -   Menu Item Name: 
.head 4 -   Menu Separator 
.head 4 +   Popup Menu: &Pull
.head 5 -   Enabled when: 
.head 5 -   Status Text: 
.head 5 -   Menu Item Name: 
.head 5 +   Menu Item: &Rail
.head 6 -   Keyboard Accelerator: (none)
.head 6 -   Status Text: 
.head 6 +   Menu Settings 
.head 7 -   Enabled when: 
.head 7 -   Checked when: 
.head 6 +   Menu Actions 
.head 7 -   Call PullRegionRailOrMail( hWndForm, tblRegion, 'RAIL' )
.head 6 -   Menu Item Name: 
.head 5 +   Menu Item: &Mail
.head 6 -   Keyboard Accelerator: (none)
.head 6 -   Status Text: 
.head 6 +   Menu Settings 
.head 7 -   Enabled when: 
.head 7 -   Checked when: 
.head 6 +   Menu Actions 
.head 7 -   Call PullRegionRailOrMail( hWndForm, tblRegion, 'MAIL' )
.head 6 -   Menu Item Name: 
.head 4 +   Popup Menu: &Invoice
.head 5 -   Enabled when: 
.head 5 -   Status Text: 
.head 5 -   Menu Item Name: 
.head 5 +   Menu Item: &Rail
.head 6 -   Keyboard Accelerator: (none)
.head 6 -   Status Text: 
.head 6 +   Menu Settings 
.head 7 -   Enabled when: 
.head 7 -   Checked when: 
.head 6 +   Menu Actions 
.head 7 -  ! Call InvoiceRegionRailOrMail( hWndForm, tblRegion, 'RAIL' )
.head 6 -   Menu Item Name: 
.head 5 +   Menu Item: &Mail
.head 6 -   Keyboard Accelerator: (none)
.head 6 -   Status Text: 
.head 6 +   Menu Settings 
.head 7 -   Enabled when: 
.head 7 -   Checked when: 
.head 6 +   Menu Actions 
.head 7 -  ! Call InvoiceRegionRailOrMail( hWndForm, tblRegion, 'MAIL' )
.head 6 -   Menu Item Name: 
.head 4 -   Menu Separator 
.head 4 +   Menu Item: &Outstanding NPA Report
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: 
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 +   If nOk = SalModalDialog( dlgGenNPAReport, hWndForm )
.head 7 -   Call PopNumber( nQtr, TRUE )
.head 7 -   Call PopNumber( nYear, TRUE )
.head 7 +   If NOT SalTblAnyRows( frmRegion.tblRegion, ROW_Selected, 0 )
.head 8 -   Set bForRegion = FALSE
.head 8 -   Call SalPostMsg( hWndForm, PAM_PRINTNPAS, TRUE, 0 )
.head 7 +   Else 
.head 8 -   Set ngRow = TBL_MinRow
.head 8 +   While SalTblFindNextRow( frmRegion.tblRegion, ngRow, ROW_Selected, 0 )
.head 9 -   Call SalTblFetchRow( frmRegion.tblRegion, ngRow )
.head 9 -   Set bForRegion = TRUE
.head 9 -   Call SalSendMsg( hWndForm, PAM_PRINTNPAS, TRUE, 0 )
.head 6 +   Else 
.head 7 -   Call SalWaitCursor( FALSE )
.head 5 -   Menu Item Name: 
.head 4 -   Menu Separator 
.head 4 +   Menu Item: &Region Meets
.head 5 -   Keyboard Accelerator: (none)
.head 5 -   Status Text: 
.head 5 +   Menu Settings 
.head 6 -   Enabled when: 
.head 6 -   Checked when: 
.head 5 +   Menu Actions 
.head 6 -   Call SalSendMsg( pbRegionMeets, SAM_Click, 0, 0 )
.head 5 -   Menu Item Name: 
.head 2 +   Tool Bar 
.head 3 -   Contents 
.head 2 +   Contents 
.head 3 +   Data Field: dfDatabase
.head 4 +   Message Actions 
.head 5 +   On SAM_Create
.head 6 +   If SqlDatabase = 'STOCKDEV'
.head 7 -   Set dfDatabase = 'FLEMINGS PLAY SYSTEM'
.head 6 +   Else 
.head 7 -   Set dfDatabase = ''
.head 5 +   On PAM_NOINIT
.head 6 -   Return TRUE
.head 5 +   On PAM_DATAVAL
.head 6 -   Return TRUE
.head 3 +   Data Field: dfCurrDate
.head 4 -   Message Actions 
.head 3 +   Child Table: tblRegion
.head 4 +   Contents 
.head 5 +   Column: colRegId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL( wParam,hWndItem,'REGION_ID' )
.head 7 +   On PAM_DATAVAL
.head 8 +   If SalIsNull( hWndItem )
.head 9 -   Call ErrorMessage( ' Please enter a Region Id first. ', hWndForm, ngRow )
.head 9 -  ! Call SalNumberToStr( ngRow+1, 0, sRow )
.head 9 -  ! Call SalMessageBox( 'On row '||sRow||', The Region Id requires an entry.  Please enter',
 'Region', MB_Ok )
.head 9 -   Call SalTblSetFocusCell( hWndForm, ngRow, hWndItem, -1, -1 )
.head 9 -   Return FALSE
.head 8 -   Return TRUE
.head 7 +   On PAM_COLOURYOURSELF
.head 8 -   Call SalTblSetCellTextColor(hWndItem, COLOR_DarkAqua, TRUE )
.head 7 +   On PAM_COLOURRESET
.head 8 -   Call SalTblSetCellTextColor(hWndItem, COLOR_Default, TRUE )
.head 7 +   On PAM_NotROWID
.head 8 -   Call PushString( 'Region' )
.head 8 -   Return TRUE
.head 7 +   On PAM_RESTOREROWS
.head 8 -   Return TRUE
.head 7 +   On PAM_DISALLOWENTRY
.head 8 -   Call SalTblSetColumnFlags(hWndItem, COL_Editable, FALSE )
.head 7 +   On PAM_ALLOWENTRY
.head 8 -   Call SalTblSetColumnFlags( hWndItem, COL_Editable, TRUE )
.head 7 +   On PAM_QBE
.head 8 -   Set colRegId = colRegId||'%'
.head 8 -   Call PushString( colRegId )
.head 8 -   Call PushString(LIKEOPERAND )
.head 8 -   Call PushString( STRINGFOLLOWING )
.head 8 -   Call PushString( 'REGION.REGION_ID' )
.head 8 -   Return TRUE
.head 7 +   On SAM_Click
.head 8 +   If NOT bRowHeaderClicked
.head 9 +   If NOT SalTblQueryRowFlags( hWndForm, SalTblQueryContext( hWndForm ), ROW_New )
.head 10 -   Call SalTblSetColumnFlags( hWndItem, COL_Editable, FALSE )
.head 9 +   Else 
.head 10 -   Call SalSendMsgToChildren( hWndForm, PAM_ALLOWENTRY, TRUE, 0 )
.head 10 -   Call SalTblSetFocusCell( hWndForm, SalTblQueryContext( hWndForm ), hWndItem, COL_GetPos, COL_GetPos )
.head 8 +   Else 
.head 9 -   Set bRowHeaderClicked = FALSE
.head 5 +   Column: colRegdesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL( wParam,hWndItem,'REGION_DESC' )
.head 7 +   On PAM_NotROWID
.head 8 -   Call PushString( 'Description' )
.head 8 -   Return TRUE
.head 7 +   On PAM_RESTOREROWS
.head 8 -   Return TRUE
.head 7 +   On PAM_COLOURRESET
.head 8 -   Call SalTblSetCellTextColor(hWndItem, COLOR_Default, TRUE )
.head 7 +   On PAM_COLOURYOURSELF
.head 8 -   Call SalTblSetCellTextColor(hWndItem, COLOR_DarkAqua, TRUE )
.head 7 +   On PAM_DATAVAL
.head 8 -   Return TRUE
.head 7 +   On PAM_QBE
.head 8 -   Set colRegdesc = colRegdesc||'%'
.head 8 -   Call PushString( colRegdesc )
.head 8 -   Call PushString(LIKEOPERAND )
.head 8 -   Call PushString( STRINGFOLLOWING )
.head 8 -   Call PushString( 'REGION.REGION_DESC' )
.head 8 -   Return TRUE
.head 7 +   On PAM_TRUCKSHEETFIELDS
.head 8 -   Call BuildSQL(  wParam,hWndItem,'Region_Desc' )
.head 5 +   Column: colFrCode
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL( wParam,hWndItem,'FREIGHT_CODE' )
.head 7 +   On PAM_NotROWID
.head 8 -   Call PushString( 'Description' )
.head 8 -   Return TRUE
.head 7 +   On PAM_RESTOREROWS
.head 8 -   Return TRUE
.head 7 +   On PAM_COLOURRESET
.head 8 -   Call SalTblSetCellTextColor(hWndItem, COLOR_Default, TRUE )
.head 7 +   On PAM_COLOURYOURSELF
.head 8 -   Call SalTblSetCellTextColor(hWndItem, COLOR_DarkAqua, TRUE )
.head 7 +   On PAM_LOOKUPTYPE
.head 8 -   Call PopString( colFrCode, TRUE )
.head 8 -   Call SalSetFieldEdit( hWndItem, TRUE )
.head 8 -  ! Because were are not interested in the description and comments
  we still need to pop them off.
.head 8 -   Call PopString( sTmpStr, TRUE )
.head 8 -   Call PopString( sTmpStr, TRUE )
.head 8 -   Call SalSendMsg( frmRegion.tblRegion, PAM_SETROWEDITFLAG, 0, 0 )
.head 7 +   On PAM_ENABLEFREIGHTCODEPB
.head 8 -   Return TRUE
.head 7 +   On PAM_QBE
.head 8 -   Set colFrCode = colFrCode||'%'
.head 8 -   Call PushString( colFrCode )
.head 8 -   Call PushString(LIKEOPERAND )
.head 8 -   Call PushString( STRINGFOLLOWING )
.head 8 -   Call PushString( 'REGION.FREIGHT_CODE' )
.head 8 -   Return TRUE
.head 7 +   On PAM_DATAVAL
.head 8 +   If SalIsNull( colFrCode )
.head 9 -   Return TRUE
.head 8 +   If NOT FreightCodeExists(  )
.head 9 -   Return FALSE
.head 8 -   Return TRUE
.head 5 +   Column: colRowid
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL( wParam,hWndItem,'ROWID' )
.head 7 +   On PAM_DATAVAL
.head 8 -   Return TRUE
.head 4 -   Functions 
.head 4 +   Window Variables 
.head 5 -   Boolean: bRowHeaderClicked
.head 5 -   String: sTmpStr
.head 4 +   Message Actions 
.head 5 +   On PAM_POPULATE
.head 6 -   Call SalWaitCursor( TRUE )
.head 6 -   Call CallBuildSql( hWndForm,nSELECT, PAM_SQL, REGION, ORDBYREG )
.head 6 -   Call SalTblPopulate( frmRegion.tblRegion, frmRegion.hLocalSqlPopTbl, sgSql, TBL_FillNormal )
.head 6 -   Call SalSendMsgToChildren( frmRegion.tblRegion, PAM_DISALLOWENTRY, 0, 0 )
.head 6 -   Call SalWaitCursor( FALSE )
.head 5 +   On PAM_SETROWEDITFLAG
.head 6 -   Set ngRow = SalTblQueryContext( frmRegion.tblRegion )
.head 6 -   Call SalTblSetRowFlags( frmRegion.tblRegion, ngRow, ROW_Edited, TRUE )
.head 5 +   On PAM_ADDROW
.head 6 -   Call SalTblQueryFocus(hWndForm, ngRow, hWndCol )
.head 6 -   Set ngRow = SalTblInsertRow( hWndForm, ngRow )
.head 6 -   Call SalSendMsgToChildren( frmRegion.tblRegion, PAM_ALLOWENTRY, 0, 0 )
.head 6 -   Call SalTblSetFocusCell( hWndForm, ngRow, colRegId, -1, -1 )
.head 6 -   Return TRUE
.head 5 +   On PAM_WRITEINSERTSUPDATES
.head 6 +   If IDNO = SalMessageBox( 'Are you ready to insert/update/delete the selected rows?',
'Region', MB_YesNo|MB_IconExclamation )
.head 7 -   Return FALSE
.head 6 +   If NOT TableDataVal( hWndForm )
.head 7 -   Return FALSE
.head 6 -   Set bOk = TRUE
.head 6 -   Set ngRow = TBL_MinRow
.head 6 +   While SalTblFindNextRow( hWndForm, ngRow, ROW_New, 0 )
.head 7 -   Call SalTblFetchRow( hWndForm, ngRow )
.head 7 +   If NOT RegionExists( hWndForm )
.head 8 -   Call CallBuildSql( hWndForm,nINSERT, PAM_SQL, REGION, '' )
.head 8 +   If SqlPrepareAndExecute( frmRegion.hLocalSqlDoTbl, sgSql )
.head 9 -   Call SqlCommit( frmRegion.hLocalSqlDoTbl )
.head 8 +   Else 
.head 9 -   Call SqlPrepareAndExecute( frmRegion.hLocalSqlDoTbl, 'rollback' )
.head 8 -  ! Set bOk = SqlImmediate( sgSql )
.head 8 +  ! If bOk
.head 9 -   Call SqlClearImmediate(  )
.head 9 -   Call SalTblSetRowFlags( hWndForm, ngRow, ROW_New|ROW_Edited, FALSE )
.head 8 +  ! Else 
.head 9 -   Call SqlClearImmediate(  )
.head 9 -   Call SqlImmediate( 'commit' )
.head 9 -   Call SqlClearImmediate(  )
.head 9 -   Return FALSE
.head 7 +   Else 
.head 8 -   Call SqlCommit( frmRegion.hLocalSqlDoTbl )
.head 8 -  ! Call SqlImmediate( 'commit' )
.head 8 -  ! Call SqlClearImmediate(  )
.head 8 -   Return FALSE
.head 6 -  ! Call SqlImmediate( 'commit' )
.head 6 -  ! Call SqlClearImmediate(  )
.head 6 +   When SqlError
.head 7 -   Call PushString( REGION )
.head 7 -   Call PushWndHdl( hWndForm )
.head 7 -   Call WhenSqlError(  )
.head 7 -   Call WhenUpdSqlError(  )
.head 6 -   Set ngRow = TBL_MinRow
.head 6 +   While SalTblFindNextRow( hWndForm, ngRow, ROW_Edited, 0 )
.head 7 -   Call SalTblFetchRow( hWndForm, ngRow )
.head 7 -   Call CallBuildSql( hWndForm,nUPDATE, PAM_SQL, REGION,
 WHERECOLROWID )
.head 7 +   If SqlPrepareAndExecute( frmRegion.hLocalSqlDoTbl, sgSql )
.head 8 -   Call SqlCommit( frmRegion.hLocalSqlDoTbl )
.head 7 +   Else 
.head 8 -   Call SqlPrepareAndExecute( frmRegion.hLocalSqlDoTbl, 'rollback' )
.head 7 -  ! Set bOk = SqlImmediate( sgSql )
.head 7 +  ! If bOk
.head 8 -   Call SqlClearImmediate(  )
.head 8 -   Call SalTblSetRowFlags( hWndForm, ngRow, ROW_Edited, FALSE )
.head 7 +  ! Else 
.head 8 -   Call SqlClearImmediate(  )
.head 8 -   Call SqlImmediate( 'commit' )
.head 8 -   Call SqlClearImmediate(  )
.head 8 -   Return FALSE
.head 6 -  ! Call SqlImmediate( 'commit' )
.head 6 -  ! Call SqlClearImmediate(  )
.head 6 +   When SqlError
.head 7 -   Call PushString( REGION )
.head 7 -   Call PushWndHdl( hWndForm )
.head 7 -   Call WhenSqlError(  )
.head 7 -   Call WhenDelSqlError(  )
.head 6 +   If SalTblAnyRows( hWndForm,ROW_MarkDeleted,0 )
.head 7 +   If NOT IfRegionUsed (  )
.head 8 +   If DeleteRegionLoads(  )
.head 9 -   Call SqlPrepare( frmRegion.hLocalSqlDoTbl, 'DELETE FROM REGION WHERE
ROWID = :frmRegion.tblRegion.colRowid' )
.head 9 -   Set bOk = FALSE
.head 9 -   Set bOk = SalTblDoDeletes( hWndForm, frmRegion.hLocalSqlDoTbl, ROW_MarkDeleted )
.head 8 +   Else 
.head 9 -   Set bOk = FALSE
.head 7 +   Else 
.head 8 -   Set bOk = FALSE
.head 6 +   If bOk 
.head 7 -   Call SqlCommit( frmRegion.hLocalSqlDoTbl )
.head 7 -   Call SalMessageBox( 'Row(s) updated.', 'Region',
MB_Ok|MB_IconAsterisk )
.head 7 -   Call SalSendMsg(  hWndForm, PAM_POPULATE, 0, 0 ) 
.head 7 -   Return TRUE
.head 6 +   Else 
.head 7 -   Call SqlPrepareAndExecute( frmRegion.hLocalSqlDoTbl, 'rollback' )
.head 7 -   Call SalSendMsg(  hWndForm, PAM_POPULATE, 0, 0 ) 
.head 7 -   Return FALSE
.head 5 +   On PAM_DELETEROWS
.head 6 +   If SalTblAnyRows( hWndForm, ROW_Selected,0 )
.head 7 -   Set ngRow = TBL_MinRow
.head 7 +   While SalTblFindNextRow( hWndForm, ngRow, ROW_Selected, 0 )
.head 8 -   Call SalTblSetRowFlags( hWndForm,ngRow, ROW_MarkDeleted, TRUE )
.head 8 -   Call SalTblSetRowFlags( hWndForm, ngRow, ROW_Edited|ROW_New, FALSE )
.head 5 +   On PAM_UNDELETEROWS
.head 6 +   If SalTblAnyRows( hWndForm, ROW_Selected,0 )
.head 7 -   Set ngRow = TBL_MinRow
.head 7 +   While SalTblFindNextRow( hWndForm, ngRow, ROW_Selected, 0 )
.head 8 -   Call SalTblSetRowFlags( hWndForm, ngRow, ROW_MarkDeleted, FALSE )
.head 5 +   On PAM_SEARCH
.head 6 -   Call PushWndHdl( frmRegion.tblRegion )
.head 6 -   Call PushNumber( PAM_QBE )
.head 6 -   Call BuildWhereQBE(  )
.head 6 -  ! Need to add an order by statement to the sBuildWhere
.head 6 -   Call PushString( ORDBYREG )
.head 6 -   Call AddOrderByToWhere(  )
.head 6 -   Set bgSearch = TRUE
.head 6 -   Call CallBuildSql( hWndForm,nSELECT, PAM_SQL, REGION, sBuildWhere )
.head 6 -   Call SalTblPopulate( frmRegion.tblRegion, frmRegion.hLocalSqlSrchTbl, sgSql, TBL_FillNormal )
.head 6 -   Call SqlGetResultSetCount( frmRegion.hLocalSqlSrchTbl, ngCount )
.head 6 +   If ngCount = 0
.head 7 -   Call SalPostMsg( frmRegion.tblRegion, PAM_NOROWS, 0, 0 )
.head 6 -   Call SalSendMsg( frmRegion.pbQuery, PAM_ENABLE, 0, 0 )
.head 6 -   Call SalSendMsgToChildren( frmRegion.tblRegion, PAM_DISALLOWENTRY, 0, 0 )
.head 6 -   Call SalSendMsgToChildren( frmRegion, PAM_HIDE, 0, 0 )
.head 5 +   On PAM_RESET
.head 6 -   Call SalTblReset( frmRegion.tblRegion )
.head 6 -   Set ngRow = 0
.head 6 -   Set ngRow = SalTblInsertRow(  frmRegion.tblRegion, ngRow )
.head 6 -   Call SalSendMsgToChildren( frmRegion.tblRegion, PAM_ALLOWENTRY, 0, 0 )
.head 6 -   Call SalTblSetFocusCell(  frmRegion.tblRegion, ngRow, colRegId, -1, -1 )
.head 5 +   On PAM_NOROWS
.head 6 -   Call SalMessageBox( 'No rows match the search criteria',
 'Regions', MB_Ok )
.head 5 +   On SAM_RowHeaderClick
.head 6 -   Set bRowHeaderClicked = TRUE
.head 6 +   If NOT SalTblQueryRowFlags( hWndForm, SalTblQueryContext( hWndForm ), ROW_New )
.head 7 -   Call SalTblSetColumnFlags( hWndItem, COL_Editable, FALSE )
.head 6 +   Else 
.head 7 -   Call SalSendMsgToChildren( hWndForm, PAM_ALLOWENTRY, TRUE, 0 )
.head 5 +   On SAM_Create
.head 6 -   Set bRowHeaderClicked = FALSE
.head 3 +   Child Table: tblMaster
.head 4 +   Contents 
.head 5 +   Column: colWhere2
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_WHEREPOPULATE
.head 8 +   If frmRegion.bForRegion
.head 9 -   Set sBuildWhere = ' WHERE CUSTOMER_MASTER.CUSTOMER_TYPE
 = CUSTOMER_TYPE.CUST_TYPE AND
 CUSTOMER_TYPE.NPA_REQUIRED = \'Y\'
 AND CUSTOMER_MASTER.REGION_ID = :frmRegion.tblRegion.colRegId AND
REGION.REGION_ID = CUSTOMER_MASTER.REGION_ID'
.head 8 +   Else 
.head 9 -   Set sBuildWhere = ' WHERE CUSTOMER_MASTER.CUSTOMER_TYPE 
= CUSTOMER_TYPE.CUST_TYPE AND
 CUSTOMER_TYPE.NPA_REQUIRED = \'Y\' AND
REGION.REGION_ID = CUSTOMER_MASTER.REGION_ID '
.head 5 +   Column: colPOAdd1
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.ADDRESS_1' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Ship_Address_Line1' )
.head 5 +   Column: colPOAdd2
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.ADDRESS_2' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Ship_Address_Line2' )
.head 5 +   Column: colPOSuburb
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.SUBURB' )
.head 7 +   On PAM_DATANOTNULL
.head 8 +   If SalIsNull( hWndItem )
.head 9 -   Return FALSE
.head 8 +   Else 
.head 9 -   Return TRUE
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Suburb' )
.head 5 +   Column: colPOState
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.STATE' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'State' )
.head 5 +   Column: colPOPostcode
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.POSTCODE' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Postcode' )
.head 5 +   Column: colPOACode
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.AREA_CODE' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Contact_Wrk_Ph_Code' )
.head 5 +   Column: colPOPhoneNo
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.PHONE_NO' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Contact_Wrk_Ph' )
.head 5 +   Column: colSHAdd1
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.ADDRESS_1' )
.head 5 +   Column: colSHAdd2
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.ADDRESS_2' )
.head 5 +   Column: colSHSuburb
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.SUBURB' )
.head 7 +   On PAM_DATANOTNULL
.head 8 +   If SalIsNull( hWndItem )
.head 9 -   Return FALSE
.head 8 +   Else 
.head 9 -   Return TRUE
.head 5 +   Column: colSHState
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.STATE' )
.head 5 +   Column: colSHPostcode
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.POSTCODE' )
.head 5 +   Column: colSHACode
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.AREA_CODE' )
.head 5 +   Column: colSHPoneNo
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ADDRESS.PHONE_NO' )
.head 5 +   Column: colCustNo
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 +   If nWhichPopulate = 1
.head 9 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_MASTER.CUST_NO' )
.head 8 +   Else 
.head 9 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_MASTER.CUST_NO' )
.head 7 +   On PAM_NPACUSTBITS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Cust_No' )
.head 5 +   Column: colCustName
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 +   If nWhichPopulate = 1
.head 9 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_MASTER.CUST_NAME' )
.head 8 +   Else 
.head 9 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_MASTER.CUST_NAME' )
.head 7 +   On PAM_NPACUSTBITS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Cust_Name' )
.head 5 +   Column: colBusName
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_MASTER.BUS_NAME' )
.head 7 +   On PAM_NPACUSTBITS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'BusName' )
.head 5 +   Column: colRegion
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_MASTER.REGION_ID' )
.head 5 +   Column: colRegDesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'REGION.REGION_DESC' )
.head 7 +   On PAM_NPACUSTBITS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Region_Desc' )
.head 5 +   Column: colShippingDate
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL2
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'LOAD.SHIPPING_DATE' )
.head 5 +   Column: colShipVia
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL2
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'TRANSPORT_METHOD.TRANSP_DESC' )
.head 5 +   Column: colYr
.head 6 -   List Values 
.head 6 -   Message Actions 
.head 4 -   Functions 
.head 4 +   Window Variables 
.head 5 -   Sql Handle: hLocalSqlPopTbl
.head 5 -   Boolean: bLocalSqlPopTbl
.head 5 -   String: sSQLPOPTABLENAME
.head 5 -   String: sORDERBY
.head 5 -   Number: nWhichPopulate
.head 5 -   String: sCurrentBuildWhere
.head 4 +   Message Actions 
.head 5 +   On PAM_POPULATE
.head 6 -  ! for NPAs
.head 6 -   Call TablePopulate( hWndForm, hLocalSqlPopTbl, colWhere2, nSELECT, sSQLPOPTABLENAME, sORDERBY, sCurrentBuildWhere, FALSE, TBL_FillNormal, PAM_SQL )
.head 5 +   On SAM_Create
.head 6 -   Set bLocalSqlPopTbl = SqlConnect( hLocalSqlPopTbl ) 
.head 6 +   If bLocalSqlPopTbl
.head 7 -   Call SqlSetLockTimeout( hLocalSqlPopTbl, SQLTIMEOUT )
.head 7 -   Call SqlSetParameter( hLocalSqlPopTbl, DBP_PRESERVE, TRUE, ''  )
.head 6 +   Else 
.head 7 -   Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 7 -   Return FALSE
.head 6 -   Set sSQLPOPTABLENAME = ' CUSTOMER_MASTER, CUSTOMER_TYPE, REGION '
.head 6 -   Set sORDERBY = ' ORDER BY CUSTOMER_MASTER.REGION_ID, CUSTOMER_MASTER.CUST_NO '
.head 5 +   On SAM_Destroy
.head 6 +   If bLocalSqlPopTbl
.head 7 -   Call SqlDisconnect( hLocalSqlPopTbl )
.head 3 +   Child Table: tblNPAOrd
.head 4 +   Contents 
.head 5 +   Column: colWhere
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_WHEREPOPULATE
.head 8 -   Set sBuildWhere = ' WHERE CUSTOMER_ORDER.CUST_NO = :frmRegion.tblMaster.colCustNo AND
CUSTOMER_ORDER.YEAR_OF_SALE = :frmRegion.nYear AND
CUSTOMER_ORDER.CONF_AMT > 0 AND 
CUSTOMER_ORDER.CUST_NO = CUSTOMER_MASTER.CUST_NO AND
CUSTOMER_ORDER.STOCK_ITEM_NO = STOCK_ITEM.ITEM_NO AND
STOCK_ITEM.TREE_TYPE = TREE_TYPE.TREE_TYPE '
.head 8 -  ! Set sBuildWhere = ' WHERE CUSTOMER_ORDER.CUST_NO = :frmRegion.tblMaster.colCustNo AND
CUSTOMER_ORDER.YEAR_OF_SALE = :frmRegion.nYear AND
CUSTOMER_ORDER.CONF_AMT > 0 AND 
CUSTOMER_ORDER.CUST_NO = CUSTOMER_MASTER.CUST_NO AND
CUSTOMER_ORDER.STOCK_ITEM_NO = STOCK_ITEM.ITEM_NO AND
STOCK_ITEM.CULTIVAR_ID = CULTIVAR.CULT_ID(+) AND
STOCK_ITEM.TREE_TYPE = TREE_TYPE.TREE_TYPE '
.head 5 -  ! colVariety needs to be the first column - if it is not change the order by in 
.head 5 +   Column: colVariety
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, '@UPPER(STOCK_ITEM.VARIETY)' )
.head 8 -  ! Call BuildSQL(  wParam, hWndItem, '@UPPER(CULTIVAR.VARIETY)' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 -  ! the sORDERBY local variable
.head 5 +   Column: colType
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'STOCK_ITEM.TREE_TYPE' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colTypeDesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'TREE_TYPE.TREE_TYPE_DESC' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Tree_Type' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colCultdesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'STOCK_ITEM.CULT_DESC' )
.head 8 -  ! Call BuildSQL(  wParam, hWndItem, 'CULTIVAR.CULT_DESC' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CultivarDesc' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colCultNPAflag
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'STOCK_ITEM.CV_NON_PROP_FLAG' )
.head 8 -  ! Call BuildSQL(  wParam, hWndItem, 'CULTIVAR.CV_NON_PROP_FLAG' )
.head 5 +   Column: colCultId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'STOCK_ITEM.CULTIVAR_ID' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colRootId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'STOCK_ITEM.ROOTSTOCK_ID' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colRootDesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'RootDesc' )
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'STOCK_ITEM.ROOT_DESC' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colRootNPAflag
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'STOCK_ITEM.RT_NON_PROP_FLAG' )
.head 5 +   Column: colNPASnt
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.NPA_SENT_FLAG' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'NPASent' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colNPASntDte
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.NPA_SENT_DATE' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'NPASentDate' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colNPARcd
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.NPA_RECD_FLAG' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colConfAmt
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.CONF_AMT' )
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'ConfAmt' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colItemno
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.STOCK_ITEM_NO' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colSubsItemNo
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.SUBS_ITEM_NO' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colLoadId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.LOAD_ID' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colLoadDesc
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_TABLENPAFIELDS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'Load_Description' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colSaleCat
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.SALE_CAT' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colNPANeeded
.head 6 -   List Values 
.head 6 -   Message Actions 
.head 5 +   Column: colDTime
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_BUSADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'ADD_ADDED_DT' )
.head 7 +   On PAM_SHIPADDRESS
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'ADD_ADDED_DT' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 5 +   Column: colRowId
.head 6 -   List Values 
.head 6 +   Message Actions 
.head 7 +   On PAM_SQL
.head 8 -   Call BuildSQL(  wParam, hWndItem, 'CUSTOMER_ORDER.ROWID' )
.head 7 +   On PAM_INITIALIZE
.head 8 -   Call SalClearField( hWndItem )
.head 4 -   Functions 
.head 4 +   Window Variables 
.head 5 -   Sql Handle: hLocalSqlPopTbl
.head 5 -   Boolean: bLocalSqlPopTbl
.head 5 -   Sql Handle: hLocalSqlExtraTbl
.head 5 -   Boolean: bLocalSqlExtraTbl
.head 5 -   String: sSqlExtra
.head 5 -   Sql Handle: hSqlHdlRootDesc
.head 5 -   Boolean: bHdlRootDescConnected 
.head 5 -   Boolean: bHdlRootDescPrepared
.head 5 -   Number: nInd
.head 5 -   Number: nYear
.head 5 -   String: sSQLPOPTABLENAME
.head 5 -   String: sORDERBY
.head 5 -   String: sCurrentBuildWhere
.head 4 +   Message Actions 
.head 5 +   On PAM_POPULATE
.head 6 -   Call TablePopulate( hWndForm, hLocalSqlPopTbl, colWhere, nSELECT, sSQLPOPTABLENAME, sORDERBY, sCurrentBuildWhere, FALSE, TBL_FillNormal, PAM_SQL )
.head 5 +   On SAM_FetchRowDone
.head 6 +   If NOT SalIsNull( colLoadId )
.head 7 -   Set sSqlExtra = 'SELECT Load_Description FROM Load
 INTO :frmRegion.tblNPAOrd.colLoadDesc WHERE Load_Id = \''||colLoadId||'\' '
.head 7 -   Call MySqlPrepExecFetch( hLocalSqlExtraTbl, sSqlExtra, nInd )
.head 6 +   If frmRegion.tblNPAOrd.colRootNPAflag = 'Y' OR frmRegion.tblNPAOrd.colCultNPAflag = 'Y'
.head 7 +   If frmRegion.tblNPAOrd.colNPARcd != 'Y'
.head 8 +   If frmRegion.tblNPAOrd.colConfAmt > 0
.head 9 +   If frmRegion.tblNPAOrd.colSaleCat != 'RP'
.head 10 -   Set frmRegion.tblNPAOrd.colNPANeeded = 'Y'
.head 5 +  ! On SAM_FetchRow
.head 6 +   If SqlFetchRow( hLocalSqlPopTbl, lParam, nInd )
.head 7 +   If NOT SalIsNull( colRootId )
.head 8 -   Call MyGetRootDesc( hSqlHdlRootDesc, bHdlRootDescConnected,
 bHdlRootDescPrepared, 'frmRegion.tblNPAOrd.colRootDesc',
 'frmRegion.tblNPAOrd.colRootNPAflag', 'frmRegion.tblNPAOrd.colRootId' )
.head 8 -  ! Set sSqlExtra = 'SELECT Root_Desc FROM Rootstock INTO :tblNPAOrd.colRootDesc WHERE Root_Id = \''||colRootId||'\' '
.head 8 -  ! Call MySqlPrepExecFetch( hLocalSqlExtraTbl, sSqlExtra, nInd )
.head 7 +   If NOT SalIsNull( colLoadId )
.head 8 -   Set sSqlExtra = 'SELECT Load_Description FROM Load
 INTO :frmRegion.tblNPAOrd.colLoadDesc WHERE Load_Id = \''||colLoadId||'\' '
.head 8 -   Call MySqlPrepExecFetch( hLocalSqlExtraTbl, sSqlExtra, nInd )
.head 7 +   If frmRegion.tblNPAOrd.colRootNPAflag = 'Y' OR frmRegion.tblNPAOrd.colCultNPAflag = 'Y'
.head 8 +   If frmRegion.tblNPAOrd.colNPARcd != 'Y'
.head 9 +   If frmRegion.tblNPAOrd.colConfAmt > 0
.head 10 +   If frmRegion.tblNPAOrd.colSaleCat != 'RP'
.head 11 -   Set frmRegion.tblNPAOrd.colNPANeeded = 'Y'
.head 5 +   On SAM_Create
.head 6 -   Set bLocalSqlPopTbl = SqlConnect( hLocalSqlPopTbl ) 
.head 6 +   If bLocalSqlPopTbl
.head 7 -   Call SqlSetLockTimeout( hLocalSqlPopTbl, SQLTIMEOUT )
.head 7 -   Call SqlSetParameter( hLocalSqlPopTbl, DBP_PRESERVE, TRUE, ''  )
.head 6 +   Else 
.head 7 -   Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 7 -   Return FALSE
.head 6 -   Set bLocalSqlExtraTbl = SqlConnect( hLocalSqlExtraTbl ) 
.head 6 +   If bLocalSqlExtraTbl
.head 7 -   Call SqlSetLockTimeout( hLocalSqlExtraTbl, SQLTIMEOUT )
.head 6 +   Else 
.head 7 -   Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 7 -   Return FALSE
.head 6 -   Set bHdlRootDescConnected = FALSE
.head 6 -   Set bHdlRootDescPrepared = FALSE
.head 6 -   Set sSQLPOPTABLENAME = 'CUSTOMER_ORDER, STOCK_ITEM, TREE_TYPE, CUSTOMER_MASTER '
.head 6 -  ! Set sSQLPOPTABLENAME = 'CUSTOMER_ORDER, STOCK_ITEM, CULTIVAR, TREE_TYPE, CUSTOMER_MASTER '
.head 6 -   Set sORDERBY = ' ORDER BY 1 '
.head 5 +   On SAM_Destroy
.head 6 +   If bLocalSqlPopTbl
.head 7 -   Call SqlDisconnect( hLocalSqlPopTbl )
.head 6 +   If bLocalSqlExtraTbl
.head 7 -   Call SqlDisconnect( hLocalSqlExtraTbl )
.head 6 +   If bHdlRootDescConnected
.head 7 -   Call SqlDisconnect( hSqlHdlRootDesc )
.head 3 +   Pushbutton: pbItemEnq
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call ItemEnquiry(  )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbAdd
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call SalSendMsg( frmRegion.tblRegion, PAM_ADDROW, 0, 0 )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbSave
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call SalWaitCursor( TRUE )
.head 6 -   Call SalSendMsg(frmRegion.tblRegion, PAM_WRITEINSERTSUPDATES, 0, 0 )
.head 6 -   Call SalWaitCursor( FALSE )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbLoads
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 +   If NOT SalTblAnyRows( frmRegion.tblRegion, ROW_Selected, 0 )
.head 7 -   Call SalMessageBox( 'Please select a region first', 'Region', MB_Ok )
.head 7 -   Return FALSE
.head 6 -   Call SalWaitCursor( TRUE )
.head 6 -   Call PushWndHdl( frmRegion.tblRegion )
.head 6 -   Call SelectLoad(  )
.head 5 +   On PAM_ENABLE
.head 6 -   Call SalEnableWindow( hWndItem )
.head 6 -   Call SalSendMsg( frmRegion.tblRegion, PAM_POPULATE, 0, 0 )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbFreight
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call SalWaitCursor( TRUE )
.head 6 -   Call SalTblQueryFocus( tblRegion, nRow, hWndCol )
.head 6 +   If NOT SalTblQueryRowFlags( tblRegion, nRow, ROW_Selected )
.head 7 +   If NOT SalSendMsg( hWndCol, PAM_ENABLEFREIGHTCODEPB, nRow, 0 )
.head 8 -   Call SalWaitCursor( FALSE )
.head 8 -   Call SalMessageBox( 'Please select a ROW for which to LOOK UP or REPLACE a Freight Code!', 'Warning', MB_Ok )
.head 8 -   Return FALSE
.head 6 -   Call PushWndHdl( hWndItem)
.head 6 -   Call PushString( frmRegion.tblRegion.colFrCode )
.head 6 -   Call SalDisableWindow ( hWndItem ) 
.head 6 -   Call SalModalDialog( dlgFreight, hWndForm )
.head 5 +   On PAM_ENABLE
.head 6 +   If lParam
.head 7 -   Call SalSendMsgToChildren( tblRegion, PAM_LOOKUPTYPE, 0, 0 )
.head 6 -   Call SalEnableWindow( hWndItem )
.head 6 -   Call SalSetFocus( pbSave )
.head 6 -   Call SalWaitCursor( FALSE )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbClear
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call ClearSelections( frmRegion.tblRegion )
.head 6 -   Call SalSendMsgToChildren( frmRegion.tblRegion, PAM_DISALLOWENTRY, 0, 0 )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbOutstandingOrders
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call SalWaitCursor( TRUE )
.head 6 -   Call SalDisableWindow( hWndItem )
.head 6 +   If SalTblAnyRows( tblRegion, ROW_Selected, 0 )
.head 7 -   Call PushString( frmRegion.tblRegion.colRegId )
.head 6 +   Else 
.head 7 -   Call PushString( '' )
.head 6 -   Call PushWndHdl( hWndItem )
.head 6 -   Call SalCreateWindow( frmOutstandingOrders, hWndForm )
.head 5 +   On PAM_ENABLE
.head 6 -   Call SalEnableWindow( hWndItem )
.head 6 -   Call SalWaitCursor( FALSE )
.head 3 +   Pushbutton: pbQuery
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 +   If SalTblAnyRows( hWndForm.tblRegion, ROW_Edited|ROW_New|ROW_MarkDeleted, 0 )
.head 7 +   If NOT ForgetChanges(  )
.head 8 -   Return FALSE
.head 6 -   Call SalHideWindow( hWndItem )
.head 6 -   Call PushWndHdl( frmRegion )
.head 6 -   Call QueryForm(  )
.head 6 -   Set bShowQueryOk = TRUE
.head 6 -   Call SalSendMsgToChildren( hWndForm, PAM_QUERYDISABLE, TRUE, 0 )
.head 5 +   On PAM_ENABLE
.head 6 -   Call SalShowWindow( hWndItem )
.head 3 +   Pushbutton: pbOk
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call SalWaitCursor( TRUE )
.head 6 -   Call SalSendMsg( frmRegion.tblRegion, PAM_SEARCH, 0, 0 )
.head 6 -   Set bShowQueryOk = FALSE
.head 6 -   Call SalSendMsgToChildren( hWndForm, PAM_QUERYDISABLE, FALSE, 0 )
.head 6 -   Call SalWaitCursor( FALSE )
.head 5 +   On PAM_HIDE
.head 6 -   Call SalHideWindow( hWndItem )
.head 3 +   Pushbutton: pbDelete
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 +   If SalTblQueryRowFlags( hWndForm.tblRegion, SalTblQueryContext( hWndForm.tblRegion ), ROW_New )
.head 7 -   Call SalSendMsg( hWndForm.pbClear, SAM_Click, 0, 0 )
.head 6 +   Else 
.head 7 -   Call SalSendMsg( frmRegion.tblRegion, PAM_DELETEROWS, 0, 0 )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbUndelete
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call SalSendMsg( frmRegion.tblRegion, PAM_UNDELETEROWS, 0, 0 )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbExit
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 +   If SalTblAnyRows( hWndForm.tblRegion, ROW_Edited|ROW_New|ROW_MarkDeleted, 0 )
.head 7 +   If NOT ForgetChanges(  )
.head 8 -   Return FALSE
.head 6 -   Call SalDestroyWindow( hWndForm )
.head 5 +   On PAM_QUERYDISABLE
.head 6 +   If wParam
.head 7 -   Call SalDisableWindow( hWndItem )
.head 6 +   Else 
.head 7 -   Call SalEnableWindow( hWndItem )
.head 3 +   Pushbutton: pbHelp
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call ActivateHelp ( sFrmLoadRegHelpFileName )
.head 3 +   Pushbutton: pbRegionMeets
.head 4 +   Message Actions 
.head 5 +   On SAM_Click
.head 6 -   Call SalWaitCursor( TRUE )
.head 6 +   If MyTableAnyRows( tblRegion, ROW_Selected, 0, nRowsSelected )
.head 7 -  ! Call SalModalDialog( dlgRegionMeets, hWndForm, tblRegion, tblRegion.colRegId, nRowsSelected )
.head 7 -   Call SalCreateWindow( frmRegionMeets, hWndForm, tblRegion, tblRegion.colRegId, nRowsSelected )
.head 7 -   Call SalWaitCursor( FALSE )
.head 6 +   Else 
.head 7 -   Call SalWaitCursor( FALSE )
.head 7 -   Call SalMessageBox( 'Please pick a region to see meet address\' for!', 'NOTE', MB_Ok )
.head 3 -   Frame 
.head 2 -   Functions 
.head 2 -   Window Parameters 
.head 2 +   Window Variables 
.head 3 -   Window Handle: hWndPushbutton
.head 3 -   Number: nRowsSelected
.head 3 -   Boolean: bShowQueryOk
.head 3 -   Number: nNoItemsPrinted
.head 3 -   Number: nNoNPAs
.head 3 -   Number: nCustRow
.head 3 -   Number: nOrderRow
.head 3 -   Boolean: bProcessCust
.head 3 -   Boolean: bProcessOrders
.head 3 -   Boolean: bPopulateTblOrd
.head 3 -   Boolean: bForRegion
.head 3 -   Boolean: bPrintNPAs
.head 3 -   Number: nRow
.head 3 -   Number: nQtr
.head 3 -   Number: nYear
.head 3 -   Number: nInd
.head 3 -   String: sRepInto
.head 3 -   String: sRepBind
.head 3 -   String: sReportFile
.head 3 -   String: sSql
.head 3 -   Number: nError
.head 3 -   Sql Handle: hSqlHandle
.head 3 -   Boolean: bSqlHandle
.head 3 -  !
.head 3 -  ! Sql Handle: hSqlCVHdl
.head 3 -  ! Boolean: bSqlCVHdlConnected
.head 3 -  ! Boolean: bSqlCVHdlPrepared
.head 3 -  !
.head 3 -  ! Sql Handle: hSqlRtHdl
.head 3 -  ! Boolean: bSqlRtHdlConnected
.head 3 -  ! Boolean: bSqlRtHdlPrepared
.head 3 -  !
.head 3 -   Sql Handle: hSqlNPAHdl
.head 3 -   Boolean: bSqlNPAHdlConnected
.head 3 -   Boolean: bSqlNPAHdlPrepared
.head 3 -  !
.head 3 -   Sql Handle: hLocalSqlPopTbl
.head 3 -   Boolean: bLocalSqlPopTbl
.head 3 -   Sql Handle: hLocalSqlSrchTbl
.head 3 -   Boolean: bLocalSqlSrchTbl
.head 3 -   Sql Handle: hLocalSqlDoTbl
.head 3 -   Boolean: bLocalSqlDoTbl
.head 2 +   Message Actions 
.head 3 +   On SAM_Create
.head 4 -   Set bLocalSqlPopTbl = SqlConnect( hLocalSqlPopTbl ) 
.head 4 +   If bLocalSqlPopTbl
.head 5 -   Call SqlSetLockTimeout( hLocalSqlPopTbl, SQLTIMEOUT )
.head 5 -   Call SqlSetParameter( hLocalSqlPopTbl, DBP_PRESERVE, TRUE, ''  )
.head 4 +   Else 
.head 5 -   Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 5 -   Return FALSE
.head 4 -   Set bLocalSqlSrchTbl = SqlConnect( hLocalSqlSrchTbl ) 
.head 4 +   If bLocalSqlSrchTbl
.head 5 -   Call SqlSetLockTimeout( hLocalSqlSrchTbl, SQLTIMEOUT )
.head 5 -   Call SqlSetParameter( hLocalSqlSrchTbl, DBP_PRESERVE, TRUE, ''  )
.head 4 +   Else 
.head 5 -   Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 5 -   Return FALSE
.head 4 -   Set bLocalSqlDoTbl = SqlConnect( hLocalSqlDoTbl ) 
.head 4 +   If bLocalSqlDoTbl
.head 5 -   Call SqlSetLockTimeout( hLocalSqlDoTbl, SQLTIMEOUT )
.head 4 +   Else 
.head 5 -   Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 5 -   Return FALSE
.head 4 -  ! Set bSqlCVHdlConnected = FALSE
.head 4 -  ! Set bSqlCVHdlPrepared = FALSE
.head 4 -  ! Set bSqlRtHdlConnected = FALSE
.head 4 -  ! Set bSqlRtHdlPrepared = FALSE
.head 4 -   Set bSqlNPAHdlConnected = FALSE
.head 4 -   Set bSqlNPAHdlPrepared = FALSE
.head 4 -   Call SalSendMsg( hWndForm,PAM_CREATECOMPLETE,0,0 )
.head 3 +   On PAM_PRINTNPAS
.head 4 -   Call SalWaitCursor( TRUE )
.head 4 -   Set bPrintNPAs = TRUE
.head 4 -   Call CallBuildSql( frmRegion.tblMaster, nSELECT, PAM_NPACUSTBITS, '', '' )
.head 4 -   Set sRepInto = sColumns
.head 4 -   Set sRepBind = sIntoVars
.head 4 -   Call CallBuildSql( frmRegion.tblMaster, nSELECT, PAM_TABLENPAFIELDS, '', '' )
.head 4 -   Set sRepInto = sRepInto||','||sColumns
.head 4 -   Set sRepBind = sRepBind||','||sIntoVars
.head 4 -   Call CallBuildSql( frmRegion.tblNPAOrd, nSELECT, PAM_TABLENPAFIELDS, '', '' )
.head 4 -   Set sRepInto = sRepInto||','||sColumns
.head 4 -   Set sRepBind = sRepBind||','||sIntoVars
.head 4 -   Set sReportFile = 'g:\\apps\\gupta\\reports\\npaoutst.qrp'
.head 4 -   Set nError = 1
.head 4 -   Call SalReportPrint( hWndForm, sReportFile, sRepBind, sRepInto, 1, RPT_PrintAll,0,0, nError )
.head 3 +   On SAM_Destroy
.head 4 +   If bLocalSqlPopTbl
.head 5 -   Call SqlDisconnect( hLocalSqlPopTbl )
.head 4 +   If bLocalSqlSrchTbl
.head 5 -   Call SqlDisconnect( hLocalSqlSrchTbl )
.head 4 +   If bLocalSqlDoTbl
.head 5 -   Call SqlDisconnect( hLocalSqlDoTbl )
.head 4 +  ! If bSqlCVHdlConnected
.head 5 -   Call SqlDisconnect( hSqlCVHdl )
.head 4 +  ! If bSqlRtHdlConnected
.head 5 -   Call SqlDisconnect( hSqlRtHdl )
.head 4 +   If bSqlNPAHdlConnected
.head 5 -   Call SqlDisconnect( hSqlNPAHdl )
.head 4 -   Call SalSendMsg( hWndCallProg, PAM_ENABLE,0,0 )
.head 3 +   On PAM_CREATECOMPLETE
.head 4 -   Call SalSendMsgToChildren( hWndForm, PAM_HIDE, 0, 0 )
.head 4 -   Set hWndForm.dfCurrDate = SalDateCurrent(  )
.head 4 -   Call SalSendMsg( frmRegion.tblRegion, PAM_POPULATE, 0, 0 )
.head 3 +   On SAM_Close
.head 4 +   If SalTblAnyRows( hWndForm.tblRegion, ROW_Edited|ROW_New|ROW_MarkDeleted, 0 )
.head 5 +   If NOT ForgetChanges(  )
.head 6 -   Return FALSE
.head 3 +   On SAM_ReportStart
.head 4 +   If bPrintNPAs
.head 5 -   Set nCustRow = TBL_MinRow
.head 5 -   Set nOrderRow = TBL_MinRow
.head 5 -   Set bProcessCust = TRUE
.head 5 -   Set bProcessOrders = FALSE
.head 5 -   Set bPopulateTblOrd = FALSE
.head 5 -   Set bSqlHandle = SqlConnect( hSqlHandle ) 
.head 5 +   If bSqlHandle
.head 6 -   Call SqlSetLockTimeout( hSqlHandle, SQLTIMEOUT )
.head 5 +   Else 
.head 6 -   Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 6 -   Return FALSE
.head 5 -   Return TRUE
.head 3 +   On SAM_ReportFetchInit
.head 4 +   If bPrintNPAs
.head 5 -   Call SalSendMsg( tblMaster, PAM_POPULATE, 0, 0 )
.head 5 -   Return TRUE
.head 3 +   On SAM_ReportFetchNext
.head 4 +   If bPrintNPAs
.head 5 +   If bProcessCust
.head 6 -   Call SalSendMsgToChildren( frmRegion.tblNPAOrd, PAM_INITIALIZE, 0, 0 )
.head 6 +   Loop 
.head 7 -   Set bOk = SalTblFindNextRow( frmRegion.tblMaster, nCustRow, 0, 0 )
.head 7 +   If bOk
.head 8 -   Call SalTblFetchRow( tblMaster, nCustRow )
.head 8 +   If HasCustAnyNPAstock( frmRegion.tblMaster.colCustNo, nYear,hSqlNPAHdl, bSqlNPAHdlConnected, bSqlNPAHdlPrepared )
.head 9 -   Set bProcessCust = FALSE
.head 9 -   Set bProcessOrders = TRUE
.head 9 -   Set nOrderRow = TBL_MinRow
.head 9 -   Set nNoItemsPrinted = 0
.head 9 -  ! Need converting for apl routine
.head 9 -  ! Call GetBusinessAddress( frmRegion.tblMaster, frmRegion.tblMaster.colCustNo, frmRegion.tblMaster.colPOSuburb )
.head 9 -  ! Set nCommaPos = SalStrScan( tblMaster.colCustName, ',' )
.head 9 +  ! If nCommaPos >= 0
.head 10 -   Call SalStrLeft( tblMaster.colCustName, nCommaPos, sCustLeftName )
.head 10 -   Call SalStrMid( tblMaster.colCustName, nCommaPos+2, SalStrLength( tblMaster.colCustName ) - nCommaPos, sCustRightName )
.head 10 -   Set tblMaster.colCustName = sCustRightName || ' ' || sCustLeftName
.head 9 -  ! Set sNPALabelStr = tblMaster.colCustName || ',' || 
  tblMaster.colPOAdd1 || ',' ||
  tblMaster.colPOAdd2 || ',' ||
  tblMaster.colPOSuburb || ',' ||
  tblMaster.colPOState || ',' ||
  tblMaster.colPOPostcode
.head 9 -  ! Call SalFilePutStr( hNPALabelFile, sNPALabelStr )
.head 9 -   Set bPopulateTblOrd = TRUE
.head 9 -   Return TRUE
.head 7 +   If NOT bOk
.head 8 -   Return FALSE
.head 5 +   If bProcessOrders
.head 6 +   If bPopulateTblOrd
.head 7 -   Call SalSendMsg( frmRegion.tblNPAOrd, PAM_POPULATE, 0, 0 )
.head 7 -  ! Set nNoNPAs = MarkNPItems ( hSqlCVHdl, bSqlCVHdlConnected, bSqlCVHdlPrepared,
 hSqlRtHdl, bSqlRtHdlConnected, bSqlRtHdlPrepared, frmRegion.tblNPAOrd )
.head 7 -   Set bPopulateTblOrd = FALSE
.head 6 +   Loop 
.head 7 -   Set bOk = SalTblFindNextRow( frmRegion.tblNPAOrd, nOrderRow, 0, 0 )
.head 7 +   If bOk
.head 8 +   If NOT SalTblFindNextRow( frmRegion.tblNPAOrd, nOrderRow, 0, 0 )
.head 9 -   Set bProcessCust = TRUE
.head 9 -   Set bProcessOrders = FALSE
.head 8 +   Else 
.head 9 -   Call SalTblFindPrevRow( frmRegion.tblNPAOrd, nOrderRow, 0, 0  )
.head 8 -   Call SalTblFetchRow( frmRegion.tblNPAOrd, nOrderRow )
.head 8 +   If frmRegion.tblNPAOrd.colNPANeeded = 'Y'
.head 9 -   Set nNoItemsPrinted = nNoItemsPrinted + 1
.head 9 -   Break 
.head 7 +   If NOT bOk
.head 8 -   Set bProcessCust = TRUE
.head 8 -   Set bProcessOrders = FALSE
.head 8 -   Return TRUE
.head 6 +   If nNoItemsPrinted = nNoNPAs
.head 7 -   Set bProcessCust = TRUE
.head 7 -   Set bProcessOrders = FALSE
.head 6 +   If frmRegion.tblNPAOrd.colCultNPAflag = 'N' AND frmRegion.tblNPAOrd.colRootNPAflag = 'Y'
.head 7 -   Set frmRegion.tblNPAOrd.colCultdesc = frmRegion.tblNPAOrd.colVariety
.head 6 +   Else If frmRegion.tblNPAOrd.colCultNPAflag = 'Y' AND frmRegion.tblNPAOrd.colRootNPAflag = 'N'
.head 7 -   Set frmRegion.tblNPAOrd.colRootDesc = ''
.head 6 -   Return TRUE
.head 3 +   On SAM_ReportFinish
.head 4 +  ! If bPrintNPAs
.head 5 +   If bSqlHandle
.head 6 -   Call SqlDisconnect( hSqlHandle )
