Connect water7 sysadm graham;
set recovery off;
set bulk on;
lock database;
reorganize;
set bulk off;
set recovery on;
lock database;
check database;
unlock database;
set logbackup on;
commit;
disconnect water7;
*************************************************************;
*******************************************************;
