.head 0 +  Application Description: SQLWindows version 5.0 
.data CLASSPROPSSIZE
0000: 4800
.enddata
.data CLASSPROPS
0000: 4170705061746800 10006B3A5C63656E 747572615C636C61 7373004170705061
0020: 74684C656E000400 1000000000557365 476C6F62616C5061 7468000400010000
0040: 0000000000000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFFECFFFF FFFEFFFFFF7C0200 0037010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000C819DD0A0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: -0.05"
.head 3 -  Top: 0.01"
.head 3 -  Width:  8.025"
.head 3 -  Height: 5.042"
.head 2 +  Options Box Location
.data VIEWINFO
0000: D4188507B80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.613"
.head 3 -  Top: 3.177"
.head 3 -  Width:  4.188"
.head 3 -  Height: 2.698"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 6.875"
.head 3 -  Top: 1.927"
.head 2 -  Fully Qualified External References? Yes
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 +  Select From: CommLoadFunc.apl
.head 3 -  Constants
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Dialog Box
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Light Green
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Dark Green
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Green
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Dark Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Number: 0000000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: dd-MMM-yyyy hh:mm:ss AMPM
.head 2 -  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 -  System
.head 3 +  User
.head 4 -  ! PAM_Messages in here can only go in range SAM_User + 3300 -> 3399
.head 3 -  Enumerations
.head 2 -  Resources
.head 2 -  Variables
.data RESOURCE 0 0 1 1925081699
0000: D60000009A000000 0000000000000000 0200000700000057 0100001019000000
0020: 016A01E0EA350000 0040730000000100 00A3700100192500 016A0539B8000000
0040: 73D1000100006889 0100190089016A7F 07006E0073003401 0000A2015A001900
0060: 01A26A800700001B 730001008D00BB01 00161900046A01E0 AB0A000000667300
0080: 0100A3D401001925 00016A8B2AB80000 0073D10001000068 ED0100190009016A
00A0: FD2E00006E007300 34010000
.enddata
.head 2 -  Named Menus
.head 2 +  Internal Functions
.head 3 +  Function: GetCustTypeAndDefDelType2
.head 4 -  Description: Given a customer number this function returns the customer_type
and the second receive parameter classifies GC for Garden Centers
OR for orchadists and the third parameter returns the customers
Default delivery type
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Receive String: sCustType
.head 5 -  Receive String: sGCOR
.head 5 -  Receive String: sDefDelType
.head 5 -  Number: nActionType
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nInd
.head 5 -  Number: nSqlHandleNo
.head 5 -  !
.head 5 -  String: sGotCustType
.head 5 -  String: sGotDefDelType
.head 4 +  Actions
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GETCUSTDELTYPES' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = "  SELECT Customer_Type, Def_Deliv_Type
FROM Customer_Master
WHERE Cust_No = :1 "
.head 7 -  Set sName = 'GETCUSTDELTYPES'
.head 7 -  Set sBind = ':nCustNo'
.head 7 -  Set sInto = ':sGotCustType, :sGotDefDelType'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sCustType = ''
.head 7 -  Set sGotCustType = ''
.head 7 -  Set sGCOR = ''
.head 7 -  Set sDefDelType = ''
.head 7 -  Set sGotDefDelType = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 9 -  Set sCustType = sGotCustType
.head 9 -  Set sDefDelType = sGotDefDelType
.head 9 +  If ( SalStrScan( sCustType, 'OR%' ) >= 0 ) OR ( sCustType = 'NOR' )
.head 10 -  Set sGCOR = 'OR'
.head 9 +  Else
.head 10 -  Set sGCOR = 'GC'
.head 9 -  Return TRUE
.head 8 +  Else
.head 9 -  Return FALSE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nSqlHandleNo ].Disconnect( )
.head 3 +  Function: GetShipAddress
.head 4 -  Description: Given a customer number this function returns the customer_type
and the second receive parameter classifies GC for Garden Centers
OR for orchadists and the third parameter returns the customers
Default delivery type
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Number: nYear
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Receive Boolean: bPickUpAddress
.head 5 -  Number: nActionType
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  !
.head 5 -  String: sSqlConfAmtHandle
.head 5 -  String: sBindConfAmtHandle
.head 5 -  String: sIntoConfAmtHandle
.head 5 -  String: sNameConfAmtHandle
.head 5 -  !
.head 5 -  Date/Time: dtGotAddressDT
.head 5 -  String: sGotAddressType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  String: sGotDefaultShipping
.head 5 -  Number: nSqlHandleNo
.head 5 -  Number: nSqlHandleNoConfAmt
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  !
.head 5 -  String: sAddressType
.head 5 -  String: sCustType
.head 5 -  String: sGCOR
.head 5 -  String: sDefDelType
.head 5 -  Boolean: bStopFetch
.head 5 -  Boolean: bAfterConfirmations
.head 5 -  Number: nSumConfAmt
.head 5 -  Boolean: bNoDefaultShipping
.head 5 -  Number: nTmp
.head 5 -  String: sTmp
.head 4 +  Actions
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GETSHIPADDRS' )
.head 5 -  Set nSqlHandleNoConfAmt = SqlHandlesGetReferenceNo( 'CUSTTOTCONF' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT
Add_Added_DT,
Address_Type,
Address_1,
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag,
Default_Shipping
FROM Customer_Address
WHERE Cust_No = :1 AND Address_Type = :2 "
.head 7 -  Set sNameHandle = 'GETSHIPADDRS1'
.head 7 -  Set sBindHandle = ':nCustNo, :sAddressType'
.head 7 -  Set sIntoHandle = ':dtGotAddressDT, :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState,
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments,
:sGotMeetId, :sGotMainAddressFlag, :sGotDefaultShipping'
.head 7 -  !
.head 7 -  Set sSqlConfAmtHandle = " SELECT Sum(Conf_Amt)
FROM Customer_Order
WHERE Cust_No = :1 AND Year_Of_Sale = :2 "
.head 7 -  Set sNameConfAmtHandle = 'CUSTTOTCONF'
.head 7 -  Set sBindConfAmtHandle = ':nCustNo, :nYear'
.head 7 -  Set sIntoConfAmtHandle = ':nSumConfAmt'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNoConfAmt ].Setup( sSqlConfAmtHandle, sNameConfAmtHandle, sBindConfAmtHandle, sIntoConfAmtHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNoConfAmt ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sCustType = ''
.head 7 -  Set sGCOR = ''
.head 7 -  Set sDefDelType = ''
.head 7 -  !
.head 7 -  Set dtAddressDT = DATETIME_Null
.head 7 -  Set sAddressType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set dtGotAddressDT = DATETIME_Null
.head 7 -  Set sGotAddressType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set bPickUpAddress = FALSE
.head 7 -  Call GetCustTypeAndDefDelType2( nCustNo, sCustType, sGCOR, sDefDelType, SH_cls_Execute )
.head 7 +  If sGCOR = 'GC'
.head 8 -  Set sAddressType = 'SHIP'
.head 8 -  Set bStopFetch = FALSE
.head 8 -  Set nInd = FETCH_EOF
.head 8 -  Set bNoDefaultShipping = FALSE
.head 8 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 9 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 10 -  ! GF 21/6/02 Chaged below from 'If' to 'While' and added bNoDefaultShipping check to loop though once looking for default shipping
then if not found find the next ship address.
.head 10 +  While haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 11 +  If sGotDefaultShipping = 'Y' OR sAddressType != 'SHIP' OR bNoDefaultShipping
.head 12 -  Set dtAddressDT = dtGotAddressDT
.head 12 -  Set sAddrType = sGotAddressType
.head 12 -  Set sAddressLine1 = sGotAddressLine1
.head 12 -  Set sAddressLine2 = sGotAddressLine2
.head 12 -  Set sSuburb = sGotSuburb
.head 12 -  Set sPostcode = sGotPostcode
.head 12 -  Set sState = sGotState
.head 12 -  Set sCountry = sGotCountry
.head 12 -  Set sAreaCode = sGotAreaCode
.head 12 -  Set sPhoneNo = sGotPhoneNo
.head 12 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 12 -  Set sFaxNo = sGotFaxNo
.head 12 -  Set sComments = sGotComments
.head 12 -  Set sMeetId = sGotMeetId
.head 12 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 12 -  Return TRUE
.head 11 +  ! Else
.head 12 -  ! Set sAddressType = 'BUS'
.head 12 -  Set bNoDefaultShipping = TRUE
.head 12 -  Set nInd = FETCH_EOF
.head 10 -  ! GF 21/6/02 Had to change this from 'Else If' to 'If'
.head 10 +  If sAddressType = 'SHIP' and bNoDefaultShipping
.head 11 -  Set sAddressType = 'BUS'
.head 11 -  Set nInd = FETCH_EOF
.head 10 +  Else If sAddressType = 'SHIP' and NOT bNoDefaultShipping
.head 11 -  Set bNoDefaultShipping = TRUE
.head 11 -  Set nInd = FETCH_EOF
.head 10 +  Else If sAddressType = 'BUS'
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Return TRUE
.head 9 +  Else
.head 10 -  Set bStopFetch = TRUE
.head 10 -  Return FALSE
.head 7 +  Else
.head 8 +  If sDefDelType = 'PICKUP'
.head 9 -  Set bPickUpAddress = TRUE
.head 9 -  Return TRUE
.head 8 -  !
.head 8 +  If haSqlHandles[ nSqlHandleNoConfAmt ].Execute( )
.head 9 +  If haSqlHandles[ nSqlHandleNoConfAmt ].FetchNext( nInd )
.head 10 -  Set bAfterConfirmations = TRUE
.head 9 +  Else
.head 10 -  Set bAfterConfirmations = FALSE
.head 9 -  !
.head 9 +  If sDefDelType = 'DELIVER'
.head 10 -  Set sAddressType = 'SHIP'
.head 10 -  Set bStopFetch = FALSE
.head 10 -  Set nInd = FETCH_EOF
.head 10 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 11 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 13 +  If sGotDefaultShipping = 'Y' OR sAddressType != 'SHIP'
.head 14 -  Set dtAddressDT = dtGotAddressDT
.head 14 -  Set sAddrType = sGotAddressType
.head 14 -  Set sAddressLine1 = sGotAddressLine1
.head 14 -  Set sAddressLine2 = sGotAddressLine2
.head 14 -  Set sSuburb = sGotSuburb
.head 14 -  Set sPostcode = sGotPostcode
.head 14 -  Set sState = sGotState
.head 14 -  Set sCountry = sGotCountry
.head 14 -  Set sAreaCode = sGotAreaCode
.head 14 -  Set sPhoneNo = sGotPhoneNo
.head 14 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 14 -  Set sFaxNo = sGotFaxNo
.head 14 -  Set sComments = sGotComments
.head 14 -  Set sMeetId = sGotMeetId
.head 14 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 14 -  Return TRUE
.head 13 +  Else
.head 14 -  Set sAddressType = 'BUS'
.head 14 -  Set nInd = FETCH_EOF
.head 12 +  Else If sAddressType = 'SHIP'
.head 13 -  Set sAddressType = 'BUS'
.head 12 +  Else If sAddressType = 'BUS'
.head 13 +  If bAfterConfirmations
.head 14 +  If nSumConfAmt < MINOrdersForDelivery
.head 15 -  Set sAddressType = 'MEET'
.head 14 +  Else
.head 15 -  Return TRUE
.head 13 +  Else
.head 14 -  ! The next line was added and the return uncommented
.head 14 -  ! Set sAddressType = 'MEET'
.head 14 -  Return TRUE
.head 12 +  Else If sAddressType = 'MEET'
.head 13 -  Return TRUE
.head 12 +  Else
.head 13 -  Return TRUE
.head 11 +  Else
.head 12 -  Set bStopFetch = TRUE
.head 12 -  Return FALSE
.head 9 +  Else If sDefDelType = 'GROUP'
.head 10 -  ! Else is for GROUP DefDelType
.head 10 -  Set sAddressType = 'MEET'
.head 10 -  Set bStopFetch = FALSE
.head 10 -  Set nInd = FETCH_EOF
.head 10 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 11 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 13 +  If sGotDefaultShipping = 'Y' OR sAddressType != 'SHIP'
.head 14 -  Set dtAddressDT = dtGotAddressDT
.head 14 -  Set sAddrType = sGotAddressType
.head 14 -  Set sAddressLine1 = sGotAddressLine1
.head 14 -  Set sAddressLine2 = sGotAddressLine2
.head 14 -  Set sSuburb = sGotSuburb
.head 14 -  Set sPostcode = sGotPostcode
.head 14 -  Set sState = sGotState
.head 14 -  Set sCountry = sGotCountry
.head 14 -  Set sAreaCode = sGotAreaCode
.head 14 -  Set sPhoneNo = sGotPhoneNo
.head 14 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 14 -  Set sFaxNo = sGotFaxNo
.head 14 -  Set sComments = sGotComments
.head 14 -  Set sMeetId = sGotMeetId
.head 14 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 14 -  Return TRUE
.head 13 +  Else
.head 14 -  Set sAddressType = 'BUS'
.head 14 -  Set nInd = FETCH_EOF
.head 12 +  Else If sAddressType = 'MEET'
.head 13 +  If bAfterConfirmations
.head 14 +  If nSumConfAmt >= MINOrdersForDelivery
.head 15 -  Set sAddressType = 'SHIP'
.head 14 +  Else
.head 15 -  Return TRUE
.head 13 +  Else
.head 14 -  ! The next line was added and the return uncommented
.head 14 -  ! Set sAddressType = 'SHIP'
.head 14 -  Return TRUE
.head 12 +  Else If sAddressType = 'SHIP'
.head 13 -  Set sAddressType = 'BUS'
.head 12 +  Else If sAddressType = 'BUS'
.head 13 -  Return TRUE
.head 12 +  Else
.head 13 -  Return TRUE
.head 11 +  Else
.head 12 -  Set bStopFetch = TRUE
.head 12 -  Return FALSE
.head 9 +  Else
.head 10 -  ! Else is for Blank DefDelType
.head 10 +  If bAfterConfirmations AND nSumConfAmt >= MINOrdersForDelivery
.head 11 -  Set sAddressType = 'SHIP'
.head 11 -  Set bStopFetch = FALSE
.head 11 -  Set nInd = FETCH_EOF
.head 11 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 12 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 13 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 14 +  If sGotDefaultShipping = 'Y' OR sAddressType != 'SHIP'
.head 15 -  Set dtAddressDT = dtGotAddressDT
.head 15 -  Set sAddrType = sGotAddressType
.head 15 -  Set sAddressLine1 = sGotAddressLine1
.head 15 -  Set sAddressLine2 = sGotAddressLine2
.head 15 -  Set sSuburb = sGotSuburb
.head 15 -  Set sPostcode = sGotPostcode
.head 15 -  Set sState = sGotState
.head 15 -  Set sCountry = sGotCountry
.head 15 -  Set sAreaCode = sGotAreaCode
.head 15 -  Set sPhoneNo = sGotPhoneNo
.head 15 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 15 -  Set sFaxNo = sGotFaxNo
.head 15 -  Set sComments = sGotComments
.head 15 -  Set sMeetId = sGotMeetId
.head 15 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 15 -  Return TRUE
.head 14 +  Else
.head 15 -  Set sAddressType = 'BUS'
.head 15 -  Set nInd = FETCH_EOF
.head 13 +  Else If sAddressType = 'SHIP'
.head 14 -  Set sAddressType = 'BUS'
.head 13 +  Else If sAddressType = 'BUS'
.head 14 -  Set sAddressType = 'MEET'
.head 13 +  Else If sAddressType = 'MEET'
.head 14 -  Return TRUE
.head 13 +  Else
.head 14 -  Return TRUE
.head 12 +  Else
.head 13 -  Set bStopFetch = TRUE
.head 13 -  Return FALSE
.head 10 +  Else
.head 11 -  Set sAddressType = 'MEET'
.head 11 -  Set bStopFetch = FALSE
.head 11 -  Set nInd = FETCH_EOF
.head 11 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 12 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 13 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 14 +  If sGotDefaultShipping = 'Y' OR sAddressType != 'SHIP'
.head 15 -  Set dtAddressDT = dtGotAddressDT
.head 15 -  Set sAddrType = sGotAddressType
.head 15 -  Set sAddressLine1 = sGotAddressLine1
.head 15 -  Set sAddressLine2 = sGotAddressLine2
.head 15 -  Set sSuburb = sGotSuburb
.head 15 -  Set sPostcode = sGotPostcode
.head 15 -  Set sState = sGotState
.head 15 -  Set sCountry = sGotCountry
.head 15 -  Set sAreaCode = sGotAreaCode
.head 15 -  Set sPhoneNo = sGotPhoneNo
.head 15 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 15 -  Set sFaxNo = sGotFaxNo
.head 15 -  Set sComments = sGotComments
.head 15 -  Set sMeetId = sGotMeetId
.head 15 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 15 -  Return TRUE
.head 14 +  Else
.head 15 -  Set sAddressType = 'BUS'
.head 15 -  Set nInd = FETCH_EOF
.head 13 +  Else If sAddressType = 'MEET'
.head 14 -  Return TRUE
.head 13 +  Else
.head 14 -  Return TRUE
.head 12 +  Else
.head 13 -  Set bStopFetch = TRUE
.head 13 -  Return FALSE
.head 8 +  Else
.head 9 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Disconnect( )
.head 7 -  Call haSqlHandles[ nSqlHandleNoConfAmt ].Disconnect( )
.head 7 -  Call GetCustTypeAndDefDelType2( nTmp, sTmp, sTmp, sTmp, SH_cls_Disconnect )
.head 7 -  Return TRUE
.head 3 +  Function: GetDefaultShipAddress
.head 4 -  Description: Given a customer number this function returns the customer_type
and the second receive parameter classifies GC for Garden Centers
OR for orchadists and the third parameter returns the customers
Default delivery type
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Number: nYear
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Receive Boolean: bPickUpAddress
.head 5 -  Number: nActionType
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  !
.head 5 -  !
.head 5 -  Date/Time: dtGotAddressDT
.head 5 -  String: sGotAddressType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  String: sGotDefaultShipping
.head 5 -  Number: nSqlHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  !
.head 5 -  String: sAddressType
.head 5 -  String: sCustType
.head 5 -  String: sGCOR
.head 5 -  String: sDefDelType
.head 5 -  Boolean: bStopFetch
.head 5 -  Boolean: bAfterConfirmations
.head 5 -  Number: nSumConfAmt
.head 5 -  Boolean: bNoDefaultShipping
.head 5 -  Number: nTmp
.head 5 -  String: sTmp
.head 4 +  Actions
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( '2605GetDefShip' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " 
SELECT
	Add_Added_DT,
	Address_Type,
	Address_1,
	Address_2,
	Suburb,
	Postcode,
	State,
	Country,
	Area_Code,
	Phone_No,
	Area_Code_Fax,
	Fax_No,
	Comments,
	Address_Meet_Id,
	Main_Address_Flag,
	Default_Shipping
FROM 
	Customer_Address
WHERE 
	Cust_No = :1 AND 
	Default_Shipping = 'Y' "
.head 7 -  Set sNameHandle = '2605GetDefShip'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':dtGotAddressDT, :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState,
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments,
:sGotMeetId, :sGotMainAddressFlag, :sGotDefaultShipping'
.head 7 -  !
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sCustType = ''
.head 7 -  Set sGCOR = ''
.head 7 -  Set sDefDelType = ''
.head 7 -  !
.head 7 -  Set dtAddressDT = DATETIME_Null
.head 7 -  Set sAddressType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set dtGotAddressDT = DATETIME_Null
.head 7 -  Set sGotAddressType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set bPickUpAddress = FALSE
.head 7 -  Call GetCustTypeAndDefDelType2( nCustNo, sCustType, sGCOR, sDefDelType, SH_cls_Execute )
.head 7 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 9 -  Set dtAddressDT = dtGotAddressDT
.head 9 -  Set sAddrType = sGotAddressType
.head 9 -  Set sAddressLine1 = sGotAddressLine1
.head 9 -  Set sAddressLine2 = sGotAddressLine2
.head 9 -  Set sSuburb = sGotSuburb
.head 9 -  Set sPostcode = sGotPostcode
.head 9 -  Set sState = sGotState
.head 9 -  Set sCountry = sGotCountry
.head 9 -  Set sAreaCode = sGotAreaCode
.head 9 -  Set sPhoneNo = sGotPhoneNo
.head 9 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 9 -  Set sFaxNo = sGotFaxNo
.head 9 -  Set sComments = sGotComments
.head 9 -  Set sMeetId = sGotMeetId
.head 9 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 9 -  Return TRUE
.head 8 +  Else
.head 9 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Disconnect( )
.head 7 -  Call GetCustTypeAndDefDelType2( nTmp, sTmp, sTmp, sTmp, SH_cls_Disconnect )
.head 7 -  Return TRUE
.head 3 +  Function: GetAddressFromDelAddrDT
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Date/Time: dtAddrDT
.head 5 -  Receive String: sAddressType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nSqlHandleNo
.head 5 -  Number: nMeetSqlHandleNo
.head 5 -  !
.head 5 -  String: sGotAddressType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Boolean: bStopFetch
.head 4 +  Actions
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GETADDRSFRMDT' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT
Address_Type,
Address_1,
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag
FROM Customer_Address
WHERE Cust_No = :1 AND Add_Added_DT = :2 "
.head 7 -  Set sName = 'GETADDRSFRMDT'
.head 7 -  Set sBind = ':nCustNo, :dtAddrDT'
.head 7 -  Set sInto = ':sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState,
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments,
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sAddressType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set sGotAddressType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 9 -  !
.head 9 -  Set nMeetSqlHandleNo = SqlHandlesGetReferenceNo( 'GETMEETADDRS' )
.head 9 +  If NOT sGotMeetId = ''
.head 10 -  Set sSql = " SELECT
	Meet_Address_1,
	Meet_Address_2,
	Meet_Suburb,
	Meet_State
  FROM
	Meet_Address
  WHERE
	Meet_Id  = :1 "
.head 10 -  Set sName = 'GETMEETADDRS'
.head 10 -  Set sBind = ':sGotMeetId'
.head 10 -  Set sInto = ':sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState'
.head 10 -  !
.head 10 -  Call haSqlHandles[ nMeetSqlHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 10 -  Call SqlVarSetup( haSqlHandles[ nMeetSqlHandleNo ].hSqlHandle )
.head 10 +  ! If NOT bMeetHandleConnected
.head 11 -  Set bMeetHandleConnected = SqlConnect( hSqlMeetHandle )
.head 11 +  If bMeetHandleConnected
.head 12 -  Call SqlSetLockTimeout( hSqlMeetHandle, SQLTIMEOUT )
.head 12 -  Call SqlSetParameter( hSqlMeetHandle, DBP_PRESERVE, TRUE, ''  )
.head 11 +  Else
.head 12 -  Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 12 -  Return FALSE
.head 10 +  ! If NOT bMeetHandlePrepared
.head 11 -  Set sSql = ' SELECT Meet_Address_1, Meet_Address_2, Meet_Suburb, Meet_State
  FROM Meet_Address
  INTO :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState
  WHERE Meet_Id  = :sGotMeetId '
.head 11 +  If SqlPrepare( hSqlMeetHandle, sSql )
.head 12 -  Set bMeetHandlePrepared = TRUE
.head 11 +  Else
.head 12 -  Set bMeetHandlePrepared = FALSE
.head 10 +  If haSqlHandles[ nMeetSqlHandleNo ].Execute( )
.head 11 -  Call haSqlHandles[ nMeetSqlHandleNo ].FetchNext( nInd )
.head 10 +  Else
.head 11 -  Call SalMessageBox( 'SqlExecute had a error in GetDeliveryAddress, Contact programmers please!', 'ERROR', MB_Ok )
.head 11 -  Return FALSE
.head 9 -  Set sAddressType = sGotAddressType
.head 9 -  Set sAddressLine1 = sGotAddressLine1
.head 9 -  Set sAddressLine2 = sGotAddressLine2
.head 9 -  Set sSuburb = sGotSuburb
.head 9 -  Set sPostcode = sGotPostcode
.head 9 -  Set sState = sGotState
.head 9 -  Set sCountry = sGotCountry
.head 9 -  Set sAreaCode = sGotAreaCode
.head 9 -  Set sPhoneNo = sGotPhoneNo
.head 9 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 9 -  Set sFaxNo = sGotFaxNo
.head 9 -  Set sComments = sGotComments
.head 9 -  Set sMeetId = sGotMeetId
.head 9 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 9 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Disconnect( )
.head 7 -  Return haSqlHandles[ nMeetSqlHandleNo ].Disconnect( )
.head 3 +  Function: GetDeliveryAddress
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Date/Time: dtAddrDT
.head 5 -  Receive String: sAddressType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sState
.head 5 -  Receive Date/Time: dtTmpShipDT
.head 5 -  Number: nActionType
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nSqlHandleNo
.head 5 -  Number: nMeetSqlHandleNo
.head 5 -  Number: nInd
.head 5 -  String: sGotAddressType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotState
.head 5 -  String: sGotMeetId
.head 5 -  Date/Time: dtGotTmpShipDT
.head 4 +  Actions
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GETDELADDRS' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 +  ! If NOT bHandleConnected
.head 8 -  Set bHandleConnected = SqlConnect( hSqlHandle )
.head 8 +  If bHandleConnected
.head 9 -  Call SqlSetLockTimeout( hSqlHandle, SQLTIMEOUT )
.head 9 -  Call SqlSetParameter( hSqlHandle, DBP_PRESERVE, TRUE, ''  )
.head 8 +  Else
.head 9 -  Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 9 -  Return FALSE
.head 7 +  ! If NOT bHandlePrepared
.head 8 -  Set sSql = ' SELECT Address_Type, Address_1, Address_2, Suburb, State, Address_Meet_Id, Temp_Ship_Date
  FROM Customer_Address
  INTO :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState, :sGotMeetId, :dtGotTmpShipDT
  WHERE Cust_No = :nCustNo AND Add_Added_DT = :dtAddrDT '
.head 8 +  If SqlPrepare( hSqlHandle, sSql )
.head 9 -  Set bHandlePrepared = TRUE
.head 8 +  Else
.head 9 -  Set bHandlePrepared = FALSE
.head 7 -  Set sSql = " SELECT
	Address_Type,
	Address_1,
	Address_2,
	Suburb,
	State,
	Address_Meet_Id,
	Temp_Ship_Date
  FROM
	Customer_Address
  WHERE
	Cust_No = :1 AND
	Add_Added_DT = :2 "
.head 7 -  Set sName = 'GETDELADDRS1'
.head 7 -  Set sBind = ':nCustNo, :dtAddrDT'
.head 7 -  Set sInto = ':sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState, :sGotMeetId, :dtGotTmpShipDT '
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 -  Set sAddressType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sState = ''
.head 7 -  Set sGotAddressType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set dtTmpShipDT = DATETIME_Null
.head 7 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 9 +  If NOT sGotMeetId = ''
.head 10 -  Set nMeetSqlHandleNo = SqlHandlesGetReferenceNo( 'GETMEETADDRSA' )
.head 10 +  If NOT sGotMeetId = ''
.head 11 -  Set sSql = " SELECT
	Meet_Address_1,
	Meet_Address_2,
	Meet_Suburb,
	Meet_State
  FROM
	Meet_Address
  WHERE
	Meet_Id  = :1 "
.head 11 -  Set sName = 'GETMEETADDRSA'
.head 11 -  Set sBind = ':sGotMeetId'
.head 11 -  Set sInto = ':sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState'
.head 11 -  !
.head 11 -  Call haSqlHandles[ nMeetSqlHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nMeetSqlHandleNo ].hSqlHandle )
.head 11 +  ! If NOT bMeetHandleConnected
.head 12 -  Set bMeetHandleConnected = SqlConnect( hSqlMeetHandle )
.head 12 +  If bMeetHandleConnected
.head 13 -  Call SqlSetLockTimeout( hSqlMeetHandle, SQLTIMEOUT )
.head 13 -  Call SqlSetParameter( hSqlMeetHandle, DBP_PRESERVE, TRUE, ''  )
.head 12 +  Else
.head 13 -  Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 13 -  Return FALSE
.head 11 +  ! If NOT bMeetHandlePrepared
.head 12 -  Set sSql = ' SELECT Meet_Address_1, Meet_Address_2, Meet_Suburb, Meet_State
  FROM Meet_Address
  INTO :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState
  WHERE Meet_Id  = :sGotMeetId '
.head 12 +  If SqlPrepare( hSqlMeetHandle, sSql )
.head 13 -  Set bMeetHandlePrepared = TRUE
.head 12 +  Else
.head 13 -  Set bMeetHandlePrepared = FALSE
.head 11 +  If haSqlHandles[ nMeetSqlHandleNo ].Execute( )
.head 12 -  Call haSqlHandles[ nMeetSqlHandleNo ].FetchNext( nInd )
.head 11 +  Else
.head 12 -  Call SalMessageBox( 'SqlExecute had a error in GetDeliveryAddress, Contact programmers please!', 'ERROR', MB_Ok )
.head 12 -  Return FALSE
.head 10 +  ! If NOT bMeetHandleConnected
.head 11 -  Set bMeetHandleConnected = SqlConnect( hSqlMeetHandle )
.head 11 +  If bMeetHandleConnected
.head 12 -  Call SqlSetLockTimeout( hSqlMeetHandle, SQLTIMEOUT )
.head 12 -  Call SqlSetParameter( hSqlMeetHandle, DBP_PRESERVE, TRUE, ''  )
.head 11 +  Else
.head 12 -  Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 12 -  Return FALSE
.head 10 +  ! If NOT bMeetHandlePrepared
.head 11 -  Set sSql = ' SELECT Meet_Address_1, Meet_Address_2, Meet_Suburb, Meet_State
  FROM Meet_Address
  INTO :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState
  WHERE Meet_Id  = :sGotMeetId '
.head 11 +  If SqlPrepare( hSqlMeetHandle, sSql )
.head 12 -  Set bMeetHandlePrepared = TRUE
.head 11 +  Else
.head 12 -  Set bMeetHandlePrepared = FALSE
.head 10 +  ! If SqlExecute( hSqlMeetHandle )
.head 11 -  Call SqlFetchNext( hSqlMeetHandle, nInd )
.head 10 +  ! Else
.head 11 -  Set bMeetHandlePrepared = FALSE
.head 11 -  Call SalMessageBox( 'SqlExecute had a error in GetDeliveryAddress, Contact programmers please!', 'ERROR', MB_Ok )
.head 11 -  Return FALSE
.head 8 -  Set sAddressType = sGotAddressType
.head 8 -  Set sAddressLine1 = sGotAddressLine1
.head 8 -  Set sAddressLine2 = sGotAddressLine2
.head 8 -  Set sSuburb = sGotSuburb
.head 8 -  Set sState = sGotState
.head 8 -  Set dtTmpShipDT = dtGotTmpShipDT
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Call SalMessageBox( 'SqlExecute had a error in GetDeliveryAddress, Contact programmers please!', 'ERROR', MB_Ok )
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nMeetSqlHandleNo ].Disconnect(  )
.head 7 -  Return haSqlHandles[ nSqlHandleNo ].Disconnect(  )
.head 3 +  Function: FixLineSpaceAddress
.head 4 -  Description: This function assumes that the variables passed in for all paramentes are strings of the
same length.  Even though the database columns are not, data can be fetched into variables
of the same length.  This function will then remove any blank line ( ie null string ) by
suffling DOWN the parameters values.  Therefore the names of the parements will not
necessaraly match the values.
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Receive String: sCustName
.head 5 -  Receive String: sBusName
.head 5 -  Receive String: sAddrL1
.head 5 -  Receive String: sAddrL2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sState
.head 5 -  Receive String: sPostcode
.head 4 -  Static Variables
.head 4 -  Local variables
.head 4 +  Actions
.head 5 +  If sPostcode = ''
.head 6 -  Set sCustName = ''
.head 6 -  Set sBusName = sCustName
.head 6 -  Set sAddrL1 = sBusName
.head 6 -  Set sAddrL2 = sAddrL1
.head 6 -  Set sSuburb = sAddrL2
.head 6 -  Set sState = sSuburb
.head 6 -  Set sPostcode = sState
.head 5 +  If sState = ''
.head 6 -  Set sCustName = ''
.head 6 -  Set sBusName = sCustName
.head 6 -  Set sAddrL1 = sBusName
.head 6 -  Set sAddrL2 = sAddrL1
.head 6 -  Set sSuburb = sAddrL2
.head 6 -  Set sState = sSuburb
.head 5 +  If sSuburb = ''
.head 6 -  Set sCustName = ''
.head 6 -  Set sBusName = sCustName
.head 6 -  Set sAddrL1 = sBusName
.head 6 -  Set sAddrL2 = sAddrL1
.head 6 -  Set sSuburb = sAddrL2
.head 5 +  If sAddrL2 = ''
.head 6 -  Set sCustName = ''
.head 6 -  Set sBusName = sCustName
.head 6 -  Set sAddrL1 = sBusName
.head 6 -  Set sAddrL2 = sAddrL1
.head 5 +  If sAddrL1 = ''
.head 6 -  Set sCustName = ''
.head 6 -  Set sBusName = sCustName
.head 6 -  Set sAddrL1 = sBusName
.head 5 +  If sBusName = ''
.head 6 -  Set sCustName = ''
.head 6 -  Set sBusName = sCustName
.head 3 +  Function: FormatAddressToAddressLines
.head 4 -  Description:
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  String: sCustName
.head 5 -  String: sBusName
.head 5 -  String: sAddrL1
.head 5 -  String: sAddrL2
.head 5 -  String: sSuburb
.head 5 -  String: sState
.head 5 -  String: sPostcode
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sAddressLine3
.head 5 -  Receive String: sAddressLine4
.head 5 -  Receive String: sAddressLine5
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sAddressLines[5]
.head 5 -  String: sFormatedAddressLines[5]
.head 5 -  Number: nAddrPos
.head 5 -  Number: nFmtAddrPos
.head 4 +  Actions
.head 5 -  Set sAddressLines[1] = sCustName
.head 5 -  Set sAddressLines[2] = sBusName
.head 5 -  Set sAddressLines[3] = sAddrL2
.head 5 -  Set sAddressLines[4] = sAddrL1
.head 5 -  Set sAddressLines[5] = sSuburb || ' ' || sState || ' ' || sPostcode
.head 5 -  !
.head 5 -  Set sFormatedAddressLines[1] = ''
.head 5 -  Set sFormatedAddressLines[2] = ''
.head 5 -  Set sFormatedAddressLines[3] = ''
.head 5 -  Set sFormatedAddressLines[4] = ''
.head 5 -  Set sFormatedAddressLines[5] = ''
.head 5 -  !
.head 5 -  ! Set nWorkPos = 1
.head 5 +  ! While nWorkPos < 6
.head 6 -  Set nPos = nWorkPos
.head 6 +  While sAddressLines[ nPos ] = ''
.head 7 +  While nPos < 6
.head 8 -  Set sAddressLines[ nPos ] = sAddressLines[ nPos + 1 ]
.head 8 -  Set nPos = nPos + 1
.head 7 -  Set sAddressLines[ nPos ] = ''
.head 6 -  Set nWorkPos = nWorkPos + 1
.head 5 -  !
.head 5 -  Set nAddrPos = 1
.head 5 -  Set nFmtAddrPos = 1
.head 5 +  While nAddrPos <= 5
.head 6 +  If sAddressLines[ nAddrPos ] != ''
.head 7 -  Set sFormatedAddressLines[ nFmtAddrPos ] = sAddressLines[ nAddrPos ]
.head 7 -  Set nFmtAddrPos = nFmtAddrPos + 1
.head 6 -  Set nAddrPos = nAddrPos + 1
.head 5 -  !
.head 5 -  Set sAddressLine1 = sFormatedAddressLines[1]
.head 5 -  Set sAddressLine2 = sFormatedAddressLines[2]
.head 5 -  Set sAddressLine3 = sFormatedAddressLines[3]
.head 5 -  Set sAddressLine4 = sFormatedAddressLines[4]
.head 5 -  Set sAddressLine5 = sFormatedAddressLines[5]
.head 3 +  Function: GetContactDetails
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Receive String: sContactTitle
.head 5 -  Receive String: sContactGivenName
.head 5 -  Receive String: sContactSurname
.head 5 -  Receive String: sContactWrkPhCode
.head 5 -  Receive String: sContactWrkPh
.head 5 -  Receive String: sContactAHPhCode
.head 5 -  Receive String: sContactAHPh
.head 5 -  Receive String: sContactMobPhCode
.head 5 -  Receive String: sContactMobPh
.head 5 -  Number: nActionType
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nSqlHandleNo
.head 5 -  Number: nInd
.head 5 -  String: sGotContactTitle
.head 5 -  String: sGotContactGivenName
.head 5 -  String: sGotContactSurname
.head 5 -  String: sGotContactWrkPhCode
.head 5 -  String: sGotContactWrkPh
.head 5 -  String: sGotContactAHPhCode
.head 5 -  String: sGotContactAHPh
.head 5 -  String: sGotContactMobPhCode
.head 5 -  String: sGotContactMobPh
.head 4 +  Actions
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GETCONTACTDETS2' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT
	Contact_Title,
	Contact_Given_Name,
	Contact_Surname,
	Wrk_Phone_Code,
	Contact_Work_Phone,
	AH_Phone_code,
	Contact_AH_Phone,
  	Mob_Phone_code,
	Contact_Mob_Phone
  FROM
	Customer_Contacts
  WHERE
	Cust_No = :1
  AND 	Main_Contact_Flag = 'Y' "
.head 7 -  Set sName = 'GETCONTACTDETS2'
.head 7 -  Set sBind = ':nCustNo'
.head 7 -  Set sInto = ':sGotContactTitle, :sGotContactGivenName, :sGotContactSurname, :sGotContactWrkPhCode, :sGotContactWrkPh, :sGotContactAHPhCode,
:sGotContactAHPh, :sGotContactMobPhCode, :sGotContactMobPh '
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 +  ! If NOT bMeetHandleConnected
.head 8 -  Set bMeetHandleConnected = SqlConnect( hSqlMeetHandle )
.head 8 +  If bMeetHandleConnected
.head 9 -  Call SqlSetLockTimeout( hSqlMeetHandle, SQLTIMEOUT )
.head 9 -  Call SqlSetParameter( hSqlMeetHandle, DBP_PRESERVE, TRUE, ''  )
.head 8 +  Else
.head 9 -  Call SalMessageBox( 'Connection in Database Error, could not obtain handle!', 'Error', MB_Ok )
.head 9 -  Return FALSE
.head 7 +  ! If NOT bMeetHandlePrepared
.head 8 -  Set sSql = ' SELECT Meet_Address_1, Meet_Address_2, Meet_Suburb, Meet_State
  FROM Meet_Address
  INTO :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotState
  WHERE Meet_Id  = :sGotMeetId '
.head 8 +  If SqlPrepare( hSqlMeetHandle, sSql )
.head 9 -  Set bMeetHandlePrepared = TRUE
.head 8 +  Else
.head 9 -  Set bMeetHandlePrepared = FALSE
.head 7 -  Set sGotContactTitle = ''
.head 7 -  Set sGotContactGivenName = ''
.head 7 -  Set sGotContactSurname = ''
.head 7 -  Set sGotContactWrkPhCode = ''
.head 7 -  Set sGotContactWrkPh = ''
.head 7 -  Set sGotContactAHPhCode = ''
.head 7 -  Set sGotContactAHPh = ''
.head 7 -  Set sGotContactMobPhCode = ''
.head 7 -  Set sGotContactMobPh = ''
.head 7 -  !
.head 7 -  Set sContactTitle = ''
.head 7 -  Set sContactGivenName = ''
.head 7 -  Set sContactSurname = ''
.head 7 -  Set sContactWrkPhCode = ''
.head 7 -  Set sContactWrkPh = ''
.head 7 -  Set sContactAHPhCode = ''
.head 7 -  Set sContactAHPh = ''
.head 7 -  Set sContactMobPhCode = ''
.head 7 -  Set sContactMobPh = ''
.head 7 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 9 -  Set sContactTitle = sGotContactTitle
.head 9 -  Set sContactGivenName = sGotContactGivenName
.head 9 -  Set sContactSurname = sGotContactSurname
.head 9 -  Set sContactWrkPhCode = sGotContactWrkPhCode
.head 9 -  Set sContactWrkPh = sGotContactWrkPh
.head 9 -  Set sContactAHPhCode = sGotContactAHPhCode
.head 9 -  Set sContactAHPh = sGotContactAHPh
.head 9 -  Set sContactMobPhCode = sGotContactMobPhCode
.head 9 -  Set sContactMobPh = sGotContactMobPh
.head 9 -  Return TRUE
.head 7 +  Else
.head 8 -  Call SalMessageBox( 'SqlExecute had a error in GetDeliveryAddress, Contact programmers please!', 'ERROR', MB_Ok )
.head 8 -  Return FALSE
.head 7 +  ! Loop Execute
.head 8 +  Loop Connect
.head 9 +  If NOT bHandleConnected
.head 10 -  Set bHandleConnected = SqlConnect( hSqlHandle )
.head 10 +  If bHandleConnected
.head 11 -  Call SqlSetLockTimeout( hSqlHandle, SQLTIMEOUT )
.head 11 -  Call SqlSetParameter( hSqlHandle, DBP_PRESERVE, TRUE, ''  )
.head 11 -  ! Break Connect
.head 10 +  Else
.head 11 +  If IDNO = SalMessageBox( 'Could not connect handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -  Break Connect
.head 9 +  If bAnyHandleConnected
.head 10 -  Break Connect
.head 9 +  Else
.head 10 -  Set bAnyHandleConnected = SqlConnect( hSqlAnyHandle )
.head 10 +  If bAnyHandleConnected
.head 11 -  Call SqlSetLockTimeout( hSqlAnyHandle, SQLTIMEOUT )
.head 11 -  Call SqlSetParameter( hSqlAnyHandle, DBP_PRESERVE, TRUE, ''  )
.head 11 -  Break Connect
.head 10 +  Else
.head 11 +  If IDNO = SalMessageBox( 'Could not connect handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -  Break Connect
.head 8 +  Loop Prepare
.head 9 +  If NOT bHandlePrepared
.head 10 -  Set sSql = " SELECT Contact_Title, Contact_Given_Name, Contact_Surname,
  Wrk_Phone_Code, Contact_Work_Phone, AH_Phone_code, Contact_AH_Phone,
  Mob_Phone_code, Contact_Mob_Phone
  FROM Customer_Contacts
  INTO :sGotContactTitle, :sGotContactGivenName, :sGotContactSurname,
  :sGotContactWrkPhCode, :sGotContactWrkPh, :sGotContactAHPhCode, :sGotContactAHPh,
  :sGotContactMobPhCode, :sGotContactMobPh
  WHERE Cust_No = :nCustNo AND MAIN_CONTACT_FLAG = 'Y' "
.head 10 +  If SqlPrepare( hSqlHandle, sSql )
.head 11 -  Set bHandlePrepared = TRUE
.head 11 -  ! Break Prepare
.head 10 +  Else
.head 11 -  Set bHandlePrepared = FALSE
.head 11 +  If IDNO = SalMessageBox( 'Could not prepare handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -  Break Prepare
.head 9 +  If bAnyHandlePrepared
.head 10 -  Break Prepare
.head 9 +  Else
.head 10 -  Set sSql = ' SELECT Contact_Title, Contact_Given_Name, Contact_Surname,
  Wrk_Phone_Code, Contact_Work_Phone, AH_Phone_code, Contact_AH_Phone,
  Mob_Phone_code, Contact_Mob_Phone
  FROM Customer_Contacts
  INTO :sGotContactTitle, :sGotContactGivenName, :sGotContactSurname,
  :sGotContactWrkPhCode, :sGotContactWrkPh, :sGotContactAHPhCode, :sGotContactAHPh,
  :sGotContactMobPhCode, :sGotContactMobPh
  WHERE Cust_No = :nCustNo '
.head 10 +  If SqlPrepare( hSqlAnyHandle, sSql )
.head 11 -  Set bAnyHandlePrepared = TRUE
.head 11 -  Break Prepare
.head 10 +  Else
.head 11 -  Set bAnyHandlePrepared = FALSE
.head 11 +  If IDNO = SalMessageBox( 'Could not prepare handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -  Break Prepare
.head 8 -  !
.head 8 -  Set sGotContactTitle = ''
.head 8 -  Set sGotContactGivenName = ''
.head 8 -  Set sGotContactSurname = ''
.head 8 -  Set sGotContactWrkPhCode = ''
.head 8 -  Set sGotContactWrkPh = ''
.head 8 -  Set sGotContactAHPhCode = ''
.head 8 -  Set sGotContactAHPh = ''
.head 8 -  Set sGotContactMobPhCode = ''
.head 8 -  Set sGotContactMobPh = ''
.head 8 -  !
.head 8 -  Set sContactTitle = ''
.head 8 -  Set sContactGivenName = ''
.head 8 -  Set sContactSurname = ''
.head 8 -  Set sContactWrkPhCode = ''
.head 8 -  Set sContactWrkPh = ''
.head 8 -  Set sContactAHPhCode = ''
.head 8 -  Set sContactAHPh = ''
.head 8 -  Set sContactMobPhCode = ''
.head 8 -  Set sContactMobPh = ''
.head 8 -  !
.head 8 +  If SqlExecute( hSqlHandle )
.head 9 +  If SqlFetchNext( hSqlHandle, nInd )
.head 10 -  Set sContactTitle = sGotContactTitle
.head 10 -  Set sContactGivenName = sGotContactGivenName
.head 10 -  Set sContactSurname = sGotContactSurname
.head 10 -  Set sContactWrkPhCode = sGotContactWrkPhCode
.head 10 -  Set sContactWrkPh = sGotContactWrkPh
.head 10 -  Set sContactAHPhCode = sGotContactAHPhCode
.head 10 -  Set sContactAHPh = sGotContactAHPh
.head 10 -  Set sContactMobPhCode = sGotContactMobPhCode
.head 10 -  Set sContactMobPh = sGotContactMobPh
.head 10 -  Return TRUE
.head 9 +  Else
.head 10 +  If SqlExecute( hSqlAnyHandle )
.head 11 -  Call SqlFetchNext( hSqlAnyHandle, nInd )
.head 11 -  Set sContactTitle = sGotContactTitle
.head 11 -  Set sContactGivenName = sGotContactGivenName
.head 11 -  Set sContactSurname = sGotContactSurname
.head 11 -  Set sContactWrkPhCode = sGotContactWrkPhCode
.head 11 -  Set sContactWrkPh = sGotContactWrkPh
.head 11 -  Set sContactAHPhCode = sGotContactAHPhCode
.head 11 -  Set sContactAHPh = sGotContactAHPh
.head 11 -  Set sContactMobPhCode = sGotContactMobPhCode
.head 11 -  Set sContactMobPh = sGotContactMobPh
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Set bAnyHandlePrepared = FALSE
.head 11 +  If IDNO = SalMessageBox( 'Could not execute ANY handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -  Return FALSE
.head 8 +  Else
.head 9 -  Set bHandlePrepared = FALSE
.head 9 +  If IDNO = SalMessageBox( 'Could not execute handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 10 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nSqlHandleNo ].Disconnect(  )
.head 6 +  Case SH_cls_RePrepare
.head 7 -  Return haSqlHandles[ nSqlHandleNo ].RePrepare(  )
.head 2 -  Class Definitions
.data RESOURCE 0 0 1 3138615660
0000: 2802000098010000 0000000000000000 0200000500FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F1D003C00 000D63006C735365
0040: 6E64456D0061696C 7340000000F00200 0000101900000001 6A01300500000058
0060: 0100730000000100 00001B1900040004 0000026A010600EC 000058D900010000
0080: 0180810000000100 01000863514F456D 07C0000000067A00 00194B00016A051B
00A0: 009A0173A3000100 00CD190019120001 6A080000F6009A68 0001000032B00000
00C0: 00190084016A0B00 00003D9A00011A00 004B00002C001900 016A610E0000009A
00E0: 8F00010006006400 0000194B00016A11 D80000009AA30001 0000C17D00000004
0100: 100001026A140000 FE00838001000000 7F01888004000002 00100010636C546F
0120: 6F006C5469705769 6E64006F77220000 000100BD00048500 036A01050D009C02
0140: 7300D90001001801 8004000300200000 0C636C7262004765 6E6572616C22A200
0160: 00010000B70400B4 026A060031C60273 00011B0001801D32 000004000CC76362
0180: 474F400000F40200 00961900016A3700 DE02467300010000 9B1900042500026A
01A0: 0700EC0000DED900 0100
.enddata
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control: cSpinField
.head 3 -  ActiveX:
.head 2 -  Application Actions
