echo off
cls
echo ÿ
echo ÿ
echo ÿ
echo     Thank you for ordering an "IBM Underground" shareware disk
echo ÿ
echo     The programs on this disk have been collected by Salrail Pty Ltd 
echo     from various sources and are provided as a service to the readers 
echo     of the IBM Underground column in Your Computer Magazine
echo ÿ
echo     The programs are copyright by the respective authors. 
echo     After initial evaluation you should register with the authors,
echo     The registration fee requested by each author is shown in 
echo     the manual-on-disk for each program.
echo ÿ
echo     Salrail Pty Ltd
echo     PO Box 102
echo     Haberfield, NSW, 2045
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
pause
cls
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
ECHO                           DISCLAIMER
echo ÿ
echo     Salrail Pty Ltd makes no representation as to the quality of these 
echo     programs and no warranty is made as to the fitness of these 
echo     programs for any purpose. 
echo ÿ
echo     By unpacking the files on this disk and using the programs provided 
echo     the user accepts the responsibility of ensuring that the programs 
echo     meet the user's needs and the user also accepts the responsibility 
echo     of ensuring that the programs will cause no harm to the user's 
echo     computer equipment computer software or computer data files.
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
pause
cls
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo     *********************************************************************** 
echo     It is recommended that before running any new software, including the 
echo     programs on this disk, you back up all files on your hard disk and have 
echo     up-to-date back-up copies of all programs and data normally stored on 
echo     floppy disk.
echo     *********************************************************************** 
echo ÿ
echo ÿ
echo     *********************************************************************** 
echo     The master for this disk, and all programs on it, have been scanned 
echo     for viruses with the program SCAN 3.1V62 by McAfee Associates. No virus 
echo     was detected, however to guard against any viruses having infected the 
echo     disk after it left Salrail Pty Ltd you should use the appropriate 
echo     precautions including but not limited to scanning the disk and all files 
echo     with virus detection software that is known to be effective and 
echo     up-to-date.
echo     *********************************************************************** 
echo ÿ
pause
cls
echo ÿ
echo                     UNPACKING THE FILES
ECHO ÿ
echo   The programs are in self-unpacking archives. Each 
echo   contains several files which have been compressed and combined into one file. 
echo   To unpack a file
echo ÿ
echo          -    Change to the drive an directory where you want to put the 
echo               unpacked files. If necessary, create a new directory.
echo ÿ
echo          -    If this disk is in drive A, then at the DOS prompt type
echo ÿ
echo                  A:filename
echo ÿ
echo               Replace the word 'filename' in the above command with the 
echo               actual name of the archive file you want to unpack. 
echo ÿ
echo          -    To unpack FILENAME.EXE or FILENAME.COM from a disk in 
echo               drive B, the command would be
echo ÿ
echo                  B:filename 
echo ÿ
pause
cls
echo ÿ
echo                      MANUALS
echo ÿ
echo     Each archive file contains several files. 
echo ÿ
echo     These may include demonstration echo files and manuals ready to
echo     print out. Typically the manuals are in text files with 
echo     a .DOC or .TXT extension. They can be printed with the command 
echo ÿ
echo       COPY filename.ext PRN
echo ÿ
echo     Most files are paginated for 66 line paper, and COPYing to PRN will 
echo     not work if you use 70 line (A4) paper. In this case,
echo ÿ
echo           - Load the file into your word processor.
echo           - Set the top and bottom margins to 2 lines.
echo           - Set the left and right margins to zero.
echo           - Print the file from the word processor.
echo ÿ
echo ÿ
echo ÿ
echo ÿ
pause
cls
echo Disk No   SAL-031
echo ÿ
echo This disk contains the following files.  
echo ÿ
echo ICO       A collection of about 400 icons in .ICO files for Windows 3.0. 
echo ÿ
echo ICONDR    Create and edit icons for Windows 3.0
echo ÿ
echo ICONLIB   A collection of around 200 icons in a .EXE file
echo ÿ
echo VI101     View your .ICO files
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
echo ÿ
pause
cls
echo We recommend that you create a new directory for your icon
echo files and for the programs that can edit and view them. 
echo If your Windows programs are in the C:\WINDOWS directory,
echo then a good icon directory might be C:\WINDOWS\ICONS.
echo ÿ
echo Change to your icon directory, then run the programs on the 
echo distribution disk with the commands:
echo ÿ
echo      A:ICO
echo ÿ
echo      A:ICONDR
echo ÿ
echo      A:ICONLIB
echo ÿ
echo      A:VI101
echo ÿ
echo These commands will unpack the various files into the default
echo directory. If the distribution disk is not in the A drive,
echo use the correct drive letter instead of A.
echo ÿ
echo ÿ
echo ÿ
echo ÿ
pause
cls
echo Now start Windows. We recommend that you do not run any 
echo programs under Windows while installing icons as Windows
echo may terminate with an Unrecoverable Application Error should 
echo it have difficulty reading an icon file.
echo ÿ
echo We recommend that you install ICONDR, ICONLIB and VI in your
echo Accessories Group.
echo ÿ
echo To install ICONLIB
echo ÿ
echo      (a)     Open the Accessories Group
echo ÿ
echo      (b)     Choose the New option in the File menu in Program
echo              Manager.
echo ÿ
echo      (c)     Choose Program Item
echo ÿ
echo      (d)     From the dialog box that opens, choose browse, 
echo              then change to the ICONS directory and select 
echo              ICONLIB.EXE
echo ÿ
echo Repeat the above for ICONDR and VI
echo ÿ
pause
cls
echo To view the icons in ICONLIB.EXE, launch it by double clicking 
echo on the icon you just inserted in the Accessories Group.
echo ÿ
echo To change a program's icon:
echo ÿ
echo      (a)     Click ONCE on its existing icon
echo ÿ
echo      (b)     Select File Properties in Program Manager
echo ÿ
echo      (c)     Select Change Icon
echo ÿ
echo      (d)     If using one of the icons in ICONLIB.EXE, enter 
echo              C:\WINDOWS\ICONS\ICONLIB.EXE as the name of the 
echo              file containing the icon. 
echo ÿ
echo      (e)     Repeatedly click on View Next until the desired 
echo              icon appears. 
echo ÿ
echo      (f)     Then click on OK in the Select Icon window, and 
echo              again on OK in the Program Item Properties 
echo              window.
echo ÿ
pause
cls
echo To use an ICO file
echo ÿ
echo      (a)    Run VI
echo ÿ
echo      (b)    Choose the desired icon, and note the name shown 
echo             beneath it.
echo ÿ
echo      (c)    Go to Program Item Properties as detailed above. 
echo ÿ
echo      (d)    Enter the icon name in the File Name box in the 
echo             Select Icon window. Note that you will have to 
echo             specify the drive and directory and also add the 
echo             .ICO extension to the name shown by VI
echo ÿ
echo             As an example, if the icon had the name XYZZY, and 
echo             your icon files are in C:\WINDOWS\ICONS, then 
echo             specify C:\WINDOWS\ICONS\XYZZY.ICO as the file
echo ÿ
echo      (e)    Confirm by clicking on OK in the various windows 
echo             until back at the Program Manager screen
echo ÿ