.head 0 +  Application Description: SQLWindows 5.01 Jans Part Details APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 4170705061746800 24006B3A5C63656E 747572615C636C61 73733B6B3A5C6365
0020: 6E747572615C666C 656D61706C730041 7070506174684C65 6E00040024000000
0040: 00557365476C6F62 616C506174680004 0001000000000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000130100 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE2FFFFFF000000 0000000000140300 009F010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: FRMCTBL.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: TABLE.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: STRINGS.APL
.head 2 -  File Include: METER.APL
.head 2 -  File Include: STACKS.APL
.head 2 -  File Include: VTMETER.APL
.head 2 -  File Include: FLAGS.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: CHECKBOX.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: QUERY.APL
.head 2 -  File Include: CMBFIELD.APL
.head 2 -  File Include: PICK.APL
.head 2 -  File Include: ACTIVATE.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: GROUPBOX.APL
.head 2 -  File Include: VTWIN.APL
.head 2 -  File Include: LISTBOX.APL
.head 2 -  File Include: VEHPARTS.APL
.head 2 -  File Include: DLGCTBL.APL
.head 2 -  File Include: VEHQUERY.APL
.head 2 -  File Include: VEHDETS.APL
.head 2 -  File Include: FRMDETS.APL
.head 2 -  File Include: MLFIELD.APL
.head 2 -  File Include: VEHSERV.APL
.head 2 -  File Include: SRVPUSED.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for PARTDETS.APL
.head 4 -  Number: PARTDETSAplMsgOffSet = SAM_User + 2600
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: PARTDETSAplConstOffSet = 1250
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 156078632
0000: 9A00000073000000 0000000000000000 020000050000006F 0100001019000000
0020: 010601E04C020000 0040730000000100 00A3880100192500 01066204B8000000
0040: 73D10001000068A1 0100190009010676 0B00006E00730034 010000BA015A0019
0060: 0001A206770B0000 1B730001008D00D3 0100161900040601 E000130000002673
0080: 0001000003
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1223806010
0000: 961B0000E1100000 0000000000000000 0200003000FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F21003C00 001063006C737062
0040: 5061727400446574 61696C735E800000 0003000000870400 0000800216010700
0060: 000001F800730000 0001D80000000420 0019000000011660 0108000000F88F00
0080: 010006001D000000 040B0003160109D8 000000F8B3000100 2101800400000142
00A0: 000013636C701F73 496E0076656E746F 72792AB000000001 0037190001B40116
00C0: 0800FFE080010000 001F018004030002 0000001104636C66 726D5061FB448122
00E0: 0000000100DE0004 1200021623000086 00160173006C0001 000180804F000000
0100: 03001C0010466F72 006D426173655461 62806C657C000000 04BD0019A5000116
0120: 090D00F0027300D1 0001000066190019 000901160A000000 7BF0003401000032
0140: 00580000190001C2 160B0000001EF000 01000D004B000000 D6040002B00C0000
0160: 00F0670001000301 8053000000860400 0B636CFF009A0000 00050000006F1900
0180: 6901160800433203 730000B401000019 5900040002DB0900 9E3200016D001D00
01A0: 161900041601B60A 0032670001000336 0000000400A50003 160BED0032D90001
01C0: 00603A0000001900 6901160C007B3200 3401000001806419 00000500F817636C
01E0: 805072696E744261 0069635265706F72 7444220000010000 6F19006901160900
0200: 63B0037300340100 0001800619000600 0000280C636C7047 65806E6572616C22
0220: 00E8000100002D19 0001166D0700FE8C 0373000100060001 8068000008000700
0240: 0009636C0748656C 709AB200000500B7 0400BE0200210A04 73000001DA000004
0260: 2C00190001166D08 000A8F0001003600 1D00194B00011609 DB000AA300010000
0280: CD360019D2000116 0AF6000A68000100 004FB200001900B4 01160B003D0A0001
02A0: 1A00000180192300 080000091F457869 8C7422000100DE00 19D200011607C600
02C0: 2204736800010000 018C80040009001C 000C506963004578 70616E642200D100
02E0: 0100005B040002DF 00989A047300018D 0001800411000A00 0012631E6C546F67
0300: 00676C6542757474 6F886E2200000100 DE00049A00020600 C600A604736C0001
0320: 00018C8004000B00 1C000C646647FE65 D1000100005B0400 03DF0098C4047300
0340: 010D0001803B0112 000C00001663F26C 476539546147651F 8A0200E115000000
0360: 2D190001166F000C 8805730000010036 001900194B000116 07DB000CA3000100
0380: 00C932000019D200 011608F6000C6800 0100004BB3001900 B4011609003D0C00
03A0: 011A0000640000AC 000400026D0A000C CF00012600680000 046B00020BDB000C
03C0: B3000100C16C0000 0004DA00020CF600 0C6C00010070B000 0000040086020D00
03E0: 00003D0C00011B00 740000AC00040002 610E0000000CCF00 0106007800000004
0400: 6B00020FD8000000 0CB3000100C97C00 00041A0002100000 F6000C6C00010080
0420: 3100000400018402 1612000000FFE480 0100001F8400008C 0019000101E11300
0440: 00003F8001F90000 17880000194B0001 1614D80000000CA3 00010000C1A10000
0460: 0019120001161600 00F6000C68000100 00BAB00000001900 8001160117000000
0480: 3D0C00011A0000D3 00002C0019000116 61180000000C8F00 01000600EC000000
04A0: 194B0001161AD800 00000CA300010000 D105010019120001 161C0000F6000C68
04C0: 000100001EB40100 1900A401161D0000 3D0C00011A000037 0100AD040003611E
04E0: 0000000CCF000186 0001803A0008000D 00001D636C015462 6C4D616B65005365
0500: 6C65637465640052 6F774B6579417220 726179840000047B 00046300010205FA
0520: 00004F800100FE00 CD040019D2000116 06C6005405736800 0100001DB2000019
0540: 00B4011607003D54 0001DA000036AC00 0400026D080054CF 0001860001801D00
0560: C8000E0000100143 6F6C756D6E471E65 6C4000D000000200 005B040002DA1605
0580: 0018660573000100 6D00040096190001 16B6060066470001 00006301805300E4
05A0: 0F00001000446961 6C6F6747659F9A00 E8000500002D1900 01166D1200EE8807
05C0: 7300000100360019 00046B000213DB00 EEB3000100CD1D00 19D200041614F600
05E0: EE6C00010036A300 040000A603150000 3DEE0001DB003A2C 0019000116691600
0600: 00EE8F000100C600 01801D8800100000 0C63F16362471B40 000200BD00198500
0620: 011601060D005A08 7300D10001000066 1900040069021607 007B5A0036010001
0640: 8000570000001100 00006C11635451C0 756572794469826F B800000006BD0004
0660: B50003138D007E08 73D1000100006604 0004006D0214007B 7E00B60100085900
0680: 040002DB15009E7E 00014D000C000096 19000116B4160000 7E47000100008325
06A0: 0000001985000116 0117ED007ED10001 0000603E00000019 0069011618007B7E
06C0: 0034010000018040 99000000120000CE 1151750361746146 6965A06C64740100
06E0: 0CBD0004B5000206 8D00A80873D10001 000066040004006D 0207007BA800B601
0700: 00085900040002DB 08009EA800016D00 0C00D6040002B609 00A8670001009B10
0720: 0019A50001160AED 00A8D10001000060 2900000019006901 160B007BA8003401
0740: 0000420018000004 000102DB0C007F80 F20100000F460000 009619000116B60D
0760: 00A8470001000083 5F00000004B50002 0EED00A8D9000100 6063000000190069
0780: 01160F007BA800B4 0100007C59000400 02DB10009EA80001 6D00800096190001
07A0: 16B4110000A84700 0100006301809900 C413000012631F43 6F6DF0626F4669B7
07C0: 0C00B70400B60206 0031BA08730001DA 000004AC00040002 6D0700BACF000136
07E0: 000800046B000208 DB00BAB3000100CD 0C0004DA000209F6 00BA6C00010010B3
0800: 001900B401160A00 3DBA0001DA000029 2C00190001166D0B 00BA8F0001003600
0820: 420004630001020C FB004F800100FE00 CD460019D2000116 0DF600BA68000100
0840: 005FB3000400B602 0E003DBA0001DB00 632C00190001166D 0F00BA8F00010036
0860: 007C00046B000210 DB00BAB3000100CD 800019D200011611 F600BA6800010000
0880: 018C8099001400FC 00127F43C0616368 657401F60C00D604 0002360700CC0846
08A0: 73000100009B0400 04B5000208ED00CC D900010066080004 006D0209007BCC00
08C0: B601000C59000400 02DB0A009ECC0001 6D00100096190001 16B60B00CC470001
08E0: 00009B290019A500 01160CED00CCD100 0100006642000400 6C01020D00FFC980
0900: 010000BF46590019 0001DA160E001ECC 0001006D005F00D6 040002B60F00CC67
0920: 0001009B630019A5 00011610ED00CCD1 00010000667C0004 006D0211007BCC00
0940: B601008059001900 01DA1612001ECC00 01000D0001803200 1900150015637E6C
0960: 4F0070657261746F 72464E69400000F4 0200009619000116 360600EA08467300
0980: 0100009B190019A5 00011607ED00EAD1 0001000018018004 001600F100136303
09A0: 794342596573004E 6F466C61672200D1 000100005B040002 DA16060098F60873
09C0: 00010D0001806400 110017000014634A 6C70536565034672 6F6D546133657C00
09E0: 047B00194B000116 071B001A0973A200 00010000CD190019 D200011608F6001A
0A00: 680001000032B300 1900B4011609003D 1A0001DA00004B2C 00190001166D0A00
0A20: 1A8F000100C60001 800408001800000D 636C595365634920 6E746F220000017A
0A40: 0000046B0003051B 00320973B3000100 310180190019F300 110070696E536561
0A60: 736F806E59656172 2200E8000100002D 190001166D06005C 8C09730001008600
0A80: 01804600C8001A00 00110D7074617274 0050726F6772616D D6B00000000700B7
0AA0: 0400BE020031B009 730001DA000004AC 000400026D0700B0 CF00013600080004
0AC0: 6B000208DB00B0B3 000100CD0C0019D2 00011609F600B068 0001000025B30004
0AE0: 00B6030A003DB000 01DB0029AC000400 026D0B00B0CF0001 06002D000000194B
0B00: 0001160CDB00B0A3 0001000001018052 0000001B40000000 0F636C53FE744730
0B20: 01000A7B00194B00 0116051B00C20973 A300010000CD1900 19D200011606F600
0B40: C2680001000032B2 00000400B6020700 3DC20001DB0036AC 000400026D0800C2
0B60: CF000136003A0004 6B000209DB00C2B3 000100CD3E0004DA 00020AF600C26C00
0B80: 010042B3000400B6 020B003DC20001DB 0046AC000400026D 0C00C2CF00010600
0BA0: 4A000000046B0002 0DDB00C2B3000100 C14E00000004DA00 020EF600C26C0001
0BC0: 00018C8004001C00 18000C637262478F 616C22D100010000 5B040002DB060090
0BE0: 220A730000010D00 0180210099001D00 0D0B705665685066 61735E00F4030000
0C00: D604000236070082 0A4673000100009B 040019A500011608 ED0082D100010000
0C20: 661D000400690316 09007B8200360100 01804621001E0000 BE11501356656963
0C40: 6C1865735E000300 BD0004B50002078D 00EE0A73D1000100 0066040019006901
0C60: 1608007BEE00B401 00001D5900040003 DA1609009EEE0001 8D0001800481001F
0C80: 00000012B9736661 7F658D22000100DE 00049A000222008E 000B73006C000100
0CA0: 0108803600002000 00CC00137344056F 4368696C649C5461 5E00E8000300002D
0CC0: 190001166D1300BA 8C0B730001003600 1900194B00011614 DB00BAA300010000
0CE0: CD320004DA000215 F600BA6C00010001 8C80210021005C00 0D7056176365735E
0D00: B3000300B70400B6 02070031E40B7300 01DA0000042C0019 0001166D0800E48F
0D20: 00010036001D0004 4B00031609DB00E4 B300010031018004 00228200001A636C
0D40: 737F658149644368 61721C5265742A00 D1000100001B1900 0101DB08007F80F2
0D60: 0100008F01800491 0023000013997366 5175F17956651A65 22000100BD0004B5
0D80: 0002210D00A40C73 00D9000100100180 9A00002400980000 127346916D446573
0DA0: 479761D600EC0007 002D190001166D14 0014880F73000001 0036001900194B00
0DC0: 011615DB0014A300 010000CD32001992 0001161600F60014 68000100004BB300
0DE0: 1900B00116011700 3D140001DA000064 2C00190001166D18 00148F0001000600
0E00: 7D000000194B0001 1619DA000014A300 010000C196000000 04DA00021AF60014
0E20: 6C00010001C88008 0000251C000D636D 627846726D40A200 00020000B70400B4
0E40: 02160600319E0F73 0001DA000004AC00 0400026D07009ECF 0001C600018004C0
0E60: 00260000000CE16D 6C47651B22000100 BD0004B50003058D 00B60F73D9000100
0E80: 18018021002700B8 00000F7007536572 76691863655E0003 00BD0004B5000207
0EA0: 8D00E00F73D10001 0000660400190061 01160108007BE000 B40100001D590004
0EC0: 0003DA1609009EE0 00018D0001801D01 002800000010639B 6656657F40A20000
0EE0: 020000B704008402 162C000000210410 730000019A000004 002C001900011669
0F00: 2D0000048E100001 00C60001803ACC00 2900126570536550 0661735573656444
0F20: 7C00000400006F04 006D02070063B810 7300B40100000459 00190001DA160800
0F40: 1EB80001006D001D 009619000416B609 00B8670001001B36 000400B500030AED
0F60: 00B8D90001001801 8004002A00390010 546F006F6C546970 57696E20646F7722
0F80: 0000017A0000046B 0003051B00721173 B200000100310180 04002B100000000C
0FA0: 665461E743614422 00000100006F0400 6D03070043681273 0000360100018046
0FC0: 21002C0000E00B63 66436108506F6F66 000000F403000006 290001071601A100
0FE0: 010068009E008001 FC00009B040004A5 000316098D007412 73D9000100660800
1000: 19006901160A007B 7400340100000180 6619002D00000C67 774D6F757365C057
1020: 6865656C22E80001 00002D19000116EF 008D73000100C600 01801DC0002E0000
1040: 000D0153656E6445 6D61326973400002 7A0000194B000116 051B00281373A200
1060: 00010000CD190004 D200021606F60028 6C00010001008081 0000002F00008000
1080: 0863514F456D83C0 00000006BD0019A5 000116058D007613 73D1000100006619
10A0: 0019006901160800 7B7600B401000032 5900190001DA160B 001E760001006D00
10C0: 4B009619000116B6 0E00764700010000 9B640019A5000116 11ED0076D1000100
10E0: 00667D0004006801 02161400FFC98001 00003F
.enddata
.head 3 +  Pushbutton Class: clspbPartDetails
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\PARTS.ICO
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbPickInto
.head 4 +  Class Variables
.head 5 -  String: sTmp
.head 5 -  Number: nTmp
.head 5 -  Window Handle: hWndTmp
.head 4 +  Instance Variables
.head 5 -  ! PUBLIC
.head 5 -  Window Handle: hWndPickIntoTable
.head 5 -  ! PRIVATE
.head 5 -  Number: nPartId
.head 5 -  String: sPartType
.head 5 -  String: sPartName
.head 5 -  String: sPartLocation
.head 5 -  String: sPartReOrderNo
.head 5 -  Number: nPartQuantity
.head 4 +  Functions
.head 5 +  Function: SetPartDetailsFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nNewPartId
.head 7 -  String: sNewPartType
.head 7 -  String: sNewPartName
.head 7 -  String: sNewPartLocation
.head 7 -  String: sNewPartReOrderNo
.head 7 -  Number: nNewPartQuantity
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set nPartId = nNewPartId
.head 7 -  Set sPartType = sNewPartType
.head 7 -  Set sPartName = sNewPartName
.head 7 -  Set sPartLocation = sNewPartLocation
.head 7 -  Set sPartReOrderNo = sNewPartReOrderNo
.head 7 -  Set nPartQuantity = nNewPartQuantity
.head 7 -  Return TRUE
.head 5 +  Function: GetPartDetailsFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Receive Number: nNewPartId
.head 7 -  Receive String: sNewPartType
.head 7 -  Receive String: sNewPartName
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set nNewPartId = nPartId
.head 7 -  Set sNewPartType = sPartType
.head 7 -  Set sNewPartName = sPartName
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set nPartId = NUMBER_Null
.head 6 -  Set sPartType = ''
.head 6 -  Set sPartName = ''
.head 6 -  Set sPartLocation = ''
.head 6 -  Set sPartReOrderNo = ''
.head 6 -  Set nPartQuantity = NUMBER_Null
.head 6 -  Set hWndPickIntoTable = hWndItem
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set clspbPartDetails.nActivateWindowType = ACTIVATE_FormWindow
.head 6 -  Set clspbPartDetails.sActivateDialogName = 'frmPartDetails'
.head 6 -  Set clspbPartDetails.hWndTable = hWndPickIntoTable
.head 6 -  Set clspbPartDetails.hWndParentTable = hWndPickIntoTable
.head 6 -  Set clspbPartDetails.hWndFieldLookUp = hWndItem
.head 5 +  On PAM_clsACTIVATE_PUSHFIELDS
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call PushWndHdl( hWndItem )
.head 6 -  Call PushNumber( nPartId )
.head 6 -  Call PushString( sPartType )
.head 6 -  Call PushString( sPartName )
.head 6 -  Call PushString( sPartLocation )
.head 6 -  Call PushString( sPartReOrderNo )
.head 6 -  Call PushNumber( nPartQuantity )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsACTIVATE_POPFIELDS
.head 6 -  Call PopNumber( nTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopNumber( nTmp, TRUE )
.head 6 -  Call PopWndHdl( hWndTmp, TRUE )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsPICK_LOOKUP
.head 6 -  Call PopString( sPartName, TRUE )
.head 6 -  Call PopString( sPartType, TRUE )
.head 6 -  Call PopNumber( nPartId, TRUE )
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_GETFIELDS, 0, 0 )
.head 6 -  Return TRUE
.head 3 +  Pushbutton Class: clspbPartsInventory
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\LETTERS.BMP
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbGeneral
.head 5 -  Class: clsTblMakeSelectedRowKeyArray
.head 4 +  Class Variables
.head 5 -  Number: naPartIds[*]
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Call SalSendClassMessageNamed( clsTblMakeSelectedRowKeyArray, SAM_Create, wParam, lParam )
.head 6 -  Return SalSendClassMessageNamed( clspbGeneral, SAM_Create, wParam, lParam )
.head 5 +  On SAM_Click
.head 6 +  If NOT GetNumberArrayList( naPartIds )
.head 7 -  Set naPartIds[ 0 ] = NUMBER_Null
.head 6 -  Call SalModalDialog( dlgPartInventoryRepDetails, hWndForm, naPartIds )
.head 3 +  Form Window Class: clsfrmPartDetails
.head 4 -  Title: Fleming's Nurseries Parts Details
.head 4 -  Icon File:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Automatically Created at Runtime? Class Default
.head 5 -  Initial State: Class Default
.head 5 -  Maximizable? Class Default
.head 5 -  Minimizable? Class Default
.head 5 -  Allow Child Docking? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  System Menu? Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 5.542"
.head 6 -  Height Editable? Class Default
.head 5 -  Form Size
.head 6 -  Width:  Class Default
.head 6 -  Height: Class Default
.head 6 -  Number of Pages: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Next Class Child Key: 79
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsFormChildTable
.head 4 -  Menu
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: 0.365"
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbSelect
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 58
.head 7 -  Class: clspbSelectFromTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 1.2"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbSelect.hWndTable = tblParts
.head 9 -  Set pbSelect.hWndSelectParent = hWndForm.clsfrmPartDetails.hWndActivateButton
.head 9 -  Set pbSelect.nSelectType = PICK_SelectManyToMany
.head 8 +  On PAM_clsPICK_PUSHFIELDS
.head 9 -  Call PushNumber( tblParts.colPartId )
.head 9 -  Call PushString( tblParts.colPartType )
.head 9 -  Call PushString( tblParts.colPartName )
.head 9 -  Return TRUE
.head 8 +  On PAM_clsPICK_POPFIELDS
.head 9 -  Call PopString( sTmp, TRUE )
.head 9 -  Call PopString( sTmp, TRUE )
.head 9 -  Call PopNumber( nTmp, TRUE )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbAddRows
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 8
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbSaveRows
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 9
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 8
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbDeleteRows
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 11
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRePopulate
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 12
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbTools
.head 7 -  Class Child Ref Key: 23
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  ! clspbFirstRec: pbFirstRec
.winattr class Pushbutton:
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 24
.head 7 -  Class: clspbFirstRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: First
.head 7 -  Window Location and Size
.head 8 -  Left: 6.4"
.head 8 -  Top: 0.0"
.head 8 -  Width:  0.6"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.58"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Arial
.head 7 -  Font Size: 8
.head 7 -  Font Enhancement: Bold
.head 7 -  Picture File Name: G:\APPS\GUPTA\ICONS\TOPREC.BMP
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.end
.head 7 -  Message Actions 
.head 6 +  ! clspbPrevRec: pbPrevRec
.winattr class Pushbutton:
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 25
.head 7 -  Class: clspbPrevRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Prev
.head 7 -  Window Location and Size
.head 8 -  Left: 7.0"
.head 8 -  Top: 0.0"
.head 8 -  Width:  0.6"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.58"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Arial
.head 7 -  Font Size: 8
.head 7 -  Font Enhancement: Bold
.head 7 -  Picture File Name: G:\APPS\GUPTA\ICONS\PREVREC.BMP
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.end
.head 7 -  Message Actions 
.head 6 +  ! clspbNextRec: pbNextRec
.winattr class Pushbutton:
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 26
.head 7 -  Class: clspbNextRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Next
.head 7 -  Window Location and Size
.head 8 -  Left: 7.6"
.head 8 -  Top: 0.0"
.head 8 -  Width:  0.6"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.58"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Arial
.head 7 -  Font Size: 8
.head 7 -  Font Enhancement: Bold
.head 7 -  Picture File Name: G:\APPS\GUPTA\ICONS\NEXTREC.BMP
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.end
.head 7 -  Message Actions 
.head 6 +  ! clspbLastRec: pbLastRec
.winattr class Pushbutton:
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 27
.head 7 -  Class: clspbLastRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title: Last
.head 7 -  Window Location and Size
.head 8 -  Left: 8.2"
.head 8 -  Top: 0.0"
.head 8 -  Width:  0.6"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.58"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Font Name: Arial
.head 7 -  Font Size: 8
.head 7 -  Font Enhancement: Bold
.head 7 -  Picture File Name: G:\APPS\GUPTA\ICONS\LASTREC.BMP
.head 7 -  Picture Transparent Color: None
.head 7 -  Image Style: Single
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Button Appearance: Standard
.end
.head 7 -  Message Actions 
.head 6 +  Pushbutton: pbPartsInventory
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 67
.head 7 -  Class: clspbPartsInventory
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 7.6"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbPartsInventory.hWndTable = tblParts
.head 9 -  Set pbPartsInventory.hWndColKey = tblParts.colPartId
.head 6 +  Pushbutton: pbPartVehicles
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 66
.head 7 -  Class: clspbPartVehicles
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 8.2"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbPartVehicles.hWndParentTable = tblParts
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbPartVehicles.SetPartVehiclesFields( tblParts.colPartId, tblParts.colPartType, tblParts.colPartName )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 42
.head 7 -  Class ChildKey: 72
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 43
.head 7 -  Class ChildKey: 73
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 44
.head 7 -  Class ChildKey: 74
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClearRows
.head 7 -  Class Child Ref Key: 52
.head 7 -  Class ChildKey: 76
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 50
.head 7 -  Class ChildKey: 77
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDClose
.head 7 -  Class Child Ref Key: 54
.head 7 -  Class ChildKey: 78
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDRead
.head 7 -  Class Child Ref Key: 55
.head 7 -  Class ChildKey: 79
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 -  Background Text: Step 1 - Part Type
.head 6 -  Resource Id: 29180
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 59
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.775"
.head 7 -  Top: 0.125"
.head 7 -  Width:  1.538"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Left
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Black
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Step 2 - Parts
.head 6 -  Resource Id: 29181
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 60
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.075"
.head 7 -  Top: 1.604"
.head 7 -  Width:  1.163"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Left
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Blue
.head 6 -  Background Color: Class Default
.head 5 +  Data Field: dfQQPartTypesOptions
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 61
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.775"
.head 8 -  Top: 0.344"
.head 8 -  Width:  4.875"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Black
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On SAM_Create
.head 8 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 8 -  Call SalSendMsg( hWndItem, PAM_clsDF_CLEAR, 0, 0 )
.head 7 +  On PAM_clsDF_CLEAR
.head 8 -  Set sQQPartTypeOptions = '%'
.head 8 -  Set sQQPartType = ''
.head 8 -  Return TRUE
.head 7 +  On SAM_AnyEdit
.head 8 -  Set sQQPartTypeOptions = dfQQPartTypesOptions || '%'
.head 8 -  Call SalSendMsg( lbQQPartTypes, PAM_clsLB_POPULATE, 0, 0 )
.head 7 +  On PAM_clsTBL_ZOOMTABLE
.head 8 +  If wParam
.head 9 -  Call SalHideWindow( hWndItem )
.head 9 -  Call SalDisableWindow( hWndItem )
.head 8 +  Else
.head 9 -  Call SalEnableWindow( hWndItem )
.head 9 -  Call SalShowWindow( hWndItem )
.head 5 +  List Box: lbQQPartTypes
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 62
.head 6 -  Class: clslbClass
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.775"
.head 7 -  Top: 0.625"
.head 7 -  Width:  4.875"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 1.021"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Multiple selection? Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Black
.head 6 -  Background Color: Class Default
.head 6 -  Horizontal Scroll? Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set lbQQPartTypes.sSqlPopStatement = ' SELECT DISTINCT 
  Part_Type 
FROM 
  Part 
WHERE 
  @UPPER( Part_Type ) LIKE @UPPER( :hWndForm.clsfrmPartDetails.sQQPartTypeOptions ) 
ORDER BY 
  Part_Type '
.head 8 -  Set lbQQPartTypes.bPopulateOnce = FALSE
.head 8 -  Set lbQQPartTypes.bGetCountOnPopulate = TRUE
.head 7 +  On SAM_Click
.head 8 -  Call SalSendClassMessage( SAM_Click, wParam, lParam )
.head 8 -  Set sQQPartType = lbQQPartTypes.sCurrentSelectionString
.head 8 -  Set sQuickBuildWhere = " Part_Type = :hWndForm.clsfrmPartDetails.sQQPartType "
.head 8 -  Call PushString( sQuickBuildWhere )
.head 8 +  If NOT SalSendMsg( tblParts, PAM_clsTBL_SEARCH, TRUE, 0 )
.head 9 -  Call PopString( sQuickBuildWhere, TRUE )
.head 7 +  On PAM_clsLB_POPULATE
.head 8 -  Call SalSendClassMessage( PAM_clsLB_POPULATE, wParam, lParam )
.head 8 -  Call SalSendMsg( tblParts, PAM_clsTBL_RESET, 0, 0 )
.head 7 +  On PAM_clsLB_POPULATEDCOUNT
.head 8 +  If lParam = 1
.head 9 -  Call SalListSetSelect( hWndItem, 0 )
.head 9 -  Call SalPostMsg( hWndItem, SAM_Click, 0, 0 )
.head 7 +  On PAM_clsTBL_ZOOMTABLE
.head 8 +  If wParam
.head 9 -  Call SalHideWindow( hWndItem )
.head 9 -  Call SalDisableWindow( hWndItem )
.head 8 +  Else
.head 9 -  Call SalEnableWindow( hWndItem )
.head 9 -  Call SalShowWindow( hWndItem )
.head 5 -  !
.head 5 +  Child Table: tblParts
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 28
.head 6 -  Class: clsTableGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.038"
.head 8 -  Top: 1.833"
.head 8 -  Width:  9.725"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 2.76"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colPartId
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 29
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Part Id
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.613"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Call GetNextPartId( colPartId, SH_cls_Execute )
.head 10 +  If colPartId > 0
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Call ErrorMessage( 'An error has occured in allocating the next Part Id. Please try and save again.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 9 +  On PAM_clsTBL_ROWDELETED
.head 10 +  If DeletePartVehicleParts( colPartId, SH_cls_Execute )
.head 11 -  Call DeletePartVehicleParts( 0, SH_cls_Commit )
.head 10 +  If DeletePartServPartsUsed( colPartId, SH_cls_Execute )
.head 11 -  Call DeletePartServPartsUsed( 0, SH_cls_Commit )
.head 7 +  Column: colPartType
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 63
.head 8 -  Class: clsColDropListGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Part Type
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.5"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colPartType.sSqlPopStatement = " SELECT DISTINCT Part_Type FROM Part "
.head 10 -  Set colPartType.bOrderBy = TRUE
.head 10 -  Set colPartType.bPopulateOnce = FALSE
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Call ErrorMessage( 'Please choose the part type first.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 7 +  Column: colPartName
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 31
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Part Name
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  2.875"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colPartName.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Call ErrorMessage( 'Please enter the part name first.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 7 +  Column: colPartLocation
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 64
.head 8 -  Class: clsColDropListGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Part Location
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.8"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colPartLocation.bOrderBy = TRUE
.head 10 -  Set colPartLocation.sSqlPopStatement = " SELECT DISTINCT Location FROM Part "
.head 10 -  Set colPartLocation.bPopulateOnce = FALSE
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Call ErrorMessage( 'Please choose the part location first.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 7 +  Column: colPartQuantity
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 32
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Quantity
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Right
.head 8 -  Width:  0.838"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: #0
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colPartQuantity.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Set colPartQuantity = 1
.head 10 -  Return TRUE
.head 9 +  On PAM_clsTBL_ROWNEWINIT
.head 10 -  Set colPartQuantity = 1
.head 7 +  Column: colPartReOrderNo
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 57
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Part ReOrder No.
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.8"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colPartReOrderNo.bOrderBy = TRUE
.head 6 +  Functions
.head 7 +  Function: GetNextPartId
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  Receive Number: nNextPartId
.head 9 -  Number: nActionType
.head 8 +  Static Variables
.head 9 -  ! hcSqlHandle: fcOurHandle
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nInd
.head 9 -  Number: nGotPartId
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetNextPartId' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " SELECT Max( Part_Id ) + 1
FROM Part "
.head 11 -  Set sName = 'NEXTPARTID'
.head 11 -  Set sBind = ''
.head 11 -  Set sInto = ':nGotPartId'
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Set nNextPartId = NUMBER_Null
.head 11 -  Set nGotPartId = NUMBER_Null
.head 11 -  !
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 +  If NOT nGotPartId > 0
.head 14 -  Set nGotPartId = 1
.head 13 -  Set nNextPartId = nGotPartId
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 +  Function: DeletePartVehicleParts
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  Number: nPartId
.head 9 -  Number: nActionType
.head 8 +  Static Variables
.head 9 -  ! hcSqlHandle: fcOurHandle
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'DeletePartVehicleParts' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " DELETE FROM Vehicle_Parts 
WHERE Part_Id = :1 "
.head 11 -  Set sName = 'DLPRTVEHPRT'
.head 11 -  Set sBind = ':nPartId'
.head 11 -  Set sInto = ''
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Execute( )
.head 10 +  Case SH_cls_Commit
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Commit( )
.head 10 +  Case SH_cls_Rollback
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Rollback( )
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 +  Function: DeletePartServPartsUsed
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  Number: nPartId
.head 9 -  Number: nActionType
.head 8 +  Static Variables
.head 9 -  ! hcSqlHandle: fcOurHandle
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'DeletePartServPartsUsed' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " DELETE FROM Service_Parts_Used 
WHERE Part_Id = :1 "
.head 11 -  Set sName = 'DLPRTSRVPUSD'
.head 11 -  Set sBind = ':nPartId'
.head 11 -  Set sInto = ''
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Execute( )
.head 10 +  Case SH_cls_Commit
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Commit( )
.head 10 +  Case SH_cls_Rollback
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Rollback( )
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 6 +  Window Variables
.head 7 -  ! PRIVATE
.head 7 -  String: sPartType
.head 7 -  String: sPartName
.head 7 -  String: sPartLocation
.head 7 -  String: sPartReOrderNo
.head 7 -  Number: nPartQuantity
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set sSQLPopHandle = ' SELECT 
  Part_Id, 
  Part_Type, 
  Part_Name, 
  Location, 
  Quantity_On_Hand, 
  Re_Order_No 
FROM 
  Part 
ORDER BY 
  Part_Type, Part_Name '
.head 8 -  Set sNAMEPopHandle = 'POPPARTS'
.head 8 -  Set sBINDPopHandle = ''
.head 8 -  Set sINTOPopHandle = ':clsfrmPartDetails.tblParts.colPartId, 
:clsfrmPartDetails.tblParts.colPartType, 
:clsfrmPartDetails.tblParts.colPartName, 
:clsfrmPartDetails.tblParts.colPartLocation,
:clsfrmPartDetails.tblParts.colPartQuantity, 
:clsfrmPartDetails.tblParts.colPartReOrderNo'
.head 8 -  !
.head 8 -  Set sSQLRefreshHandle = ' SELECT 
  Part_Id, 
  Part_Type, 
  Part_Name, 
  Location, 
  Quantity_On_Hand, 
  Re_Order_No 
FROM 
  Part 
WHERE 
  Part_Id = :1 '
.head 8 -  Set sNAMERefreshHandle = 'REFPARTS'
.head 8 -  Set sBINDRefreshHandle = ':clsfrmPartDetails.tblParts.colPartId'
.head 8 -  Set sINTORefreshHandle = ':clsfrmPartDetails.tblParts.colPartId, 
:clsfrmPartDetails.tblParts.colPartType, 
:clsfrmPartDetails.tblParts.colPartName, 
:clsfrmPartDetails.tblParts.colPartLocation,
:clsfrmPartDetails.tblParts.colPartQuantity, 
:clsfrmPartDetails.tblParts.colPartReOrderNo'
.head 8 -  !
.head 8 -  Set sSQLInsertHandle = 'INSERT INTO Part  
( Part_Id, 
  Part_Type, 
  Part_Name, 
  Location, 
  Quantity_On_Hand, 
  Re_Order_No  ) 
VALUES ( :1, :2, :3, :4, :5, :6 ) '
.head 8 -  Set sNAMEInsertHandle = 'INSPARTS'
.head 8 -  Set sBINDInsertHandle = ':clsfrmPartDetails.tblParts.colPartId, 
:clsfrmPartDetails.tblParts.colPartType, 
:clsfrmPartDetails.tblParts.colPartName, 
:clsfrmPartDetails.tblParts.colPartLocation,
:clsfrmPartDetails.tblParts.colPartQuantity, 
:clsfrmPartDetails.tblParts.colPartReOrderNo'
.head 8 -  Set sINTOInsertHandle = ''
.head 8 -  !
.head 8 -  Set sSQLUpdateHandle = ' UPDATE Part  
SET 
  Part_Type = :2, 
  Part_Name = :3, 
  Location = :4, 
  Quantity_On_Hand = :5, 
  Re_Order_No = :6
WHERE 
  Part_Id = :1 '
.head 8 -  Set sNAMEUpdateHandle = 'UPDPARTSS'
.head 8 -  Set sBINDUpdateHandle = ':clsfrmPartDetails.tblParts.colPartId, 
:clsfrmPartDetails.tblParts.colPartType, 
:clsfrmPartDetails.tblParts.colPartName, 
:clsfrmPartDetails.tblParts.colPartLocation,
:clsfrmPartDetails.tblParts.colPartQuantity, 
:clsfrmPartDetails.tblParts.colPartReOrderNo'
.head 8 -  Set sINTOUpdateHandle = ''
.head 8 -  !
.head 8 -  Set sSQLDeleteHandle = ' DELETE FROM Part  
WHERE 
  Part_Id = :1 '
.head 8 -  Set sNAMEDeleteHandle = 'DELPARTS'
.head 8 -  Set sBINDDeleteHandle = ':clsfrmPartDetails.tblParts.colPartId'
.head 8 -  !
.head 8 -  Set bAddAllowed = TRUE
.head 8 -  Set bSaveAllowed = TRUE
.head 8 -  Set bDeleteAllowed = TRUE
.head 8 -  Set bUnDeleteAllowed = TRUE
.head 8 -  Set bRepopulateAllowed = TRUE
.head 8 -  Set bClearSelectAllowed = TRUE
.head 8 -  Set bQueryAllowed = TRUE
.head 8 -  Set bReportAllowed = FALSE
.head 8 -  Set bOrderAllowed = TRUE
.head 8 -  Set bZoomTableAllowed = TRUE
.head 8 -  !
.head 8 -  Set hWndRowNewColumn = colPartType
.head 8 -  !
.head 8 -  Set sQueryDialogName = 'dlgQueryPartDetails'
.head 8 -  !
.head 8 -  Set nZoomTblTop = 0.458
.head 8 -  Set nZoomTblHeight = 4.604
.head 7 +  On SAM_Destroy
.head 8 -  Call GetNextPartId( colPartId, SH_cls_Disconnect )
.head 8 -  Call DeletePartVehicleParts( 0, SH_cls_Disconnect )
.head 8 -  Call DeletePartServPartsUsed( 0, SH_cls_Disconnect )
.head 8 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 7 +  On PAM_clsTBL_PUSHFIELDS
.head 8 -  Call PushNumber( hWndParent.clsfrmPartDetails.nPartId )
.head 8 -  Call PushString( hWndParent.clsfrmPartDetails.sPartType )
.head 8 -  Call PushString( hWndParent.clsfrmPartDetails.sPartName )
.head 8 -  Call PushString( hWndParent.clsfrmPartDetails.sPartLocation )
.head 8 -  Call PushString( hWndParent.clsfrmPartDetails.sPartReOrderNo )
.head 8 -  Call PushNumber( hWndParent.clsfrmPartDetails.nPartQuantity )
.head 8 -  Return TRUE
.head 7 +  On PAM_clsTBL_POPFIELDS
.head 8 -  Call PopNumber( hWndParent.clsfrmPartDetails.nPartQuantity, FALSE )
.head 8 -  Call PopString( hWndParent.clsfrmPartDetails.sPartReOrderNo, FALSE )
.head 8 -  Call PopString( hWndParent.clsfrmPartDetails.sPartLocation, FALSE )
.head 8 -  Call PopString( hWndParent.clsfrmPartDetails.sPartName, FALSE )
.head 8 -  Call PopString( hWndParent.clsfrmPartDetails.sPartType, FALSE )
.head 8 -  Call PopNumber( hWndParent.clsfrmPartDetails.nPartId, FALSE )
.head 8 -  Return TRUE
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 68
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 47
.head 6 -  Class ChildKey: 69
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 13597
.head 6 -  Class Child Ref Key: 48
.head 6 -  Class ChildKey: 70
.head 6 -  Class: clsFormChildTable
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 49
.head 6 -  Class ChildKey: 71
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 4 +  Class Variables
.head 5 -  String: sQuickBuildWhere
.head 4 +  Instance Variables
.head 5 -  Number: nPartId
.head 5 -  String: sPartType
.head 5 -  String: sPartName
.head 5 -  String: sPartLocation
.head 5 -  String: sPartReOrderNo
.head 5 -  Number: nPartQuantity
.head 5 -  !
.head 5 -  String: sQQPartTypeOptions
.head 5 -  String: sQQPartType
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  Set bZoomTableAllowed = TRUE
.head 6 -  Set bTreeSystem = FALSE
.head 6 -  Set bPrintFormAllowed = FALSE
.head 6 -  Set hWndChildTable = tblParts
.head 6 -  Set nPopOrQueryOnStartUp = TBL_cls_NothingOnStartUp
.head 5 +  On PAM_clsFRM_POPFIELDS
.head 6 -  Call PopNumber( nPartQuantity, FALSE )
.head 6 -  Call PopString( sPartReOrderNo, FALSE )
.head 6 -  Call PopString( sPartLocation, FALSE )
.head 6 -  Call PopString( sPartName, FALSE )
.head 6 -  Call PopString( sPartType, FALSE )
.head 6 -  Call PopNumber( nPartId, FALSE )
.head 6 -  Call PopWndHdl( hWndActivateButton, TRUE )
.head 6 -  Return TRUE
.head 5 +  On SAM_CreateComplete
.head 6 -  Call SalSendClassMessage( SAM_CreateComplete, wParam, lParam )
.head 6 -  Return SalSendMsg( lbQQPartTypes, PAM_clsLB_POPULATE, 0, 0 )
.head 5 +  On PAM_cls_REFRESHAFTRCHILDCHANGE
.head 6 -  Return FALSE
.head 3 +  Dialog Box Class: clsdlgQPartDetails
.head 4 -  Title: Query Part Details
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  5.0"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 3.459"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 46
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 16
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 2.25"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 17
.head 7 -  Class ChildKey: 7
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClear
.head 7 -  Class Child Ref Key: 19
.head 7 -  Class ChildKey: 37
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 20
.head 7 -  Class ChildKey: 46
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Data Field: dfPartId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 12
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Number
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.938"
.head 8 -  Top: 0.583"
.head 8 -  Width:  0.663"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: #0
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfPartId.sSQLCOLNAME = 'PART_ID'
.head 8 -  Set dfPartId.hWndOperatorField = cmbPartIdOp
.head 8 -  Set dfPartId.hWndNotField = cbNOTPartId
.head 7 +  On SAM_Create
.head 8 +  If NOT IsUserAdmin( SqlUser, FALSE )
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsDF_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  Data Field: dfPartType
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 33
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.938"
.head 8 -  Top: 0.865"
.head 8 -  Width:  0.913"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfPartType.sSQLCOLNAME = 'PART_TYPE'
.head 8 -  Set dfPartType.hWndOperatorField = cmbPartTypeOp
.head 8 -  Set dfPartType.hWndNotField = cbNOTPartType
.head 8 -  Set dfPartType.nDefaultLikePercent = Q_PostLikePercent
.head 5 +  Data Field: dfPartName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 13
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.938"
.head 8 -  Top: 1.146"
.head 8 -  Width:  1.675"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfPartName.sSQLCOLNAME = 'PART_NAME'
.head 8 -  Set dfPartName.hWndOperatorField = cmbPartNameOp
.head 8 -  Set dfPartName.hWndNotField = cbNOTPartName
.head 8 -  Set dfPartName.bCompareUpCase = TRUE
.head 5 +  Data Field: dfPartLocation
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 14
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.938"
.head 8 -  Top: 1.427"
.head 8 -  Width:  1.675"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfPartLocation.sSQLCOLNAME = 'LOCATION'
.head 8 -  Set dfPartLocation.hWndOperatorField = cmbPartLocationOp
.head 8 -  Set dfPartLocation.hWndNotField = cbNOTPartLocation
.head 8 -  Set dfPartLocation.bCompareUpCase = TRUE
.head 5 +  Data Field: dfPartReOrderNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 38
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.938"
.head 8 -  Top: 1.708"
.head 8 -  Width:  1.675"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfPartReOrderNo.sSQLCOLNAME = 'RE_ORDER_NO'
.head 8 -  Set dfPartReOrderNo.hWndOperatorField = cmbPartReOrderNoOp
.head 8 -  Set dfPartReOrderNo.hWndNotField = cbNOTPartReOrderNo
.head 5 +  Data Field: dfPartQuantity
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 42
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Number
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.938"
.head 8 -  Top: 1.99"
.head 8 -  Width:  0.913"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Right
.head 7 -  Format: #0
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfPartQuantity.sSQLCOLNAME = 'QUANTITY_ON_HAND'
.head 8 -  Set dfPartQuantity.hWndOperatorField = cmbPartQuantityOp
.head 8 -  Set dfPartQuantity.hWndNotField = cbNOTPartQuantity
.head 5 +  Combo Box: cmbPartIdOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 20
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.025"
.head 7 -  Top: 0.583"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbPartIdOp.hWndQueryField = dfPartId
.head 8 -  Set cmbPartIdOp.sOperator = ' = '
.head 7 +  On SAM_Create
.head 8 +  If NOT IsUserAdmin( SqlUser, FALSE )
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsCMB_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  Combo Box: cmbPartTypeOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 34
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.025"
.head 7 -  Top: 0.865"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbPartTypeOp.hWndQueryField = dfPartType
.head 8 -  Set cmbPartTypeOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbPartNameOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 21
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.025"
.head 7 -  Top: 1.146"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbPartNameOp.hWndQueryField = dfPartName
.head 8 -  Set cmbPartNameOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbPartLocationOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 22
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.025"
.head 7 -  Top: 1.427"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbPartLocationOp.hWndQueryField = dfPartLocation
.head 8 -  Set cmbPartLocationOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbPartReOrderNoOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 39
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.025"
.head 7 -  Top: 1.708"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbPartReOrderNoOp.hWndQueryField = dfPartReOrderNo
.head 8 -  Set cmbPartReOrderNoOp.sOperator = ' = '
.head 5 +  Combo Box: cmbPartQuantityOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 43
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.025"
.head 7 -  Top: 1.99"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbPartQuantityOp.hWndQueryField = dfPartQuantity
.head 8 -  Set cmbPartQuantityOp.sOperator = ' = '
.head 5 +  Check Box: cbNOTPartId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 23
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.538"
.head 7 -  Top: 0.583"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTPartId.hWndQueryField = dfPartId
.head 7 +  On SAM_Create
.head 8 +  If NOT IsUserAdmin( SqlUser, FALSE )
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsCB_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  Check Box: cbNOTPartType
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 35
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.538"
.head 7 -  Top: 0.865"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTPartType.hWndQueryField = dfPartType
.head 5 +  Check Box: cbNOTPartName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 24
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.538"
.head 7 -  Top: 1.125"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTPartName.hWndQueryField = dfPartName
.head 5 +  Check Box: cbNOTPartLocation
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 25
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.538"
.head 7 -  Top: 1.417"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTPartLocation.hWndQueryField = dfPartLocation
.head 5 +  Check Box: cbNOTPartReOrderNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 40
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.538"
.head 7 -  Top: 1.698"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTPartReOrderNo.hWndQueryField = dfPartReOrderNo
.head 5 +  Check Box: cbNOTPartQuantity
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 44
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.538"
.head 7 -  Top: 1.99"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTPartQuantity.hWndQueryField = dfPartQuantity
.head 5 -  !
.head 5 +  Data Field: lblPartId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 36
.head 6 -  Class: clslblGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 1.125"
.head 8 -  Top: 0.625"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set lblPartId.sLabel = 'Part ID'
.head 7 +  On SAM_Create
.head 8 +  If NOT IsUserAdmin( SqlUser, FALSE )
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsDF_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 -  Background Text: Type
.head 6 -  Resource Id: 29163
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 11
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.463"
.head 7 -  Top: 0.906"
.head 7 -  Width:  0.488"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Name
.head 6 -  Resource Id: 29164
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 30
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.363"
.head 7 -  Top: 1.156"
.head 7 -  Width:  0.588"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Location
.head 6 -  Resource Id: 29166
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 31
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.125"
.head 7 -  Top: 1.469"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: ReOrder #
.head 6 -  Resource Id: 29167
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 41
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.1"
.head 7 -  Top: 1.75"
.head 7 -  Width:  0.85"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Quantity
.head 6 -  Resource Id: 29173
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 45
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.213"
.head 7 -  Top: 2.031"
.head 7 -  Width:  0.775"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 12
.head 6 -  Class ChildKey: 1
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 13
.head 6 -  Class ChildKey: 2
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 14
.head 6 -  Class ChildKey: 3
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 29165
.head 6 -  Class Child Ref Key: 15
.head 6 -  Class ChildKey: 4
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 4 +  Derived From
.head 5 -  Class: clsTblQueryDialog
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bMapEnterToTab = TRUE
.head 6 -  Set bTreeSystem = FALSE
.head 6 -  Set bPrintFormAllowed = FALSE
.head 6 -  Set hWndFirstFocus = dfPartType
.head 5 +  On PAM_clsDLG_POPFIELDS
.head 6 -  Call PopNumber( dfPartQuantity, FALSE )
.head 6 -  Call PopString( dfPartReOrderNo, FALSE )
.head 6 -  Call PopString( dfPartLocation, FALSE )
.head 6 -  Call PopString( dfPartName, FALSE )
.head 6 -  Call PopString( dfPartType, FALSE )
.head 6 -  Call PopNumber( dfPartId, FALSE )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsDLG_PUSHFIELDS
.head 6 -  Call PushNumber( dfPartId )
.head 6 -  Call PushString( dfPartType )
.head 6 -  Call PushString( dfPartName )
.head 6 -  Call PushString( dfPartLocation )
.head 6 -  Call PushString( dfPartReOrderNo )
.head 6 -  Call PushNumber( dfPartQuantity )
.head 6 -  Return TRUE
.head 3 -  !
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton: clspbSIGrowLocations
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  Form Window: frmPartDetails
.head 2 -  Class: clsfrmPartDetails
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbSelect
.head 5 -  Class Child Ref Key: 58
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Class Child Ref Key: 8
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Class Child Ref Key: 12
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbTools
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPartsInventory
.head 5 -  Class Child Ref Key: 67
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPartVehicles
.head 5 -  Class Child Ref Key: 66
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 72
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 73
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 74
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Class Child Ref Key: 76
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 77
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDClose
.head 5 -  Class Child Ref Key: 78
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDRead
.head 5 -  Class Child Ref Key: 79
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 48715
.head 4 -  Class Child Ref Key: 59
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 48716
.head 4 -  Class Child Ref Key: 60
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfQQPartTypesOptions
.head 4 -  Class Child Ref Key: 61
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  List Box: lbQQPartTypes
.head 4 -  Class Child Ref Key: 62
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Multiple selection? Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Horizontal Scroll? Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Child Table: tblParts
.head 4 -  Class Child Ref Key: 28
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colPartId
.head 6 -  Class Child Ref Key: 29
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmPartDetails
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPartType
.head 6 -  Class Child Ref Key: 63
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmPartDetails
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPartName
.head 6 -  Class Child Ref Key: 31
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmPartDetails
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPartLocation
.head 6 -  Class Child Ref Key: 64
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmPartDetails
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPartQuantity
.head 6 -  Class Child Ref Key: 32
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmPartDetails
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPartReOrderNo
.head 6 -  Class Child Ref Key: 57
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmPartDetails
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 4 -  Functions
.head 4 -  Window Variables
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 68
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 69
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 13603
.head 4 -  Class Child Ref Key: 70
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 71
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
.head 1 +  Dialog Box: dlgQueryPartDetails
.head 2 -  Class: clsdlgQPartDetails
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 2.713"
.head 4 -  Top: 1.302"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 5
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 7
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClear
.head 5 -  Class Child Ref Key: 37
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 46
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQPartDetails
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Data Field: dfPartId
.head 4 -  Class Child Ref Key: 12
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfPartType
.head 4 -  Class Child Ref Key: 33
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfPartName
.head 4 -  Class Child Ref Key: 13
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfPartLocation
.head 4 -  Class Child Ref Key: 14
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfPartReOrderNo
.head 4 -  Class Child Ref Key: 38
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfPartQuantity
.head 4 -  Class Child Ref Key: 42
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbPartIdOp
.head 4 -  Class Child Ref Key: 20
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbPartTypeOp
.head 4 -  Class Child Ref Key: 34
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbPartNameOp
.head 4 -  Class Child Ref Key: 21
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbPartLocationOp
.head 4 -  Class Child Ref Key: 22
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbPartReOrderNoOp
.head 4 -  Class Child Ref Key: 39
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbPartQuantityOp
.head 4 -  Class Child Ref Key: 43
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTPartId
.head 4 -  Class Child Ref Key: 23
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTPartType
.head 4 -  Class Child Ref Key: 35
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTPartName
.head 4 -  Class Child Ref Key: 24
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTPartLocation
.head 4 -  Class Child Ref Key: 25
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTPartReOrderNo
.head 4 -  Class Child Ref Key: 40
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTPartQuantity
.head 4 -  Class Child Ref Key: 44
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: lblPartId
.head 4 -  Class Child Ref Key: 36
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 29174
.head 4 -  Class Child Ref Key: 11
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 29175
.head 4 -  Class Child Ref Key: 30
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 29176
.head 4 -  Class Child Ref Key: 31
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 29177
.head 4 -  Class Child Ref Key: 41
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 29178
.head 4 -  Class Child Ref Key: 45
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 3
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 29179
.head 4 -  Class Child Ref Key: 4
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQPartDetails
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
.head 1 +  Dialog Box: dlgPartInventoryRepDetails
.head 2 -  Class: clsDialogGeneral
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Parts Inventory
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 2.338"
.head 4 -  Top: 1.458"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 2.459"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clspbOk
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.075"
.head 6 -  Top: 0.0"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 15
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 8
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 13
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 48712
.head 4 -  Class Child Ref Key: 14
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  !
.head 3 -  Group Box: Report Type
.head 4 -  Resource Id: 48713
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsgbGeneral
.head 4 -  Window Location and Size
.head 5 -  Left: 1.413"
.head 5 -  Top: 0.583"
.head 5 -  Width:  2.1"
.head 5 -  Width Editable? Class Default
.head 5 -  Height: 0.833"
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Radio Button: rbSelected
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: Selected Prior
.head 4 -  Window Location and Size
.head 5 -  Left: 1.75"
.head 5 -  Top: 0.833"
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Radio Button: rbAll
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: All Parts
.head 4 -  Window Location and Size
.head 5 -  Left: 1.75"
.head 5 -  Top: 1.083"
.head 5 -  Width:  1.0"
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  Number: naPartIds[*]
.head 2 +  Window Variables
.head 3 -  String: sSelectionType
.head 2 +  Message Actions
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set bTreeSystem = FALSE
.head 3 +  On PAM_clsPB_OKACTION
.head 4 +  If rbSelected
.head 5 -  Set sSelectionType = 'SELECTED'
.head 4 +  Else
.head 5 -  Set sSelectionType = 'ALL'
.head 4 -  Call SalCreateWindow( frmPrintPartsInventory, hWndForm, naPartIds, sSelectionType )
.head 3 +  On PAM_clsFRM_REPORTCLOSED
.head 4 -  Return SalSendMsg( pbExit, SAM_Click, TRUE, 0 )
.head 1 +  Form Window: frmPrintPartsInventory
.head 2 -  Class: clsFormPrintBasicReport
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Parts Inventory
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: Default
.head 4 -  Top: Default
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 -  Contents
.head 2 -  Contents
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  Number: naPartIds[*]
.head 3 -  ! sSelectionType = 'ALL', 'SELECTED'
.head 3 -  String: sSelectionType
.head 2 +  Window Variables
.head 3 -  String: sTmp
.head 3 -  ! REPORT FIELDS
.head 3 -  Number: nPart_Id
.head 3 -  String: sPart_Type
.head 3 -  String: sPart_Name
.head 3 -  String: sLocation
.head 3 -  String: sRe_Order_No
.head 3 -  Number: nQuantity_On_Hand
.head 2 +  Message Actions
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set sReportFileNameNoPath = 'partrep.qrp'
.head 4 -  Set sPrinter = 'A4Printer'
.head 4 -  Set sReportBind = ':frmPrintPartsInventory.nPart_Id, 
:frmPrintPartsInventory.sPart_Type, 
:frmPrintPartsInventory.sPart_Name, 
:frmPrintPartsInventory.sLocation, 
:frmPrintPartsInventory.sRe_Order_No, 
:frmPrintPartsInventory.nQuantity_On_Hand'
.head 4 -  Set sReportInto = 'nPart_Id, 
 sPart_Type,
 sPart_Name,
 sLocation,
 sRe_Order_No,
 nQuantity_On_Hand'
.head 4 -  Set sReportType = 'PRINT'
.head 4 -  !
.head 4 +  If sSelectionType = 'SELECTED'
.head 5 -  Call MakeNumberList( naPartIds, 0, ', ', '', sTmp )
.head 5 -  Set sReportSql = " SELECT 
  Part_Id, 
  Part_Type,
  Part_Name,
  Location,
  Re_Order_No,
  Quantity_On_Hand
FROM 
  Part  
INTO 
  :frmPrintPartsInventory.nPart_Id, 
  :frmPrintPartsInventory.sPart_Type, 
  :frmPrintPartsInventory.sPart_Name, 
  :frmPrintPartsInventory.sLocation, 
  :frmPrintPartsInventory.sRe_Order_No, 
  :frmPrintPartsInventory.nQuantity_On_Hand 
WHERE Part_Id IN ( " || sTmp || " ) 
ORDER BY Part_Type, Part_Name "
.head 4 +  Else
.head 5 -  Set sReportSql = " SELECT 
  Part_Id, 
  Part_Type,
  Part_Name,
  Location,
  Re_Order_No,
  Quantity_On_Hand
FROM 
  Part  
INTO 
  :frmPrintPartsInventory.nPart_Id, 
  :frmPrintPartsInventory.sPart_Type, 
  :frmPrintPartsInventory.sPart_Name, 
  :frmPrintPartsInventory.sLocation, 
  :frmPrintPartsInventory.sRe_Order_No, 
  :frmPrintPartsInventory.nQuantity_On_Hand 
ORDER BY Part_Type, Part_Name "
