.head 0 +  Application Description: SQLWindows 5.01 Jans Vehicle Services APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 4170705061746800 24006B3A5C63656E 747572615C636C61 73733B6B3A5C6365
0020: 6E747572615C666C 656D61706C730041 7070506174684C65 6E00040024000000
0040: 00557365476C6F62 616C506174680004 0001000000000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D90000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE2FFFFFF000000 0000000000140300 009F010000010000 0000000000010000
0060: 000F4170706C6963 6174696F6E497465 6D02000000075769 6E646F7773186672
0080: 6D5072696E745365 7276696365447565 5265706F7274
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: FRMCTBL.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: TABLE.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: STRINGS.APL
.head 2 -  File Include: METER.APL
.head 2 -  File Include: STACKS.APL
.head 2 -  File Include: VTMETER.APL
.head 2 -  File Include: FLAGS.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: CHECKBOX.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: QUERY.APL
.head 2 -  File Include: CMBFIELD.APL
.head 2 -  File Include: PICK.APL
.head 2 -  File Include: ACTIVATE.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: GROUPBOX.APL
.head 2 -  File Include: VTWIN.APL
.head 2 -  File Include: LISTBOX.APL
.head 2 -  File Include: SRVPUSED.APL
.head 2 -  File Include: DLGCTBL.APL
.head 2 -  File Include: PARTDETS.APL
.head 2 -  File Include: VEHPARTS.APL
.head 2 -  File Include: VEHQUERY.APL
.head 2 -  File Include: VEHDETS.APL
.head 2 -  File Include: FRMDETS.APL
.head 2 -  File Include: MLFIELD.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for VEHSERV.APL
.head 4 -  Number: VEHSERVAplMsgOffSet = SAM_User + 2900
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: VEHSERVAplConstOffSet = 1400
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 3313642788
0000: 9A00000072000000 0000000000000000 020000050000006F 0100001019000000
0020: 011602E0D7020000 0040730000000100 00A3880100192500 0116ED04B8000000
0040: 73D10001000068A1 0100190009011676 0B00006E00730034 010000BA015A0019
0060: 0001A216770B0000 1B730001008D00D3 0100161900041602 E000130000006673
0080: 00010003
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 3 +  Function: DeleteServPartsUsed
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nServiceNo
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Number: nPartUsedId
.head 5 -  Number: nQuantityUsed
.head 5 -  Boolean: bOk
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'DeleteServPartsUsed' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT Part_Id, Quantity_Used 
FROM Service_Parts_Used 
WHERE Service_No = :1 "
.head 7 -  Set sName = 'GTSRVPRTUSED'
.head 7 -  Set sBind = ':nServiceNo'
.head 7 -  Set sInto = ':nPartUsedId, :nQuantityUsed'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 -  Set bOk = TRUE
.head 8 +  While haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 +  If NOT IncrementPartQuantity( nPartUsedId, nQuantityUsed, SH_cls_Execute )
.head 10 -  Set bOk = FALSE
.head 9 +  If NOT DelServPartUsed( nServiceNo, nPartUsedId, SH_cls_Execute )
.head 10 -  Set bOk = FALSE
.head 8 -  Return bOk
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Commit
.head 7 -  Set bOk = TRUE
.head 7 +  If NOT IncrementPartQuantity( 0, 0, SH_cls_Commit )
.head 8 -  Set bOk = FALSE
.head 7 +  If NOT DelServPartUsed( 0, 0, SH_cls_Commit )
.head 8 -  Set bOk = FALSE
.head 7 -  Return bOk
.head 6 +  Case SH_cls_Rollback
.head 7 -  Set bOk = TRUE
.head 7 +  If NOT IncrementPartQuantity( 0, 0, SH_cls_Rollback )
.head 8 -  Set bOk = FALSE
.head 7 +  If NOT DelServPartUsed( 0, 0, SH_cls_Rollback )
.head 8 -  Set bOk = FALSE
.head 7 -  Return bOk
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Set bOk = TRUE
.head 7 +  If NOT IncrementPartQuantity( 0, 0, SH_cls_Disconnect )
.head 8 -  Set bOk = FALSE
.head 7 +  If NOT DelServPartUsed( 0, 0, SH_cls_Disconnect )
.head 8 -  Set bOk = FALSE
.head 7 +  If NOT haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 8 -  Set bOk = FALSE
.head 7 -  Return bOk
.head 3 +  Function: DelServPartUsed
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nServiceNo
.head 5 -  Number: nPartId
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'DelServPartUsed' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " DELETE FROM Service_Parts_Used 
WHERE Service_No = :1 AND Part_Id = :2 "
.head 7 -  Set sName = 'DLSNSRV1PUSD'
.head 7 -  Set sBind = ':nServiceNo, :nPartId'
.head 7 -  Set sInto = ''
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Execute( )
.head 6 +  Case SH_cls_Commit
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Commit( )
.head 6 +  Case SH_cls_Rollback
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Rollback( )
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  Function: IncrementPartQuantity
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nPartId
.head 5 -  Number: nIncQuantity
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'IncrementPartQuantity' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " UPDATE Part 
SET Quantity_On_Hand = Quantity_On_Hand + :2
WHERE Part_Id = :1 "
.head 7 -  Set sName = 'INCPRTQNTY'
.head 7 -  Set sBind = ':nPartId, :nIncQuantity'
.head 7 -  Set sInto = ''
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 +  If nIncQuantity = NUMBER_Null
.head 8 -  Set nIncQuantity = 0
.head 7 -  !
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Execute( )
.head 6 +  Case SH_cls_Commit
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Commit( )
.head 6 +  Case SH_cls_Rollback
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Rollback( )
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1949494777
0000: 961B0000F3100000 0000000000000000 0200003000FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F21003C00 000F63006C737062
0040: 5665685300657276 6963655E00C00000 0300000043040000 0002C01602070000
0060: 0000FE0073000000 01006C0000040010 19000000011602B0 08000000FE470001
0080: 0000831D00000004 05000316020900EC 0000FED900010010 01801D0000010021
00A0: 0010636C6672F86D 5665074000000002 78000000044B0002 162C180000002201
00C0: 73B200000100CD04 0019120001162D00 00F6002268000100 000180804F000000
00E0: 02001C0010466F72 006D426173655461 62806C657C000000 04BD0019A5000116
0100: 090D0030027300D1 0001000066190019 000901160A000000 7B30003401000032
0120: 00580000190001C2 160B0000001E3000 01000D004B000000 9604000216B00C00
0140: 0000306700010003 0180530000008403 00000B636CFF009A 000000050000006F
0160: 1900690116080063 72027300B4010000 195900040002DB09 009E7200016D001D
0180: 00161900041602B6 0A00726700010003 360000000400A500 03160BED0072D900
01A0: 0100603A00000019 006901160C007B72 0034010000018064 1900000400F81763
01C0: 6C805072696E7442 610069635265706F 7274402200000001 00006F1900690116
01E0: 090063F002730034 0100000180661900 0500280C636C7047 65806E6572616C22
0200: 00E8000100002D19 0001166D07003E88 0373000001000600 0180680000000006
0220: 00000009636C0748 656C709AB2000005 00B70400BE020031 4A03730001DA0000
0240: 042C00190001166D 08004A8F00010036 001D00194B000116 09DB004AA3000100
0260: 00CD360019D20001 160AF6004A680001 00004FB200001900 B401160B003D4A00
0280: 011A000001801923 00070000091F4578 698C7422000100DE 0019D200011607C6
02A0: 0062037368000100 0001888004000008 001C000C50696300 457870616E642200
02C0: D1000100005B0400 02DF0098DA037300 018D000180041100 09000012631E6C54
02E0: 6F6700676C654275 74746F886E220000 0100DE00049A0002 0600C600E603736C
0300: 000100018C800400 0A001C000C646647 FE65D1000100005B 040003DF00900404
0320: 730000010D000180 3B0112000B000016 63F26C4765395461 47651F8A0200E115
0340: 0000002D19000116 6F004C8C04730001 0036001900194B00 011607DB004CA300
0360: 010000CD320019D2 00011608F6004C68 000100004BB30019 00B4011609003D4C
0380: 00011A0000640000 A800040000026D0A 004CCF0001260068 0000046B00020BDB
03A0: 004CB3000100C16C 00000004DA00020C F6004C6C00010070 B000000004008602
03C0: 0D0000003D4C0001 1B00740000AC0004 0002610E0000004C CF00010600780000
03E0: 00046B00020FD800 00004CB3000100C9 7C0000041A000210 0000F6004C6C0001
0400: 0080310000040001 84021612000000FF E080010000001F84 00000C0019000101
0420: 16E1130000003F80 01F9000007880000 00194B00011614D8 0000004CA3000100
0440: 00C1A10000001912 000116160000F600 4C6800010000BAB0 0000001900840116
0460: 170000003D4C0001 1A0000D300002C00 1900011661180000 004C8F0001000600
0480: EC000000194B0001 161AD80000004CA3 00010000D1050100 19120001161C0000
04A0: F6004C6800010000 1EB401001900A401 161D00003D4C0001 1A0000370100AD04
04C0: 0003611E0000004C CF0001860001803A 0008000C00001D63 6C0154626C4D616B
04E0: 650053656C656374 656400526F774B65 7941722072617984 0000047B00042300
0500: 01020205FA00004F 800100FE00CD0400 19D200011606C600 9404736800010000
0520: 1DB200001900B401 1607003D940001DA 000036AC00040002 6D080094CF0001C6
0540: 0001801DC8000D00 001001436F6C756D 6E471E656C4000D1 000200005B040002
0560: DA16050018A60473 0001006D00040096 19000116B60600A6 4700010000630180
0580: 5300E40E00001000 4469616C6F674765 9F9A00E800050000 2D190001166D1200
05A0: 2E88077300000100 36001900046B0002 13DB002EB3000100 CD1D0019D2000416
05C0: 14F6002E6C000100 36A300040000A603 1500003D2E0001DB 003A2C0019000116
05E0: 691600002E8F0001 00C60001801D8800 0F00000C63F16362 471B40000200BD00
0600: 19A5000116068D00 9A0773D100010000 6619000400610216 0207007B9A003601
0620: 0001804057000000 1000006811636C54 51C0756572794469 826FB800000006BD
0640: 0004B50003138D00 BE0773D100010000 66040004006D0214 007BBE00B6010008
0660: 5900040002DB1500 9EBE00014D000C00 009619000116B416 0000BE4700010000
0680: 832500000019A500 011617ED00BED100 010000603E000000 190069011618007B
06A0: BE00340100000180 0099000000110000 00CC116351750361 7461466965A06C64
06C0: 7401000CBD000495 000202068D00E807 73D1000100006604 0004006D0207007B
06E0: E800B60100085900 040002DB08009EE8 00016D000C00D604 0002B60900E86700
0700: 01009B100019A500 01160AED00E8D100 0100006029000000 19006901160B007B
0720: E800340100004200 18000004000102DB 0C007F80F2010000 0F46000000961900
0740: 0116B60D00E84700 010000835F000000 04B500020EED00E8 D900010060630000
0760: 0019006901160F00 7BE800B40100007C 5900040002DB1000 9EE800016D008000
0780: 9619000116B41100 00E8470001000063 01809900C4120000 12631F436F6DF062
07A0: 6F4669B70C00B704 00B602060031FA07 730001DA000004AC 000400026D0700FA
07C0: CF00013600080004 6B000208DB00FAB3 000100CD0C0004DA 000209F600FA6C00
07E0: 010010B3001900B4 01160A003DFA0001 DA0000292C001900 01166D0B00FA8F00
0800: 0100360042000463 0001020CFB004F80 0100FE00CD460019 D20001160DF600FA
0820: 68000100005FB300 0400B6020E003DFA 0001DB00632C0019 0001166D0F00FA8F
0840: 00010036007C0004 6B000210DB00FAB3 000100CD800019D2 00011611F600FA68
0860: 00010000018C8099 001300FC00127F43 C0616368657401F6 0C00D60400023607
0880: 000C084473000001 00009B040004B500 0208ED000CD90001 0066080004006D02
08A0: 09007B0C00360100 0C005900040002DB 0A009C0C0800016D 0010009619000116
08C0: B60B000C47000100 009B290019A50001 160CED000CD10001 000066420004006C
08E0: 01020D00FFC98001 0000BF4659001900 01DA160E001E0C00 01006D005F00D604
0900: 0002B60F000C6700 01009B630019A500 011610ED000CD100 010000667C000400
0920: 6D0211007B0C00B6 0100805900190001 DA1612001E0C0001 000D000180320011
0940: 0014000015637E6C 4F0070657261746F 72464E69400000F4 0200009619000116
0960: 3606002A08467300 0100009B190019A5 00011607ED002AD1 0001000018018004
0980: 001500E10013636C 0379434259657300 4E6F466C61672200 D1000100005B0400
09A0: 02DA160600983608 7300010D00018064 0011001600001463 4A6C705365650346
09C0: 726F6D546133657C 00047B00194B0001 16071B005A0873A3 00010000CD190019
09E0: D200011608F6005A 680001000032B300 1900B4011609003D 5A0001DA00004B2C
0A00: 00190001166D0A00 5A8F000100C60001 800408001700000D 636C595365634920
0A20: 6E746F220000017A 0000046B0003051B 00720873B3000100 310180190018F200
0A40: 00110070696E5365 61736F806E596561 722200E800010000 2D190001166D0600
0A60: 9C8C087300010086 0001804600CC0019 00110D7074617274 0050726F6772616D
0A80: D6B00000000700B7 0400BE020031F008 730001DA000004AC 000400026D0700F0
0AA0: CF00013600080004 6B000208DB00F0B3 000100C90C000019 D200011609F600F0
0AC0: 680001000025B300 0400B6030A003DF0 0001DB0029AC0004 00026D0B00F0CF00
0AE0: 0126002D0000194B 0001160CDB00F0A3 0001000001018052 0000001A6200000F
0B00: 6353FE7447300100 0A7B00194B000116 051B00020973A200 00010000CD190019
0B20: D200011606F60002 680001000032B300 0400B40216070039 020900019B003600
0B40: 2C00040002166D08 0002CE0900013600 3A00044B00021609 1A0000020973B300
0B60: 0100CD3E0004D200 02160AE60002096C 00010042B3000400 B402160B00390209
0B80: 0001DB00462C0004 0002166D0C0002CE 09000106004A0000 00044B0002160D9B
0BA0: 000209B3000100C1 4E00000004D20002 160EE60002096C00 0100010C8004001B
0BC0: 000018000C637262 478F616C22D10001 00005B040002DA16 0600986209730001
0BE0: 8D0001803A91001C 0000121B70657276 0850617273557365 C8647C000004DE00
0C00: 04DA000207C600C2 0973680001000004 B3001900B4011608 003DC20001DA0000
0C20: 1D2C001900041669 090000C2CF000136 003600046A000003 0ADB00C2B3000100
0C40: 2101803600001D73 001344176F436869 706C6454615EA300 030000B71900B401
0C60: 16130021700A7300 0001DA0000192C00 190001166D140070 8F00010036003200
0C80: 046B000215DB0070 B300010021018021 00001E6200001063 7019506144657440
0CA0: 61696C735E0000F6 0300D60400023607 009A0A4673000100 009B040019A50001
0CC0: 1608ED009AD10001 0000661D00040069 031609007B9A0036 010001800604001F
0CE0: 000000EE13700373 496E76656E027472 792A000000F40100 00C619000101F608
0D00: 009F8001FC000063 01800400E0200000 00116E6661443F22 00D1000100005B04
0D20: 0002C32300000098 B80A7300018D0001 802191002100000D 6B7056506661735E
0D40: 00F4030000D60400 02360700320C4473 00000100009B0400 19A500011608ED00
0D60: 32D100010000661D 0004006903160900 7B32003601000180 462100220000BE11
0D80: 5013566569636C18 65735E000300BD00 04B50002078D009E 0C73D10001000066
0DA0: 0400190069011608 007B9E00B4010000 1D5900040003DA16 09009E9E00018D00
0DC0: 0180049100230000 12F973667F658D22 000100DE00049A00 022200C600B00C73
0DE0: 6C0001000108809A 0000240000CC0012 7346C86D44657347 4A6561D60000F607
0E00: 0096190001163614 009A104473000001 00009B190019A500 011615ED009AD100
0E20: 0100006432000019 004901161600007B 9A00B40100004B59 00190001DA161700
0E40: 1E9A0001006D0064 009619000116B618 009A470001000083 7D00000019250001
0E60: 161900ED009AD100 0100006096000000 04006502021A007B 9A00360100018064
0E80: 08000025000E0D63 6D62463C726D4000 D1000200005B0400 02DA160600102411
0EA0: 73000001006D0004 00D6040002B60700 2467000100630180 0400E0260000000C
0EC0: F06D6C47658D2200 0100DE0004DA0003 05C6003C11736C00 0100010C80040027
0EE0: 00001C0010546F6F 006C54697057696E 64106F7722000001 00BD0004F500038D
0F00: 00721173D9000100 1801800400280088 00000C6654617343 6122A20000010000
0F20: B70400B603070021 6812730000011B00 018021330029000B 706366436150046F
0F40: 6F66000000037A00 0029830001071602 5101006800004F80 0100FE00CD040004
0F60: D200031609C60074 12736C00010008B3 001900B00116020A 003D7400011A0000
0F80: 01801923002A0000 0C0067774D6F7573 6557606865656C22 00F4010000961900
0FA0: 0116F70046730001 00006301801D00E0 2B0000000D005365 6E64456D61691B40
0FC0: 000200BD0019A500 0116050D00281373 00D1000100006619 0004006902160600
0FE0: 7B28003601000180 40810000002C0000 C00863514F456DC1 C000000006DE0019
1000: D200011605C60076 1373680001000019 B3001900B4011608 003D760001DA0000
1020: 322C00190001166D 0B00768F00010036 004B00194B000116 0EDB0076A3000100
1040: 00CD640019D20001 1611F60076680001 00007D3300040001 B6021400FFE48001
1060: 00001F0180213300 2D000DD77056C765 735EE800030000AD 040002650700006A
1080: 880D730000010036 000400194B000116 08DB006AA3000100 00CD1D0004D20003
10A0: 1609F6006A6C0001 00010C8004002E00 00E0001A636C735F 6549206443686172
10C0: 526547742A0000F4 010000C619000101 F608009F8001FC00 006301800400602F
10E0: 0000001373666651 7579BC5665654622 000100006F04004D 02210000432A0E73
1100: 0000360100
.enddata
.head 3 +  Pushbutton Class: clspbVehService
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\VEHSERV.ICO
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbPickInto
.head 4 +  Class Variables
.head 5 -  String: sTmp
.head 5 -  Number: nTmp
.head 5 -  Window Handle: hWndTmp
.head 4 +  Instance Variables
.head 5 -  ! PUBLIC
.head 5 -  Window Handle: hWndPickIntoTable
.head 5 -  ! PRIVATE
.head 5 -  Number: nVehicleId
.head 5 -  String: sVehicleType
.head 5 -  String: sVehicleMake
.head 5 -  String: sVehicleLocation
.head 5 -  String: sVehicleDriver
.head 4 +  Functions
.head 5 +  Function: SetVehServiceFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nNewVehicleId
.head 7 -  String: sNewVehicleType
.head 7 -  String: sNewVehicleMake
.head 7 -  String: sNewVehicleLocation
.head 7 -  String: sNewVehicleDriver
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set nVehicleId = nNewVehicleId
.head 7 -  Set sVehicleType = sNewVehicleType
.head 7 -  Set sVehicleMake = sNewVehicleMake
.head 7 -  Set sVehicleLocation = sNewVehicleLocation
.head 7 -  Set sVehicleDriver = sNewVehicleDriver
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set hWndPickIntoTable = hWndItem
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set clspbVehService.nActivateWindowType = ACTIVATE_FormWindow
.head 6 -  Set clspbVehService.sActivateDialogName = 'frmVehService'
.head 6 -  Set clspbVehService.hWndTable = hWndPickIntoTable
.head 6 -  Set clspbVehService.hWndFieldLookUp = hWndItem
.head 5 +  On PAM_clsACTIVATE_PUSHFIELDS
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call PushWndHdl( hWndItem )
.head 6 -  Call PushNumber( nVehicleId )
.head 6 -  Call PushString( sVehicleType )
.head 6 -  Call PushString( sVehicleMake )
.head 6 -  Call PushString( sVehicleLocation )
.head 6 -  Call PushString( sVehicleDriver )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsACTIVATE_POPFIELDS
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopNumber( nTmp, TRUE )
.head 6 -  Call PopWndHdl( hWndTmp, TRUE )
.head 6 -  Return TRUE
.head 3 +  Pushbutton Class: clspbPrintVehicleServiceReport
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\LETTERS.BMP
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbGeneral
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  ! PRIVATE
.head 5 -  Number: nVehicleId
.head 5 -  Number: nServiceNo
.head 4 +  Functions
.head 5 +  Function: SetVehServiceRepFields
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Number: nNewVehicleId
.head 7 -  Number: nNewServiceNo
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set nVehicleId = nNewVehicleId
.head 7 -  Set nServiceNo = nNewServiceNo
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set nVehicleId = NUMBER_Null
.head 6 -  Set nServiceNo = NUMBER_Null
.head 6 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  On SAM_Click
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 +  If nVehicleId > 0 AND nServiceNo > 0
.head 7 -  Call SalCreateWindow( frmPrintServiceReport, hWndItem, nVehicleId, nServiceNo )
.head 6 +  Else
.head 7 -  Call SalMessageBox( 'No vehicle service selected!', 'Warning', MB_Ok )
.head 7 -  Return FALSE
.head 3 +  Pushbutton Class: clspbPrintVehicleServiceDueReport
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\LETTERS.BMP
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbGeneral
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  ! PRIVATE
.head 5 -  ! Number: nVehicleId
.head 5 -  ! Number: nServiceNo
.head 4 +  Functions
.head 5 +  ! Function: SetVehServiceRepFields
.head 6 -  Description: 
.head 6 -  Returns 
.head 6 +  Parameters 
.head 7 -  Number: nNewVehicleId
.head 7 -  Number: nNewServiceNo
.head 6 -  Static Variables 
.head 6 -  Local variables 
.head 6 +  Actions 
.head 7 -  Set nVehicleId = nNewVehicleId
.head 7 -  Set nServiceNo = nNewServiceNo
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  ! Set nVehicleId = NUMBER_Null
.head 6 -  ! Set nServiceNo = NUMBER_Null
.head 6 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  On SAM_Click
.head 6 -  ! Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call SalCreateWindow( frmPrintServiceDueReport, hWndItem )
.head 6 -  ! Call SalCreateWindow( frmPrintServiceDueReport, hWndItem, nVehicleId, nServiceNo )
.head 6 -  ! If nVehicleId > 0 AND nServiceNo > 0
.head 6 +  ! Else
.head 7 -  Call SalMessageBox( 'No vehicle service selected!', 'Warning', MB_Ok )
.head 7 -  Return FALSE
.head 3 +  Form Window Class: clsfrmVehService
.head 4 -  Title: Fleming's Nurseries Vehicle Services
.head 4 -  Icon File:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Automatically Created at Runtime? Class Default
.head 5 -  Initial State: Class Default
.head 5 -  Maximizable? Class Default
.head 5 -  Minimizable? Class Default
.head 5 -  Allow Child Docking? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  System Menu? Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 5.542"
.head 6 -  Height Editable? Class Default
.head 5 -  Form Size
.head 6 -  Width:  Class Default
.head 6 -  Height: Class Default
.head 6 -  Number of Pages: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Next Class Child Key: 100
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsFormChildTable
.head 4 +  Menu
.head 5 -  Named Menu: clsFormFileMenu
.head 6 -  Resource Id: 58696
.head 5 +  Popup Menu: &Table Actions
.head 6 -  Resource Id: 58693
.head 6 -  Enabled when:
.head 6 -  Status Text:
.head 6 -  Menu Item Name:
.head 6 +  Menu Item: &Clear Rows
.head 7 -  Resource Id: 58695
.head 7 -  Keyboard Accelerator: F3
.head 7 -  Status Text: Un select all selected rows and delete newly inserted ones.
.head 7 +  Menu Settings
.head 8 -  Enabled when: bClearSelectAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_ClearRow, 0 )
.head 7 -  Menu Item Name:
.head 6 -  Menu Separator
.head 6 +  Menu Item: &Add Row
.head 7 -  Resource Id: 58682
.head 7 -  Keyboard Accelerator: F6
.head 7 -  Status Text: Insert a New row into table at current position
.head 7 +  Menu Settings
.head 8 -  Enabled when: bAddAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_AddRow, 0 )
.head 7 -  Menu Item Name:
.head 6 +  Menu Item: &Save Rows
.head 7 -  Resource Id: 58694
.head 7 -  Keyboard Accelerator: F5
.head 7 -  Status Text: Save any New, Modified Or Mark Deleted Rows.
.head 7 +  Menu Settings
.head 8 -  Enabled when: bSaveAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_SaveRow, 0 )
.head 7 -  Menu Item Name:
.head 6 -  Menu Separator
.head 6 +  Menu Item: &Delete Rows
.head 7 -  Resource Id: 58691
.head 7 -  Keyboard Accelerator: F4
.head 7 -  Status Text: Mark selected rows as deleted.
.head 7 +  Menu Settings
.head 8 -  Enabled when: bDeleteAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_DeleteRow, 0 )
.head 7 -  Menu Item Name:
.head 6 +  Menu Item: &UnDelete Rows
.head 7 -  Resource Id: 58685
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text: Un Mark selected rows as deleted. 
.head 7 +  Menu Settings
.head 8 -  Enabled when: bUnDeleteAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_UnDeleteRow, 0 )
.head 7 -  Menu Item Name:
.head 6 -  Menu Separator
.head 6 +  Menu Item: &Query
.head 7 -  Resource Id: 58684
.head 7 -  Keyboard Accelerator: F7
.head 7 -  Status Text: Search for specific information.
.head 7 +  Menu Settings
.head 8 -  Enabled when: bQueryAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_Query, 0 )
.head 7 -  Menu Item Name:
.head 6 -  Menu Separator
.head 6 +  Menu Item: S&ort Table
.head 7 -  Resource Id: 58683
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text: Change the order of the table.
.head 7 +  Menu Settings
.head 8 -  Enabled when: bOrderAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_OrderTable, 0 )
.head 7 -  Menu Item Name:
.head 6 +  Menu Item: Re&Pop Table
.head 7 -  Resource Id: 58681
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text: Refresh table from database.
.head 7 +  Menu Settings
.head 8 -  Enabled when: bRepopulateAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_RePopTable, 0 )
.head 7 -  Menu Item Name:
.head 6 +  Menu Item: Table &Report
.head 7 -  Resource Id: 58692
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text: Produce report of table ( either selected items only OR whole table )
.head 7 +  Menu Settings
.head 8 -  Enabled when: bReportAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_TableReport, 0 )
.head 7 -  Menu Item Name:
.head 6 -  Menu Separator
.head 6 +  Menu Item: &Move Row Up One
.head 7 -  Resource Id: 58690
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text: Swap above row for current row. ( Only visual, no changes have been performed )
.head 7 +  Menu Settings
.head 8 -  Enabled when: bMoveRowUpOneAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_MoveUpOne, 0 )
.head 7 -  Menu Item Name:
.head 6 +  Menu Item: &Move Row Down One
.head 7 -  Resource Id: 58689
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text: Swap bellow row for current row. ( Only visual, no changes have been performed )
.head 7 +  Menu Settings
.head 8 -  Enabled when: bMoveRowDownOneAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_MoveDownOne, 0 )
.head 7 -  Menu Item Name:
.head 6 -  Menu Separator
.head 6 +  Menu Item: &Zoom Table
.head 7 -  Resource Id: 58688
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text: Toggles the size of the table.
.head 7 +  Menu Settings
.head 8 -  Enabled when: bZoomTableAllowed
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( hWndForm, PAM_clsTBL_USERACTIONS, TBL_cls_ZoomTable, 0 )
.head 7 -  Menu Item Name:
.head 5 +  Popup Menu: &Report
.head 6 -  Resource Id: 58687
.head 6 -  Enabled when:
.head 6 -  Status Text:
.head 6 -  Menu Item Name:
.head 6 +  Menu Item: &Service Report
.head 7 -  Resource Id: 58686
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text:
.head 7 +  Menu Settings
.head 8 -  Enabled when:
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( pbPrintServReport, SAM_Click, 0, 0 )
.head 7 -  Menu Item Name:
.head 6 +  Menu Item: &Vehicle Id Charts
.head 7 -  Resource Id: 58680
.head 7 -  Keyboard Accelerator: (none)
.head 7 -  Status Text:
.head 7 +  Menu Settings
.head 8 -  Enabled when:
.head 8 -  Checked when:
.head 7 +  Menu Actions
.head 8 -  Call SalSendValidateMsg(  )
.head 8 -  Call SalSendMsg( pbVehIdChartReport, SAM_Click, 0, 0 )
.head 7 -  Menu Item Name:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: 0.594"
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbAddRows
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 8
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbSaveRows
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 9
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 8
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbDeleteRows
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 11
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRePopulate
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 12
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 4.6"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbTools
.head 7 -  Class Child Ref Key: 23
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 5.2"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintServReport
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 85
.head 7 -  Class: clspbPrintVehicleServiceReport
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 0.6"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? No
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbPrintServReport.SetVehServiceRepFields( nVehicleId, tblVehService.colServiceNo )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbServPartsUsed
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 84
.head 7 -  Class: clspbServPartsUsed
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 5.8"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbServPartsUsed.hWndPickIntoTable = tblVehService
.head 8 +  On PAM_clsPB_CLICK
.head 9 -  Call TableAnyRows( tblVehService, 0, 0, nTmpRow )
.head 9 +  If nTmpRow > 0
.head 10 +  If SalTblQueryRowFlags( tblVehService, SalTblQueryContext( tblVehService ), ROW_New )
.head 11 -  Call SalMessageBox( 'Please save your service first!', 'Warning', MB_Ok )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return SalSendClassMessage( PAM_clsPB_CLICK, wParam, lParam )
.head 9 +  Else
.head 10 -  Call SalMessageBox( 'Please create a service first!', 'Warning', MB_Ok )
.head 10 -  Return FALSE
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbServPartsUsed.SetServPartsUsedFields( nVehicleId, dfVehicleType, dfVehicleMake, 
dfVehicleLocation, dfVehicleDriver, tblVehService.colServiceNo, tblVehService.colServiceDoneDate )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbVehIdChartReport
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 86
.head 7 -  Class: clspbVehiclesIdChartReport
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 1.2"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? No
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbVehIdChartReport.SetOneVehicleChartFields( nVehicleId )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbFirstRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 73
.head 7 -  Class: clspbFirstRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.4"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrevRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 74
.head 7 -  Class: clspbPrevRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 7.0"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbNextRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 75
.head 7 -  Class: clspbNextRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 7.6"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbLastRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 76
.head 7 -  Class: clspbLastRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 8.2"
.head 8 -  Top: 0.04"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 42
.head 7 -  Class ChildKey: 93
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 43
.head 7 -  Class ChildKey: 94
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 44
.head 7 -  Class ChildKey: 95
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClearRows
.head 7 -  Class Child Ref Key: 52
.head 7 -  Class ChildKey: 97
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 50
.head 7 -  Class ChildKey: 98
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDClose
.head 7 -  Class Child Ref Key: 54
.head 7 -  Class ChildKey: 99
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDRead
.head 7 -  Class Child Ref Key: 55
.head 7 -  Class ChildKey: 100
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 -  Background Text: Type
.head 6 -  Resource Id: 24925
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 67
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.95"
.head 7 -  Top: 0.115"
.head 7 -  Width:  0.463"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Blue
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Make
.head 6 -  Resource Id: 24926
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 68
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.913"
.head 7 -  Top: 0.365"
.head 7 -  Width:  0.5"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Blue
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Location
.head 6 -  Resource Id: 24924
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 69
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.588"
.head 7 -  Top: 0.604"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Blue
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Driver
.head 6 -  Resource Id: 59170
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 87
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.588"
.head 7 -  Top: 0.854"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Blue
.head 6 -  Background Color: Class Default
.head 5 +  Data Field: dfVehicleType
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 70
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.475"
.head 8 -  Top: 0.073"
.head 8 -  Width:  3.538"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfVehicleMake
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 71
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.475"
.head 8 -  Top: 0.323"
.head 8 -  Width:  3.538"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfVehicleLocation
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 72
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.475"
.head 8 -  Top: 0.563"
.head 8 -  Width:  3.538"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfVehicleDriver
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 88
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.475"
.head 8 -  Top: 0.813"
.head 8 -  Width:  3.538"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  !
.head 5 +  Child Table: tblVehService
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 28
.head 6 -  Class: clsTableGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.038"
.head 8 -  Top: 1.146"
.head 8 -  Width:  9.725"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 3.438"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colServiceNo
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 29
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Service No
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.025"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Call GetNextServiceNo( colServiceNo, SH_cls_Execute )
.head 10 +  If colServiceNo > 0
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Call ErrorMessage( 'An error has occured in allocating the next Service No. Please try and save again.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 9 +  On PAM_clsTBL_ROWDELETED
.head 10 +  If DeleteServPartsUsed( colServiceNo, SH_cls_Execute )
.head 11 -  Call DeleteServPartsUsed( 0, SH_cls_Commit )
.head 7 +  Column: colServiceDueDate
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 79
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Due Date
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Date/Time
.head 8 -  Justify: Center
.head 8 -  Width:  1.163"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: dd-MMM-yyyy
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colServiceDueDate.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_ROWNEWINIT
.head 10 -  Set colServiceDueDate = SalDateCurrent(  )
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 7 +  Column: colServiceDoneDate
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 80
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Serviced Date
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Date/Time
.head 8 -  Justify: Center
.head 8 -  Width:  1.288"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: dd-MMM-yyyy
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colServiceDoneDate.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_ROWNEWINIT
.head 10 -  Set colServiceDoneDate = SalDateCurrent(  )
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 7 +  Column: colServiceDueDistance
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 31
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Due Distance
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.988"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colServiceDueDistance.bOrderBy = TRUE
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 7 +  Column: colServiceDoneDistance
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 78
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Serviced Distance
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.788"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colServiceDoneDistance.bOrderBy = TRUE
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 7 +  Column: colMechanic
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 63
.head 8 -  Class: clsColDropListGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Mechanic
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.225"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colMechanic.sSqlPopStatement = " SELECT DISTINCT Service_Mechanic FROM Vehicle_Service "
.head 10 -  Set colMechanic.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_ROWNEWINIT
.head 10 -  Set colMechanic = SqlUser
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Set colMechanic = SqlUser
.head 10 -  Return TRUE
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 7 +  Column: colGeneralConditions
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 81
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: General Conditions
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: 10000
.head 8 -  Data Type: Long String
.head 8 -  Justify: Class Default
.head 8 -  Width:  3.238"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Popup Edit
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 7 +  Column: colFurtherRequirements
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 82
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Further Requirements
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: 10000
.head 8 -  Data Type: Long String
.head 8 -  Justify: Class Default
.head 8 -  Width:  3.375"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Popup Edit
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 7 +  Column: colDoneAboveService
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 83
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Done above Service
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: 10000
.head 8 -  Data Type: Long String
.head 8 -  Justify: Class Default
.head 8 -  Width:  4.563"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Popup Edit
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On SAM_SetFocus
.head 10 -  Call SalTblSetFocusCell( hWndForm, lParam, hWndItem, 0, 0 )
.head 10 -  Return SalSendClassMessage( SAM_SetFocus, wParam, lParam )
.head 6 +  Functions
.head 7 +  Function: GetNextServiceNo
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  Receive Number: nNextServiceNo
.head 9 -  Number: nActionType
.head 8 +  Static Variables
.head 9 -  ! hcSqlHandle: fcOurHandle
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nInd
.head 9 -  Number: nGotServiceNo
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetNextServiceNo' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " SELECT Max( Service_No ) + 1
FROM Vehicle_Service "
.head 11 -  Set sName = 'NEXTSERVNO'
.head 11 -  Set sBind = ''
.head 11 -  Set sInto = ':nGotServiceNo'
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Set nNextServiceNo = NUMBER_Null
.head 11 -  Set nGotServiceNo = NUMBER_Null
.head 11 -  !
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 +  If NOT nGotServiceNo > 0
.head 14 -  Set nGotServiceNo = 1
.head 13 -  Set nNextServiceNo = nGotServiceNo
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 6 -  Window Variables
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set sSQLPopHandle = ' SELECT 
  Service_No, 
  Service_Due_Date, 
  Service_Done_Date, 
  Service_Due_Dist, 
  Service_Done_Dist, 
  Service_Mechanic, 
  General_Conditions, 
  Further_Require, 
  Done_Above_Service 
FROM 
  Vehicle_Service 
WHERE 
  Vehicle_Id = :1 
ORDER BY 
  Service_Due_Date '
.head 8 -  Set sNAMEPopHandle = 'POPVEHSERV'
.head 8 -  Set sBINDPopHandle = ':hWndParent.clsfrmVehService.nVehicleId'
.head 8 -  Set sINTOPopHandle = ':clsfrmVehService.tblVehService.colServiceNo, 
:clsfrmVehService.tblVehService.colServiceDueDate, 
:clsfrmVehService.tblVehService.colServiceDoneDate, 
:clsfrmVehService.tblVehService.colServiceDueDistance,
:clsfrmVehService.tblVehService.colServiceDoneDistance, 
:clsfrmVehService.tblVehService.colMechanic, 
:clsfrmVehService.tblVehService.colGeneralConditions, 
:clsfrmVehService.tblVehService.colFurtherRequirements, 
:clsfrmVehService.tblVehService.colDoneAboveService'
.head 8 -  !
.head 8 -  Set sSQLRefreshHandle = ' SELECT 
  Service_No, 
  Service_Due_Date, 
  Service_Done_Date, 
  Service_Due_Dist, 
  Service_Done_Dist, 
  Service_Mechanic, 
  General_Conditions, 
  Further_Require, 
  Done_Above_Service 
FROM 
  Vehicle_Service 
WHERE 
  Service_No = :1 '
.head 8 -  Set sNAMERefreshHandle = 'REFVEHSERV'
.head 8 -  Set sBINDRefreshHandle = ':clsfrmVehService.tblVehService.colServiceNo'
.head 8 -  Set sINTORefreshHandle = ':clsfrmVehService.tblVehService.colServiceNo, 
:clsfrmVehService.tblVehService.colServiceDueDate, 
:clsfrmVehService.tblVehService.colServiceDoneDate, 
:clsfrmVehService.tblVehService.colServiceDueDistance,
:clsfrmVehService.tblVehService.colServiceDoneDistance, 
:clsfrmVehService.tblVehService.colMechanic, 
:clsfrmVehService.tblVehService.colGeneralConditions, 
:clsfrmVehService.tblVehService.colFurtherRequirements, 
:clsfrmVehService.tblVehService.colDoneAboveService'
.head 8 -  !
.head 8 -  Set sSQLInsertHandle = 'INSERT INTO Vehicle_Service  
( Service_No, 
  Vehicle_Id, 
  Service_Due_Date, 
  Service_Done_Date, 
  Service_Due_Dist, 
  Service_Done_Dist, 
  Service_Mechanic, 
  General_Conditions, 
  Further_Require, 
  Done_Above_Service   ) 
VALUES ( :1, :2, :3, :4, :5, :6, :7, :8, :9, :10 ) '
.head 8 -  Set sNAMEInsertHandle = 'INSVEHSERV'
.head 8 -  Set sBINDInsertHandle = ':clsfrmVehService.tblVehService.colServiceNo, 
:hWndParent.clsfrmVehService.nVehicleId, 
:clsfrmVehService.tblVehService.colServiceDueDate, 
:clsfrmVehService.tblVehService.colServiceDoneDate, 
:clsfrmVehService.tblVehService.colServiceDueDistance,
:clsfrmVehService.tblVehService.colServiceDoneDistance, 
:clsfrmVehService.tblVehService.colMechanic, 
:clsfrmVehService.tblVehService.colGeneralConditions, 
:clsfrmVehService.tblVehService.colFurtherRequirements, 
:clsfrmVehService.tblVehService.colDoneAboveService'
.head 8 -  Set sINTOInsertHandle = ''
.head 8 -  !
.head 8 -  Set sSQLUpdateHandle = ' UPDATE Vehicle_Service  
SET 
  Service_Due_Date = :2, 
  Service_Done_Date = :3, 
  Service_Due_Dist = :4, 
  Service_Done_Dist = :5, 
  Service_Mechanic = :6, 
  General_Conditions = :7, 
  Further_Require = :8, 
  Done_Above_Service = :9 
WHERE 
  Service_No = :1 '
.head 8 -  Set sNAMEUpdateHandle = 'UPDVEHSERV'
.head 8 -  Set sBINDUpdateHandle = ':clsfrmVehService.tblVehService.colServiceNo, 
:clsfrmVehService.tblVehService.colServiceDueDate, 
:clsfrmVehService.tblVehService.colServiceDoneDate, 
:clsfrmVehService.tblVehService.colServiceDueDistance,
:clsfrmVehService.tblVehService.colServiceDoneDistance, 
:clsfrmVehService.tblVehService.colMechanic, 
:clsfrmVehService.tblVehService.colGeneralConditions, 
:clsfrmVehService.tblVehService.colFurtherRequirements, 
:clsfrmVehService.tblVehService.colDoneAboveService'
.head 8 -  Set sINTOUpdateHandle = ''
.head 8 -  !
.head 8 -  Set sSQLDeleteHandle = ' DELETE FROM Vehicle_Service 
WHERE 
  Service_No = :1 '
.head 8 -  Set sNAMEDeleteHandle = 'DELVEHSERV'
.head 8 -  Set sBINDDeleteHandle = ':clsfrmVehService.tblVehService.colServiceNo'
.head 8 -  !
.head 8 -  Set bAddAllowed = TRUE
.head 8 -  Set bSaveAllowed = TRUE
.head 8 -  Set bDeleteAllowed = TRUE
.head 8 -  Set bUnDeleteAllowed = TRUE
.head 8 -  Set bRepopulateAllowed = TRUE
.head 8 -  Set bClearSelectAllowed = TRUE
.head 8 -  Set bQueryAllowed = FALSE
.head 8 -  Set bReportAllowed = FALSE
.head 8 -  Set bOrderAllowed = TRUE
.head 8 -  Set bZoomTableAllowed = FALSE
.head 8 -  !
.head 8 -  Set hWndRowNewColumn = colServiceDueDate
.head 8 -  !
.head 8 -  Set sQueryDialogName = ''
.head 7 +  On SAM_Destroy
.head 8 -  Call GetNextServiceNo( colServiceNo, SH_cls_Disconnect )
.head 8 -  Call DeleteServPartsUsed( 0, SH_cls_Disconnect )
.head 8 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 89
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 47
.head 6 -  Class ChildKey: 90
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 13627
.head 6 -  Class Child Ref Key: 48
.head 6 -  Class ChildKey: 91
.head 6 -  Class: clsFormChildTable
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 49
.head 6 -  Class ChildKey: 92
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 4 +  Class Variables
.head 5 -  String: sQuickBuildWhere
.head 5 -  Number: nTmpRow
.head 4 +  Instance Variables
.head 5 -  Number: nVehicleId
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bQueryAllowed = FALSE
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  Set bZoomTableAllowed = TRUE
.head 6 -  Set bTreeSystem = FALSE
.head 6 -  Set bPrintFormAllowed = FALSE
.head 6 -  Set hWndChildTable = tblVehService
.head 6 -  Set nPopOrQueryOnStartUp = TBL_cls_PopulateOnStartUp
.head 5 +  On PAM_clsFRM_POPFIELDS
.head 6 -  Call PopWndHdl( hWndActivateButton, TRUE )
.head 6 -  Call PopString( dfVehicleDriver, TRUE )
.head 6 -  Call PopString( dfVehicleLocation, TRUE )
.head 6 -  Call PopString( dfVehicleMake, TRUE )
.head 6 -  Call PopString( dfVehicleType, TRUE )
.head 6 -  Call PopNumber( nVehicleId, TRUE )
.head 6 -  Return TRUE
.head 5 +  On PAM_cls_REFRESHAFTRCHILDCHANGE
.head 6 -  Return FALSE
.head 3 -  !
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton: clspbSIGrowLocations
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  Form Window: frmVehService
.head 2 -  Class: clsfrmVehService
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Class Child Ref Key: 8
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Class Child Ref Key: 12
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbTools
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintServReport
.head 5 -  Class Child Ref Key: 85
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbServPartsUsed
.head 5 -  Class Child Ref Key: 84
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbVehIdChartReport
.head 5 -  Class Child Ref Key: 86
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbFirstRec
.head 5 -  Class Child Ref Key: 73
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrevRec
.head 5 -  Class Child Ref Key: 74
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbNextRec
.head 5 -  Class Child Ref Key: 75
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbLastRec
.head 5 -  Class Child Ref Key: 76
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 93
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 94
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 95
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Class Child Ref Key: 97
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 98
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDClose
.head 5 -  Class Child Ref Key: 99
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDRead
.head 5 -  Class Child Ref Key: 100
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmVehService
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 59172
.head 4 -  Class Child Ref Key: 67
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 59173
.head 4 -  Class Child Ref Key: 68
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 59174
.head 4 -  Class Child Ref Key: 69
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 59175
.head 4 -  Class Child Ref Key: 87
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfVehicleType
.head 4 -  Class Child Ref Key: 70
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfVehicleMake
.head 4 -  Class Child Ref Key: 71
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfVehicleLocation
.head 4 -  Class Child Ref Key: 72
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfVehicleDriver
.head 4 -  Class Child Ref Key: 88
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Child Table: tblVehService
.head 4 -  Class Child Ref Key: 28
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colServiceNo
.head 6 -  Class Child Ref Key: 29
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colServiceDueDate
.head 6 -  Class Child Ref Key: 79
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colServiceDoneDate
.head 6 -  Class Child Ref Key: 80
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colServiceDueDistance
.head 6 -  Class Child Ref Key: 31
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colServiceDoneDistance
.head 6 -  Class Child Ref Key: 78
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colMechanic
.head 6 -  Class Child Ref Key: 63
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colGeneralConditions
.head 6 -  Class Child Ref Key: 81
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colFurtherRequirements
.head 6 -  Class Child Ref Key: 82
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colDoneAboveService
.head 6 -  Class Child Ref Key: 83
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmVehService
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 4 -  Functions
.head 4 -  Window Variables
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 89
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 90
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 13630
.head 4 -  Class Child Ref Key: 91
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 92
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmVehService
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
.head 1 +  Form Window: frmPrintServiceReport
.head 2 -  Class: clsFormPrintBasicReport
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Service Report
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: Default
.head 4 -  Top: Default
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 -  Contents
.head 2 -  Contents
.head 2 +  Functions
.head 3 +  Function: GetServiceVehicleDetails
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nVehicleId
.head 5 -  Receive String: sVehicleType
.head 5 -  Receive String: sLocation
.head 5 -  Receive String: sMake
.head 5 -  Receive String: sModel
.head 5 -  Receive String: sRegNo
.head 5 -  Receive String: sDriver
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  String: sGotVehicleType
.head 5 -  String: sGotLocation
.head 5 -  String: sGotMake
.head 5 -  String: sGotModel
.head 5 -  String: sGotRegNo
.head 5 -  String: sGotDriver
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetServiceVehicleDetails' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
  Vehicle_Type, 
  Location, 
  Make, 
  Model, 
  Reg_No, 
  Driver 
FROM 
  Vehicle 
WHERE 
  Vehicle_Id = :1 "
.head 7 -  Set sName = 'SRVRPVHDETS'
.head 7 -  Set sBind = ':nVehicleId'
.head 7 -  Set sInto = ':sGotVehicleType, :sGotLocation, :sGotMake, :sGotModel, :sGotRegNo, :sGotDriver'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sVehicleType = ''
.head 7 -  Set sLocation = ''
.head 7 -  Set sMake = ''
.head 7 -  Set sModel = ''
.head 7 -  Set sRegNo = ''
.head 7 -  Set sDriver = ''
.head 7 -  !
.head 7 -  Set sGotVehicleType = ''
.head 7 -  Set sGotLocation = ''
.head 7 -  Set sGotMake = ''
.head 7 -  Set sGotModel = ''
.head 7 -  Set sGotRegNo = ''
.head 7 -  Set sGotDriver = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set sVehicleType = sGotVehicleType
.head 9 -  Set sLocation = sGotLocation
.head 9 -  Set sMake = sGotMake
.head 9 -  Set sModel = sGotModel
.head 9 -  Set sRegNo = sGotRegNo
.head 9 -  Set sDriver = sGotDriver
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  Function: GetThisServiceDetails
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nVehicleId
.head 5 -  Number: nServiceNo
.head 5 -  Receive Date/Time: dtServiceDoneDate
.head 5 -  Receive String: sServiceDueDistance
.head 5 -  Receive String: sServiceDoneDistance
.head 5 -  Receive String: sServiceMechanic
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Date/Time: dtGotServiceDoneDate
.head 5 -  String: sGotServiceDueDistance
.head 5 -  String: sGotServiceDoneDistance
.head 5 -  String: sGotServiceMechanic
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetThisServiceDetails' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
  Service_Done_Date, 
  Service_Due_Dist, 
  Service_Done_Dist,
  Service_Mechanic  
FROM 
  Vehicle_Service 
WHERE 
  Vehicle_Id = :1 AND 
  Service_No = :2 "
.head 7 -  Set sName = 'THISSRVDTS'
.head 7 -  Set sBind = ':nVehicleId, :nServiceNo'
.head 7 -  Set sInto = ':dtGotServiceDoneDate, :sGotServiceDueDistance, :sGotServiceDoneDistance, :sGotServiceMechanic'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set dtServiceDoneDate = DATETIME_Null
.head 7 -  Set sServiceDueDistance = ''
.head 7 -  Set sServiceMechanic = ''
.head 7 -  Set dtGotServiceDoneDate = DATETIME_Null
.head 7 -  Set sGotServiceDueDistance = ''
.head 7 -  Set sGotServiceDoneDistance = ''
.head 7 -  Set sGotServiceMechanic = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set dtServiceDoneDate = dtGotServiceDoneDate
.head 9 -  Set sServiceDueDistance = sGotServiceDueDistance
.head 9 -  Set sServiceDoneDistance = sGotServiceDoneDistance
.head 9 -  Set sServiceMechanic = sGotServiceMechanic
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  Function: GetLastServiceNextTimeDetails
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nVehicleId
.head 5 -  Number: nServiceNo
.head 5 -  Receive Long String: sFurtherRequire
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Long String: sGotFurtherRequire
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetLastServiceNextTimeDetails' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
    Further_Require 
  FROM 
    Vehicle_Service 
  WHERE 
    Vehicle_Id = :1 AND 
    Service_No < :2
  ORDER BY 
    Service_Done_Date DESC "
.head 7 -  Set sName = 'LSTSRVNXTDETS'
.head 7 -  Set sBind = ':nVehicleId, :nServiceNo'
.head 7 -  Set sInto = ':sGotFurtherRequire'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sFurtherRequire = ''
.head 7 -  Set sGotFurtherRequire = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set sFurtherRequire = sGotFurtherRequire
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 2 +  Window Parameters
.head 3 -  Number: nVehicleId
.head 3 -  Number: nServiceNo
.head 2 +  Window Variables
.head 3 -  ! REPORT FIELDS
.head 3 -  String: sVehicle_Type
.head 3 -  String: sLocation
.head 3 -  String: sMake
.head 3 -  String: sModel
.head 3 -  String: sReg_No
.head 3 -  String: sDriver
.head 3 -  Date/Time: dtServiceDoneDate
.head 3 -  String: sServiceDueDistance
.head 3 -  String: sServiceDoneDistance
.head 3 -  String: sServiceMechanic
.head 3 -  Long String: sFurther_Require
.head 3 -  String: sLeft_Condition
.head 3 -  String: sRight_Condition
.head 2 +  Message Actions
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set sReportFileNameNoPath = 'servrep2.qrp'
.head 4 -  Set sPrinter = 'A4Printer'
.head 4 -  Set sReportBind = ':frmPrintServiceReport.nVehicleId, 
:frmPrintServiceReport.sVehicle_Type,
:frmPrintServiceReport.sLocation,
:frmPrintServiceReport.sMake,
:frmPrintServiceReport.sModel,
:frmPrintServiceReport.sReg_No, 
:frmPrintServiceReport.sDriver, 
:frmPrintServiceReport.dtServiceDoneDate, 
:frmPrintServiceReport.sServiceDueDistance, 
:frmPrintServiceReport.sServiceDoneDistance, 
:frmPrintServiceReport.sServiceMechanic, 
:frmPrintServiceReport.sFurther_Require,
:frmPrintServiceReport.sLeft_Condition,
:frmPrintServiceReport.sRight_Condition'
.head 4 -  Set sReportInto = 'nVehicle_Id, 
sVehicle_Type,
sLocation,
sMake,
sModel,
sReg_No, 
sDriver, 
dtServiceDoneDate, 
sServiceDueDistance, 
sServiceDoneDistance,
sServiceMechanic, 
sGeneral_Conditions,
sLeft_Condition,
sRight_Condition'
.head 4 -  Set sReportType = 'PRINT'
.head 4 -  !
.head 4 -  Set sReportSql = " SELECT 
  Left_Condition, 
  Right_Condition 
FROM 
  Vehicle_Check_List 
INTO 
  :frmPrintServiceReport.sLeft_Condition,
  :frmPrintServiceReport.sRight_Condition
WHERE 
  Vehicle_Type = :frmPrintServiceReport.sVehicle_Type
ORDER BY 
  Seq_No"
.head 3 +  On SAM_ReportStart
.head 4 -  Set sVehicle_Type = ''
.head 4 -  Set sLocation = ''
.head 4 -  Set sMake = ''
.head 4 -  Set sModel = ''
.head 4 -  Set sReg_No = ''
.head 4 -  Set sDriver = ''
.head 4 -  Set sFurther_Require = ''
.head 4 -  Set sLeft_Condition = ''
.head 4 -  Set sRight_Condition = ''
.head 4 -  Call GetServiceVehicleDetails( nVehicleId, sVehicle_Type, sLocation, sMake, sModel, sReg_No, sDriver, SH_cls_Execute )
.head 4 -  Call GetThisServiceDetails( nVehicleId, nServiceNo, dtServiceDoneDate, sServiceDueDistance, sServiceDoneDistance, sServiceMechanic, SH_cls_Execute )
.head 4 -  Call GetLastServiceNextTimeDetails( nVehicleId, nServiceNo, sFurther_Require, SH_cls_Execute )
.head 4 -  Return SalSendClassMessage( SAM_ReportStart, wParam, lParam )
.head 3 +  On SAM_Destroy
.head 4 -  Call GetServiceVehicleDetails( 0, sVehicle_Type, sLocation, sMake, sModel, sReg_No, sDriver, SH_cls_Disconnect )
.head 4 -  Call GetThisServiceDetails( 0, 0, dtServiceDoneDate, sServiceDueDistance, sServiceDoneDistance, sServiceMechanic, SH_cls_Disconnect )
.head 4 -  Call GetLastServiceNextTimeDetails( 0, 0, sFurther_Require, SH_cls_Disconnect )
.head 4 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 1 +  Form Window: frmPrintServiceDueReport
.head 2 -  Class: clsFormPrintBasicReport
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Service Report
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: Default
.head 4 -  Top: Default
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 -  Contents
.head 2 -  Contents
.head 2 +  Functions
.head 3 +  Function: GetVehicleServiceNumbers
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nVehicleId
.head 5 -  Receive Number: naServiceNo[*]
.head 5 -  Number: nActionType
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Number: nCount
.head 5 -  Boolean: bOk
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetVehServiceNumbers' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
  	service_no
FROM 
  	Vehicle_service
WHERE 
  	Vehicle_Id = :1
ORDER BY
	service_no desc "
.head 7 -  Set sName = 'GetVehServiceNumbers'
.head 7 -  Set sBind = ':nVehicleId'
.head 7 -  Set sInto = ':naServiceNo[nCount]'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set bOk = FALSE
.head 7 -  !
.head 7 -  Set nCount = 0
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  While haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set nCount = nCount + 1
.head 9 -  Set naServiceNo[nCount] = NUMBER_Null
.head 9 -  Set bOk = TRUE
.head 8 -  Return bOk
.head 7 +  Else
.head 8 -  Return bOk
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  ! Function: GetServiceVehicleDetails
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nVehicleId
.head 5 -  Receive String: sVehicleType
.head 5 -  Receive String: sLocation
.head 5 -  Receive String: sMake
.head 5 -  Receive String: sModel
.head 5 -  Receive String: sRegNo
.head 5 -  Receive String: sDriver
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables 
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  String: sGotVehicleType
.head 5 -  String: sGotLocation
.head 5 -  String: sGotMake
.head 5 -  String: sGotModel
.head 5 -  String: sGotRegNo
.head 5 -  String: sGotDriver
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetServiceVehicleDetails' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
  Vehicle_Type, 
  Location, 
  Make, 
  Model, 
  Reg_No, 
  Driver 
FROM 
  Vehicle 
WHERE 
  Vehicle_Id = :1 "
.head 7 -  Set sName = 'SRVRPVHDETS'
.head 7 -  Set sBind = ':nVehicleId'
.head 7 -  Set sInto = ':sGotVehicleType, :sGotLocation, :sGotMake, :sGotModel, :sGotRegNo, :sGotDriver'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sVehicleType = ''
.head 7 -  Set sLocation = ''
.head 7 -  Set sMake = ''
.head 7 -  Set sModel = ''
.head 7 -  Set sRegNo = ''
.head 7 -  Set sDriver = ''
.head 7 -  !
.head 7 -  Set sGotVehicleType = ''
.head 7 -  Set sGotLocation = ''
.head 7 -  Set sGotMake = ''
.head 7 -  Set sGotModel = ''
.head 7 -  Set sGotRegNo = ''
.head 7 -  Set sGotDriver = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set sVehicleType = sGotVehicleType
.head 9 -  Set sLocation = sGotLocation
.head 9 -  Set sMake = sGotMake
.head 9 -  Set sModel = sGotModel
.head 9 -  Set sRegNo = sGotRegNo
.head 9 -  Set sDriver = sGotDriver
.head 8 -  Return TRUE
.head 7 +  Else 
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  Function: GetThisServiceDetails
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nVehicleId
.head 5 -  Number: nServiceNo
.head 5 -  Receive Date/Time: dtServiceDoneDate
.head 5 -  Receive Date/Time: dtServiceDueDate
.head 5 -  Receive String: sServiceDueDistance
.head 5 -  Receive String: sServiceDoneDistance
.head 5 -  Receive String: sServiceMechanic
.head 5 -  Receive Long String: sFurtherRequire
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Date/Time: dtGotServiceDoneDate
.head 5 -  String: sGotServiceDueDistance
.head 5 -  String: sGotServiceDoneDistance
.head 5 -  String: sGotServiceMechanic
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetThisServiceDetails' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
  Service_Due_Date, 
  Service_Done_Date, 
  Service_Due_Dist, 
  Service_Done_Dist,
  Service_Mechanic,
Further_Require
FROM 
  Vehicle_Service 
WHERE 
  Vehicle_Id = :1 AND 
  Service_No = :2 "
.head 7 -  Set sName = 'THISSRVDTS2'
.head 7 -  Set sBind = ':nVehicleId, :nServiceNo'
.head 7 -  Set sInto = ':dtServiceDueDate, :dtGotServiceDoneDate, :sGotServiceDueDistance, :sGotServiceDoneDistance, :sGotServiceMechanic, :sFurtherRequire'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set dtServiceDoneDate = DATETIME_Null
.head 7 -  Set sServiceDueDistance = ''
.head 7 -  Set sServiceMechanic = ''
.head 7 -  Set dtGotServiceDoneDate = DATETIME_Null
.head 7 -  Set sGotServiceDueDistance = ''
.head 7 -  Set sGotServiceDoneDistance = ''
.head 7 -  Set sGotServiceMechanic = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set dtServiceDoneDate = dtGotServiceDoneDate
.head 9 -  Set sServiceDueDistance = sGotServiceDueDistance
.head 9 -  Set sServiceDoneDistance = sGotServiceDoneDistance
.head 9 -  Set sServiceMechanic = sGotServiceMechanic
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  Function: GetLastServiceNextTimeDetails
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nVehicleId
.head 5 -  Number: nServiceNo
.head 5 -  Receive Date/Time: dtServiceDoneDate
.head 5 -  Receive Date/Time: dtServiceDueDate
.head 5 -  Receive String: sServiceDueDistance
.head 5 -  Receive String: sServiceDoneDistance
.head 5 -  Receive Long String: sFurtherRequire
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Long String: sGotFurtherRequire
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetLastServiceNextTimeDetails' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
  Service_Done_Date, 
  Service_Due_Date, 
  Service_Due_Dist, 
  Service_Done_Dist,
    Further_Require 
  FROM 
    Vehicle_Service 
  WHERE 
    Vehicle_Id = :1 AND 
    Service_No = :2
  ORDER BY 
    Service_Done_Date DESC "
.head 7 -  Set sName = 'LSTSRVNXTDETS3'
.head 7 -  Set sBind = ':nVehicleId, :nServiceNo'
.head 7 -  Set sInto = ':dtServiceDoneDate, :dtServiceDueDate, :sServiceDueDistance, :sServiceDoneDistance, :sGotFurtherRequire, '
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sFurtherRequire = ''
.head 7 -  Set sGotFurtherRequire = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set sFurtherRequire = sGotFurtherRequire
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 2 +  Window Parameters
.head 3 -  ! Number: nVehicleId
.head 3 -  ! Number: nServiceNo
.head 2 +  Window Variables
.head 3 -  ! REPORT FIELDS
.head 3 -  String: sVehicle_Type
.head 3 -  String: sLocation
.head 3 -  String: sMake
.head 3 -  String: sModel
.head 3 -  String: sReg_No
.head 3 -  String: sDriver
.head 3 -  Date/Time: dtServiceDoneDate
.head 3 -  Date/Time: dtServiceDueDate
.head 3 -  String: sServiceDueDistance
.head 3 -  String: sServiceDoneDistance
.head 3 -  String: sServiceMechanic
.head 3 -  Long String: sFurther_Require
.head 3 -  String: sLeft_Condition
.head 3 -  String: sRight_Condition
.head 3 -  Number: nVehicleId
.head 3 -  Number: naServiceNo[*]
.head 3 -  Date/Time: dtLastServiceDoneDate
.head 3 -  Date/Time: dtLastServiceDueDate
.head 3 -  String: sLastServiceDueDistance
.head 3 -  String: sLastServiceDoneDistance
.head 3 -  Long String: sLastFurther_Require
.head 2 +  Message Actions
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set sReportFileNameNoPath = 'servduerep.qrp'
.head 4 -  Set sPrinter = 'A4Booklet'
.head 4 -  Set sReportBind = ':frmPrintServiceDueReport.nVehicleId, 
:frmPrintServiceDueReport.sVehicle_Type,
:frmPrintServiceDueReport.sLocation,
:frmPrintServiceDueReport.sMake,
:frmPrintServiceDueReport.sModel,
:frmPrintServiceDueReport.sReg_No, 
:frmPrintServiceDueReport.sDriver, 
:frmPrintServiceDueReport.dtServiceDoneDate, 
:frmPrintServiceDueReport.dtServiceDueDate, 
:frmPrintServiceDueReport.sServiceDueDistance, 
:frmPrintServiceDueReport.sServiceDoneDistance, 
:frmPrintServiceDueReport.sServiceMechanic, 
:frmPrintServiceDueReport.sFurther_Require'
.head 4 -  Set sReportInto = 'nVehicle_Id, 
sVehicle_Type,
sLocation,
sMake,
sModel,
sReg_No, 
sDriver, 
dtServiceDoneDate, 
dtServiceDueDate, 
sServiceDueDistance, 
sServiceDoneDistance,
sServiceMechanic, 
sGeneral_Conditions'
.head 4 -  Set sReportType = 'PRINT'
.head 4 -  Set sReportType = 'VIEW'
.head 4 -  !
.head 4 -  ! Set sReportSql = " SELECT 
  Left_Condition, 
  Right_Condition 
FROM 
  Vehicle_Check_List 
INTO 
  :frmPrintServiceDueReport.sLeft_Condition,
  :frmPrintServiceDueReport.sRight_Condition
WHERE 
  Vehicle_Type = :frmPrintServiceDueReport.sVehicle_Type
ORDER BY 
  Seq_No"
.head 4 -  Set sReportSql = "SELECT 
	Vehicle_Id,
  	Vehicle_Type, 
  	Location, 
  	Make, 
  	Model, 
  	Reg_No, 
  	Driver 
FROM 
  	Vehicle 
INTO
	:frmPrintServiceDueReport.nVehicleId,
	:frmPrintServiceDueReport.sVehicle_Type, 
	:frmPrintServiceDueReport.sLocation, 
	:frmPrintServiceDueReport.sMake, 
	:frmPrintServiceDueReport.sModel, 
	:frmPrintServiceDueReport.sReg_No, 
	:frmPrintServiceDueReport.sDriver
ORDER BY
	Location,
	Vehicle_Type,
	Make"
.head 3 +  On SAM_ReportStart
.head 4 -  Set sVehicle_Type = ''
.head 4 -  Set sLocation = ''
.head 4 -  Set sMake = ''
.head 4 -  Set sModel = ''
.head 4 -  Set sReg_No = ''
.head 4 -  Set sDriver = ''
.head 4 -  Set sFurther_Require = ''
.head 4 -  ! Call GetServiceVehicleDetails( nVehicleId, sVehicle_Type, sLocation, sMake, sModel, sReg_No, sDriver, SH_cls_Execute )
.head 4 -  ! Call GetLastServiceNumber( nVehicleId, nServiceNo, SH_cls_Execute )
.head 4 -  ! Call GetThisServiceDetails( nVehicleId, nServiceNo, dtServiceDoneDate, sServiceDueDistance, sServiceDoneDistance, sServiceMechanic, SH_cls_Execute )
.head 4 -  ! Call GetLastServiceNextTimeDetails( nVehicleId, nServiceNo, sFurther_Require, SH_cls_Execute )
.head 4 -  Return SalSendClassMessage( SAM_ReportStart, wParam, lParam )
.head 3 +  On PAM_clsFRM_REPORTFETCHNEXT
.head 4 -  ! Call GetServiceVehicleDetails( nVehicleId, sVehicle_Type, sLocation, sMake, sModel, sReg_No, sDriver, SH_cls_Execute )
.head 4 +  If GetVehicleServiceNumbers( nVehicleId, naServiceNo, SH_cls_Execute )
.head 5 -  Set sFurther_Require = STRING_Null
.head 5 -  Call GetThisServiceDetails( nVehicleId, naServiceNo[0], dtServiceDoneDate, dtServiceDueDate, sServiceDueDistance, sServiceDoneDistance, sServiceMechanic, sFurther_Require, SH_cls_Execute )
.head 5 +  If naServiceNo[1] != NUMBER_Null
.head 6 -  Call GetLastServiceNextTimeDetails( nVehicleId, naServiceNo[1], dtLastServiceDoneDate, dtLastServiceDoneDate, sLastServiceDueDistance, sLastServiceDoneDistance, sLastFurther_Require, SH_cls_Execute )
.head 5 +  If sFurther_Require = STRING_Null
.head 6 -  Set sFurther_Require = sLastFurther_Require
.head 5 +  If dtServiceDoneDate = DATETIME_Null
.head 6 -  Set dtServiceDoneDate = dtLastServiceDoneDate
.head 5 +  If dtServiceDueDate = DATETIME_Null
.head 6 -  Set dtServiceDueDate = dtLastServiceDueDate
.head 5 +  If sServiceDueDistance = STRING_Null
.head 6 -  Set sServiceDueDistance = sLastServiceDueDistance
.head 5 +  If sServiceDoneDistance = STRING_Null
.head 6 -  Set sServiceDoneDistance = sLastServiceDoneDistance
.head 4 +  Else
.head 5 -  Set dtServiceDoneDate = DATETIME_Null
.head 5 -  Set dtServiceDueDate = DATETIME_Null
.head 5 -  Set dtLastServiceDoneDate = DATETIME_Null
.head 5 -  Set sServiceDueDistance = STRING_Null
.head 5 -  Set sServiceDoneDistance = STRING_Null
.head 5 -  Set sLastServiceDueDistance = STRING_Null
.head 5 -  Set sLastServiceDoneDistance = STRING_Null
.head 5 -  Set sServiceMechanic = STRING_Null
.head 5 -  Set sFurther_Require = STRING_Null
.head 5 -  Set sLastFurther_Require = STRING_Null
.head 4 -  Return TRUE
.head 3 +  On SAM_Destroy
.head 4 -  ! Call GetServiceVehicleDetails( 0, sVehicle_Type, sLocation, sMake, sModel, sReg_No, sDriver, SH_cls_Disconnect )
.head 4 -  Call GetVehicleServiceNumbers( 0, naServiceNo, SH_cls_Disconnect )
.head 4 -  Call GetThisServiceDetails( 0, 0, dtServiceDoneDate, dtServiceDueDate, sServiceDueDistance, sServiceDoneDistance, sServiceMechanic, sFurther_Require, SH_cls_Disconnect )
.head 4 -  Call GetLastServiceNextTimeDetails( 0, 0, dtServiceDoneDate, dtTmp, sTmp,sTmp,sFurther_Require, SH_cls_Disconnect )
.head 4 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
