.head 0 +  Application Description: SQLWindows 5.01 Address functions APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C666C656D
0040: 61706C733B6B3A5C 63656E747572615C 636C617373000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D80000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF000000 0000000000140300 009F010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D0100000012496E 7465726E616C2046
0080: 756E6374696F6E73
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: sqlhandl.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for ADDRESS.APL
.head 4 -  Number: ADDRAplMsgOffSet = SAM_User + 3300
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  !
.head 4 -  Number: ADDRAplConstOffSet = 1600
.head 4 -  String: sPICKUPADDRESSLINE1= "Customer Pickup"
.head 4 -  String: sPICKUPADDRESSLINE2 = "from Fleming's Nurseries"
.head 4 -  Number: MINOrdersForDelivery = 500
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1765036113
0000: D400000051000000 0000000000000000 02000008000000D3 000000E0010D0000
0020: 00FF3FE000B80000 0100FFFFE0ED0000 0001FE00FF83FA00 000001FB00FF0F07
0040: 010000EE0100FF3F 1401BA000100FFFF 88210100040D00FE 00FFA32E010001FB
0060: 00FF0F
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 3 +  Function: GetCustBusNames
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Receive String: sCustName
.head 5 -  Receive String: sBusName
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nInd
.head 5 -  String: sGotCustName
.head 5 -  String: sGotBusName
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GETCUSTBUSNAME' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT
  Cust_Name, 
  Bus_Name
FROM
  Customer_Master
WHERE
  Cust_No = :1 "
.head 7 -  Set sNameHandle = 'GETCUSTBUSNAME'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':sGotCustName, :sGotBusName'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sCustName = ''
.head 7 -  Set sBusName = ''
.head 7 -  Set sGotCustName = ''
.head 7 -  Set sGotBusName = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set sCustName = sGotCustName
.head 9 -  Set sBusName = sGotBusName
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  Function: GetCustTypeAndDefDelType2
.head 4 -  Description: Given a customer number this function returns the customer_type
and the second receive parameter classifies GC for Garden Centers
OR for orchadists and the third parameter returns the customers
Default delivery type
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Receive String: sCustType
.head 5 -  Receive String: sGCOR
.head 5 -  Receive String: sDefDelType
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nInd
.head 5 -  !
.head 5 -  String: sGotCustType
.head 5 -  String: sGotDefDelType
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GETCUSTDELTYPES' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = "  SELECT Customer_Type, Def_Deliv_Type 
FROM Customer_Master 
WHERE Cust_No = :1 "
.head 7 -  Set sName = 'GETCUSTDELTYPES'
.head 7 -  Set sBind = ':nCustNo'
.head 7 -  Set sInto = ':sGotCustType, :sGotDefDelType'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sCustType = ''
.head 7 -  Set sGotCustType = ''
.head 7 -  Set sGCOR = ''
.head 7 -  Set sDefDelType = ''
.head 7 -  Set sGotDefDelType = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set sCustType = sGotCustType
.head 9 -  Set sDefDelType = sGotDefDelType
.head 9 +  If ( SalStrScan( sCustType, 'OR%' ) >= 0 ) OR ( sCustType = 'NOR' )
.head 10 -  Set sGCOR = 'OR'
.head 9 +  Else
.head 10 -  Set sGCOR = 'GC'
.head 9 -  Return TRUE
.head 8 +  Else
.head 9 -  Return FALSE
.head 7 +  Else
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  Function: GetShipAddress
.head 4 -  Description: Given a customer number this function returns the customer_type
and the second receive parameter classifies GC for Garden Centers
OR for orchadists and the third parameter returns the customers
Default delivery type
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: nCustNo
.head 5 -  Number: nYear
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Receive Boolean: bPickUpAddress
.head 5 -  Number: nActionType
.head 4 +  Static Variables
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 5 -  ! hcSqlHandle: fcOurConfAmtHandle
.head 4 +  Local variables
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  !
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nOurConfAmtHandleNo
.head 5 -  String: sSqlConfAmtHandle
.head 5 -  String: sBindConfAmtHandle
.head 5 -  String: sIntoConfAmtHandle
.head 5 -  String: sNameConfAmtHandle
.head 5 -  !
.head 5 -  Date/Time: dtGotAddressDT
.head 5 -  String: sGotAddressType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  !
.head 5 -  String: sAddressType
.head 5 -  String: sCustType
.head 5 -  String: sGCOR
.head 5 -  String: sDefDelType
.head 5 -  Boolean: bStopFetch
.head 5 -  Boolean: bAfterConfirmations
.head 5 -  Number: nSumConfAmt
.head 4 +  Actions
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GETSHIPADDRS' )
.head 5 -  Set nOurConfAmtHandleNo = SqlHandlesGetReferenceNo( 'CUSTTOTCONF' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT 
Add_Added_DT, 
Address_Type, 
Address_1, 
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag 
FROM Customer_Address 
WHERE Cust_No = :1 AND Address_Type = :2 "
.head 7 -  Set sNameHandle = 'GETSHIPADDRS'
.head 7 -  Set sBindHandle = ':nCustNo, :sAddressType'
.head 7 -  Set sIntoHandle = ':dtGotAddressDT, :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState, 
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments, 
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Set sSqlConfAmtHandle = " SELECT Sum(Conf_Amt) 
FROM Customer_Order 
WHERE Cust_No = :1 AND Year_Of_Sale = :2 "
.head 7 -  Set sNameConfAmtHandle = 'CUSTTOTCONF'
.head 7 -  Set sBindConfAmtHandle = ':nCustNo, :nYear'
.head 7 -  Set sIntoConfAmtHandle = ':nSumConfAmt'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurConfAmtHandleNo ].Setup( sSqlConfAmtHandle, sNameConfAmtHandle, sBindConfAmtHandle, sIntoConfAmtHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurConfAmtHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sCustType = ''
.head 7 -  Set sGCOR = ''
.head 7 -  Set sDefDelType = ''
.head 7 -  !
.head 7 -  Set dtAddressDT = DATETIME_Null
.head 7 -  Set sAddressType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set dtGotAddressDT = DATETIME_Null
.head 7 -  Set sGotAddressType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set bPickUpAddress = FALSE
.head 7 -  Call GetCustTypeAndDefDelType2( nCustNo, sCustType, sGCOR, sDefDelType, SH_cls_Execute )
.head 7 +  If sGCOR = 'GC'
.head 8 -  Set sAddressType = 'SHIP'
.head 8 -  Set bStopFetch = FALSE
.head 8 -  Set nInd = FETCH_EOF
.head 8 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 9 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 10 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 11 -  Set dtAddressDT = dtGotAddressDT
.head 11 -  Set sAddrType = sGotAddressType
.head 11 -  Set sAddressLine1 = sGotAddressLine1
.head 11 -  Set sAddressLine2 = sGotAddressLine2
.head 11 -  Set sSuburb = sGotSuburb
.head 11 -  Set sPostcode = sGotPostcode
.head 11 -  Set sState = sGotState
.head 11 -  Set sCountry = sGotCountry
.head 11 -  Set sAreaCode = sGotAreaCode
.head 11 -  Set sPhoneNo = sGotPhoneNo
.head 11 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 11 -  Set sFaxNo = sGotFaxNo
.head 11 -  Set sComments = sGotComments
.head 11 -  Set sMeetId = sGotMeetId
.head 11 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 11 -  Return TRUE
.head 10 +  Else If sAddressType = 'SHIP'
.head 11 -  Set sAddressType = 'BUS'
.head 10 +  Else If sAddressType = 'BUS'
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Return TRUE
.head 9 +  Else
.head 10 -  Set bStopFetch = TRUE
.head 10 -  Return FALSE
.head 7 +  Else
.head 8 +  If sDefDelType = 'PICKUP'
.head 9 -  Set bPickUpAddress = TRUE
.head 9 -  Return TRUE
.head 8 -  !
.head 8 +  If haSqlHandles[ nOurConfAmtHandleNo ].Execute( )
.head 9 +  If haSqlHandles[ nOurConfAmtHandleNo ].FetchNext( nInd )
.head 10 -  Set bAfterConfirmations = TRUE
.head 9 +  Else
.head 10 -  Set bAfterConfirmations = FALSE
.head 9 -  !
.head 9 +  If sDefDelType = 'DELIVER'
.head 10 -  Set sAddressType = 'SHIP'
.head 10 -  Set bStopFetch = FALSE
.head 10 -  Set nInd = FETCH_EOF
.head 10 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 -  Set dtAddressDT = dtGotAddressDT
.head 13 -  Set sAddrType = sGotAddressType
.head 13 -  Set sAddressLine1 = sGotAddressLine1
.head 13 -  Set sAddressLine2 = sGotAddressLine2
.head 13 -  Set sSuburb = sGotSuburb
.head 13 -  Set sPostcode = sGotPostcode
.head 13 -  Set sState = sGotState
.head 13 -  Set sCountry = sGotCountry
.head 13 -  Set sAreaCode = sGotAreaCode
.head 13 -  Set sPhoneNo = sGotPhoneNo
.head 13 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 13 -  Set sFaxNo = sGotFaxNo
.head 13 -  Set sComments = sGotComments
.head 13 -  Set sMeetId = sGotMeetId
.head 13 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 13 -  Return TRUE
.head 12 +  Else If sAddressType = 'SHIP'
.head 13 -  Set sAddressType = 'BUS'
.head 12 +  Else If sAddressType = 'BUS'
.head 13 +  If bAfterConfirmations
.head 14 +  If nSumConfAmt < MINOrdersForDelivery
.head 15 -  Set sAddressType = 'MEET'
.head 14 +  Else
.head 15 -  Return TRUE
.head 13 +  Else
.head 14 -  ! The next line was added and the return uncommented
.head 14 -  ! Set sAddressType = 'MEET'
.head 14 -  Return TRUE
.head 12 +  Else If sAddressType = 'MEET'
.head 13 -  Return TRUE
.head 12 +  Else
.head 13 -  Return TRUE
.head 11 +  Else
.head 12 -  Set bStopFetch = TRUE
.head 12 -  Return FALSE
.head 9 +  Else If sDefDelType = 'GROUP' 
.head 10 -  ! Else is for GROUP DefDelType
.head 10 -  Set sAddressType = 'MEET'
.head 10 -  Set bStopFetch = FALSE
.head 10 -  Set nInd = FETCH_EOF
.head 10 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 -  Set dtAddressDT = dtGotAddressDT
.head 13 -  Set sAddrType = sGotAddressType
.head 13 -  Set sAddressLine1 = sGotAddressLine1
.head 13 -  Set sAddressLine2 = sGotAddressLine2
.head 13 -  Set sSuburb = sGotSuburb
.head 13 -  Set sPostcode = sGotPostcode
.head 13 -  Set sState = sGotState
.head 13 -  Set sCountry = sGotCountry
.head 13 -  Set sAreaCode = sGotAreaCode
.head 13 -  Set sPhoneNo = sGotPhoneNo
.head 13 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 13 -  Set sFaxNo = sGotFaxNo
.head 13 -  Set sComments = sGotComments
.head 13 -  Set sMeetId = sGotMeetId
.head 13 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 13 -  Return TRUE
.head 12 +  Else If sAddressType = 'MEET'
.head 13 +  If bAfterConfirmations
.head 14 +  If nSumConfAmt >= MINOrdersForDelivery
.head 15 -  Set sAddressType = 'SHIP'
.head 14 +  Else
.head 15 -  Return TRUE
.head 13 +  Else
.head 14 -  ! The next line was added and the return uncommented
.head 14 -  ! Set sAddressType = 'SHIP'
.head 14 -  Return TRUE
.head 12 +  Else If sAddressType = 'SHIP'
.head 13 -  Set sAddressType = 'BUS'
.head 12 +  Else If sAddressType = 'BUS'
.head 13 -  Return TRUE
.head 12 +  Else
.head 13 -  Return TRUE
.head 11 +  Else
.head 12 -  Set bStopFetch = TRUE
.head 12 -  Return FALSE
.head 9 +  Else
.head 10 -  ! Else is for Blank DefDelType
.head 10 +  If bAfterConfirmations AND nSumConfAmt >= MINOrdersForDelivery
.head 11 -  Set sAddressType = 'SHIP'
.head 11 -  Set bStopFetch = FALSE
.head 11 -  Set nInd = FETCH_EOF
.head 11 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 12 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 13 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 14 -  Set dtAddressDT = dtGotAddressDT
.head 14 -  Set sAddrType = sGotAddressType
.head 14 -  Set sAddressLine1 = sGotAddressLine1
.head 14 -  Set sAddressLine2 = sGotAddressLine2
.head 14 -  Set sSuburb = sGotSuburb
.head 14 -  Set sPostcode = sGotPostcode
.head 14 -  Set sState = sGotState
.head 14 -  Set sCountry = sGotCountry
.head 14 -  Set sAreaCode = sGotAreaCode
.head 14 -  Set sPhoneNo = sGotPhoneNo
.head 14 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 14 -  Set sFaxNo = sGotFaxNo
.head 14 -  Set sComments = sGotComments
.head 14 -  Set sMeetId = sGotMeetId
.head 14 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 14 -  Return TRUE
.head 13 +  Else If sAddressType = 'SHIP'
.head 14 -  Set sAddressType = 'BUS'
.head 13 +  Else If sAddressType = 'BUS'
.head 14 -  Set sAddressType = 'MEET'
.head 13 +  Else If sAddressType = 'MEET'
.head 14 -  Return TRUE
.head 13 +  Else
.head 14 -  Return TRUE
.head 12 +  Else
.head 13 -  Set bStopFetch = TRUE
.head 13 -  Return FALSE
.head 10 +  Else
.head 11 -  Set sAddressType = 'MEET'
.head 11 -  Set bStopFetch = FALSE
.head 11 -  Set nInd = FETCH_EOF
.head 11 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 12 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 13 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 14 -  Set dtAddressDT = dtGotAddressDT
.head 14 -  Set sAddrType = sGotAddressType
.head 14 -  Set sAddressLine1 = sGotAddressLine1
.head 14 -  Set sAddressLine2 = sGotAddressLine2
.head 14 -  Set sSuburb = sGotSuburb
.head 14 -  Set sPostcode = sGotPostcode
.head 14 -  Set sState = sGotState
.head 14 -  Set sCountry = sGotCountry
.head 14 -  Set sAreaCode = sGotAreaCode
.head 14 -  Set sPhoneNo = sGotPhoneNo
.head 14 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 14 -  Set sFaxNo = sGotFaxNo
.head 14 -  Set sComments = sGotComments
.head 14 -  Set sMeetId = sGotMeetId
.head 14 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 14 -  Return TRUE
.head 13 +  Else If sAddressType = 'MEET'
.head 14 -  Return TRUE
.head 13 +  Else
.head 14 -  Return TRUE
.head 12 +  Else
.head 13 -  Set bStopFetch = TRUE
.head 13 -  Return FALSE
.head 8 +  Else
.head 9 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 -  Call haSqlHandles[ nOurConfAmtHandleNo ].Disconnect( )
.head 7 -  Return TRUE
.head 3 -  ! Care needs to be taken modifying the select statements is GetBusAddress and GetBusAddressPrivateFunction
  as they are also declared and used with the same names in GetPostalAddress and GetPostalAddressPrivateFunction
.head 3 +  ! Function: GetBusAddress
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nInd
.head 5 -  Number: nGotParentCustNo
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetBusAddressGETPARENTCSTNO' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  ! if editing bellow sql statement NOTE that this exact name and statement is referenced in 
GetMainAddress function so you must change both.
.head 7 -  Set sSqlHandle = " SELECT
  Ass_Cust_No
FROM
  Customer_Master
WHERE
  Cust_No = :1 "
.head 7 -  Set sNameHandle = 'GETPARENTCSTNO'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':nGotParentCustNo'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set nGotParentCustNo = NUMBER_Null
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 +  If nGotParentCustNo > 0
.head 10 +  If GetBusAddressPrivateFunction( nGotParentCustNo,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Execute )
.head 11 -  Return TRUE
.head 7 -  Return GetBusAddressPrivateFunction( nCustNo,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Execute )
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 -  Call GetBusAddressPrivateFunction( 0,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Disconnect )
.head 7 -  Return TRUE
.head 3 +  ! Function: GetBusAddressPrivateFunction
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 5 -  ! hcSqlHandle: fcOurAnyHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  !
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nOurAnyHandleNo
.head 5 -  String: sSqlAnyHandle
.head 5 -  String: sBindAnyHandle
.head 5 -  String: sIntoAnyHandle
.head 5 -  String: sNameAnyHandle
.head 5 -  !
.head 5 -  Date/Time: dtGotAddressDT
.head 5 -  String: sGotAddressType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  !
.head 5 -  String: sAddressType
.head 5 -  Boolean: bStopFetch
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetBusAddressPrivateFunctionGETBUSADDRS' )
.head 5 -  Set nOurAnyHandleNo = SqlHandlesGetReferenceNo( 'GetBusAddressPrivateFunctionGETBUSANYADDRS' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT 
Add_Added_DT, 
Address_Type, 
Address_1, 
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag 
FROM Customer_Address 
WHERE Cust_No = :1 AND Address_Type = :2 "
.head 7 -  Set sNameHandle = 'GETBUSADDRS'
.head 7 -  Set sBindHandle = ':nCustNo, :sAddressType'
.head 7 -  Set sIntoHandle = ':dtGotAddressDT, :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState, 
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments, 
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Set sSqlAnyHandle = " SELECT 
Add_Added_DT, 
Address_Type, 
Address_1, 
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag 
FROM Customer_Address 
WHERE Cust_No = :1 "
.head 7 -  Set sNameAnyHandle = 'GETBUSANYADDRS'
.head 7 -  Set sBindAnyHandle = ':nCustNo'
.head 7 -  Set sIntoAnyHandle = ':dtGotAddressDT, :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState, 
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments, 
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Set dtAddressDT = DATETIME_Null
.head 7 -  Set sAddressType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set dtGotAddressDT = DATETIME_Null
.head 7 -  Set sGotAddressType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sAddressType = 'BUS'
.head 7 -  Set bStopFetch = FALSE
.head 7 -  Set nInd = FETCH_EOF
.head 7 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 8 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 9 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 10 -  Set dtAddressDT = dtGotAddressDT
.head 10 -  Set sAddrType = sGotAddressType
.head 10 -  Set sAddressLine1 = sGotAddressLine1
.head 10 -  Set sAddressLine2 = sGotAddressLine2
.head 10 -  Set sSuburb = sGotSuburb
.head 10 -  Set sPostcode = sGotPostcode
.head 10 -  Set sState = sGotState
.head 10 -  Set sCountry = sGotCountry
.head 10 -  Set sAreaCode = sGotAreaCode
.head 10 -  Set sPhoneNo = sGotPhoneNo
.head 10 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 10 -  Set sFaxNo = sGotFaxNo
.head 10 -  Set sComments = sGotComments
.head 10 -  Set sMeetId = sGotMeetId
.head 10 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 10 -  Return TRUE
.head 9 +  Else If sAddressType = 'BUS'
.head 10 -  Set sAddressType = 'POSTAL'
.head 9 +  Else If sAddressType = 'POSTAL'
.head 10 -  Set sAddressType = 'HOME'
.head 9 +  Else If sAddressType = 'HOME'
.head 10 -  Set sAddressType = 'SHIP'
.head 9 +  Else If sAddressType = 'SHIP'
.head 10 -  Set sAddressType = 'RAIL'
.head 9 +  Else If sAddressType = 'RAIL'
.head 10 -  Set sAddressType = 'ANY'
.head 10 -  Set bStopFetch = TRUE
.head 8 +  Else 
.head 9 -  Set bStopFetch = TRUE
.head 9 -  Return FALSE
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurAnyHandleNo ].Setup( sSqlAnyHandle, sNameAnyHandle, sBindAnyHandle, sIntoAnyHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurAnyHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 +  If bStopFetch AND sAddressType = 'ANY'
.head 8 +  If haSqlHandles[ nOurAnyHandleNo ].Execute( )
.head 9 -  Call haSqlHandles[ nOurAnyHandleNo ].FetchNext( nInd )
.head 9 -  !
.head 9 -  Set dtAddressDT = dtGotAddressDT
.head 9 -  Set sAddrType = sGotAddressType
.head 9 -  Set sAddressLine1 = sGotAddressLine1
.head 9 -  Set sAddressLine2 = sGotAddressLine2
.head 9 -  Set sSuburb = sGotSuburb
.head 9 -  Set sPostcode = sGotPostcode
.head 9 -  Set sState = sGotState
.head 9 -  Set sCountry = sGotCountry
.head 9 -  Set sAreaCode = sGotAreaCode
.head 9 -  Set sPhoneNo = sGotPhoneNo
.head 9 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 9 -  Set sFaxNo = sGotFaxNo
.head 9 -  Set sComments = sGotComments
.head 9 -  Set sMeetId = sGotMeetId
.head 9 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 9 -  Return TRUE
.head 8 +  Else 
.head 9 -  Return FALSE
.head 7 +  Else 
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 -  Call haSqlHandles[ nOurAnyHandleNo ].Disconnect( )
.head 7 -  Return TRUE
.head 3 +  ! Function: GetPostalAddress
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nInd
.head 5 -  Number: nGotParentCustNo
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetPostalAddressGETPARENTCSTNO' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  ! if editing bellow sql statement NOTE that this exact name and statement is referenced in 
GetMainAddress function so you must change both.
.head 7 -  Set sSqlHandle = " SELECT
  Ass_Cust_No
FROM
  Customer_Master
WHERE
  Cust_No = :1 "
.head 7 -  Set sNameHandle = 'GETPARENTCSTNO'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':nGotParentCustNo'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set nGotParentCustNo = NUMBER_Null
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 +  If nGotParentCustNo > 0
.head 10 +  If GetPostalAddressPrivateFunction( nGotParentCustNo,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Execute )
.head 11 -  Return TRUE
.head 7 -  Return GetPostalAddressPrivateFunction( nCustNo,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Execute )
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 -  Call GetPostalAddressPrivateFunction( 0,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Disconnect )
.head 7 -  Return TRUE
.head 3 +  ! Function: GetPostalAddressPrivateFunction
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 5 -  ! hcSqlHandle: fcOurAnyHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  !
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nOurAnyHandleNo
.head 5 -  String: sSqlAnyHandle
.head 5 -  String: sBindAnyHandle
.head 5 -  String: sIntoAnyHandle
.head 5 -  String: sNameAnyHandle
.head 5 -  !
.head 5 -  Date/Time: dtGotAddressDT
.head 5 -  String: sGotAddressType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  !
.head 5 -  String: sAddressType
.head 5 -  Boolean: bStopFetch
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetPostalAddressPrivateFunctionGETPOSADDRS' )
.head 5 -  Set nOurAnyHandleNo = SqlHandlesGetReferenceNo( 'GetPostalAddressPrivateFunctionGETPOSANYADDRS' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT 
Add_Added_DT, 
Address_Type, 
Address_1, 
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag 
FROM Customer_Address 
WHERE Cust_No = :1 AND Address_Type = :2 "
.head 7 -  ! 02/07/03 (PXD) Set sNameHandle = 'GETBUSADDRS'
.head 7 -  Set sNameHandle = 'GETPOSTADDRS'
.head 7 -  Set sBindHandle = ':nCustNo, :sAddressType'
.head 7 -  Set sIntoHandle = ':dtGotAddressDT, :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState, 
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments, 
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Set sSqlAnyHandle = " SELECT 
Add_Added_DT, 
Address_Type, 
Address_1, 
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag 
FROM Customer_Address 
WHERE Cust_No = :1 "
.head 7 -  ! 02/07/03 (PXD)  Set sNameAnyHandle = 'GETBUSANYADDRS'
.head 7 -  Set sNameAnyHandle = 'GETPOSTANYADDRS'
.head 7 -  Set sBindAnyHandle = ':nCustNo'
.head 7 -  Set sIntoAnyHandle = ':dtGotAddressDT, :sGotAddressType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState, 
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments, 
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Set dtAddressDT = DATETIME_Null
.head 7 -  Set sAddressType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set dtGotAddressDT = DATETIME_Null
.head 7 -  Set sGotAddressType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sAddressType = 'POSTAL'
.head 7 -  Set bStopFetch = FALSE
.head 7 -  Set nInd = FETCH_EOF
.head 7 +  While nInd != FETCH_Ok AND NOT bStopFetch
.head 8 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 9 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 10 -  Set dtAddressDT = dtGotAddressDT
.head 10 -  Set sAddrType = sGotAddressType
.head 10 -  Set sAddressLine1 = sGotAddressLine1
.head 10 -  Set sAddressLine2 = sGotAddressLine2
.head 10 -  Set sSuburb = sGotSuburb
.head 10 -  Set sPostcode = sGotPostcode
.head 10 -  Set sState = sGotState
.head 10 -  Set sCountry = sGotCountry
.head 10 -  Set sAreaCode = sGotAreaCode
.head 10 -  Set sPhoneNo = sGotPhoneNo
.head 10 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 10 -  Set sFaxNo = sGotFaxNo
.head 10 -  Set sComments = sGotComments
.head 10 -  Set sMeetId = sGotMeetId
.head 10 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 10 -  Return TRUE
.head 9 +  Else If sAddressType = 'POSTAL'
.head 10 -  Set sAddressType = 'BUS'
.head 9 +  Else If sAddressType = 'BUS'
.head 10 -  Set sAddressType = 'HOME'
.head 9 +  Else If sAddressType = 'HOME'
.head 10 -  Set sAddressType = 'SHIP'
.head 9 +  Else If sAddressType = 'SHIP'
.head 10 -  Set sAddressType = 'RAIL'
.head 9 +  Else If sAddressType = 'RAIL'
.head 10 -  Set sAddressType = 'ANY'
.head 10 -  Set bStopFetch = TRUE
.head 8 +  Else 
.head 9 -  Set bStopFetch = TRUE
.head 9 -  Return FALSE
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurAnyHandleNo ].Setup( sSqlAnyHandle, sNameAnyHandle, sBindAnyHandle, sIntoAnyHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurAnyHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 +  If bStopFetch AND sAddressType = 'ANY'
.head 8 +  If haSqlHandles[ nOurAnyHandleNo ].Execute( )
.head 9 -  Call haSqlHandles[ nOurAnyHandleNo ].FetchNext( nInd )
.head 9 -  !
.head 9 -  Set dtAddressDT = dtGotAddressDT
.head 9 -  Set sAddrType = sGotAddressType
.head 9 -  Set sAddressLine1 = sGotAddressLine1
.head 9 -  Set sAddressLine2 = sGotAddressLine2
.head 9 -  Set sSuburb = sGotSuburb
.head 9 -  Set sPostcode = sGotPostcode
.head 9 -  Set sState = sGotState
.head 9 -  Set sCountry = sGotCountry
.head 9 -  Set sAreaCode = sGotAreaCode
.head 9 -  Set sPhoneNo = sGotPhoneNo
.head 9 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 9 -  Set sFaxNo = sGotFaxNo
.head 9 -  Set sComments = sGotComments
.head 9 -  Set sMeetId = sGotMeetId
.head 9 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 9 -  Return TRUE
.head 8 +  Else 
.head 9 -  Return FALSE
.head 7 +  Else 
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 -  Call haSqlHandles[ nOurAnyHandleNo ].Disconnect( )
.head 7 -  Return TRUE
.head 3 +  ! Function: GetMainAddress
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  Number: nOurHandleNo
.head 5 -  Number: nInd
.head 5 -  Number: nGotParentCustNo
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetMainAddressGETPARENTCSTNO' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  ! if editing bellow sql statement NOTE that this exact name and statement is referenced in 
GetBusAddress function so you must change both.
.head 7 -  Set sSqlHandle = " SELECT
  Ass_Cust_No
FROM
  Customer_Master
WHERE
  Cust_No = :1 "
.head 7 -  Set sNameHandle = 'GETPARENTCSTNO'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':nGotParentCustNo'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set nGotParentCustNo = NUMBER_Null
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 +  If nGotParentCustNo > 0
.head 10 +  If GetMainAddressPrivateFunction( nGotParentCustNo,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag, 
SH_cls_Execute )
.head 11 -  Return TRUE
.head 7 -  Return GetMainAddressPrivateFunction( nCustNo,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Execute )
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 -  Call GetMainAddressPrivateFunction( 0,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Disconnect )
.head 7 -  Return TRUE
.head 3 +  ! Function: GetMainAddressPrivateFunction
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive Date/Time: dtAddressDT
.head 5 -  Receive String: sAddrType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  !
.head 5 -  Number: nOurHandleNo
.head 5 -  Date/Time: dtGotAddressDT
.head 5 -  String: sGotAddrType
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Boolean: bOk
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetMainAddressPrivateFunctionGETMAINADDRS' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT 
Add_Added_DT, 
Address_Type, 
Address_1, 
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id
FROM Customer_Address 
WHERE Cust_No = :1 AND Main_Address_Flag = 'Y' "
.head 7 -  Set sNameHandle = 'GETMAINADDRS'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':dtGotAddressDT, :sGotAddrType, :sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState, 
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments, 
:sGotMeetId'
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set dtAddressDT = DATETIME_Null
.head 7 -  Set sAddrType = ''
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set dtGotAddressDT = DATETIME_Null
.head 7 -  Set sGotAddrType = ''
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set bOk = FALSE
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 9 -  Set dtAddressDT = dtGotAddressDT
.head 9 -  Set sAddrType = sGotAddrType
.head 9 -  Set sAddressLine1 = sGotAddressLine1
.head 9 -  Set sAddressLine2 = sGotAddressLine2
.head 9 -  Set sSuburb = sGotSuburb
.head 9 -  Set sPostcode = sGotPostcode
.head 9 -  Set sState = sGotState
.head 9 -  Set sCountry = sGotCountry
.head 9 -  Set sAreaCode = sGotAreaCode
.head 9 -  Set sPhoneNo = sGotPhoneNo
.head 9 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 9 -  Set sFaxNo = sGotFaxNo
.head 9 -  Set sComments = sGotComments
.head 9 -  Set sMeetId = sGotMeetId
.head 9 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 9 -  Set bOk = TRUE
.head 8 +  Else 
.head 9 -  Set bOk = FALSE
.head 7 +  Else 
.head 8 -  Set bOk = FALSE
.head 7 -  !
.head 7 +  If bOk
.head 8 -  Return TRUE
.head 7 +  Else 
.head 8 -  Return GetBusAddressPrivateFunction( nCustNo,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Execute )
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 -  Call GetBusAddressPrivateFunction( 0,
dtAddressDT,
sAddrType,
sAddressLine1,
sAddressLine2,
sSuburb,
sPostcode,
sState,
sCountry,
sAreaCode,
sPhoneNo,
sAreaCodeFax,
sFaxNo,
sComments,
sMeetId,
sMainAddressFlag,
SH_cls_Disconnect )
.head 7 -  Return TRUE
.head 3 +  ! Function: GetAddressFromDelType
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  String: sAddressType
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables 
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Boolean: bStopFetch
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GETADDRSFRMTYPE' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
Address_1, 
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag 
FROM Customer_Address 
WHERE Cust_No = :1 AND Address_Type = :2 "
.head 7 -  Set sName = 'GETADDRSFRMTYPE'
.head 7 -  Set sBind = ':nCustNo, :sAddressType'
.head 7 -  Set sInto = ':sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState, 
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments, 
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 -  Call haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 8 -  !
.head 8 -  Set sAddressLine1 = sGotAddressLine1
.head 8 -  Set sAddressLine2 = sGotAddressLine2
.head 8 -  Set sSuburb = sGotSuburb
.head 8 -  Set sPostcode = sGotPostcode
.head 8 -  Set sState = sGotState
.head 8 -  Set sCountry = sGotCountry
.head 8 -  Set sAreaCode = sGotAreaCode
.head 8 -  Set sPhoneNo = sGotPhoneNo
.head 8 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 8 -  Set sFaxNo = sGotFaxNo
.head 8 -  Set sComments = sGotComments
.head 8 -  Set sMeetId = sGotMeetId
.head 8 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 8 -  Return TRUE
.head 7 +  Else 
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  ! Function: GetAddressFromAddrDT
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Date/Time: dtAddrDT
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sSuburb
.head 5 -  Receive String: sPostcode
.head 5 -  Receive String: sState
.head 5 -  Receive String: sCountry
.head 5 -  Receive String: sAreaCode
.head 5 -  Receive String: sPhoneNo
.head 5 -  Receive String: sAreaCodeFax
.head 5 -  Receive String: sFaxNo
.head 5 -  Receive String: sComments
.head 5 -  Receive String: sMeetId
.head 5 -  Receive String: sMainAddressFlag
.head 5 -  Number: nActionType
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  String: sGotAddressLine1
.head 5 -  String: sGotAddressLine2
.head 5 -  String: sGotSuburb
.head 5 -  String: sGotPostcode
.head 5 -  String: sGotState
.head 5 -  String: sGotCountry
.head 5 -  String: sGotAreaCode
.head 5 -  String: sGotPhoneNo
.head 5 -  String: sGotAreaCodeFax
.head 5 -  String: sGotFaxNo
.head 5 -  String: sGotComments
.head 5 -  String: sGotMeetId
.head 5 -  String: sGotMainAddressFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Boolean: bStopFetch
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetAddressFromAddrDT' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT
Address_1,
Address_2,
Suburb,
Postcode,
State,
Country,
Area_Code,
Phone_No,
Area_Code_Fax,
Fax_No,
Comments,
Address_Meet_Id,
Main_Address_Flag
FROM Customer_Address
WHERE Cust_No = :1 AND Add_Added_DT = :2 "
.head 7 -  Set sName = 'GTADRFADRDT'
.head 7 -  Set sBind = ':nCustNo, :dtAddrDT'
.head 7 -  Set sInto = ':sGotAddressLine1, :sGotAddressLine2, :sGotSuburb, :sGotPostcode,:sGotState,
:sGotCountry, :sGotAreaCode, :sGotPhoneNo, :sGotAreaCodeFax, :sGotFaxNo, :sGotComments,
:sGotMeetId, :sGotMainAddressFlag'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sAddressLine1 = ''
.head 7 -  Set sAddressLine2 = ''
.head 7 -  Set sSuburb = ''
.head 7 -  Set sPostcode = ''
.head 7 -  Set sState = ''
.head 7 -  Set sCountry = ''
.head 7 -  Set sAreaCode = ''
.head 7 -  Set sPhoneNo = ''
.head 7 -  Set sAreaCodeFax = ''
.head 7 -  Set sFaxNo = ''
.head 7 -  Set sComments = ''
.head 7 -  Set sMeetId = ''
.head 7 -  Set sMainAddressFlag = ''
.head 7 -  !
.head 7 -  Set sGotAddressLine1 = ''
.head 7 -  Set sGotAddressLine2 = ''
.head 7 -  Set sGotSuburb = ''
.head 7 -  Set sGotPostcode = ''
.head 7 -  Set sGotState = ''
.head 7 -  Set sGotCountry = ''
.head 7 -  Set sGotAreaCode = ''
.head 7 -  Set sGotPhoneNo = ''
.head 7 -  Set sGotAreaCodeFax = ''
.head 7 -  Set sGotFaxNo = ''
.head 7 -  Set sGotComments = ''
.head 7 -  Set sGotMeetId = ''
.head 7 -  Set sGotMainAddressFlag = ''
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 -  Call haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 8 -  !
.head 8 -  Set sAddressLine1 = sGotAddressLine1
.head 8 -  Set sAddressLine2 = sGotAddressLine2
.head 8 -  Set sSuburb = sGotSuburb
.head 8 -  Set sPostcode = sGotPostcode
.head 8 -  Set sState = sGotState
.head 8 -  Set sCountry = sGotCountry
.head 8 -  Set sAreaCode = sGotAreaCode
.head 8 -  Set sPhoneNo = sGotPhoneNo
.head 8 -  Set sAreaCodeFax = sGotAreaCodeFax
.head 8 -  Set sFaxNo = sGotFaxNo
.head 8 -  Set sComments = sGotComments
.head 8 -  Set sMeetId = sGotMeetId
.head 8 -  Set sMainAddressFlag = sGotMainAddressFlag
.head 8 -  Return TRUE
.head 7 +  Else 
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  ! Function: GetMainContact
.head 4 -  Description: 11/10/01 GF Changed to get phone numbers, will need to change calling parameters.
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive String: sContactTitle
.head 5 -  Receive String: sContactGivenName
.head 5 -  Receive String: sContactSurname
.head 5 -  Receive String: sBHPhoneCode
.head 5 -  Receive String: sBHPhoneNo
.head 5 -  Receive String: sAHPhoneCode
.head 5 -  Receive String: sAHPhoneNo
.head 5 -  Receive String: sContactEmail
.head 5 -  Boolean: bForceOnlyMainContact
.head 5 -  Number: nActionType
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sSql
.head 5 -  String: sBind
.head 5 -  String: sInto
.head 5 -  String: sName
.head 5 -  Number: nOurHandleNo
.head 5 -  !
.head 5 -  String: sGotContactTitle
.head 5 -  String: sGotContactGivenName
.head 5 -  String: sGotContactSurname
.head 5 -  String: sGotMainContactFlag
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Boolean: bFound
.head 4 +  Actions 
.head 5 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetMainContact' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSql = " SELECT 
  Contact_Title, 
  Contact_Given_Name, 
  Contact_Surname, 
  Main_Contact_Flag,
Wrk_Phone_Code,
Contact_Work_Phone,
AH_Phone_Code,
Contact_Ah_Phone,
Email
FROM 
  Customer_Contacts 
WHERE 
  Cust_No = :1 
ORDER BY 
  Main_Contact_Flag DESC "
.head 7 -  Set sName = 'GTCSTMAINCNTCT3'
.head 7 -  Set sBind = ':nCustNo'
.head 7 -  Set sInto = ':sGotContactTitle, :sGotContactGivenName, :sGotContactSurname, :sGotMainContactFlag, :sBHPhoneCode, :sBHPhoneNo
:sAHPhoneCode, :sAHPhoneNo, :sContactEmail'
.head 7 -  !
.head 7 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sContactTitle = ''
.head 7 -  Set sContactGivenName = ''
.head 7 -  Set sContactSurname = ''
.head 7 -  !
.head 7 -  Set sGotContactTitle = ''
.head 7 -  Set sGotContactGivenName = ''
.head 7 -  Set sGotContactSurname = ''
.head 7 -  Set sGotMainContactFlag = ''
.head 7 -  Set bFound = FALSE
.head 7 -  !
.head 7 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 8 +  While haSqlHandles[ nOurHandleNo ].FetchNext( nInd ) AND NOT bFound
.head 9 +  If bForceOnlyMainContact
.head 10 +  If sGotMainContactFlag = 'Y'
.head 11 -  Set bFound = TRUE
.head 10 +  Else 
.head 11 -  Set bFound = FALSE
.head 9 +  Else 
.head 10 -  Set bFound = TRUE
.head 9 -  !
.head 9 +  If bFound
.head 10 -  Set sContactTitle = sGotContactTitle
.head 10 -  Set sContactGivenName = sGotContactGivenName
.head 10 -  Set sContactSurname = sGotContactSurname
.head 8 -  Return TRUE
.head 7 +  Else 
.head 8 -  Return FALSE
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 3 +  ! Function: FormatAttentionContactName
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sTitle
.head 5 -  String: sGivenName
.head 5 -  String: sSurname
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Return 'Attn: ' || SalStrTrimX( sTitle ) || ' ' || SalStrTrimX( sGivenName ) || ' ' || SalStrTrimX( sSurname )
.head 3 -  !
.head 3 +  Function: FixLineSpaceAddress
.head 4 -  Description: This function assumes that the variables passed in for all paramentes are strings of the 
same length.  Even though the database columns are not, data can be fetched into variables
of the same length.  This function will then remove any blank line ( ie null string ) by 
suffling DOWN the parameters values.  Therefore the names of the parements will not
necessaraly match the values.
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  String: sAttention
.head 5 -  String: sCustName
.head 5 -  String: sBusName
.head 5 -  String: sAddrL1
.head 5 -  String: sAddrL2
.head 5 -  String: sSuburb
.head 5 -  String: sState
.head 5 -  String: sPostcode
.head 5 -  Receive String: sAddressLine1
.head 5 -  Receive String: sAddressLine2
.head 5 -  Receive String: sAddressLine3
.head 5 -  Receive String: sAddressLine4
.head 5 -  Receive String: sAddressLine5
.head 5 -  Receive String: sAddressLine6
.head 4 +  Static Variables
.head 5 -  Number: nLine
.head 4 +  Local variables
.head 5 -  String: sField
.head 5 -  Number: nField
.head 4 +  Actions
.head 5 -  Set nField = 1
.head 5 -  Set sField = ''
.head 5 +  While sField = '' AND nField <= 6
.head 6 -  Set sField = NextField( sAttention, sCustName, sBusName, sAddrL1, sAddrL2, sSuburb, sState, sPostcode, nField )
.head 6 -  Set nField = nField + 1
.head 5 -  Set sAddressLine1 = sField
.head 5 -  !
.head 5 -  Set sField = ''
.head 5 +  While sField = '' AND nField <= 6
.head 6 -  Set sField = NextField( sAttention, sCustName, sBusName, sAddrL1, sAddrL2, sSuburb, sState, sPostcode, nField )
.head 6 -  Set nField = nField + 1
.head 5 -  Set sAddressLine2 = sField
.head 5 -  !
.head 5 -  Set sField = ''
.head 5 +  While sField = '' AND nField <= 6
.head 6 -  Set sField = NextField( sAttention, sCustName, sBusName, sAddrL1, sAddrL2, sSuburb, sState, sPostcode, nField )
.head 6 -  Set nField = nField + 1
.head 5 -  Set sAddressLine3 = sField
.head 5 -  !
.head 5 -  Set sField = ''
.head 5 +  While sField = '' AND nField <= 6
.head 6 -  Set sField = NextField( sAttention, sCustName, sBusName, sAddrL1, sAddrL2, sSuburb, sState, sPostcode, nField )
.head 6 -  Set nField = nField + 1
.head 5 -  Set sAddressLine4 = sField
.head 5 -  !
.head 5 -  Set sField = ''
.head 5 +  While sField = '' AND nField <= 6
.head 6 -  Set sField = NextField( sAttention, sCustName, sBusName, sAddrL1, sAddrL2, sSuburb, sState, sPostcode, nField )
.head 6 -  Set nField = nField + 1
.head 5 -  Set sAddressLine5 = sField
.head 5 -  !
.head 5 -  Set sField = ''
.head 5 +  While sField = '' AND nField <= 6
.head 6 -  Set sField = NextField( sAttention, sCustName, sBusName, sAddrL1, sAddrL2, sSuburb, sState, sPostcode, nField )
.head 6 -  Set nField = nField + 1
.head 5 -  Set sAddressLine6 = sField
.head 3 +  Function: NextField
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  String: sAttention
.head 5 -  String: sCustName
.head 5 -  String: sBusName
.head 5 -  String: sAddrL1
.head 5 -  String: sAddrL2
.head 5 -  String: sSuburb
.head 5 -  String: sState
.head 5 -  String: sPostcode
.head 5 -  Number: nProcessingFieldNo
.head 4 -  Static Variables
.head 4 -  Local variables
.head 4 +  Actions
.head 5 +  Select Case nProcessingFieldNo
.head 6 +  Case 1
.head 7 -  Return sAttention
.head 6 +  Case 2
.head 7 -  Return sCustName
.head 6 +  Case 3
.head 7 -  Return sBusName
.head 6 +  Case 4
.head 7 -  Return sAddrL1
.head 6 +  Case 5
.head 7 -  Return sAddrL2
.head 6 +  Case 6
.head 7 -  Return sSuburb || '  ' || sState || '  ' || sPostcode
.head 6 +  Default
.head 7 -  Return ''
.head 5 +  ! Select Case nProcessingFieldNo
.head 6 +     Case 1
.head 7 +     If sCustName = ''
.head 8 -     Return sBusName
.head 7 +     Else 
.head 8 -     Return sCustName
.head 6 +     Case 2
.head 7 +     If sBusName = ''
.head 8 -     Return sAddrL1
.head 7 +     Else 
.head 8 -     Return sBusName
.head 6 +     Case 3
.head 7 +     If sAddrL1 = ''
.head 8 -     Return sAddrL2
.head 7 +     Else 
.head 8 -     Return sAddrL1
.head 6 +     Case 4
.head 7 +     If sAddrL2 = ''
.head 8 -     Return sSuburb || ' ' || sState || ' ' || sPostcode
.head 7 +     Else 
.head 8 -     Return sAddrL2
.head 6 +     Case 5
.head 7 -     Return sSuburb || ' ' || sState || ' ' || sPostcode
.head 6 +     Default 
.head 7 -     Return ''
.head 3 +  Function: SwapSurnameWithFirstname
.head 4 -  Description:
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Receive String: sCustName
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: nCommaPos
.head 5 -  String: sCustLeftName
.head 5 -  String: sCustRightName
.head 4 +  Actions
.head 5 -  Set nCommaPos = SalStrScan( sCustName, ',' )
.head 5 +  If nCommaPos >= 0
.head 6 -  Call SalStrLeft( sCustName, nCommaPos, sCustLeftName )
.head 6 -  Call SalStrMid( sCustName, nCommaPos + 2, SalStrLength( sCustName ) - nCommaPos, sCustRightName )
.head 6 -  Set sCustName = sCustRightName || ' ' || sCustLeftName
.head 3 +  ! Function: GetMainEmailAddress
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive String: sMainEmailAddress
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  Number: nSqlHandleNo
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  Number: nGotParentCustNo
.head 4 +  Actions 
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GETPARENTCSTNO' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT
  Ass_Cust_No
FROM
  Customer_Master
WHERE
  Cust_No = :1 "
.head 7 -  Set sNameHandle = 'GETPARENTCSTNO'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':nGotParentCustNo'
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set nGotParentCustNo = NUMBER_Null
.head 7 -  !
.head 7 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 9 +  If nGotParentCustNo > 0
.head 10 +  If GetEmailAddressPrivateFunction( nGotParentCustNo,
sMainEmailAddress,
SH_cls_Execute )
.head 11 -  Return TRUE
.head 7 -  Return GetEmailAddressPrivateFunction( nCustNo,
sMainEmailAddress,
SH_cls_Execute )
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Disconnect( )
.head 7 -  Call GetEmailAddressPrivateFunction( 0,
sMainEmailAddress,
SH_cls_Disconnect )
.head 7 -  Return TRUE
.head 3 +  ! Function: GetEmailAddressPrivateFunction
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 5 -  Receive String: sEmailAddress
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  ! hcSqlHandle: fcOurHandle
.head 5 -  ! hcSqlHandle: fcOurAnyHandle
.head 4 +  Local variables 
.head 5 -  String: sSqlHandle
.head 5 -  String: sBindHandle
.head 5 -  String: sIntoHandle
.head 5 -  String: sNameHandle
.head 5 -  Number: nSqlHandleNo
.head 5 -  !
.head 5 -  !
.head 5 -  String: sGotEmail
.head 5 -  !
.head 5 -  Number: nInd
.head 5 -  !
.head 5 -  String: sAddressType
.head 5 -  Boolean: bStopFetch
.head 4 +  Actions 
.head 5 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GETEMAILADDRS' )
.head 5 +  Select Case nActionType
.head 6 +  Case SH_cls_Execute
.head 7 -  Set sSqlHandle = " SELECT
Email
FROM Customer_Address
WHERE Cust_No = :1 AND Main_Address_Flag = 'Y' "
.head 7 -  Set sNameHandle = 'GETMAINEMAILADD'
.head 7 -  Set sBindHandle = ':nCustNo'
.head 7 -  Set sIntoHandle = ':sGotEmail '
.head 7 -  !
.head 7 -  !
.head 7 -  Set sEmailAddress = ''
.head 7 -  Set sGotEmail = ''
.head 7 -  !
.head 7 -  !
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSqlHandle, sNameHandle, sBindHandle, sIntoHandle )
.head 7 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 7 -  !
.head 7 -  Set sAddressType = 'POSTAL'
.head 7 -  Set bStopFetch = FALSE
.head 7 -  Set nInd = FETCH_EOF
.head 7 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 8 +  If haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 9 -  Set sEmailAddress = sGotEmail
.head 9 -  Return TRUE
.head 8 +  Else 
.head 9 -  Return FALSE
.head 7 +  Else 
.head 8 -  Return FALSE
.head 7 -  !
.head 6 +  Case SH_cls_Disconnect
.head 7 -  Call haSqlHandles[ nSqlHandleNo ].Disconnect( )
.head 7 -  Return TRUE
.head 3 -  !
.head 3 +  ! Function: FormatAddressToAddressLines
.head 4 -     Description: 
.head 4 -     Returns 
.head 4 +     Parameters 
.head 5 -     String: sCustName
.head 5 -     String: sBusName
.head 5 -     String: sAddrL1
.head 5 -     String: sAddrL2
.head 5 -     String: sSuburb
.head 5 -     String: sState
.head 5 -     String: sPostcode
.head 5 -     Receive String: sAddressLine1
.head 5 -     Receive String: sAddressLine2
.head 5 -     Receive String: sAddressLine3
.head 5 -     Receive String: sAddressLine4
.head 5 -     Receive String: sAddressLine5
.head 4 -     Static Variables 
.head 4 +     Local variables 
.head 5 -     String: sAddressLines[5]
.head 5 -     String: sFormatedAddressLines[5]
.head 5 -     Number: nAddrPos
.head 5 -     Number: nFmtAddrPos
.head 4 +     Actions 
.head 5 -     Set sAddressLines[1] = sCustName
.head 5 -     Set sAddressLines[2] = sBusName
.head 5 -     Set sAddressLines[3] = sAddrL2
.head 5 -     Set sAddressLines[4] = sAddrL1
.head 5 -     Set sAddressLines[5] = sSuburb || ' ' || sState || ' ' || sPostcode
.head 5 -  !
.head 5 -     Set sFormatedAddressLines[1] = ''
.head 5 -     Set sFormatedAddressLines[2] = ''
.head 5 -     Set sFormatedAddressLines[3] = ''
.head 5 -     Set sFormatedAddressLines[4] = ''
.head 5 -     Set sFormatedAddressLines[5] = ''
.head 5 -  !
.head 5 -  ! Set nWorkPos = 1
.head 5 +  ! While nWorkPos < 6
.head 6 -     Set nPos = nWorkPos
.head 6 +     While sAddressLines[ nPos ] = ''
.head 7 +     While nPos < 6
.head 8 -     Set sAddressLines[ nPos ] = sAddressLines[ nPos + 1 ]
.head 8 -     Set nPos = nPos + 1
.head 7 -     Set sAddressLines[ nPos ] = ''
.head 6 -     Set nWorkPos = nWorkPos + 1
.head 5 -  !
.head 5 -     Set nAddrPos = 1
.head 5 -     Set nFmtAddrPos = 1
.head 5 +     While nAddrPos <= 5
.head 6 +     If sAddressLines[ nAddrPos ] != ''
.head 7 -     Set sFormatedAddressLines[ nFmtAddrPos ] = sAddressLines[ nAddrPos ]
.head 7 -     Set nFmtAddrPos = nFmtAddrPos + 1
.head 6 -     Set nAddrPos = nAddrPos + 1
.head 5 -  !
.head 5 -     Set sAddressLine1 = sFormatedAddressLines[1]
.head 5 -     Set sAddressLine2 = sFormatedAddressLines[2]
.head 5 -     Set sAddressLine3 = sFormatedAddressLines[3]
.head 5 -     Set sAddressLine4 = sFormatedAddressLines[4]
.head 5 -     Set sAddressLine5 = sFormatedAddressLines[5]
.head 3 -  !
.head 3 +  ! Function: GetContactDetails
.head 4 -     Description: 
.head 4 +     Returns 
.head 5 -     Boolean: 
.head 4 +     Parameters 
.head 5 -     Number: nCustNo
.head 5 -     Receive String: sContactTitle
.head 5 -     Receive String: sContactGivenName
.head 5 -     Receive String: sContactSurname
.head 5 -     Receive String: sContactWrkPhCode
.head 5 -     Receive String: sContactWrkPh
.head 5 -     Receive String: sContactAHPhCode
.head 5 -     Receive String: sContactAHPh
.head 5 -     Number: nActionType
.head 4 +     Static Variables 
.head 5 -     : fcOurHandle
.head 5 -     : fcOurAnyHandle
.head 4 +     Local variables 
.head 5 -     String: sSql
.head 5 -     String: sFuncName
.head 5 -     Boolean: bOk
.head 5 -     Number: nInd
.head 5 -     String: sGotContactTitle
.head 5 -     String: sGotContactGivenName
.head 5 -     String: sGotContactSurname
.head 5 -     String: sGotContactWrkPhCode
.head 5 -     String: sGotContactWrkPh
.head 5 -     String: sGotContactAHPhCode
.head 5 -     String: sGotContactAHPh
.head 4 +     Actions 
.head 5 +     Select Case nActionType
.head 6 +     Case nExecute
.head 7 +     Loop Execute
.head 8 +     Loop Connect
.head 9 +     If NOT bHandleConnected
.head 10 -     Set bHandleConnected = SqlConnect( hSqlHandle ) 
.head 10 +     If bHandleConnected
.head 11 -     Call SqlSetLockTimeout( hSqlHandle, SQLTIMEOUT )
.head 11 -     Call SqlSetParameter( hSqlHandle, DBP_PRESERVE, TRUE, ''  )
.head 11 -  ! Break Connect
.head 10 +     Else 
.head 11 +     If IDNO = SalMessageBox( 'Could not connect handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -     Break Connect
.head 9 +     If bAnyHandleConnected
.head 10 -     Break Connect
.head 9 +     Else 
.head 10 -     Set bAnyHandleConnected = SqlConnect( hSqlAnyHandle ) 
.head 10 +     If bAnyHandleConnected
.head 11 -     Call SqlSetLockTimeout( hSqlAnyHandle, SQLTIMEOUT )
.head 11 -     Call SqlSetParameter( hSqlAnyHandle, DBP_PRESERVE, TRUE, ''  )
.head 11 -     Break Connect
.head 10 +     Else 
.head 11 +     If IDNO = SalMessageBox( 'Could not connect handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -     Break Connect
.head 8 +     Loop Prepare
.head 9 +     If NOT bHandlePrepared
.head 10 -     Set sSql = " SELECT Contact_Title, Contact_Given_Name, Contact_Surname, 
  Wrk_Phone_Code, Contact_Work_Phone, AH_Phone_code, Contact_AH_Phone
  FROM Customer_Contacts
  INTO :sGotContactTitle, :sGotContactGivenName, :sGotContactSurname, 
  :sGotContactWrkPhCode, :sGotContactWrkPh, :sGotContactAHPhCode, :sGotContactAHPh
  WHERE Cust_No = :nCustNo AND MAIN_CONTACT_FLAG = 'Y' "
.head 10 +     If SqlPrepare( hSqlHandle, sSql )
.head 11 -     Set bHandlePrepared = TRUE
.head 11 -  ! Break Prepare
.head 10 +     Else 
.head 11 -     Set bHandlePrepared = FALSE
.head 11 +     If IDNO = SalMessageBox( 'Could not prepare handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -     Break Prepare
.head 9 +     If bAnyHandlePrepared
.head 10 -     Break Prepare
.head 9 +     Else 
.head 10 -     Set sSql = ' SELECT Contact_Title, Contact_Given_Name, Contact_Surname, 
  Wrk_Phone_Code, Contact_Work_Phone, AH_Phone_code, Contact_AH_Phone
  FROM Customer_Contacts
  INTO :sGotContactTitle, :sGotContactGivenName, :sGotContactSurname, 
  :sGotContactWrkPhCode, :sGotContactWrkPh, :sGotContactAHPhCode, :sGotContactAHPh
  WHERE Cust_No = :nCustNo '
.head 10 +     If SqlPrepare( hSqlAnyHandle, sSql )
.head 11 -     Set bAnyHandlePrepared = TRUE
.head 11 -     Break Prepare
.head 10 +     Else 
.head 11 -     Set bAnyHandlePrepared = FALSE
.head 11 +     If IDNO = SalMessageBox( 'Could not prepare handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -     Break Prepare
.head 8 -  !
.head 8 -     Set sGotContactTitle = ''
.head 8 -     Set sGotContactGivenName = ''
.head 8 -     Set sGotContactSurname = ''
.head 8 -     Set sGotContactWrkPhCode = ''
.head 8 -     Set sGotContactWrkPh = ''
.head 8 -     Set sGotContactAHPhCode = ''
.head 8 -     Set sGotContactAHPh = ''
.head 8 -  !
.head 8 -     Set sContactTitle = ''
.head 8 -     Set sContactGivenName = ''
.head 8 -     Set sContactSurname = ''
.head 8 -     Set sContactWrkPhCode = ''
.head 8 -     Set sContactWrkPh = ''
.head 8 -     Set sContactAHPhCode = ''
.head 8 -     Set sContactAHPh = ''
.head 8 -  !
.head 8 +     If SqlExecute( hSqlHandle )
.head 9 +     If SqlFetchNext( hSqlHandle, nInd )
.head 10 -     Set sContactTitle = sGotContactTitle
.head 10 -     Set sContactGivenName = sGotContactGivenName
.head 10 -     Set sContactSurname = sGotContactSurname
.head 10 -     Set sContactWrkPhCode = sGotContactWrkPhCode
.head 10 -     Set sContactWrkPh = sGotContactWrkPh
.head 10 -     Set sContactAHPhCode = sGotContactAHPhCode
.head 10 -     Set sContactAHPh = sGotContactAHPh
.head 10 -     Return TRUE
.head 9 +     Else 
.head 10 +     If SqlExecute( hSqlAnyHandle )
.head 11 -     Call SqlFetchNext( hSqlAnyHandle, nInd )
.head 11 -     Set sContactTitle = sGotContactTitle
.head 11 -     Set sContactGivenName = sGotContactGivenName
.head 11 -     Set sContactSurname = sGotContactSurname
.head 11 -     Set sContactWrkPhCode = sGotContactWrkPhCode
.head 11 -     Set sContactWrkPh = sGotContactWrkPh
.head 11 -     Set sContactAHPhCode = sGotContactAHPhCode
.head 11 -     Set sContactAHPh = sGotContactAHPh
.head 11 -     Return TRUE
.head 10 +     Else 
.head 11 -     Set bAnyHandlePrepared = FALSE
.head 11 +     If IDNO = SalMessageBox( 'Could not execute ANY handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 12 -     Return FALSE
.head 8 +     Else 
.head 9 -     Set bHandlePrepared = FALSE
.head 9 +     If IDNO = SalMessageBox( 'Could not execute handle in function '||sFuncName||'! Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 10 -     Return FALSE
.head 6 +     Case nDisconnect
.head 7 -     Set bOk = TRUE
.head 7 +     Loop Disconnect
.head 8 +     If bHandleConnected
.head 9 +     If SqlDisconnect( hSqlHandle )
.head 10 -     Set bHandleConnected = FALSE
.head 10 -     Set bHandlePrepared = FALSE
.head 9 +     Else 
.head 10 +     If IDNO = SalMessageBox( 'Could not disconnect handle in function '||sFuncName||'Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 11 -     Set bOk = FALSE
.head 11 -     Break Disconnect
.head 8 +     If bAnyHandleConnected
.head 9 +     If SqlDisconnect( hSqlAnyHandle )
.head 10 -     Set bAnyHandleConnected = FALSE
.head 10 -     Set bAnyHandlePrepared = FALSE
.head 10 -     Break Disconnect
.head 9 +     Else 
.head 10 +     If IDNO = SalMessageBox( 'Could not disconnect ANY handle in function '||sFuncName||'Contact programmers! RETRY?', 'Error', MB_YesNo )
.head 11 -     Set bOk = FALSE
.head 11 -     Break Disconnect
.head 8 +     Else 
.head 9 -     Break Disconnect
.head 7 -     Return bOk
.head 6 +     Case nRePrepare
.head 7 -     Set bHandlePrepared = FALSE
.head 7 -     Set bAnyHandlePrepared = FALSE
.head 7 -     Return TRUE
.head 5 +  ! Select Case nActionType
.head 6 +     Case SH_cls_Execute
.head 7 -     Set sSql = " SELECT Sold_Out_Flag 
FROM Stock_Item_Sale 
WHERE Stock_Item_No = :1 AND Year_Of_Sale = :2 "
.head 7 -     Set sName = 'SISYREXISTS'
.head 7 -     Set sBind = ':nItemNo, :nYear'
.head 7 -     Set sInto = ':sGotSoldOutFlag'
.head 7 -  !
.head 7 -     Call fcOurHandle.Setup( sSql, sName, sBind, sInto )
.head 7 -     Call SqlVarSetup( fcOurHandle.hSqlHandle )
.head 7 -  !
.head 7 -     Set bExists = FALSE
.head 7 -     Set sSoldOutFlag = ''
.head 7 -     Set sGotSoldOutFlag = ''
.head 7 -  !
.head 7 +     If fcOurHandle.Execute( )
.head 8 +     If fcOurHandle.FetchNext( nInd )
.head 9 -     Set bExists = TRUE
.head 8 +     Else 
.head 9 -     Set bExists = FALSE
.head 8 -     Set sSoldOutFlag = sGotSoldOutFlag
.head 8 -     Return TRUE
.head 7 +     Else 
.head 8 -     Return FALSE
.head 6 +     Case SH_cls_Disconnect
.head 7 -     Return fcOurHandle.Disconnect( )
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 130984242
0000: B70C0000F8050000 0000000000000000 0200001A00FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F04003C00 001063006C73546F
0040: 6F6C546900705769 6E646F771E800000 0001000000470304 0000FFFF21018004
0060: 0000014200000C63 6C72006247656E65 72616C641E000001 008F020400FE00FF
0080: 03018011000000E0 020000000CF86362 47C138000000021E 00010D00FC0000FF
00A0: 270D000002F60400 FF1F018011030003 0000000D04636C53 656E6445806D6169
00C0: 6C733800E8000200 00D9010D00FF7F0D 620000020400FFFF 0101804500000004
00E0: 0200000863514F45 0E6DA8000000F006 000000EC010D00FF BF0DB9000100FFFF
0100: E21A000001FE00FF 832700000001FB00 FF0F34000000EE01 00FF3F4100380000
0120: 020001FA00000780 01000000FF180180 040005003800000C 6D6C744765651EA3
0140: 0001000067030400 FFFF0101802E0000 0006430011636C70 0062537461727450
0160: 72006F6772616DBA 0000E00007000000 DD0200FF7F047300 0200FFFFC1080000
0180: 0002FD00FF070C00 000001F60D00FF1F 190000DC000300FF 7F1D700000000200
01A0: FFFFC12100000001 FD00FF0701803A00 000C0007000F636C F953741F080100E1
01C0: 0A000000D9010D00 FF7F0D73000100FF FFCD1A0002FD00FF 271E000002F700FF
01E0: 1F220000DC000200 FF7F267000000002 00FFFFC12A000000 02FD00FF272E0000
0200: 02F700FF1F320000 DC000200FF7F3670 0000000200FFFF21 01800D0000086300
0220: 0C63707D476C4700 010000CF010DFE00 FF43018038000080 0900000009636C03
0240: 48656C708600D800 000500BB0200FFFF C60400010DFE00FF 9311000001FB00FF
0260: 6F1E00EE0100FF3F 2B00B800000100FF FF9801800D000AF9 000940457869741E
0280: 0000F4010000EC01 0D00FF3F01800604 000B0000000E0C50 696345807870616E
02A0: 641E00E800010000 DD0200FF7F018C80 04000C00F0001263 6C00546F67676C65
02C0: 42754074746F6E1E 0000F4010000EE02 00FF3F0180660400 0D000C0C63646647
02E0: 65FFE800010000DD 0300FF7F0100802F 0000000E00001000 0B636C466F72806D
0300: 426173658600EC00 0500D9010D00FF7F 0D73000200FFFF0D 1100040D00FD00FF
0320: 371E0003F700FFDF 22DC000100FF7F01 0C800D000F0000F0 0017636C01507269
0340: 6E74426101696352 65706F728C741E00 01009E00010DFD00 FFC701802F800010
0360: 0000001063014469 616C6F67473E6586 00D9000500B3010D 00FFFFE60D0002FE
0380: 00FF9B110004FB00 FF6F1E00EE0300FF BF22B9000100FFFF 9801800D00113100
03A0: 1163537000696E53 6561736F6E405965 61721E0000F40100 00EC010D00FF3F01
03C0: 8004340000120000 002814636C705365 006C65637446726F 6D005461626C656C
03E0: 0000E800040000D9 010D00FF7F0D7300 0100FFFFCD1A0001 FD00FF37270001F7
0400: 00FF1F0180040300 130000000D266353 65656381496E746F 1E00E800010000DD
0420: 0300FF7F010080B7 0000001400009000 16636C4765CF5461 F947650836020015
0440: 000000CF010DFE00 FF930D000001FB00 FF6F1A00EE0100FF BF27B9000100FFFF
0460: E6340002FE00FF93 38000002FB00FF0F 3C000000EE0200FF 3F4000B800000200
0480: FFFFE04400000002 FE00FF8348000000 02FB00FF0F4C0000 00EE0200FF3F5000
04A0: 380000020001FA00 002780010000FFC0 54000000010DE800 0100009F8001FC00
04C0: 000358000000010D FB00FF0F65000000 EE0100FF3F7200B8 00000100FFFFE07F
04E0: 00000001FE00FF83 8C00000001FB00FF 0F99000000EE0100 FF3FA600B8000001
0500: 00FFFFE0B3000000 03FE00FF43018022 00008615001D636C 0054626C4D616B65
0520: 5316656365645200 6F774B6579417272 8061797400000004 BD0002A300010000
0540: 7F80F20100006F04 00EC010D00FF3F11 00B9000100FFFFE6 1E0002FE00FF6301
0560: 801100E016000000 1000436F6C756D6E 4765CF6C38E80002 0000D9020400FF7F
0580: 046300010D00FFFF 3101800400171000 00000C6654610365 4361636865441E00
05A0: 00010000EF03FE00 FF43018015000020 180000000B66438E 61506F6F405A0000
05C0: 000300008F071900 80000101004A0900 9E008001FC00001B 04000304FB00FF6F
05E0: 0800EC010D00FF3F 0180660D00190000 0C67774D6F757365 C0576865656C1EE8
0600: 00010000D9010D00 FF7F
.enddata
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
