.head 0 +  Application Description: SQLWindows 5.01 Jans Customer Customer Barcode Labels APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C666C656D
0040: 61706C733B6B3A5C 63656E747572615C 636C617373000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D80000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF580000 0058000000EC0200 0095010000010000 0000000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: FRMCTBL.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: TABLE.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: STRINGS.APL
.head 2 -  File Include: METER.APL
.head 2 -  File Include: STACKS.APL
.head 2 -  File Include: VTMETER.APL
.head 2 -  File Include: FLAGS.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: CHECKBOX.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: QUERY.APL
.head 2 -  File Include: CMBFIELD.APL
.head 2 -  File Include: PICK.APL
.head 2 -  File Include: ACTIVATE.APL
.head 2 -  File Include: ITEMFUNC.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: GROUPBOX.APL
.head 2 -  File Include: DLGCTBL.APL
.head 2 -  File Include: STCKITMQ.APL
.head 2 -  File Include: CUSTQ.APL
.head 2 -  File Include: VTWIN.APL
.head 2 -  File Include: LISTBOX.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for CstLblA.APL
.head 4 -  Number: CstLblAAplMsgOffSet = SAM_User + 5000
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: CstLblAAplConstOffSet = 2450
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1890852527
0000: E4040000AC010000 0000000000000000 020000300000005D 000000E0010D0000
0020: 00FF3F6A00B80000 0100FFFFE0770000 0001FE00FF838400 000001FB00FF0F91
0040: 000000EE0100FF3F 9E00B800000100FF FFE0AB00000001FE 00FF83B800000001
0060: FB00FF0FC5000000 E00204000000FF3F C900B800000200FF FFE0CD00000001FE
0080: 00FF83DA00000001 FB00FF0FE7000000 EE0100FF3FF400B8 00000100FFFF8001
00A0: 010000030400FE00 FF23050100010DFB 00FF8F120100EE01 00FF3F1F01BA0002
00C0: 00FFFFE823010002 FE00FFA327010002 FB00FF8F2B0100EE 0100FF3F3801BA00
00E0: 0200FFFFE83C0100 02FE00FFA3400100 01FB00FF8F4D0100 EE0100FF3F5A01BA
0100: 000100FFFFE86701 0001FE00FFA37401 0003FB00FF8F7801 00EE0100FF3F8501
0120: BA000100FFFFE892 010002FE00FFA396 010002FB00FF8F9A 0100EE0200FF3F9E
0140: 01BA000100FFFFE8 AB010002FE00FFA3 AF010002FB00FF8F B30100EE0100FF3F
0160: C001BA000100FFFF E8CD010001FE00FF A3DA010001FB00FF 8FE70100EE0300FF
0180: 3FEB01BA000100FF FFE8F8010001FE00 FF830502000002FB 00FF8F090200EE02
01A0: 00FF3F0D02BA0002 00FFFFE811020001 FE00FF231E020004 0DFA0000FF0F
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 3906881067
0000: 760F0000F7060000 0000000000000000 0200001D00FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F15003C00 000F63006C737062
0040: 51756F7400617469 6F6E735200C00000 0300000083020400 0000FFFF04040000
0060: 010D0000FE00FF03 110000000304FA00 00FF0F01802B0000 0000010000001163
0080: 026C466F726D4368 00696C645461626C 65606C0000000400 CF010DFE00FF930D
00A0: 000001FB00FF0F1A 000000EE0100FF3F 2700B800000200FF FF0001802F000000
00C0: 0200E000000E636C 0347656E65726100 6C86000000050000 9E00010DFD00FF37
00E0: 0D0002F60400FF9F 1100D000040D0000 FF7F1E7000000003 00FFFFC122000000
0100: 01FD00FF8701800D 0008000300001763 6C1F507269006E74 4261736963528065
0120: 706F72741E00E800 010000D9010D00FF 7F018C800D000400 50000C636C70473E
0140: 651E00D100010000 B3010D00FFFF9801 800D0005E1000963 6C60457869741E00
0160: F4010000EC010D00 FF3F018004040000 060000000E0C5069 6345807870616E64
0180: 1E00E800010000DD 0200FF7F010C8004 00070000F0001263 6C00546F67676C65
01A0: 42754074746F6E1E 0000F4010000EE02 00FF3F0180060400 080000000E0C6466
01C0: 4765FFE800010000 D9030400FF7F0108 8022000009000010 001D636C54626C00
01E0: 4D616B6553656C65 0063746564526F77 4B00657941727261 7974B00000000400
0200: 770200F40100000F 80010000FE008D04 00010DFD00FF3711 0001F700FFDF1EDC
0220: 000200FF7F010080 B70000000A0000BC 000F61F165476590 6C36020015009E00
0240: 010DFD00FF370D00 01F700FFDF1ADC00 0100FF7F27730001 00FFFFC134000000
0260: 02FD00FF07380000 0002F700FF1F3C00 00DC000200FF7F40 700000000200FFFF
0280: C14400000002FD00 FF074800000002F7 00FF1F4C0000DC00 0200FF7F50700000
02A0: 000200F40100004F 800100FE00815400 0000010DD1000100 003F8001F9000007
02C0: 5800000001F60D00 FF1F650000DC0001 00FF7F7270000000 0100FFFFC17F0000
02E0: 0001FD00FF078C00 000001F700FF1F99 0000DC000100FF7F A6700000000100FF
0300: FFC1B300000003FD 00FFC701800D0000 0B0000000B686340 53716C48616E6C88
0320: 651E000001009E00 010DFD00FFC70180 2F00000C00000010 636C014469616C6F
0340: 6747BE6586D90005 00B3010D00FFFFE6 0D0002FE00FF1B11 00040DFB00FF6F1E
0360: 00EE0300FFBF22B9 000100FFFF980180 0D000D31000C6363 627E471EA3000100
0380: 0067010D00FFFF21 01803400000E4000 000014636C705953 656346E0726F6D54
03A0: 61446C0000040000 CF010DFE00FF9B0D 0001FB00FF6F1A00 EE0100FFBF27B900
03C0: 0100FFFF18018004 000F002000000D63 6C5365096563496E 746F441E00000100
03E0: 00EF03FE00FF6301 800D00C010000000 11630170696E5365 6173006F6E596561
0400: 721E00D100010000 B3010D00FFFF0001 802E0000001100B1 0011637001746172
0420: 7450726F00677261 6DBA000000F60700 EE0200FFBF04B900 0200FFFFE6080002
0440: FE00FF130C000001 0DFB00FF0F190000 00EE0300FF3F1D00 B800000200FFFFE0
0460: 2100000001FE00FF 4301801E00008012 00000013636C2E44 6F4368FF44520000
0480: 030000CF010DFE00 FF930D000001FB00 FF6F1A00EE0200FF 3F01800415000013
04A0: 0000002C0E637043 750073746F6D6572 7352B30003007702 00FFFF8D0400010D
04C0: FD00FF2711000003 F60400FF1F018033 0000000014000000 11266354625175E0
04E0: 6572794469C1A000 000006DE0003FD00 FF37040002F700FF DF08DC000200FF7F
0500: 0C6300010D00FFFF CD190001FD00FF07 2600000001F700FF 1F01805D30000000
0520: 150011E751750161 74614669656CD064 4401000CDE0002FD 00FF37040002F700
0540: FFDF08DC000200FF 7F0C73000200FFFF 8D1000010DFD00FF 371D0001F700FF1F
0560: 2A00001C00020001 00FD009380010000 7F2E620000010D00 FFFFC13B00000002
0580: FD00FF073F000000 01F700FFDF4CDC00 0200FF7F50730001 00FFFF3101805D00
05A0: 16E1000012630F43 6F6D62F86F4669DB 0C00BB0200FFFFE6 040002FE00FF9B08
05C0: 0002FB00FF6F0C00 EE0200FFBF10B100 010D00FFFFE61D00 01FE00FF9B2A0002
05E0: A3000100007F80F2 0100006F2E00EC01 0D00FFBF3BB90002 00FFFFE63F0001FE
0600: 00FF9B4C0002FB00 FF6F5000EE0100FF 3F0180041A000017 000000F815636C01
0620: 4F70657261746F38 7246693800D10002 0000B3010D00FFFF E60D0001FE00FF63
0640: 01800400C0180000 0013630F79434259 0065734E6F466C61 67441E0000010000
0660: CF0204FE00FF6301 801500C619000F63 0A70536F636B4960 74656D735200F403
0680: 0000EE0200FFBF04 B100010D00FFFFC4 1100000304FE00FF 6301801500E61A00
06A0: 12035768656E4176 A061696C616265A3 00030000770200FF FF8D0400010DFD00
06C0: FF37110003F60400 FF1F01800D03001B 0000001207646C67 5151FC5374131E00
06E0: 0001003D00010DFB 00FF8F0180048100 1C00000015836672 6D5175F353747F00
0700: F4010000EE0200FF 3F
.enddata
.head 3 +  Pushbutton Class: clspbCustLabels
.head 4 -  Title: CstLbls
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name:
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbPickInto
.head 4 +  Class Variables
.head 5 -  String: sTmp
.head 5 -  Number: nTmp
.head 5 -  Window Handle: hWndTmp
.head 4 +  Instance Variables
.head 5 -  ! PUBLIC
.head 5 -  Window Handle: hWndPickIntoTable
.head 5 -  ! PRIVATE
.head 5 -  Number: nCustNo
.head 5 -  String: sCustName
.head 5 -  Number: nItemNo
.head 5 -  Number: nYear
.head 5 -  String: sTreeTypeDesc
.head 5 -  String: sCultDesc
.head 5 -  String: sRootDesc
.head 4 +  Functions
.head 5 +  Function: SetCstLblationsFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nNewCustNo
.head 7 -  String: sNewCustName
.head 7 -  Number: nNewItemNo
.head 7 -  Number: nNewYear
.head 7 -  String: sNewTreeTypeDesc
.head 7 -  String: sNewCultDesc
.head 7 -  String: sNewRootDesc
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set nCustNo = nNewCustNo
.head 7 -  Set sCustName = sNewCustName
.head 7 -  Set nItemNo = nNewItemNo
.head 7 -  Set nYear = nNewYear
.head 7 -  Set sTreeTypeDesc = sNewTreeTypeDesc
.head 7 -  Set sCultDesc = sNewCultDesc
.head 7 -  Set sRootDesc = sNewRootDesc
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set hWndPickIntoTable = hWndItem
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set clspbCustLabels.nActivateWindowType = ACTIVATE_FormWindow
.head 6 -  Set clspbCustLabels.sActivateDialogName = 'frmCustLabels'
.head 6 -  Set clspbCustLabels.hWndTable = hWndPickIntoTable
.head 6 -  Set clspbCustLabels.hWndFieldLookUp = hWndItem
.head 5 +  On PAM_clsACTIVATE_PUSHFIELDS
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call PushNumber( nCustNo )
.head 6 -  Call PushString( sCustName )
.head 6 -  Call PushNumber( nItemNo )
.head 6 -  Call PushNumber( nYear )
.head 6 -  Call PushString( sTreeTypeDesc )
.head 6 -  Call PushString( sCultDesc )
.head 6 -  Call PushString( sRootDesc )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsACTIVATE_POPFIELDS
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopNumber( nTmp, TRUE )
.head 6 -  Call PopNumber( nTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopNumber( nTmp, TRUE )
.head 6 -  Return TRUE
.head 3 +  Form Window Class: clsfrmCustLabels
.head 4 -  Title: Customer Customer Barcode Labels
.head 4 -  Icon File:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Automatically Created at Runtime? Class Default
.head 5 -  Initial State: Class Default
.head 5 -  Maximizable? Class Default
.head 5 -  Minimizable? Class Default
.head 5 -  Allow Child Docking? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  System Menu? Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Form Size
.head 6 -  Width:  Class Default
.head 6 -  Height: Class Default
.head 6 -  Number of Pages: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Next Class Child Key: 45
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsFormChildTable
.head 4 -  Menu
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbAddRows
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 8
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbSaveRows
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 9
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 8
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbDeleteRows
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 11
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRePopulate
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 12
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbTools
.head 7 -  Class Child Ref Key: 23
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbStockItems
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 31
.head 7 -  Class: clspbStockItems
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 7.513"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbStockItems.hWndPickIntoTable = tblCustLabels
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbStockItems.SetStockItemsFields( tblCustLabels.colCstLblYearOfSale, tblCustLabels.colTreeTypeDesc, tblCustLabels.colCultDesc, tblCustLabels.colRootDesc )
.head 9 -  Return TRUE
.head 8 +  On PAM_cls_GETFIELDS
.head 9 -  Call pbStockItems.GetStockItemsFields( tblCustLabels.colCstLblItemNo, 
tblCustLabels.colCstLblYearOfSale, 
sTmp, 
tblCustLabels.colTreeTypeDesc, 
sTmp, 
tblCustLabels.colCultDesc, 
sTmp, 
tblCustLabels.colRootDesc, 
nTmp, nTmp  )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbCustomers
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 32
.head 7 -  Class: clspbCustomers
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 8.113"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbCustomers.hWndPickIntoTable = tblCustLabels
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbCustomers.SetCustomersFields( tblCustLabels.colCstLblCustNo, tblCustLabels.colCustName, '' )
.head 9 -  Return TRUE
.head 8 +  On PAM_cls_GETFIELDS
.head 9 -  Call pbCustomers.GetCustomersFields( tblCustLabels.colCstLblCustNo, tblCustLabels.colCustName, sTmp )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 42
.head 7 -  Class ChildKey: 38
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 43
.head 7 -  Class ChildKey: 39
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 44
.head 7 -  Class ChildKey: 40
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClearRows
.head 7 -  Class Child Ref Key: 52
.head 7 -  Class ChildKey: 42
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 50
.head 7 -  Class ChildKey: 43
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDClose
.head 7 -  Class Child Ref Key: 54
.head 7 -  Class ChildKey: 44
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDRead
.head 7 -  Class Child Ref Key: 55
.head 7 -  Class ChildKey: 45
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 +  Child Table: tblCustLabels
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 16
.head 6 -  Class: clsTableGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.013"
.head 8 -  Top: 0.344"
.head 8 -  Width:  9.85"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 4.417"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colCstLblUserId
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 17
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Added By
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCstLblUserId.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Set colCstLblUserId = SqlUser
.head 10 -  Return TRUE
.head 7 +  Column: colCstLblSysDT
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 18
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Added Date
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Date/Time
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCstLblSysDT.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Set colCstLblSysDT = GetUniqueCurrentSysDT(  )
.head 10 -  Return TRUE
.head 7 +  Column: colCstLblItemNo
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 21
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: ItemNo
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Call ErrorMessage( 'No Stock Item was selected here! Please select a valid stock item first.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Call CountSpecificCstLblas( colCstLblCustNo, colCstLblItemNo, colCstLblYearOfSale, nCount, SH_cls_Execute )
.head 10 +  If nCount > 0
.head 11 -  Call ErrorMessage( 'This same CstLblation already exists for this customer! Please rectify!', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 9 +  On PAM_clsTBL_CHECKROWEDITED
.head 10 -  Call CountSpecificCstLblas( colCstLblCustNo, colCstLblItemNo, colCstLblYearOfSale, nCount, SH_cls_Execute )
.head 10 +  If nCount > 1
.head 11 -  Call ErrorMessage( 'This same CstLblation already exists for this customer! Please rectify!', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 7 +  Column: colCstLblYearOfSale
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 22
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Year
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.625"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: #0
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCstLblYearOfSale.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Call CheckYearItemExists( colCstLblItemNo, colCstLblYearOfSale, bExists, sTmp, SH_cls_Execute )
.head 10 +  If bExists
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Call ErrorMessage( 'This Stock Item is not growing for the entered year of sale! Please select a valid Stock Item.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 9 +  On PAM_clsTBL_CHECKROWEDITED
.head 10 -  Call CheckYearItemExists( colCstLblItemNo, colCstLblYearOfSale, bExists, sTmp, SH_cls_Execute )
.head 10 +  If bExists
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Call ErrorMessage( 'This Stock Item is not growing for the entered year of sale! Please select a valid Stock Item.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 7 +  Column: colVarietyType
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 27
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Variety Type
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colVarietyType.bOrderBy = TRUE
.head 7 +  Column: colUpperVariety
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 33
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Variety
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colUpperVariety.bOrderBy = TRUE
.head 7 +  Column: colUpperCultDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 28
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cultivar Description
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colUpperCultDesc.bOrderBy = TRUE
.head 7 +  Column: colUpperRootDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 29
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Rootstock Desc.
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colUpperRootDesc.bOrderBy = TRUE
.head 7 +  Column: colTreeTypeDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 23
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Tree Type Desc.
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.413"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colTreeTypeDesc.bOrderBy = TRUE
.head 7 +  Column: colCultDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 24
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cultivar Description
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  2.1"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colRootDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 25
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Rootstock Desc.
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.463"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colCstLblContPrice
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 30
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cont.Price
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Right
.head 8 -  Width:  1.075"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: ###000;###000
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCstLblContPrice.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Call ErrorMessage( 'Please enter a price first!', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 7 +  Column: colCstLblCustNo
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 19
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cust.No.
.head 8 -  Visible? Class Default
.head 8 -  Editable? Yes
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.863"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: #0
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCstLblCustNo.bOrderBy = TRUE
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( hWndItem )
.head 11 -  Call ErrorMessage( 'No customer was selected here! Please select a valid customer first.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 +  If CustNoExists( colCstLblCustNo, SH_cls_Execute )
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 7 +  Column: colUpperCustName
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 26
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Customer Name
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colUpperCustName.bOrderBy = TRUE
.head 7 +  Column: colCustName
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 20
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Customer Name
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.938"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 6 +  Functions
.head 7 +  Function: CountSpecificCstLblas
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  Number: nCustNo
.head 9 -  Number: nItemNo
.head 9 -  Number: nYear
.head 9 -  Receive Number: nCount
.head 9 -  Number: nActionType
.head 8 +  Static Variables
.head 9 -  ! hcSqlHandle: fcOurHandle
.winattr class FunctionalVar:
.head 10 -  Class: hcSqlHandle
.end
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nGotCount
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'CNTSPECCstLblA' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " SELECT 
  Count( * ) 
FROM 
  CstLblation 
WHERE 
  Cust_No = :1 AND 
  Stock_Item_No = :2 AND 
  Year_Of_Sale = :3 "
.head 11 -  Set sName = 'CNTSPECCstLblA'
.head 11 -  Set sBind = ':nCustNo, :nItemNo, :nYear'
.head 11 -  Set sInto = ':nGotCount'
.head 11 -  !
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Set nCount = NUMBER_Null
.head 11 -  Set nGotCount = NUMBER_Null
.head 11 -  !
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 -  Set nCount = nGotCount
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 +  Function: CustNoExists
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  Number: nCustNo
.head 9 -  Number: nActionType
.head 8 -  Static Variables
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nGotCustNo
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'CstLblCUSTNOEXISTS' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " SELECT 
  CUST_NO
FROM 
  Customer_Master
WHERE 
  Cust_No = :1 "
.head 11 -  Set sName = 'CstLblCUSTNOEXISTS'
.head 11 -  Set sBind = ':nCustNo'
.head 11 -  Set sInto = ':nGotCustNo'
.head 11 -  !
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Set nGotCustNo = NUMBER_Null
.head 11 -  !
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 -  ! Set nCount = nGotCount
.head 13 -  Return TRUE
.head 12 +  Else
.head 13 -  Return FALSE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 6 +  Window Variables
.head 7 -  Number: nCount
.head 7 -  Boolean: bExists
.head 7 -  String: sTmp
.head 7 -  ! Query hold fields
.head 7 -  String: sRootDesc
.head 7 -  String: sCultDesc
.head 7 -  String: sTreeTypeDesc
.head 7 -  Number: nItemNo
.head 7 -  Number: nYear
.head 7 -  String: sBusName
.head 7 -  String: sCustName
.head 7 -  Number: nCustNo
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set sSQLPopHandle = ' SELECT 
  CstLblation.User_Id, 
  CstLblation.Sys_Date_Time, 
  CstLblation.Stock_Item_No, 
  CstLblation.Year_Of_Sale,
  Stock_Item.Variety_Type, 
  @UPPER( Stock_Item.Variety ), 
  @UPPER( Stock_Item.Cult_Desc ), 
  @UPPER( Stock_Item.Root_Desc ), 
  Stock_Item.Tree_Type_Desc, 
  Stock_Item.Cult_Desc, 
  Stock_Item.Root_Desc, 
  CstLblation.Contract_Price, 
  CstLblation.Cust_No, 
  @UPPER( Customer_Master.Cust_Name ), 
  Customer_Master.Cust_Name 
FROM 
  CstLblation, 
  Customer_Master, 
  Stock_Item 
WHERE 
  CstLblation.Cust_No = Customer_Master.Cust_No AND 
  CstLblation.Stock_Item_No = Stock_Item.Item_No
ORDER BY 14,13,4,5,6,7,8,9 '
.head 8 -  Set sNAMEPopHandle = 'POPCstLblS'
.head 8 -  Set sBINDPopHandle = ''
.head 8 -  Set sINTOPopHandle = ':clsfrmCustLabels.tblCustLabels.colCstLblUserId, 
:clsfrmCustLabels.tblCustLabels.colCstLblSysDT, 
:clsfrmCustLabels.tblCustLabels.colCstLblItemNo, 
:clsfrmCustLabels.tblCustLabels.colCstLblYearOfSale, 
:clsfrmCustLabels.tblCustLabels.colVarietyType, 
:clsfrmCustLabels.tblCustLabels.colUpperVariety, 
:clsfrmCustLabels.tblCustLabels.colUpperCultDesc, 
:clsfrmCustLabels.tblCustLabels.colUpperRootDesc, 
:clsfrmCustLabels.tblCustLabels.colTreeTypeDesc, 
:clsfrmCustLabels.tblCustLabels.colCultDesc,
:clsfrmCustLabels.tblCustLabels.colRootDesc, 
:clsfrmCustLabels.tblCustLabels.colCstLblContPrice, 
:clsfrmCustLabels.tblCustLabels.colCstLblCustNo, 
:clsfrmCustLabels.tblCustLabels.colUpperCustName, 
:clsfrmCustLabels.tblCustLabels.colCustName'
.head 8 -  !
.head 8 -  Set sSQLRefreshHandle = ' SELECT 
  CstLblation.User_Id, 
  CstLblation.Sys_Date_Time, 
  CstLblation.Stock_Item_No, 
  CstLblation.Year_Of_Sale,
  Stock_Item.Variety_Type, 
  @UPPER( Stock_Item.Variety ), 
  @UPPER( Stock_Item.Cult_Desc ), 
  @UPPER( Stock_Item.Root_Desc ), 
  Stock_Item.Tree_Type_Desc, 
  Stock_Item.Cult_Desc, 
  Stock_Item.Root_Desc, 
  CstLblation.Contract_Price, 
  CstLblation.Cust_No, 
  @UPPER( Customer_Master.Cust_Name ), 
  Customer_Master.Cust_Name  
FROM 
  CstLblation, 
  Customer_Master, 
  Stock_Item 
WHERE 
  CstLblation.User_Id = :1 AND 
  CstLblation.Sys_Date_Time = :2 AND 
  CstLblation.Cust_No = Customer_Master.Cust_No AND 
  CstLblation.Stock_Item_No = Stock_Item.Item_No '
.head 8 -  Set sNAMERefreshHandle = 'REFCstLblS'
.head 8 -  Set sBINDRefreshHandle = ':clsfrmCustLabels.tblCustLabels.colCstLblUserId, :clsfrmCustLabels.tblCustLabels.colCstLblSysDT'
.head 8 -  Set sINTORefreshHandle = ':clsfrmCustLabels.tblCustLabels.colCstLblUserId, 
:clsfrmCustLabels.tblCustLabels.colCstLblSysDT, 
:clsfrmCustLabels.tblCustLabels.colCstLblItemNo, 
:clsfrmCustLabels.tblCustLabels.colCstLblYearOfSale, 
:clsfrmCustLabels.tblCustLabels.colVarietyType, 
:clsfrmCustLabels.tblCustLabels.colUpperVariety, 
:clsfrmCustLabels.tblCustLabels.colUpperCultDesc, 
:clsfrmCustLabels.tblCustLabels.colUpperRootDesc, 
:clsfrmCustLabels.tblCustLabels.colTreeTypeDesc, 
:clsfrmCustLabels.tblCustLabels.colCultDesc,
:clsfrmCustLabels.tblCustLabels.colRootDesc, 
:clsfrmCustLabels.tblCustLabels.colCstLblContPrice, 
:clsfrmCustLabels.tblCustLabels.colCstLblCustNo, 
:clsfrmCustLabels.tblCustLabels.colUpperCustName, 
:clsfrmCustLabels.tblCustLabels.colCustName'
.head 8 -  !
.head 8 -  Set sSQLInsertHandle = ' INSERT INTO CstLblation 
( 
  User_Id, 
  Sys_Date_Time, 
  Cust_No, 
  Stock_Item_No, 
  Year_Of_Sale,
  Contract_Price 
) VALUES ( :1, :2, :3, :4, :5, :6 ) '
.head 8 -  Set sNAMEInsertHandle = 'INSCstLblS'
.head 8 -  Set sBINDInsertHandle = ':clsfrmCustLabels.tblCustLabels.colCstLblUserId, 
:clsfrmCustLabels.tblCustLabels.colCstLblSysDT, 
:clsfrmCustLabels.tblCustLabels.colCstLblCustNo, 
:clsfrmCustLabels.tblCustLabels.colCstLblItemNo, 
:clsfrmCustLabels.tblCustLabels.colCstLblYearOfSale, 
:clsfrmCustLabels.tblCustLabels.colCstLblContPrice'
.head 8 -  Set sINTOInsertHandle = ''
.head 8 -  !
.head 8 -  Set sSQLUpdateHandle = ' UPDATE CstLblation 
SET 
  Cust_No = :3, 
  Stock_Item_No = :4, 
  Year_Of_Sale = :5,
  Contract_Price = :6
WHERE 
  CstLblation.User_Id = :1 AND 
  CstLblation.Sys_Date_Time = :2 '
.head 8 -  Set sNAMEUpdateHandle = 'UPDTCstLblS'
.head 8 -  Set sBINDUpdateHandle = ':clsfrmCustLabels.tblCustLabels.colCstLblUserId, 
:clsfrmCustLabels.tblCustLabels.colCstLblSysDT, 
:clsfrmCustLabels.tblCustLabels.colCstLblCustNo, 
:clsfrmCustLabels.tblCustLabels.colCstLblItemNo, 
:clsfrmCustLabels.tblCustLabels.colCstLblYearOfSale, 
:clsfrmCustLabels.tblCustLabels.colCstLblContPrice'
.head 8 -  Set sINTOUpdateHandle = ''
.head 8 -  !
.head 8 -  Set sSQLDeleteHandle = ' DELETE FROM CstLblation 
WHERE 
  CstLblation.User_Id = :1 AND 
  CstLblation.Sys_Date_Time = :2 '
.head 8 -  Set sNAMEDeleteHandle = 'DELCstLblS'
.head 8 -  Set sBINDDeleteHandle = ':clsfrmCustLabels.tblCustLabels.colCstLblUserId, :clsfrmCustLabels.tblCustLabels.colCstLblSysDT'
.head 8 -  !
.head 8 -  Set bAddAllowed = TRUE
.head 8 -  Set bSaveAllowed = TRUE
.head 8 -  Set bDeleteAllowed = TRUE
.head 8 -  Set bUnDeleteAllowed = TRUE
.head 8 -  Set bRepopulateAllowed = TRUE
.head 8 -  Set bClearSelectAllowed = TRUE
.head 8 -  Set bQueryAllowed = TRUE
.head 8 -  Set bReportAllowed = FALSE
.head 8 -  Set bOrderAllowed = TRUE
.head 8 -  !
.head 8 -  Set sQueryDialogName = 'dlgQCstLblations'
.head 8 -  !
.head 8 -  Set sRootDesc = ''
.head 8 -  Set sCultDesc = ''
.head 8 -  Set sTreeTypeDesc = ''
.head 8 -  Set nItemNo = NUMBER_Null
.head 8 -  Set nYear = NUMBER_Null
.head 8 -  Set sBusName = ''
.head 8 -  Set sCustName = ''
.head 8 -  Set nCustNo = NUMBER_Null
.head 7 +  On SAM_Destroy
.head 8 -  Call CheckYearItemExists( 0, 0, bExists, sTmp, SH_cls_Disconnect )
.head 8 -  Call CountSpecificCstLblas( 0, 0, 0, nCount, SH_cls_Disconnect )
.head 8 -  Call CustNoExists( 0, SH_cls_Disconnect)
.head 8 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 7 -  !
.head 7 +  On PAM_clsTBL_POPFIELDS
.head 8 -  Call PopString( sRootDesc, FALSE )
.head 8 -  Call PopString( sCultDesc, FALSE )
.head 8 -  Call PopString( sTreeTypeDesc, FALSE )
.head 8 -  Call PopNumber( nItemNo, FALSE )
.head 8 -  Call PopNumber( nYear, FALSE )
.head 8 -  Call PopString( sBusName, FALSE )
.head 8 -  Call PopString( sCustName, FALSE )
.head 8 -  Call PopNumber( nCustNo, FALSE )
.head 8 -  Return TRUE
.head 7 +  On PAM_clsTBL_PUSHFIELDS
.head 8 -  Call PushNumber( nCustNo )
.head 8 -  Call PushString( sCustName )
.head 8 -  Call PushString( sBusName )
.head 8 -  Call PushNumber( nYear )
.head 8 -  Call PushNumber( nItemNo )
.head 8 -  Call PushString( sTreeTypeDesc )
.head 8 -  Call PushString( sCultDesc )
.head 8 -  Call PushString( sRootDesc )
.head 8 -  Return TRUE
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 34
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 47
.head 6 -  Class ChildKey: 35
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 57545
.head 6 -  Class Child Ref Key: 48
.head 6 -  Class ChildKey: 36
.head 6 -  Class: clsFormChildTable
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 49
.head 6 -  Class ChildKey: 37
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  Set hWndChildTable = tblCustLabels
.head 6 -  Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 3 +  Dialog Box Class: clsdlgQCustLabels
.head 4 -  Title: Query Customer Customer Barcode Labels
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  7.188"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 3.823"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 39
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 16
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 3.338"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 17
.head 7 -  Class ChildKey: 7
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 5.863"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClear
.head 7 -  Class Child Ref Key: 19
.head 7 -  Class ChildKey: 38
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 20
.head 7 -  Class ChildKey: 39
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 12
.head 6 -  Class ChildKey: 1
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 13
.head 6 -  Class ChildKey: 2
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 14
.head 6 -  Class ChildKey: 3
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.075"
.head 8 -  Top: 0.01"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 +  Message Actions
.head 7 +  On PAM_clsSPN_VALIDATE
.head 8 -  Set dfYear = ccSeasonYear.GetSeasonYear( )
.head 8 -  Return TRUE
.head 5 -  Background Text:
.head 6 -  Resource Id: 23666
.head 6 -  Class Child Ref Key: 15
.head 6 -  Class ChildKey: 4
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Window Location and Size
.head 7 -  Left: 5.325"
.head 7 -  Top: 0.063"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 -  Background Text: Customer No.
.head 6 -  Resource Id: 23671
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.113"
.head 7 -  Top: 0.698"
.head 7 -  Width:  1.15"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Customer Name
.head 6 -  Resource Id: 23670
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 10
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.913"
.head 7 -  Top: 0.99"
.head 7 -  Width:  1.35"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Business Name
.head 6 -  Resource Id: 23668
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 11
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.9"
.head 7 -  Top: 1.282"
.head 7 -  Width:  1.363"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Data Field: dfCustNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 12
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Number
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.25"
.head 8 -  Top: 0.657"
.head 8 -  Width:  0.888"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: #0
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCustNo.sSQLCOLNAME = 'CstLblATION.CUST_NO'
.head 8 -  Set dfCustNo.hWndOperatorField = cmbCustNoOp
.head 8 -  Set dfCustNo.hWndNotField = cbNOTCustNo
.head 5 +  Data Field: dfCustName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 13
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.25"
.head 8 -  Top: 0.948"
.head 8 -  Width:  3.475"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCustName.sSQLCOLNAME = 'CUST_NAME'
.head 8 -  Set dfCustName.hWndOperatorField = cmbCustNameOp
.head 8 -  Set dfCustName.hWndNotField = cbNOTCustName
.head 8 -  Set dfCustName.bCompareUpCase = TRUE
.head 5 +  Data Field: dfBusName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 14
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.25"
.head 8 -  Top: 1.24"
.head 8 -  Width:  3.475"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfBusName.sSQLCOLNAME = 'BUS_NAME'
.head 8 -  Set dfBusName.hWndOperatorField = cmbBusNameOp
.head 8 -  Set dfBusName.hWndNotField = cbNOTBusName
.head 8 -  Set dfBusName.bCompareUpCase = TRUE
.head 5 +  Combo Box: cmbCustNoOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 15
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.338"
.head 7 -  Top: 0.657"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCustNoOp.hWndQueryField = dfCustNo
.head 8 -  Set cmbCustNoOp.sOperator = ' = '
.head 5 +  Combo Box: cmbCustNameOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 16
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.338"
.head 7 -  Top: 0.948"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCustNameOp.hWndQueryField = dfCustName
.head 8 -  Set cmbCustNameOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbBusNameOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 17
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.338"
.head 7 -  Top: 1.24"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbBusNameOp.hWndQueryField = dfBusName
.head 8 -  Set cmbBusNameOp.sOperator = ' LIKE '
.head 5 +  Check Box: cbNOTCustNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 18
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.338"
.head 7 -  Top: 0.657"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCustNo.hWndQueryField = dfCustNo
.head 5 +  Check Box: cbNOTCustName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 19
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.338"
.head 7 -  Top: 0.948"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCustName.hWndQueryField = dfCustName
.head 5 +  Check Box: cbNOTBusName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 20
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.338"
.head 7 -  Top: 1.24"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTBusName.hWndQueryField = dfBusName
.head 5 -  !
.head 5 +  Data Field: dfYear
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 21
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Number
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.25"
.head 8 -  Top: 0.626"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? No
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text: Tree Type Desc.
.head 6 -  Resource Id: 23667
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 22
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.925"
.head 7 -  Top: 1.844"
.head 7 -  Width:  1.338"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Cultivar Desc.
.head 6 -  Resource Id: 23665
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 36
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.013"
.head 7 -  Top: 2.094"
.head 7 -  Width:  1.25"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Rootstock Desc.
.head 6 -  Resource Id: 23669
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 37
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.913"
.head 7 -  Top: 2.406"
.head 7 -  Width:  1.35"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Data Field: lblItemNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 23
.head 6 -  Class: clslblGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 1.438"
.head 8 -  Top: 1.563"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set lblItemNo.sLabel = 'Item No.'
.head 7 +  On SAM_Create
.head 8 +  If NOT SqlUser = 'JAN'
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsDF_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  Data Field: dfItemNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 24
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Number
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.25"
.head 8 -  Top: 1.521"
.head 8 -  Width:  0.663"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: #0
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfItemNo.sSQLCOLNAME = 'CstLblATION.ITEM_NO'
.head 8 -  Set dfItemNo.hWndOperatorField = cmbItemNoOp
.head 8 -  Set dfItemNo.hWndNotField = cbNOTItemNo
.head 7 +  On SAM_Create
.head 8 +  If NOT SqlUser = 'JAN'
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsDF_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  Data Field: dfTreeTypeDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 25
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.25"
.head 8 -  Top: 1.802"
.head 8 -  Width:  3.475"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Uppercase
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfTreeTypeDesc.sSQLCOLNAME = 'TREE_TYPE_DESC'
.head 8 -  Set dfTreeTypeDesc.hWndOperatorField = cmbTreeTypeDescOp
.head 8 -  Set dfTreeTypeDesc.hWndNotField = cbNOTTreeTypeDesc
.head 8 -  Set dfTreeTypeDesc.nDefaultLikePercent = Q_PostLikePercent
.head 5 +  Data Field: dfCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 26
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.25"
.head 8 -  Top: 2.083"
.head 8 -  Width:  3.475"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCultDesc.sSQLCOLNAME = 'CULT_DESC'
.head 8 -  Set dfCultDesc.hWndOperatorField = cmbCultDescOp
.head 8 -  Set dfCultDesc.hWndNotField = cbNOTCultDesc
.head 8 -  Set dfCultDesc.bCompareUpCase = TRUE
.head 5 +  Data Field: dfRootDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 27
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 3.25"
.head 8 -  Top: 2.365"
.head 8 -  Width:  3.475"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfRootDesc.sSQLCOLNAME = 'ROOT_DESC'
.head 8 -  Set dfRootDesc.hWndOperatorField = cmbRootDescOp
.head 8 -  Set dfRootDesc.hWndNotField = cbNOTRootDesc
.head 8 -  Set dfRootDesc.bCompareUpCase = TRUE
.head 5 +  Combo Box: cmbItemNoOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 28
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.338"
.head 7 -  Top: 1.521"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbItemNoOp.hWndQueryField = dfItemNo
.head 8 -  Set cmbItemNoOp.sOperator = ' = '
.head 7 +  On SAM_Create
.head 8 +  If NOT SqlUser = 'JAN'
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsCMB_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  Combo Box: cmbTreeTypeDescOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 29
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.338"
.head 7 -  Top: 1.802"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbTreeTypeDescOp.hWndQueryField = dfTreeTypeDesc
.head 8 -  Set cmbTreeTypeDescOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbCultDescOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 30
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.338"
.head 7 -  Top: 2.083"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCultDescOp.hWndQueryField = dfCultDesc
.head 8 -  Set cmbCultDescOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbRootDescOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 31
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 2.338"
.head 7 -  Top: 2.365"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbRootDescOp.hWndQueryField = dfRootDesc
.head 8 -  Set cmbRootDescOp.sOperator = ' LIKE '
.head 5 +  Check Box: cbNOTItemNo
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 32
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.338"
.head 7 -  Top: 1.521"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTItemNo.hWndQueryField = dfItemNo
.head 7 +  On SAM_Create
.head 8 +  If NOT SqlUser = 'JAN'
.head 9 -  Call SalSendMsg( hWndItem, PAM_clsCB_HIDE, 0, 0 )
.head 8 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 5 +  Check Box: cbNOTTreeTypeDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 33
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.338"
.head 7 -  Top: 1.802"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTTreeTypeDesc.hWndQueryField = dfTreeTypeDesc
.head 5 +  Check Box: cbNOTCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 34
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.338"
.head 7 -  Top: 2.063"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCultDesc.hWndQueryField = dfCultDesc
.head 5 +  Check Box: cbNOTRootDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 35
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 0.338"
.head 7 -  Top: 2.354"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTRootDesc.hWndQueryField = dfRootDesc
.head 4 +  Derived From
.head 5 -  Class: clsTblQueryDialog
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set bMapEnterToTab = TRUE
.head 6 -  Set hWndFirstFocus = dfCustNo
.head 5 +  On PAM_clsDLG_POPFIELDS
.head 6 -  Call PopString( dfRootDesc, FALSE )
.head 6 -  Call PopString( dfCultDesc, FALSE )
.head 6 -  Call PopString( dfTreeTypeDesc, FALSE )
.head 6 -  Call PopNumber( dfItemNo, FALSE )
.head 6 -  Call PopNumber( dfYear, FALSE )
.head 6 -  Call PopString( dfBusName, FALSE )
.head 6 -  Call PopString( dfCustName, FALSE )
.head 6 -  Call PopNumber( dfCustNo, FALSE )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsDLG_PUSHFIELDS
.head 6 -  Call PushNumber( dfCustNo )
.head 6 -  Call PushString( dfCustName )
.head 6 -  Call PushString( dfBusName )
.head 6 -  Call PushNumber( dfYear )
.head 6 -  Call PushNumber( dfItemNo )
.head 6 -  Call PushString( dfTreeTypeDesc )
.head 6 -  Call PushString( dfCultDesc )
.head 6 -  Call PushString( dfRootDesc )
.head 6 -  Return TRUE
.head 3 -  !
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
