.head 0 +  Application Description: SQLWindows 5.01 Jans Cultivar Royalty Owners APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 4170705061746800 24006B3A5C63656E 747572615C636C61 73733B6B3A5C6365
0020: 6E747572615C666C 656D61706C730041 7070506174684C65 6E00040024000000
0040: 00557365476C6F62 616C506174680004 0001000000000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000DC0000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF160000 0016000000AA0200 0035010000010000 0000000000010000
0060: 000F4170706C6963 6174696F6E497465 6D0200000007436C 61737365730F636C
0080: 7366726D526F794F 776E657273
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000001000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1018B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: FRMCTBL.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: TABLE.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: STRINGS.APL
.head 2 -  File Include: METER.APL
.head 2 -  File Include: STACKS.APL
.head 2 -  File Include: VTMETER.APL
.head 2 -  File Include: FLAGS.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: CHECKBOX.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: GROUPBOX.APL
.head 2 -  File Include: QUERY.APL
.head 2 -  File Include: CMBFIELD.APL
.head 2 -  File Include: ROYOWNRD.APL
.head 2 -  File Include: PICK.APL
.head 2 -  File Include: ACTIVATE.APL
.head 2 -  File Include: OPATENTS.APL
.head 2 -  File Include: ITEMFUNC.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: VTWIN.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 3 -  Number: ###000
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for CULTROY.APL
.head 4 -  Number: CULTROYAplMsgOffSet = SAM_User + 3700
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: CULTROYAplConstOffSet = 1800
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 3383282870
0000: 200200007B010000 0000000000000000 0200001200000046 0100001019000000
0020: 016C01E049020000 0040730000000100 00A35F0100192500 016C5F04B8000000
0040: 73D1000100006878 0100190009016C3E 0700006E00730034 01000091015A0019
0060: 0001826CAA0B0000 001B730001008D00 AA0100961900016C E8AB0B0000467300
0080: 010000A3C3010019 2500016CAC0BBA00 0073D10001000068 DC0100190089016C
00A0: AD0B006E00730034 010000F5015A0019 0001826C040C0000 001B730001008D00
00C0: 0E0200961900016C E8050C0000467300 010000A327020019 2500016C060CBA00
00E0: 0073D10001000068 400200190089016C 070C006E00730034 010000590222003B
0100: 01000007006C0168 1001002E079A0073 00018C00005D0200 CE3B0007E86A1001
0120: 2E267300010000A3 6102003B3300076C 10BA012E73C90001 0000686502001900
0140: 01016C01591A0000 6E00730034010000 7E025A00190001A2 6C5A1A00001B7300
0160: 01008D0097020016 1900046C01E0871D 0000006673000100 A3B0020019250001
0180: 6CB333B800000073 D100010000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 3400158688
0000: 13160000A80D0000 0000000000000000 0200002400FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F08003C00 001263006C737062
0040: 43756C7400526F79 4F776E6572007340 0000000200001E00 0400008200021200
0060: 08000600F8007300 0060000100000004 B300040080031200 090000003DF80001
0080: 1B0001804F200000 000100001004636C 466F726D42006173 655461626C65607C
00A0: 00000004000F1900 0000710112000043 C602730000B40100 00195900190001C2
00C0: 120A0000001EC600 01000D0032000000 9619000112B00B00 0000C64700010000
00E0: 834B000000043500 020C00EC0000C6D9 0001000001805300 00000200E1000B63
0100: 6C3F9A00C0000005 0000005B190001DA 1208001008037300 0001006D00190096
0120: 04000212B6090008 67000100831D0000 001985000412000A ED0008D900010040
0140: 360000000400004D 030B00007B080036 01003A0058000019 0001DA120C001E08
0160: 0001000D00018019 0001000300000017 633E6C507220696E 7442616963005265
0180: 706F72742200D000 000100005B190001 DA12090018860373 0001008D00018019
01A0: 190004000C630A6C 7047656E6521616C 220000017A000019 4B00011207180000
01C0: 00D40373A3000100 0001018068000000 05C30009636C8148 656C709A00EC0005
01E0: 00AD0400026F00E0 8C03730001003600 0400194B00011208 DA0000E0A3000100
0200: 00CD1D0019920001 120900F600E06800 01000036B3001900 B401120A003DE000
0220: 019A00004F002C00 190001126D0B00E0 8F000100C6000180 1980000600000009
0240: 63074578697422A3 00010000B71900B4 0112070031F80373 00011A0000018004
0260: 32000007000C0750 696345784070616E 64220000F4010000 D604000237007004
0280: 6473000001006301 800400E608001207 546F67676C006542 7574746F6E22A200
02A0: 00010000B70400B6 020600317C047300 011B000180042300 0900000C87646647
02C0: 657F00F401000096 0400031237009A04 6673000100830180 3B0100860A001663
02E0: 6C7C476554CE6147 65478A0200157800 000019CB0001121B 00E20473A3000100
0300: 00CD190019D20001 1207F600E2680001 000032B3001900B4 011208003DE20001
0320: DA00004B2C001900 01126D0900E28F00 0100060064000000 046B00020ADB00E2
0340: B3000100C9680000 04DA00020BF600E2 6C0001006CB00000 000400A6020C0000
0360: 3DE200011B007000 00AC00040002610D 000000E2CF000106 0074000000046B00
0380: 020ED8000000E2B3 000100C178000000 041A00020F0000F6 00E26C0001007CB2
03A0: 0000040086021000 00003DE200015B00 80000C0004000102 12E1120000003F80
03C0: 01F8000000078400 0000194300010112 13F80000004F8001 00FE00C188000000
03E0: 1912000112140000 F600E26800010000 A1B0000000190084 0112160000003DE2
0400: 00011A0000BA0000 2C00190001126117 000000E28F000100 0600D3000000194B
0420: 00011218D8000000 E2A300010000C1EC 0000001912000112 1A0000F600E26800
0440: 01000005B4010019 008401121C000000 3DE200011A00001E 01002D190001126D
0460: 1D00E28F00010046 00370100046B0003 1ED8000000E2B300 01002101803A0000
0480: 0B43001D636C5400 626C4D616B655365 006C656374656452 6F00774B65794172
04A0: 7261C87984000004 DE00049800010205 00FE009380010000 7F04B3001900B401
04C0: 120600212A057300 00019A00001D002C 00190001126D0700 2A8F000100360036
04E0: 00046B000208DB00 2AB3000100210180 1D00000C63001063 43806F6C756D6E47
0500: 65476C400000F402 0000960400021236 05003C0546730001 00009B040019A500
0520: 011206ED003CD100 0100009801805300 0D3900104469C061 6C6F674765279A00
0540: 00057B00194B0001 1212190000C40773 A20000010000CD19 0004DA000213F600
0560: C46C0001001DB300 1900B4041214003D C40001DB0036A800 040000036D1500C4
0580: CF000136003A0019 4B00011216DB00C4 A300010000310180 1D000E63000C6363
05A0: FC62474640000200 006F190069011206 00433008730000B4 0100001959000400
05C0: 02DA1207009E3000 018D000180049900 0F000CE372624737 2200017A0000046B
05E0: 0002061B003C0873 B300010001018057 0000001042000011 636C540351756572
0600: 794416696FB80000 EC000600AD040003 6D13006C8C087300 010036000400046B
0620: 000214DB006CB300 0100CD080004DA00 0215F6006C6C0001 000CB200001900B4
0640: 011216003D6C0001 1A00002500002C00 190001126D17006C 8F00010006003E00
0660: 0000194B00011218 DB006CA300010000 0101809900000011 600000001163511E
0680: 7561746100466965 6C64740100ED0C00 AD0400026D060096 8C08730001003600
06A0: 0400046B000207DB 0096B3000100CD08 0004DA000208F600 966C0001000CB300
06C0: 0400B60209003D96 0001DB00102C0019 0001126D0A00968F 0001000600290000
06E0: 00194B0001120BDB 0096A300010000C1 4200000004D80001 020CFE0093800100
0700: 007F46B000000019 00B401120D003D96 00011A00005F0000 AC000400026D0E00
0720: 96CF000106006300 0000194B0001120F DB0096A300010000 CD7C0004DA000210
0740: F600966C00010080 B3001900A4011211 00003D9600011A00 0001809913001200
0760: 0012FE6380436F6D 626F4669BF0CBD00 04B50002068D00A8 0873D10001000066
0780: 040004006D020700 7BA800B601000859 00040002DB08009E A800016D000C00D6
07A0: 040002B60900A867 0001009B100019A5 0001120AED00A8D1 0001000066290019
07C0: 006901120B007BA8 00B4010000421900 04000102DB0C007F 80F20100006F4600
07E0: 9619000112B60D00 A847000100009B5F 0004B500020EED00 A8D9000100666300
0800: 19006901120F007B A800B40100007C59 00040002DB10009E A800016D00800096
0820: 19000112B61100A8 4700010000630180 9900E6130012FF03 436163686574B601
0840: 0C00B70400B60207 0031BA08730001DA 000004AC00040002 6D0800BACF000136
0860: 000800046B000209 DB00BAB3000100CD 0C0004DA00020AF6 00BA6C00010010B3
0880: 001900B401120B00 3DBA0001DA000029 2C00190001126D0C 00BA8F0001003600
08A0: 420004630001020D FB004F800100FE00 CD460019D2000112 0EF600BA68000100
08C0: 005FB3000400B602 0F003DBA0001DB00 632C00190001126D 1000BA8F00010036
08E0: 007C00046B000211 DB00BAB3000100CD 8000191200011212 0000F600BA680001
0900: 000001C880320000 14F00015636C034F 7065726174706F72 466940A200000200
0920: 00B71900B4011206 0031D808730001DA 0000192C00190001 126D0700D88F0001
0940: 00C6000180040800 15000013636C1F79 4342005965734E6F 466C618867220000
0960: 0100DE0004D20002 1206C600E408736C 00010001C8800800 001650000E636C70
0980: 52746F7977734700 0200006F04006902 1207004308097300 00B4010000045900
09A0: 040003D30800009C 080900010D000180 6400190017001463 4E6C536565034672
09C0: 6F6D546133657C00 047B00194B000112 071B00460A73A200 00010000CD190019
09E0: 920001120800F600 46680001000032B3 001900B401120900 3D460001DA00004B
0A00: 2C00190001126D0A 00468F000100C600 0180040C0018000D 636C595365634920
0A20: 6E746F220000017A 0000046B0003051B 005E0A73B3000100 3101800800196300
0A40: 126370794F775080 6174656E747340D1 000200005B040002 DA12070018760A73
0A60: 0001006D000400D6 040003B608007667 0001006301801900 C61A001163005370
0A80: 696E53656173006F 6E596561722200D1 000100005B190001 DA120600109C0B73
0AA0: 000001000D000180 460081001B000000 110B705374617200 7450726F6772616D
0AC0: 60D600000007006F 04007D020063F00B 7300B40100000459 00040002DB07009E
0AE0: F000016D000800D6 040002B60800F067 0001009B0C0019A5 00011209ED00F0D1
0B00: 0001000066250004 006D030A007BF000 B601002959000400 02DB0B009EF00001
0B20: 0D002D0000009619 000112B60C00F047 0001000003018052 000000861C000F63
0B40: 6CFC53748F300100 F60A009619000112 360500020C447300 000100009B190019
0B60: A500011206ED0002 D100010000663200 0400690212070073 020C00B601003659
0B80: 00040002DA120800 9C020C00016D003A 0096040002123609 00020C670001009B
0BA0: 3E0004A50002120A CD00020CD9000100 6642000400690212 0B0073020C003601
0BC0: 0046005900040002 DA120C009C020C00 010D004A00000096 04000212340D0000
0BE0: 020C67000100834E 0000000425000212 0E00CD00020CD900 010098018004001D
0C00: 31001063546F006F 6C54697057696E20 646F77220000017A 0000046B0003051B
0C20: 00740C73B3000100 31018004001E0300 0C63665461E74361 442200000100006F
0C40: 04006D03070063F8 0C73003601000180 00210000001F0000 00E00B6366436108
0C60: 506F6F66000000F4 0300000629000107 1200A30100F8009E 008001FC00009B04
0C80: 0004A5000312090D 00040D7300D90001 0066080019006901 120A007B04003401
0CA0: 0000018006190020 000000000C67774D 6F757365C0576865 656C22E800010000
0CC0: 2D19000112EF008D 73000100C6000180 1D88002100000D63 0153656E64456D61
0CE0: 30696C734000027A 0000194B00011205 1B00B80D73A30001 00008D19000400D2
0D00: 00021206F600B86C 0001000180808100 0000220080000863 514F456D83C00000
0D20: 0006BD0019A50001 12051D000E7300D1 0001000066190019 0049011208000077
0D40: 0E00B40100003259 00190001D2120B00 001D0E0001006D00 4B00961900011274
0D60: 0E00000E46730001 00009B6400192500 01121100DD000ED1 00010000607D0000
0D80: 0004004C01021400 00FFC9800100003F 0180060400230000 00080C636C6D6C47
0DA0: 65C565616C22E800 010000AD0400036D 05000CCC0E730001 0600
.enddata
.head 3 -  ! When changing the interface to clspbCultRoyOwners remember the application for this apl
.head 3 +  Pushbutton Class: clspbCultRoyOwners
.head 4 -  Title: Cult.Roy.
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\CVRTROY.BMP
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbPickInto
.head 4 +  Class Variables
.head 5 -  String: sTmp
.head 5 -  Window Handle: hWndTmp
.head 4 +  Instance Variables
.head 5 -  ! PUBLIC
.head 5 -  Window Handle: hWndPickIntoTable
.head 5 -  ! PRIVATE
.head 5 -  String: sCultId
.head 5 -  String: sCultDesc
.head 5 -  String: sManyCultIdsFile
.head 4 +  Functions
.head 5 +  Function: SetCultRoyOwnerFields
.head 6 -  Description: Null terminated arrays
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sNewCultId
.head 7 -  String: sNewCultDesc
.head 7 -  String: sNewManyCultIdsFile
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set sCultId = sNewCultId
.head 7 -  Set sCultDesc = sNewCultDesc
.head 7 -  Set sManyCultIdsFile = sNewManyCultIdsFile
.head 7 -  Return TRUE
.head 5 +  Function: GetCultRoyOwnerFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Receive String: sNewCultId
.head 7 -  Receive String: sNewCultDesc
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set sNewCultId = sCultId
.head 7 -  Set sNewCultDesc = sCultDesc
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set hWndPickIntoTable = hWndItem
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set clspbCultRoyOwners.nActivateWindowType = ACTIVATE_FormWindow
.head 6 -  Set clspbCultRoyOwners.sActivateDialogName = 'frmCultRoyOwners'
.head 6 -  Set clspbCultRoyOwners.hWndTable = hWndPickIntoTable
.head 6 -  Set clspbCultRoyOwners.hWndFieldLookUp = hWndItem
.head 5 +  On PAM_clsACTIVATE_PUSHFIELDS
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call PushString( sCultId )
.head 6 -  Call PushString( sCultDesc )
.head 6 -  Call PushString( sManyCultIdsFile )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsPICK_LOOKUP
.head 6 -  Call PopString( sCultDesc, TRUE )
.head 6 -  Call PopString( sCultId, TRUE )
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_GETFIELDS, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsACTIVATE_POPFIELDS
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Return TRUE
.head 3 +  Form Window Class: clsfrmCultRoyOwners
.head 4 -  Title: Cultivar Royalty Owners
.head 4 -  Icon File:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Automatically Created at Runtime? Class Default
.head 5 -  Initial State: Class Default
.head 5 -  Maximizable? Class Default
.head 5 -  Minimizable? Class Default
.head 5 -  Allow Child Docking? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  System Menu? Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 4.75"
.head 6 -  Height Editable? Class Default
.head 5 -  Form Size
.head 6 -  Width:  Class Default
.head 6 -  Height: Class Default
.head 6 -  Number of Pages: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Next Class Child Key: 44
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsFormChildTable
.head 4 -  Menu
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbAddRows
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 8
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbSaveRows
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 9
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 8
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbDeleteRows
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 11
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRePopulate
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 12
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbTools
.head 7 -  Class Child Ref Key: 23
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPickRoyOwners
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 20
.head 7 -  Class: clspbRoyOwners
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 8.113"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbPickRoyOwners.hWndPickIntoTable = tblCultRoyOwners
.head 9 -  ! Call SalSendClassMessage( PAM_cls_SETINSTANCEVARS, wParam, lParam )
.head 8 +  On PAM_cls_GETFIELDS
.head 9 -  Call pbPickRoyOwners.GetRoyOwnerFields( tblCultRoyOwners.colRoyOwnerId, sTmp )
.head 9 -  Return TRUE
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbPickRoyOwners.SetRoyOwnerFields( tblCultRoyOwners.colRoyOwnerId, '' )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 42
.head 7 -  Class ChildKey: 32
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 43
.head 7 -  Class ChildKey: 33
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 44
.head 7 -  Class ChildKey: 34
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 50
.head 7 -  Class ChildKey: 41
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClearRows
.head 7 -  Class Child Ref Key: 52
.head 7 -  Class ChildKey: 42
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDClose
.head 7 -  Class Child Ref Key: 54
.head 7 -  Class ChildKey: 43
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDRead
.head 7 -  Class Child Ref Key: 55
.head 7 -  Class ChildKey: 44
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Child Table: tblManyCultIds
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 38
.head 6 -  Class:
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: -0.025"
.head 8 -  Top: 0.406"
.head 8 -  Width:  9.713"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 4.167"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Black
.head 7 -  Background Color: Gray
.head 7 -  View: Table
.head 7 -  Allow Row Sizing? No
.head 7 -  Lines Per Row: Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Default
.head 7 -  Discardable? No
.head 6 +  Contents
.head 7 +  Column: colManyCultId
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 39
.head 8 -  Class:
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cult Id
.head 8 -  Visible? Yes
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Default
.head 8 -  Data Type: String
.head 8 -  Justify: Left
.head 8 -  Width:  Default
.head 8 -  Width Editable? Yes
.head 8 -  Format: Unformatted
.head 8 -  Country: Default
.head 8 -  Input Mask: Unformatted
.head 8 -  Cell Options
.head 9 -  Cell Type? Standard
.head 9 -  Multiline Cell? No
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Yes
.head 10 -  Vertical Scroll? Yes
.head 10 -  Auto Drop Down? No
.head 10 -  Allow Text Editing? Yes
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Yes
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colManyCultDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 40
.head 8 -  Class:
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cultivar Description
.head 8 -  Visible? Yes
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Default
.head 8 -  Data Type: String
.head 8 -  Justify: Left
.head 8 -  Width:  7.838"
.head 8 -  Width Editable? Yes
.head 8 -  Format: Unformatted
.head 8 -  Country: Default
.head 8 -  Input Mask: Unformatted
.head 8 -  Cell Options
.head 9 -  Cell Type? Standard
.head 9 -  Multiline Cell? No
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Yes
.head 10 -  Vertical Scroll? Yes
.head 10 -  Auto Drop Down? No
.head 10 -  Allow Text Editing? Yes
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Yes
.head 8 -  List Values
.head 8 -  Message Actions
.head 6 -  Functions
.head 6 +  Window Variables
.head 7 -  String: saCultIds[*]
.head 7 -  Number: nPos
.head 7 -  Number: nRow
.head 6 +  Message Actions
.head 7 +  On PAM_clsTBL_POPULATE
.head 8 +  If wParam = 1
.head 9 -  Set nRow = SalTblInsertRow( hWndForm, TBL_MaxRow ) 
.head 9 -  Call SalTblSetContext( hWndForm, nRow )
.head 9 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_HideMarks, TRUE )
.head 9 -  Set colManyCultId = sCultId
.head 9 -  Call ExtractCultivarDescription( colManyCultId, colManyCultDesc, SH_cls_Execute )
.head 8 +  Else
.head 9 -  Call ReadStrArrayListFromFile( sManyCultIdsFile, saCultIds )
.head 9 -  Set nPos = 0
.head 9 +  While saCultIds[ nPos ] != ''
.head 10 -  Set nRow = SalTblInsertRow( hWndForm, TBL_MaxRow ) 
.head 10 -  Call SalTblSetContext( hWndForm, nRow )
.head 10 -  Call SalTblSetRowFlags( hWndForm, nRow, ROW_HideMarks, TRUE )
.head 10 -  Set colManyCultId = saCultIds[ nPos ]
.head 10 -  Call ExtractCultivarDescription( colManyCultId, colManyCultDesc, SH_cls_Execute )
.head 10 -  Set nPos = nPos + 1
.head 8 -  Call SalTblSetContext( hWndForm, 0 )
.head 8 -  Call SalTblSetRowFlags( hWndForm, 0, ROW_Selected, TRUE )
.head 8 -  Set sCultId = colManyCultId
.head 8 -  Set sCultDesc = colManyCultDesc
.head 7 +  On SAM_Destroy
.head 8 -  Call ExtractCultivarDescription( '', colManyCultDesc, SH_cls_Disconnect )
.head 7 +  On SAM_RowValidate
.head 8 +  If SalSendMsg( hWndChildTable, PAM_clsTBL_CHECKCHANGES, 0, 0 )
.head 9 -  Call SalPostMsg( hWndForm, PAM_clsTBL_CHKCONTEXTROW, 0, 0 )
.head 9 -  Return VALIDATE_Ok
.head 8 +  Else
.head 9 -  Return VALIDATE_Cancel
.head 7 +  On PAM_clsTBL_CHKCONTEXTROW
.head 8 -  Set sCultId = colManyCultId
.head 8 -  Set sCultDesc = colManyCultDesc
.head 8 -  Call SalSendMsg( hWndChildTable, PAM_clsTBL_POPULATE, 0, 0 )
.head 8 -  Call SalSetFocus( hWndForm )
.head 8 -  Return VALIDATE_Ok
.head 5 -  !
.head 5 +  Child Table: tblCultRoyOwners
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 21
.head 6 -  Class: clsTableGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: -0.063"
.head 8 -  Top: 4.656"
.head 8 -  Width:  9.75"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 1.677"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colRoyOwnerId
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 22
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Owner Id
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.9"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Call ExistsOwnerCult( colRoyOwnerId, hWndForm.hWndParent.clsfrmCultRoyOwners.sCultId, bExists, SH_cls_Execute )
.head 10 +  If bExists
.head 11 -  Call ErrorMessage( 'This owner already owns this cultivar.  Please rectify.', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 7 +  Column: colRoyInstanceNo
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 23
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Owner Id
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.063"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 +  If GetNextRoyInstanceNo( colRoyOwnerId, colRoyInstanceNo, SH_cls_Execute )
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Call ErrorMessage( 'Error occured for this royalty instance. Please try again!', hWndForm, lParam )
.head 11 -  Return FALSE
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 +  If SalIsNull( colAmtPayable ) AND SalIsNull( colPercPayable )
.head 11 -  Call ErrorMessage( 'Please enter either Amount or Percentage payable first!', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Return TRUE
.head 7 +  Column: colRoyBusName
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 24
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Business Name
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  3.863"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colAmtPayable
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 25
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Amount
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Right
.head 8 -  Width:  0.963"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: ###000;###000
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPercPayable
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 27
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: % Payable
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Center
.head 8 -  Width:  0.95"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: ###000
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPayDueDate
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 26
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Due Date
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Date/Time
.head 8 -  Justify: Center
.head 8 -  Width:  1.175"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: dd-MMM-yyyy
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colCurrencyPayable
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 37
.head 8 -  Class: clsColDropListGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Currency
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.1"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Uppercase
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCurrencyPayable.sSqlPopStatement = 'SELECT DISTINCT Currency_Payable FROM Royalty_Payable'
.head 6 +  Functions
.head 7 +  Function: GetNextRoyInstanceNo
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  String: sOwnerId
.head 9 -  Receive Number: nNextInstanceNo
.head 9 -  Number: nActionType
.head 8 -  Static Variables
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nGotNextInstanceNo
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'GetNextRoyInstanceNo' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " SELECT MAX( Roy_Instance# ) + 1 
FROM Royalty_Payable   
WHERE Royalty_Owner_Id = :1 "
.head 11 -  Set sName = 'GTNXTROYINSTNO'
.head 11 -  Set sBind = ':sOwnerId'
.head 11 -  Set sInto = ':nGotNextInstanceNo'
.head 11 -  !
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Set nNextInstanceNo = NUMBER_Null
.head 11 -  Set nGotNextInstanceNo = NUMBER_Null
.head 11 -  !
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 -  Call haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 12 +  If nGotNextInstanceNo = NUMBER_Null
.head 13 -  Set nNextInstanceNo = 1
.head 12 +  Else
.head 13 -  Set nNextInstanceNo = nGotNextInstanceNo
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 7 +  Function: ExistsOwnerCult
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  String: sOwnerId
.head 9 -  String: sCultId
.head 9 -  Receive Boolean: bExists
.head 9 -  Number: nActionType
.head 8 -  Static Variables
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'ExistsOwnerCult' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " SELECT 
  Roy_Instance# 
FROM 
  Royalty_Payable   
WHERE 
  Royalty_Owner_Id = :1 AND 
  Cultivar_Id = :2 "
.head 11 -  Set sName = 'XSTOWRCLT2'
.head 11 -  Set sBind = ':sOwnerId, :sCultId'
.head 11 -  Set sInto = ''
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Set bExists = FALSE
.head 11 -  !
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 -  Set bExists = TRUE
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 6 +  Window Variables
.head 7 -  String: saHistoryNewRoyOwnerId[*]
.head 7 -  String: saHistoryNewRoyBusName[*]
.head 7 -  Number: naHistoryNewAmtPayable[*]
.head 7 -  Number: naHistoryNewPercPayable[*]
.head 7 -  Date/Time: dtaHistoryNewPayDueDate[*]
.head 7 -  String: saHistoryNewCurrencyPayable[*]
.head 7 -  !
.head 7 -  Number: nPos
.head 7 -  Boolean: bExists
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set nPos = 0
.head 8 -  Set saHistoryNewRoyOwnerId[ nPos ] = 'FNA'
.head 8 -  Set saHistoryNewRoyBusName[ nPos ] = ''
.head 8 -  Set naHistoryNewAmtPayable[ nPos ] = NUMBER_Null
.head 8 -  Set naHistoryNewPercPayable[ nPos ] = NUMBER_Null
.head 8 -  Set dtaHistoryNewPayDueDate[ nPos ] = DATETIME_Null
.head 8 -  Set saHistoryNewCurrencyPayable[ nPos ] = 'AUS $'
.head 8 -  Set nPos = nPos + 1
.head 8 -  Set saHistoryNewRoyOwnerId[ nPos ] = 'FMN'
.head 8 -  Set saHistoryNewRoyBusName[ nPos ] = ''
.head 8 -  Set naHistoryNewAmtPayable[ nPos ] = NUMBER_Null
.head 8 -  Set naHistoryNewPercPayable[ nPos ] = NUMBER_Null
.head 8 -  Set dtaHistoryNewPayDueDate[ nPos ] = DATETIME_Null
.head 8 -  Set saHistoryNewCurrencyPayable[ nPos ] = 'AUS $'
.head 8 -  Set nPos = nPos + 1
.head 8 -  Set saHistoryNewRoyOwnerId[ nPos ] = ''
.head 8 -  Set saHistoryNewRoyBusName[ nPos ] = ''
.head 8 -  Set naHistoryNewAmtPayable[ nPos ] = NUMBER_Null
.head 8 -  Set naHistoryNewPercPayable[ nPos ] = NUMBER_Null
.head 8 -  Set dtaHistoryNewPayDueDate[ nPos ] = DATETIME_Null
.head 8 -  Set saHistoryNewCurrencyPayable[ nPos ] = ''
.head 8 -  !
.head 8 -  Set sSQLPopHandle = ' SELECT 
  Royalty_Payable.Royalty_Owner_Id, 
  Royalty_Payable.Roy_Instance#, 
  Royalty_Owner.Roy_Bus_Name, 
  Royalty_Payable.Amount_Payable, 
  Royalty_Payable.Percentage_Payable, 
  Royalty_Payable.Payment_Due_Date, 
  Royalty_Payable.Currency_Payable 
FROM 
  Royalty_Payable, 
  Royalty_Owner
WHERE 
  Royalty_Payable.Cultivar_Id = :1 AND 
  Royalty_Payable.Royalty_Owner_Id = Royalty_Owner.Royalty_Owner_Id 
ORDER BY 
  Royalty_Payable.Roy_Instance# '
.head 8 -  Set sNAMEPopHandle = 'CULTROYOWN'
.head 8 -  Set sBINDPopHandle = ':hWndParent.clsfrmCultRoyOwners.sCultId'
.head 8 -  Set sINTOPopHandle = ':clsfrmCultRoyOwners.tblCultRoyOwners.colRoyOwnerId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colRoyInstanceNo, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colRoyBusName, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colAmtPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPercPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPayDueDate, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colCurrencyPayable'
.head 8 -  !
.head 8 -  Set sSQLRefreshHandle = ' SELECT 
  Royalty_Owner.Roy_Bus_Name, 
  Royalty_Payable.Amount_Payable, 
  Royalty_Payable.Percentage_Payable, 
  Royalty_Payable.Payment_Due_Date, 
  Royalty_Payable.Currency_Payable 
FROM 
  Royalty_Payable, 
  Royalty_Owner
WHERE 
  Royalty_Payable.Cultivar_Id = :1 AND 
  Royalty_Payable.Royalty_Owner_Id = :2 AND 
  Royalty_Payable.Roy_Instance# = :3 AND 
  Royalty_Payable.Royalty_Owner_Id = Royalty_Owner.Royalty_Owner_Id '
.head 8 -  Set sNAMERefreshHandle = 'REFCVROYOWN'
.head 8 -  Set sBINDRefreshHandle = ':hWndParent.clsfrmCultRoyOwners.sCultId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colRoyOwnerId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colRoyInstanceNo'
.head 8 -  Set sINTORefreshHandle = ':clsfrmCultRoyOwners.tblCultRoyOwners.colRoyBusName, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colAmtPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPercPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPayDueDate, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colCurrencyPayable'
.head 8 -  !
.head 8 -  Set sSQLInsertHandle = 'INSERT INTO Royalty_Payable 
( 
  Royalty_Owner_Id, 
  Roy_Instance#, 
  Cultivar_Id, 
  Amount_Payable, 
  Percentage_Payable, 
  Payment_Due_Date, 
  Currency_Payable 
) VALUES ( :1, :2, :3, :4, :5, :6, :7 ) '
.head 8 -  Set sNAMEInsertHandle = 'INSCVROYOWNR'
.head 8 -  Set sBINDInsertHandle = ':clsfrmCultRoyOwners.tblCultRoyOwners.colRoyOwnerId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colRoyInstanceNo, 
:hWndParent.clsfrmCultRoyOwners.sCultId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colAmtPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPercPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPayDueDate, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colCurrencyPayable'
.head 8 -  Set sINTOInsertHandle = ''
.head 8 -  !
.head 8 -  Set sSQLUpdateHandle = 'UPDATE Royalty_Payable 
SET 
   Amount_Payable = :4, 
   Percentage_Payable = :5, 
   Payment_Due_Date = :6, 
   Currency_Payable = :7 
WHERE 
  Royalty_Payable.Royalty_Owner_Id = :1 AND 
  Royalty_Payable.Roy_Instance# = :2 AND 
  Royalty_Payable.Cultivar_Id = :3 ' 
.head 8 -  Set sNAMEUpdateHandle = 'UPDTCVROYOWNR'
.head 8 -  Set sBINDUpdateHandle = ':clsfrmCultRoyOwners.tblCultRoyOwners.colRoyOwnerId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colRoyInstanceNo, 
:hWndParent.clsfrmCultRoyOwners.sCultId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colAmtPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPercPayable, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colPayDueDate, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colCurrencyPayable'
.head 8 -  Set sINTOUpdateHandle = ''
.head 8 -  !
.head 8 -  Set sSQLDeleteHandle = 'DELETE FROM Royalty_Payable 
WHERE 
  Royalty_Payable.Royalty_Owner_Id = :1 AND 
  Royalty_Payable.Roy_Instance# = :2 AND 
  Royalty_Payable.Cultivar_Id = :3 '
.head 8 -  Set sNAMEDeleteHandle = 'DELCVROYOWNR'
.head 8 -  Set sBINDDeleteHandle = ':clsfrmCultRoyOwners.tblCultRoyOwners.colRoyOwnerId, 
:clsfrmCultRoyOwners.tblCultRoyOwners.colRoyInstanceNo, 
:hWndParent.clsfrmCultRoyOwners.sCultId'
.head 8 -  Set sINTODeleteHandle = ''
.head 8 -  !
.head 8 -  Set bAddAllowed = TRUE
.head 8 -  Set bSaveAllowed = TRUE
.head 8 -  Set bDeleteAllowed = TRUE
.head 8 -  Set bUnDeleteAllowed = TRUE
.head 8 -  Set bRepopulateAllowed = TRUE
.head 8 -  Set bClearSelectAllowed = TRUE
.head 8 -  Set bQueryAllowed = TRUE
.head 8 -  Set bReportAllowed = FALSE
.head 8 -  Set bOrderAllowed = TRUE
.head 8 -  !
.head 8 -  Set sQueryDialogName = 'dlgQueryCultRoyOwners'
.head 7 +  On PAM_clsTBL_ADDROW
.head 8 -  Set nPos = 0
.head 8 +  While saHistoryNewRoyOwnerId[ nPos ] != ''
.head 9 -  Call SalSendClassMessage( PAM_clsTBL_ADDROW, wParam, lParam )
.head 9 -  Set colRoyOwnerId = saHistoryNewRoyOwnerId[ nPos ]
.head 9 -  Set colRoyBusName = saHistoryNewRoyBusName[ nPos ]
.head 9 -  Set colAmtPayable = naHistoryNewAmtPayable[ nPos ]
.head 9 -  Set colPercPayable = naHistoryNewPercPayable[ nPos ]
.head 9 -  Set colPayDueDate = dtaHistoryNewPayDueDate[ nPos ]
.head 9 -  Set colCurrencyPayable = saHistoryNewCurrencyPayable[ nPos ]
.head 9 -  !
.head 9 -  Set nPos = nPos + 1
.head 8 -  Return TRUE
.head 7 +  On PAM_clsTBL_SAVECHANGES
.head 8 -  Set nPos = 0
.head 8 -  Return SalSendClassMessage( PAM_clsTBL_SAVECHANGES, wParam, lParam )
.head 7 +  On PAM_clsTBL_SAVEROWNEW
.head 8 -  Set saHistoryNewRoyOwnerId[ nPos ] = colRoyOwnerId
.head 8 -  Set saHistoryNewRoyBusName[ nPos ] = colRoyBusName
.head 8 -  Set naHistoryNewAmtPayable[ nPos ] = colAmtPayable
.head 8 -  Set naHistoryNewPercPayable[ nPos ] = colPercPayable
.head 8 -  Set dtaHistoryNewPayDueDate[ nPos ] = colPayDueDate
.head 8 -  Set saHistoryNewCurrencyPayable[ nPos ] = colCurrencyPayable
.head 8 -  Set nPos = nPos + 1
.head 8 -  Set saHistoryNewRoyOwnerId[ nPos ] = ''
.head 8 -  Set saHistoryNewRoyBusName[ nPos ] = ''
.head 8 -  Set naHistoryNewAmtPayable[ nPos ] = NUMBER_Null
.head 8 -  Set naHistoryNewPercPayable[ nPos ] = NUMBER_Null
.head 8 -  Set dtaHistoryNewPayDueDate[ nPos ] = DATETIME_Null
.head 8 -  Set saHistoryNewCurrencyPayable[ nPos ] = ''
.head 8 -  !
.head 8 -  Return SalSendClassMessage( PAM_clsTBL_SAVEROWNEW, wParam, lParam )
.head 7 +  On PAM_clsTBL_NOROWS
.head 8 -  Return TRUE
.head 7 +  On SAM_Destroy
.head 8 -  Call GetNextRoyInstanceNo( '', colRoyInstanceNo, SH_cls_Disconnect )
.head 8 -  Call ExistsOwnerCult( colRoyOwnerId, sCultId, bExists, SH_cls_Execute )
.head 8 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 28
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 47
.head 6 -  Class ChildKey: 29
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 3793
.head 6 -  Class Child Ref Key: 48
.head 6 -  Class ChildKey: 30
.head 6 -  Class: clsFormChildTable
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 49
.head 6 -  Class ChildKey: 31
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  String: sManyCultIdsFile
.head 5 -  String: sCultId
.head 5 -  String: sCultDesc
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  Set hWndChildTable = tblCultRoyOwners
.head 6 -  ! Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 5 +  On PAM_clsFRM_POPFIELDS
.head 6 -  Call PopString( sManyCultIdsFile, TRUE )
.head 6 -  Call PopString( sCultDesc, TRUE )
.head 6 -  Call PopString( sCultId, TRUE )
.head 6 -  Return TRUE
.head 5 +  On SAM_CreateComplete
.head 6 +  If SalStrScan( sManyCultIdsFile, 'cultids.tmp' ) < 0
.head 7 -  Call SalSendMsg( tblManyCultIds, PAM_clsTBL_POPULATE, 1, 0 )
.head 6 +  Else
.head 7 -  Call SalSendMsg( tblManyCultIds, PAM_clsTBL_POPULATE, 0, 0 )
.head 6 -  Call SalSendClassMessage( SAM_CreateComplete, wParam, lParam )
.head 6 -  Call SalSetFocus( tblManyCultIds )
.head 3 +  Dialog Box Class: clsdlgQueryCultRoyOwners
.head 4 -  Title: Query Cultivar Royalty Owners
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  7.975"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 3.49"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 32
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 16
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 3.763"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 17
.head 7 -  Class ChildKey: 7
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.65"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClear
.head 7 -  Class Child Ref Key: 19
.head 7 -  Class ChildKey: 31
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 20
.head 7 -  Class ChildKey: 32
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 12
.head 6 -  Class ChildKey: 1
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 13
.head 6 -  Class ChildKey: 2
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 14
.head 6 -  Class ChildKey: 3
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.863"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 22799
.head 6 -  Class Child Ref Key: 15
.head 6 -  Class ChildKey: 4
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Window Location and Size
.head 7 -  Left: 6.113"
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 -  Background Text: Cultivar Id
.head 6 -  Resource Id: 22801
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.175"
.head 7 -  Top: 0.677"
.head 7 -  Width:  0.913"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Cultivar Description
.head 6 -  Resource Id: 22803
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 10
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.425"
.head 7 -  Top: 0.959"
.head 7 -  Width:  1.663"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Variety
.head 6 -  Resource Id: 22800
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 11
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.475"
.head 7 -  Top: 1.24"
.head 7 -  Width:  0.613"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Variety Type
.head 6 -  Resource Id: 22802
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 12
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.063"
.head 7 -  Top: 1.521"
.head 7 -  Width:  1.025"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 +  Data Field: dfCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 13
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.05"
.head 8 -  Top: 0.636"
.head 8 -  Width:  0.963"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Uppercase
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCultId.sSQLCOLNAME = 'CULTIVAR.CULT_ID'
.head 8 -  Set dfCultId.hWndOperatorField = cmbCultIdOp
.head 8 -  Set dfCultId.hWndNotField = cbNOTCultId
.head 5 +  Data Field: dfCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 14
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.05"
.head 8 -  Top: 0.917"
.head 8 -  Width:  3.4"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Unformatted
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCultDesc.sSQLCOLNAME = 'CULTIVAR.CULT_DESC'
.head 8 -  Set dfCultDesc.hWndOperatorField = cmbCultDescOp
.head 8 -  Set dfCultDesc.hWndNotField = cbNOTCultDesc
.head 8 -  Set dfCultDesc.sOperator = ' LIKE '
.head 8 -  Set dfCultDesc.bCompareUpCase = TRUE
.head 5 +  Data Field: dfVariety
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 15
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.05"
.head 8 -  Top: 1.198"
.head 8 -  Width:  3.4"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Class Default
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfVariety.sSQLCOLNAME = 'CULTIVAR.VARIETY'
.head 8 -  Set dfVariety.hWndOperatorField = cmbVarietyOp
.head 8 -  Set dfVariety.hWndNotField = cbNOTVariety
.head 8 -  Set dfVariety.sOperator = ' LIKE '
.head 8 -  Set dfVariety.bCompareUpCase = TRUE
.head 5 +  Combo Box: cmbVarietyType
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 16
.head 6 -  Class: clsQueryComboField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 4.05"
.head 7 -  Top: 1.48"
.head 7 -  Width:  0.525"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: 0.594"
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Editable? No
.head 6 -  String Type: Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Sorted? Class Default
.head 6 -  Always Show List? Class Default
.head 6 -  Vertical Scroll? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Input Mask: Class Default
.head 6 +  List Initialization
.head 7 -  Text: F
.head 7 -  Text: O
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbVarietyType.sSQLCOLNAME = 'CULTIVAR.VARIETY_TYPE'
.head 8 -  Set cmbVarietyType.hWndOperatorField = cmbVarietyTypeOp
.head 8 -  Set cmbVarietyType.hWndNotField = cbNOTVarietyType
.head 8 -  Set cmbVarietyType.bUsedInQueryDialog = TRUE
.head 5 +  Check Box: cbVFree
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 17
.head 6 -  Class: clsQueryCBYesNoFlag
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Virus Free Flag
.head 6 -  Window Location and Size
.head 7 -  Left: 4.05"
.head 7 -  Top: 1.782"
.head 7 -  Width:  1.525"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbVFree.sSQLCOLNAME = 'CULTIVAR.CV_VFREE_FLAG'
.head 8 -  Set cbVFree.hWndNotField = cbNOTVFree
.head 5 +  Check Box: cbNPA
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 18
.head 6 -  Class: clsQueryCBYesNoFlag
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Non Prop. Flag
.head 6 -  Window Location and Size
.head 7 -  Left: 4.05"
.head 7 -  Top: 2.052"
.head 7 -  Width:  1.5"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNPA.sSQLCOLNAME = 'CULTIVAR.CV_NON_PROP_FLAG'
.head 8 -  Set cbNPA.hWndNotField = cbNOTNPA
.head 5 +  Check Box: cbNotSale
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 19
.head 6 -  Class: clsQueryCBYesNoFlag
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Not for Sale Flag
.head 6 -  Window Location and Size
.head 7 -  Left: 4.05"
.head 7 -  Top: 2.323"
.head 7 -  Width:  1.625"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNotSale.sSQLCOLNAME = 'CULTIVAR.CV_NOT_SALE_FLAG'
.head 8 -  Set cbNotSale.hWndNotField = cbNOTNotSale
.head 5 -  !
.head 5 +  Check Box: cbNOTCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 20
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 0.85"
.head 7 -  Top: 0.636"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCultId.hWndQueryField = dfCultId
.head 5 +  Check Box: cbNOTCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 21
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 0.85"
.head 7 -  Top: 0.917"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCultDesc.hWndQueryField = dfCultDesc
.head 5 +  Check Box: cbNOTVariety
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 22
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 0.85"
.head 7 -  Top: 1.198"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTVariety.hWndQueryField = dfVariety
.head 5 +  Check Box: cbNOTVarietyType
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 23
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 0.85"
.head 7 -  Top: 1.48"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTVarietyType.hWndQueryField = cmbVarietyType
.head 5 +  Check Box: cbNOTVFree
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 24
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 3.463"
.head 7 -  Top: 1.782"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTVFree.hWndQueryField = cbVFree
.head 5 +  Check Box: cbNOTNPA
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 25
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 3.463"
.head 7 -  Top: 2.052"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTNPA.hWndQueryField = cbNPA
.head 5 +  Check Box: cbNOTNotSale
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 26
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.463"
.head 7 -  Top: 2.323"
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTNotSale.hWndQueryField = cbNotSale
.head 5 -  !
.head 5 +  Combo Box: cmbCultIdOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 27
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.138"
.head 7 -  Top: 0.636"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCultIdOp.hWndQueryField = dfCultId
.head 8 -  Set cmbCultIdOp.sOperator = ' = '
.head 5 +  Combo Box: cmbCultDescOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 28
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.138"
.head 7 -  Top: 0.917"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCultDescOp.hWndQueryField = dfCultDesc
.head 8 -  Set cmbCultDescOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbVarietyOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 29
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.138"
.head 7 -  Top: 1.198"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbVarietyOp.hWndQueryField = dfVariety
.head 8 -  Set cmbVarietyOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbVarietyTypeOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 30
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.138"
.head 7 -  Top: 1.48"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbVarietyTypeOp.hWndQueryField = cmbVarietyType
.head 8 -  Set cmbVarietyTypeOp.sOperator = ' LIKE '
.head 5 -  !
.head 4 +  Derived From
.head 5 -  Class: clsTblQueryDialog
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bMapEnterToTab = TRUE
.head 6 -  Set hWndFirstFocus = dfCultDesc
.head 3 -  !
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  ! clsfrmCultRoyOwners: frmCultRoyOwners
.winattr class Form Window:
.head 2 -  Class: clsfrmCultRoyOwners
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Cultivar Royalty Owners
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Yes
.head 2 -  Visible? Yes
.head 2 -  Display Settings
.head 3 -  Display Style? Default
.head 3 -  Visible at Design time? Yes
.head 3 -  Automatically Created at Runtime? No
.head 3 -  Initial State: Normal
.head 3 -  Maximizable? Yes
.head 3 -  Minimizable? Yes
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Yes
.head 3 -  Resizable? Yes
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  9.988"
.head 4 -  Width Editable? Yes
.head 4 -  Height: 5.948"
.head 4 -  Height Editable? Yes
.head 3 -  Form Size
.head 4 -  Width:  Default
.head 4 -  Height: Default
.head 4 -  Number of Pages: Dynamic
.head 3 -  Font Name: Default
.head 3 -  Font Size: Default
.head 3 -  Font Enhancement: Default
.head 3 -  Text Color: Default
.head 3 -  Background Color: Default
.end
.head 2 -  Description: 
.head 2 -  Named Menus 
.head 2 -  Menu 
.head 2 +  Tool Bar 
.winattr
.head 3 -  Display Settings
.head 4 -  Display Style? Default
.head 4 -  Location? Top
.head 4 -  Visible? Yes
.head 4 -  Size: Default
.head 4 -  Size Editable? Yes
.head 4 -  Docking Toolbar? No
.head 4 -  Toolbar Docking Orientation: Top | Bottom
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.head 4 -  Resizable? No
.end
.head 3 +  Contents 
.head 4 +  Pushbutton: pbClearRows
.winattr
.head 5 -  Class Child Ref Key: 7
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Clear F3
.head 5 -  Window Location and Size
.head 6 -  Left: 1.8"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: F3
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\MAINT.ICO
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbAddRows
.winattr
.head 5 -  Class Child Ref Key: 8
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Add F6
.head 5 -  Window Location and Size
.head 6 -  Left: 2.4"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: F6
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\FMTSTR.ICO
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbSaveRows
.winattr
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Save F5
.head 5 -  Window Location and Size
.head 6 -  Left: 3.113"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: F5
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\DISK.BMP
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbQuery
.winattr
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Query F7
.head 5 -  Window Location and Size
.head 6 -  Left: 4.525"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: F7
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\QUERY.BMP
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbDeleteRows
.winattr
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Del F4
.head 5 -  Window Location and Size
.head 6 -  Left: 3.825"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: F4
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\DELREC.BMP
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbRePopulate
.winattr
.head 5 -  Class Child Ref Key: 12
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Repop
.head 5 -  Window Location and Size
.head 6 -  Left: 5.2"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: (none)
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\STYLE.ICO
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbTools
.winattr
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Tools
.head 5 -  Window Location and Size
.head 6 -  Left: 5.8"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: (none)
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\TOOLS.BMP
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPickRoyOwners
.winattr
.head 5 -  Class Child Ref Key: 20
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: R.Ownr
.head 5 -  Window Location and Size
.head 6 -  Left: 8.113"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: (none)
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\ROYOWNR.BMP
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbHelp
.winattr
.head 5 -  Class Child Ref Key: 32
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Help F1
.head 5 -  Window Location and Size
.head 6 -  Left: 0.0"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: F1
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\HELP2.BMP
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbItemEnq
.winattr
.head 5 -  Class Child Ref Key: 33
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Enq
.head 5 -  Window Location and Size
.head 6 -  Left: 0.6"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: (none)
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\ENQUIRE.BMP
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrintForm
.winattr
.head 5 -  Class Child Ref Key: 34
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Print
.head 5 -  Window Location and Size
.head 6 -  Left: 8.713"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: (none)
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\PRINT.ICO
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbExit
.winattr
.head 5 -  Class Child Ref Key: 35
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title: Exit Esc
.head 5 -  Window Location and Size
.head 6 -  Left: 9.313"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.58"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: Esc
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Bold
.head 5 -  Picture File Name: C:\CENTURA\ICONS\CLOSE.ICO
.head 5 -  Picture Transparent Color: None
.head 5 -  Image Style: Single
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  Button Appearance: Standard
.end
.head 5 -  Message Actions 
.head 2 +  Contents 
.head 3 +  Child Table: tblCultRoyOwners
.winattr
.head 4 -  Class Child Ref Key: 21
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.038"
.head 6 -  Top: 1.479"
.head 6 -  Width:  9.738"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 3.104"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Dark Blue
.head 5 -  Background Color: Default
.head 5 -  View: Table
.head 5 -  Allow Row Sizing? No
.head 5 -  Lines Per Row: Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Default
.head 5 -  Discardable? Yes
.end
.head 4 +  Contents 
.head 5 +  Column: colRoyOwnerId
.winattr
.head 6 -  Class Child Ref Key: 22
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Owner Id
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: String
.head 6 -  Justify: Left
.head 6 -  Width:  0.9"
.head 6 -  Width Editable? Yes
.head 6 -  Format: Unformatted
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colRoyInstanceNo
.winattr
.head 6 -  Class Child Ref Key: 23
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Owner Id
.head 6 -  Visible? No
.head 6 -  Editable? Yes
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Left
.head 6 -  Width:  1.063"
.head 6 -  Width Editable? Yes
.head 6 -  Format: Unformatted
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colRoyBusName
.winattr
.head 6 -  Class Child Ref Key: 24
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Business Name
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: String
.head 6 -  Justify: Left
.head 6 -  Width:  3.863"
.head 6 -  Width Editable? Yes
.head 6 -  Format: Unformatted
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colAmtPayable
.winattr
.head 6 -  Class Child Ref Key: 25
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Amount
.head 6 -  Visible? Yes
.head 6 -  Editable? Yes
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Right
.head 6 -  Width:  0.963"
.head 6 -  Width Editable? Yes
.head 6 -  Format: ###000;###000
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colPercPayable
.winattr
.head 6 -  Class Child Ref Key: 27
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: % Payable
.head 6 -  Visible? Yes
.head 6 -  Editable? Yes
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: Number
.head 6 -  Justify: Center
.head 6 -  Width:  0.95"
.head 6 -  Width Editable? Yes
.head 6 -  Format: #0
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colPayDueDate
.winattr
.head 6 -  Class Child Ref Key: 26
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Due Date
.head 6 -  Visible? Yes
.head 6 -  Editable? Yes
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: Date/Time
.head 6 -  Justify: Center
.head 6 -  Width:  1.175"
.head 6 -  Width Editable? Yes
.head 6 -  Format: dd-MMM-yyyy
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: col8
.winattr
.head 6 -  Class Child Ref Key: 37
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Currency
.head 6 -  Visible? Yes
.head 6 -  Editable? Yes
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: String
.head 6 -  Justify: Left
.head 6 -  Width:  1.1"
.head 6 -  Width Editable? Yes
.head 6 -  Format: Uppercase
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Drop Down List
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 4 -  Functions 
.head 4 -  Window Variables 
.head 4 -  Message Actions 
.head 3 +  Data Field: dfDatabase
.winattr
.head 4 -  Class Child Ref Key: 28
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: String
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.025"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.875"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? No
.head 5 -  Justify: Left
.head 5 -  Format: Unformatted
.head 5 -  Country: Default
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Magenta
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Unformatted
.end
.head 4 -  Message Actions 
.head 3 +  Data Field: dfUser
.winattr
.head 4 -  Class Child Ref Key: 29
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Default
.head 5 -  Data Type: String
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.925"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.875"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.25"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? No
.head 5 -  Justify: Left
.head 5 -  Format: Unformatted
.head 5 -  Country: Default
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 8
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Magenta
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Unformatted
.end
.head 4 -  Message Actions 
.head 3 -  Background Text: Season
.winattr
.head 4 -  Class Child Ref Key: 30
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Window Location and Size
.head 5 -  Left: 8.2"
.head 5 -  Top: 0.052"
.head 5 -  Width:  0.663"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.167"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Justify: Right
.head 4 -  Font Name: Default
.head 4 -  Font Size: Default
.head 4 -  Font Enhancement: Default
.head 4 -  Text Color: Default
.head 4 -  Background Color: Default
.end
.head 3 +  Custom Control: ccSeasonYear
.winattr
.head 4 -  Class Child Ref Key: 31
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name: vti11.dll
.head 4 -  Display Settings
.head 5 -  DLL Name: vti11.dll
.head 5 -  MS Windows Class Name: VT:cSpinField
.head 5 -  Style:  0x00000000
.head 5 -  ExStyle:  0x00000000
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 8.9"
.head 6 -  Top: 0.0"
.head 6 -  Width:  0.975"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.271"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Etched Border? Yes
.head 5 -  Hollow? No
.head 5 -  Vertical Scroll? No
.head 5 -  Horizontal Scroll? No
.head 5 -  Tab Stop? Tab
.head 5 -  Tile To Parent? No
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: Default
.head 5 -  DLL Settings
.end
.head 4 -  Message Actions 
.head 3 +  Child Table: tbl2
.winattr
.head 4 -  Class Child Ref Key: 38
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.075"
.head 6 -  Top: 0.302"
.head 6 -  Width:  9.663"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.979"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Black
.head 5 -  Background Color: Gray
.head 5 -  View: Table
.head 5 -  Allow Row Sizing? No
.head 5 -  Lines Per Row: Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Default
.head 5 -  Discardable? Yes
.end
.head 4 +  Contents 
.head 5 +  Column: col1
.winattr
.head 6 -  Class Child Ref Key: 39
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Cult Id
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: String
.head 6 -  Justify: Left
.head 6 -  Width:  Default
.head 6 -  Width Editable? Yes
.head 6 -  Format: Unformatted
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: col2
.winattr
.head 6 -  Class Child Ref Key: 40
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: Cultivar Description
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  Maximum Data Length: Default
.head 6 -  Data Type: String
.head 6 -  Justify: Left
.head 6 -  Width:  7.838"
.head 6 -  Width Editable? Yes
.head 6 -  Format: Unformatted
.head 6 -  Country: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  Cell Options
.head 7 -  Cell Type? Standard
.head 7 -  Multiline Cell? No
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Yes
.head 8 -  Vertical Scroll? Yes
.head 8 -  Auto Drop Down? No
.head 8 -  Allow Text Editing? Yes
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Yes
.end
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 4 -  Functions 
.head 4 -  Window Variables 
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 -  Window Parameters 
.head 2 -  Window Variables 
.head 2 -  Message Actions 
.head 1 +  Form Window: frmCultRoyOwners
.head 2 -  Class: clsfrmCultRoyOwners
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? Yes
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 5.75"
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Class Child Ref Key: 8
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Class Child Ref Key: 12
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbTools
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPickRoyOwners
.head 5 -  Class Child Ref Key: 20
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 32
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 33
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 34
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 41
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Class Child Ref Key: 42
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDClose
.head 5 -  Class Child Ref Key: 43
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDRead
.head 5 -  Class Child Ref Key: 44
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Child Table: tblManyCultIds
.head 4 -  Class Child Ref Key: 38
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colCultId
.head 6 -  Class Child Ref Key: 39
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colCultDesc
.head 6 -  Class Child Ref Key: 40
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 4 -  Functions
.head 4 -  Window Variables
.head 4 -  Message Actions
.head 3 +  Child Table: tblCultRoyOwners
.head 4 -  Class Child Ref Key: 21
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colRoyOwnerId
.head 6 -  Class Child Ref Key: 22
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colRoyInstanceNo
.head 6 -  Class Child Ref Key: 23
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colRoyBusName
.head 6 -  Class Child Ref Key: 24
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colAmtPayable
.head 6 -  Class Child Ref Key: 25
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPercPayable
.head 6 -  Class Child Ref Key: 27
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPayDueDate
.head 6 -  Class Child Ref Key: 26
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colCurrencyPayable
.head 6 -  Class Child Ref Key: 37
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultRoyOwners
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 4 -  Functions
.head 4 -  Window Variables
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 28
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 29
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 46282
.head 4 -  Class Child Ref Key: 30
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 31
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
.head 1 +  Dialog Box: dlgQueryCultRoyOwners
.head 2 -  Class: clsdlgQueryCultRoyOwners
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.15"
.head 4 -  Top: 1.094"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 5
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 7
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClear
.head 5 -  Class Child Ref Key: 31
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 32
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultRoyOwners
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 3
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 22807
.head 4 -  Class Child Ref Key: 4
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 22808
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 22809
.head 4 -  Class Child Ref Key: 10
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 22810
.head 4 -  Class Child Ref Key: 11
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 22811
.head 4 -  Class Child Ref Key: 12
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCultId
.head 4 -  Class Child Ref Key: 13
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCultDesc
.head 4 -  Class Child Ref Key: 14
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfVariety
.head 4 -  Class Child Ref Key: 15
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbVarietyType
.head 4 -  Class Child Ref Key: 16
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Check Box: cbVFree
.head 4 -  Class Child Ref Key: 17
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNPA
.head 4 -  Class Child Ref Key: 18
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNotSale
.head 4 -  Class Child Ref Key: 19
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTCultId
.head 4 -  Class Child Ref Key: 20
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTCultDesc
.head 4 -  Class Child Ref Key: 21
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTVariety
.head 4 -  Class Child Ref Key: 22
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTVarietyType
.head 4 -  Class Child Ref Key: 23
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTVFree
.head 4 -  Class Child Ref Key: 24
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTNPA
.head 4 -  Class Child Ref Key: 25
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTNotSale
.head 4 -  Class Child Ref Key: 26
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbCultIdOp
.head 4 -  Class Child Ref Key: 27
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbCultDescOp
.head 4 -  Class Child Ref Key: 28
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbVarietyOp
.head 4 -  Class Child Ref Key: 29
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbVarietyTypeOp
.head 4 -  Class Child Ref Key: 30
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultRoyOwners
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
