.head 0 +  Application Description: SQLWindows 5.01 Jans Cultivar Pollination APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C666C656D
0040: 61706C733B6B3A5C 63656E747572615C 636C617373000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF000000 0000000000900200 0039010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? No
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: FRMCTBL.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: TABLE.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: STRINGS.APL
.head 2 -  File Include: METER.APL
.head 2 -  File Include: STACKS.APL
.head 2 -  File Include: VTMETER.APL
.head 2 -  File Include: FLAGS.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: CHECKBOX.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: GROUPBOX.APL
.head 2 -  File Include: QUERY.APL
.head 2 -  File Include: CMBFIELD.APL
.head 2 -  File Include: PICK.APL
.head 2 -  File Include: ACTIVATE.APL
.head 2 -  File Include: ITEMFUNC.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: CULTTBLD.APL
.head 2 -  File Include: CULTDETS.APL
.head 2 -  File Include: FRMDETS.APL
.head 2 -  File Include: MLFIELD.APL
.head 2 -  File Include: PAINTMD.APL
.head 2 -  ! File Include: CULTROY.APL
.head 2 -  ! File Include: ROYOWNRD.APL
.head 2 -  ! File Include: OPATENTS.APL
.head 2 -  File Include: EXTRNPRG.APL
.head 2 -  File Include: VTWIN.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for CULTPOLL.APL
.head 4 -  Number: CULTPOLLAplMsgOffSet = SAM_User + 4500
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: CULTPOLLAplConstOffSet = 2050
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1687207138
0000: 200200007C010000 0000000000000000 0200001200000046 0100001019000000
0020: 01A401E049020000 0040730000000100 00A35F0100192500 01A45F04B8000000
0040: 73D1000100006878 010019000901A43E 0700006E00730034 01000091015A0019
0060: 000182A4AA0B0000 001B730001008D00 AA010096190001A4 E8AB0B0000467300
0080: 010000A3C3010019 250001A4AC0BBA00 0073D10001000068 DC010019008901A4
00A0: AD0B006E00730034 010000F5015A0019 000182A4040C0000 001B730001008D00
00C0: 0E020096190001A4 E8050C0000467300 010000A327020019 250001A4060CBA00
00E0: 0073D10001000068 40020019008901A4 070C006E00730034 010000590222003B
0100: 0100000700A40168 100100BC06980000 7300018C00005D02 00CE3B0007E86A10
0120: 01BC267300010000 A36102003B330007 6C10BA01BC73C900 0100006865020019
0140: 000901A4761A0000 6E00730034010000 7E025A00190001A2 A4771A00001B7300
0160: 01008D0097020016 190004A401E0A41D 0000006673000100 A3B0020019050001
0180: A401D033B8000000 73D100010000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 525886956
0000: 3B180000F80E0000 0000000000000000 0200002900FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F08003C00 001463006C737062
0040: 43756C7420506F6C 6C69617400696F6E 4000000002780000 000408000000029A
0060: 01081A0000F80073 8000000001000000 CD0400040200039A 01090000F600F86C
0080: 0001000180804F00 0000010010001063 6C466F72006D4261 7365546162806C65
00A0: 7C000000043D0019 00C40000019A010D 0054027300D10001 0000661900190009
00C0: 019A0A0000007B54 0034010000320058 0000190001C29A0B 0000001E54000100
00E0: 0D004B000000D604 0002B00C00000054 6700010003018053 000000840200000B
0100: 636CFF009A000000 050000006F190069 019A080063960273 00B4010000195900
0120: 040002DA9A09009E 9600010D001D0000 00161900049A01B6 0A00966700010003
0140: 360000000400B500 030BED0096D90001 00603A0000001900 69019A0C007B9600
0160: 3401000001800419 000003000000F817 636C805072696E74 4261006963526570
0180: 6F72744022000000 0100006F19006901 9A09004314037300 0034010000018066
01A0: 19000400280C636C 704765806E657261 6C2200E800010000 2D1900019A610700
01C0: 0000628C03730001 0006000180680000 0C00050009636C07 48656C709AB20000
01E0: 0500B70400BE0200 316E03730001DA00 00042C001900019A 6D08006E8F000100
0200: 36001D00194B0001 9A09DB006EA30001 0000CD360019D200 019A0AF6006E6800
0220: 0100004FB2000019 00B4019A0B003D6E 00011A0000018019 030006000000091F
0240: 4578698C74220001 00DE0019D200019A 07C6008603736800 0100000188800400
0260: 0007001C000C5069 6300457870616E64 2200D1000100005B 040002DF0098FE03
0280: 7300018D00018004 110008000012631E 6C546F6700676C65 427574746F886E22
02A0: 00000100DE00049A 0002060086000A04 73006C000100018C 80040009001C000C
02C0: 646647FE65D10001 00005B040003DE9A 009828047300010D 0001803B0112000A
02E0: 00001663F26C4765 39546147651F8A02 00E1150000002D19 00019A6F00708C04
0300: 7300010036001900 194B00019A07DB00 70A300010000CD32 0019D200019A08F6
0320: 007068000100004B B3001900B4019A09 003D7000011A0000 640000AC00040002
0340: 6D0A0070CF000126 00680000046B0002 0BDB0070B3000100 C16C00000004DA00
0360: 020CF600706C0001 0070B00000000400 86020D0000003970 0400011B00740000
0380: AC00040002610E00 000070CF00010600 78000000046B0002 0FD800000070B300
03A0: 0100C97C0000041A 0002100000F60070 6C00010080310000 04000184029A1200
03C0: 0000FFE080010000 001F8400000C0019 0001019AE1130000 003F8001F9000017
03E0: 880000194B00019A 14D800000070A300 010000C1A1000000 191200019A160000
0400: F600706800010000 BAB0000000190084 019A170000003D70 00011A0000D30000
0420: 2C001900019A6118 000000708F000100 0600EC000000194B 00019A1AD8000000
0440: 70A300010000D105 0100191200019A1C 0000F60070680001 00001EB401001900
0460: A4019A1D00003D70 00011A0000370100 AD040003611E0000 0070CF0001860001
0480: 803A0008000B0000 1D636C0154626C4D 616B650053656C65 6374656400526F77
04A0: 4B65794172207261 79840000047B0004 6300010205FA0000 4F800100FE00CD04
04C0: 0019D200019A06C6 00B8047368000100 001DB200001900B4 019A07003DB80001
04E0: DA000036AC000400 026D0800B8CF0001 860001801D00C800 0C00001001436F6C
0500: 756D6E471E656C40 00D1000200005B04 0002DA9A050018CA 04730001006D0004
0520: 00961900019AB606 00CA470001000063 01805300E40D0000 10004469616C6F67
0540: 47659F9A00E80005 00002D1900019A6D 1200528807730000 010036001900046B
0560: 000213DB0052B300 0100CD1D0019D200 049A14F600526C00 010036A300040000
0580: A6031500003D5200 01DB003A2C001900 019A6D1600528F00 0100C60001801D88
05A0: 000E00000C63F163 62471B40000200BD 0019A500019A068D 00BE0773D1000100
05C0: 0066190004006902 9A07007BBE003601 0001804604000F00 008E0C726247DF22
05E0: E800010000AD0400 026D0600CACC0773 0001060001805700 0008001000001163
0600: 6C0D545175657258 7944696FB8B00000 000600B70400B603 130031FA07730001
0620: DA000004AC000400 026D1400FACF0001 36000800046B0002 15DB00FAB3000100
0640: C90C000019D20001 9A16F600FA680001 000025B000000019 00B4019A17003DFA
0660: 00011A00003E0000 2C001900019A6D18 00FA8F0001000600 0180990000800011
0680: 0000001163795175 610074614669656C 6474B401000C00B7 0400B60206002124
06A0: 0873000001DA0000 04AC000400026D07 0024CF0001360008 00046B000208DB00
06C0: 24B3000100CD0C00 04DA000209F60024 6C00010010B30019 00B4019A0A003D24
06E0: 00015A000029002C 001900019A6D0B00 248F000100060042 0000000463000102
0700: 0CFB004F800100FE 00C14600000019D2 00019A0DF6002468 000100005FB00000
0720: 000400B6020E003D 2400011B00630000 2C001900019A6D0F 00248F0001003600
0740: 7C00046B000210DB 0024B3000100CD80 00199200019A1100 F600246800010000
0760: 018C8099001200F8 00126303436F6D62 6F46FE69F60C00D6 0400023606003608
0780: 4673000100009B04 0004B5000207ED00 36D9000100660800 04006D0208007B36
07A0: 00B601000C590004 0002DB09009E3600 016D001000961900 019AB60A00364700
07C0: 0100009B290019A5 00019A0BED0036D1 0001000066420004 006C01020C00FFC9
07E0: 80010000BF465900 190001DA9A0D001E 360001006D005F00 D6040002B60E0036
0800: 670001009B630019 A500019A0FED0036 D100010000667C00 04006D0210007B36
0820: 00B6010080590019 0001DA9A11001E36 0001008D00018099 910013000012FF0F
0840: 43616368D8657401 0CDE0004DA000207 C600480873680001 000004B3000400B6
0860: 0208003D480001DB 0008AC000400026D 090048CF00013600 0C00046B00020ADB
0880: 0048B3000100CD10 0019D200019A0BF6 0048680001000029 B3001900B4019A0C
08A0: 003D480001DA0000 428C0004000102ED 0D003F8001F90000 374600194B00019A
08C0: 0EDB0048A3000100 00CD5F0004DA0002 0FF600486C000100 63B3001900B4019A
08E0: 10003D480001DA00 007CAC000400026D 110048CF00013600 8000194B00019A12
0900: DB0048A300010000 21018032000014C2 000015636C0F4F70 6572C061746F7246
0920: 69894000000200DE 0019D200019A06C6 0066087368000100 0019B3001900B401
0940: 9A07003D6600011A 0000018004230015 0000137C636C7900 43425965734E6F46
0960: 206C616722000001 7A0000044B00029A 061B00720873B300 0100210180640000
0980: 1662000014637069 5365654660726F6D 546165667C000400 6F190069019A0700
09A0: 6396087300B40100 00195900190001DA 9A08001E96000100 6D00320096190001
09C0: 9AB6090096470001 00009B4B0019A500 019A0AED0096D100 0100001801800400
09E0: 170021000D636C53 650B63496E746F44 2200000100006F04 006D03050063AE08
0A00: 7300360100018046 19001800001E1170 696E00536561736F 6E59651061722200
0A20: 000100BD0019A500 019A068D00D80873 D100010000900180 46000019B9001170
0A40: 017461727450726F 006772616DD60000 00F60700D6040002 37002C0944730000
0A60: 0100009B040004B5 000207ED002CD900 010066080004006D 0208007B2C00B601
0A80: 000C5900190001DA 9A09001E2C000100 6D002500D6040003 B60A002C67000100
0AA0: 9B290004B500020B ED002CD900010060 2D00000019006901 9A0C007B2C003401
0AC0: 0000018040520000 001A0000C80F636C 5374FF683001000A 006F190061019A01
0AE0: 0500633E097300B4 0100001959001900 01DA9A06001E3E00 01006D003200D604
0B00: 0002B607003E6700 01009336000004B5 000208ED003ED900 0100663A0004006D
0B20: 0209007B3E003601 003E005900040002 DB0A009C3E090001 6D004200D6040002
0B40: B60B003E67000100 9B460004B500020C ED003ED900010060 4A00000004006D02
0B60: 0D007B3E00360100 4E00580000040002 DB0E009E3E00010D 000180080001001B
0B80: 0000000E63EA6C70 4380697661727340 00E8000200002D04 00029A6D07009E8C
0BA0: 0973000100360004 00046B000308DB00 9EB3000100210180 9A00001C72000012
0BC0: 46036D4465747347 0F616CD600D90007 005B190001DA9A14 0010061173000001
0BE0: 006D001900961900 019AB61500064700 0100009B32001925 00019A1600ED0006
0C00: D100010000664B00 190069019A17007B 0600B40100006459 00190001DA9A1800
0C20: 1E060001000D007D 000000961900019A B419000006470001 00008B96000004B5
0C40: 00021AED0006D900 010098018008001D 39000D636DF06246 726D464000020000
0C60: 6F040069029A0600 6390117300B40100 00045900040002DB 07009E9000018D00
0C80: 01800411001E0000 0C63C36D6C476537 2200017A0000046B 0003051B00A81173
0CA0: B300010031018008 001F600000001063 70015061696E744D 6140737465724000
0CC0: 00F4020000960400 029A360700D21146 73000100009B0400 04B5000308ED00D2
0CE0: D900010018018019 002000F000001563 19726947434FC072 646572466F442200
0D00: 000100006F190069 019A070043181473 0000340100000180 06190021000000FE
0D20: 1407416464724C80 6162656C732200E8 000100002D190001 9A6F00248C147300
0D40: 0100C60001801908 0022000019636CFD 70024D696C46696C 65004C697374696E
0D60: 6722A300010000A7 190000BC019A0031 30147300011A0000 0180040300230000
0D80: 001007546F6F6C54 00697057696E646F 7744220000010000 6F04006D03050043
0DA0: 8216730000360100 0180060400240000 00A20C6654616C9C 43612200E8000100
0DC0: 00AD0400036D0700 06C8177300000186 00018021000C0025 000B63661C436150
0DE0: 6F6F816600000003 00DE002920000107 9A010001D4000600 0093800100007F04
0E00: B3000400B4039A09 00311217730001DB 00082C001900019A 6D0A00128F000100
0E20: C600018019000026 0000000C6777004D 6F75736557686518 656C22000100BD00
0E40: 19E500019ABD0073 D100010000180180 1D0027003800000D 5365406E64456D61
0E60: 6973464000020000 6F190069019A0500 63C0177300B40100 00195900040002DA
0E80: 9A06009EC000010D 0001808100000000 2800000008637051 4F456DC0A0000000
0EA0: 060000B71900B401 9A0500210E187300 0001DA0000192C00 1900019A6D08000E
0EC0: 8F00010036003200 194B00019A0BDB00 0EA300010000CD4B 0019D200019A0EF6
0EE0: 000E680001000064 B3001900B4019A11 003D0E0001DA0000 7D0C00040001029A
0F00: ED14003F8001F900 0007
.enddata
.head 3 -  ! When changing the clspbCultPollination interface consider the application program
.head 3 +  Pushbutton Class: clspbCultPollination
.head 4 -  Title: Cult.Poll.
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\POLLIN.BMP
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbPickInto
.head 4 +  Class Variables
.head 5 -  String: sTmp
.head 5 -  Window Handle: hWndTmp
.head 4 +  Instance Variables
.head 5 -  ! PUBLIC
.head 5 -  Window Handle: hWndPickIntoTable
.head 5 -  ! PRIVATE
.head 5 -  String: sCultId
.head 5 -  String: sCultDesc
.head 4 +  Functions
.head 5 +  Function: SetCultPollinationFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sNewCultId
.head 7 -  String: sNewCultDesc
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set sCultId = sNewCultId
.head 7 -  Set sCultDesc = sNewCultDesc
.head 7 -  Return TRUE
.head 5 +  ! Function: GetCultPollinationFields
.head 6 -  Description: 
.head 6 +  Returns 
.head 7 -  Boolean: 
.head 6 +  Parameters 
.head 7 -  Receive String: sNewCultId
.head 7 -  Receive String: sNewCultDesc
.head 6 -  Static Variables 
.head 6 -  Local variables 
.head 6 +  Actions 
.head 7 -  Set sNewCultId = sCultId
.head 7 -  Set sNewCultDesc = sCultDesc
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set hWndPickIntoTable = hWndItem
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set clspbCultPollination.nActivateWindowType = ACTIVATE_FormWindow
.head 6 -  Set clspbCultPollination.sActivateDialogName = 'frmCultPollination'
.head 6 -  Set clspbCultPollination.hWndTable = hWndPickIntoTable
.head 6 -  Set clspbCultPollination.hWndFieldLookUp = hWndItem
.head 5 +  On PAM_clsACTIVATE_PUSHFIELDS
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call PushString( sCultId )
.head 6 -  Call PushString( sCultDesc )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsPICK_LOOKUP
.head 6 -  Call PopString( sCultDesc, TRUE )
.head 6 -  Call PopString( sCultId, TRUE )
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_GETFIELDS, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsACTIVATE_POPFIELDS
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Return TRUE
.head 3 +  Form Window Class: clsfrmCultPollination
.head 4 -  Title: Cultivar Pollination
.head 4 -  Icon File:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Automatically Created at Runtime? Class Default
.head 5 -  Initial State: Class Default
.head 5 -  Maximizable? Class Default
.head 5 -  Minimizable? Class Default
.head 5 -  Allow Child Docking? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  System Menu? Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Form Size
.head 6 -  Width:  Class Default
.head 6 -  Height: Class Default
.head 6 -  Number of Pages: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Next Class Child Key: 37
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsFormChildTable
.head 4 -  Menu
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbAddRows
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 8
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbSaveRows
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 9
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 8
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbDeleteRows
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 11
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRePopulate
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 12
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbTools
.head 7 -  Class Child Ref Key: 23
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbCultivars
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 20
.head 7 -  Class: clspbCultivars
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 8.113"
.head 8 -  Top: 0.0"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbCultivars.hWndPickIntoTable = tblCultPollination
.head 8 +  On PAM_cls_GETFIELDS
.head 9 -  Return pbCultivars.GetCultivarFields( tblCultPollination.colPollCultId, tblCultPollination.colPollCultDesc, tblCultPollination.colPolProdRoy )
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 42
.head 7 -  Class ChildKey: 29
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 43
.head 7 -  Class ChildKey: 30
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 44
.head 7 -  Class ChildKey: 31
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClearRows
.head 7 -  Class Child Ref Key: 52
.head 7 -  Class ChildKey: 33
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 50
.head 7 -  Class ChildKey: 34
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDClose
.head 7 -  Class Child Ref Key: 54
.head 7 -  Class ChildKey: 36
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDRead
.head 7 -  Class Child Ref Key: 55
.head 7 -  Class ChildKey: 37
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 -  Background Text: Cult.Id
.head 6 -  Resource Id: 30909
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 16
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.05"
.head 7 -  Top: 0.135"
.head 7 -  Width:  0.575"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Cultivar Description
.head 6 -  Resource Id: 30910
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 17
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.963"
.head 7 -  Top: 0.375"
.head 7 -  Width:  1.663"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Data Field: dfCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 18
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.675"
.head 8 -  Top: 0.094"
.head 8 -  Width:  0.975"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 19
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.675"
.head 8 -  Top: 0.344"
.head 8 -  Width:  7.188"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  !
.head 5 +  Child Table: tblCultPollination
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 21
.head 6 -  Class: clsTableGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.038"
.head 8 -  Top: 0.688"
.head 8 -  Width:  9.825"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 4.146"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colPollCultId
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 22
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Poll.Cult.Id
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.975"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 +  If colPollCultId = hWndForm.hWndParent.dfCultId
.head 11 -  Call ErrorMessage( 'This cultivar is the same as the one being pollinated. Please choose another!', hWndForm, lParam )
.head 11 -  Return FALSE
.head 10 +  Else
.head 11 -  Call CheckCultPollinatorExists( hWndForm.hWndParent.dfCultId, colPollCultId, bExists, SH_cls_Execute )
.head 11 +  If bExists
.head 12 -  Call ErrorMessage( 'This cultivar is already used in this table as a pollinator.', hWndForm, lParam )
.head 12 -  Return FALSE
.head 11 +  Else
.head 12 -  Return TRUE
.head 7 +  Column: colPollCultDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 23
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Poll.Cultivar Description
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  4.25"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPolProdRoy
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 35
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title:
.head 8 -  Visible? No
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPollComments
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 24
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Comments
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: String
.head 8 -  Justify: Class Default
.head 8 -  Width:  4.138"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 6 +  Functions
.head 7 +  Function: CheckCultPollinatorExists
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  String: sCultId
.head 9 -  String: sPollCultId
.head 9 -  Receive Boolean: bExists
.head 9 -  Number: nActionType
.head 8 +  Static Variables
.head 9 -  ! hcSqlHandle: fcOurHandle
.winattr class FunctionalVar:
.head 10 -  Class: hcSqlHandle
.end
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nOurHandleNo
.head 9 -  !
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nOurHandleNo = SqlHandlesGetReferenceNo( 'CULTPOLLEXISTS' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = " SELECT 
  Poll_Cult_Id 
FROM 
  Pollination 
WHERE 
  Cult_Id = :1 AND 
  Poll_Cult_Id = :2 "
.head 11 -  Set sName = 'CULTPOLLEXISTS'
.head 11 -  Set sBind = ':sCultId, :sPollCultId'
.head 11 -  Set sInto = ''
.head 11 -  !
.head 11 -  Call haSqlHandles[ nOurHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nOurHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 -  Set bExists = FALSE
.head 11 -  !
.head 11 +  If haSqlHandles[ nOurHandleNo ].Execute( )
.head 12 +  If haSqlHandles[ nOurHandleNo ].FetchNext( nInd )
.head 13 -  Set bExists = TRUE
.head 12 +  Else
.head 13 -  Set bExists = FALSE
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nOurHandleNo ].Disconnect( )
.head 6 +  Window Variables
.head 7 -  Boolean: bExists
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set sSQLPopHandle = ' SELECT 
  Pollination.Poll_Cult_Id, 
  Cultivar.Cult_Desc, 
  Pollination.Poll_Comments 
FROM 
  Pollination, 
  Cultivar 
WHERE 
  Pollination.Cult_Id = :1 AND 
  Pollination.Poll_Cult_Id = Cultivar.Cult_Id '
.head 8 -  Set sNAMEPopHandle = 'CULTPOLL'
.head 8 -  Set sBINDPopHandle = ':hWndParent.dfCultId'
.head 8 -  Set sINTOPopHandle = ':clsfrmCultPollination.tblCultPollination.colPollCultId, 
:clsfrmCultPollination.tblCultPollination.colPollCultDesc, 
:clsfrmCultPollination.tblCultPollination.colPollComments'
.head 8 -  !
.head 8 -  Set sSQLRefreshHandle = ' SELECT 
  Cultivar.Cult_Desc, 
  Pollination.Poll_Comments 
FROM 
  Pollination, 
  Cultivar 
WHERE 
  Pollination.Cult_Id = :1 AND 
  Pollination.Poll_Cult_Id = :2 AND 
  Pollination.Poll_Cult_Id = Cultivar.Cult_Id '
.head 8 -  Set sNAMERefreshHandle = 'REFCULTPOLL'
.head 8 -  Set sBINDRefreshHandle = ':hWndParent.dfCultId, 
:clsfrmCultPollination.tblCultPollination.colPollCultId'
.head 8 -  Set sINTORefreshHandle = ':clsfrmCultPollination.tblCultPollination.colPollCultDesc, 
:clsfrmCultPollination.tblCultPollination.colPollComments'
.head 8 -  !
.head 8 -  Set sSQLInsertHandle = 'INSERT INTO Pollination 
( Cult_Id, Poll_Cult_Id, Poll_Comments ) 
VALUES ( :1, :2, :3 ) '
.head 8 -  Set sNAMEInsertHandle = 'INSCULTPOLL'
.head 8 -  Set sBINDInsertHandle = ':hWndParent.dfCultId, 
:clsfrmCultPollination.tblCultPollination.colPollCultId,
:clsfrmCultPollination.tblCultPollination.colPollComments'
.head 8 -  Set sINTOInsertHandle = ''
.head 8 -  !
.head 8 -  Set sSQLUpdateHandle = ' UPDATE Pollination 
SET 
  Poll_Cult_Id = :2, 
  Poll_Comments = :3 
WHERE 
  Cult_Id = :1'
.head 8 -  Set sNAMEUpdateHandle = 'UPDTCULTPOLL'
.head 8 -  Set sBINDUpdateHandle = ':hWndParent.dfCultId, 
:clsfrmCultPollination.tblCultPollination.colPollCultId,
:clsfrmCultPollination.tblCultPollination.colPollComments'
.head 8 -  Set sINTOUpdateHandle = ''
.head 8 -  !
.head 8 -  Set sSQLDeleteHandle = ' DELETE FROM Pollination 
WHERE 
  Cult_Id = :1 AND 
  Poll_Cult_Id = :2 '
.head 8 -  Set sNAMEDeleteHandle = 'DELCULTPOLL'
.head 8 -  Set sBINDDeleteHandle = ':hWndParent.dfCultId, 
:clsfrmCultPollination.tblCultPollination.colPollCultId'
.head 8 -  Set sINTODeleteHandle = ''
.head 8 -  !
.head 8 -  Set bAddAllowed = TRUE
.head 8 -  Set bSaveAllowed = TRUE
.head 8 -  Set bDeleteAllowed = TRUE
.head 8 -  Set bUnDeleteAllowed = TRUE
.head 8 -  Set bRepopulateAllowed = TRUE
.head 8 -  Set bClearSelectAllowed = TRUE
.head 8 -  Set bQueryAllowed = TRUE
.head 8 -  Set bReportAllowed = FALSE
.head 8 -  Set bOrderAllowed = TRUE
.head 8 -  !
.head 8 -  Set sQueryDialogName = 'dlgQueryCultPollination'
.head 7 +  On SAM_Destroy
.head 8 -  Call CheckCultPollinatorExists( '', '', bExists, SH_cls_Disconnect )
.head 8 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 25
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 47
.head 6 -  Class ChildKey: 26
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 57745
.head 6 -  Class Child Ref Key: 48
.head 6 -  Class ChildKey: 27
.head 6 -  Class: clsFormChildTable
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 49
.head 6 -  Class ChildKey: 28
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  Set hWndChildTable = tblCultPollination
.head 6 -  ! Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 5 +  On PAM_clsFRM_POPFIELDS
.head 6 -  Call PopString( dfCultDesc, TRUE )
.head 6 -  Call PopString( dfCultId, TRUE )
.head 6 -  Return TRUE
.head 3 +  Dialog Box Class: clsdlgQueryPollination
.head 4 -  Title: Query Cultivar Pollinations
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  7.975"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 2.177"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 14
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 16
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 3.775"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 17
.head 7 -  Class ChildKey: 7
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.65"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClear
.head 7 -  Class Child Ref Key: 19
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 20
.head 7 -  Class ChildKey: 14
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 -  Background Text: Cultivar Id
.head 6 -  Resource Id: 30919
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.663"
.head 7 -  Top: 0.75"
.head 7 -  Width:  0.913"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 +  Data Field: dfCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 10
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.538"
.head 8 -  Top: 0.709"
.head 8 -  Width:  0.963"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Uppercase
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCultId.sSQLCOLNAME = 'POLLINATION.CULT_ID'
.head 8 -  Set dfCultId.hWndOperatorField = cmbCultIdOp
.head 8 -  Set dfCultId.hWndNotField = cbNOTCultId
.head 5 -  !
.head 5 +  Check Box: cbNOTCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 11
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 2.05"
.head 7 -  Top: 0.709"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCultId.hWndQueryField = dfCultId
.head 5 -  !
.head 5 +  Combo Box: cmbCultIdOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 12
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.625"
.head 7 -  Top: 0.709"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCultIdOp.hWndQueryField = dfCultId
.head 8 -  Set cmbCultIdOp.sOperator = ' = '
.head 5 -  !
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 12
.head 6 -  Class ChildKey: 1
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 13
.head 6 -  Class ChildKey: 2
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 14
.head 6 -  Class ChildKey: 3
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.863"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 30918
.head 6 -  Class Child Ref Key: 15
.head 6 -  Class ChildKey: 4
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Window Location and Size
.head 7 -  Left: 6.113"
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 4 +  Derived From
.head 5 -  Class: clsTblQueryDialog
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bMapEnterToTab = TRUE
.head 6 -  Set hWndFirstFocus = dfCultId
.head 3 -  !
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  ! clsFormChildTable: frmCultPollination
.head 2 -  Description: 
.head 2 -  Named Menus 
.head 2 -  Menu 
.head 2 +  Tool Bar 
.head 3 +  Contents 
.head 4 +  Pushbutton: pbHelp
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbQuery
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbCultivars
.head 5 +  Message Actions 
.head 6 +  On PAM_cls_SETINSTANCEVARS
.head 7 -  Set pbCultivars.hWndPickIntoTable = tblCultPollination
.head 6 +  On PAM_cls_GETFIELDS
.head 7 -  Return pbCultivars.GetCultivarFields( tblCultPollination.colPollCultId, tblCultPollination.colPollCultDesc )
.head 4 +  Pushbutton: pbExit
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbTools
.head 5 -  Message Actions 
.head 2 +  Contents 
.head 3 +  Data Field: dfDatabase
.head 4 -  Message Actions 
.head 3 +  Data Field: dfUser
.head 4 -  Message Actions 
.head 3 -  !
.head 3 -  Background Text: Cult.Id
.head 3 -  Background Text: Cultivar Description
.head 3 +  Data Field: dfCultId
.head 4 -  Message Actions 
.head 3 +  Data Field: dfCultDesc
.head 4 -  Message Actions 
.head 3 -  !
.head 3 +  Child Table: tblCultPollination
.head 4 +  Contents 
.head 5 +  Column: colPollCultId
.head 6 -  List Values 
.head 6 +  Message Actions 
.head 7 +  On PAM_clsTBL_CHECKROWNEW
.head 8 +  If colPollCultId = hWndForm.hWndParent.dfCultId
.head 9 -  Call ErrorMessage( 'This cultivar is the same as the one being pollinated. Please choose another!', hWndForm, lParam )
.head 9 -  Return FALSE
.head 8 +  Else 
.head 9 -  Call CheckCultPollinatorExists( hWndForm.hWndParent.dfCultId, colPollCultId, bExists, SH_cls_Execute )
.head 9 +  If bExists
.head 10 -  Call ErrorMessage( 'This cultivar is already used in this table as a pollinator.', hWndForm, lParam )
.head 10 -  Return FALSE
.head 9 +  Else 
.head 10 -  Return TRUE
.head 5 +  Column: colPollCultDesc
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colPollComments
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 4 +  Functions 
.head 5 +  Function: CheckCultPollinatorExists
.head 6 -  Description: 
.head 6 +  Returns 
.head 7 -  Boolean: 
.head 6 +  Parameters 
.head 7 -  String: sCultId
.head 7 -  String: sPollCultId
.head 7 -  Receive Boolean: bExists
.head 7 -  Number: nActionType
.head 6 +  Static Variables 
.head 7 -  : fcOurHandle
.head 6 +  Local variables 
.head 7 -  String: sSql
.head 7 -  String: sBind
.head 7 -  String: sInto
.head 7 -  String: sName
.head 7 -  !
.head 7 -  Number: nInd
.head 6 +  Actions 
.head 7 +  Select Case nActionType
.head 8 +  Case SH_cls_Execute
.head 9 -  Set sSql = " SELECT 
  Poll_Cult_Id 
FROM 
  Pollination 
WHERE 
  Cult_Id = :1 AND 
  Poll_Cult_Id = :2 "
.head 9 -  Set sName = 'CULTPOLLEXISTS'
.head 9 -  Set sBind = ':sCultId, :sPollCultId'
.head 9 -  Set sInto = ''
.head 9 -  !
.head 9 -  Call fcOurHandle.Setup( sSql, sName, sBind, sInto )
.head 9 -  Call SqlVarSetup( fcOurHandle.hSqlHandle )
.head 9 -  !
.head 9 -  Set bExists = FALSE
.head 9 -  !
.head 9 +  If fcOurHandle.Execute( )
.head 10 +  If fcOurHandle.FetchNext( nInd )
.head 11 -  Set bExists = TRUE
.head 10 +  Else 
.head 11 -  Set bExists = FALSE
.head 10 -  Return TRUE
.head 9 +  Else 
.head 10 -  Return FALSE
.head 8 +  Case SH_cls_Disconnect
.head 9 -  Return fcOurHandle.Disconnect( )
.head 4 +  Window Variables 
.head 5 -  Boolean: bExists
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set sSQLPopHandle = ' SELECT 
  Pollination.Poll_Cult_Id, 
  Cultivar.Cult_Desc, 
  Pollination.Poll_Comments 
FROM 
  Pollination, 
  Cultivar 
WHERE 
  Pollination.Cult_Id = :1 AND 
  Pollination.Poll_Cult_Id = Cultivar.Cult_Id '
.head 6 -  Set sNAMEPopHandle = 'CULTPOLL'
.head 6 -  Set sBINDPopHandle = ':hWndParent.dfCultId'
.head 6 -  Set sINTOPopHandle = ':hWndForm.colPollCultId, 
:hWndForm.colPollCultDesc, 
:hWndForm.colPollComments'
.head 6 -  !
.head 6 -  Set sSQLRefreshHandle = ' SELECT 
  Cultivar.Cult_Desc, 
  Pollination.Poll_Comments 
FROM 
  Pollination, 
  Cultivar 
WHERE 
  Pollination.Cult_Id = :1 AND 
  Pollination.Poll_Cult_Id = :2 AND 
  Pollination.Poll_Cult_Id = Cultivar.Cult_Id '
.head 6 -  Set sNAMERefreshHandle = 'REFCULTPOLL'
.head 6 -  Set sBINDRefreshHandle = ':hWndParent.dfCultId, 
:hWndForm.colPollCultId'
.head 6 -  Set sINTORefreshHandle = ':hWndForm.colPollCultDesc, 
:hWndForm.colPollComments'
.head 6 -  !
.head 6 -  Set sSQLInsertHandle = 'INSERT INTO Pollination 
( Cult_Id, Poll_Cult_Id, Poll_Comments ) 
VALUES ( :1, :2, :3 ) '
.head 6 -  Set sNAMEInsertHandle = 'INSCULTPOLL'
.head 6 -  Set sBINDInsertHandle = ':hWndParent.dfCultId, 
:hWndForm.colPollCultId,
:hWndForm.colPollComments'
.head 6 -  Set sINTOInsertHandle = ''
.head 6 -  !
.head 6 -  Set sSQLUpdateHandle = ' UPDATE Pollination 
SET 
  Poll_Cult_Id = :2, 
  Poll_Comments = :3 
WHERE 
  Cult_Id = :1'
.head 6 -  Set sNAMEUpdateHandle = 'UPDTCULTPOLL'
.head 6 -  Set sBINDUpdateHandle = ':hWndParent.dfCultId, 
:hWndForm.colPollCultId,
:hWndForm.colPollComments'
.head 6 -  Set sINTOUpdateHandle = ''
.head 6 -  !
.head 6 -  Set sSQLDeleteHandle = ' DELETE FROM Pollination 
WHERE 
  Cult_Id = :1 AND 
  Poll_Cult_Id = :2 '
.head 6 -  Set sNAMEDeleteHandle = 'DELCULTPOLL'
.head 6 -  Set sBINDDeleteHandle = ':hWndParent.dfCultId, 
:hWndForm.colPollCultId'
.head 6 -  Set sINTODeleteHandle = ''
.head 6 -  !
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bRepopulateAllowed = TRUE
.head 6 -  Set bClearSelectAllowed = TRUE
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  !
.head 6 -  Set sQueryDialogName = 'dlgQueryCultPollination'
.head 5 +  On SAM_Destroy
.head 6 -  Call CheckCultPollinatorExists( '', '', bExists, SH_cls_Disconnect )
.head 6 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 3 -  Background Text: Season
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 -  Window Parameters 
.head 2 -  Window Variables 
.head 2 +  Message Actions 
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set bQueryAllowed = TRUE
.head 4 -  Set bAddAllowed = TRUE
.head 4 -  Set bSaveAllowed = TRUE
.head 4 -  Set bDeleteAllowed = TRUE
.head 4 -  Set bUnDeleteAllowed = TRUE
.head 4 -  Set bReportAllowed = FALSE
.head 4 -  Set bOrderAllowed = TRUE
.head 4 -  Set hWndChildTable = tblCultPollination
.head 4 -  ! Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 3 +  On PAM_clsFRM_POPFIELDS
.head 4 -  Call PopString( dfCultDesc, TRUE )
.head 4 -  Call PopString( dfCultId, TRUE )
.head 4 -  Return TRUE
.head 1 +  ! clsTblQueryDialog: dlgQueryCultPollination
.head 2 -  Description: 
.head 2 +  Tool Bar 
.head 3 +  Contents 
.head 4 +  Pushbutton: pbQuery
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbHelp
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbExit
.head 5 -  Message Actions 
.head 2 +  Contents 
.head 3 -  !
.head 3 -  Background Text: Cultivar Id
.head 3 -  !
.head 3 +  Data Field: dfCultId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set dfCultId.sSQLCOLNAME = 'POLLINATION.CULT_ID'
.head 6 -  Set dfCultId.hWndOperatorField = cmbCultIdOp
.head 6 -  Set dfCultId.hWndNotField = cbNOTCultId
.head 3 -  !
.head 3 +  Check Box: cbNOTCultId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cbNOTCultId.hWndQueryField = dfCultId
.head 3 -  !
.head 3 +  Combo Box: cmbCultIdOp
.head 4 -  List Initialization 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cmbCultIdOp.hWndQueryField = dfCultId
.head 6 -  Set cmbCultIdOp.sOperator = ' = '
.head 3 -  !
.head 3 +  Data Field: dfUser
.head 4 -  Message Actions 
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Message Actions 
.head 3 -  Background Text: Season
.head 3 +  Data Field: dfDatabase
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 -  Window Parameters 
.head 2 -  Window Variables 
.head 2 +  Message Actions 
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set bMapEnterToTab = TRUE
.head 4 -  Set hWndFirstFocus = dfCultId
.head 1 +  Form Window: frmCultPollination
.head 2 -  Class: clsfrmCultPollination
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Class Child Ref Key: 8
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Class Child Ref Key: 12
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbTools
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbCultivars
.head 5 -  Class Child Ref Key: 20
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 8.1"
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 29
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 30
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 31
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 8.7"
.head 6 -  Top: 0.031"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Class Child Ref Key: 33
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 34
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDClose
.head 5 -  Class Child Ref Key: 36
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDRead
.head 5 -  Class Child Ref Key: 37
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 30921
.head 4 -  Class Child Ref Key: 16
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 30922
.head 4 -  Class Child Ref Key: 17
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCultId
.head 4 -  Class Child Ref Key: 18
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCultDesc
.head 4 -  Class Child Ref Key: 19
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Child Table: tblCultPollination
.head 4 -  Class Child Ref Key: 21
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colPollCultId
.head 6 -  Class Child Ref Key: 22
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultPollination
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPollCultDesc
.head 6 -  Class Child Ref Key: 23
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultPollination
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPollComments
.head 6 -  Class Child Ref Key: 24
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultPollination
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: col4
.head 6 -  Class Child Ref Key: 35
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultPollination
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 4 -  Functions
.head 4 -  Window Variables
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 25
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 26
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 57746
.head 4 -  Class Child Ref Key: 27
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 28
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
.head 1 +  Dialog Box: dlgQueryCultPollination
.head 2 -  Class: clsdlgQueryPollination
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.138"
.head 4 -  Top: 1.417"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 5
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.021"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 7
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClear
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.021"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.552"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 14
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryPollination
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 30923
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCultId
.head 4 -  Class Child Ref Key: 10
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTCultId
.head 4 -  Class Child Ref Key: 11
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbCultIdOp
.head 4 -  Class Child Ref Key: 12
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 3
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 30924
.head 4 -  Class Child Ref Key: 4
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryPollination
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
