.head 0 +  Application Description: SQLWindows 5.01 Jans Cultivar Prohibition APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C666C656D
0040: 61706C733B6B3A5C 63656E747572615C 636C617373000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D80000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF840000 0084000000180300 00C1010000010000 0000000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? No
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: FRMCTBL.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: TABLE.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: STRINGS.APL
.head 2 -  File Include: METER.APL
.head 2 -  File Include: STACKS.APL
.head 2 -  File Include: VTMETER.APL
.head 2 -  File Include: FLAGS.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: CHECKBOX.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: QUERY.APL
.head 2 -  File Include: CMBFIELD.APL
.head 2 -  File Include: PICK.APL
.head 2 -  File Include: ACTIVATE.APL
.head 2 -  File Include: ITEMFUNC.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: GROUPBOX.APL
.head 2 -  File Include: VTWIN.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for CVPROHIB.APL
.head 4 -  Number: CVPROHIBAplMsgOffSet = SAM_User + 4300
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: CVPROHIBAplConstOffSet = 2100
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1116642653
0000: 54460000DC140000 0000000000000000 020000EE02000048 00040DF8000000FF
0020: 0F5500010DFA0000 FF8F620001FB00FF 8F6F0001FB00FF8F 7C0001FB00FF0F89
0040: 000204F8000000FF AF8D02FB00FF8F91 0001FB00FF8F9E00 01FB00FF8FAB0001
0060: FB00FF8FB80001FB 00FF0FC5000304FA 0000FF8FC90001FB 00FF8FD60001FB00
0080: FF8FE30002FB00FF 8FE70002FB00FF8F EB0002FB00FF8FEF 0001FB00FF8FFC00
00A0: 02FB00FF1F010204 FB00FF0F0401010D FB00FF8F110101FB 00FF8F1E0101FB00
00C0: FF8F2B0101FB00FF 0F38010304FB00FF 8F3C0101FB00FF8F 490101FB00FF8F56
00E0: 0102FB00FF8F5A01 02FB00FF8F5E0102 FB00FF8F620101FB 00FF8F6F0102FB00
0100: FF8F730102FB00FF 8F770101FB00FF8F 840101FB00FF8F91 0101FB00FF8F9E01
0120: 01FB00FF8FAB0103 FB00FF8FAF0101FB 00FF8FBC0101FB00 FF8FC90102FB00FF
0140: 8FCD0102FB00FF8F D10102FB00FF8FD5 0101FB00FF8FE201 02FB00FF8FE60102
0160: FB00FF8FEA0101FB 00FF8FF70101FB00 FF0F0402010DFB00 FF8F110201FB00FF
0180: 0F1E020304FB00FF 8F220201FB00FF8F 2F0201FB00FF0F3C 020204FB00FF8F40
01A0: 0202FB00FF8F4402 02FB00FF8F480201 FB00FF8F550202FB 00FF8F590202FB00
01C0: FF8F5D0201FB00FF 8F6A0201FB00FF8F 770201FB00FF8F84 0201FB00FF8F9102
01E0: 03FB00FF8F950201 FB00FF8FA20201FB 00FF8FAF0202FB00 FF8FB30202FB00FF
0200: 8FB70202FB00FF8F BB0201FB00FF8FC8 0202FB00FF8FCC02 02FB00FF8FD00201
0220: FB00FF8FDD0201FB 00FF8FEA0201FB00 FF8FF70201FB00FF 0F04030304FB00FF
0240: 0F0803010DFB00FF 8F150301FB00FF0F 22030204FB00FF8F 260302FB00FF8F2A
0260: 0302FB00FF8F2E03 01FB00FF8F3B0302 FB00FF8F3F0302FB 00FF8F430301FB00
0280: FF8F500301FB00FF 8F5D0301FB00FF8F 6A0301FB00FF8F77 0303FB00FF8F7B03
02A0: 01FB00FF8F880301 FB00FF8F950302FB 00FF8F990302FB00 FF8F9D0302FB00FF
02C0: 8FA10301FB00FF8F AE0302FB00FF8FB2 0302FB00FF8FB603 01FB00FF8FC30301
02E0: FB00FF8FD00301FB 00FF8FDD0301FB00 FF8FEA0303FB00FF 8FEE0301FB00FF8F
0300: FB0301FB00FF0F08 040204FB00FF8F0C 0402FB00FF8F1004 02FB00FF0F140401
0320: 0DFB00FF8F210402 FB00FF8F250402FB 00FF8F290401FB00 FF8F360401FB00FF
0340: 8F430401FB00FF8F 500401FB00FF0F5D 040304FB00FF8F61 0401FB00FF8F6E04
0360: 01FB00FF8F7B0402 FB00FF8F7F0402FB 00FFAF8302FB00FF 8F870401FB00FF8F
0380: 940402FB00FF8F98 0402FB00FF8F9C04 01FB00FF8FA90401 FB00FF8FB60401FB
03A0: 00FF8FC30401FB00 FF8FD00403FB00FF 8FD40401FB00FF8F E10401FB00FF8FEE
03C0: 0402FB00FF8FF204 02FB00FF8FF60402 FB00FF8FFA0401FB 00FF0F07050204FB
03E0: 00FF8F0B0502FB00 FF0F0F05010DFB00 FF8F1C0501FB00FF 8F290501FB00FF8F
0400: 360501FB00FF0F43 050304FB00FF8F47 0501FB00FF8F5405 01FB00FF8F610502
0420: FB00FF8F650502FB 00FF8F690502FB00 FF8F6D0501FB00FF 8F7A0502FB00FF8F
0440: 7E0502FB00FF8F82 0501FB00FF8F8F05 01FB00FF8F9C0501 FB00FF8FA90501FB
0460: 00FF8FB60503FB00 FF8FBA0501FB00FF 8FC70501FB00FF8F D40502FB00FF8FD8
0480: 0502FB00FF8FDC05 02FB00FF8FE00501 FB00FF8FED0502FB 00FF8FF10502FB00
04A0: FF8FF50501FB00FF 0F0206010DFB00FF 8F0F0601FB00FF8F 1C0601FB00FF0F29
04C0: 060304FB00FF8F2D 0601FB00FF8F3A06 01FB00FF0F470602 04FB00FF8F4B0602
04E0: FB00FF8F4F0602FB 00FF8F530601FB00 FF8F600601FB00FF 8F6D0601FB00FF8F
0500: 7A0601FB00FF8F87 0601FB00FF8F9406 02FB00FF8F980602 FB00FF8F9C0601FB
0520: 00FF8FA90601FB00 FF8FB60601FB00FF 8FC30601FB00FF8F D00603FB00FF8FD4
0540: 0601FB00FF8FE106 01FB00FF8FEE0602 FB00FF8FF20602FB 00FF8FF60602FB00
0560: FF8FFA0601FB00FF 0F07070204FB00FF 8F0B0702FB00FF0F 0F07010DFB00FF8F
0580: 1C0701FB00FF8F29 0701FB00FF8F3607 01FB00FF0F430703 04FB00FF8F470701
05A0: FB00FF8F540701FB 00FF8F610702FB00 FF8F650702FB00FF 8F690702FB00FF8F
05C0: 6D0701FB00FF8F7A 0702FB00FF8F7E07 02FB00FF8F820701 FB00FF8F8F0701FB
05E0: 00FF8F9C0701FB00 FF8FA90701FB00FF 8FB60703FB00FF8F BA0701FB00FF8FC7
0600: 0701FB00FF8FD407 02FB00FF8FD80702 FB00FF8FDC0702FB 00FF8FE00701FB00
0620: FF8FED0702FB00FF 8FF10702FB00FF8F F50701FB00FF0F02 08010DFB00FF8F0F
0640: 0801FB00FF8F1C08 01FB00FF0F290803 04FB00FF8F2D0801 FB00FF8F3A0801FB
0660: 00FF0F47080204FB 00FF8F4B0802FB00 FF8F4F0802FB00FF 8F530801FB00FF8F
0680: 600802FB00FF8F64 0802FB00FF8F6808 01FB00FF8F750801 FB00FF8F820801FB
06A0: 00FF8F8F0801FB00 FF8F9C0803FB00FF 8FA00801FB00FF8F AD0801FB00FF8FBA
06C0: 0802FB00FF8FBE08 02FB00FF8FC20802 FB00FF8FC60801FB 00FF8FD30802FB00
06E0: FF8FD70802FB00FF 8FDB0801FB00FF8F E80801FB00FF8FF5 0801FB00FF0F0209
0700: 010DFB00FF0F0F09 0304FB00FF8F1309 01FB00FF8F200901 FB00FF0F2D090204
0720: FB00FF8F310902FB 00FF8F350902FB00 FF8F390901FB00FF 8F460902FB00FF8F
0740: 4A0902FB00FF8F4E 0901FB00FF8F5B09 01FB00FF8F680901 FB00FF8F750901FB
0760: 00FF8F820903FB00 FF8F860901FB00FF 8F930901FB00FF8F A00902FB00FF8FA4
0780: 0902FB00FF8FA809 02FB00FF8FAC0901 FB00FF8FB90902FB 00FF8FBD0902FB00
07A0: FF8FC10901FB00FF 8FCE0901FB00FF8F DB0901FB00FF8FE8 0901FB00FF8FF509
07C0: 03FB00FF8FF90901 FB00FF0F060A010D FB00FF0F130A0204 FB00FF8F170A02FB
07E0: 00FF8F1B0A02FB00 FF8F1F0A01FB00FF 8F2C0A02FB00FF8F 300A02FB00FF8F34
0800: 0A01FB00FF8F410A 01FB00FF8F4E0A01 FB00FF8F5B0A01FB 00FF0F680A0304FB
0820: 00FF8F6C0A01FB00 FF8F790A01FB00FF 8F860A02FB00FF8F 8A0A02FB00FF8F8E
0840: 0A02FB00FF8F920A 01FB00FF8F9F0A02 FB00FF8FA30A02FB 00FF8FA70A01FB00
0860: FF8FB40A01FB00FF 8FC10A01FB00FF8F CE0A01FB00FF8FDB 0A03FB00FF8FDF0A
0880: 01FB00FF8FEC0A01 FB00FF8FF90A02FB 00FF8FFD0A02FB00 FF0F010B0204FB00
08A0: FF0F050B010DFB00 FF8F120B02FB00FF 8F160B02FB00FF8F 1A0B01FB00FF8F27
08C0: 0B01FB00FF8F340B 01FB00FF8F410B01 FB00FF0F4E0B0304 FB00FF8F520B01FB
08E0: 00FF8F5F0B01FB00 FF8F6C0B02FB00FF 8F700B02FB00FF8F 740B02FB00FF8F78
0900: 0B01FB00FF8F850B 02FB00FF8F890B02 FB00FF8F8D0B01FA 0000FF8F9A0B01FB
0920: 00FF8FA70B01FB00 FF8FB40B01FB00FF 8FC10B03FB00FF8F C50B01FB00FF8FD2
0940: 0B01FB00FF8FDF0B 02FB00FF8FE30B02 FB00FF8FE70B02FB 00FF8FEB0B01FB00
0960: FF8FF80B02FB00FF 8FFC0B02FB00FF1F 0C010DFB00FF8F0D 0C01FB00FF8F1A0C
0980: 01FB00FF8F270C01 FB00FF0F340C0304 FB00FF8F380C01FB 00FF8F450C01FB00
09A0: FF0F520C0204FB00 FF8F560C02FB00FF 8F5A0C02FB00FF8F 5E0C01FB00FF8F6B
09C0: 0C02FB00FF8F6F0C 02FB00FF8F730C01 FB00FF8F800C01FB 00FF8F8D0C01FA00
09E0: 00FF8F9A0C01FB00 FF8FA70C03FB00FF 8FAB0C01FB00FF8F B80C01FB00FF8FC5
0A00: 0C02FB00FF8FC90C 02FB00FF8FCD0C02 FB00FF8FD10C01FB 00FF8FDE0C02FB00
0A20: FF8FE20C02FB00FF 8FE60C01FB00FF8F F30C01FB00FF1F0D 010DFB00FF8F0D0D
0A40: 01FB00FF0F1A0D03 04FB00FF8F1E0D01 FB00FF8F2B0D01FB 00FF0F380D0204FB
0A60: 00FF8F3C0D02FB00 FF8F400D02FB00FF 8F440D01FB00FF8F 510D02FB00FF8F55
0A80: 0D02FB00FF8F590D 01FB00FF8F660D01 FB00FF8F730D01FB 00FF8F800D01FB00
0AA0: FF8F8D0D03FB00FF 8F910D01FA0000FF 8F9E0D01FB00FF8F AB0D02FB00FF8FAF
0AC0: 0D02FB00FF8FB30D 02FB00FF8FB70D01 FB00FF8FC40D02FB 00FF8FC80D02FB00
0AE0: FF8FCC0D01FB00FF 8FD90D01FB00FF8F E60D01FB00FF8FF3 0D01FB00FF1F0E03
0B00: 04FB00FF0F040E01 0DFB00FF8F110E01 FB00FF0F1E0E0204 FB00FF8F220E02FB
0B20: 00FF8F260E02FB00 FF8F2A0E01FB00FF 8F370E02FB00FF8F 3B0E02FB00FF8F3F
0B40: 0E01FB00FF8F4C0E 01FB00FF8F590E01 FB00FF8F660E01FB 00FF8F730E03FB00
0B60: FF8F770E01FB00FF 8F840E01FB00FF8F 910E02FB00FF8F95 0E02FB00FF8F990E
0B80: 02FB00FF8F9D0E01 FB00FF8FAA0E02FB 00FF8FAE0E02FB00 FF8FB20E01FB00FF
0BA0: 8FBF0E01FB00FF8F CC0E01FB00FF8FD9 0E01FB00FF8FE60E 03FB00FF8FEA0E01
0BC0: FB00FF8FF70E01FB 00FF0F040F0204FB 00FF8F080F02FB00 FF8F0C0F02FB00FF
0BE0: 0F100F010DFB00FF 8F1D0F02FB00FF8F 210F02FB00FF8F25 0F01FB00FF8F320F
0C00: 01FB00FF8F3F0F01 FB00FF8F4C0F01FB 00FF0F590F0304FB 00FF8F5D0F01FB00
0C20: FF8F6A0F01FB00FF 8F770F02FB00FF8F 7B0F02FB00FF8F7F 0F02FB00FF8F830F
0C40: 01FB00FF8F900F02 FB00FF8F940F02FB 00FF8F980F01FB00 FF8FA50F01FB00FF
0C60: 8FB20F01FB00FF8F BF0F01FB00FF8FCC 0F03FB00FF8FD00F 01FB00FF8FDD0F01
0C80: FB00FF8FEA0F02FB 00FF8FEE0F02FB00 FF8FF20F02FB00FF 8FF60F01FB00FF0F
0CA0: 03100204FB00FF8F 071002FB00FF0F0B 10010DFB00FF8F18 1001FB00FF8F2510
0CC0: 01FB00FF8F321001 FB00FF0F3F100304 FB00FF8F431001FB 00FF8F501001FB00
0CE0: FF8F5D1002FB00FF 8F611002FB00FF8F 651002FB00FF8F69 1001FB00FF8F7610
0D00: 02FB00FF8F7A1002 FB00FF8F7E1001FB 00FF8F8B1001FB00 FF8F981001FB00FF
0D20: 8FA51001FB00FF8F B21003FB00FF8FB6 1001FB00FF8FC310 01FB00FF8FD01002
0D40: FB00FF8FD41002FB 00FF8FD81002FB00 FF8FDC1001FB00FF 8FE91002FB00FF8F
0D60: ED1002FB00FF8FF1 1001FB00FF8FFE10 01FB00FF0F0B1101 0DFB00FF8F181101
0D80: FB00FF0F25110304 FB00FF8F291101FB 00FF8F361101FB00 FF0F43110204FB00
0DA0: FF8F471102FB00FF 8F4B1102FB00FF8F 4F1101FB00FF8F5C 1102FB00FF8F6011
0DC0: 02FB00FF8F641101 FB00FF8F711101FB 00FF8F7E1101FB00 FF8F8B1101FB00FF
0DE0: 8F981103FB00FF8F 9C1101FB00FF8FA9 1101FB00FF8FB611 02FB00FF8FBA1102
0E00: FB00FF8FBE1102FB 00FF8FC21101FB00 FF8FCF1102FB00FF 8FD31102FB00FF8F
0E20: D71101FB00FF8FE4 1101FB00FF8FF111 01FB00FF8FFE1101 FB00FF0F0B120304
0E40: FB00FF0F0F12010D FB00FF8F1C1201FB 00FF0F29120204FB 00FF8F2D1202FB00
0E60: FF8F311202FB00FF 8F351201FB00FF8F 421202FB00FF8F46 1202FB00FF8F4A12
0E80: 01FB00FF8F571201 FB00FF8F641201FB 00FF8F711201FB00 FF8F7E1203FB00FF
0EA0: 8F821201FB00FF8F 8F1201FB00FF8F9C 1202FB00FF8FA012 02FB00FF8FA41202
0EC0: FB00FF8FA81201FB 00FF8FB51202FB00 FF8FB91202FB00FF 8FBD1201FB00FF8F
0EE0: CA1201FB00FF8FD7 1201FB00FF8FE412 01FB00FF8FF11203 FB00FF8FF51201FB
0F00: 00FF0F0213010DFB 00FF0F0F130204FB 00FF8F131302FB00 FF8F171302FB00FF
0F20: 8F1B1301FB00FF8F 281302FB00FF8F2C 1302FB00FF8F3013 01FB00FF8F3D1301
0F40: FB00FF8F4A1301FB 00FF8F571301FB00 FF0F64130304FB00 FF8F681301FB00FF
0F60: 8F751301FB00FF8F 821302FB00FF8F86 1302FB00FF8F8A13 02FB00FF8F8E1301
0F80: FB00FF8F9B1302FB 00FF8F9F1302FB00 FF8FA31301FB00FF 8FB01301FB00FF8F
0FA0: BD1301FB00FF8FCA 1301FB00FF8FD713 03FB00FF8FDB1301 FB00FF8FE81301FB
0FC0: 00FF8FF51302FB00 FF8FF91302FB00FF 8FFD1302FB00FF0F 0114010DFB00FF0F
0FE0: 0E140204FB00FF8F 121402FB00FF8F16 1401FB00FF8F2314 01FB00FF8F301401
1000: FB00FF8F3D1401FB 00FF0F4A140304FB 00FF8F4E1401FB00 FF8F5B1401FB00FF
1020: 8F681402FB00FF8F 6C1402FB00FF8F70 1402FB00FF8F7414 01FB00FF8F811402
1040: FB00FF8F851402FB 00FF8F891401FB00 FF8F961401FB00FF 8FA31401FB00FF8F
1060: B01401FB00FF8FBD 1403FB00FF8FC114 01FB00FF8FCE1401 FB00FF8FDB1402FB
1080: 00FF8FDF1402FB00 FF8FE31402FB00FF 8FE71401FB00FF8F F41402FB00FF8FF8
10A0: 1402FB00FF8FFC14 01FB00FF0F091501 0DFB00FF8F161501 FB00FF8F231501FB
10C0: 00FF0F30150304FB 00FF8F341501FB00 FF8F411501FB00FF 0F4E150204FB00FF
10E0: 8F521502FB00FF8F 561502FB00FF8F5A 1501FB00FF8F6715 02FB00FF8F6B1502
1100: FB00FF8F6F1501FB 00FF8F7C1501FB00 FF8F891501FB00FF 8F961501FB00FF8F
1120: A31503FB00FF8FA7 1501FB00FF8FB415 01FB00FF8FC11502 FB00FF8FC51502FB
1140: 00FF8FC91502FB00 FF8FCD1501FB00FF 8FDA1502FB00FF8F DE1502FB00FF8FE2
1160: 1501FB00FF8FEF15 01FB00FF8FFC1501 FB00FF0F0916010D FB00FF0F16160304
1180: FB00FF8F1A1601FB 00FF8F271601FB00 FF0F34160204FB00 FF8F381602FB00FF
11A0: 8F3C1602FB00FF8F 401601FB00FF8F4D 1602FB00FF8F5116 02FB00FF8F551601
11C0: FB00FF8F621601FB 00FF8F6F1601FB00 FF8F7C1601FB00FF 8F891603FB00FF8F
11E0: 8D1601FA0000FF8F 9A1601FB00FF8FA7 1602FB00FF8FAB16 02FB00FF8FAF1602
1200: FB00FF8FB31601FB 00FF8FC01602FB00 FF8FC41602FB00FF 8FC81601FB00FF8F
1220: D51601FB00FF8FE2 1601FB00FF8FEF16 01FB00FF8FFC1603 FB00FF1F17010DFB
1240: 00FF8F0D1701FB00 FF0F1A170204FB00 FF8F1E1702FB00FF 8F221702FB00FF8F
1260: 261701FB00FF8F33 1702FB00FF8F3717 02FB00FF8F3B1701 FB00FF8F481701FB
1280: 00FF8F551701FB00 FF8F621701FB00FF 0F6F170304FB00FF 8F731701FB00FF8F
12A0: 801701FB00FF8F8D 1702FB00FF8F9117 02FB00FF8F951702 FB00FF8F991701FA
12C0: 0000FF8FA61702FB 00FF8FAA1702FB00 FF8FAE1701FB00FF 8FBB1701FB00FF8F
12E0: C81701FB00FF8FD5 1701FB00FF8FE217 03FB00FF8FE61701 FB00FF8FF31701FB
1300: 00FF1F180204FB00 FF8F041802FB00FF 8F081802FB00FF0F 0C18010DFB00FF8F
1320: 191802FB00FF8F1D 1802FB00FF8F2118 01FB00FF8F2E1801 FB00FF8F3B1801FB
1340: 00FF8F481801FB00 FF0F55180304FB00 FF8F591801FB00FF 8F661801FB00FF8F
1360: 731802FB00FF8F77 1802FB00FF8F7B18 02FB00FF8F7F1801 FB00FF8F8C1802FB
1380: 00FF8F901802FB00 FF8F941801FB00FF 8FA11801FB00FF8F AE1801FB00FF8FBB
13A0: 1801FB00FF8FC818 03FB00FF8FCC1801 FB00FF8FD91801FB 00FF8FE61802FB00
13C0: FF8FEA1802FB00FF 8FEE1802FB00FF8F F21801FB00FF8FFF 1802FB00FF0F0319
13E0: 0204FB00FF0F0719 010DFB00FF8F1419 01FB00FF8F211901 FB00FF8F2E1901FB
1400: 00FF0F3B190304FB 00FF8F3F1901FB00 FF8F4C1901FB00FF 8F591902FB00FF8F
1420: 5D1902FB00FF8F61 1902FB00FF8F6519 01FB00FF8F721902 FB00FF8F761902FB
1440: 00FF8F7A1901FB00 FF8F871901FB00FF 8F941901FB00FF8F A11901FB00FF8FAE
1460: 1903FB00FF8FB219 01FB00FF8FBF1901 FB00FF8FCC1902FB 00FF8FD01902FB00
1480: FF8FD41902FB00FF 8FD81901FB00FF8F E51902FB00FF8FE9 1902FB00FF8FED19
14A0: 01FB00FF8FFA1901 FB00FF0F071A010D FB00FF8F141A01FB 00FF0F211A0304FB
14C0: 00FF8F251A01FB00 FF8F321A01FB00FF 0F3F1A0204FB00FF 8F431A02FB00FF8F
14E0: 471A02FB00FF8F4B 1A01FB00FF0F
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1982595204
0000: 5C0C000076050000 0000000000000000 0200001700FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F08003C00 001463006C737062
0040: 43756C740050726F 686962697400696F 6E34000000021800 0000020400FC0000
0060: FF070400030400FC 0000FF0701803300 0000000100000011 636C0154626C5175
0080: 657200794469616C 6F67948000000006 000000DD0300FF7F 04CD020000FF7F08
00A0: DC000200FF7F0CC0 00010D000000FF7F 19DC000100FF7F26 DC000100FF7F0180
00C0: 805D00000002009C 0011517507617461 466940656C642C01 000C9900000204FD
00E0: 00FFD70402FC0000 FFF708FD00FFD70C 02FD00FF87100001 0DFD00FFC71D0001
0100: FD00FFC72A0002D1 000100003F8001F8 000000872E00010D FD00FFC73B0002FD
0120: 00FFC73F0001FD00 FFC74C0002FD00FF C7500001FD00FFC7 01805D0000030000
0140: 0012636C3F436FE0 6D626F46692F0C00 00BB0200FFFF9A04 020000FFFFBE0800
0160: FFFFBA0C0200FFFF B6100D00FFFFBE1D 00FFFF3E2A0001FA 00002780010000FF
0180: B62E0D00FFFFBE3B 00FFFFBE3F00FFFF BE4C00FFFFBE5000 FFFF8001801A0000
01A0: 0004E10015636C07 4F70657261E0746F 7246694434000002 0000B3010D00FFFF
01C0: 980D00010000FFFF 1001800400000500 E0000013636C0379 4342596573004E6F
01E0: 466C61671C00D000 00010000EC020400 FF3F0180640D0000 0600080C636C6362
0200: 4765806E6572616C 1C00680001000001 F60D00FF1F01800D 0300070000000CD7
0220: 70477F0034010000 010DFB00FF8F0180 0D09000800000963 0E6C45786974441C
0240: 0000010000B3010D 00FFFF1801800400 09003800000C5069 0063457870616E64
0260: 1CA20000010000DD 0200FF7F010C8004 000A0000FC001200 546F67676C654275
0280: 4074746F6E1C0000 B401000002FB00FF 0F01802200000000 0B0000001D631A6C
02A0: 544D616B00655365 6C65637465006452 6F774B6579410072 7261796C000000B6
02C0: 040002A300010000 7F80F20100002F04 010DFB00FF8F1100 01FB00FF8F1E0002
02E0: F90000FF0F0180B7 000000000C000000 0F63066C61626C65 471E656C0C02C200
0300: 15000000EC010D00 FFBF0DE6010000FF 3F1A00EE0100FF3F 2700EE0100FF3F34
0320: 00EE0200FF3F3800 EE0200FF3F3C00EE 0200FF3F4000EE02 00FF3F4400EE0200
0340: FF3F4800EE0200FF BF4CEF00FFBF508E 02000100FE00C980 0100003F54008C01
0360: 0D000100FE00C980 0100003F5800EC01 0D00FF3F6500EE01 00FF3F7200EE0100
0380: FF3F7F00EE0100FF 3F8C00EE0100FF3F 9900EE0100FF3FA6 00EE0100FF3FB300
03A0: EC030400FF3F0180 660D000D000C1163 5370696E00536561 736F6E5965106172
03C0: 1C00000100CD0001 0DFE00FF0301802B 000000E00E000000 1100466F726D4368
03E0: 696C386454616400 D800000400EC010D 00FFBF0DE6010000 FFBF1AEF00FFBF27
0400: EE0200FF3F018006 0D000F000000000B 686353716C486142 6E6C651C00003401
0420: 0000010DFB00FF0F 01802F0008000010 00000E633E6C4765 1F7C00006C000500
0440: 01F60D00FF5F0D02 F700FF1F110004F0 0D000000FF5F1E03 F700FF1F220001F7
0460: 00FF1F01800D1300 110000177C636C50 0072696E74426173 6900635265706F72
0480: 741CA300010000D9 010D00FF7F010080 2E00000012000058 0011637053207461
04A0: 7274506F67007261 6DAC00000007DB00 02FD00FFC7040002 FC0000FFD70802FD
04C0: 00FF970C010DFD00 FFD71903FD00FFC7 1D0002FD00FFC721 0001FD00FFC70180
04E0: 048000130000000C 63E164664765196C 1C000100ED0003FE 00FF6301802F0080
0500: 1400000010636C2C 44696F4765DF7C6C 00050001F60D00FF 5F0D02F700FF1F11
0520: 0004F20D0000FFDF 1EF700FFDF22F700 FF1F018034300000 0015001436637065
0540: 6C056346726F6D54 6E61640034040000 010DFB00FFAF0D01 F90000FFEF1AFB00
0560: FFAF2701FB00FF8F 0180040900160000 0D63B26C53656340 496E746F1C0000B4
0580: 01000003FB00FF0F
.enddata
.head 3 -  ! when changing clspbCultProhibtion interface consider the app of this app the the start button there
.head 3 +  Pushbutton Class: clspbCultProhibition
.head 4 -  Title: CV.Proh
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\PROHIB.BMP
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbPickInto
.head 4 +  Class Variables
.head 5 -  String: sTmp
.head 5 -  Window Handle: hWndTmp
.head 4 +  Instance Variables
.head 5 -  ! PUBLIC
.head 5 -  Window Handle: hWndPickIntoTable
.head 5 -  ! PRIVATE
.head 5 -  String: sCultId
.head 5 -  String: sCultDesc
.head 4 +  Functions
.head 5 +  Function: SetCultProhibitionFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sNewCultId
.head 7 -  String: sNewCultDesc
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set sCultId = sNewCultId
.head 7 -  Set sCultDesc = sNewCultDesc
.head 7 -  Return TRUE
.head 5 +  ! Function: GetCultProhibitionFields
.head 6 -  Description: 
.head 6 +  Returns 
.head 7 -  Boolean: 
.head 6 +  Parameters 
.head 7 -  Receive String: sNewCultId
.head 7 -  Receive String: sNewCultDesc
.head 6 -  Static Variables 
.head 6 -  Local variables 
.head 6 +  Actions 
.head 7 -  Set sNewCultId = sCultId
.head 7 -  Set sNewCultDesc = sCultDesc
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set hWndPickIntoTable = hWndItem
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set clspbCultProhibition.nActivateWindowType = ACTIVATE_FormWindow
.head 6 -  Set clspbCultProhibition.sActivateDialogName = 'frmCultProhibition'
.head 6 -  Set clspbCultProhibition.hWndTable = hWndPickIntoTable
.head 6 -  Set clspbCultProhibition.hWndFieldLookUp = hWndItem
.head 5 +  On PAM_clsACTIVATE_PUSHFIELDS
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call PushString( sCultId )
.head 6 -  Call PushString( sCultDesc )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsPICK_LOOKUP
.head 6 -  Call PopString( sCultDesc, TRUE )
.head 6 -  Call PopString( sCultId, TRUE )
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_GETFIELDS, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsACTIVATE_POPFIELDS
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Return TRUE
.head 3 +  Form Window Class: clsfrmCultProhibition
.head 4 -  Title: Cultivar Prohibitions
.head 4 -  Icon File:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Automatically Created at Runtime? Class Default
.head 5 -  Initial State: Class Default
.head 5 -  Maximizable? Class Default
.head 5 -  Minimizable? Class Default
.head 5 -  Allow Child Docking? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  System Menu? Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Form Size
.head 6 -  Width:  Class Default
.head 6 -  Height: Class Default
.head 6 -  Number of Pages: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Next Class Child Key: 38
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsFormChildTable
.head 4 -  Menu
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbAddRows
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 8
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbSaveRows
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 9
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 8
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbDeleteRows
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 11
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRePopulate
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 12
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbTools
.head 7 -  Class Child Ref Key: 23
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClearRows
.head 7 -  Class Child Ref Key: 52
.head 7 -  Class ChildKey: 32
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 42
.head 7 -  Class ChildKey: 33
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 43
.head 7 -  Class ChildKey: 34
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 44
.head 7 -  Class ChildKey: 35
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 50
.head 7 -  Class ChildKey: 36
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDClose
.head 7 -  Class Child Ref Key: 54
.head 7 -  Class ChildKey: 37
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDRead
.head 7 -  Class Child Ref Key: 55
.head 7 -  Class ChildKey: 38
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 -  Background Text: Cult.Id
.head 6 -  Resource Id: 13499
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 16
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.038"
.head 7 -  Top: 0.135"
.head 7 -  Width:  0.575"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Cultivar Description
.head 6 -  Resource Id: 13498
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 17
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.95"
.head 7 -  Top: 0.375"
.head 7 -  Width:  1.663"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Data Field: dfCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 18
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.663"
.head 8 -  Top: 0.094"
.head 8 -  Width:  0.975"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 19
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.663"
.head 8 -  Top: 0.344"
.head 8 -  Width:  7.2"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  !
.head 5 +  Child Table: tblCultProhibition
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 20
.head 6 -  Class: clsTableGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.025"
.head 8 -  Top: 0.688"
.head 8 -  Width:  9.838"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 4.083"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colProhibSysDT
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 21
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title:
.head 8 -  Visible? No
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Date/Time
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.975"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Set colProhibSysDT = GetUniqueCurrentSysDT(  )
.head 10 -  Return TRUE
.head 7 +  Column: colProhibYear
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 22
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Year
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.588"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: #0
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_DATAVAL
.head 10 -  Call AdjustYearToYearOfSale( colProhibYear )
.head 10 -  Return TRUE
.head 7 +  Column: colProhibEnteredBy
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 23
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Entered By
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.088"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 -  Set colProhibEnteredBy = SqlUser
.head 10 -  Return TRUE
.head 7 +  Column: colProhibState
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 24
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: State
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.638"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Drop Down List
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? No
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 +  List Values
.head 9 -  Text: NSW
.head 9 -  Text: NT
.head 9 -  Text: QLD
.head 9 -  Text: SA
.head 9 -  Text: TAS
.head 9 -  Text: VIC
.head 9 -  Text: WA
.head 8 -  Message Actions
.head 7 +  Column: colProhibWhoBy
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 25
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Prohibited By
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: 254
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  3.575"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPollReason
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 26
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Reason
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: 254
.head 8 -  Data Type: String
.head 8 -  Justify: Class Default
.head 8 -  Width:  3.0"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPollComments
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 27
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Comments
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: String
.head 8 -  Justify: Class Default
.head 8 -  Width:  4.138"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 6 -  Functions
.head 6 -  Window Variables
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set sSQLPopHandle = ' SELECT 
  Prohibition.Prohib_Date_Time, 
  Prohibition.Year_Of_Prohib, 
  Prohibition.Prohib_Entered_By, 
  Prohibition.State_Prohib_In, 
  Prohibition.Prohib_Who_By, 
  Prohibition.Prohib_Reason, 
  Prohibition.Prohib_Comments  
FROM 
  Prohibition 
WHERE 
  Prohibition.Cult_Id = :1'
.head 8 -  Set sNAMEPopHandle = 'CULTPROHIB'
.head 8 -  Set sBINDPopHandle = ':hWndParent.dfCultId'
.head 8 -  Set sINTOPopHandle = ':clsfrmCultProhibition.tblCultProhibition.colProhibSysDT, 
:clsfrmCultProhibition.tblCultProhibition.colProhibYear, 
:clsfrmCultProhibition.tblCultProhibition.colProhibEnteredBy,
:clsfrmCultProhibition.tblCultProhibition.colProhibState, 
:clsfrmCultProhibition.tblCultProhibition.colProhibWhoBy,
:clsfrmCultProhibition.tblCultProhibition.colPollReason, 
:clsfrmCultProhibition.tblCultProhibition.colPollComments'
.head 8 -  !
.head 8 -  Set sSQLRefreshHandle = ' SELECT 
  Prohibition.State_Prohib_In, 
  Prohibition.Prohib_Who_By, 
  Prohibition.Prohib_Reason, 
  Prohibition.Prohib_Comments  
FROM 
  Prohibition 
WHERE 
  Prohibition.Cult_Id = :1 AND 
  Prohibition.Prohib_Date_Time = :2 AND 
  Prohibition.Year_Of_Prohib = :3 AND 
  Prohibition.Prohib_Entered_By = :4 '
.head 8 -  Set sNAMERefreshHandle = 'REFCULTPROHIB'
.head 8 -  Set sBINDRefreshHandle = ':hWndParent.dfCultId, 
:clsfrmCultProhibition.tblCultProhibition.colProhibSysDT, 
:clsfrmCultProhibition.tblCultProhibition.colProhibYear, 
:clsfrmCultProhibition.tblCultProhibition.colProhibEnteredBy'
.head 8 -  Set sINTORefreshHandle = ':clsfrmCultProhibition.tblCultProhibition.colProhibState, 
:clsfrmCultProhibition.tblCultProhibition.colProhibWhoBy,
:clsfrmCultProhibition.tblCultProhibition.colPollReason, 
:clsfrmCultProhibition.tblCultProhibition.colPollComments'
.head 8 -  !
.head 8 -  Set sSQLInsertHandle = 'INSERT INTO Prohibition 
( Cult_Id, 
  Prohib_Date_Time, 
  Year_Of_Prohib, 
  Prohib_Entered_By, 
  State_Prohib_In, 
  Prohib_Who_By, 
  Prohib_Reason, 
  Prohib_Comments  ) 
VALUES ( :1, :2, :3, :4, :5, :6, :7, :8 ) '
.head 8 -  Set sNAMEInsertHandle = 'INSCULTPROHIB'
.head 8 -  Set sBINDInsertHandle = ':hWndParent.dfCultId, 
:clsfrmCultProhibition.tblCultProhibition.colProhibSysDT, 
:clsfrmCultProhibition.tblCultProhibition.colProhibYear, 
:clsfrmCultProhibition.tblCultProhibition.colProhibEnteredBy,
:clsfrmCultProhibition.tblCultProhibition.colProhibState, 
:clsfrmCultProhibition.tblCultProhibition.colProhibWhoBy,
:clsfrmCultProhibition.tblCultProhibition.colPollReason, 
:clsfrmCultProhibition.tblCultProhibition.colPollComments'
.head 8 -  Set sINTOInsertHandle = ''
.head 8 -  !
.head 8 -  Set sSQLUpdateHandle = ' UPDATE Prohibition 
SET 
  State_Prohib_In = :5, 
  Prohib_Who_By = :6, 
  Prohib_Reason = :7, 
  Prohib_Comments = :8 
WHERE 
  Cult_Id = :1 AND 
  Prohib_Date_Time = :2 AND 
  Year_Of_Prohib = :3 AND 
  Prohib_Entered_By = :4 '
.head 8 -  Set sNAMEUpdateHandle = 'UPDTCULTPROHIB'
.head 8 -  Set sBINDUpdateHandle = ':hWndParent.dfCultId, 
:clsfrmCultProhibition.tblCultProhibition.colProhibSysDT, 
:clsfrmCultProhibition.tblCultProhibition.colProhibYear, 
:clsfrmCultProhibition.tblCultProhibition.colProhibEnteredBy,
:clsfrmCultProhibition.tblCultProhibition.colProhibState, 
:clsfrmCultProhibition.tblCultProhibition.colProhibWhoBy,
:clsfrmCultProhibition.tblCultProhibition.colPollReason, 
:clsfrmCultProhibition.tblCultProhibition.colPollComments'
.head 8 -  Set sINTOUpdateHandle = ''
.head 8 -  !
.head 8 -  Set sSQLDeleteHandle = ' DELETE FROM Prohibition 
WHERE 
  Cult_Id = :1 AND 
  Prohib_Date_Time = :2 AND 
  Year_Of_Prohib = :3 AND 
  Prohib_Entered_By = :4 '
.head 8 -  Set sNAMEDeleteHandle = 'DELCULTPROHIB'
.head 8 -  Set sBINDDeleteHandle = ':hWndParent.dfCultId, 
:clsfrmCultProhibition.tblCultProhibition.colProhibSysDT, 
:clsfrmCultProhibition.tblCultProhibition.colProhibYear, 
:clsfrmCultProhibition.tblCultProhibition.colProhibEnteredBy'
.head 8 -  Set sINTODeleteHandle = ''
.head 8 -  !
.head 8 -  Set bAddAllowed = TRUE
.head 8 -  Set bSaveAllowed = TRUE
.head 8 -  Set bDeleteAllowed = TRUE
.head 8 -  Set bUnDeleteAllowed = TRUE
.head 8 -  Set bRepopulateAllowed = TRUE
.head 8 -  Set bClearSelectAllowed = TRUE
.head 8 -  Set bQueryAllowed = TRUE
.head 8 -  Set bReportAllowed = FALSE
.head 8 -  Set bOrderAllowed = TRUE
.head 8 -  !
.head 8 -  Set sQueryDialogName = 'dlgQueryCultProhibition'
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 28
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 47
.head 6 -  Class ChildKey: 29
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 27859
.head 6 -  Class Child Ref Key: 48
.head 6 -  Class ChildKey: 30
.head 6 -  Class: clsFormChildTable
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 49
.head 6 -  Class ChildKey: 31
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  Set hWndChildTable = tblCultProhibition
.head 6 -  ! Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 5 +  On PAM_clsFRM_POPFIELDS
.head 6 -  Call PopString( dfCultDesc, TRUE )
.head 6 -  Call PopString( dfCultId, TRUE )
.head 6 -  Return TRUE
.head 3 +  Dialog Box Class: clsdlgQueryCultProhibition
.head 4 -  Title: Query Cultivar Prohibitions
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  7.975"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 2.177"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 14
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 16
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 3.738"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 17
.head 7 -  Class ChildKey: 7
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.65"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClear
.head 7 -  Class Child Ref Key: 19
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 20
.head 7 -  Class ChildKey: 14
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 -  Background Text: Cultivar Id
.head 6 -  Resource Id: 13500
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.663"
.head 7 -  Top: 0.75"
.head 7 -  Width:  0.913"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 +  Data Field: dfCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 10
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.538"
.head 8 -  Top: 0.709"
.head 8 -  Width:  0.963"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Uppercase
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCultId.sSQLCOLNAME = 'PROHIBITION.CULT_ID'
.head 8 -  Set dfCultId.hWndOperatorField = cmbCultIdOp
.head 8 -  Set dfCultId.hWndNotField = cbNOTCultId
.head 5 -  !
.head 5 +  Check Box: cbNOTCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 11
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 2.05"
.head 7 -  Top: 0.709"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCultId.hWndQueryField = dfCultId
.head 5 -  !
.head 5 +  Combo Box: cmbCultIdOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 12
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.625"
.head 7 -  Top: 0.709"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCultIdOp.hWndQueryField = dfCultId
.head 8 -  Set cmbCultIdOp.sOperator = ' = '
.head 5 -  !
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 12
.head 6 -  Class ChildKey: 1
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 13
.head 6 -  Class ChildKey: 2
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 14
.head 6 -  Class ChildKey: 3
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.863"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 13501
.head 6 -  Class Child Ref Key: 15
.head 6 -  Class ChildKey: 4
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Window Location and Size
.head 7 -  Left: 6.113"
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 4 +  Derived From
.head 5 -  Class: clsTblQueryDialog
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bMapEnterToTab = TRUE
.head 6 -  Set hWndFirstFocus = dfCultId
.head 3 -  !
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  ! clsFormChildTable: frmCultProhibition
.head 2 -  Description: 
.head 2 -  Named Menus 
.head 2 -  Menu 
.head 2 +  Tool Bar 
.head 3 +  Contents 
.head 4 +  Pushbutton: pbHelp
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbQuery
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbExit
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbTools
.head 5 -  Message Actions 
.head 2 +  Contents 
.head 3 +  Data Field: dfDatabase
.head 4 -  Message Actions 
.head 3 +  Data Field: dfUser
.head 4 -  Message Actions 
.head 3 -  !
.head 3 -  Background Text: Cult.Id
.head 3 -  Background Text: Cultivar Description
.head 3 +  Data Field: dfCultId
.head 4 -  Message Actions 
.head 3 +  Data Field: dfCultDesc
.head 4 -  Message Actions 
.head 3 -  !
.head 3 +  Child Table: tblCultProhibition
.head 4 +  Contents 
.head 5 +  Column: colProhibSysDT
.head 6 -  List Values 
.head 6 +  Message Actions 
.head 7 +  On PAM_clsTBL_CHECKROWNEW
.head 8 -  Set colProhibSysDT = GetUniqueCurrentSysDT(  )
.head 8 -  Return TRUE
.head 5 +  Column: colProhibYear
.head 6 -  List Values 
.head 6 +  Message Actions 
.head 7 +  On PAM_clsTBL_DATAVAL
.head 8 -  Call AdjustYearToYearOfSale( colProhibYear )
.head 8 -  Return TRUE
.head 5 +  Column: colProhibEnteredBy
.head 6 -  List Values 
.head 6 +  Message Actions 
.head 7 +  On PAM_clsTBL_CHECKROWNEW
.head 8 -  Set colProhibEnteredBy = SqlUser
.head 8 -  Return TRUE
.head 5 +  Column: colProhibState
.head 6 +  List Values 
.head 7 -  Text: NSW
.head 7 -  Text: NT
.head 7 -  Text: QLD
.head 7 -  Text: SA
.head 7 -  Text: TAS
.head 7 -  Text: VIC
.head 7 -  Text: WA
.head 6 -  Message Actions 
.head 5 +  Column: colProhibWhoBy
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colPollReason
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colPollComments
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 4 -  Functions 
.head 4 -  Window Variables 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set sSQLPopHandle = ' SELECT 
  Prohibition.Prohib_Date_Time, 
  Prohibition.Year_Of_Prohib, 
  Prohibition.Prohib_Entered_By, 
  Prohibition.State_Prohib_In, 
  Prohibition.Prohib_Who_By, 
  Prohibition.Prohib_Reason, 
  Prohibition.Prohib_Comments  
FROM 
  Prohibition 
WHERE 
  Prohibition.Cult_Id = :1'
.head 6 -  Set sNAMEPopHandle = 'CULTPROHIB'
.head 6 -  Set sBINDPopHandle = ':hWndParent.dfCultId'
.head 6 -  Set sINTOPopHandle = ':hWndForm.colProhibSysDT, 
:hWndForm.colProhibYear, 
:hWndForm.colProhibEnteredBy,
:hWndForm.colProhibState, 
:hWndForm.colProhibWhoBy,
:hWndForm.colPollReason, 
:hWndForm.colPollComments'
.head 6 -  !
.head 6 -  Set sSQLRefreshHandle = ' SELECT 
  Prohibition.State_Prohib_In, 
  Prohibition.Prohib_Who_By, 
  Prohibition.Prohib_Reason, 
  Prohibition.Prohib_Comments  
FROM 
  Prohibition 
WHERE 
  Prohibition.Cult_Id = :1 AND 
  Prohibition.Prohib_Date_Time = :2 AND 
  Prohibition.Year_Of_Prohib = :3 AND 
  Prohibition.Prohib_Entered_By = :4 '
.head 6 -  Set sNAMERefreshHandle = 'REFCULTPROHIB'
.head 6 -  Set sBINDRefreshHandle = ':hWndParent.dfCultId, 
:hWndForm.colProhibSysDT, 
:hWndForm.colProhibYear, 
:hWndForm.colProhibEnteredBy'
.head 6 -  Set sINTORefreshHandle = ':hWndForm.colProhibState, 
:hWndForm.colProhibWhoBy,
:hWndForm.colPollReason, 
:hWndForm.colPollComments'
.head 6 -  !
.head 6 -  Set sSQLInsertHandle = 'INSERT INTO Prohibition 
( Cult_Id, 
  Prohib_Date_Time, 
  Year_Of_Prohib, 
  Prohib_Entered_By, 
  State_Prohib_In, 
  Prohib_Who_By, 
  Prohib_Reason, 
  Prohib_Comments  ) 
VALUES ( :1, :2, :3, :4, :5, :6, :7, :8 ) '
.head 6 -  Set sNAMEInsertHandle = 'INSCULTPROHIB'
.head 6 -  Set sBINDInsertHandle = ':hWndParent.dfCultId, 
:hWndForm.colProhibSysDT, 
:hWndForm.colProhibYear, 
:hWndForm.colProhibEnteredBy,
:hWndForm.colProhibState, 
:hWndForm.colProhibWhoBy,
:hWndForm.colPollReason, 
:hWndForm.colPollComments'
.head 6 -  Set sINTOInsertHandle = ''
.head 6 -  !
.head 6 -  Set sSQLUpdateHandle = ' UPDATE Prohibition 
SET 
  State_Prohib_In = :5, 
  Prohib_Who_By = :6, 
  Prohib_Reason = :7, 
  Prohib_Comments = :8 
WHERE 
  Cult_Id = :1 AND 
  Prohib_Date_Time = :2 AND 
  Year_Of_Prohib = :3 AND 
  Prohib_Entered_By = :4 '
.head 6 -  Set sNAMEUpdateHandle = 'UPDTCULTPROHIB'
.head 6 -  Set sBINDUpdateHandle = ':hWndParent.dfCultId, 
:hWndForm.colProhibSysDT, 
:hWndForm.colProhibYear, 
:hWndForm.colProhibEnteredBy,
:hWndForm.colProhibState, 
:hWndForm.colProhibWhoBy,
:hWndForm.colPollReason, 
:hWndForm.colPollComments'
.head 6 -  Set sINTOUpdateHandle = ''
.head 6 -  !
.head 6 -  Set sSQLDeleteHandle = ' DELETE FROM Prohibition 
WHERE 
  Cult_Id = :1 AND 
  Prohib_Date_Time = :2 AND 
  Year_Of_Prohib = :3 AND 
  Prohib_Entered_By = :4 '
.head 6 -  Set sNAMEDeleteHandle = 'DELCULTPROHIB'
.head 6 -  Set sBINDDeleteHandle = ':hWndParent.dfCultId, 
:hWndForm.colProhibSysDT, 
:hWndForm.colProhibYear, 
:hWndForm.colProhibEnteredBy'
.head 6 -  Set sINTODeleteHandle = ''
.head 6 -  !
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bRepopulateAllowed = TRUE
.head 6 -  Set bClearSelectAllowed = TRUE
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  !
.head 6 -  Set sQueryDialogName = 'dlgQueryCultProhibition'
.head 3 -  Background Text: Season
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 -  Window Parameters 
.head 2 -  Window Variables 
.head 2 +  Message Actions 
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set bQueryAllowed = TRUE
.head 4 -  Set bAddAllowed = TRUE
.head 4 -  Set bSaveAllowed = TRUE
.head 4 -  Set bDeleteAllowed = TRUE
.head 4 -  Set bUnDeleteAllowed = TRUE
.head 4 -  Set bReportAllowed = FALSE
.head 4 -  Set bOrderAllowed = TRUE
.head 4 -  Set hWndChildTable = tblCultProhibition
.head 4 -  ! Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 3 +  On PAM_clsFRM_POPFIELDS
.head 4 -  Call PopString( dfCultDesc, TRUE )
.head 4 -  Call PopString( dfCultId, TRUE )
.head 4 -  Return TRUE
.head 1 +  ! clsTblQueryDialog: dlgQueryCultProhibition
.head 2 -  Description: 
.head 2 +  Tool Bar 
.head 3 +  Contents 
.head 4 +  Pushbutton: pbQuery
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbHelp
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbExit
.head 5 -  Message Actions 
.head 2 +  Contents 
.head 3 -  !
.head 3 -  Background Text: Cultivar Id
.head 3 -  !
.head 3 +  Data Field: dfCultId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set dfCultId.sSQLCOLNAME = 'PROHIBITION.CULT_ID'
.head 6 -  Set dfCultId.hWndOperatorField = cmbCultIdOp
.head 6 -  Set dfCultId.hWndNotField = cbNOTCultId
.head 3 -  !
.head 3 +  Check Box: cbNOTCultId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cbNOTCultId.hWndQueryField = dfCultId
.head 3 -  !
.head 3 +  Combo Box: cmbCultIdOp
.head 4 -  List Initialization 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cmbCultIdOp.hWndQueryField = dfCultId
.head 6 -  Set cmbCultIdOp.sOperator = ' = '
.head 3 -  !
.head 3 +  Data Field: dfUser
.head 4 -  Message Actions 
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Message Actions 
.head 3 -  Background Text: Season
.head 3 +  Data Field: dfDatabase
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 -  Window Parameters 
.head 2 -  Window Variables 
.head 2 +  Message Actions 
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set bMapEnterToTab = TRUE
.head 4 -  Set hWndFirstFocus = dfCultId
.head 1 +  Form Window: frmCultProhibition
.head 2 -  Class: clsfrmCultProhibition
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? No
.head 4 -  Toolbar Docking Orientation: Top | Bottom
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? No
.head 3 +  Contents
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Class Child Ref Key: 8
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Class Child Ref Key: 12
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbTools
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Class Child Ref Key: 32
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 33
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 34
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 35
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 36
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDClose
.head 5 -  Class Child Ref Key: 37
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDRead
.head 5 -  Class Child Ref Key: 38
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 13503
.head 4 -  Class Child Ref Key: 16
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 13504
.head 4 -  Class Child Ref Key: 17
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCultId
.head 4 -  Class Child Ref Key: 18
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCultDesc
.head 4 -  Class Child Ref Key: 19
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Child Table: tblCultProhibition
.head 4 -  Class Child Ref Key: 20
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colProhibSysDT
.head 6 -  Class Child Ref Key: 21
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultProhibition
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colProhibYear
.head 6 -  Class Child Ref Key: 22
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultProhibition
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colProhibEnteredBy
.head 6 -  Class Child Ref Key: 23
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultProhibition
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colProhibState
.head 6 -  Class Child Ref Key: 24
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultProhibition
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colProhibWhoBy
.head 6 -  Class Child Ref Key: 25
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultProhibition
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPollReason
.head 6 -  Class Child Ref Key: 26
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultProhibition
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPollComments
.head 6 -  Class Child Ref Key: 27
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmCultProhibition
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 4 -  Functions
.head 4 -  Window Variables
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 28
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 29
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 27860
.head 4 -  Class Child Ref Key: 30
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 31
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
.head 1 +  Dialog Box: dlgQueryCultProhibition
.head 2 -  Class: clsdlgQueryCultProhibition
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.138"
.head 4 -  Top: 1.417"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? No
.head 4 -  Toolbar Docking Orientation: Top | Bottom
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? No
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 5
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 7
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClear
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 14
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryCultProhibition
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 13505
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCultId
.head 4 -  Class Child Ref Key: 10
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTCultId
.head 4 -  Class Child Ref Key: 11
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbCultIdOp
.head 4 -  Class Child Ref Key: 12
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 3
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 13506
.head 4 -  Class Child Ref Key: 4
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryCultProhibition
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
