.head 0 +  Application Description: SQLWindows 5.01 Stock Or Stockdev login APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C636C6173
0040: 733B6B3A5C63656E 747572615C666C65 6D61706C73000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF000000 0000000000900200 0039010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D02000000075769 6E646F777308646C
0080: 674C6F67696E
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: VTWIN.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: picture.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 3 +  ! Library name: nwconn.dll
.head 4 +    Function: GetConnectionNumber
.head 5 -    Description: 
.head 5 -    Export Ordinal: 10
.head 5 +    Returns 
.head 6 -    Number: WORD
.head 5 -    Parameters 
.head 4 +    Function: GetConnectionInformation
.head 5 -    Description: 
.head 5 -    Export Ordinal: 9
.head 5 +    Returns 
.head 6 -    Number: WORD
.head 5 +    Parameters 
.head 6 -    Number: WORD
.head 6 -    Receive String: LPSTR
.head 6 -    Receive Number: LPWORD
.head 6 -    Receive Number: LPLONG
.head 6 -    Receive Number: LPLONG
.head 3 +  Library name: advapi32.dll
.head 4 -  ThreadSafe: No
.head 4 +  Function: GetUserNameA
.head 5 -  Description:
.head 5 -  Export Ordinal: 0
.head 5 +  Returns
.head 6 -  Boolean: BOOL
.head 5 +  Parameters
.head 6 -  Receive String: LPSTR
.head 6 -  Receive Number: LPDWORD
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for FLMLOGIN.APL
.head 4 -  Number: FLMLOGINAplMsgOffSet = SAM_User + 2900
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  !
.head 4 -  Number: FLMLOGINAplConstOffSet = 1400
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 599986411
0000: D600000099000000 0000000000000000 0200000700000046 0100005019000000
0020: 0100E05602000000 4073000000010000 A35F010019250001 20EE05B800000073
0040: D100010000687801 001900090120DE0B 00006E0073003401 000091015A001900
0060: 01A220DF0B00001B 730001008D00AA01 005619000400E00C 0F00000066730001
0080: 00A3C30100192500 01203825B8000000 73D10001000068DC 0100190009012074
00A0: 2B00006E00730034 010000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 3 +  Function: GetUser
.head 4 -  Description:
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Receive String: sUser
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: nBuffer
.head 4 +  Actions
.head 5 -  Call SalStrSetBufferLength( sUser, 100 )
.head 5 -  Set nBuffer = 100
.head 5 -  Call GetUserNameA( sUser, nBuffer )
.head 5 -  Set sUser = SalStrUpperX ( sUser )
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1015819425
0000: 1B0E00000D090000 0000000000000000 0200001A00FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F53003C00 001063006C734469
0040: 616C6F670047656E 6572616C9A800000 0005000000871900 0000800178011200
0060: 0000014601730000 0001D80000001920 0004000000027860 011300000046CF00
0080: 0106001D00000019 0B0004780114D800 000046B300010081 3600000004000200
00A0: 037801150000F600 466C0001003AB000 0000190084017816 0000003D4600011A
00C0: 0000018019220000 0100000C84636C70 6247650F22000000 F601009619000178
00E0: 3007000000B80146 7300010000030180 6800000080020000 0009636C0348656C
0100: 709A00D90005005B 040002DE780018C4 01730001006D0004 009619000178B008
0120: 000000C447000100 009B1D0019250001 780900EC0000C4D1 0001000066360019
0140: 000901780A000000 7BC400340100004F 00580000190001C2 780B0000001EC400
0160: 01008D0001801981 0003000000090F45 7869744422000001 00006F1900690178
0180: 070063DC01730034 0100000180640400 0004000E0C506963 45807870616E6422
01A0: 00E800010000AD04 00026F0054C80273 000001C600018004 0C00050012636C0F
01C0: 546F6767006C6542 7574746F6E442200 000100006F04000D 0206000000636002
01E0: 7300360100018046 04000600000E0C64 664765FFE8000100 002D040003786F00
0200: 7ECC02730001C600 018004C800070000 0CF17262471F0001 00BD0004F500028D
0220: 00C00273D9000100 1801801900080021 0011636C53700069 6E536561736F6E40
0240: 59656172220000F4 0100009619000178 3700FC0246730001 0000430180530000
0260: 840900000B636C00 466F726D42617365 649A000005006F19 0069017808004368
0280: 03730000B4010000 195900040002DB09 009E6800016D001D 009619000478B60A
02A0: 0068670001001B36 000400B500030BED 0068D9000100663A 0019000901780C00
02C0: 00007B6800340100 0001804619000A00 00F817636C805072 696E744261006963
02E0: 5265706F72744622 000100006F190069 0178090063E60373 0034010000018040
0300: 460000000B00002E 1170537400617274 50726F677280616D D600000007BD0004
0320: B50002060D003404 7300D10001000066 040004006D020700 7B3400B601000859
0340: 00040002DB08009E 3400014D000C0000 9619000178B60900 3447000100008325
0360: 00000004B500030A ED0034D900010060 2900000004006D02 0B007B3400360100
0380: 2D00580000190001 DA780C001E340001 000D000180520018 00000C000F63F26C
03A0: 53743F3001DA000A 005B190001D27805 0000184604730001 006D001900961900
03C0: 0178B60600464700 0100008332000000 04B5000207ED0046 D900010066360004
03E0: 006D0208007B4600 B601003A59000400 02DB09009E460001 0D003E000000D604
0400: 0002B60A00466700 0100834200000004 B500020BED0046D9 0001006446000004
0420: 006D020C00734604 003601004A005800 00040002C30D0000 009E4600010D004E
0440: 000000D6040002B0 0E00000046670001 006301800400E40D 00001000546F6F6C
0460: 5469705780696E64 6F772200E8000100 00AD040003ED0500 C805730000018600
0480: 01801D0088000E00 000C63F163624701 6C400000000200BD 0019A5000178068D
04A0: 00840573D1000100 0066190004006902 7807007B84003601 0001800064000000
04C0: 0F0000006814636C 7065006C65637446 726F6D005461626C 657C0000EC000400
04E0: 2D190001786F00DE 8C05730001003600 1900194B00017808 DB00DEA300010000
0500: CD320019D2000178 09F600DE68000100 004BB00000001900 B401780A003DDE00
0520: 011A000001800403 00100000000D6463 6C53656381496E74 6F2200E800010000
0540: AD0400036D0500F6 CC05730001C60001 801DC00011000000 0D076E64456D6120
0560: 696C73400000027A 000019CB0001781B 008C0673A2000001 0000CD190004D200
0580: 027806F6008C6C00 01000190803B0100 1200900016636C47 65CE655461F94765
05A0: 488A02001500006F 19007901780063CE 067300B401000019 5900190001DA7807
05C0: 001ECE0001006D00 32009619000178B6 0800CE4700010000 9B4B0019A5000178
05E0: 09ED00CED1000100 006464000004006D 020A007BCE003601 0068005900040002
0600: DB0B009ECE00010D 006C000000D60400 02B40C0000CE6700 0100837000000004
0620: B500020DED00CED9 0001006074000000 04006D020E007BCE 0036010078005800
0640: 00040002D30F0000 9ECE00014D007C00 00D6040002B41000 00CE670001008B80
0660: 000004A100010278 12FD000780010000 00FF608400000019 00680101781300FF
0680: C980010000BF8858 0000190001DA7814 001ECE0001000D00 A100000096190001
06A0: 78B61600CE470001 000083BA00000019 250001781700EC00 00CED10001000060
06C0: D300000019000901 78180000007BCE00 34010000EC005800 00190001C2781A00
06E0: 00001ECE0001008D 0005010096190001 78B01C000000CE47 00010000A31E0100
0700: 19250001781D00ED 00CED10001000068 37010004000D031E 0000007BCE003601
0720: 000180443A000013 0000081D636C5462 6C4D40616B655365 6C63016564526F77
0740: 4B65007941727261 798400D90004001B 04000102DB05007F 80F20100006F0400
0760: 9619000178360600 1607447300000100 00931D000019A500 017807ED0016D100
0780: 0100006636000400 6D0208007B160036 01000180461D0014 00000C1063436F6C
07A0: 75F06D6E47658C6C 40000200DE0004D2 00027805C6002807 73680001000004B3
07C0: 001900B401780600 3D2800011A000001 8081300000001500 08E063514F456D60
07E0: C000000006006F19 0069017805004332 09730000B4010000 195900190001DA78
0800: 08001E320001004D 0032000096190001 78360B0032094700 0100009B4B0019A5
0820: 0001780EED0032D1 0001000066640019 004901781100007B 3200340100007D00
0840: 18000004000102DB 14007F80F2010000 8F01800491001600 000CC36D6C476537
0860: 2200017A0000046B 0003051B003E0973 B300010031018004 00171200000C6654
0880: 6103654361636865 442200000100006F 04006D0307006380 0973003201000001
08A0: 8040210000001800 00E00B6366436108 506F6F66000000F4 0300000629000107
08C0: 7801810001008009 009E008001FC0000 9B040004A5000378 098D008C0973D900
08E0: 0100640800001900 6901780A007B8C00 3401000001806619 001900000C67774D
0900: 6F757365C0576865 656C22E800010000 2D19000178EF0089 73000001000600
.enddata
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text: clsBackTextGeneral
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  Dialog Box: dlgLogin
.head 2 -  Class: clsDialogGeneral
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Fleming's Nurseries Login
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 2.2"
.head 4 -  Top: 0.865"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 4.365"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: 0.438"
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 0.1"
.head 6 -  Top: 0.021"
.head 6 -  Width:  0.475"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.385"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: Query.bmp
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Single
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clspbOk
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.213"
.head 6 -  Top: 0.021"
.head 6 -  Width:  0.475"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.385"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: Enter
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: OK.BMP
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Single
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 +  Message Actions
.head 6 +  On PAM_clsPB_CLICK
.head 7 +  If SqlDatabase = 'STOCK'
.head 8 -  Set sDatabase = 'LIVE'
.head 7 +  Else
.head 8 -  Set sDatabase = 'PLAY'
.head 7 -  !
.head 7 +  When SqlError
.head 8 -  Call SalMessageBox( 'Error!  Please try again.','Login', MB_Ok )
.head 7 -  Set bOk = SqlConnect( hSqlA )
.head 7 +  If bOk
.head 8 -  Call SqlDisconnect( hSqlA )
.head 8 -  Call SalEndDialog( hWndForm,TRUE )
.head 7 +  Else
.head 8 -  Call SalEndDialog( hWndForm, FALSE )
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 4.238"
.head 6 -  Top: 0.021"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.469"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? No
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: EXIT.ICO
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Single
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 15
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 4.388"
.head 6 -  Top: Class Default
.head 6 -  Width:  0.475"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.385"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 8
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  !
.head 3 +  Data Field: dfHeading
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdfGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.038"
.head 6 -  Top: 0.333"
.head 6 -  Width:  4.813"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.417"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? No
.head 5 -  Justify: Center
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 24
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Picture: pic1
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsPicture
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: 0.688"
.head 5 -  Top: 0.833"
.head 5 -  Width:  3.55"
.head 5 -  Width Editable? Class Default
.head 5 -  Height: 1.625"
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  File Name: C:\Centura\icons\pictures\Flemrain.tif
.head 4 -  Storage: Class Default
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Fit: Class Default
.head 4 -  Scaling
.head 5 -  Width:  Class Default
.head 5 -  Height:  Class Default
.head 4 -  Corners: Class Default
.head 4 -  Border Style: Class Default
.head 4 -  Border Thickness: Class Default
.head 4 -  Tile To Parent? Class Default
.head 4 -  Border Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 +  Message Actions
.head 5 +  ! On SAM_Create
.head 6 -   Call pic1.GetPicToLoad(  )
.head 6 -   Call pic1.LoadPic(  )
.head 3 -  Background Text: Please SELECT a Login ?
.head 4 -  Resource Id: 20867
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsBackTextGeneral
.head 4 -  Window Location and Size
.head 5 -  Left: 0.7"
.head 5 -  Top: 2.625"
.head 5 -  Width:  3.538"
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Center
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Black
.head 4 -  Background Color: Class Default
.head 3 +  Radio Button: rbLive
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: LIVE System
.head 4 -  Window Location and Size
.head 5 -  Left: 0.988"
.head 5 -  Top: 2.927"
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Bold
.head 4 -  Text Color: Blue
.head 4 -  Background Color: Class Default
.head 4 +  Message Actions
.head 5 +  On PAM_clsRB_CLICK
.head 6 -  Set dfHeading = "Fleming's LIVE System"
.head 6 -  Set SqlDatabase = 'STOCK'
.head 6 -  Set dfDatabase = SqlDatabase
.head 6 -  Call SalColorSet( dfHeading, COLOR_IndexWindowText, COLOR_Blue )
.head 3 +  Radio Button: rbPlay
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: PLAY System
.head 4 -  Window Location and Size
.head 5 -  Left: 2.638"
.head 5 -  Top: 2.927"
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Bold
.head 4 -  Text Color: Red
.head 4 -  Background Color: Class Default
.head 4 +  Message Actions
.head 5 +  On PAM_clsRB_CLICK
.head 6 -  Set dfHeading = "Fleming's PLAY System"
.head 6 -  Set SqlDatabase = 'STOCKDEV'
.head 6 -  Set dfDatabase = SqlDatabase
.head 6 -  Call SalColorSet( dfHeading, COLOR_IndexWindowText, COLOR_Red )
.head 3 +  Radio Button: rbLocal
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: LOCAL System
.head 4 -  Window Location and Size
.head 5 -  Left: 2.638"
.head 5 -  Top: 3.229"
.head 5 -  Width:  1.45"
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Bold
.head 4 -  Text Color: Red
.head 4 -  Background Color: Class Default
.head 4 +  Message Actions
.head 5 +  On PAM_clsRB_CLICK
.head 6 -  Set dfHeading = "Fleming's LOCAL System"
.head 6 -  Set SqlDatabase = 'STKLOCAL'
.head 6 -  Set dfDatabase = SqlDatabase
.head 6 -  Call SalColorSet( dfHeading, COLOR_IndexWindowText, COLOR_Red )
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 13
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 35211
.head 4 -  Class Child Ref Key: 14
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  String: sStartDatabase
.head 3 -  String: sStartUser
.head 2 +  Window Variables
.head 3 -  Number: nConnection 
.head 3 -  String: sUserName 
.head 3 -  Number: nType
.head 3 -  Number: nID
.head 3 -  Number: nLoginTime
.head 3 -  Number: nRetCode
.head 3 -  Sql Handle: hSqlA
.head 3 -  Boolean: bOk
.head 2 +  Message Actions
.head 3 +  On SAM_Create
.head 4 -  ! Set nConnection=NWGetConnectionNumber()
.head 4 -  ! Call SalStrSetBufferLength( sUserName,20 )
.head 4 -  ! Set nRetCode=NWGetConnectionInformation(nConnection,sUserName,nType,nID,nLoginTime)
.head 4 -  Call GetUser( sUserName )
.head 4 +  If sUserName = ''
.head 5 -  Call SalModalDialog( dlgDatabaseInfo, hWndForm )
.head 5 -  Set dfUser = SqlUser
.head 5 -  Set sUserName = SqlUser
.head 4 +  If sUserName = 'SUPERVISOR'
.head 5 -  Set SqlUser = 'SYSADM'
.head 5 -  Set SqlPassword = 'DANI'
.head 4 +  Else If sUserName = 'ADMIN'
.head 5 -  Set SqlUser = 'SYSADM'
.head 5 -  Set SqlPassword = 'DANI'
.head 4 +  Else
.head 5 -  Set sUserName = SalStrLeftX( sUserName, 8 )
.head 5 -  Set SqlDatabase = ''
.head 5 -  Set SqlUser = sUserName
.head 5 -  Set SqlPassword = sUserName
.head 4 +  If sStartDatabase = 'STOCKDEV'
.head 5 -  Set rbPlay = TRUE
.head 4 +  Else If sStartDatabase = 'STKLOCAL'
.head 5 -  Set rbLocal = TRUE
.head 4 +  Else
.head 5 -  Set rbLive = TRUE
.head 4 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 3 +  On SAM_CreateComplete
.head 4 -  Call SalSetFocus(pbOk)
.head 4 +  If rbPlay
.head 5 -  Call SalSendMsg( rbPlay, SAM_Click, 0, 0 )
.head 4 +  Else If rbLocal
.head 5 -  Call SalSendMsg( rbLocal, SAM_Click, 0, 0 )
.head 4 +  Else
.head 5 -  Call SalSendMsg( rbLive, SAM_Click, 0, 0 )
.head 4 -  Return SalSendClassMessage( SAM_CreateComplete, wParam, lParam )
