.head 0 +  Application Description: SQLWindows 5.01 Stock Or Stockdev login APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C636C6173
0040: 733B6B3A5C63656E 747572615C666C65 6D61706C73000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF000000 0000000000900200 0039010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D02000000075769 6E646F777308646C
0080: 674C6F67696E
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: VTWIN.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: picture.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 3 +  ! Library name: nwconn.dll
.head 4 +    Function: GetConnectionNumber
.head 5 -    Description: 
.head 5 -    Export Ordinal: 10
.head 5 +    Returns 
.head 6 -    Number: WORD
.head 5 -    Parameters 
.head 4 +    Function: GetConnectionInformation
.head 5 -    Description: 
.head 5 -    Export Ordinal: 9
.head 5 +    Returns 
.head 6 -    Number: WORD
.head 5 +    Parameters 
.head 6 -    Number: WORD
.head 6 -    Receive String: LPSTR
.head 6 -    Receive Number: LPWORD
.head 6 -    Receive Number: LPLONG
.head 6 -    Receive Number: LPLONG
.head 3 +  Library name: advapi32.dll
.head 4 -  ThreadSafe: No
.head 4 +  Function: GetUserNameA
.head 5 -  Description:
.head 5 -  Export Ordinal: 0
.head 5 +  Returns
.head 6 -  Boolean: BOOL
.head 5 +  Parameters
.head 6 -  Receive String: LPSTR
.head 6 -  Receive Number: LPDWORD
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for FLMLOGIN.APL
.head 4 -  Number: FLMLOGINAplMsgOffSet = SAM_User + 2900
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  !
.head 4 -  Number: FLMLOGINAplConstOffSet = 1400
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 4010489951
0000: 9A00000072000000 0000000000000000 0200000500000010 0100001019000000
0020: 011001E056020000 0040730000000100 00A3290100192500 01101103B8000000
0040: 73D1000100006842 0100190009011040 0700006E00730034 0100005B015A0019
0060: 0001A21041070000 1B730001008D0074 0100161900041001 E0A20E0000006673
0080: 00010003
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 3 +  Function: GetUser
.head 4 -  Description:
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Receive String: sUser
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: nBuffer
.head 4 +  Actions
.head 5 -  Call SalStrSetBufferLength( sUser, 100 )
.head 5 -  Set nBuffer = 100
.head 5 -  Call GetUserNameA( sUser, nBuffer )
.head 5 -  Set sUser = SalStrUpperX ( sUser )
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1411198542
0000: 8608000094050000 0000000000000000 0200001200FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F53003C00 001063006C734469
0040: 616C6F670047656E 6572616C9A800000 0005000000871900 0000800110011200
0060: 0000014601730000 0001D80000001920 0004000000021060 011300000046CF00
0080: 0106001D00000019 0B0004100114D800 000046B300010081 3600000004000200
00A0: 031001150000F600 466C0001003AB000 0000190084011016 0000003D4600011A
00C0: 0000018019220000 0100000C84636C70 6247650F22000000 F601009619000110
00E0: 3007000000B80146 7300010000030180 6800000080020000 0009636C0348656C
0100: 709A00D90005005B 040002DE100018C4 01730001006D0004 009619000110B008
0120: 000000C447000100 009B1D0019250001 100900EC0000C4D1 0001000066360019
0140: 000901100A000000 7BC400340100004F 00580000190001C2 100B0000001EC400
0160: 01008D0001801981 0003000000090F45 7869744422000001 00006F1900690110
0180: 070063DC01730034 0100000180640400 0004000E0C506963 45807870616E6422
01A0: 00E800010000AD04 00026F0054C80273 000001C600018004 0C00050012636C0F
01C0: 546F6767006C6542 7574746F6E442200 000100006F04000D 0206000000636002
01E0: 7300360100018046 04000600000E0C64 664765FFE8000100 002D040003106F00
0200: 7ECC02730001C600 018004C800070000 0CF17262471F0001 00BD0004F500028D
0220: 00C00273D9000100 1801801900080021 0011636C53700069 6E536561736F6E40
0240: 59656172220000F4 0100009619000110 3700FC0246730001 0000430180530000
0260: 840900000B636C00 466F726D42617365 649A000005006F19 0069011008004368
0280: 03730000B4010000 195900040002DB09 009E6800016D001D 009619000410B60A
02A0: 0068670001001B36 000400B500030BED 0068D9000100663A 0019000901100C00
02C0: 00007B6800340100 0001804619000A00 00F817636C805072 696E744261006963
02E0: 5265706F72744622 000100006F190069 0110090063E60373 0034010000018040
0300: 460000000B00002E 1170537400617274 50726F677280616D D600000007BD0004
0320: B50002060D003404 7300D10001000066 040004006D020700 7B3400B601000859
0340: 00040002DB08009E 3400014D000C0000 9619000110B60900 3447000100008325
0360: 00000004B500030A ED0034D900010060 2900000004006D02 0B007B3400360100
0380: 2D00580000190001 DA100C001E340001 000D000180520018 00000C000F63F26C
03A0: 53743F3001DA000A 005B190001D21005 0000184604730001 006D001900961900
03C0: 0110B60600464700 0100008332000000 04B5000207ED0046 D900010066360004
03E0: 006D0208007B4600 B601003A59000400 02DB09009E460001 0D003E000000D604
0400: 0002B60A00466700 0100834200000004 B500020BED0046D9 0001006446000004
0420: 006D020C00734604 003601004A005800 00040002C30D0000 009E4600010D004E
0440: 000000D6040002B0 0E00000046670001 006301800400E40D 00001000546F6F6C
0460: 5469705780696E64 6F772200E8000100 00AD040003ED0500 C805730000018600
0480: 01801D0088000E00 000C63F163624701 6C400000000200BD 0019A5000110068D
04A0: 00840573D1000100 0066190004006902 1007007B84003601 000180061D000F00
04C0: 0000080D636C5365 6E6400456D61696C 734000D100020000 5B190001DA100500
04E0: 1038067300000100 6D00190096040002 10B6060038670001 0003018081000000
0500: 0010000000086351 4F1C456DC00000EC 0006002D19000110 6D0500868C067300
0520: 010036001900194B 00011008DB0086A3 00010000CD320019 D20001100BF60086
0540: 68000100004BB000 00001900B401100E 003D8600011A0000 6400002C00190001
0560: 106111000000868F 00010006007D0000 0004430001021014 FB000F80010000FE
0580: 0031018004001172 00000C6DE86C4765 654622000100006F 04006D0305006392
05A0: 067300360100
.enddata
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text: clsBackTextGeneral
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  Dialog Box: dlgLogin
.head 2 -  Class: clsDialogGeneral
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title: Fleming's Nurseries Login
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 2.2"
.head 4 -  Top: 0.865"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 4.365"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: 0.438"
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 0.1"
.head 6 -  Top: 0.021"
.head 6 -  Width:  0.475"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.385"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: Query.bmp
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Single
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clspbOk
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 2.213"
.head 6 -  Top: 0.021"
.head 6 -  Width:  0.475"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.385"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: Enter
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: OK.BMP
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Single
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 +  Message Actions
.head 6 +  On PAM_clsPB_CLICK
.head 7 +  If SqlDatabase = 'STOCK'
.head 8 -  Set sDatabase = 'LIVE'
.head 7 +  Else
.head 8 -  Set sDatabase = 'PLAY'
.head 7 -  !
.head 7 +  When SqlError
.head 8 -  Call SalMessageBox( 'Error!  Please try again.','Login', MB_Ok )
.head 7 -  Set bOk = SqlConnect( hSqlA )
.head 7 +  If bOk
.head 8 -  Call SqlDisconnect( hSqlA )
.head 8 -  Call SalEndDialog( hWndForm,TRUE )
.head 7 +  Else
.head 8 -  Call SalEndDialog( hWndForm, FALSE )
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 4.238"
.head 6 -  Top: 0.021"
.head 6 -  Width:  0.6"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.469"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? No
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name: EXIT.ICO
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Single
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 15
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 4.388"
.head 6 -  Top: Class Default
.head 6 -  Width:  0.475"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.385"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Yes
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 8
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  !
.head 3 +  Data Field: dfHeading
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdfGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? No
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: 0.038"
.head 6 -  Top: 0.333"
.head 6 -  Width:  4.813"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.417"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? No
.head 5 -  Justify: Center
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Arial
.head 5 -  Font Size: 24
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Gray
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text: Please SELECT a Login ?
.head 4 -  Resource Id: 20867
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsBackTextGeneral
.head 4 -  Window Location and Size
.head 5 -  Left: 0.7"
.head 5 -  Top: 1.125"
.head 5 -  Width:  3.538"
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Center
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Black
.head 4 -  Background Color: Class Default
.head 3 +  Radio Button: rbLive
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: LIVE System
.head 4 -  Window Location and Size
.head 5 -  Left: 1.088"
.head 5 -  Top: 1.677"
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Bold
.head 4 -  Text Color: Blue
.head 4 -  Background Color: Class Default
.head 4 +  Message Actions
.head 5 +  On PAM_clsRB_CLICK
.head 6 -  Set dfHeading = "Habitude LIVE System"
.head 6 -  Set SqlDatabase = 'HAB'
.head 6 -  Set dfDatabase = SqlDatabase
.head 6 -  Call SalColorSet( dfHeading, COLOR_IndexWindowText, COLOR_Blue )
.head 3 +  ! clsrbGeneral: rbPlay
.winattr class Radio Button:
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: PLAY System
.head 4 -  Window Location and Size
.head 5 -  Left: 2.638"
.head 5 -  Top: 2.927"
.head 5 -  Width:  1.4"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Arial
.head 4 -  Font Size: 8
.head 4 -  Font Enhancement: Bold
.head 4 -  Text Color: Red
.head 4 -  Background Color: Default
.end
.head 4 +  Message Actions 
.head 5 +  On PAM_clsRB_CLICK
.head 6 -  Set dfHeading = "Fleming's PLAY System"
.head 6 -  Set SqlDatabase = 'STOCKDEV'
.head 6 -  Set dfDatabase = SqlDatabase
.head 6 -  Call SalColorSet( dfHeading, COLOR_IndexWindowText, COLOR_Red )
.head 3 +  ! clsrbGeneral: rbLocal
.winattr class Radio Button:
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsrbGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title: LOCAL System
.head 4 -  Window Location and Size
.head 5 -  Left: 2.638"
.head 5 -  Top: 3.229"
.head 5 -  Width:  1.45"
.head 5 -  Width Editable? Yes
.head 5 -  Height: 0.25"
.head 5 -  Height Editable? Yes
.head 4 -  Visible? Yes
.head 4 -  Font Name: Arial
.head 4 -  Font Size: 8
.head 4 -  Font Enhancement: Bold
.head 4 -  Text Color: Red
.head 4 -  Background Color: Default
.end
.head 4 +  Message Actions 
.head 5 +  On PAM_clsRB_CLICK
.head 6 -  Set dfHeading = "Fleming's LOCAL System"
.head 6 -  Set SqlDatabase = 'STKLOCAL'
.head 6 -  Set dfDatabase = SqlDatabase
.head 6 -  Call SalColorSet( dfHeading, COLOR_IndexWindowText, COLOR_Red )
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 13
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 35211
.head 4 -  Class Child Ref Key: 14
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  String: sStartDatabase
.head 3 -  String: sStartUser
.head 2 +  Window Variables
.head 3 -  Number: nConnection 
.head 3 -  String: sUserName 
.head 3 -  Number: nType
.head 3 -  Number: nID
.head 3 -  Number: nLoginTime
.head 3 -  Number: nRetCode
.head 3 -  Sql Handle: hSqlA
.head 3 -  Boolean: bOk
.head 2 +  Message Actions
.head 3 +  On SAM_Create
.head 4 -  ! Set nConnection=NWGetConnectionNumber()
.head 4 -  ! Call SalStrSetBufferLength( sUserName,20 )
.head 4 -  ! Set nRetCode=NWGetConnectionInformation(nConnection,sUserName,nType,nID,nLoginTime)
.head 4 -  Call GetUser( sUserName )
.head 4 +  If sUserName = ''
.head 5 -  Call SalModalDialog( dlgDatabaseInfo, hWndForm )
.head 5 -  Set dfUser = SqlUser
.head 5 -  Set sUserName = SqlUser
.head 4 +  If sUserName = 'SUPERVISOR'
.head 5 -  Set SqlUser = 'SYSADM'
.head 5 -  Set SqlPassword = 'DANI'
.head 4 +  Else If sUserName = 'ADMIN'
.head 5 -  Set SqlUser = 'SYSADM'
.head 5 -  Set SqlPassword = 'DANI'
.head 4 +  Else
.head 5 -  Set sUserName = SalStrLeftX( sUserName, 8 )
.head 5 -  Set SqlDatabase = ''
.head 5 -  Set SqlUser = sUserName
.head 5 -  Set SqlPassword = sUserName
.head 4 +  ! If sStartDatabase = 'STOCKDEV'
.head 5 -  Set rbPlay = TRUE
.head 4 +  ! Else If sStartDatabase = 'STKLOCAL'
.head 5 -  Set rbLocal = TRUE
.head 4 -  ! Else
.head 4 -  Set rbLive = TRUE
.head 4 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 3 +  On SAM_CreateComplete
.head 4 -  Call SalSetFocus(pbOk)
.head 4 +  ! If rbPlay
.head 5 -  Call SalSendMsg( rbPlay, SAM_Click, 0, 0 )
.head 4 +  ! Else If rbLocal
.head 5 -  Call SalSendMsg( rbLocal, SAM_Click, 0, 0 )
.head 4 -  ! Else
.head 4 -  Call SalSendMsg( rbLive, SAM_Click, 0, 0 )
.head 4 -  Return SalSendClassMessage( SAM_CreateComplete, wParam, lParam )
