.head 0 +  Application Description: SQLWindows 5.01 Jans Royalty Owners Patents APL
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 4170705061746800 24006B3A5C63656E 747572615C636C61 73733B6B3A5C6365
0020: 6E747572615C666C 656D61706C730041 7070506174684C65 6E00040024000000
0040: 00557365476C6F62 616C506174680004 0001000000000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000C80000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE2FFFFFF160000 0016000000AA0200 0053010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.113"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 8.263"
.head 3 -  Top: 0.688"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: GENERAL.APL
.head 2 -  File Include: FRMCTBL.APL
.head 2 -  File Include: FORM.APL
.head 2 -  File Include: BUTTON.APL
.head 2 -  File Include: DATFIELD.APL
.head 2 -  File Include: TABLE.APL
.head 2 -  File Include: SQLHANDL.APL
.head 2 -  File Include: STRINGS.APL
.head 2 -  File Include: METER.APL
.head 2 -  File Include: STACKS.APL
.head 2 -  File Include: VTMETER.APL
.head 2 -  File Include: FLAGS.APL
.head 2 -  File Include: DIALOG.APL
.head 2 -  File Include: CHECKBOX.APL
.head 2 -  File Include: RADIOBTN.APL
.head 2 -  File Include: BGTEXT.APL
.head 2 -  File Include: GROUPBOX.APL
.head 2 -  File Include: QUERY.APL
.head 2 -  File Include: CMBFIELD.APL
.head 2 -  File Include: ITEMFUNC.APL
.head 2 -  File Include: PICK.APL
.head 2 -  File Include: ACTIVATE.APL
.head 2 -  File Include: SPNFIELD.APL
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: DATES.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: VTWIN.APL
.head 2 -  File Include: culttbld.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 3 -  Number: #0
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for OPATENTS.APL
.head 4 -  Number: OPATENTSAplMsgOffSet = SAM_User + 4000
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: OPATENTSAplConstOffSet = 1950
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 735193549
0000: E401000051010000 0000000000000000 020000100000006F 0100001019000000
0020: 010601E04C020000 0040730000000100 00A3880100192500 01066204B8000000
0040: 73D10001000068A1 0100190009010633 0700006E00730034 010000BA015A0019
0060: 0001A20634070000 1B730001008D00D3 01009619000106E8 3507000046730001
0080: 0000A3EC01001925 0001063607BA0000 73D1000100006805 020019008901068D
00A0: 07006E0073003401 00001E025A001900 01A2068E0700001B 730001008D003702
00C0: 009619000106E88F 0700004673000100 00A3500200192500 01069007BA000073
00E0: D100010000886902 003B010000000706 01F30B010040E606 0000730000320100
0100: 006D023A003B0007 A3F50B01E69B7300 018C0000710200CE 3B0007E8F70B01E6
0120: 267300010000A375 0200196500010611 B800000073D10001 0000688E02001900
0140: 890106F811006E00 730034010000A702 5A00190004A00601 811900001B730001
0160: 000D00
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 6861826
0000: 39180000FE0E0000 0000000000000000 0200002900FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F08003C00 001263006C737062
0040: 4F776E6500727350 6174656E74007340 0000000200001E00 0400000200021201
0060: 0700000600F80073 0000600001000000 04B3000400A00312 010800003DF80001
0080: 1B0001804F200000 000100001004636C 466F726D42006173 655461626C65607C
00A0: 00000004000F1900 0000010112010900 0000437E02730000 B401000019590019
00C0: 0001C2120A000000 1E7E0001000D0032 0000009619000112 B00B0000007E4700
00E0: 010000834B000000 043500020C00EC00 007ED90001000001 80530000000200E1
0100: 000B636C3F9A00C0 0000050000005B19 0001DA12080018C0 02730001006D0019
0120: 009604000212B609 00C067000100831D 0000001985000412 010AED00C0D90001
0140: 0040360000000400 006D030B007BC000 3601003A00580000 190001DA120C001E
0160: C00001000D000180 1900010003000000 17633E6C50722069 6E74426169630052
0180: 65706F72742200D0 00000100005B1900 01DA120900103E03 73000001008D0001
01A0: 8019190004000C63 0A6C7047656E6521 616C220000017A00 00194B000112071B
01C0: 008C0373A3000100 0001018068000000 05C30009636C8148 656C709A00EC0005
01E0: 00AD0400026F0098 8C03730001003600 0400194B00011208 DB0098A300010000
0200: CD1D0019D2000112 09F6009868000100 0036B3001900B401 120A003D9800019A
0220: 00004F002C001900 01126D0B00988F00 0100C600018019C0 0006000000090745
0240: 78697422A3000100 00B71900B4011207 0031B0037300011A 0000018004220000
0260: 0700000C07506963 45784070616E6422 0000F4010000D604 0002370028046473
0280: 0000010063018004 00E4080000120754 6F67676C00654275 74746F6E22A20000
02A0: 010000B70400A602 0600003134047300 011B000180042300 0900000C87646647
02C0: 657F00F401000096 0400031237005204 6673000100830180 3B0100840A000016
02E0: 636C7C476554CE61 4765478A02001578 00000019CB000112 1B009A0473A30001
0300: 0000CD190019D200 011207F6009A6800 01000032B3001900 B4011208003D9A00
0320: 01DA00004B2C0019 0001126D09009A8F 0001000600640000 00046B00020ADB00
0340: 9AB3000100C96800 0004DA00020BF600 9A6C0001006CB000 00000400A6020C00
0360: 003D9A00011B0070 0000AC0004000261 0D0000009ACF0001 060074000000046B
0380: 00020ED80000009A B3000100C1780000 00041A00020F0000 F6009A6C0001007C
03A0: B200000400860210 0000003D9A00015B 0080000C00040001 0212E1120000003F
03C0: 8001F80000000784 0000001903000101 120113F80000004F 800100FE00C58800
03E0: 0019120001121400 00F6009A68000100 00A1B00000001900 840112160000003D
0400: 9A00011A0000BA00 002C001900011261 170000009A8F0001 000600D300000019
0420: 4B00011218D80000 009AA300010000C1 EC00000019120001 121A0000E6009A04
0440: 680001000005B401 0019008401121C00 00003D9A00011A00 001E01002D190001
0460: 12691D00009A8F00 0100460037010004 6B00031ED8000000 9AB3000100210180
0480: 3A00000B4200001D 636C5400626C4D61 6B655365006C6563 746564526F00774B
04A0: 657941727261C879 84000004DE000498 0001020500FE0093 800100007F04B300
04C0: 1900B40112060031 E2047300019A0000 1D002C0019000112 6D0700E28F000100
04E0: 36003600046B0002 08DB00E2B3000100 2101801D00000C72 00001043806F6C75
0500: 6D6E4765476C4000 00F4020000960400 0212360500F40446 73000100009B0400
0520: 19A500011206ED00 F4D1000100001801 8053000D00390010 4469C0616C6F6747
0540: 65279A0000057A00 00194B000112121A 00007C0773A20000 010000CD190004DA
0560: 000213F6007C6C00 01001DB3001900B4 041214003D7C0001 DB0036A800040000
0580: 03691500007CCF00 0136003A00190B00 01120116DB007CA3 000100003101801D
05A0: 000E6200000C6363 FC62474640000200 006F190069011206 0063E8077300B401
05C0: 0000195900040002 DA1207009EE80001 8D0001800491000F 00000CE372624737
05E0: 2200017A0000046B 0002061B00F40773 B300010001018057 0000001042000011
0600: 636C540351756572 794416696FB80000 EC000600AD040003 6D13002488087300
0620: 0001003600040004 6B000214DB0024B3 000100CD080004DA 000215F600246C00
0640: 01000CB200001900 B4011216003D2400 011A00002500002C 00190001126D1700
0660: 248F00010006003E 000000194B000112 18DB0024A3000100 0001018099000000
0680: 1160000000116351 1E75617461004669 656C64740100ED0C 00AD0400026D0600
06A0: 4E8C087300010036 000400046B000207 DB004EB3000100CD 080004DA000208F6
06C0: 004E6C0001000CB3 000400B60209003D 4E0001DB00102C00 190001126D0A004E
06E0: 8F00010016002900 00194B0001120BDB 004EA300010000C1 4200000004D80001
0700: 020CFE0093800100 007F46B000000019 00B401120D003D4E 00011A00005F0000
0720: AC000400026D0E00 4ECF000106006300 0000194B0001120F DB004EA300010000
0740: C97C000004DA0002 10F6004E6C000100 80B3001900A40112 1100003D4E00011A
0760: 0000018099230012 000012FE6380436F 6D626F4669BF0CBD 0004B50002068D00
0780: 600873D100010000 66040004006D0207 007B6000B6010008 5900040002DB0800
07A0: 9E6000016D000C00 D6040002B6090060 670001009B100019 A50001120AED0060
07C0: D100010000662900 19006901120B007B 6000B40100004219 0004000102DB0C00
07E0: 7F80F20100006F46 009619000112B60D 006047000100009B 5F0004B500020EED
0800: 0060D90001006663 0019006901120F00 7B6000B40100007C 5900040002DB1000
0820: 9E6000016D008000 9619000112B61100 6047000100006301 809900E413000012
0840: FF03436163686574 B6010C00B70400B6 0207003172087300 01DA000004AC0004
0860: 00026D080072CF00 0136000800046B00 0209DB0072B30001 00CD0C0004DA0002
0880: 0AF600726C000100 10B3001900B40112 0B003D720001DA00 00292C0019000112
08A0: 6D0C00728F000100 3600420004630001 020DFB004F800100 FE00CD460019D200
08C0: 01120EF600726800 0100005FB3000400 B6020F003D720001 DB00632C00190001
08E0: 126D1000728F0001 0036007C00046B00 0211DB0072B30001 00CD800019920001
0900: 121200F600726800 0100000188803200 001400F00015636C 034F706572617470
0920: 6F72466940A20000 020000B71900B001 1201060031900873 0001DA0000192C00
0940: 190001126D070090 8F000100C6000180 0408001500001363 6C1F794342005965
0960: 734E6F466C618867 2200000100DE0004 D200021206C6009C 08736C0001000188
0980: 8064000016005000 14636C70531A6565 46726F986D546165 7CD90004005B1900
09A0: 01DA12070018C008 730001006D001900 9619000112B60800 C047000100009B32
09C0: 0019A500011209ED 00C0D10001000066 4B0019006901120A 007BC00034010000
09E0: 0180460400170000 C80D636C53650263 496E746F2200D100 0100005B040003DB
0A00: 050098D808730001 8D00018019910018 0000110770696E53 650061736F6E5965
0A20: 6172442200000100 006F190069011206 0043020973000034 0100000180644600
0A40: 0019006E11707400 61727450726F6772 80616DD600000007 BD0004E50002128D
0A60: 00560973D1000100 0066040004006D02 07007B5600B60100 085900040002DB08
0A80: 009E5600016D000C 009619000112B609 005647000100009B 250004B500030AED
0AA0: 0056D90001006629 0004006D020B007B 56003601002D0058 0000190001DA120C
0AC0: 001E560001000D00 018052001000001A 00000F63F26C5374 3F3001DA000A005B
0AE0: 190001DA12050018 6809730001006D00 19009619000112B6 0600684700010000
0B00: 9B320004B5000207 ED0068D900010066 360004006D020800 7B6800B601003A59
0B20: 00040002DB09009E 6800016D003E00D6 040002B60A006867 0001009B420004B5
0B40: 00020BED0068D900 010066460004006D 020C007B68003601 004A005800000400
0B60: 02DB0D009E680001 0D004E000000D604 0002B60E00686700 0100430180080000
0B80: 801B0000000E636C 027043756C746976 306172734000027A 0000044B00021207
0BA0: 1B00CE0973A30001 0000CD040004DA00 0308F600CE6C0001 00018C8004001C00
0BC0: 18001063546F6F00 6C54697057696E64 106F772200000100 BD0004B50003050D
0BE0: 00180B7300D90001 0098018004001D81 000C636654617343 6122A20000010000
0C00: B70400B603070021 0E0C730000011B00 018021200000001E 00000B7063664361
0C20: 50046F6F66000000 037A000029830001 071201500001000E 00004F800100FE00
0C40: CD040004D2000312 09C6001A0C736C00 010008B3001900B4 01120A003D1A0001
0C60: 1A00000180190300 1F0000000C006777 4D6F757365576068 65656C2200F40100
0C80: 009619000112F700 4673000100004301 809A0000E0200000 001206466D446574
0CA0: 731E47616CD69200 00070000B71900B4 0112140021FA1373 000001DA0000192C
0CC0: 00190001126D1500 FA8F000100360032 00194B00011216DB 00FAA300010000CD
0CE0: 4B0019D200011217 F600FA6800010000 64B3001900B40112 18003DFA00011A00
0D00: 007D00002C001900 011269190000FA8F 0001001600960000 046B00021ADA0000
0D20: FAB3000100310180 0800217200000D63 E06D6246726D8D40 000200DE0004D200
0D40: 0212068600841473 00680001000004B3 000400B60207003D 8400011B00018004
0D60: 23002200000C8463 6C6D6C47656F2200 F4010000D6040003 3605009C14667300
0D80: 01006301800800E0 2300000010027050 61696E744D806173 7465724000E80002
0DA0: 00002D040002126D 0700C68C14730001 0036000400046B00 0308DB00C6B30001
0DC0: 00310180190024E0 0000001563337269 4743804F72646572 466F892200000100
0DE0: DE0019D200011207 86000C1773006800 01000001CC801900 25FC00140F416464
0E00: 72004C6162656C73 2200D1000100005B 190001DE12001818 17730001008D0001
0E20: 8019010026000000 1963FA6C70054D69 6C46696C00654C69 7374696E67462200
0E40: 0100004F19000079 0112006324177300 340100000180061D 00270000000E0D53
0E60: 656E6490456D6169 7340D1000200005B 190001DA12050010 821973000001006D
0E80: 0019009604000212 B606008267000100 0301808100000000 280000000863514F
0EA0: 1C456DC00000EC00 06002D190001126D 0500D08C19730001 0036001900194B00
0EC0: 011208DB00D0A300 010000CD320019D2 0001120BF600D068 000100004BB30019
0EE0: 00B401120E003DD0 0001DA0000642C00 190001126D1100D0 8F00010036007D00
0F00: 04430001021214FB 004F800100FE0001
.enddata
.head 3 +  Pushbutton Class: clspbOwnersPatents
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left:
.head 5 -  Top:
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Keyboard Accelerator: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Picture File Name: C:\CENTURA\ICONS\PATENT.BMP
.head 4 -  Picture Transparent Color: Class Default
.head 4 -  Image Style: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Button Appearance: Class Default
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clspbPickInto
.head 4 +  Class Variables
.head 5 -  String: sTmp
.head 5 -  Window Handle: hWndTmp
.head 4 +  Instance Variables
.head 5 -  ! PUBLIC
.head 5 -  Window Handle: hWndPickIntoTable
.head 5 -  ! PRIVATE
.head 5 -  String: sOwnerId
.head 5 -  String: sBusName
.head 5 -  !
.head 5 -  Number: nRoyInstanceNo
.head 5 -  String: sCultId
.head 5 -  String: sCultDesc
.head 5 -  String: sRootId
.head 5 -  String: sRootDesc
.head 4 +  Functions
.head 5 +  Function: SetOwnerPatentsFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sNewOwnerId
.head 7 -  String: sNewBusName
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set sOwnerId = sNewOwnerId
.head 7 -  Set sBusName = sNewBusName
.head 7 -  Return TRUE
.head 5 +  Function: GetOwnerPatentsFields
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Receive Number: nNewRoyInstanceNo
.head 7 -  Receive String: sNewCultId
.head 7 -  Receive String: sNewCultDesc
.head 7 -  Receive String: sNewRootId
.head 7 -  Receive String: sNewRootDesc
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set nNewRoyInstanceNo = nRoyInstanceNo
.head 7 -  Set sNewCultId = sCultId
.head 7 -  Set sNewCultDesc = sCultDesc
.head 7 -  Set sNewRootId = sRootId
.head 7 -  Set sNewRootDesc = sRootDesc
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set hWndPickIntoTable = hWndItem
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Set clspbOwnersPatents.nActivateWindowType = ACTIVATE_FormWindow
.head 6 -  Set clspbOwnersPatents.sActivateDialogName = 'frmOwnersPatents'
.head 6 -  Set clspbOwnersPatents.hWndTable = hWndPickIntoTable
.head 6 -  Set clspbOwnersPatents.hWndFieldLookUp = hWndItem
.head 5 +  On PAM_clsACTIVATE_PUSHFIELDS
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETFIELDS, 0, 0 )
.head 6 -  Call PushString( sOwnerId )
.head 6 -  Call PushString( sBusName )
.head 6 -  Call PushWndHdl( hWndItem )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsPICK_LOOKUP
.head 6 -  Call PopString( sRootDesc, TRUE )
.head 6 -  Call PopString( sRootId, TRUE )
.head 6 -  Call PopString( sCultDesc, TRUE )
.head 6 -  Call PopString( sCultId, TRUE )
.head 6 -  Call PopNumber( nRoyInstanceNo, TRUE )
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_GETFIELDS, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsACTIVATE_POPFIELDS
.head 6 -  Call PopWndHdl( hWndTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Call PopString( sTmp, TRUE )
.head 6 -  Return TRUE
.head 3 +  Form Window Class: clsfrmOwnersPatents
.head 4 -  Title: Cultivar Royalty Owners
.head 4 -  Icon File:
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Automatically Created at Runtime? Class Default
.head 5 -  Initial State: Maximized
.head 5 -  Maximizable? Class Default
.head 5 -  Minimizable? Class Default
.head 5 -  Allow Child Docking? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  System Menu? Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 5.76"
.head 6 -  Height Editable? Class Default
.head 5 -  Form Size
.head 6 -  Width:  Class Default
.head 6 -  Height: Class Default
.head 6 -  Number of Pages: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Next Class Child Key: 52
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsFormChildTable
.head 4 -  Menu
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbSelect
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 24
.head 7 -  Class: clspbSelectFromTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 1.6"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbSelect.hWndTable = tblOwnerPatents
.head 9 -  Set pbSelect.hWndSelectParent = hWndForm.clsFormChildTable.hWndActivateButton
.head 9 -  Set pbSelect.nSelectType = PICK_SelectManyToMany
.head 8 +  On PAM_clsPICK_PUSHFIELDS
.head 9 -  Call PushNumber( tblOwnerPatents.colRoyInstanceNo )
.head 9 -  Call PushString( tblOwnerPatents.colCultId )
.head 9 -  Call PushString( tblOwnerPatents.colCultDesc )
.head 9 -  Call PushString( tblOwnerPatents.colRootId )
.head 9 -  Call PushString( tblOwnerPatents.colRootDesc )
.head 9 -  Return TRUE
.head 8 +  On PAM_clsPICK_POPFIELDS
.head 9 -  Call PopString( sTmp, TRUE )
.head 9 -  Call PopString( sTmp, TRUE )
.head 9 -  Call PopString( sTmp, TRUE )
.head 9 -  Call PopString( sTmp, TRUE )
.head 9 -  Call PopNumber( nTmp, TRUE )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbAddRows
.head 7 -  Class Child Ref Key: 6
.head 7 -  Class ChildKey: 8
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbSaveRows
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 9
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 8
.head 7 -  Class ChildKey: 10
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 4.663"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbDeleteRows
.head 7 -  Class Child Ref Key: 9
.head 7 -  Class ChildKey: 11
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRePopulate
.head 7 -  Class Child Ref Key: 11
.head 7 -  Class ChildKey: 12
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 5.113"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbTools
.head 7 -  Class Child Ref Key: 23
.head 7 -  Class ChildKey: 13
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 5.713"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbFirstRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 20
.head 7 -  Class: clspbFirstRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 7.063"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrevRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 21
.head 7 -  Class: clspbPrevRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 7.413"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbNextRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 22
.head 7 -  Class: clspbNextRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 7.763"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbLastRec
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 23
.head 7 -  Class: clspbLastRec
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 8.113"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 42
.head 7 -  Class ChildKey: 37
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbItemEnq
.head 7 -  Class Child Ref Key: 43
.head 7 -  Class ChildKey: 38
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 44
.head 7 -  Class ChildKey: 39
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 50
.head 7 -  Class ChildKey: 47
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClearRows
.head 7 -  Class Child Ref Key: 52
.head 7 -  Class ChildKey: 48
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbCultivars
.head 7 -  Class Child Ref Key: 0
.head 7 -  Class ChildKey: 50
.head 7 -  Class: clspbCultivars
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 3.2"
.head 8 -  Top: 0.042"
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 +  Message Actions
.head 8 +  On PAM_cls_SETINSTANCEVARS
.head 9 -  Set pbCultivars.hWndPickIntoTable = tblOwnerPatents
.head 9 -  Call SalSendClassMessage( PAM_cls_SETINSTANCEVARS, wParam, lParam )
.head 8 +  On PAM_cls_SETFIELDS
.head 9 -  Call pbCultivars.SetCultivarFields( tblOwnerPatents.colCultId, tblOwnerPatents.colCultDesc, '' )
.head 9 -  Return TRUE
.head 8 +  On PAM_cls_GETFIELDS
.head 9 -  Call pbCultivars.GetCultivarFields( tblOwnerPatents.colCultId, tblOwnerPatents.colCultDesc, sTmp )
.head 9 -  Return TRUE
.head 6 +  Pushbutton: pbRFIDClose
.head 7 -  Class Child Ref Key: 54
.head 7 -  Class ChildKey: 51
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbRFIDRead
.head 7 -  Class Child Ref Key: 55
.head 7 -  Class ChildKey: 52
.head 7 -  Class: clsFormChildTable
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Class Default
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 -  !
.head 5 -  Background Text: Owner Id.
.head 6 -  Resource Id: 46911
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 16
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.825"
.head 7 -  Top: 0.146"
.head 7 -  Width:  0.788"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Business Name
.head 6 -  Resource Id: 46910
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 17
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 0.95"
.head 7 -  Top: 0.385"
.head 7 -  Width:  1.663"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Data Field: dfOwnerId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 18
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.663"
.head 8 -  Top: 0.104"
.head 8 -  Width:  0.975"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfOwnerBusName
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 19
.head 6 -  Class: clsdfGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? No
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 2.663"
.head 8 -  Top: 0.354"
.head 8 -  Width:  7.188"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  !
.head 5 +  Child Table: tblOwnerPatents
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 25
.head 6 -  Class: clsTableGeneral
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 0.038"
.head 8 -  Top: 0.688"
.head 8 -  Width:  12.45"
.head 8 -  Width Editable? Class Default
.head 8 -  Height: 5.802"
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Font Name: Arial
.head 7 -  Font Size: 8
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  View: Class Default
.head 7 -  Allow Row Sizing? Class Default
.head 7 -  Lines Per Row: Class Default
.head 6 -  Memory Settings
.head 7 -  Maximum Rows in Memory: Class Default
.head 7 -  Discardable? Class Default
.head 6 +  Contents
.head 7 +  Column: colRoyInstanceNo
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 26
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Owner Id
.head 8 -  Visible? Yes
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.063"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_clsTBL_CHECKROWNEW
.head 10 +  If GetDistinctInsNo( dfOwnerId, colRoyInstanceNo, SH_cls_Execute )
.head 11 -  Return TRUE
.head 10 +  Else
.head 11 -  Call SalMessageBox('Error getting inst_no, contact programmer', 'Error', MB_Ok)
.head 11 -  Return FALSE
.head 7 +  Column: colCultId
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 27
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cult Id
.head 8 -  Visible? No
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.65"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colCultDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 28
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Cultivar Description
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  3.283"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCultDesc.bOrderBy = TRUE
.head 7 +  Column: colRootId
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 29
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Root Id
.head 8 -  Visible? No
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.3"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colRootDesc
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 30
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Rootstock Description
.head 8 -  Visible? Class Default
.head 8 -  Editable? No
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  1.833"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Class Default
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colRootDesc.bOrderBy = TRUE
.head 7 +  Column: colCurrency
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 42
.head 8 -  Class: clsColDropListGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Currency
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Class Default
.head 8 -  Justify: Class Default
.head 8 -  Width:  0.933"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: Uppercase
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCurrency.sSqlPopStatement = "SELECT DISTINCT currency_payable FROM royalty_payable"
.head 7 +  Column: colPercentage
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 46
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: % Payable
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Right
.head 8 -  Width:  0.95"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: ###000
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colPercentage.bOrderBy = TRUE
.head 7 +  Column: colCurrencyAmtPayable
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 43
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Curr. Roy Amt
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Right
.head 8 -  Width:  1.233"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: ###000;###000
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 +  Message Actions
.head 9 +  On PAM_cls_SETINSTANCEVARS
.head 10 -  Set colCurrencyAmtPayable.bOrderBy = TRUE
.head 7 +  Column: colAmtPayable
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 31
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Amount
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Right
.head 8 -  Width:  0.883"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: ###000;###000
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPayDueDate
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 32
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Due Date
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Date/Time
.head 8 -  Justify: Center
.head 8 -  Width:  1.583"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: dd-MMM-yyyy
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colPaidUptoDate
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 44
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Paid Upto Date
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Date/Time
.head 8 -  Justify: Center
.head 8 -  Width:  1.683"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: dd-MMM-yyyy
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 7 +  Column: colDueEveryMonths
.head 8 -  Class Child Ref Key: 0
.head 8 -  Class ChildKey: 45
.head 8 -  Class: clsColumnGeneral
.head 8 -  Property Template:
.head 8 -  Class DLL Name:
.head 8 -  Title: Due Every (n) Months
.head 8 -  Visible? Class Default
.head 8 -  Editable? Class Default
.head 8 -  Maximum Data Length: Class Default
.head 8 -  Data Type: Number
.head 8 -  Justify: Left
.head 8 -  Width:  1.333"
.head 8 -  Width Editable? Class Default
.head 8 -  Format: #0
.head 8 -  Country: Class Default
.head 8 -  Input Mask: Class Default
.head 8 -  Cell Options
.head 9 -  Cell Type? Class Default
.head 9 -  Multiline Cell? Class Default
.head 9 -  Cell DropDownList
.head 10 -  Sorted? Class Default
.head 10 -  Vertical Scroll? Class Default
.head 10 -  Auto Drop Down? Class Default
.head 10 -  Allow Text Editing? Class Default
.head 9 -  Cell CheckBox
.head 10 -  Check Value:
.head 10 -  Uncheck Value:
.head 10 -  Ignore Case? Class Default
.head 8 -  List Values
.head 8 -  Message Actions
.head 6 +  Functions
.head 7 +  Function: GetDistinctInsNo
.head 8 -  Description:
.head 8 +  Returns
.head 9 -  Boolean:
.head 8 +  Parameters
.head 9 -  String: sOwnerId
.head 9 -  Receive Number: nInstNo
.head 9 -  Number: nActionType
.head 8 -  Static Variables
.head 8 +  Local variables
.head 9 -  String: sSql
.head 9 -  String: sBind
.head 9 -  String: sInto
.head 9 -  String: sName
.head 9 -  Number: nSqlHandleNo
.head 9 -  !
.head 9 -  Number: nInd
.head 8 +  Actions
.head 9 -  Set nSqlHandleNo = SqlHandlesGetReferenceNo( 'GetDistInstNo' )
.head 9 +  Select Case nActionType
.head 10 +  Case SH_cls_Execute
.head 11 -  Set sSql = "
SELECT
	Max( Roy_Instance# ) + 1
  FROM
	Royalty_Payable
WHERE
	Royalty_Owner_Id = :1 "
.head 11 -  Set sName = 'GetDistInstNo1'
.head 11 -  Set sBind = ':sOwnerId '
.head 11 -  Set sInto = ' :nInstNo '
.head 11 -  !
.head 11 -  Call haSqlHandles[ nSqlHandleNo ].Setup( sSql, sName, sBind, sInto )
.head 11 -  Call SqlVarSetup( haSqlHandles[ nSqlHandleNo ].hSqlHandle )
.head 11 -  !
.head 11 +  If haSqlHandles[ nSqlHandleNo ].Execute( )
.head 12 +  If NOT haSqlHandles[ nSqlHandleNo ].FetchNext( nInd )
.head 13 -  Set nInstNo = 0
.head 12 +  Else
.head 13 +  If nInstNo = NUMBER_Null
.head 14 -  Set nInstNo = 0
.head 12 -  Return TRUE
.head 11 +  Else
.head 12 -  Return FALSE
.head 10 +  Case SH_cls_Disconnect
.head 11 -  Return haSqlHandles[ nSqlHandleNo ].Disconnect( )
.head 6 -  Window Variables
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 +  If TRUE	! SELECT
.head 9 -  Set sSQLPopHandle = ' SELECT 
  Royalty_Payable.Roy_Instance#, 
  Royalty_Payable.Cultivar_Id, 
  Cultivar.Cult_Desc, 
  Royalty_Payable.Rootstock_Id,  
  Royalty_Payable.Currency_Payable,
  Royalty_Payable.Currency_Roy_Amt,
  Royalty_Payable.Amount_Payable, 
  Royalty_Payable.Percentage_Payable, 
  Royalty_Payable.Payment_Due_Date,
  Royalty_Payable.Paid_Upto_Date,
  Royalty_Payable.Due_Every_Months
FROM 
  Royalty_Payable, 
  Cultivar 
WHERE 
  Royalty_Payable.Royalty_Owner_Id = :1 AND 
  Royalty_Payable.Cultivar_Id = Cultivar.Cult_Id(+)  
ORDER BY 
  Royalty_Payable.Roy_Instance# '
.head 9 -  Set sNAMEPopHandle = 'OWNPATNT4'
.head 9 -  Set sBINDPopHandle = ':hWndParent.dfOwnerId'
.head 9 -  Set sINTOPopHandle = ':clsfrmOwnersPatents.tblOwnerPatents.colRoyInstanceNo, 
:clsfrmOwnersPatents.tblOwnerPatents.colCultId, 
:clsfrmOwnersPatents.tblOwnerPatents.colCultDesc, 
:clsfrmOwnersPatents.tblOwnerPatents.colRootId,  
:clsfrmOwnersPatents.tblOwnerPatents.colCurrency,  
:clsfrmOwnersPatents.tblOwnerPatents.colCurrencyAmtPayable,  
:clsfrmOwnersPatents.tblOwnerPatents.colAmtPayable, 
:clsfrmOwnersPatents.tblOwnerPatents.colPercentage, 
:clsfrmOwnersPatents.tblOwnerPatents.colPayDueDate,
:clsfrmOwnersPatents.tblOwnerPatents.colPaidUptoDate,
:clsfrmOwnersPatents.tblOwnerPatents.colDueEveryMonths'
.head 8 -  !
.head 8 +  If TRUE	! REFRESH
.head 9 -  Set sSQLRefreshHandle = ' SELECT 
  Royalty_Payable.Cultivar_Id, 
  Cultivar.Cult_Desc, 
  Royalty_Payable.Rootstock_Id,  
  Royalty_Payable.Currency_Payable,
  Royalty_Payable.Currency_Roy_Amt,
  Royalty_Payable.Amount_Payable, 
  Royalty_Payable.Percentage_Payable, 
  Royalty_Payable.Payment_Due_Date,
  Royalty_Payable.Paid_Upto_Date,
  Royalty_Payable.Due_Every_Months
FROM 
  Royalty_Payable, 
  Cultivar 
WHERE 
  Royalty_Payable.Royalty_Owner_Id = :1 AND 
  Royalty_Payable.Roy_Instance# = :2 AND 
  Royalty_Payable.Cultivar_Id = Cultivar.Cult_Id(+) '
.head 9 -  Set sNAMERefreshHandle = 'REFOWNPATNT4'
.head 9 -  Set sBINDRefreshHandle = ':hWndParent.dfOwnerId, 
:clsfrmOwnersPatents.tblOwnerPatents.colRoyInstanceNo'
.head 9 -  Set sINTORefreshHandle = ':clsfrmOwnersPatents.tblOwnerPatents.colCultId, 
:clsfrmOwnersPatents.tblOwnerPatents.colCultDesc, 
:clsfrmOwnersPatents.tblOwnerPatents.colRootId,  
:clsfrmOwnersPatents.tblOwnerPatents.colCurrency,  
:clsfrmOwnersPatents.tblOwnerPatents.colCurrencyAmtPayable,  
:clsfrmOwnersPatents.tblOwnerPatents.colAmtPayable, 
:clsfrmOwnersPatents.tblOwnerPatents.colPercentage, 
:clsfrmOwnersPatents.tblOwnerPatents.colPayDueDate,
:clsfrmOwnersPatents.tblOwnerPatents.colPaidUptoDate,
:clsfrmOwnersPatents.tblOwnerPatents.colDueEveryMonths'
.head 8 -  !
.head 8 +  If TRUE	! UPDATE
.head 9 -  Set sSQLUpdateHandle = 'UPDATE Royalty_Payable
SET 
  Currency_Payable = :3,
  Currency_Roy_Amt = :4,
  Amount_Payable = :5, 
  Percentage_Payable = :6, 
  Payment_Due_Date = :7,
  Paid_Upto_Date = :8,
  Due_Every_Months = :9
WHERE 
  Royalty_Owner_Id = :1 AND 
  Roy_Instance# = :2 '
.head 9 -  Set sNAMEUpdateHandle = 'UPTOWNPATNT4'
.head 9 -  Set sBINDUpdateHandle = ':hWndParent.dfOwnerId, 
:clsfrmOwnersPatents.tblOwnerPatents.colRoyInstanceNo,
:clsfrmOwnersPatents.tblOwnerPatents.colCurrency,  
:clsfrmOwnersPatents.tblOwnerPatents.colCurrencyAmtPayable,  
:clsfrmOwnersPatents.tblOwnerPatents.colAmtPayable, 
:clsfrmOwnersPatents.tblOwnerPatents.colPercentage, 
:clsfrmOwnersPatents.tblOwnerPatents.colPayDueDate,
:clsfrmOwnersPatents.tblOwnerPatents.colPaidUptoDate,
:clsfrmOwnersPatents.tblOwnerPatents.colDueEveryMonths'
.head 9 -  Set sINTOUpdateHandle = ''
.head 8 +  If TRUE	! ADD
.head 9 -  Set sSQLInsertHandle = '
INSERT INTO 
	Royalty_Payable
	(  
  	Royalty_Owner_Id, 
	Cultivar_Id, 
  	Roy_Instance#,
	Currency_Payable,
  	Currency_Roy_Amt,
  	Amount_Payable, 
  	Percentage_Payable, 
  	Payment_Due_Date,
  	Paid_Upto_Date,
  	Due_Every_Months
	)
VALUES
	( :1, :2, :3, :4, :5, :6, :7, :8, :9, :10 )'
.head 9 -  Set sNAMEInsertHandle = '1005INSOWNPATN1'
.head 9 -  Set sBINDInsertHandle = ':hWndParent.dfOwnerId, 
:clsfrmOwnersPatents.tblOwnerPatents.colCultId,
:clsfrmOwnersPatents.tblOwnerPatents.colRoyInstanceNo,
:clsfrmOwnersPatents.tblOwnerPatents.colCurrency,  
:clsfrmOwnersPatents.tblOwnerPatents.colCurrencyAmtPayable,  
:clsfrmOwnersPatents.tblOwnerPatents.colAmtPayable, 
:clsfrmOwnersPatents.tblOwnerPatents.colPercentage, 
:clsfrmOwnersPatents.tblOwnerPatents.colPayDueDate,
:clsfrmOwnersPatents.tblOwnerPatents.colPaidUptoDate,
:clsfrmOwnersPatents.tblOwnerPatents.colDueEveryMonths'
.head 9 -  Set sINTOInsertHandle = ''
.head 8 +  If TRUE	! DELETE
.head 9 -  Set sSQLDeleteHandle = '
DELETE FROM 
	Royalty_Payable
WHERE
	Royalty_Owner_Id = :1 and
	Cultivar_Id = :2'
.head 9 -  Set sNAMEDeleteHandle = '1005DelOWNPATN1'
.head 9 -  Set sBINDDeleteHandle = ':hWndParent.dfOwnerId, 
:clsfrmOwnersPatents.tblOwnerPatents.colCultId'
.head 9 -  Set sINTODeleteHandle = ''
.head 8 -  !
.head 8 -  Set bAddAllowed = TRUE
.head 8 -  Set bSaveAllowed = TRUE
.head 8 -  Set bDeleteAllowed = TRUE
.head 8 -  Set bUnDeleteAllowed = TRUE
.head 8 -  Set bRepopulateAllowed = TRUE
.head 8 -  Set bClearSelectAllowed = TRUE
.head 8 -  Set bQueryAllowed = TRUE
.head 8 -  Set bReportAllowed = FALSE
.head 8 -  Set bOrderAllowed = TRUE
.head 8 -  !
.head 8 -  Set sQueryDialogName = 'dlgQueryOwnerPatents'
.head 7 +  On SAM_FetchRowDone
.head 8 +  If colRootId != ''
.head 9 -  Call ExtractRootstockDescription( colRootId, colRootDesc, SH_cls_Execute )
.head 8 -  Return SalSendClassMessage( SAM_FetchRowDone, wParam, lParam )
.head 7 +  On SAM_Destroy
.head 8 -  Call ExtractRootstockDescription( '', colRootDesc, SH_cls_Disconnect )
.head 8 -  Call GetDistinctInsNo( '', nTmp, SH_cls_Disconnect )
.head 8 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 33
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 47
.head 6 -  Class ChildKey: 34
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 8063
.head 6 -  Class Child Ref Key: 48
.head 6 -  Class ChildKey: 35
.head 6 -  Class: clsFormChildTable
.head 6 -  Window Location and Size
.head 7 -  Left: Class Default
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 49
.head 6 -  Class ChildKey: 36
.head 6 -  Class: clsFormChildTable
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bAddAllowed = TRUE
.head 6 -  Set bSaveAllowed = TRUE
.head 6 -  Set bDeleteAllowed = TRUE
.head 6 -  Set bUnDeleteAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  Set hWndChildTable = tblOwnerPatents
.head 6 -  ! Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 5 +  On PAM_clsFRM_POPFIELDS
.head 6 -  Call PopWndHdl( hWndActivateButton, TRUE )
.head 6 -  Call PopString( dfOwnerBusName, TRUE )
.head 6 -  Call PopString( dfOwnerId, TRUE )
.head 6 -  Return TRUE
.head 3 +  Dialog Box Class: clsdlgQueryOwnersPatents
.head 4 -  Title: Query Royalty Owner Patented Stock
.head 4 -  Accessories Enabled? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Display Settings
.head 5 -  Display Style? Class Default
.head 5 -  Visible at Design time? Yes
.head 5 -  Type of Dialog: Modal
.head 5 -  Allow Dock to Parent? Class Default
.head 5 -  Docking Orientation: Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  7.975"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 2.448"
.head 6 -  Height Editable? Class Default
.head 5 -  Absolute Screen Location? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Resizable? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 4 -  Next Class Child Key: 22
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Tool Bar
.head 5 -  Display Settings
.head 6 -  Display Style? Class Default
.head 6 -  Location? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Size: Class Default
.head 6 -  Size Editable? Class Default
.head 6 -  Docking Toolbar? Class Default
.head 6 -  Toolbar Docking Orientation: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 6 -  Resizable? Class Default
.head 5 +  Contents
.head 6 +  Pushbutton: pbHelp
.head 7 -  Class Child Ref Key: 16
.head 7 -  Class ChildKey: 5
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbQuery
.head 7 -  Class Child Ref Key: 7
.head 7 -  Class ChildKey: 6
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 3.675"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbPrintForm
.head 7 -  Class Child Ref Key: 17
.head 7 -  Class ChildKey: 7
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.638"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbClear
.head 7 -  Class Child Ref Key: 19
.head 7 -  Class ChildKey: 21
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 6 +  Pushbutton: pbExit
.head 7 -  Class Child Ref Key: 20
.head 7 -  Class ChildKey: 22
.head 7 -  Class: clsTblQueryDialog
.head 7 -  Property Template:
.head 7 -  Class DLL Name:
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Keyboard Accelerator: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Picture File Name:
.head 7 -  Picture Transparent Color: Class Default
.head 7 -  Image Style: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Button Appearance: Standard
.head 7 -  Message Actions
.head 4 +  Contents
.head 5 +  Data Field: dfDatabase
.head 6 -  Class Child Ref Key: 12
.head 6 -  Class ChildKey: 1
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Data Field: dfUser
.head 6 -  Class Child Ref Key: 13
.head 6 -  Class ChildKey: 2
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: Class Default
.head 7 -  Editable? Class Default
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: Class Default
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Justify: Class Default
.head 7 -  Format: Class Default
.head 7 -  Country: Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  Input Mask: Class Default
.head 6 -  Message Actions
.head 5 +  Custom Control: ccSeasonYear
.head 6 -  Class Child Ref Key: 14
.head 6 -  Class ChildKey: 3
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Display Settings
.head 7 -  DLL Name:
.head 7 -  MS Windows Class Name:
.head 7 -  Style:  Class Default
.head 7 -  ExStyle:  Class Default
.head 7 -  Title:
.head 7 -  Window Location and Size
.head 8 -  Left: 6.85"
.head 8 -  Top: Class Default
.head 8 -  Width:  Class Default
.head 8 -  Width Editable? Class Default
.head 8 -  Height: Class Default
.head 8 -  Height Editable? Class Default
.head 7 -  Visible? Class Default
.head 7 -  Border? Class Default
.head 7 -  Etched Border? Class Default
.head 7 -  Hollow? Class Default
.head 7 -  Vertical Scroll? Class Default
.head 7 -  Horizontal Scroll? Class Default
.head 7 -  Tab Stop? Class Default
.head 7 -  Tile To Parent? Class Default
.head 7 -  Font Name: Class Default
.head 7 -  Font Size: Class Default
.head 7 -  Font Enhancement: Class Default
.head 7 -  Text Color: Class Default
.head 7 -  Background Color: Class Default
.head 7 -  DLL Settings
.head 6 -  Message Actions
.head 5 -  Background Text:
.head 6 -  Resource Id: 46912
.head 6 -  Class Child Ref Key: 15
.head 6 -  Class ChildKey: 4
.head 6 -  Class: clsTblQueryDialog
.head 6 -  Window Location and Size
.head 7 -  Left: 6.1"
.head 7 -  Top: Class Default
.head 7 -  Width:  Class Default
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 -  Background Text: Cultivar Id
.head 6 -  Resource Id: 46914
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 9
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.175"
.head 7 -  Top: 0.563"
.head 7 -  Width:  0.913"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Cultivar Description
.head 6 -  Resource Id: 46915
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 10
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 1.425"
.head 7 -  Top: 0.844"
.head 7 -  Width:  1.663"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  Background Text: Rootstock Id
.head 6 -  Resource Id: 46913
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 11
.head 6 -  Class: clsBackTextGeneral
.head 6 -  Window Location and Size
.head 7 -  Left: 2.0"
.head 7 -  Top: 1.136"
.head 7 -  Width:  1.088"
.head 7 -  Width Editable? Class Default
.head 7 -  Height: Class Default
.head 7 -  Height Editable? Class Default
.head 6 -  Visible? Class Default
.head 6 -  Justify: Class Default
.head 6 -  Font Name: Class Default
.head 6 -  Font Size: Class Default
.head 6 -  Font Enhancement: Class Default
.head 6 -  Text Color: Class Default
.head 6 -  Background Color: Class Default
.head 5 -  !
.head 5 +  Data Field: dfCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 12
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.075"
.head 8 -  Top: 0.521"
.head 8 -  Width:  0.963"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Uppercase
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCultId.sSQLCOLNAME = 'ROYALTY_PAYABLE.CULTIVAR_ID'
.head 8 -  Set dfCultId.hWndOperatorField = cmbCultIdOp
.head 8 -  Set dfCultId.hWndNotField = cbNOTCultId
.head 5 +  Data Field: dfCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 13
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.075"
.head 8 -  Top: 0.802"
.head 8 -  Width:  3.4"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Unformatted
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfCultDesc.sSQLCOLNAME = 'CULTIVAR.CULT_DESC'
.head 8 -  Set dfCultDesc.hWndOperatorField = cmbCultDescOp
.head 8 -  Set dfCultDesc.hWndNotField = cbNOTCultDesc
.head 8 -  Set dfCultDesc.sOperator = ' LIKE '
.head 8 -  Set dfCultDesc.bCompareUpCase = TRUE
.head 5 +  Data Field: dfRootId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 14
.head 6 -  Class: clsQueryDataField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Data
.head 7 -  Maximum Data Length: Class Default
.head 7 -  Data Type: String
.head 7 -  Editable? Yes
.head 6 -  Display Settings
.head 7 -  Window Location and Size
.head 8 -  Left: 4.075"
.head 8 -  Top: 1.094"
.head 8 -  Width:  0.963"
.head 8 -  Width Editable? Yes
.head 8 -  Height: 0.25"
.head 8 -  Height Editable? Yes
.head 7 -  Visible? Yes
.head 7 -  Border? Yes
.head 7 -  Justify: Left
.head 7 -  Format: Uppercase
.head 7 -  Country: Default
.head 7 -  Font Name: Default
.head 7 -  Font Size: Default
.head 7 -  Font Enhancement: Default
.head 7 -  Text Color: Default
.head 7 -  Background Color: Default
.head 7 -  Input Mask: Unformatted
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfRootId.sSQLCOLNAME = 'ROYALTY_PAYABLE.ROOTSTOCK_ID'
.head 8 -  Set dfRootId.hWndOperatorField = cmbRootIdOp
.head 8 -  Set dfRootId.hWndNotField = cbNOTRootId
.head 5 +  ! clsQueryDataField: dfRootDesc
.head 6 +  Message Actions 
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set dfRootDesc.sSQLCOLNAME = 'ROOTSTOCK.ROOT_DESC'
.head 8 -  Set dfRootDesc.hWndOperatorField = cmbRootDescOp
.head 8 -  Set dfRootDesc.hWndNotField = cbNOTRootDesc
.head 8 -  Set dfRootDesc.sOperator = ' LIKE '
.head 8 -  Set dfRootDesc.bCompareUpCase = TRUE
.head 5 -  !
.head 5 +  Check Box: cbNOTCultId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 15
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 0.7"
.head 7 -  Top: 0.521"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCultId.hWndQueryField = dfCultId
.head 5 +  Check Box: cbNOTCultDesc
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 16
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 0.7"
.head 7 -  Top: 0.802"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTCultDesc.hWndQueryField = dfCultDesc
.head 5 +  Check Box: cbNOTRootId
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 17
.head 6 -  Class: clsQueryNOTField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title: NOT
.head 6 -  Window Location and Size
.head 7 -  Left: 0.7"
.head 7 -  Top: 1.094"
.head 7 -  Width:  0.538"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 0.25"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Font Name: Arial
.head 6 -  Font Size: 8
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Dark Blue
.head 6 -  Background Color: Gray
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTRootId.hWndQueryField = dfRootId
.head 5 +  ! clsQueryNOTField: cbNOTRootDesc
.head 6 +  Message Actions 
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cbNOTRootDesc.hWndQueryField = dfRootDesc
.head 5 -  !
.head 5 +  Combo Box: cmbCultIdOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 18
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.15"
.head 7 -  Top: 0.521"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCultIdOp.hWndQueryField = dfCultId
.head 8 -  Set cmbCultIdOp.sOperator = ' = '
.head 5 +  Combo Box: cmbCultDescOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 19
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.15"
.head 7 -  Top: 0.802"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbCultDescOp.hWndQueryField = dfCultDesc
.head 8 -  Set cmbCultDescOp.sOperator = ' LIKE '
.head 5 +  Combo Box: cmbRootIdOp
.head 6 -  Class Child Ref Key: 0
.head 6 -  Class ChildKey: 20
.head 6 -  Class: clsQueryOperatorField
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Window Location and Size
.head 7 -  Left: 3.15"
.head 7 -  Top: 1.094"
.head 7 -  Width:  0.863"
.head 7 -  Width Editable? Yes
.head 7 -  Height: 1.26"
.head 7 -  Height Editable? Yes
.head 6 -  Visible? Yes
.head 6 -  Editable? No
.head 6 -  String Type: String
.head 6 -  Maximum Data Length: Default
.head 6 -  Sorted? No
.head 6 -  Always Show List? No
.head 6 -  Vertical Scroll? Yes
.head 6 -  Font Name: Default
.head 6 -  Font Size: Default
.head 6 -  Font Enhancement: Default
.head 6 -  Text Color: Default
.head 6 -  Background Color: Default
.head 6 -  Input Mask: Unformatted
.head 6 -  List Initialization
.head 6 +  Message Actions
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbRootIdOp.hWndQueryField = dfRootId
.head 8 -  Set cmbRootIdOp.sOperator = ' = '
.head 5 +  ! clsQueryOperatorField: cmbRootDescOp
.head 6 -  List Initialization 
.head 6 +  Message Actions 
.head 7 +  On PAM_cls_SETINSTANCEVARS
.head 8 -  Set cmbRootDescOp.hWndQueryField = dfCultDesc
.head 8 -  Set cmbRootDescOp.sOperator = ' LIKE '
.head 5 -  !
.head 4 +  Derived From
.head 5 -  Class: clsTblQueryDialog
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set bMapEnterToTab = TRUE
.head 6 -  Set hWndFirstFocus = dfCultDesc
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  ! clsFormChildTable: frmOwnersPatents
.head 2 -  Description: 
.head 2 -  Named Menus 
.head 2 -  Menu 
.head 2 +  Tool Bar 
.head 3 +  Contents 
.head 4 +  Pushbutton: pbHelp
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbSelect
.head 5 +  Message Actions 
.head 6 +  On PAM_cls_SETINSTANCEVARS
.head 7 -  Set pbSelect.hWndTable = tblOwnerPatents
.head 7 -  Set pbSelect.hWndSelectParent = hWndForm.clsFormChildTable.hWndActivateButton
.head 7 -  Set pbSelect.nSelectType = PICK_SelectManyToMany
.head 6 +  On PAM_clsPICK_PUSHFIELDS
.head 7 -  Call PushNumber( tblOwnerPatents.colRoyInstanceNo )
.head 7 -  Call PushString( tblOwnerPatents.colCultId )
.head 7 -  Call PushString( tblOwnerPatents.colCultDesc )
.head 7 -  Call PushString( tblOwnerPatents.colRootId )
.head 7 -  Call PushString( tblOwnerPatents.colRootDesc )
.head 7 -  Return TRUE
.head 6 +  On PAM_clsPICK_POPFIELDS
.head 7 -  Call PopString( sTmp, TRUE )
.head 7 -  Call PopString( sTmp, TRUE )
.head 7 -  Call PopString( sTmp, TRUE )
.head 7 -  Call PopString( sTmp, TRUE )
.head 7 -  Call PopNumber( nTmp, TRUE )
.head 7 -  Return TRUE
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbQuery
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbFirstRec
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrevRec
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbNextRec
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbLastRec
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbExit
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbTools
.head 5 -  Message Actions 
.head 2 +  Contents 
.head 3 +  Data Field: dfDatabase
.head 4 -  Message Actions 
.head 3 +  Data Field: dfUser
.head 4 -  Message Actions 
.head 3 -  !
.head 3 -  Background Text: Owner Id.
.head 3 -  Background Text: Business Name
.head 3 +  Data Field: dfOwnerId
.head 4 -  Message Actions 
.head 3 +  Data Field: dfOwnerBusName
.head 4 -  Message Actions 
.head 3 -  !
.head 3 +  Child Table: tblOwnerPatents
.head 4 +  Contents 
.head 5 +  Column: colRoyInstanceNo
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colCultId
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colCultDesc
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colRootId
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colRootDesc
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colAmtPayable
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 5 +  Column: colPayDueDate
.head 6 -  List Values 
.head 6 -  Message Actions 
.head 4 -  Functions 
.head 4 -  Window Variables 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set sSQLPopHandle = ' SELECT 
  Royalty_Payable.Roy_Instance#, 
  Royalty_Payable.Cultivar_Id, 
  Cultivar.Cult_Desc, 
  Royalty_Payable.Rootstock_Id,  
  Royalty_Payable.Amount_Payable, 
  Royalty_Payable.Payment_Due_Date
FROM 
  Royalty_Payable, 
  Cultivar 
WHERE 
  Royalty_Payable.Royalty_Owner_Id = :1 AND 
  Royalty_Payable.Cultivar_Id = Cultivar.Cult_Id(+)  
ORDER BY 
  Royalty_Payable.Roy_Instance# '
.head 6 -  Set sNAMEPopHandle = 'OWNPATENT'
.head 6 -  Set sBINDPopHandle = ':hWndParent.dfOwnerId'
.head 6 -  Set sINTOPopHandle = ':hWndForm.colRoyInstanceNo, 
:hWndForm.colCultId, 
:hWndForm.colCultDesc, 
:hWndForm.colRootId,  
:hWndForm.colAmtPayable, 
:hWndForm.colPayDueDate'
.head 6 -  !
.head 6 -  Set sSQLRefreshHandle = ' SELECT 
  Royalty_Payable.Cultivar_Id, 
  Cultivar.Cult_Desc, 
  Royalty_Payable.Rootstock_Id,  
  Royalty_Payable.Amount_Payable, 
  Royalty_Payable.Payment_Due_Date
FROM 
  Royalty_Payable, 
  Cultivar 
WHERE 
  Royalty_Payable.Royalty_Owner_Id = :1 AND 
  Royalty_Payable.Roy_Instance# = :2 AND 
  Royalty_Payable.Cultivar_Id = Cultivar.Cult_Id(+) '
.head 6 -  Set sNAMERefreshHandle = 'REFOWNPATENT'
.head 6 -  Set sBINDRefreshHandle = ':hWndParent.dfOwnerId, 
:hWndForm.colRoyInstanceNo'
.head 6 -  Set sINTORefreshHandle = ':hWndForm.colCultId, 
:hWndForm.colCultDesc, 
:hWndForm.colRootId,  
:hWndForm.colAmtPayable, 
:hWndForm.colPayDueDate'
.head 6 -  !
.head 6 -  Set bAddAllowed = FALSE
.head 6 -  Set bSaveAllowed = FALSE
.head 6 -  Set bDeleteAllowed = FALSE
.head 6 -  Set bUnDeleteAllowed = FALSE
.head 6 -  Set bRepopulateAllowed = TRUE
.head 6 -  Set bClearSelectAllowed = TRUE
.head 6 -  Set bQueryAllowed = TRUE
.head 6 -  Set bReportAllowed = FALSE
.head 6 -  Set bOrderAllowed = TRUE
.head 6 -  !
.head 6 -  Set sQueryDialogName = 'dlgQueryOwnerPatents'
.head 5 +  On SAM_FetchRowDone
.head 6 +  If colRootId != ''
.head 7 -  Call ExtractRootstockDescription( colRootId, colRootDesc, SH_cls_Execute )
.head 6 -  Return SalSendClassMessage( SAM_FetchRowDone, wParam, lParam )
.head 5 +  On SAM_Destroy
.head 6 -  Call ExtractRootstockDescription( '', colRootDesc, SH_cls_Disconnect )
.head 6 -  Return SalSendClassMessage( SAM_Destroy, wParam, lParam )
.head 3 -  Background Text: Season
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 -  Window Parameters 
.head 2 -  Window Variables 
.head 2 +  Message Actions 
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set bQueryAllowed = TRUE
.head 4 -  Set bAddAllowed = FALSE
.head 4 -  Set bSaveAllowed = FALSE
.head 4 -  Set bDeleteAllowed = FALSE
.head 4 -  Set bUnDeleteAllowed = FALSE
.head 4 -  Set bReportAllowed = FALSE
.head 4 -  Set bOrderAllowed = TRUE
.head 4 -  Set hWndChildTable = tblOwnerPatents
.head 4 -  ! Set nPopOrQueryOnStartUp = TBL_cls_QueryOnStartUp
.head 3 +  On PAM_clsFRM_POPFIELDS
.head 4 -  Call PopWndHdl( hWndActivateButton, TRUE )
.head 4 -  Call PopString( dfOwnerBusName, TRUE )
.head 4 -  Call PopString( dfOwnerId, TRUE )
.head 4 -  Return TRUE
.head 1 +  ! clsTblQueryDialog: dlgQueryOwnerPatents
.head 2 -  Description: 
.head 2 +  Tool Bar 
.head 3 +  Contents 
.head 4 +  Pushbutton: pbQuery
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbHelp
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Message Actions 
.head 4 +  Pushbutton: pbExit
.head 5 -  Message Actions 
.head 2 +  Contents 
.head 3 -  !
.head 3 -  Background Text: Cultivar Id
.head 3 -  Background Text: Cultivar Description
.head 3 -  Background Text: Rootstock Id
.head 3 -  !
.head 3 +  Data Field: dfCultId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set dfCultId.sSQLCOLNAME = 'ROYALTY_PAYABLE.CULTIVAR_ID'
.head 6 -  Set dfCultId.hWndOperatorField = cmbCultIdOp
.head 6 -  Set dfCultId.hWndNotField = cbNOTCultId
.head 3 +  Data Field: dfCultDesc
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set dfCultDesc.sSQLCOLNAME = 'CULTIVAR.CULT_DESC'
.head 6 -  Set dfCultDesc.hWndOperatorField = cmbCultDescOp
.head 6 -  Set dfCultDesc.hWndNotField = cbNOTCultDesc
.head 6 -  Set dfCultDesc.sOperator = ' LIKE '
.head 6 -  Set dfCultDesc.bCompareUpCase = TRUE
.head 3 +  Data Field: dfRootId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set dfRootId.sSQLCOLNAME = 'ROYALTY_PAYABLE.ROOTSTOCK_ID'
.head 6 -  Set dfRootId.hWndOperatorField = cmbRootIdOp
.head 6 -  Set dfRootId.hWndNotField = cbNOTRootId
.head 3 +  ! clsQueryDataField: dfRootDesc
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set dfRootDesc.sSQLCOLNAME = 'ROOTSTOCK.ROOT_DESC'
.head 6 -  Set dfRootDesc.hWndOperatorField = cmbRootDescOp
.head 6 -  Set dfRootDesc.hWndNotField = cbNOTRootDesc
.head 6 -  Set dfRootDesc.sOperator = ' LIKE '
.head 6 -  Set dfRootDesc.bCompareUpCase = TRUE
.head 3 -  !
.head 3 +  Check Box: cbNOTCultId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cbNOTCultId.hWndQueryField = dfCultId
.head 3 +  Check Box: cbNOTCultDesc
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cbNOTCultDesc.hWndQueryField = dfCultDesc
.head 3 +  Check Box: cbNOTRootId
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cbNOTRootId.hWndQueryField = dfRootId
.head 3 +  ! clsQueryNOTField: cbNOTRootDesc
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cbNOTRootDesc.hWndQueryField = dfRootDesc
.head 3 -  !
.head 3 +  Combo Box: cmbCultIdOp
.head 4 -  List Initialization 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cmbCultIdOp.hWndQueryField = dfCultId
.head 6 -  Set cmbCultIdOp.sOperator = ' = '
.head 3 +  Combo Box: cmbCultDescOp
.head 4 -  List Initialization 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cmbCultDescOp.hWndQueryField = dfCultDesc
.head 6 -  Set cmbCultDescOp.sOperator = ' LIKE '
.head 3 +  Combo Box: cmbRootIdOp
.head 4 -  List Initialization 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cmbRootIdOp.hWndQueryField = dfRootId
.head 6 -  Set cmbRootIdOp.sOperator = ' = '
.head 3 +  ! clsQueryOperatorField: cmbRootDescOp
.head 4 -  List Initialization 
.head 4 +  Message Actions 
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set cmbRootDescOp.hWndQueryField = dfCultDesc
.head 6 -  Set cmbRootDescOp.sOperator = ' LIKE '
.head 3 -  !
.head 3 +  Data Field: dfUser
.head 4 -  Message Actions 
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Message Actions 
.head 3 -  Background Text: Season
.head 3 +  Data Field: dfDatabase
.head 4 -  Message Actions 
.head 2 -  Functions 
.head 2 -  Window Parameters 
.head 2 -  Window Variables 
.head 2 +  Message Actions 
.head 3 +  On PAM_cls_SETINSTANCEVARS
.head 4 -  Set bMapEnterToTab = TRUE
.head 4 -  Set hWndFirstFocus = dfCultDesc
.head 1 +  Dialog Box: dlgQueryOwnerPatents
.head 2 -  Class: clsdlgQueryOwnersPatents
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: 1.05"
.head 4 -  Top: 1.688"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 5
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 7
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClear
.head 5 -  Class Child Ref Key: 21
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 22
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsdlgQueryOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 1
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 2
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 3
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 46919
.head 4 -  Class Child Ref Key: 4
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 46920
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 46921
.head 4 -  Class Child Ref Key: 10
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 46922
.head 4 -  Class Child Ref Key: 11
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfCultId
.head 4 -  Class Child Ref Key: 12
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfCultDesc
.head 4 -  Class Child Ref Key: 13
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfRootId
.head 4 -  Class Child Ref Key: 14
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTCultId
.head 4 -  Class Child Ref Key: 15
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTCultDesc
.head 4 -  Class Child Ref Key: 16
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Check Box: cbNOTRootId
.head 4 -  Class Child Ref Key: 17
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Title:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbCultIdOp
.head 4 -  Class Child Ref Key: 18
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbCultDescOp
.head 4 -  Class Child Ref Key: 19
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 3 +  Combo Box: cmbRootIdOp
.head 4 -  Class Child Ref Key: 20
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsdlgQueryOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Editable? Class Default
.head 4 -  String Type: Class Default
.head 4 -  Maximum Data Length: Class Default
.head 4 -  Sorted? Class Default
.head 4 -  Always Show List? Class Default
.head 4 -  Vertical Scroll? Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Input Mask: Class Default
.head 4 -  List Initialization
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
.head 1 +  Form Window: frmOwnersPatents
.head 2 -  Class: clsfrmOwnersPatents
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Icon File:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? Yes
.head 3 -  Automatically Created at Runtime? Class Default
.head 3 -  Initial State: Class Default
.head 3 -  Maximizable? Class Default
.head 3 -  Minimizable? Class Default
.head 3 -  Allow Child Docking? No
.head 3 -  Docking Orientation: All
.head 3 -  System Menu? Class Default
.head 3 -  Resizable? Class Default
.head 3 -  Window Location and Size
.head 4 -  Left: 0.0"
.head 4 -  Top: 0.0"
.head 4 -  Width:  Class Default
.head 4 -  Width Editable? Class Default
.head 4 -  Height: Class Default
.head 4 -  Height Editable? Class Default
.head 3 -  Form Size
.head 4 -  Width:  Class Default
.head 4 -  Height: Class Default
.head 4 -  Number of Pages: Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 2 -  Description:
.head 2 -  Named Menus
.head 2 -  Menu
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbSelect
.head 5 -  Class Child Ref Key: 24
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbAddRows
.head 5 -  Class Child Ref Key: 8
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbSaveRows
.head 5 -  Class Child Ref Key: 9
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbQuery
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 4.663"
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbDeleteRows
.head 5 -  Class Child Ref Key: 11
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRePopulate
.head 5 -  Class Child Ref Key: 12
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbTools
.head 5 -  Class Child Ref Key: 13
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbFirstRec
.head 5 -  Class Child Ref Key: 20
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 6.913"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrevRec
.head 5 -  Class Child Ref Key: 21
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 7.263"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbNextRec
.head 5 -  Class Child Ref Key: 22
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 7.613"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbLastRec
.head 5 -  Class Child Ref Key: 23
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 7.963"
.head 6 -  Top: 0.042"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 37
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbItemEnq
.head 5 -  Class Child Ref Key: 38
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 39
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 47
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbClearRows
.head 5 -  Class Child Ref Key: 48
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pb17
.head 5 -  Class Child Ref Key: 50
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDClose
.head 5 -  Class Child Ref Key: 51
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbRFIDRead
.head 5 -  Class Child Ref Key: 52
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsfrmOwnersPatents
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Class Default
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  Background Text:
.head 4 -  Resource Id: 48441
.head 4 -  Class Child Ref Key: 16
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 -  Background Text:
.head 4 -  Resource Id: 48442
.head 4 -  Class Child Ref Key: 17
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Data Field: dfOwnerId
.head 4 -  Class Child Ref Key: 18
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfOwnerBusName
.head 4 -  Class Child Ref Key: 19
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Child Table: tblOwnerPatents
.head 4 -  Class Child Ref Key: 25
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  View: Class Default
.head 5 -  Allow Row Sizing? Class Default
.head 5 -  Lines Per Row: Class Default
.head 4 -  Memory Settings
.head 5 -  Maximum Rows in Memory: Class Default
.head 5 -  Discardable? Class Default
.head 4 +  Contents
.head 5 +  Column: colRoyInstanceNo
.head 6 -  Class Child Ref Key: 26
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colCultId
.head 6 -  Class Child Ref Key: 27
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colCultDesc
.head 6 -  Class Child Ref Key: 28
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colRootId
.head 6 -  Class Child Ref Key: 29
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colRootDesc
.head 6 -  Class Child Ref Key: 30
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colCurrency
.head 6 -  Class Child Ref Key: 42
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPercentage
.head 6 -  Class Child Ref Key: 46
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colCurrencyAmtPayable
.head 6 -  Class Child Ref Key: 43
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colAmtPayable
.head 6 -  Class Child Ref Key: 31
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPayDueDate
.head 6 -  Class Child Ref Key: 32
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colPaidUptoDate
.head 6 -  Class Child Ref Key: 44
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 5 +  Column: colDueEveryMonths
.head 6 -  Class Child Ref Key: 45
.head 6 -  Class ChildKey: 0
.head 6 -  Class: clsfrmOwnersPatents
.head 6 -  Property Template:
.head 6 -  Class DLL Name:
.head 6 -  Title:
.head 6 -  Visible? Class Default
.head 6 -  Editable? Class Default
.head 6 -  Maximum Data Length: Class Default
.head 6 -  Data Type: Class Default
.head 6 -  Justify: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Format: Class Default
.head 6 -  Country: Class Default
.head 6 -  Input Mask: Class Default
.head 6 -  Cell Options
.head 7 -  Cell Type? Class Default
.head 7 -  Multiline Cell? Class Default
.head 7 -  Cell DropDownList
.head 8 -  Sorted? Class Default
.head 8 -  Vertical Scroll? Class Default
.head 8 -  Auto Drop Down? Class Default
.head 8 -  Allow Text Editing? Class Default
.head 7 -  Cell CheckBox
.head 8 -  Check Value:
.head 8 -  Uncheck Value:
.head 8 -  Ignore Case? Class Default
.head 6 -  List Values
.head 6 -  Message Actions
.head 4 -  Functions
.head 4 -  Window Variables
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 33
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 34
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 48443
.head 4 -  Class Child Ref Key: 35
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 36
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsfrmOwnersPatents
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 2 -  Functions
.head 2 -  Window Parameters
.head 2 -  Window Variables
.head 2 -  Message Actions
