.head 0 +  Application Description: SQLWindows 5.01 Jans Multiline Field Class
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C636C6173
0040: 733B6B3A5C63656E 747572615C666C65 6D61706C73000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D80000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF160000 0016000000AA0200 0053010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.1"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 6.6"
.head 3 -  Top: 0.521"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: VTSPIN.APL
.head 2 -  File Include: RUNPROG.APL
.head 2 -  File Include: VTWIN.APL
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for MLFIELD.APL
.head 4 -  Number: MLAplMsgOffSet = SAM_User + 2400
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: MLAplConstOffSet = 1200
.head 4 -  !
.head 4 -  Number: PAM_clsML_ENABLE = MLAplMsgOffSet + 1
.head 4 -  Number: PAM_clsML_DISABLE = MLAplMsgOffSet + 2
.head 4 -  !
.head 4 -  Number: PAM_clsML_SHOW = MLAplMsgOffSet + 3
.head 4 -  Number: PAM_clsML_HIDE = MLAplMsgOffSet + 4
.head 4 -  !
.head 4 -  Number: PAM_clsML_CLEAR = MLAplMsgOffSet + 5
.head 4 -  Number: PAM_clsML_ZOOMEND = MLAplMsgOffSet + 6
.head 4 -  !
.head 4 -  Number: ML_ClearOnInit = MLAplConstOffSet + 1
.head 4 -  Number: ML_DisableOnInit = MLAplConstOffSet + 2
.head 4 -  Number: ML_EnableOnInit = MLAplConstOffSet + 3
.head 4 -  Number: ML_HideOnInit = MLAplConstOffSet + 4
.head 4 -  Number: ML_ShowOnInit = MLAplConstOffSet + 5
.head 4 -  Number: ML_NothingOnInit = MLAplConstOffSet + 6
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 3792329508
0000: D60000009B000000 0000000000000000 0200000700000046 0100001019000000
0020: 017001F093000000 4073000000010000 A35F010019250001 706905B800000073
0040: D100010000687801 0019008901706A05 006E007300340100 0091015A00190004
0060: 8070019708000000 9B7300018D00AA01 009619000170E0C3 1E00000046730001
0080: 0000A3C301001925 0001708B24B80000 0073D10001000068 DC01001900090170
00A0: 002C00006E007300 3001000000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 1098747780
0000: 1B0E00000C090000 0000000000000000 0200001A00FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F04003C00 000C63006C736D6C
0040: 47656E650072616C 2200000001780000 00040A0000036601 0518000000F20073
0060: B000000001000101 8046000000014200 0011636C70006253 746172745072006F
0080: 6772616DD60000E0 00070000002D0400 0266600106000000 46C8017300000136
00A0: 000400046B000207 DA000046B3000100 C108000000049A00 020800F600466C00
00C0: 01000C8000000019 0000008001660109 0000003D4600011A 0000250000AC0004
00E0: 0003610A00000046 CF00010600290000 00046B00020BD800 000046B3000100C1
0100: 2D00000019920001 660C00F600466800 0100000100805200 000002000090000F
0120: 636C5374FF913001 000A00DE0019D200 016605C600580173 680001000019B300
0140: 1900B4016606003D 5800011A00003200 002C00040002666D 070058CF00010600
0160: 36000000046B0002 08DB0058B3000100 C13A00000004DA00 0209F600586C0001
0180: 003EB00000000400 B6020A003D580001 1B00420000AC0004 00026D0B0058CF00
01A0: 012600460000046B 00020CDB0058B300 0100C14A00000004 1A00020D0000F600
01C0: 586C0001004EB000 0000040086020E00 00003D5800011B00 0180190200000300
01E0: 00000C9663704765 776C00F401000096 19000166360700DC 0146730001000003
0200: 0180680000008604 0009636C0348656C 709A00D000000500 005B040002DF0018
0220: E801730001006D00 04009619000166B6 0800E84700010000 831D00000019A500
0240: 016609ED00E8D100 0100006636001900 6901660A007BE800 340100004F005800
0260: 00190001DA660B00 1EE80001008D0001 801999000500090F 4578697444220000
0280: 0100006F19006901 6607004702730000 3401000001804404 00000600000E0C50
02A0: 696345807870616E 642200E800010000 2D040002666F0078 CC02730001C60001
02C0: 80040C0007001263 6C0F546F6767006C 65427574746F6E44 2200000100006F04
02E0: 006D020600638402 7300360100018066 040008000E0C6466 4765FFE800010000
0300: 2D040003666F00A2 CC02730001060001 8053000008000900 000B636C01466F72
0320: 6D426173C8659A00 0005DE0019D20001 660886001A037300 680001000019B300
0340: 0400B60209003D1A 0001DB001D2C0019 0004666C010A001A CF00013600360004
0360: 6A0000030BDB001A B3000100CD3A0019 D20001660CF6001A 680001000001CC80
0380: 19000AF00017636C 015072696E744261 0169635265706F72 8C7422000100DE00
03A0: 19D200016609C600 9803736800010000 018C8004000B0010 0010636C546F6F00
03C0: 6C54697057696E64 106F772200000100 BD0004B50003050D 0028047300D90001
03E0: 0018018053000C00 3900104469C0616C 6F674765279A0000 057B00194B000166
0400: 1218000000520473 A300010000CD1900 041A0002130000F6 00526C0001001DB3
0420: 0019008404661400 00003D520001DB00 36A8000400000361 1500000052CF0001
0440: 36003A00194B0001 6616D800000052A3 0001000031018019 000D720000115300
0460: 70696E536561736F 806E596561722200 E8000100002D1900 01666D0600EE8C04
0480: 7300010086000180 1D0008000E00000D 636C03656E64456D 6100696C73400000
04A0: 00027A0000194B00 0166051B00A80573 A20000010000CD19 0004D200026606F6
04C0: 00A86C000100010C 8004000F00001800 0C63726247BB6522 D1000100005B0400
04E0: 02DF0098FC057300 018D0001801D8100 100000000CE36362 4727400000027A00
0500: 0019CB0001661B00 140673A200000100 00CD190004D20002 6607F600146C0001
0520: 0001008064000000 110000500014636C 705300656C656374 46726F006D546162
0540: 6C657C00D8000004 005B190001DE6600 186806730001006D 0019009619000166
0560: B608006847000100 009B320019A50001 6609ED0068D10001 0000604B00000019
0580: 006901660A007B68 0034010000018046 0400120000EE0D53 0263496E746F2200
05A0: D1000100005B0400 03DB050098800673 00010C0000018081 0010000013000008
05C0: 6370514F456DC0B0 0000000600B71900 BC016600319E0673 0001DA0000192C00
05E0: 190001666D08009E 8F00010036003200 194B0001660BDB00 9EA300010000CD4B
0600: 0019D20001660EF6 009E680001000064 B200001900A40166 1100003D9E00011A
0620: 00007D00000C0004 00010266ED14003F 8001F80000000701 803B010009140000
0640: 16636CF947659C54 6147658F8A0200F4 1500009619000166 360600F206467300
0660: 0100009B190019A5 00016607ED00F2D1 0001000066320019 0069016608007BF2
0680: 00B40100004B5900 190001DA6609001E F20001006D006400 D6040002B60A00F2
06A0: 6700010093680000 04B500020BED00F2 D9000100606C0000 0004006D020C007B
06C0: F200360100700058 0000040002DB0D00 9EF200010D007400 0000D6040002B60E
06E0: 00F2670001008378 000000043500020F 00ED00F2D9000100 647C000004004D02
0700: 1000007BF200B601 0080180000040001 02DB12007F80F201 00000F8400000086
0720: 1900010166F61300 9F8001FC00008B88 000019A500016614 ED00F2D100010000
0740: 60A1000000190069 016616007BF20034 010000BA00580000 190001C266170000
0760: 001EF20001000D00 D300000096190001 66B018000000F247 0001000083EC0000
0780: 0019250001661A00 EC0000F2D1000100 0068050100190009 01661C0000007BF2
07A0: 00340100001E015A 00190001D2661D00 001EF20001008D00 370100D6040003B0
07C0: 1E000000F2670001 004301803A000086 15001D636C005462 6C4D616B65531665
07E0: 63656452006F774B 6579417272906179 84000004BD0004B1 00010205FD002780
0800: 010000FF66040019 006901660600433A 0773000034010000 1D005900190001DA
0820: 6607001E3A000100 6D003600D6040002 B608003A67000100 6301801D00C41600
0840: 00106300436F6C75 6D6E4765CF6C40E8 000200002D040002 666D05004C8C0773
0860: 0001003600040019 4B00016606DB004C A300010000310180 0400171200000C66
0880: 5461036543616368 6544220000010000 6F04006D03070043 4A09730000360100
08A0: 0180402100000018 0000E00B63664361 08506F6F66000000 F403000006290001
08C0: 076601A10001004A 009E008001FC0000 9B040004A5000366 098D00560973D900
08E0: 0100640800001900 6901660A007B5600 3401000001806619 001900000C67774D
0900: 6F757365C0576865 656C22E800010000 2D19000166EF008D 730001000600
.enddata
.head 3 +  Multiline Field Class: clsmlGeneral
.head 4 -  Data
.head 5 -  Maximum Data Length: 32000
.head 5 -  String Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Border? Class Default
.head 5 -  Word Wrap? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  1.0"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.667"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 -  Derived From
.head 4 +  Class Variables
.head 5 -  Window Handle: hWndSrc
.head 4 +  Instance Variables
.head 5 -  Number: nActionOnInitialize
.head 5 -  String: sFieldName
.head 5 -  Number: nLength
.head 4 -  Functions
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set nActionOnInitialize = ML_ClearOnInit
.head 6 -  Set sFieldName = 'Multiple Line Field'
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETINSTANCEVARS, 0, 0 ) 
.head 5 +  On SAM_DragDrop
.head 6 -  Set hWndSrc = SalNumberToWindowHandle( wParam )
.head 6 +  If hWndSrc != hWndItem AND SalParentWindow( hWndSrc ) = hWndForm
.head 7 -  Call SalDragDropStop(  )
.head 7 -  Call SalModalDialog( dlgMLZoom, hWndForm, hWndItem, sFieldName, SalHStringToNumber( MyValue ) )
.head 5 +  On PAM_clsML_ZOOMEND
.head 6 -  Set MyValue = SalNumberToHString( lParam )
.head 6 -  Return TRUE
.head 5 -  !
.head 5 +  On PAM_cls_INITIALISE
.head 6 +  Select Case nActionOnInitialize
.head 7 +  Case ML_ClearOnInit
.head 8 -  Call SalSendMsg( hWndItem, PAM_clsML_CLEAR, 0, 0 )
.head 8 -  Break
.head 7 +  Case ML_DisableOnInit
.head 8 -  Call SalSendMsg( hWndItem, PAM_clsML_DISABLE, 0, 0 )
.head 8 -  Break
.head 7 +  Case ML_EnableOnInit
.head 8 -  Call SalSendMsg( hWndItem, PAM_clsML_ENABLE, 0, 0 )
.head 8 -  Break
.head 7 +  Case ML_HideOnInit
.head 8 -  Call SalSendMsg( hWndItem, PAM_clsML_HIDE, 0, 0 )
.head 8 -  Break
.head 7 +  Case ML_ShowOnInit
.head 8 -  Call SalSendMsg( hWndItem, PAM_clsML_SHOW, 0, 0 )
.head 8 -  Break
.head 5 -  !
.head 5 +  On PAM_clsML_DISABLE
.head 6 -  Return SalDisableWindow( hWndItem )
.head 5 +  On PAM_clsML_ENABLE
.head 6 -  Return SalEnableWindow( hWndItem )
.head 5 +  On PAM_clsML_HIDE
.head 6 -  Return SalHideWindow( hWndItem )
.head 5 +  On PAM_clsML_SHOW
.head 6 -  Return SalShowWindow( hWndItem )
.head 5 +  On PAM_clsML_CLEAR
.head 6 -  Return SalClearField( hWndItem )
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
.head 1 +  Dialog Box: dlgMLZoom
.head 2 -  Class: clsDialogGeneral
.head 2 -  Property Template:
.head 2 -  Class DLL Name:
.head 2 -  Title:
.head 2 -  Accessories Enabled? Class Default
.head 2 -  Visible? Class Default
.head 2 -  Display Settings
.head 3 -  Display Style? Class Default
.head 3 -  Visible at Design time? No
.head 3 -  Type of Dialog: Modal
.head 3 -  Allow Dock to Parent? No
.head 3 -  Docking Orientation: All
.head 3 -  Window Location and Size
.head 4 -  Left: -0.013"
.head 4 -  Top: 0.99"
.head 4 -  Width:  9.975"
.head 4 -  Width Editable? Class Default
.head 4 -  Height: 4.865"
.head 4 -  Height Editable? Class Default
.head 3 -  Absolute Screen Location? Class Default
.head 3 -  Font Name: Class Default
.head 3 -  Font Size: Class Default
.head 3 -  Font Enhancement: Class Default
.head 3 -  Text Color: Class Default
.head 3 -  Background Color: Class Default
.head 3 -  Resizable? No
.head 3 -  Vertical Scroll? Yes
.head 3 -  Horizontal Scroll? Yes
.head 2 -  Description:
.head 2 +  Tool Bar
.head 3 -  Display Settings
.head 4 -  Display Style? Class Default
.head 4 -  Location? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Size: Class Default
.head 4 -  Size Editable? Class Default
.head 4 -  Docking Toolbar? Class Default
.head 4 -  Toolbar Docking Orientation: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 4 -  Resizable? Class Default
.head 3 +  Contents
.head 4 +  Pushbutton: pbOk
.head 5 -  Class Child Ref Key: 0
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clspbOk
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: 4.85"
.head 6 -  Top: 0.021"
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbHelp
.head 5 -  Class Child Ref Key: 6
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbPrintForm
.head 5 -  Class Child Ref Key: 10
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 4 +  Pushbutton: pbExit
.head 5 -  Class Child Ref Key: 15
.head 5 -  Class ChildKey: 0
.head 5 -  Class: clsDialogGeneral
.head 5 -  Property Template:
.head 5 -  Class DLL Name:
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Keyboard Accelerator: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Picture File Name:
.head 5 -  Picture Transparent Color: Class Default
.head 5 -  Image Style: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Button Appearance: Standard
.head 5 -  Message Actions
.head 2 +  Contents
.head 3 -  !
.head 3 +  Multiline Field: mlZoom
.head 4 -  Class Child Ref Key: 0
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsmlGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  String Type: Long String
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Border? Class Default
.head 5 -  Word Wrap? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Window Location and Size
.head 6 -  Left: 0.05"
.head 6 -  Top: 0.292"
.head 6 -  Width:  9.763"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 3.635"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfDatabase
.head 4 -  Class Child Ref Key: 8
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Data Field: dfUser
.head 4 -  Class Child Ref Key: 9
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Data
.head 5 -  Maximum Data Length: Class Default
.head 5 -  Data Type: Class Default
.head 5 -  Editable? Class Default
.head 4 -  Display Settings
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Justify: Class Default
.head 5 -  Format: Class Default
.head 5 -  Country: Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  Input Mask: Class Default
.head 4 -  Message Actions
.head 3 +  Custom Control: ccSeasonYear
.head 4 -  Class Child Ref Key: 13
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left: Class Default
.head 6 -  Top: Class Default
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  Message Actions
.head 3 -  Background Text:
.head 4 -  Resource Id: 54742
.head 4 -  Class Child Ref Key: 14
.head 4 -  Class ChildKey: 0
.head 4 -  Class: clsDialogGeneral
.head 4 -  Window Location and Size
.head 5 -  Left: Class Default
.head 5 -  Top: Class Default
.head 5 -  Width:  Class Default
.head 5 -  Width Editable? Class Default
.head 5 -  Height: Class Default
.head 5 -  Height Editable? Class Default
.head 4 -  Visible? Class Default
.head 4 -  Justify: Class Default
.head 4 -  Font Name: Class Default
.head 4 -  Font Size: Class Default
.head 4 -  Font Enhancement: Class Default
.head 4 -  Text Color: Class Default
.head 4 -  Background Color: Class Default
.head 2 -  Functions
.head 2 +  Window Parameters
.head 3 -  Window Handle: hWndParent
.head 3 -  String: sFieldName
.head 3 -  Number: nStrFieldValue
.head 2 +  Window Variables
.head 3 -  Number: nFontEnhancements
.head 3 -  Number: nFontSize
.head 3 -  String: sFontName
.head 2 +  Message Actions
.head 3 +  On SAM_Create
.head 4 -  Call SalSetWindowText( hWndForm, sFieldName || ' ZOOM ' )
.head 4 -  Set mlZoom = SalNumberToHString( nStrFieldValue )
.head 4 -  !
.head 4 +  If SalIsWindowEnabled( hWndParent )
.head 5 -  Call SalEnableWindow( mlZoom )
.head 4 +  Else
.head 5 -  Call SalDisableWindow( mlZoom )
.head 4 -  Call SalSetMaxDataLength( mlZoom, SalGetMaxDataLength( hWndParent ) )
.head 4 -  Call SalFontGet( hWndParent, sFontName, nFontSize, nFontEnhancements )
.head 4 -  Call SalFontSet( mlZoom, sFontName, nFontSize, nFontEnhancements )
.head 4 -  Call SalFmtSetFormat( mlZoom, SalFmtGetFormat( hWndParent ) )
.head 4 -  !
.head 4 -  Set bMapEnterToTab = FALSE
.head 4 -  Return SalSendClassMessage( SAM_Create, wParam, lParam )
.head 3 +  On PAM_clsPB_OKACTION
.head 4 -  Call SalSendMsg( hWndParent, PAM_clsML_ZOOMEND, 0, SalHStringToNumber( mlZoom ) )
.head 4 -  Return SalSendMsg( pbExit, SAM_Click, TRUE, 0 )
