.head 0 +  Application Description: SQLWindows 5.01 Jans Spin Field Class
.data CLASSPROPSSIZE
0000: 5C00
.enddata
.data CLASSPROPS
0000: 557365476C6F6261 6C50617468000400 0100000000417070 506174684C656E00
0020: 0400240000000041 7070506174680024 006B3A5C63656E74 7572615C636C6173
0040: 733B6B3A5C63656E 747572615C666C65 6D61706C73000000 00000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000D60000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF420000 00420000000D0300 007B010000010000 0000000000010000
0060: 000F4170706C6963 6174696F6E497465 6D0200000007436C 617373657311636C
0080: 735370696E536561 736F6E59656172
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.data VIEWINFO
0000: 1418B80BB80B2500
.enddata
.data VIEWSIZE
0000: 0800
.enddata
.head 3 -  Visible? Yes
.head 3 -  Left: 5.1"
.head 3 -  Top: 2.896"
.head 3 -  Width:  4.688"
.head 3 -  Height: 2.99"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 6.6"
.head 3 -  Top: 0.521"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  ! File Include: Pick.apl
.head 2 -  File Include: Datfield.apl
.head 2 -  File Include: vtwin.apl
.head 2 -  File Include: vtspin.apl
.head 2 -  File Include: Bgtext.apl
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Dialog Box
.head 4 -  Display Style? Etched
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Gray
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Italic
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: Sky
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Dark Blue
.head 4 -  Background Color: White
.head 3 +  Line
.head 4 -  Line Color: Black
.head 3 +  Frame
.head 4 -  Border Color: Black
.head 4 -  Background Color: Gray
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! For PAM_User messages for SPNFIELD.APL
.head 4 -  Number: SPNAplMsgOffSet = SAM_User + 2000
.head 4 -  Number: PAM_clsSPN_VALIDATE = SPNAplMsgOffSet + 1
.head 4 -  Number: PAM_clsSPN_ENABLE = SPNAplMsgOffSet + 2
.head 4 -  Number: PAM_clsSPN_DISABLE = SPNAplMsgOffSet + 3
.head 4 -  Number: PAM_clsSPN_SHOW = SPNAplMsgOffSet + 4
.head 4 -  Number: PAM_clsSPN_HIDE = SPNAplMsgOffSet + 5
.head 4 -  ! Message go up to AplOffSet + 99
.head 4 -  Number: SPNAplConstOffSet = 1000
.head 4 -  !
.head 3 -  Enumerations
.head 2 +  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 2637807998
0000: 9A00000070000000 0000000000000000 0200000500000010 0100001019000000
0020: 01FC00F0B2000000 4073000000010000 A329010019250001 FC3A01BA000073D1
0040: 0001000068420100 19008901FC3B0100 6E00730034010000 5B015A0019000182
0060: FC95030000001B73 0001008D00740100 16190004FC00E085 0E00000066730001
0080: 0003
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 3 +  ! Function: WhichSeasonYear
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Number: 
.head 4 +  Parameters 
.head 5 -  Date/Time: dtCurrentDate
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 +  If dtCurrentDate >= SalDateConstruct( SalDateYear( dtCurrentDate ), 9, 1, 0, 0, 0 )
.head 6 -  Return OurDateYear( SalDateConstruct( SalDateYear( dtCurrentDate )+1, SalDateMonth( dtCurrentDate ), SalDateDay( dtCurrentDate ), 0, 0, 0 ) )
.head 5 +  Else 
.head 6 -  Return OurDateYear( dtCurrentDate )
.head 3 +  Function: WhichDateRangeSeasonYear
.head 4 -  Description:
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Number: nYear
.head 5 -  Receive Date/Time: dtFromDate
.head 5 -  Receive Date/Time: dtToDate
.head 4 -  Static Variables
.head 4 -  Local variables
.head 4 +  Actions
.head 5 +  If nYear <= 96
.head 6 -  Set nYear = nYear + 1900
.head 5 -  Set dtFromDate = SalDateConstruct( nYear-1, 10, 1, 0, 0, 0 )
.head 5 -  Set dtToDate = SalDateConstruct( nYear, 9, 30, 23, 59, 59 )
.head 3 +  Function: WhichTypeOfSeason
.head 4 -  Description: Returns 'WINTER', 'OTHER'
.head 4 +  Returns
.head 5 -  String:
.head 4 +  Parameters
.head 5 -  Date/Time: dtDate
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Date/Time: dtStartWinter
.head 5 -  Date/Time: dtEndWinter
.head 4 +  Actions
.head 5 -  Set dtStartWinter = SalDateConstruct( SalDateYear( dtDate ), 6, 1, 0, 0, 0 )
.head 5 -  Set dtEndWinter = SalDateConstruct( SalDateYear( dtDate ), 8, 31, 23, 59, 059 )
.head 5 +  If dtDate >= dtStartWinter AND dtDate <= dtEndWinter
.head 6 -  Return 'WINTER'
.head 5 +  Else
.head 6 -  Return 'OTHER'
.head 2 +  Class Definitions
.data RESOURCE 0 0 1 4037103321
0000: 860800008D050000 0000000000000000 0200001200FFFF01 00160000436C6173
0020: 73566172004F7574 6C696E6552006567 496E666F19003C00 001163006C735370
0040: 696E53650061736F 6E59656172002200 0000010000004F19 00000101FC000600
0060: 0000031001730000 0034010000018040 0400000001000008 0C636C6466476580
0080: 6E6572616C2200EC 0001002904000003 FC6E00003ACC0173 0001060001805300
00A0: 0000000200000010 636C014469616C6F 67473E659A00C000 00050000005B1900
00C0: 01CAFC12000018B2 01730001006D0019 0016040002FC00B0 13000000B2670001
00E0: 00831D0000001905 0004FC001400EC00 00B2D90001004036 0000000400000D03
0100: 150000007BB20036 01003A0058000019 0001CAFC1600001E B20001000D000180
0120: 1900810003000000 0CC3706247653722 00017A0000194B00 01FC07180000003C
0140: 0273A20000010000 0101806800000004 C30009636C814865 6C709A00EC000500
0160: AD0400026F00488C 0273000100360004 00194B0001FC08D8 00000048A3000100
0180: 00CD1D0019120001 FC090000F6004868 0001000036B30019 008401FC0A000000
01A0: 3D4800011A00004F 00002C00190001FC 610B000000488F00 0100C6000180198C
01C0: 0005000963074578 697422A200000100 00B71900B401FC07 003160027300011A
01E0: 0000018004330006 000C075069634578 4070616E64220000 F4010000D6040002
0200: 3700D80266730001 0063018004008607 0012636C07546F67 676C006542757474
0220: 6F6E22A200000100 00B70400B6020600 31E4027300011B00 018053330008000B
0240: 04636C466F726D42 206173659A000005 7B00194B0001FC08 1B00200373A20000
0260: 010000CD1900049A 00020900F600206C 0001001DB3001900 B404FC0A003D2000
0280: 01DB003628000400 0003FC690B000020 CF000136003A0019 4B0001FC0CD80000
02A0: 0020A30001000031 0180190009C30017 636C075072696E74 0442616963526570
02C0: 306F72742200017A 0000194B0001FC09 1B009E0373A30001 000031018004000A
02E0: 73001054006F6F6C 5469705769406E64 6F77220000F40100 00D6040003360500
0300: 2804647300000100 03018046000000E6 0B00110270537461 72745000726F6772
0320: 616DD600D8000007 005B040002DB0600 185804730001006D 000400D6040002B6
0340: 070058670001009B 080004B5000208ED 0058D9000100660C 0019006901FC0900
0360: 7B58003401000025 00580000040003DB 0A009E5800010D00 29000000D6040002
0380: B60B005867000100 832D00000019A500 01FC0CED0058D100 0100008001805200
03A0: 00000C21000F636C 5374FFA33001000A BD0019A50001FC05 8D006A0473D10001
03C0: 0000661900190069 01FC06007B6A0034 0100003200580000 040002DB07009E6A
03E0: 00016D003600D604 0002B608006A6700 01009B3A0004B500 0209ED006AD90001
0400: 00603E0000000400 6D020A007B6A0036 0100420058000004 0002DB0B009E6A00
0420: 014D00460000D604 0002B60C006A6700 0100834A00000004 3500020D00EC0000
0440: 6AD9000100604E00 000004000D020E00 00007B6A00360100 01806604000D008C
0460: 0C63726247EF6CE8 00010000AD040002 6D060042C8057300 0001860001801D00
0480: CC000E000CF16362 4703400000000200 BD0019E50001FC8D 005A0573D1000100
04A0: 0066190004006902 FC07007B5A003601 000180061D000F00 0000080D636C5365
04C0: 6E6400456D61696C 734000D100020000 5B190001DAFC0500 18C605730001006D
04E0: 00190096040002FC B60600C667000100 0301808100000000 100000000863514F
0500: 1C456DC00000EC00 06002D190001FC6D 0500148806730000 010036001900194B
0520: 0001FC08DA000014 A300010000CD3200 19D20001FC0BF600 1468000100004BB0
0540: 0000001900B401FC 0E003D1400011A00 006400002C001900 01FC611100000014
0560: 8F00010006007D00 00000443000102FC 14FA00000F800100 00FE003101800400
0580: 1173000C6DE86C47 6565462200010000 6F04006D03050063 20067300360100
.enddata
.head 3 +  ! Custom Control Class: clsSpinGeneral
.winattr
.head 4 -  DLL Name: vt50.dll
.head 4 -  Display Settings
.head 5 -  DLL Name: vt50.dll
.head 5 -  MS Windows Class Name: VT:cSpinField
.head 5 -  Style:  0x00000000
.head 5 -  ExStyle:  0x00000000
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  0.838"
.head 6 -  Width Editable? Yes
.head 6 -  Height: 0.323"
.head 6 -  Height Editable? Yes
.head 5 -  Visible? Yes
.head 5 -  Border? Yes
.head 5 -  Etched Border? Yes
.head 5 -  Hollow? No
.head 5 -  Vertical Scroll? No
.head 5 -  Horizontal Scroll? No
.head 5 -  Tab Stop? Tab
.head 5 -  Tile To Parent? No
.head 5 -  Font Name: Default
.head 5 -  Font Size: Default
.head 5 -  Font Enhancement: Default
.head 5 -  Text Color: Default
.head 5 -  Background Color: White
.head 5 -  DLL Settings
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name: vti60.dll
.end
.head 4 -  Description: Changes the IsValidNumber( ) so that any user input between min
max ranges is valid and doesnt need to be a multiple of nIncrement
.head 4 +  Derived From 
.head 5 -  Class: cSpinField
.head 4 -  Class Variables 
.head 4 +  Instance Variables 
.head 5 -  Number: nMinValue
.head 5 -  Number: nMaxValue
.head 5 -  Number: nIncrement
.head 5 -  Number: nAdjust
.head 5 -  Number: nInitialValue
.head 5 -  Boolean: bEditable
.head 4 +  Functions 
.head 5 +  Function: IsValidNumber
.head 6 -  Description: Same as IsValidNumber except doesnt return false if the
number is not a multiple of nIncrement.
.head 6 +  Returns 
.head 7 -  Boolean: 
.head 6 -  Parameters 
.head 6 -  Static Variables 
.head 6 +  Local variables 
.head 7 -  String: sValue
.head 7 -  Number: nValue
.head 6 +  Actions 
.head 7 -  Set sValue = GetNumber()
.head 7 -  !
.head 7 -  ! ***** Validate for valid number
.head 7 +  If Not SalStrIsValidNumber( sValue )
.head 8 -  Return FALSE
.head 7 -  !
.head 7 -  ! ***** Test if value is on an increment
.head 7 +  If nAdjust
.head 8 -  Set nValue = SalStrToNumber( sValue ) / SalNumberPower( 10, nAdjust )
.head 7 +  Else 
.head 8 -  Set nValue = SalStrToNumber( sValue )
.head 7 -  !
.head 7 -  ! ***** Test if value out of range
.head 7 +  If nValue < nMinValue or nValue > nMaxValue
.head 8 -  Return FALSE
.head 7 -  !
.head 7 -  Return TRUE
.head 4 +  Message Actions 
.head 5 +  On SAM_Create
.head 6 -  Set nMinValue = 0
.head 6 -  Set nMaxValue = 10
.head 6 -  Set nIncrement = 1
.head 6 -  Set nAdjust = 0
.head 6 -  Set nInitialValue = 0
.head 6 -  Set bEditable = TRUE
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETINSTANCEVARS, 0, 0 )
.head 6 -  Call SetNumberProperties( nMinValue, nMaxValue, nIncrement, nAdjust )
.head 6 -  Call SetNumber( nInitialValue )
.head 6 +  If bEditable
.head 7 -  Call SalSendMsg( hWndItem, PAM_clsSPN_ENABLE, 0, 0 )
.head 6 +  Else 
.head 7 -  Call SalSendMsg( hWndItem, PAM_clsSPN_DISABLE, 0, 0 )
.head 5 +  On PAM_clsSPN_DISABLE
.head 6 -  Call SalDisableWindow( hWndItem )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsSPN_ENABLE
.head 6 -  Call SalEnableWindow( hWndItem )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsSPN_SHOW
.head 6 -  Call SalShowWindow( hWndItem )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsSPN_HIDE
.head 6 -  Call SalHideWindow( hWndItem )
.head 6 -  Return TRUE
.head 3 +  Custom Control Class: clsSpinGeneral
.head 4 -  DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  0.975"
.head 6 -  Width Editable? Class Default
.head 6 -  Height: 0.271"
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: cSpinField
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Number: nMinValue
.head 5 -  Number: nMaxValue
.head 5 -  Number: nIncrement
.head 5 -  Number: nAdjust
.head 5 -  Number: nInitialValue
.head 5 -  Boolean: bEditable
.head 4 +  Functions
.head 5 +  Function: IsValidNumber
.head 6 -  Description: Same as IsValidNumber except doesnt return false if the
number is not a multiple of nIncrement.
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  String: sValue
.head 7 -  Number: nValue
.head 6 +  Actions
.head 7 -  Set sValue = GetNumber()
.head 7 -  !
.head 7 -  ! ***** Validate for valid number
.head 7 +  If Not SalStrIsValidNumber( sValue )
.head 8 -  Return FALSE
.head 7 -  !
.head 7 -  ! ***** Test if value is on an increment
.head 7 +  If nAdjust
.head 8 -  Set nValue = SalStrToNumber( sValue ) / SalNumberPower( 10, nAdjust )
.head 7 +  Else
.head 8 -  Set nValue = SalStrToNumber( sValue )
.head 7 -  !
.head 7 -  ! ***** Test if value out of range
.head 7 +  If nValue < nMinValue or nValue > nMaxValue
.head 8 -  Return FALSE
.head 7 -  !
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 -  Set nMinValue = 0
.head 6 -  Set nMaxValue = 10
.head 6 -  Set nIncrement = 1
.head 6 -  Set nAdjust = 0
.head 6 -  Set nInitialValue = 0
.head 6 -  Set bEditable = TRUE
.head 6 -  Call SalSendMsg( hWndItem, PAM_cls_SETINSTANCEVARS, 0, 0 )
.head 6 -  Call SetNumberProperties( nMinValue, nMaxValue, nIncrement, nAdjust )
.head 6 -  Call SetNumber( nInitialValue )
.head 6 +  If bEditable
.head 7 -  Call SalSendMsg( hWndItem, PAM_clsSPN_ENABLE, 0, 0 )
.head 6 +  Else
.head 7 -  Call SalSendMsg( hWndItem, PAM_clsSPN_DISABLE, 0, 0 )
.head 5 +  On PAM_clsSPN_DISABLE
.head 6 -  Call SalDisableWindow( hWndItem )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsSPN_ENABLE
.head 6 -  Call SalEnableWindow( hWndItem )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsSPN_SHOW
.head 6 -  Call SalShowWindow( hWndItem )
.head 6 -  Return TRUE
.head 5 +  On PAM_clsSPN_HIDE
.head 6 -  Call SalHideWindow( hWndItem )
.head 6 -  Return TRUE
.head 3 +  Custom Control Class: clsSpinSeasonYear
.head 4 -  DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsSpinGeneral
.head 4 +  Class Variables
.head 5 -  Number: nSeasonYear
.head 4 -  Instance Variables
.head 4 +  Functions
.head 5 +  Function: GetSeasonYear
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return nSeasonYear
.head 5 +  Function: SetSeasonYear
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 +  Parameters
.head 7 -  Date/Time: dtCurrentDate
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return WhichSeasonYear( dtCurrentDate )
.head 5 -  !
.head 5 +  Function: IncSeasonYear
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Number: nIncAmt
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: nYear
.head 6 +  Actions
.head 7 -  Set nSeasonYear = nSeasonYear + nIncAmt
.head 7 +  If nSeasonYear >=97 AND nSeasonYear <=99
.head 8 -  Set nSeasonYear = nSeasonYear + 1900
.head 7 +  Else If nSeasonYear >=0 AND nSeasonYear <=50
.head 8 -  Set nSeasonYear = nSeasonYear + 2000
.head 5 +  Function: DecSeasonYear
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Number: nDecAmt
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set nSeasonYear = nSeasonYear - nDecAmt
.head 7 +  If nSeasonYear <1997 AND nSeasonYear >1950
.head 8 -  Set nSeasonYear = nSeasonYear - 1900
.head 5 -  !
.head 5 +  Function: GetDateRangeSeasonYear
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Receive Date/Time: dtStartDate
.head 7 -  Receive Date/Time: dtEndDate
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Call WhichDateRangeSeasonYear( nSeasonYear, dtStartDate, dtEndDate )
.head 5 -  !
.head 5 +  Function: MatchSeasonYearToSpinField
.head 6 -  Description:
.head 6 -  Returns
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If nSeasonYear != SalStrToNumber( GetNumber(  ) )
.head 8 -  Call SetNumber( nSeasonYear )
.head 8 -  Call SalSendMsg( hWndItem, PAM_clsSPN_VALIDATE, 0, 0 )
.head 5 -  !
.head 5 +  Function: IsValidNumber
.head 6 -  Description: Same as IsValidNumber except doesnt return false if the
number is not a multiple of nIncrement.
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  String: sValue
.head 7 -  Number: nValue
.head 6 +  Actions
.head 7 -  Set sValue = clsSpinSeasonYear.GetNumber()
.head 7 -  !
.head 7 -  ! ***** Validate for valid number
.head 7 +  If Not SalStrIsValidNumber( sValue )
.head 8 -  Return FALSE
.head 7 -  !
.head 7 -  Set nValue = SalStrToNumber( sValue )
.head 7 -  !
.head 7 +  If nValue >=97 AND nValue <=99
.head 8 -  Set nValue = nValue + 1900
.head 8 -  Call clsSpinSeasonYear.SetNumber( nValue )
.head 7 +  Else If nValue >=0 AND nValue <=50
.head 8 -  Set nValue = nValue + 2000
.head 8 -  Call clsSpinSeasonYear.SetNumber( nValue )
.head 7 -  Set nSeasonYear = nValue
.head 7 -  !
.head 7 -  Return TRUE
.head 4 +  Message Actions
.head 5 +  On SAM_Create
.head 6 +  If NOT nSeasonYear > 0
.head 7 -  Set nSeasonYear = SetSeasonYear( SalDateCurrent(  ) )
.head 6 -  Call SalSendClassMessage( SAM_Create, wParam, lParam )
.head 6 -  Return SetNumber( nSeasonYear )
.head 5 +  On SAM_Validate
.head 6 +  If IsValidNumber(  )
.head 7 -  Call SalSendMsg( hWndItem, PAM_clsSPN_VALIDATE, 0, 0 )
.head 7 -  Return VALIDATE_Ok
.head 6 +  Else
.head 7 -  Return VALIDATE_Cancel
.head 5 +  On VTM_SpinSetValue
.head 6 -  Call SalSendMsg( hWndItem, PAM_clsSPN_VALIDATE, 0, 0 )
.head 5 +  On VTM_SpinScrollUp
.head 6 -  Call IncSeasonYear( nIncrement )
.head 6 -  Call SetNumber( nSeasonYear )
.head 6 -  Call SalSendMsg( hWndItem, PAM_clsSPN_VALIDATE, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  On VTM_SpinScrollDown
.head 6 -  Call DecSeasonYear( nIncrement )
.head 6 -  Call SetNumber( nSeasonYear )
.head 6 -  Call SalSendMsg( hWndItem, PAM_clsSPN_VALIDATE, 0, 0 )
.head 6 -  Return TRUE
.head 5 +  ! On PAM_clsFRM_ACTIVATE
.head 6 +  If wParam
.head 7 -  Call MatchSeasonYearToSpinField(  )
.head 5 +  On PAM_clsDLG_ACTIVATE
.head 6 +  If wParam
.head 7 -  Call MatchSeasonYearToSpinField(  )
.head 3 +  Custom Control Class: clsSpinYear
.head 4 -  DLL Name:
.head 4 -  Display Settings
.head 5 -  DLL Name:
.head 5 -  MS Windows Class Name:
.head 5 -  Style:  Class Default
.head 5 -  ExStyle:  Class Default
.head 5 -  Title:
.head 5 -  Window Location and Size
.head 6 -  Left:
.head 6 -  Top:
.head 6 -  Width:  Class Default
.head 6 -  Width Editable? Class Default
.head 6 -  Height: Class Default
.head 6 -  Height Editable? Class Default
.head 5 -  Visible? Class Default
.head 5 -  Border? Class Default
.head 5 -  Etched Border? Class Default
.head 5 -  Hollow? Class Default
.head 5 -  Vertical Scroll? Class Default
.head 5 -  Horizontal Scroll? Class Default
.head 5 -  Tab Stop? Class Default
.head 5 -  Tile To Parent? Class Default
.head 5 -  Font Name: Class Default
.head 5 -  Font Size: Class Default
.head 5 -  Font Enhancement: Class Default
.head 5 -  Text Color: Class Default
.head 5 -  Background Color: Class Default
.head 5 -  DLL Settings
.head 4 -  List in Tool Palette? Yes
.head 4 -  Property Template:
.head 4 -  Class DLL Name:
.head 4 -  Description:
.head 4 +  Derived From
.head 5 -  Class: clsSpinGeneral
.head 4 -  Class Variables
.head 4 -  Instance Variables
.head 4 +  Functions
.head 5 +  Function: GetYear
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalStrToNumber( clsSpinYear.GetNumber( ) )
.head 4 +  Message Actions
.head 5 +  On PAM_cls_SETINSTANCEVARS
.head 6 -  Set clsSpinYear.nMinValue = 0
.head 6 -  Set clsSpinYear.nMaxValue = 9999
.head 6 -  Set clsSpinYear.nIncrement =1
.head 6 -  Set clsSpinYear.nInitialValue = SalDateYear( SalDateCurrent ( ) )
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
