.head 0 +  Application Description: Jans string handling routines. Ver 5.01
.data CLASSPROPSSIZE
0000: 4800
.enddata
.data CLASSPROPS
0000: 4170705061746800 10006B3A5C63656E 747572615C636C61 7373004170705061
0020: 74684C656E000400 1000000000557365 476C6F62616C5061 7468000400010000
0040: 0000000000000000
.enddata
.head 1 -  Outline Version - 4.0.32
.head 1 +  Design-time Settings
.data VIEWINFO
0000: 6F00000001000000 FFFF01000D004347 5458566965775374 6174650400010000
0020: 0000000000DA0000 002C000000020000 0003000000FFFFFF FFFFFFFFFFFCFFFF
0040: FFE8FFFFFF6E0000 006E000000FE0200 00A7010000010000 0001000000010000
0060: 000F4170706C6963 6174696F6E497465 6D00000000
.enddata
.head 2 -  Outline Window State: Maximized
.head 2 +  Outline Window Location and Size
.data VIEWINFO
0000: 6600010000001B00 0200000000000000 0000E119990B0500 1D00FFFF4D61696E
0020: 00
.enddata
.data VIEWSIZE
0000: 2100
.enddata
.head 3 -  Left: 0.15"
.head 3 -  Top: 0.042"
.head 3 -  Width:  7.875"
.head 3 -  Height: 4.635"
.head 2 +  Options Box Location
.head 3 -  Visible? Yes
.head 3 -  Left: 6.05"
.head 3 -  Top: 3.104"
.head 3 -  Width:  3.738"
.head 3 -  Height: 2.781"
.head 2 +  Class Editor Location
.head 3 -  Visible? No
.head 3 -  Left: Default
.head 3 -  Top: Default
.head 3 -  Width:  Default
.head 3 -  Height: Default
.head 2 +  Tool Palette Location
.head 3 -  Visible? No
.head 3 -  Left: 6.6"
.head 3 -  Top: 0.521"
.head 2 -  Fully Qualified External References? No
.head 2 -  Reject Multiple Window Instances? No
.head 2 -  Enable Runtime Checks Of External References? No
.head 2 -  Use Release 4.0 Scope Rules? Yes
.head 1 +  Libraries
.head 2 -  File Include: Dates.apl
.head 2 -  ! File Include: General.apl
.head 2 -  File Include: number.apc
.head 2 -  File Include: vtdos.apl
.head 2 -  File Include: vtarray.apl
.head 2 -  File Include: ClassFunctions.apl
.head 2 -  ! Dynalib: STRINGS.APD
.head 2 -  ! Dynalib: dates.apd
.head 1 +  Global Declarations
.head 2 +  Window Defaults
.head 3 +  Tool Bar
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Form Window
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Dialog Box
.head 4 -  Display Style? Standard
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Top Level Table Window
.head 4 -  Font Name: System Default
.head 4 -  Font Size: System Default
.head 4 -  Font Enhancement: System Default
.head 4 -  Text Color: System Default
.head 4 -  Background Color: System Default
.head 3 +  Data Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Multiline Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Spin Field
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Background Text
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Pushbutton
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Radio Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Check Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Option Button
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 3 +  Group Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Child Table Window
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  List Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Combo Box
.head 4 -  Font Name: Use Parent
.head 4 -  Font Size: Use Parent
.head 4 -  Font Enhancement: Use Parent
.head 4 -  Text Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Line
.head 4 -  Line Color: Use Parent
.head 3 +  Frame
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 3 +  Picture
.head 4 -  Border Color: Use Parent
.head 4 -  Background Color: Use Parent
.head 2 +  Formats
.head 3 -  Number: 0%
.head 3 -  Number: #0
.head 3 -  Number: ###000
.head 3 -  Number: ###000;###000
.head 3 -  Date/Time: hh:mm:ss AMPM
.head 3 -  Date/Time: M/d/yy
.head 3 -  Date/Time: MM-dd-yy
.head 3 -  Date/Time: dd-MMM-yyyy
.head 3 -  Date/Time: MMM d, yyyy
.head 3 -  Date/Time: MMM d, yyyy hh:mm AMPM
.head 3 -  Date/Time: MMMM d, yyyy hh:mm AMPM
.head 2 +  External Functions
.head 2 +  Constants
.data CCDATA
0000: 3000000000000000 0000000000000000 00000000
.enddata
.data CCSIZE
0000: 1400
.enddata
.head 3 +  System
.head 3 +  User
.head 4 -  ! Reinserted from cstrings.apl to get migration happening
.head 4 -  Number: ARRAY_Null_Terminated = -999
.head 4 -  ! For PAM_User messages for STRINGS.APL
.head 4 -  Number: STRAplMsgOffSet = SAM_User + 1000
.head 4 -  ! Message go up to AplMsgOffSet + 99
.head 4 -  Number: STRAplConstOffSet = 500
.head 4 -  !
.head 4 -  Number: ARRAY_Reset = STRAplConstOffSet + 1
.head 4 -  Number: ARRAY_FetchNext = STRAplConstOffSet + 2
.head 4 -  Number: ARRAY_FetchPrevious = STRAplConstOffSet + 3
.head 4 -  Number: ARRAY_FetchLast = STRAplConstOffSet + 4
.head 4 -  Number: ARRAY_FetchFirst = STRAplConstOffSet + 5
.head 4 -  !
.head 4 -  !
.head 3 -  Enumerations
.head 2 -  Resources
.head 2 +  Variables
.data RESOURCE 0 0 1 1424004272
0000: 4000000034000000 0000000000000000 020000020000003A 0000001019000000
0020: 016401E0A7010000 0040730000000100 0083530000001925 000164A801BA0000
0040: 73D100010000
.enddata
.head 2 +  Named Menus
.head 2 +  Internal Functions
.head 3 +  ! Function: StringReplace  
.head 4 -  Description: Given the source string, the search string and the replacing string.
This function finds every occurance of Search String in source string
and replaces it with Replace String.  The source string will contain
the replaced characters on return.
.head 4 -  Returns 
.head 4 +  Parameters 
.head 5 -  Receive String: sSourceStr  
.head 5 -  String: sSearchStr  
.head 5 -  String: sReplaceStr  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nOffSet  
.head 5 -  String: sNewSourceStr  
.head 5 -  String: sTmpStr  
.head 4 +  Actions 
.head 5 -  Set sNewSourceStr = ''
.head 5 +  Loop 
.head 6 -  Set nOffSet = SalStrScan( sSourceStr, sSearchStr )
.head 6 +  If nOffSet >= 0
.head 7 -  Call SalStrLeft( sSourceStr, nOffSet, sTmpStr )
.head 7 -  Set sNewSourceStr = sNewSourceStr || sTmpStr || sReplaceStr
.head 7 -  Call SalStrMid( sSourceStr, nOffSet + SalStrLength( sSearchStr ), SalStrLength( sSourceStr ) - ( nOffSet + SalStrLength( sSearchStr ) ), sSourceStr )
.head 6 +  Else 
.head 7 -  Set sNewSourceStr = sNewSourceStr || sSourceStr
.head 7 -  Break 
.head 5 -  Set sSourceStr = sNewSourceStr
.head 3 +  ! Function: StringValidate
.head 4 -  Description: 10/12/2003 (PXD) Ensures that the string given are within valid parameters.
Only normal alpha/numeric values and Underscores are allowed.
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: sString
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nCharValue
.head 5 -  Number: nLoopCount
.head 5 -  Boolean: bValidString
.head 4 +  Actions 
.head 5 -  !
.head 5 -  Set bValidString = TRUE 					! Initialise flag string as valid
.head 5 -  Set nLoopCount = SalStrLength( sString )			! Get count of loops to perform
.head 5 +  While nLoopCount > 0					! While still more to do...
.head 6 -  Set nLoopCount = nLoopCount - 1				! Decrement loop control counter
.head 6 -  !
.head 6 -  Set nCharValue = SalStrLop( sString ) 				! Get ASCII value of character
.head 6 -  !
.head 6 +  If (nCharValue > 47 AND nCharValue < 58 )
	OR ( nCharValue > 64 AND nCharValue < 91 )
	OR ( nCharValue > 94 AND nCharValue < 123)		! Ensure type of character is valid (alpha/numerics)
.head 7 -  ! Valid character - do nothing
.head 6 +  Else 
.head 7 -  Set bValidString = FALSE 					! flag entire string as invalid
.head 5 -  Return bValidString						! Return flag
.head 3 +  ! Function: StringScan  
.head 4 -  Description: Works just like SalStrScan except if case sensitivity is required set bCaseSensitive = TRUE
.head 4 +  Returns 
.head 5 -  Number: 
.head 4 +  Parameters 
.head 5 -  String: sString1  
.head 5 -  String: sString2  
.head 5 -  Boolean: bCaseSensitive  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Boolean: bFound  
.head 5 -  Number: nOffSet  
.head 4 +  Actions 
.head 5 +  If bCaseSensitive
.head 6 -  Set bFound = FALSE
.head 6 -  Set nOffSet = 0
.head 6 +  While NOT bFound AND nOffSet >= 0
.head 7 -  Set nOffSet = SalStrScan( sString1, sString2 )
.head 7 +  If nOffSet >= 0
.head 8 +  If SalStrMidX( sString1, nOffSet, SalStrLength( sString2 ) ) = sString2
.head 9 -  Set bFound = TRUE
.head 8 +  Else 
.head 9 -  Set sString1 = SalStrReplaceX( sString1, nOffSet, SalStrLength( sString2 ), SalStrRepeatX( ' ', SalStrLength( sString2 ) ) )
.head 6 -  Return nOffSet
.head 5 +  Else 
.head 6 -  Return SalStrScan( sString1, sString2 )
.head 3 +  ! Function: StringEndPad
.head 4 -  Description: 
.head 4 -  Returns 
.head 4 +  Parameters 
.head 5 -  Receive String: sSource  
.head 5 -  String: sPad  
.head 5 -  Number: nLength  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nActualLength  
.head 4 +  Actions 
.head 5 -  Set nActualLength = SalStrLength( sSource )
.head 5 +  While nActualLength < nLength
.head 6 -  Set sSource = sSource || sPad
.head 6 -  Set nActualLength = SalStrLength( sSource )
.head 3 +  ! Function: StringEndPadX
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sSource  
.head 5 -  String: sPad  
.head 5 -  Number: nLength  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sTmp
.head 4 +  Actions 
.head 5 -  Set sTmp = sSource
.head 5 -  Call StringEndPad( sTmp, sPad, nLength )
.head 5 -  Return sTmp
.head 3 +  ! Function: RemoveStringBetweenCharMarks  
.head 4 -  Description: Returns a string with the substring encapsulated by starting and ending characters removed.
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sInputStr  
.head 5 -  String: sStartCharacter  
.head 5 -  String: sEndCharacter  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nStartCharPos  
.head 5 -  Number: nEndCharPos  
.head 5 -  String: sFirstInputStr  
.head 5 -  String: sLastInputStr  
.head 5 -  String: sTmpInputStr  
.head 5 -  String: sOutputStr  
.head 4 +  Actions 
.head 5 -  Set nStartCharPos = SalStrScan( sInputStr, sStartCharacter )
.head 5 +  If nStartCharPos >= 0
.head 6 -  Set sFirstInputStr = SalStrLeftX( sInputStr, nStartCharPos )
.head 6 -  Set sTmpInputStr = SalStrRightX( sInputStr, SalStrLength( sInputStr ) - nStartCharPos - SalStrLength( sStartCharacter ) )
.head 6 -  Set nEndCharPos = SalStrScan( sTmpInputStr, sEndCharacter )
.head 6 +  If nEndCharPos >= 0
.head 7 -  Set sLastInputStr = SalStrRightX( sTmpInputStr, SalStrLength( sTmpInputStr ) - nEndCharPos - SalStrLength( sEndCharacter ))
.head 6 +  Else 
.head 7 -  Set sLastInputStr = ''
.head 6 -  Set sOutputStr = sFirstInputStr || sLastInputStr
.head 5 +  Else 
.head 6 -  Set sOutputStr = sInputStr
.head 5 -  Return sOutputStr
.head 3 -  !
.head 3 +  Function: StrArrayFind  
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  String: saStringArray[*]  
.head 5 -  ! nArrayCount = number of elements or ARRAY_Null_Terminated constant
.head 5 -  Number: nArrayCount  
.head 5 -  String: sStrToFind  
.head 5 -  Receive Number: nFoundPos  
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: nPos  
.head 5 -  Boolean: bFound  
.head 4 +  Actions
.head 5 -  Set nFoundPos = NUMBER_Null
.head 5 -  Set nPos = 0
.head 5 -  Set bFound = FALSE
.head 5 +  If nArrayCount = ARRAY_Null_Terminated
.head 6 +  While saStringArray[ nPos ] != '' AND NOT bFound
.head 7 +  If saStringArray[ nPos ] = sStrToFind
.head 8 -  Set bFound = TRUE
.head 8 -  Set nFoundPos = nPos
.head 7 -  Set nPos = nPos + 1
.head 5 +  Else
.head 6 +  While nPos <= nArrayCount AND NOT bFound
.head 7 +  If saStringArray[ nPos ] = sStrToFind
.head 8 -  Set bFound = TRUE
.head 8 -  Set nFoundPos = nPos
.head 7 -  Set nPos = nPos + 1
.head 5 -  Return bFound
.head 3 +  Function: NumArrayFind  
.head 4 -  Description:
.head 4 +  Returns
.head 5 -  Boolean:
.head 4 +  Parameters
.head 5 -  Number: naNumberArray[*]  
.head 5 -  ! nArrayCount = number of elements or ARRAY_Null_Terminated constant
.head 5 -  Number: nArrayCount  
.head 5 -  Number: nNumToFind  
.head 5 -  Receive Number: nFoundPos  
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: nPos  
.head 5 -  Boolean: bFound  
.head 4 +  Actions
.head 5 -  Set nFoundPos = NUMBER_Null
.head 5 -  Set nPos = 0
.head 5 -  Set bFound = FALSE
.head 5 +  If nArrayCount = ARRAY_Null_Terminated
.head 6 +  While naNumberArray[ nPos ] != NUMBER_Null AND NOT bFound
.head 7 +  If naNumberArray[ nPos ] = nNumToFind
.head 8 -  Set bFound = TRUE
.head 8 -  Set nFoundPos = nPos
.head 7 -  Set nPos = nPos + 1
.head 5 +  Else
.head 6 +  While nPos <= nArrayCount AND NOT bFound
.head 7 +  If naNumberArray[ nPos ] = nNumToFind
.head 8 -  Set bFound = TRUE
.head 8 -  Set nFoundPos = nPos
.head 7 -  Set nPos = nPos + 1
.head 5 -  Return bFound
.head 3 +  ! Function: DTArrayFind  
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Date/Time: dtaDateTimeArray[*]  
.head 5 -  ! nArrayCount = number of elements or ARRAY_Null_Terminated constant
.head 5 -  Number: nArrayCount  
.head 5 -  Date/Time: dtDateTimeToFind  
.head 5 -  Receive Number: nFoundPos  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nPos  
.head 5 -  Boolean: bFound  
.head 4 +  Actions 
.head 5 -  Set nFoundPos = NUMBER_Null
.head 5 -  Set nPos = 0
.head 5 -  Set bFound = FALSE
.head 5 +  If nArrayCount = ARRAY_Null_Terminated
.head 6 +  While dtaDateTimeArray[ nPos ] != DATETIME_Null AND NOT bFound
.head 7 +  If dtaDateTimeArray[ nPos ] = dtDateTimeToFind
.head 8 -  Set bFound = TRUE
.head 8 -  Set nFoundPos = nPos
.head 7 -  Set nPos = nPos + 1
.head 5 +  Else 
.head 6 +  While nPos <= nArrayCount AND NOT bFound
.head 7 +  If dtaDateTimeArray[ nPos ] = dtDateTimeToFind
.head 8 -  Set bFound = TRUE
.head 8 -  Set nFoundPos = nPos
.head 7 -  Set nPos = nPos + 1
.head 5 -  Return bFound
.head 3 -  !
.head 3 +  Function: MakeStringList  
.head 4 -  Description: This functions make a any character separated list into sStringList from the array saStrings[*].
VERY IMPORTANT ASSUMPTION : saStrings[*] is assumed to be terminated by a NULL value.
PARAMETERS :
  saStirng[*] : array of strings terminated by a NULL value
  sSeparator : string used as the list string separator
                       eg: jan, michelle, dani the comma is the separator
  sQuoteType : string used as the type of character for the quotes around the strings.
                         eg: "jan", "michelle", "dani" the double quote is the quote type character
                         note use sQueryType of blank to obtain a non quoted string list.
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  String: saStrings[*]  
.head 5 -  String: sSeparator  
.head 5 -  String: sQuoteType  
.head 5 -  Receive String: sStringList  
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: naStringPos  
.head 5 -  Boolean: bFirst  
.head 4 +  Actions
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bFirst = TRUE
.head 5 -  Set sStringList = ''
.head 5 -  Set naStringPos = 0
.head 5 +  While saStrings[ naStringPos ] != ''
.head 6 +  If bFirst
.head 7 -  Set sStringList = sQuoteType || saStrings[ naStringPos ] || sQuoteType
.head 7 -  Set bFirst = FALSE
.head 6 +  Else
.head 7 -  Set sStringList = sStringList || sSeparator || sQuoteType || saStrings[ naStringPos ] || sQuoteType
.head 6 -  Set naStringPos = naStringPos + 1
.head 5 -  Call OurWaitCursor( FALSE )
.head 3 +  ! Function: MakeDateTimeList  
.head 4 -  Description: This functions make a any character separated list into sStringList from the array dtaDT[*].
VERY IMPORTANT ASSUMPTION : dtaDT[*] is assumed to be terminated by a DATETIME_NULL value.
PARAMETERS :
  dtaDT[*] : array of DateTime stamps terminated by a DATETIME_NULL value
  sSeparator : string used as the list string separator
                       eg: jan, michelle, dani the comma is the separator
  sQuoteType : string used as the type of character for the quotes around the strings.
                         eg: "jan", "michelle", "dani" the double quote is the quote type character
                         note use sQueryType of blank to obtain a non quoted string list.
.head 4 -  Returns 
.head 4 +  Parameters 
.head 5 -  Date/Time: dtaDT[*]  
.head 5 -  String: sSeparator  
.head 5 -  String: sQuoteType  
.head 5 -  Receive String: sStringList  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: naStringPos  
.head 5 -  Boolean: bFirst  
.head 5 -  String: sDate  
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bFirst = TRUE
.head 5 -  Set sStringList = ''
.head 5 -  Set naStringPos = 0
.head 5 +  While dtaDT[ naStringPos ] != DATETIME_Null
.head 6 -  Call SalDateToStr( dtaDT[ naStringPos ], sDate )
.head 6 +  If bFirst
.head 7 -  Set sStringList = sQuoteType || sDate || sQuoteType
.head 7 -  Set bFirst = FALSE
.head 6 +  Else 
.head 7 -  Set sStringList = sStringList || sSeparator || sQuoteType || sDate || sQuoteType
.head 6 -  Set naStringPos = naStringPos + 1
.head 5 -  Call OurWaitCursor( FALSE )
.head 3 +  Function: MakeNumberList  
.head 4 -  Description: This functions make a any character separated list into sStringList from the array naNumber[*].
VERY IMPORTANT ASSUMPTION : naDT[*] is assumed to be terminated by a NUMBER_NULL value.
PARAMETERS :
  naNumber[*] : array of DateTime stamps terminated by a NUMBER_NULL value
  nPrecision : number of precision decimal places applied through out naNumber[*]
  sSeparator : string used as the list string separator
                       eg: jan, michelle, dani the comma is the separator
  sQuoteType : string used as the type of character for the quotes around the strings.
                         eg: "jan", "michelle", "dani" the double quote is the quote type character
                         note use sQueryType of blank to obtain a non quoted string list.
.head 4 -  Returns
.head 4 +  Parameters
.head 5 -  Number: naNumber[*]  
.head 5 -  Number: nPrecision  
.head 5 -  String: sSeparator  
.head 5 -  String: sQuoteType  
.head 5 -  Receive String: sStringList  
.head 4 -  Static Variables
.head 4 +  Local variables
.head 5 -  Number: naStringPos  
.head 5 -  Boolean: bFirst  
.head 5 -  String: sNumber  
.head 4 +  Actions
.head 5 -  Set bFirst = TRUE
.head 5 -  Set sStringList = ''
.head 5 -  Set naStringPos = 0
.head 5 +  While naNumber[ naStringPos ] != NUMBER_Null
.head 6 -  Set sNumber = SalNumberToStrX( naNumber[ naStringPos ], nPrecision )
.head 6 +  If bFirst
.head 7 -  Set sStringList = sQuoteType || sNumber || sQuoteType
.head 7 -  Set bFirst = FALSE
.head 6 +  Else
.head 7 -  Set sStringList = sStringList || sSeparator || sQuoteType || sNumber || sQuoteType
.head 6 -  Set naStringPos = naStringPos + 1
.head 3 -  !
.head 3 +  ! Function: StringField
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sField
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Return '"' || sField || '",'
.head 3 +  ! Function: NumberField
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Number: nValue
.head 5 -  Number: nNumericPlaces
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Return SalNumberToStrX( nValue, nNumericPlaces ) || ', '
.head 3 +  ! Function: DateField
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Date/Time: dtDate
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sDate
.head 4 +  Actions 
.head 5 -  Set sDate = ''
.head 5 -  Call SalDateToStr( dtDate, sDate )
.head 5 -  Return sDate || ', '
.head 3 +  ! Function: StringFieldSpecificChar
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sField
.head 5 -  String: sChar
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Return '"' || sField || '"' || sChar
.head 3 +  ! Function: NumberFieldSpecificChar
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Number: nValue
.head 5 -  Number: nNumericPlaces
.head 5 -  String: sChar
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Return SalNumberToStrX( nValue, nNumericPlaces ) || sChar
.head 3 +  ! Function: DateFieldSpecificChar
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Date/Time: dtDate
.head 5 -  String: sChar
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sDate
.head 4 +  Actions 
.head 5 -  Set sDate = ''
.head 5 -  Call SalDateToStr( dtDate, sDate )
.head 5 -  Return sDate || sChar
.head 3 -  !
.head 3 +  ! Function: StrCSVTokenize  
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Number: 
.head 4 +  Parameters 
.head 5 -  String: sCSVLine  
.head 5 -  Receive String: sCSVFields[*]  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nFieldPos  
.head 5 -  Number: nCharPos  
.head 5 -  Number: nNumChars  
.head 5 -  String: sField  
.head 5 -  String: sPosChar  
.head 5 -  Boolean: bQuoteOpen  
.head 4 +  Actions 
.head 5 -  Set nNumChars = SalStrLength( sCSVLine )
.head 5 -  Set nFieldPos = 0
.head 5 -  Set sCSVFields[ nFieldPos ] = ''
.head 5 -  Set nCharPos = 0
.head 5 -  Set sField = ''
.head 5 +  While nCharPos < nNumChars
.head 6 -  Set sPosChar = SalStrMidX( sCSVLine, nCharPos, 1 )
.head 6 -  !
.head 6 +  If sPosChar = '"'
.head 7 +  If bQuoteOpen
.head 8 -  Set bQuoteOpen = FALSE
.head 7 +  Else 
.head 8 -  Set bQuoteOpen = TRUE
.head 6 +  Else If sPosChar = ',' AND NOT bQuoteOpen
.head 7 -  Set bQuoteOpen = FALSE
.head 7 -  Set sCSVFields[ nFieldPos ] = sField
.head 7 -  Set nFieldPos = nFieldPos + 1
.head 7 -  Set sCSVFields[ nFieldPos ] = ''
.head 7 -  Set sField = ''
.head 6 +  Else 
.head 7 -  Set sField = sField || sPosChar
.head 6 -  Set nCharPos = nCharPos + 1
.head 5 -  Set sCSVFields[ nFieldPos ] = sField
.head 5 -  Set nFieldPos = nFieldPos + 1
.head 5 -  Set sCSVFields[ nFieldPos ] = ''
.head 5 -  Return nFieldPos
.head 3 -  !
.head 3 +  ! Function: WriteStrArrayListToFile  
.head 4 -  Description: Assumption is that the saString[ * ] is termintated by a NULL string
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: saStrings[*]  
.head 5 -  String: sFileName  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  File Handle: hOutFile  
.head 5 -  Number: naStringPos  
.head 5 -  Boolean: bOk  
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 +  If SalFileOpen( hOutFile, sFileName, OF_Create | OF_ReadWrite | OF_Text )
.head 6 -  Set naStringPos = 0
.head 6 +  While saStrings[ naStringPos ] != ''
.head 7 +  If NOT SalFilePutStr( hOutFile, saStrings[ naStringPos ] )
.head 8 -  Set bOk = FALSE
.head 7 -  Set naStringPos = naStringPos + 1
.head 6 +  If NOT SalFileClose( hOutFile )
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 +  ! Function: WriteNumArrayListToFile  
.head 4 -  Description: Assumption is that the naNumber[ * ] is termintated by a NUMBER_Null
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: sFileName  
.head 5 -  Number: naNumber[*]  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  File Handle: hOutFile  
.head 5 -  Number: naPos  
.head 5 -  Boolean: bOk  
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 +  If SalFileOpen( hOutFile, sFileName, OF_Create | OF_ReadWrite | OF_Text )
.head 6 -  Set naPos = 0
.head 6 +  While naNumber[ naPos ] != NUMBER_Null
.head 7 +  If NOT SalFilePutStr( hOutFile, SalNumberToStrX( naNumber[ naPos ], 0 ))
.head 8 -  Set bOk = FALSE
.head 7 -  Set naPos = naPos + 1
.head 6 +  If NOT SalFileClose( hOutFile )
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 +  ! Function: WriteDateTimeArrayListToFile  
.head 4 -  Description: Assumption is that the dtaDateTime[ * ] is termintated by a NUMBER_Null
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: sFileName  
.head 5 -  Date/Time: dtaDateTime[*]  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  File Handle: hOutFile  
.head 5 -  Number: naPos  
.head 5 -  Boolean: bOk  
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 +  If SalFileOpen( hOutFile, sFileName, OF_Create | OF_ReadWrite | OF_Text )
.head 6 -  Set naPos = 0
.head 6 +  While dtaDateTime[ naPos ] != DATETIME_Null
.head 7 +  If NOT SalFilePutStr( hOutFile, DateToStrX( dtaDateTime[ naPos ] ) )
.head 8 -  Set bOk = FALSE
.head 7 -  Set naPos = naPos + 1
.head 6 +  If NOT SalFileClose( hOutFile )
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 +  ! Function: ReadStrArrayListFromFile  
.head 4 -  Description: The saString[ * ] will be returned and is termintated by a NULL string
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: sFileName  
.head 5 -  Receive String: saStrings[*]  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  File Handle: hOutFile  
.head 5 -  Number: naStringPos  
.head 5 -  Boolean: bOk  
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 +  If SalFileOpen( hOutFile, sFileName, OF_ReadWrite | OF_Text )
.head 6 -  Set naStringPos = 0
.head 6 +  While SalFileGetStr( hOutFile, saStrings[ naStringPos ], 255 )
.head 7 -  Set naStringPos = naStringPos + 1
.head 6 -  Set saStrings[ naStringPos ] = ''
.head 6 +  If NOT SalFileClose( hOutFile )
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 +  ! Function: ReadNumArrayListFromFile  
.head 4 -  Description: The naNumber[ * ] will be returned and is termintated by a NUMBER_Null
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: sFileName  
.head 5 -  Receive Number: naNumber[*]  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  File Handle: hOutFile  
.head 5 -  Number: naPos  
.head 5 -  Boolean: bOk  
.head 5 -  String: sString  
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 +  If SalFileOpen( hOutFile, sFileName, OF_ReadWrite | OF_Text )
.head 6 -  Set naPos = 0
.head 6 +  While SalFileGetStr( hOutFile, sString, 255 )
.head 7 -  Set naNumber[ naPos ] = SalStrToNumber( sString )
.head 7 -  Set naPos = naPos + 1
.head 6 -  Set naNumber[ naPos ] = NUMBER_Null
.head 6 +  If NOT SalFileClose( hOutFile )
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 +  ! Function: ReadDateTimeArrayListFromFile  
.head 4 -  Description: The dtaDateTime[ * ] will be returned and is termintated by a NUMBER_Null
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: sFileName  
.head 5 -  Receive Date/Time: dtaDateTime[*]  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  File Handle: hOutFile  
.head 5 -  Number: naPos  
.head 5 -  Boolean: bOk  
.head 5 -  String: sString  
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 +  If SalFileOpen( hOutFile, sFileName, OF_ReadWrite | OF_Text )
.head 6 -  Set naPos = 0
.head 6 +  While SalFileGetStr( hOutFile, sString, 255 )
.head 7 -  Set dtaDateTime[ naPos ] = SalStrToDate( sString )
.head 7 -  Set naPos = naPos + 1
.head 6 -  Set dtaDateTime[ naPos ] = DATETIME_Null
.head 6 +  If NOT SalFileClose( hOutFile )
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 -  ! The previous to this point
.head 3 +  ! Function: StrArrayAppend
.head 4 -  Description: 
.head 4 -  Returns 
.head 4 +  Parameters 
.head 5 -  Receive String: saStringArray[*]
.head 5 -  ! nArrayCount = number of elements or ARRAY_Null_Terminated constant
.head 5 -  Receive Number: nArrayCount
.head 5 -  String: sStrToAdd
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nLastPos
.head 4 +  Actions 
.head 5 +  If nArrayCount = ARRAY_Null_Terminated
.head 6 -  Set nLastPos = StrArrayNullEndFindLastPos( saStringArray )
.head 6 -  Set saStringArray[ nLastPos ] = sStrToAdd
.head 6 -  Set saStringArray[ nLastPos + 1 ] = ''
.head 5 +  Else 
.head 6 -  Set saStringArray[ nArrayCount ] = sStrToAdd
.head 6 -  Set nArrayCount = nArrayCount + 1
.head 6 -  Set saStringArray[ nArrayCount ] = ''
.head 3 +  ! Function: StrArrayNullEndFindLastPos
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Number: 
.head 4 +  Parameters 
.head 5 -  String: saStringArray[*]
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nPos
.head 4 +  Actions 
.head 5 -  Set nPos = 0
.head 5 +  While saStringArray[ nPos ] != ''
.head 6 -  Set nPos = nPos + 1
.head 5 -  Return nPos
.head 3 +  ! Function: StrArrayClearOut
.head 4 -  Description: 
.head 4 -  Returns 
.head 4 +  Parameters 
.head 5 -  Receive String: saStringArray[*]
.head 5 -  ! nArrayCount = number of elements or ARRAY_Null_Terminated constant
.head 5 -  Receive Number: nArrayCount
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Set saStringArray[ 0 ] = ''
.head 5 +  If NOT nArrayCount = ARRAY_Null_Terminated
.head 6 -  Set nArrayCount = 0
.head 3 +  ! Function: StrArrayFetchStr
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: saStringArray[*]
.head 5 -  ! nArrayCount = number of elements or ARRAY_Null_Terminated constant
.head 5 -  Number: nArrayCount
.head 5 -  Receive String: sGotString
.head 5 -  Number: nActionType
.head 4 +  Static Variables 
.head 5 -  Number: nPos
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 +  Select Case nActionType
.head 6 +  Case ARRAY_Reset
.head 7 -  Set nPos = -1
.head 7 -  Return TRUE
.head 6 +  Case ARRAY_FetchNext
.head 7 -  Set nPos = nPos + 1
.head 7 +  If nArrayCount = ARRAY_Null_Terminated
.head 8 +  If saStringArray[ nPos ] = ''
.head 9 -  Set sGotString = ''
.head 9 -  Set nPos = nPos - 1
.head 9 -  Return FALSE
.head 8 +  Else 
.head 9 -  Set sGotString = saStringArray[ nPos ]
.head 9 -  Return TRUE
.head 7 +  Else 
.head 8 +  If nPos < nArrayCount
.head 9 -  Set sGotString = saStringArray[ nPos ]
.head 9 -  Return TRUE
.head 8 +  Else 
.head 9 -  Set sGotString = ''
.head 9 -  Set nPos = nPos - 1
.head 9 -  Return FALSE
.head 6 +  Case ARRAY_FetchPrevious
.head 7 -  Set nPos = nPos - 1
.head 7 +  If nPos < 0
.head 8 -  Set sGotString = ''
.head 8 -  Set nPos = nPos + 1
.head 8 -  Return FALSE
.head 7 +  Else 
.head 8 -  Set sGotString = saStringArray[ nPos ]
.head 8 -  Return TRUE
.head 6 +  Case ARRAY_FetchLast
.head 7 +  If nArrayCount = ARRAY_Null_Terminated
.head 8 -  Set nPos = StrArrayNullEndFindLastPos( saStringArray )
.head 8 -  Set sGotString = saStringArray[ nPos ]
.head 8 -  Return TRUE
.head 7 +  Else 
.head 8 -  Set nPos = nArrayCount -1
.head 8 -  Set sGotString = saStringArray[ nPos ]
.head 8 -  Return TRUE
.head 6 +  Case ARRAY_FetchFirst
.head 7 -  Set nPos = 0
.head 7 -  Set sGotString = saStringArray[ nPos ]
.head 7 -  Return TRUE
.head 3 +  ! Function: NumberToStrXNullNull
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Number: nNumber
.head 5 -  Number: nPrecision
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 +  If nNumber = NUMBER_Null
.head 6 -  Return ''
.head 5 +  Else 
.head 6 -  Return SalNumberToStrX( nNumber, nPrecision )
.head 3 +  ! Function: StrToNumberXNullNull
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Number: 
.head 4 +  Parameters 
.head 5 -  String: sString
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 +  If sString = ''
.head 6 -  Return NUMBER_Null
.head 5 +  Else 
.head 6 -  Return SalStrToNumber( sString )
.head 3 +  ! Function: ConvertStrHexToStrBinX
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sHex
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nStrHexLength
.head 5 -  String: sHexChar
.head 5 -  String: sBinChar
.head 5 -  Number: nPos
.head 5 -  Number: nDecChar
.head 5 -  String: sBin
.head 4 +  Actions 
.head 5 -  Set nStrHexLength = SalStrLength( sHex )
.head 5 -  Set sBin = ''
.head 5 -  Set nPos = 0
.head 5 +  While nPos < nStrHexLength
.head 6 -  !
.head 6 -  Set sHexChar = SalStrUpperX( SalStrMidX( sHex, nPos, 1 ) )
.head 6 +  If sHexChar = 'A'
.head 7 -  Set nDecChar = 10
.head 6 +  Else If sHexChar = 'B'
.head 7 -  Set nDecChar = 11
.head 6 +  Else If sHexChar = 'C'
.head 7 -  Set nDecChar = 12
.head 6 +  Else If sHexChar = 'D'
.head 7 -  Set nDecChar = 13
.head 6 +  Else If sHexChar = 'E'
.head 7 -  Set nDecChar = 14
.head 6 +  Else If sHexChar = 'F'
.head 7 -  Set nDecChar = 15
.head 6 +  Else 
.head 7 -  Set nDecChar = SalStrToNumber( sHexChar )
.head 6 -  !
.head 6 -  Set sBinChar = ''
.head 6 +  While nDecChar > 0
.head 7 +  If SalNumberMod( nDecChar, 2 ) = 0
.head 8 -  Set sBinChar = '0' || sBinChar
.head 7 +  Else 
.head 8 -  Set sBinChar = '1' || sBinChar
.head 7 -  Set nDecChar = SalNumberTruncate( nDecChar / 2, 4, 0 )
.head 6 -  !
.head 6 -  Call StringStartPad( sBinChar, '0', 4 )
.head 6 -  Set sBin = sBin || sBinChar
.head 6 -  Set nPos = nPos + 1
.head 5 -  Return sBin
.head 3 -  ! to Here
.head 3 +  ! Function: CreateCustStructure0
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Boolean: bOk
.head 5 -  String: sPath
.head 5 -  String: saFolders[*]
.head 5 -  String: sCustState
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 -  Set sPath = OurGetIniFileParameter( 'GENERAL', 'FilingCabinet', 'C:\\TEMP' )
.head 5 -  Set saFolders[ 0 ] = 'Filing Cabinet'
.head 5 -  Set saFolders[ 1 ] = ''
.head 5 +  If CreateFolders( sPath, saFolders )
.head 6 -  Set saFolders[ 0 ] = 'Customers'
.head 6 -  Set saFolders[ 1 ] = 'Suppliers'
.head 6 -  Set saFolders[ 2 ] = 'Templates'
.head 6 -  Set saFolders[ 3 ] = ''
.head 6 +  If CreateFolders( sPath || '\\Filing Cabinet', saFolders )
.head 7 -  ! Parent 'Customers'
.head 7 -  Set saFolders[ 0 ] = 'NSW'
.head 7 -  Set saFolders[ 1 ] = 'NT'
.head 7 -  Set saFolders[ 2 ] = 'QLD'
.head 7 -  Set saFolders[ 3 ] = 'SA'
.head 7 -  Set saFolders[ 4 ] = 'TAS'
.head 7 -  Set saFolders[ 5 ] = 'VIC'
.head 7 -  Set saFolders[ 6 ] = 'WA'
.head 7 -  Set saFolders[ 7 ] = ''
.head 7 +  If CreateFolders( sPath || '\\Filing Cabinet' || '\\Customers', saFolders )
.head 8 -  Set saFolders[ 0 ] = SalNumberToStrX( nCustNo, 0 )
.head 8 -  Set saFolders[ 1 ] = ''
.head 8 -  Set sCustState = GetCustNoState( nCustNo )
.head 8 +  If CreateFolders( sPath || '\\Filing Cabinet' || '\\Customers' || '\\' || sCustState, saFolders )
.head 9 -  Set saFolders[ 0 ] = 'Acknowledgments'
.head 9 -  Set saFolders[ 1 ] = 'Confirmations'
.head 9 -  Set saFolders[ 2 ] = 'Correspondence'
.head 9 -  Set saFolders[ 3 ] = 'Credit Notes'
.head 9 -  Set saFolders[ 4 ] = 'Invoices'
.head 9 -  Set saFolders[ 5 ] = 'NPAs'
.head 9 -  Set saFolders[ 6 ] = 'Quotes'
.head 9 -  Set saFolders[ 7 ] = 'Receipts'
.head 9 -  Set saFolders[ 8 ] = 'Statements'
.head 9 -  Set saFolders[ 9 ] = ''
.head 9 +  If NOT CreateFolders( sPath || '\\Filing Cabinet' || '\\Customers' || '\\' || sCustState || '\\' || SalNumberToStrX( nCustNo, 0 ), saFolders )
.head 10 -  Set bOk = FALSE
.head 8 +  Else 
.head 9 -  Set bOk = FALSE
.head 7 +  Else 
.head 8 -  Set bOk = FALSE
.head 7 -  ! Parent Templates
.head 7 -  Set saFolders[ 0 ] = 'Quote'
.head 7 -  Set saFolders[ 1 ] = ''
.head 7 +  If NOT CreateFolders( sPath || '\\Filing Cabinet' || '\\Templates', saFolders )
.head 8 -  Set bOk = FALSE
.head 6 +  Else 
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 +  ! Function: CreateCustStructure
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Boolean: bOk
.head 5 -  String: sPath
.head 5 -  String: saFolders[*]
.head 5 -  String: sCustState
.head 4 +  Actions 
.head 5 -  Call OurWaitCursor( TRUE )
.head 5 -  Set bOk = TRUE
.head 5 -  Set sPath = OurGetIniFileParameter( 'GENERAL', 'FilingCabinet', 'C:\\TEMP' )
.head 5 -  Set saFolders[ 0 ] = 'Filing'
.head 5 -  Set saFolders[ 1 ] = ''
.head 5 +  If CreateFolders( sPath, saFolders )
.head 6 -  Set saFolders[ 0 ] = 'Customer'
.head 6 -  Set saFolders[ 1 ] = 'Supplier'
.head 6 -  Set saFolders[ 2 ] = 'Template'
.head 6 -  Set saFolders[ 3 ] = ''
.head 6 +  If CreateFolders( sPath || '\\Filing', saFolders )
.head 7 -  ! Parent 'Customer'
.head 7 -  Set saFolders[ 0 ] = 'NSW'
.head 7 -  Set saFolders[ 1 ] = 'NT'
.head 7 -  Set saFolders[ 2 ] = 'QLD'
.head 7 -  Set saFolders[ 3 ] = 'SA'
.head 7 -  Set saFolders[ 4 ] = 'TAS'
.head 7 -  Set saFolders[ 5 ] = 'VIC'
.head 7 -  Set saFolders[ 6 ] = 'WA'
.head 7 -  Set saFolders[ 7 ] = ''
.head 7 +  If CreateFolders( sPath || '\\Filing' || '\\Customer', saFolders )
.head 8 -  Set saFolders[ 0 ] = SalNumberToStrX( nCustNo, 0 )
.head 8 -  Set saFolders[ 1 ] = ''
.head 8 -  Set sCustState = GetCustNoState( nCustNo )
.head 8 +  If CreateFolders( sPath || '\\Filing' || '\\Customer' || '\\' || sCustState, saFolders )
.head 9 -  Set saFolders[ 0 ] = 'Acknow'
.head 9 -  Set saFolders[ 1 ] = 'Confirm'
.head 9 -  Set saFolders[ 2 ] = 'Corresp'
.head 9 -  Set saFolders[ 3 ] = 'CRNotes'
.head 9 -  Set saFolders[ 4 ] = 'Invoices'
.head 9 -  Set saFolders[ 5 ] = 'NPAs'
.head 9 -  Set saFolders[ 6 ] = 'Quotes'
.head 9 -  Set saFolders[ 7 ] = 'Receipts'
.head 9 -  Set saFolders[ 8 ] = 'Statemnt'
.head 9 -  Set saFolders[ 9 ] = 'PRCs'
.head 9 -  Set saFolders[ 10 ] = 'Other'
.head 9 -  Set saFolders[ 11 ] = 'TAs'
.head 9 -  Set saFolders[ 12 ] = ''
.head 9 +  If NOT CreateFolders( sPath || '\\Filing' || '\\Customer' || '\\' || sCustState || '\\' || SalNumberToStrX( nCustNo, 0 ), saFolders )
.head 10 -  Set bOk = FALSE
.head 8 +  Else 
.head 9 -  Set bOk = FALSE
.head 7 +  Else 
.head 8 -  Set bOk = FALSE
.head 7 -  ! Parent Template
.head 7 -  Set saFolders[ 0 ] = 'Quote'
.head 7 -  Set saFolders[ 1 ] = ''
.head 7 +  If NOT CreateFolders( sPath || '\\Filing' || '\\Template', saFolders )
.head 8 -  Set bOk = FALSE
.head 6 +  Else 
.head 7 -  Set bOk = FALSE
.head 5 +  Else 
.head 6 -  Set bOk = FALSE
.head 5 -  Call OurWaitCursor( FALSE )
.head 5 -  Return bOk
.head 3 -  !
.head 3 +  ! Function: CreateFolders
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  Boolean: 
.head 4 +  Parameters 
.head 5 -  String: sPath
.head 5 -  String: saFolders[*]
.head 5 -  ! null terminated array
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Boolean: bOk
.head 5 -  Boolean: bCreate
.head 5 -  String: saDirs[*]
.head 5 -  Number: nCount
.head 4 +  Actions 
.head 5 -  Set bOk = TRUE
.head 5 -  Set nCount = VisDosEnumDirs( sPath||'\\*.*', saDirs )
.head 5 +  If nCount > 0
.head 6 -  Set nCount = 0
.head 6 +  While saFolders[ nCount ] != '' AND bOk
.head 7 +  If VisArrayFindString( saDirs, saFolders[ nCount ] ) < 0
.head 8 -  Set bOk = SalFileCreateDirectory( sPath || '\\' || saFolders[ nCount ] )
.head 7 -  Set nCount = nCount + 1
.head 5 +  Else 
.head 6 -  Set nCount = 0
.head 6 +  While saFolders[ nCount ] != '' AND bOk
.head 7 -  Set bOk = SalFileCreateDirectory( sPath || '\\' || saFolders[ nCount ] )
.head 7 -  Set nCount = nCount + 1
.head 5 -  Return bOk
.head 3 +  ! Function: GetCustNoState
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Number: nCustNo
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sState
.head 4 +  Actions 
.head 5 +  If nCustNo >= 080000 AND nCustNo <= 099999
.head 6 -  Set sState = 'NT'
.head 5 +  Else If nCustNo >= 200000 AND nCustNo <= 299999
.head 6 -  Set sState = 'NSW'
.head 5 +  Else If nCustNo >= 300000 AND nCustNo <= 399999
.head 6 -  Set sState = 'VIC'
.head 5 +  Else If nCustNo >= 400000 AND nCustNo <= 499999
.head 6 -  Set sState = 'QLD'
.head 5 +  Else If nCustNo >= 500000 AND nCustNo <= 599999
.head 6 -  Set sState = 'SA'
.head 5 +  Else If nCustNo >= 600000 AND nCustNo <= 699999
.head 6 -  Set sState = 'WA'
.head 5 +  Else If nCustNo >= 700000 AND nCustNo <= 799999
.head 6 -  Set sState = 'TAS'
.head 5 +  Else 
.head 6 -  Set sState = 'OS'
.head 5 -  Return sState
.head 3 -  ! Below Functions have been included in Strings.apd
.head 3 +  ! Function: StripOutFileName
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sFullPathFileName
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sLast
.head 5 -  String: sCurrent
.head 5 -  Number: nPos
.head 5 -  String: sChar
.head 4 +  Actions 
.head 5 -  Set sCurrent = ''
.head 5 -  ! replace the " \ " with " ~ " because SalStrScan has problems.
.head 5 -  Set nPos = 0
.head 5 +  While nPos < SalStrLength( sFullPathFileName )
.head 6 -  Set sChar = SalStrMidX( sFullPathFileName, nPos, 1 )
.head 6 +  If sChar = '\\'
.head 7 -  Set sChar = '~'
.head 6 -  Set sCurrent = sCurrent || sChar
.head 6 -  Set nPos = nPos + 1
.head 5 -  !
.head 5 -  Set sLast = sCurrent
.head 5 -  Set sCurrent = GetStringBetweenCharMarks( sCurrent, '~', '.' )
.head 5 +  While sLast != sCurrent
.head 6 -  Set sLast = sCurrent
.head 6 -  Set sCurrent = GetStringBetweenCharMarks( sCurrent, '~', '.' )
.head 5 -  Return sCurrent
.head 3 +  ! Function: StringStartPad
.head 4 -  Description: 
.head 4 -  Returns 
.head 4 +  Parameters 
.head 5 -  Receive String: sSource  
.head 5 -  String: sPad  
.head 5 -  Number: nLength  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nActualLength  
.head 4 +  Actions 
.head 5 -  Set nActualLength = SalStrLength( sSource )
.head 5 +  While nActualLength < nLength
.head 6 -  Set sSource = sPad || sSource
.head 6 -  Set nActualLength = SalStrLength( sSource )
.head 3 +  ! Function: LastStrTwoDigitsFromYear
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Number: nYear
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Return SalStrRightX( SalNumberToStrX( nYear, 0 ), 2 )
.head 3 +  ! Function: StringStartPadX
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sSource  
.head 5 -  String: sPad  
.head 5 -  Number: nLength  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  String: sTmp
.head 4 +  Actions 
.head 5 -  Set sTmp = sSource
.head 5 -  Call StringStartPad( sTmp, sPad, nLength )
.head 5 -  Return sTmp
.head 3 +  ! Function: GetStrJulianDate
.head 4 -  Description: 
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  Date/Time: dtDate
.head 4 -  Static Variables 
.head 4 -  Local variables 
.head 4 +  Actions 
.head 5 -  Return SalNumberToStrX( dtDate - SalDateYearBegin( dtDate ) + 1, 0 ) || SalStrMidX( SalNumberToStrX( SalDateYear( dtDate ), 0 ), 3, 1 )
.head 3 +  ! Function: GetStringBetweenCharMarks
.head 4 -  Description: Returns a string encapsulated withing another string by starting and ending characters
.head 4 +  Returns 
.head 5 -  String: 
.head 4 +  Parameters 
.head 5 -  String: sInputStr  
.head 5 -  String: sStartCharacter  
.head 5 -  String: sEndCharacter  
.head 4 -  Static Variables 
.head 4 +  Local variables 
.head 5 -  Number: nStartCharPos  
.head 5 -  Number: nEndCharPos  
.head 5 -  String: sTmpInputStr  
.head 5 -  String: sOutputStr  
.head 4 +  Actions 
.head 5 -  Set nStartCharPos = SalStrScan( sInputStr, sStartCharacter )
.head 5 +  If nStartCharPos >= 0
.head 6 -  Set sTmpInputStr = SalStrRightX( sInputStr, SalStrLength( sInputStr ) - nStartCharPos - SalStrLength( sStartCharacter ) )
.head 6 -  Set nEndCharPos = SalStrScan( sTmpInputStr, sEndCharacter )
.head 6 +  If nEndCharPos < 0
.head 7 -  Set nEndCharPos = SalStrLength( sTmpInputStr )
.head 6 -  Set sOutputStr = SalStrMidX( sInputStr, nStartCharPos + SalStrLength( sStartCharacter ), nEndCharPos )
.head 5 +  Else 
.head 6 -  Set nEndCharPos = SalStrScan( sInputStr, sEndCharacter )
.head 6 +  If nEndCharPos >= 0
.head 7 -  Set sOutputStr = SalStrLeftX( sInputStr, nEndCharPos )
.head 6 +  Else 
.head 7 -  Set sOutputStr = sInputStr
.head 5 -  Return sOutputStr
.head 2 +  Class Definitions
.head 3 +  Functional Class: strStack
.head 4 -  Description:
.head 4 -  Derived From
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  String: Strings[*]
.head 5 -  Number: nLast
.head 4 +  Functions
.head 5 +  Function: StackInit
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set Strings[0] = ''
.head 7 -  Set Strings[1] = ''
.head 7 -  Set nLast = -1
.head 7 -  Return TRUE
.head 5 +  Function: StackFind
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sStrToFind
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: nPos
.head 7 -  Boolean: bFound
.head 6 +  Actions
.head 7 +  If sStrToFind = ''
.head 8 -  Return FALSE
.head 7 +  Else
.head 8 -  ! Set nPos = 0
.head 8 -  ! Set bFound = FALSE
.head 8 +  ! While nPos <= nLast AND NOT bFound
.head 9 +                     If Strings[ nPos ] = sStrToFind
.head 10 -                     Set bFound = TRUE
.head 9 -                     Set nPos = nPos + 1
.head 8 -  ! Return bFound
.head 8 -  Return StrArrayFind( Strings, nLast, sStrToFind, nPos )
.head 5 +  Function: StackPush
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sStr
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If sStr != ''
.head 8 -  Set nLast = nLast + 1
.head 8 -  Set Strings[ nLast ] = sStr
.head 8 -  Set Strings[ nLast + 1 ] = ''
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  Function: StackPushUnique
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sStr
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If StackFind( sStr )
.head 8 -  Return FALSE
.head 7 +  Else
.head 8 -  Call StackPush( sStr )
.head 8 -  Return TRUE
.head 5 +  Function: StackPop
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Receive String: sStr
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If nLast >= 0
.head 8 -  Set sStr = Strings[ nLast ]
.head 8 -  Set Strings[ nLast ] = ''
.head 8 -  Set nLast = nLast - 1
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  Function: StackMakeList
.head 6 -  Description: sSeparator : string used as the list string separator
                       eg: jan, michelle, dani the comma is the separator
  sQuoteType : string used as the type of character for the quotes around the strings.
                         eg: "jan", "michelle", "dani" the double quote is the quote type character
                         note use sQueryType of blank to obtain a non quoted string list.
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  String: sSeparator
.head 7 -  String: sQuoteType
.head 7 -  Receive String: sStringList
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Call MakeStringList( Strings, sSeparator, sQuoteType, sStringList )
.head 5 +  Function: StackCount
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return nLast
.head 3 +  Functional Class: numStack
.head 4 -  Description:
.head 4 -  Derived From
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  Number: Numbers[*]
.head 5 -  Number: nLast
.head 4 +  Functions
.head 5 +  Function: StackInit
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set Numbers[0] = NUMBER_Null
.head 7 -  Set Numbers[1] = NUMBER_Null
.head 7 -  Set nLast = -1
.head 7 -  Return TRUE
.head 5 +  Function: StackFind
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nNumToFind
.head 6 -  Static Variables
.head 6 +  Local variables
.head 7 -  Number: nPos
.head 7 -  Boolean: bFound
.head 6 +  Actions
.head 7 +  If nNumToFind = NUMBER_Null
.head 8 -  Return FALSE
.head 7 +  Else
.head 8 -  ! Set nPos = 0
.head 8 -  ! Set bFound = FALSE
.head 8 +  ! While nPos <= nLast AND NOT bFound
.head 9 +                     If Numbers[ nPos ] = nNumToFind
.head 10 -                     Set bFound = TRUE
.head 9 -                     Set nPos = nPos + 1
.head 8 -  ! Return bFound
.head 8 -  Return NumArrayFind( Numbers, nLast, nNumToFind, nPos )
.head 5 +  Function: StackPush
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nNum
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If nNum != NUMBER_Null
.head 8 -  Set nLast = nLast + 1
.head 8 -  Set Numbers[ nLast ] = nNum
.head 8 -  Set Numbers[ nLast + 1 ] = NUMBER_Null
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  Function: StackPushUnique
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nNum
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If StackFind( nNum )
.head 8 -  Return FALSE
.head 7 +  Else
.head 8 -  Call StackPush( nNum )
.head 8 -  Return TRUE
.head 5 +  Function: StackPop
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Receive Number: nNum
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 +  If nLast >= 0
.head 8 -  Set nNum = Numbers[ nLast ]
.head 8 -  Set Numbers[ nLast ] = NUMBER_Null
.head 8 -  Set nLast = nLast - 1
.head 8 -  Return TRUE
.head 7 +  Else
.head 8 -  Return FALSE
.head 5 +  Function: StackMakeList
.head 6 -  Description: sSeparator : string used as the list string separator
                       eg: jan, michelle, dani the comma is the separator
  sQuoteType : string used as the type of character for the quotes around the strings.
                         eg: "jan", "michelle", "dani" the double quote is the quote type character
                         note use sQueryType of blank to obtain a non quoted string list.
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  Number: nPrecision
.head 7 -  String: sSeparator
.head 7 -  String: sQuoteType
.head 7 -  Receive String: sStringList
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Call MakeNumberList( Numbers, nPrecision, sSeparator, sQuoteType, sStringList )
.head 5 +  Function: StackCount
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return nLast
.head 3 +  Functional Class: clsStrFileHandle
.head 4 -  Description:
.head 4 -  Derived From
.head 4 -  Class Variables
.head 4 +  Instance Variables
.head 5 -  File Handle: hFileHandle
.head 5 -  String: sFileName
.head 5 -  ! If nFileType = NUMBER_Null then Default OF_Create | OF_ReadWrite | OF_Text is assumed
.head 5 -  Number: nFileType
.head 5 -  ! if nLineSize = NUMBER_Null then Default nLineSize = 1024
.head 5 -  Number: nLineSize
.head 4 +  Functions
.head 5 +  Function: Setup
.head 6 -  Description:
.head 6 -  Returns
.head 6 +  Parameters
.head 7 -  String: sNewFileName
.head 7 -  Number: nNewFileType
.head 7 -  Number: nNewLineSize
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Set sFileName = sNewFileName
.head 7 +  If nNewFileType = NUMBER_Null
.head 8 -  Set nNewFileType = OF_Create | OF_ReadWrite | OF_Text
.head 7 +  If nNewLineSize = NUMBER_Null
.head 8 -  Set nNewLineSize = 1024
.head 7 -  Set nFileType = nNewFileType
.head 7 -  Set nLineSize = nNewLineSize
.head 5 +  Function: Open
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalFileOpen( hFileHandle, sFileName, nFileType )
.head 5 +  Function: Close
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalFileClose( hFileHandle )
.head 5 +  Function: Write
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  String: sString
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalFilePutStr( hFileHandle, sString )
.head 5 +  Function: Read
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Receive String: sString
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  ! Return SalFileGetStr( hFileHandle, sString, nLineSize )
.head 7 -  Return SalFileRead( hFileHandle, sString, nLineSize )
.head 5 +  Function: ReadLine
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Receive String: sString
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalFileGetStr( hFileHandle, sString, nLineSize )
.head 5 +  Function: Seek
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Boolean:
.head 6 +  Parameters
.head 7 -  Number: nBytes
.head 7 -  Number: nPosition
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalFileSeek( hFileHandle, nBytes, nPosition )
.head 5 +  Function: Tell
.head 6 -  Description:
.head 6 +  Returns
.head 7 -  Number:
.head 6 -  Parameters
.head 6 -  Static Variables
.head 6 -  Local variables
.head 6 +  Actions
.head 7 -  Return SalFileTell( hFileHandle )
.head 2 +  Default Classes
.head 3 -  MDI Window:
.head 3 -  Form Window:
.head 3 -  Dialog Box:
.head 3 -  Table Window:
.head 3 -  Quest Window:
.head 3 -  Data Field:
.head 3 -  Spin Field:
.head 3 -  Multiline Field:
.head 3 -  Pushbutton:
.head 3 -  Radio Button:
.head 3 -  Check Box:
.head 3 -  Option Button:
.head 3 -  Child Table:
.head 3 -  Quest Child Window:
.head 3 -  List Box:
.head 3 -  Combo Box:
.head 3 -  Picture:
.head 3 -  Vertical Scroll Bar:
.head 3 -  Horizontal Scroll Bar:
.head 3 -  Column:
.head 3 -  Background Text:
.head 3 -  Group Box:
.head 3 -  Line:
.head 3 -  Frame:
.head 3 -  Custom Control:
.head 3 -  ActiveX:
.head 2 -  Application Actions
